/**
 * image-forensics.server.ts — deterministic, AI-independent tamper signals for
 * the D17 pipeline, run on the ORIGINAL uploaded bytes (before EXIF-strip +
 * re-encode, which would destroy exactly the compression history these checks
 * read). This is a SUPPORTING layer, never a sole hard gate: a strong signal
 * routes an attempt to manual review, it does not auto-reject — deterministic
 * forensics have real false positives (an honest user who merely cropped their
 * receipt in a photo app leaves editor metadata too), so the safe outcome is
 * "a human looks", consistent with the rest of the pipeline's heuristic checks.
 *
 * Two independent signals:
 *  1. Metadata signatures — editor apps (Photoshop/GIMP/…) and AI generators
 *     (Midjourney/Stable Diffusion/DALL·E/C2PA) leave recognizable ASCII
 *     markers in EXIF / XMP / PNG text chunks. A genuine phone screenshot of a
 *     banking app has none. This is the higher-precision signal.
 *  2. Error-Level Analysis (ELA) hotspot — re-saving a JPEG re-quantizes it;
 *     a region pasted in from a different source resaves with a markedly
 *     different error level than its surroundings. A high max-block-to-mean
 *     ratio flags localized editing. Weaker/approximate (and near-meaningless
 *     for a lossless PNG original), so it's weighted low.
 *
 * Never throws — any failure returns a zero-suspicion result so a forensics
 * bug can never block a legitimate payment.
 */
import sharp from "sharp";

export interface ForensicsResult {
  /** 0 (looks like an untouched screenshot) … 100 (strong tamper signals). */
  score: number;
  flags: string[];
  details: Record<string, unknown>;
}

// Specific, low-false-positive ASCII markers only (avoid short/common strings).
const EDITOR_SIGNATURES = [
  "adobe photoshop", "photoshop", "gimp", "adobe lightroom", "pixlr",
  "picsart", "paint.net", "affinity photo", "affinity designer", "snapseed", "facetune",
];
const AI_SIGNATURES = [
  "midjourney", "stable diffusion", "stablediffusion", "dall-e", "dall·e",
  "adobe firefly", "leonardo.ai", "c2pa", "contentcredentials", "generated by ai",
];

function scanSignatures(buffer: Buffer): { editor: string[]; ai: string[] } {
  // Signatures can live anywhere (EXIF near the start, PNG tEXt/iTXt chunks
  // near the end), so scan the whole file as latin1. Cheap enough at D17
  // volumes; runs once per screenshot.
  const text = buffer.toString("latin1").toLowerCase();
  return {
    editor: EDITOR_SIGNATURES.filter((s) => text.includes(s)),
    ai: AI_SIGNATURES.filter((s) => text.includes(s)),
  };
}

const ELA_SIZE = 256;
const ELA_GRID = 8;

/** Approximate block-based ELA on a normalized grayscale copy. Returns the
 * ratio of the worst 32×32 block's mean re-save error to the whole-image mean
 * error — high when one region was edited/pasted. */
async function computeElaHotspot(buffer: Buffer): Promise<{ ratio: number; maxBlock: number; mean: number }> {
  const base = sharp(buffer, { failOn: "none" }).removeAlpha().resize(ELA_SIZE, ELA_SIZE, { fit: "fill" }).grayscale();
  const orig = await base.clone().raw().toBuffer();
  const resavedJpeg = await base.clone().jpeg({ quality: 90 }).toBuffer();
  const resaved = await sharp(resavedJpeg).removeAlpha().resize(ELA_SIZE, ELA_SIZE, { fit: "fill" }).grayscale().raw().toBuffer();

  const blockSums = new Array(ELA_GRID * ELA_GRID).fill(0);
  const blockCounts = new Array(ELA_GRID * ELA_GRID).fill(0);
  const blockPx = ELA_SIZE / ELA_GRID;
  let total = 0;
  const n = ELA_SIZE * ELA_SIZE;
  for (let y = 0; y < ELA_SIZE; y++) {
    for (let x = 0; x < ELA_SIZE; x++) {
      const i = y * ELA_SIZE + x;
      const d = Math.abs(orig[i] - resaved[i]);
      total += d;
      const b = Math.floor(y / blockPx) * ELA_GRID + Math.floor(x / blockPx);
      blockSums[b] += d;
      blockCounts[b] += 1;
    }
  }
  const mean = total / n;
  const blockMeans = blockSums.map((s, i) => (blockCounts[i] ? s / blockCounts[i] : 0));
  const maxBlock = Math.max(...blockMeans);
  return { ratio: maxBlock / (mean + 1), maxBlock, mean };
}

export async function analyzeImageForensics(originalBuffer: Buffer): Promise<ForensicsResult> {
  const flags: string[] = [];
  let score = 0;
  const details: Record<string, unknown> = {};

  try {
    const sigs = scanSignatures(originalBuffer);
    if (sigs.ai.length > 0) {
      score += 60;
      flags.push("ai_generation_metadata");
      details.aiSignatures = sigs.ai;
    }
    if (sigs.editor.length > 0) {
      score += 40;
      flags.push("editing_software_metadata");
      details.editorSignatures = sigs.editor;
    }
  } catch (e) {
    details.signatureScanError = String(e);
  }

  try {
    const ela = await computeElaHotspot(originalBuffer);
    details.ela = ela;
    if (ela.ratio > 4.5 && ela.maxBlock > 8) {
      score += 25;
      flags.push("ela_localized_anomaly");
    } else if (ela.ratio > 3 && ela.maxBlock > 6) {
      score += 12;
      flags.push("ela_elevated");
    }
  } catch (e) {
    details.elaError = String(e);
  }

  return { score: Math.min(100, score), flags, details };
}

/** Merge the forensics of the two screenshots into a single worst-case signal
 * the rule engine consumes (max score, union of flags). */
export function combineForensics(a: ForensicsResult, b: ForensicsResult): ForensicsResult {
  return {
    score: Math.max(a.score, b.score),
    flags: Array.from(new Set([...a.flags, ...b.flags])),
    details: { screenshot1: a.details, screenshot2: b.details },
  };
}
