/**
 * Runtime lookup for the pre-generated fixed-phrase audio library —
 * separate from generateLibrary.ts (which WRITES the library, offline,
 * once) so the live exam path only ever needs a cheap manifest read, never
 * touches ElevenLabs for these categories. Populated for real as of
 * 2026-10-03 (see generateLibrary.ts's header for the account-tier
 * restriction that blocked this until then) — muendlichVoiceSession.ts
 * still falls back safely to live TTS if a manifest/voice/category
 * combination is ever missing (e.g. a newly added voice before the next
 * `npm run generate-phrase-library` run).
 */
import { readFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import type { PhraseAudioAsset, LibraryCategory } from "./phraseTypes.js";
import { assignPhraseStyle } from "./voiceStyle.js";
import { pickVariant } from "./phraseSelection.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const LIBRARY_ROOT = path.resolve(__dirname, "../../../audio-library");

let cachedManifest: PhraseAudioAsset[] | null = null;

async function loadManifest(): Promise<PhraseAudioAsset[]> {
  if (cachedManifest) return cachedManifest;
  try {
    const raw = await readFile(path.join(LIBRARY_ROOT, "manifest.json"), "utf8");
    cachedManifest = JSON.parse(raw) as PhraseAudioAsset[];
  } catch {
    // No manifest yet (library never generated, or wrong working directory)
    // — treated as "library empty," not a fatal error. Cached as [] so a
    // missing file doesn't mean re-reading disk on every single call.
    cachedManifest = [];
  }
  return cachedManifest;
}

/** Invalidate the in-memory cache — used by library-related tests so they
 * can point at a fixture manifest without restarting the process. */
export function _resetManifestCacheForTests(): void {
  cachedManifest = null;
}

/** Exact lookup of one pre-generated clip by phrase id + voice (no random
 * variant selection) — used for "scripted_lead" clips, where the variant was
 * already chosen upstream (examinerPhrases.ts) and we need ITS lead audio. */
export async function findLibraryAssetById(
  category: LibraryCategory,
  voiceId: string,
  phraseId: string,
): Promise<{ asset: PhraseAudioAsset; absolutePath: string } | null> {
  const manifest = await loadManifest();
  const asset = manifest.find((a) => a.category === category && a.voiceId === voiceId && a.phraseId === phraseId);
  return asset ? { asset, absolutePath: path.join(LIBRARY_ROOT, asset.pcmPath) } : null;
}

export async function pickLibraryAsset(
  category: LibraryCategory,
  voiceId: string,
  topic?: string,
): Promise<{ asset: PhraseAudioAsset; absolutePath: string } | null> {
  const manifest = await loadManifest();
  const forVoice = manifest.filter((a) => a.category === category && a.voiceId === voiceId && (topic === undefined || a.topic === topic));
  if (forVoice.length === 0) return null;

  const chosen = pickVariant(
    `library_${category}_${voiceId}_${topic ?? ""}`,
    forVoice.map((a) => ({ id: a.phraseId, style: a.style, asset: a })),
    assignPhraseStyle(voiceId),
  );
  return { asset: chosen.asset, absolutePath: path.join(LIBRARY_ROOT, chosen.asset.pcmPath) };
}

// ---------------------------------------------------------------------------
// 1:1 tutor library (owner 2026-10-09): clips synthesized with eleven_v4_turbo in the professional ("formal") register, kept in their own
// folder + manifest so the 2:1 exam room's Flash-timbre library above is never touched. Generated by generateTutorLibrary.ts.
// ---------------------------------------------------------------------------
const TUTOR_V4_ROOT = path.join(LIBRARY_ROOT, "tutor-v4");
let cachedTutorManifest: PhraseAudioAsset[] | null = null;

async function loadTutorManifest(): Promise<PhraseAudioAsset[]> {
  if (cachedTutorManifest) return cachedTutorManifest;
  try {
    cachedTutorManifest = JSON.parse(await readFile(path.join(TUTOR_V4_ROOT, "manifest.json"), "utf8")) as PhraseAudioAsset[];
  } catch {
    cachedTutorManifest = []; // not generated yet -> callers fall back to speaking the line live
  }
  return cachedTutorManifest;
}

export function _resetTutorManifestCacheForTests(): void {
  cachedTutorManifest = null;
}

export async function findTutorV4Asset(
  category: "scripted_lead" | "exam_end",
  voiceId: string,
  phraseId: string,
): Promise<{ asset: PhraseAudioAsset; absolutePath: string } | null> {
  const manifest = await loadTutorManifest();
  const asset = manifest.find((a) => a.category === category && a.voiceId === voiceId && a.phraseId === phraseId);
  return asset ? { asset, absolutePath: path.join(TUTOR_V4_ROOT, asset.pcmPath) } : null;
}
