/**
 * Teil 1 presentation-prompt library — the question the examiner asks
 * BEFORE the candidate presents, one per (topic, drawn from this pool).
 * Replaces the previous exam_start design (which just announced "your
 * topic is X") with an actual, substantive, topic-specific PROMPT — this
 * is the core piece of the "Teil 1 should be mostly student speech"
 * redesign: the examiner asks ONE real question from here, then the
 * candidate does essentially all of the talking (up to 7,000-10,000
 * characters of their own speech, captured via STT, never TTS — see
 * whisperStt.ts).
 *
 * Fully topic-keyed, NAME-FREE (like fixedPhrases.ts's welcome/exam_end) —
 * so every question here is a true, pre-generatable audio-library asset:
 * generated ONCE per (question, voice), replayed forever, $0 ElevenLabs
 * cost at runtime once the library is generated (see generateLibrary.ts).
 *
 * Topic strings match muendlich_materials.title exactly (verified against
 * the live database this session — 7 real Teil-1 topics, confirmed, not
 * assumed): "Reise", "Buch", "Film", "Sportereignis", "Musikveranstaltung",
 * "Wichtige Person im Leben", "Wichtige Erfahrung".
 *
 * 50 questions per topic (350 total, 7 x 50) — the full requested library,
 * a real, reviewed, professionally-written batch, not template-generated
 * filler. Built across ten distinct QUESTION ANGLES per topic (personal
 * narrative, description + reasoning, opinion/evaluation, comparison,
 * preference + justification, hypothetical/planning, advice-giving,
 * impact/consequence, memory/reflection, future-oriented) so the variety is
 * structural, not just reworded repetition of one question type. The first
 * 15/topic were written and reviewed in an earlier pass; the remaining
 * 35/topic (grounded in the real per-topic sub-points, Redemittel, and
 * Premium-Wortschatz from the reference Sprechen-Teil1 material) complete
 * the set to the full 50/topic target.
 */
import type { PhraseStyle } from "./phraseTypes.js";

export interface Teil1Question {
  id: string;
  topic: string;
  style: PhraseStyle;
  text: string;
}

// Style assigned round-robin (formal, warm, calm, formal, warm, calm, ...)
// across each topic's 50 -- same three-bucket system as fixedPhrases.ts, so
// a session's assigned voice (see voiceStyle.ts) draws from a
// register-consistent subset here too.
const STYLE_CYCLE: PhraseStyle[] = ["formal", "warm", "calm"];
function withStyles(topic: string, idPrefix: string, texts: string[]): Teil1Question[] {
  return texts.map((text, i) => ({
    id: `${idPrefix}_${String(i + 1).padStart(2, "0")}`,
    topic,
    style: STYLE_CYCLE[i % STYLE_CYCLE.length],
    text,
  }));
}

const REISE = withStyles("Reise", "teil1_q_reise", [
  "Erzählen Sie von einer Reise, die Sie besonders beeindruckt hat. Was hat diese Reise so unvergesslich gemacht?",
  "Beschreiben Sie ein Reiseziel, das Sie schon einmal besucht haben. Was hat Ihnen dort am besten gefallen?",
  "Was ist Ihre wichtigste Erinnerung an eine Reise aus Ihrer Kindheit?",
  "Vergleichen Sie zwei Orte, die Sie bereist haben. Worin unterscheiden sie sich?",
  "Was halten Sie von Pauschalreisen im Vergleich zu individuell geplanten Reisen?",
  "Welche Art zu reisen bevorzugen Sie, allein oder in Gesellschaft, und warum?",
  "Wenn Sie eine Reise völlig frei planen könnten, wohin würden Sie fahren und weshalb?",
  "Was würden Sie jemandem empfehlen, der zum ersten Mal ein fremdes Land bereist?",
  "Wie hat eine bestimmte Reise Ihre Sichtweise auf die Welt verändert?",
  "Was möchten Sie in Zukunft noch bereisen, und warum reizt Sie gerade dieser Ort?",
  "Beschreiben Sie eine Reise, die nicht so verlaufen ist, wie Sie es geplant hatten.",
  "Welche Rolle spielt Reisen in Ihrem Leben, und wie oft nehmen Sie sich dafür Zeit?",
  "Erzählen Sie von einer Begegnung, die Sie während einer Reise besonders geprägt hat.",
  "Was ist für Sie wichtiger auf Reisen, Erholung oder neue Erfahrungen? Begründen Sie Ihre Antwort.",
  "Beschreiben Sie, wie sich Ihre Vorstellung von einer idealen Reise im Laufe der Zeit verändert hat.",
  "Beschreiben Sie eine Reise, bei der Sie eine völlig fremde Kultur kennengelernt haben. Was war für Sie am ungewöhnlichsten?",
  "Was halten Sie von Fernreisen im Vergleich zu Kurztrips in der näheren Umgebung?",
  "Welche Vorbereitungen treffen Sie normalerweise, bevor Sie in den Urlaub fahren?",
  "Erzählen Sie von einer Reise, auf der Sie sich zunächst unsicher gefühlt haben, sich das aber im Laufe der Zeit gelegt hat.",
  "Was wäre für Sie das perfekte Reiseziel, wenn Geld keine Rolle spielen würde?",
  "Wie hat sich Ihre Art zu reisen verändert, seit Sie älter geworden sind?",
  "Was würden Sie jemandem raten, der mit einem sehr knappen Budget verreisen möchte?",
  "Vergleichen Sie das Reisen mit dem Auto und das Reisen mit dem Zug. Was bevorzugen Sie?",
  "Erzählen Sie von einem Land, das Sie unbedingt noch bereisen möchten, und warum es Sie so reizt.",
  "Was war die größte Herausforderung, der Sie sich auf einer Reise stellen mussten?",
  "Wie wichtig ist es Ihnen, auf Reisen die Sprache des Landes zumindest ein wenig zu sprechen?",
  "Beschreiben Sie eine Reise, bei der das Wetter Ihre Pläne durcheinandergebracht hat.",
  "Was halten Sie von organisierten Gruppenreisen im Vergleich zum spontanen Reisen ohne festen Plan?",
  "Erzählen Sie, wie eine bestimmte Reise Ihr Verhältnis zu Ihrer eigenen Heimat verändert hat.",
  "Was ist Ihnen bei der Wahl einer Unterkunft im Urlaub am wichtigsten?",
  "Wenn Sie eine Reise mit einer Person Ihrer Wahl unternehmen könnten, wen würden Sie mitnehmen und warum?",
  "Was würden Sie jemandem empfehlen, der Heimweh hat, während er im Ausland unterwegs ist?",
  "Beschreiben Sie, wie Sie sich normalerweise nach einer langen Reise wieder an den Alltag gewöhnen.",
  "Was halten Sie von Reisen, bei denen man vor allem berühmte Sehenswürdigkeiten abklappert?",
  "Erzählen Sie von einem Moment auf einer Reise, in dem Sie sich besonders frei gefühlt haben.",
  "Wie beeinflusst es Ihrer Meinung nach eine Reise, wenn man die Landessprache gar nicht spricht?",
  "Was ist Ihnen wichtiger, ein Reiseziel gründlich kennenzulernen oder in kurzer Zeit möglichst viel zu sehen?",
  "Erzählen Sie, welche Rolle Fotos oder Erinnerungsstücke für Sie nach einer Reise spielen.",
  "Was halten Sie vom Massentourismus an beliebten Reisezielen?",
  "Beschreiben Sie eine Reise, die Sie ursprünglich gar nicht machen wollten, die sich aber als lohnenswert erwiesen hat.",
  "Was würden Sie jemandem raten, der zum ersten Mal allein verreist?",
  "Wie hat sich Ihr Blick auf andere Kulturen durch das Reisen verändert?",
  "Erzählen Sie von einem kulinarischen Erlebnis auf einer Reise, das Ihnen besonders in Erinnerung geblieben ist.",
  "Was ist für Sie der Unterschied zwischen Urlaub machen und wirklich reisen?",
  "Wenn Sie noch einmal an einen bereits besuchten Ort zurückkehren könnten, welchen würden Sie wählen und warum?",
  "Was halten Sie davon, den Urlaub hauptsächlich zum Ausruhen statt zum Aktivsein zu nutzen?",
  "Beschreiben Sie, wie sich eine Reise mit der Familie von einer Reise mit Freunden unterscheidet.",
  "Was möchten Sie von einer zukünftigen Reise vor allem mitnehmen, Erinnerungen, neue Fähigkeiten oder Entspannung?",
  "Erzählen Sie, wie eine Reise Ihnen geholfen hat, eine schwierige Zeit in Ihrem Leben zu verarbeiten.",
  "Was halten Sie von der Idee, ein Jahr lang zu reisen, statt fest an einem Ort zu leben?",
]);

const BUCH = withStyles("Buch", "teil1_q_buch", [
  "Erzählen Sie von einem Buch, das Sie besonders beeindruckt hat. Worum ging es darin?",
  "Beschreiben Sie eine Figur aus einem Buch, mit der Sie sich identifizieren konnten.",
  "Was halten Sie von gedruckten Büchern im Vergleich zu E-Books?",
  "Welche Art von Büchern lesen Sie am liebsten, und warum gerade diese?",
  "Erzählen Sie von einem Buch, das Sie schon als Kind besonders gerne gelesen haben.",
  "Vergleichen Sie zwei Bücher, die Sie gelesen haben. Worin unterscheiden sie sich inhaltlich?",
  "Was würden Sie jemandem empfehlen, der wieder mit dem Lesen anfangen möchte?",
  "Wie hat ein bestimmtes Buch Ihre Meinung zu einem Thema verändert?",
  "Welche Rolle spielt Lesen in Ihrem Alltag, und wie viel Zeit nehmen Sie sich dafür?",
  "Was ist Ihnen bei einem guten Buch wichtiger, eine spannende Handlung oder gut ausgearbeitete Charaktere?",
  "Beschreiben Sie ein Buch, das Sie enttäuscht hat, obwohl Sie sich viel davon erhofft hatten.",
  "Wenn Sie ein Buch schreiben könnten, worüber würde es handeln, und warum?",
  "Erzählen Sie, wie Sie normalerweise entscheiden, welches Buch Sie als Nächstes lesen.",
  "Was halten Sie von Verfilmungen bekannter Bücher, verändern sie die Geschichte zum Besseren oder Schlechteren?",
  "Was möchten Sie in Zukunft gerne einmal lesen, und weshalb interessiert Sie gerade dieses Thema?",
  "Beschreiben Sie ein Buch, das Ihre Sicht auf ein bestimmtes Thema komplett verändert hat.",
  "Was halten Sie von Hörbüchern im Vergleich zum klassischen Lesen?",
  "Welche Rolle haben Bücher in Ihrer Kindheit gespielt?",
  "Erzählen Sie von einem Buch, das Sie nicht zu Ende gelesen haben, und warum Sie es abgebrochen haben.",
  "Was wäre für Sie das ideale Buch für einen langen Urlaub?",
  "Wie hat sich Ihr Lesegeschmack im Laufe der Jahre verändert?",
  "Was würden Sie jemandem raten, der sich mit dem Lesen auf Deutsch schwertut?",
  "Vergleichen Sie Sachbücher und Romane. Was lesen Sie lieber, und warum?",
  "Erzählen Sie von einem Autor oder einer Autorin, dessen Werke Sie besonders schätzen.",
  "Was war das anspruchsvollste Buch, das Sie je gelesen haben?",
  "Wie wichtig ist es Ihnen, dass ein Buch ein Happy End hat?",
  "Beschreiben Sie ein Buch, das Sie zum Nachdenken über Ihr eigenes Leben gebracht hat.",
  "Was halten Sie von Buchclubs, in denen man gemeinsam über Bücher diskutiert?",
  "Erzählen Sie, wie ein bestimmtes Buch Ihnen in einer schwierigen Lebensphase geholfen hat.",
  "Was ist Ihnen bei der Wahl eines Buches wichtiger, Empfehlungen von Freunden oder Rezensionen?",
  "Wenn Sie eine literarische Figur persönlich treffen könnten, welche wäre das und warum?",
  "Was würden Sie jemandem empfehlen, der noch nie ein ganzes Buch auf Deutsch gelesen hat?",
  "Beschreiben Sie, wie sich Ihr Leseverhalten verändert hat, seit es Smartphones und soziale Medien gibt.",
  "Was halten Sie davon, Bücher zu lesen, die auf wahren Begebenheiten beruhen?",
  "Erzählen Sie von einem Buch, das in Ihrem Freundeskreis viel diskutiert wurde.",
  "Wie beeinflusst es Ihrer Meinung nach das Leseerlebnis, wenn man ein Buch in einer Fremdsprache liest?",
  "Was ist Ihnen wichtiger, ein Buch ganz für sich allein zu genießen oder darüber mit anderen zu sprechen?",
  "Erzählen Sie, an welchem Ort Sie am liebsten lesen und warum gerade dort.",
  "Was halten Sie von Bestsellerlisten, orientieren Sie sich daran bei der Buchauswahl?",
  "Beschreiben Sie ein Buch, das Sie überrascht hat, weil es ganz anders war, als Sie erwartet hatten.",
  "Was würden Sie einem Kind empfehlen, damit es Freude am Lesen entwickelt?",
  "Wie hat ein bestimmtes Buch Ihr Verhältnis zu einer anderen Kultur geprägt?",
  "Erzählen Sie von einem Zitat aus einem Buch, das Ihnen besonders im Gedächtnis geblieben ist.",
  "Was ist für Sie der größte Unterschied zwischen einem Buch und seiner Verfilmung?",
  "Wenn Sie mit einem Autor oder einer Autorin sprechen könnten, welche Frage würden Sie stellen?",
  "Was halten Sie davon, dass viele Menschen heute weniger Bücher lesen als früher?",
  "Beschreiben Sie, wie sich das Lesen eines Buches von dem Konsum von Kurzinhalten im Internet unterscheidet.",
  "Was möchten Sie sich für die Zukunft in Bezug auf Ihr Leseverhalten vornehmen?",
  "Erzählen Sie, wie ein Buch Ihnen geholfen hat, ein anderes Thema oder Fach besser zu verstehen.",
  "Was halten Sie von der Idee, jedes Jahr eine bestimmte Anzahl an Büchern lesen zu wollen?",
]);

const FILM = withStyles("Film", "teil1_q_film", [
  "Erzählen Sie von einem Film, der Sie besonders bewegt hat. Was genau hat Sie daran berührt?",
  "Beschreiben Sie einen Film, den Sie mehrmals gesehen haben. Was macht ihn für Sie so besonders?",
  "Was halten Sie von Filmen im Kino im Vergleich zum Streamen zu Hause?",
  "Welches Filmgenre bevorzugen Sie, und warum spricht es Sie besonders an?",
  "Vergleichen Sie zwei Filme desselben Genres. Welcher hat Sie mehr überzeugt, und weshalb?",
  "Was würden Sie jemandem empfehlen, der noch nie einen deutschen Film gesehen hat?",
  "Wie hat ein bestimmter Film Ihre Meinung zu einem gesellschaftlichen Thema beeinflusst?",
  "Erzählen Sie von einer Filmfigur, die Sie besonders inspiriert hat.",
  "Was ist Ihnen bei einem guten Film wichtiger, die Geschichte oder die visuelle Umsetzung?",
  "Beschreiben Sie einen Film, der Sie enttäuscht hat, obwohl die Kritiken gut waren.",
  "Wenn Sie einen Film drehen könnten, welches Thema würden Sie wählen, und warum?",
  "Was halten Sie von Fortsetzungen bekannter Filme, lohnen sie sich Ihrer Meinung nach meistens?",
  "Erzählen Sie, in welcher Situation Sie am liebsten einen Film schauen.",
  "Was möchten Sie sich in Zukunft gerne ansehen, und was interessiert Sie an diesem Film?",
  "Wie beeinflusst die Musik in einem Film Ihrer Meinung nach die Wirkung der Geschichte?",
  "Beschreiben Sie einen Film, der Ihre Meinung über ein historisches Ereignis verändert hat.",
  "Was halten Sie von Dokumentarfilmen im Vergleich zu Spielfilmen?",
  "Welche Rolle haben Filme in Ihrer Kindheit gespielt?",
  "Erzählen Sie von einem Film, den Sie abgebrochen haben, weil er Ihnen nicht gefallen hat.",
  "Was wäre für Sie der ideale Film für einen verregneten Sonntagnachmittag?",
  "Wie hat sich Ihr Filmgeschmack im Laufe der Jahre verändert?",
  "Was würden Sie jemandem raten, der sich für das deutsche Kino zu interessieren beginnt?",
  "Vergleichen Sie Filme mit Happy End und Filme mit offenem oder traurigem Ende. Was bevorzugen Sie?",
  "Erzählen Sie von einem Regisseur oder einer Regisseurin, dessen Filme Sie besonders schätzen.",
  "Was war der emotionalste Film, den Sie je gesehen haben?",
  "Wie wichtig ist Ihnen die Filmmusik für das gesamte Seherlebnis?",
  "Beschreiben Sie einen Film, der Sie zum Nachdenken über Ihr eigenes Leben gebracht hat.",
  "Was halten Sie davon, Filme gemeinsam mit anderen im Kino zu schauen statt allein zu Hause?",
  "Erzählen Sie, wie ein bestimmter Film Ihnen in einer schwierigen Lebensphase geholfen hat.",
  "Was ist Ihnen bei der Wahl eines Films wichtiger, Empfehlungen von Freunden oder Kritiken?",
  "Wenn Sie eine Filmfigur persönlich treffen könnten, welche wäre das und warum?",
  "Was würden Sie jemandem empfehlen, der noch nie einen fremdsprachigen Film mit Untertiteln gesehen hat?",
  "Beschreiben Sie, wie sich Ihr Sehverhalten verändert hat, seit es Streamingdienste gibt.",
  "Was halten Sie davon, Filme zu schauen, die auf wahren Begebenheiten beruhen?",
  "Erzählen Sie von einem Film, der in Ihrem Freundeskreis viel diskutiert wurde.",
  "Wie beeinflusst es Ihrer Meinung nach das Filmerlebnis, wenn man einen Film in einer Fremdsprache schaut?",
  "Was ist Ihnen wichtiger, einen Film ganz für sich allein zu genießen oder danach darüber zu sprechen?",
  "Erzählen Sie, unter welchen Umständen Sie am liebsten einen Film schauen.",
  "Was halten Sie von Filmpreisen wie dem Oscar, orientieren Sie sich daran bei der Filmauswahl?",
  "Beschreiben Sie einen Film, der Sie überrascht hat, weil er ganz anders war, als Sie erwartet hatten.",
  "Was würden Sie einem Kind empfehlen, damit es Freude am Filmschauen entwickelt, ohne zu viel Zeit vor dem Bildschirm zu verbringen?",
  "Wie hat ein bestimmter Film Ihr Verständnis für eine andere Kultur geprägt?",
  "Erzählen Sie von einer Filmszene, die Ihnen besonders im Gedächtnis geblieben ist.",
  "Was ist für Sie der größte Unterschied zwischen einem Film und der Vorlage, auf der er beruht?",
  "Wenn Sie mit einem Schauspieler oder einer Schauspielerin sprechen könnten, welche Frage würden Sie stellen?",
  "Was halten Sie davon, dass heute viele Menschen Filme eher auf kleinen Bildschirmen schauen als im Kino?",
  "Beschreiben Sie, wie sich das Schauen eines ganzen Films von dem Konsum kurzer Videos im Internet unterscheidet.",
  "Was möchten Sie sich für die Zukunft in Bezug auf Ihr Sehverhalten vornehmen?",
  "Erzählen Sie, wie ein Film Ihnen geholfen hat, ein anderes Thema besser zu verstehen.",
  "Was halten Sie von der Idee, sich bewusst Zeit für anspruchsvolle Filme statt für leichte Unterhaltung zu nehmen?",
]);

const SPORTEREIGNIS = withStyles("Sportereignis", "teil1_q_sport", [
  "Erzählen Sie von einem Sportereignis, das Sie besonders beeindruckt hat.",
  "Beschreiben Sie ein Sportereignis, das Sie live miterlebt haben. Wie war die Atmosphäre?",
  "Was halten Sie davon, Sport im Stadion zu verfolgen im Vergleich zum Fernsehen?",
  "Welche Sportart verfolgen Sie am liebsten, und was fasziniert Sie daran?",
  "Vergleichen Sie zwei Sportereignisse, die Sie erlebt haben. Worin unterschieden sie sich?",
  "Was würden Sie jemandem empfehlen, der sich zum ersten Mal für Sport zu interessieren beginnt?",
  "Wie hat ein bestimmtes Sportereignis Sie oder Ihr Umfeld emotional bewegt?",
  "Erzählen Sie von einem Sportler oder einer Sportlerin, die Sie besonders bewundern.",
  "Was ist Ihnen bei einem Sportereignis wichtiger, der Sieg der eigenen Mannschaft oder ein fairer, spannender Wettkampf?",
  "Beschreiben Sie ein Sportereignis, dessen Ausgang Sie überrascht hat.",
  "Wenn Sie ein großes Sportereignis organisieren könnten, welche Sportart würden Sie wählen, und warum?",
  "Was halten Sie von der wachsenden Kommerzialisierung im Spitzensport?",
  "Erzählen Sie, wie Sie ein wichtiges Sportereignis normalerweise verfolgen, allein oder mit anderen.",
  "Was möchten Sie sich in Zukunft gerne einmal live ansehen, und weshalb reizt Sie dieses Ereignis?",
  "Wie beeinflusst Ihrer Meinung nach das Publikum die Leistung der Sportlerinnen und Sportler?",
  "Beschreiben Sie ein Sportereignis, bei dem der Zusammenhalt der Mannschaft besonders deutlich wurde.",
  "Was halten Sie vom wachsenden Interesse an Frauensport in den letzten Jahren?",
  "Welche Rolle hat Sport in Ihrer Kindheit gespielt?",
  "Erzählen Sie von einem Wettkampf, den Sie live miterlebt haben und bei dem Sie eine Gänsehaut bekommen haben.",
  "Was wäre für Sie das Sportereignis Ihrer Träume, das Sie unbedingt einmal live sehen möchten?",
  "Wie hat sich Ihr Interesse an Sport im Laufe der Jahre verändert?",
  "Was würden Sie jemandem raten, der zum ersten Mal ein Stadion besucht?",
  "Vergleichen Sie Mannschaftssport und Einzelsport. Was verfolgen Sie lieber, und warum?",
  "Erzählen Sie von einer Sportlerin oder einem Sportler, deren Höchstform Sie besonders beeindruckt hat.",
  "Was war das packendste Sportereignis, das Sie je verfolgt haben?",
  "Wie wichtig ist Ihnen die Stimmung im Stadion für das gesamte Erlebnis?",
  "Beschreiben Sie ein Sportereignis, das Sie zum Nachdenken über Fairness im Sport gebracht hat.",
  "Was halten Sie davon, ein Sportereignis gemeinsam mit anderen zu verfolgen statt allein?",
  "Erzählen Sie, wie ein bestimmtes Sportereignis Ihnen in einer schwierigen Zeit Ablenkung verschafft hat.",
  "Was ist Ihnen bei einem Sportereignis wichtiger, eine knappe Niederlage mit starkem Kampfgeist oder ein deutlicher, ruhiger Sieg?",
  "Wenn Sie bei einem Sportereignis Ihrer Wahl live dabei sein könnten, welches wäre das und warum?",
  "Was würden Sie jemandem empfehlen, der sich für eine bestimmte Sportart zu interessieren beginnt?",
  "Beschreiben Sie, wie sich das Verfolgen von Sportereignissen verändert hat, seit es Livestreams im Internet gibt.",
  "Was halten Sie davon, dass manche Sportereignisse inzwischen sehr teuer geworden sind?",
  "Erzählen Sie von einem Sportereignis, das in Ihrem Freundeskreis viel diskutiert wurde.",
  "Wie beeinflusst es Ihrer Meinung nach die Nervenanspannung der Sportlerinnen und Sportler, wenn ein Spiel im Fernsehen übertragen wird?",
  "Was ist Ihnen wichtiger, den Sieg der eigenen Mannschaft zu feiern oder die sportliche Leistung insgesamt zu würdigen?",
  "Erzählen Sie, mit wem Sie am liebsten ein Sportereignis verfolgen und warum.",
  "Was halten Sie von Sportwetten rund um große Sportereignisse?",
  "Beschreiben Sie ein Sportereignis, dessen Verlauf Sie zunächst enttäuscht, am Ende aber doch begeistert hat.",
  "Was würden Sie jemandem raten, der bei einem wichtigen Wettkampf sehr nervös ist?",
  "Wie hat ein bestimmtes Sportereignis Ihr Verständnis für eine andere Kultur geprägt?",
  "Erzählen Sie von einem Moment bei einem Sportereignis, der Ihnen besonders im Gedächtnis geblieben ist.",
  "Was ist für Sie der größte Unterschied zwischen dem Verfolgen von Amateur- und Profisport?",
  "Wenn Sie eine Sportlerin oder einen Sportler persönlich treffen könnten, welche Frage würden Sie stellen?",
  "Was halten Sie davon, dass heute viele Menschen Sportereignisse eher auf dem Smartphone verfolgen als im Fernsehen?",
  "Beschreiben Sie, wie sich das Live-Erleben eines Sportereignisses von der Zusammenfassung in den Nachrichten unterscheidet.",
  "Was möchten Sie sich für die Zukunft in Bezug auf Ihr eigenes sportliches Engagement vornehmen?",
  "Erzählen Sie, wie ein Sportereignis Ihnen geholfen hat, eine wichtige Lektion über Durchhaltevermögen zu lernen.",
  "Was halten Sie von der Idee, sich bewusst Zeit für den Besuch lokaler Sportveranstaltungen zu nehmen statt nur große internationale Ereignisse zu verfolgen?",
]);

const MUSIKVERANSTALTUNG = withStyles("Musikveranstaltung", "teil1_q_musik", [
  "Erzählen Sie von einer Musikveranstaltung, die Sie besonders beeindruckt hat.",
  "Beschreiben Sie ein Konzert, das Sie live besucht haben. Wie war die Stimmung dort?",
  "Was halten Sie von Live-Konzerten im Vergleich zum Musikhören zu Hause?",
  "Welche Art von Musikveranstaltungen besuchen Sie am liebsten, und warum gerade diese?",
  "Vergleichen Sie zwei Konzerte oder Musikveranstaltungen, die Sie erlebt haben.",
  "Was würden Sie jemandem empfehlen, der zum ersten Mal ein Konzert besuchen möchte?",
  "Wie hat eine bestimmte Musikveranstaltung Sie emotional bewegt oder geprägt?",
  "Erzählen Sie von einem Künstler oder einer Band, die Sie besonders gerne live erleben würden.",
  "Was ist Ihnen bei einer Musikveranstaltung wichtiger, die musikalische Qualität oder die gesamte Atmosphäre?",
  "Beschreiben Sie eine Musikveranstaltung, die anders verlief, als Sie erwartet hatten.",
  "Wenn Sie eine Musikveranstaltung organisieren könnten, welche Art von Musik würden Sie wählen?",
  "Was halten Sie von den steigenden Ticketpreisen für große Konzerte?",
  "Erzählen Sie, mit wem Sie am liebsten zu einer Musikveranstaltung gehen, und warum.",
  "Was möchten Sie sich in Zukunft gerne einmal live ansehen, und weshalb interessiert Sie das?",
  "Wie beeinflusst Musik Ihrer Meinung nach die Stimmung bei einer Veranstaltung?",
  "Beschreiben Sie eine Musikveranstaltung, bei der die Bühnenpräsenz des Künstlers Sie besonders beeindruckt hat.",
  "Was halten Sie vom wachsenden Angebot an Musikfestivals in den letzten Jahren?",
  "Welche Rolle hat Musik in Ihrer Kindheit gespielt?",
  "Erzählen Sie von einem Konzert, das Sie vorzeitig verlassen mussten oder wollten, und warum.",
  "Was wäre für Sie die Musikveranstaltung Ihrer Träume, die Sie unbedingt einmal live erleben möchten?",
  "Wie hat sich Ihr Musikgeschmack im Laufe der Jahre verändert?",
  "Was würden Sie jemandem raten, der zum ersten Mal ein großes Festival besucht?",
  "Vergleichen Sie Konzerte in kleinen Locations und in großen Hallen. Was bevorzugen Sie, und warum?",
  "Erzählen Sie von einem Musiker oder einer Musikerin, deren Darbietung Sie besonders beeindruckt hat.",
  "Was war die energiegeladenste Musikveranstaltung, die Sie je besucht haben?",
  "Wie wichtig ist Ihnen die Klangqualität bei einem Konzert?",
  "Beschreiben Sie eine Musikveranstaltung, die Sie zum Nachdenken über die Bedeutung von Musik in Ihrem Leben gebracht hat.",
  "Was halten Sie davon, ein Konzert gemeinsam mit anderen zu besuchen statt allein?",
  "Erzählen Sie, wie eine bestimmte Musikveranstaltung Ihnen in einer schwierigen Zeit geholfen hat.",
  "Was ist Ihnen bei einer Musikveranstaltung wichtiger, ein bekannter Künstler oder eine besondere Location?",
  "Wenn Sie bei einer Musikveranstaltung Ihrer Wahl live dabei sein könnten, welche wäre das und warum?",
  "Was würden Sie jemandem empfehlen, der sich für ein bestimmtes Musikgenre zu interessieren beginnt?",
  "Beschreiben Sie, wie sich der Besuch von Musikveranstaltungen verändert hat, seit es Livestreams im Internet gibt.",
  "Was halten Sie davon, dass Konzerttickets für manche Künstler inzwischen sehr teuer geworden sind?",
  "Erzählen Sie von einer Musikveranstaltung, die in Ihrem Freundeskreis viel diskutiert wurde.",
  "Wie beeinflusst es Ihrer Meinung nach das Live-Erlebnis, wenn ein Konzert in einer sehr großen Halle stattfindet?",
  "Was ist Ihnen wichtiger, ein Konzert intensiv zu genießen oder Erinnerungen wie Fotos und Videos davon festzuhalten?",
  "Erzählen Sie, mit wem Sie am liebsten zu einer Musikveranstaltung gehen und warum.",
  "Was halten Sie vom Weiterverkauf von Konzerttickets zu überhöhten Preisen?",
  "Beschreiben Sie eine Musikveranstaltung, die Sie zunächst skeptisch gemacht, am Ende aber doch überzeugt hat.",
  "Was würden Sie jemandem raten, der vor seinem ersten eigenen Bühnenauftritt sehr nervös ist?",
  "Wie hat eine bestimmte Musikveranstaltung Ihr Verständnis für eine andere Kultur geprägt?",
  "Erzählen Sie von einem Ohrwurm, der Sie nach einer Musikveranstaltung noch lange begleitet hat.",
  "Was ist für Sie der größte Unterschied zwischen dem Hören eines Albums und dem Erleben eines Konzerts?",
  "Wenn Sie einen Musiker oder eine Musikerin persönlich treffen könnten, welche Frage würden Sie stellen?",
  "Was halten Sie davon, dass heute viele Menschen Musik eher über Kopfhörer als bei Live-Veranstaltungen erleben?",
  "Beschreiben Sie, wie sich das Live-Erleben eines Konzerts von einer Aufnahme im Fernsehen unterscheidet.",
  "Was möchten Sie sich für die Zukunft in Bezug auf Ihren Musikgeschmack vornehmen?",
  "Erzählen Sie, wie eine Musikveranstaltung Ihnen geholfen hat, neue Menschen kennenzulernen.",
  "Was halten Sie von der Idee, gezielt kleinere, weniger bekannte Künstler live zu unterstützen statt nur große Stars zu besuchen?",
]);

const WICHTIGE_PERSON = withStyles("Wichtige Person im Leben", "teil1_q_person", [
  "Erzählen Sie von einer Person, die einen großen Einfluss auf Ihr Leben hatte.",
  "Beschreiben Sie, wie Sie diese wichtige Person kennengelernt haben.",
  "Was hat diese Person Ihrer Meinung nach an Ihnen oder Ihrem Leben verändert?",
  "Vergleichen Sie zwei Menschen, die für Sie wichtig sind. Worin unterscheiden sie sich?",
  "Was würden Sie jemandem raten, der eine ähnlich wichtige Beziehung in seinem Leben sucht?",
  "Wie zeigen Sie dieser Person, wie wichtig sie Ihnen ist?",
  "Erzählen Sie von einer Situation, in der diese Person Ihnen besonders geholfen hat.",
  "Was ist Ihnen an einer wichtigen Beziehung am meisten wichtig, Vertrauen, Unterstützung oder gemeinsame Erlebnisse?",
  "Beschreiben Sie, wie sich Ihre Beziehung zu dieser Person im Laufe der Zeit verändert hat.",
  "Wenn Sie dieser Person heute etwas sagen könnten, was wäre das?",
  "Was halten Sie davon, dass wichtige Beziehungen oft erst im Rückblick richtig geschätzt werden?",
  "Erzählen Sie, wie diese Person auf schwierige Situationen in Ihrem Leben reagiert hat.",
  "Was möchten Sie in Zukunft gemeinsam mit dieser Person noch erleben?",
  "Wie unterscheidet sich diese Beziehung von anderen wichtigen Beziehungen in Ihrem Leben?",
  "Was haben Sie von dieser Person über das Leben gelernt?",
  "Beschreiben Sie, wie diese Person auf den ersten Blick auf Sie gewirkt hat.",
  "Was halten Sie davon, dass manche Menschen erst spät im Leben eine wirklich wichtige Bezugsperson finden?",
  "Welche Rolle spielten Großeltern oder andere ältere Verwandte in Ihrem Leben?",
  "Erzählen Sie von einem Streit oder Missverständnis mit dieser Person, das Sie am Ende überwunden haben.",
  "Was wäre für Sie die schönste Art, dieser Person Danke zu sagen?",
  "Wie hat sich Ihre Beziehung zu dieser Person verändert, seit Sie erwachsen geworden sind?",
  "Was würden Sie jemandem raten, der eine wichtige Bezugsperson verloren hat?",
  "Vergleichen Sie diese Person mit einer anderen wichtigen Person in Ihrem Leben. Worin ähneln sie sich?",
  "Erzählen Sie von einer Lebensweisheit, die Ihnen diese Person mitgegeben hat.",
  "Was war der emotionalste Moment, den Sie mit dieser Person geteilt haben?",
  "Wie wichtig ist Ihnen bedingungslose Unterstützung in einer engen Beziehung?",
  "Beschreiben Sie, wie diese Person Sie dazu gebracht hat, über sich selbst hinauszuwachsen.",
  "Was halten Sie davon, dass manche Vorbilder gar nicht aus dem eigenen Umfeld stammen, sondern öffentliche Personen sind?",
  "Erzählen Sie, wie diese Person Ihnen in einer beruflichen oder schulischen Angelegenheit geholfen hat.",
  "Was ist Ihnen bei einer engen Beziehung wichtiger, gemeinsame Interessen oder gegenseitiges Verständnis?",
  "Wenn Sie einen Tag mit dieser Person noch einmal erleben könnten, welchen würden Sie wählen und warum?",
  "Was würden Sie jemandem empfehlen, der Schwierigkeiten hat, eine enge Bindung zu einer wichtigen Person aufzubauen?",
  "Beschreiben Sie, wie sich der Kontakt zu dieser Person verändert hat, seit Sie räumlich getrennt leben.",
  "Was halten Sie davon, wichtigen Menschen im Leben regelmäßig zu sagen, wie viel sie einem bedeuten?",
  "Erzählen Sie von einer Eigenschaft dieser Person, die Sie sich selbst gerne aneignen würden.",
  "Wie beeinflusst es Ihrer Meinung nach eine Beziehung, wenn zwei Menschen sehr unterschiedliche Ansichten haben?",
  "Was ist Ihnen wichtiger, von dieser Person bewundert oder von ihr ehrlich kritisiert zu werden?",
  "Erzählen Sie, wie diese Person auf einen Erfolg von Ihnen reagiert hat.",
  "Was halten Sie davon, dass manche prägenden Personen nur für kurze Zeit im Leben eine Rolle spielen?",
  "Beschreiben Sie eine Situation, in der Sie selbst für diese Person da sein konnten.",
  "Was würden Sie jemandem raten, der Angst hat, jemandem seine Wertschätzung offen zu zeigen?",
  "Wie hat diese Person Ihre Vorstellung davon geprägt, was eine gute Freundschaft oder Beziehung ausmacht?",
  "Erzählen Sie von einem gemeinsamen Ritual oder einer Tradition, die Sie mit dieser Person verbindet.",
  "Was ist für Sie der größte Unterschied zwischen einem Vorbild und einem engen Vertrauten?",
  "Wenn Sie dieser Person eine Sache aus Ihrem heutigen Leben zeigen könnten, was wäre das?",
  "Was halten Sie davon, dass manche Menschen ihre wichtigsten Bezugspersonen erst im Rückblick richtig zu schätzen wissen?",
  "Beschreiben Sie, wie sich Ihr Bild von dieser Person im Laufe der Zeit verändert hat.",
  "Was möchten Sie sich für die Zukunft in Bezug auf diese Beziehung vornehmen?",
  "Erzählen Sie, wie diese Person Ihnen geholfen hat, eine eigene schwierige Entscheidung zu treffen.",
  "Was halten Sie von der Idee, dass man von jeder wichtigen Person im Leben etwas Bleibendes mitnimmt, auch wenn der Kontakt irgendwann endet?",
]);

const WICHTIGE_ERFAHRUNG = withStyles("Wichtige Erfahrung", "teil1_q_erfahrung", [
  "Erzählen Sie von einer Erfahrung, die Ihr Leben nachhaltig verändert hat.",
  "Beschreiben Sie eine Situation, in der Sie über sich selbst hinausgewachsen sind.",
  "Was haben Sie aus dieser Erfahrung über sich selbst gelernt?",
  "Vergleichen Sie zwei wichtige Erfahrungen in Ihrem Leben. Worin unterschieden sie sich?",
  "Was würden Sie jemandem raten, der vor einer ähnlichen Herausforderung steht?",
  "Wie hat diese Erfahrung Ihre Sichtweise auf das Leben verändert?",
  "Erzählen Sie, wie Sie sich in dem Moment gefühlt haben, als diese Erfahrung passierte.",
  "Was ist Ihnen im Rückblick an dieser Erfahrung am wichtigsten?",
  "Beschreiben Sie eine Erfahrung, die zunächst schwierig war, sich aber im Nachhinein als wertvoll erwiesen hat.",
  "Wenn Sie diese Erfahrung noch einmal machen müssten, würden Sie etwas anders angehen?",
  "Was halten Sie davon, dass man aus schwierigen Erfahrungen oft am meisten lernt?",
  "Erzählen Sie, wer Sie in dieser Erfahrung unterstützt hat.",
  "Was möchten Sie anderen Menschen aus dieser Erfahrung mitgeben?",
  "Wie hat diese Erfahrung Ihre Beziehungen zu anderen Menschen beeinflusst?",
  "Was war der entscheidende Moment in dieser Erfahrung, und warum genau dieser?",
  "Beschreiben Sie eine Erfahrung, bei der Sie Ihre Komfortzone verlassen mussten.",
  "Was halten Sie davon, dass manche wichtigen Erfahrungen erst im Nachhinein ihren wahren Wert zeigen?",
  "Welche Erfahrung aus Ihrer Kindheit hat Sie bis heute geprägt?",
  "Erzählen Sie von einer Erfahrung, die Sie ursprünglich vermeiden wollten, die sich aber als wichtig erwiesen hat.",
  "Was wäre für Sie die größte Erkenntnis, die Sie aus dieser Erfahrung gewonnen haben?",
  "Wie hat sich Ihre Reaktion auf Herausforderungen verändert, seit Sie diese Erfahrung gemacht haben?",
  "Was würden Sie jemandem raten, der gerade eine ähnliche Herausforderung durchlebt wie Sie damals?",
  "Vergleichen Sie diese Erfahrung mit einer anderen wichtigen Erfahrung in Ihrem Leben. Worin unterscheiden sie sich?",
  "Erzählen Sie von einem Moment während dieser Erfahrung, in dem Sie kurz davor waren aufzugeben.",
  "Was war der schwierigste Teil dieser Erfahrung für Sie?",
  "Wie wichtig ist Ihnen im Rückblick, dass diese Erfahrung nicht immer angenehm war?",
  "Beschreiben Sie, wie diese Erfahrung Ihr Verhältnis zu sich selbst verändert hat.",
  "Was halten Sie davon, dass manche Menschen ähnliche Erfahrungen ganz anders verarbeiten als Sie?",
  "Erzählen Sie, wie diese Erfahrung Ihre Selbstständigkeit gestärkt hat.",
  "Was ist Ihnen bei einer schwierigen Erfahrung wichtiger, sie allein zu bewältigen oder sich Hilfe zu holen?",
  "Wenn Sie diese Erfahrung einer jüngeren Version von sich selbst erklären könnten, was würden Sie sagen?",
  "Was würden Sie jemandem empfehlen, der Angst davor hat, eine ähnliche Herausforderung überhaupt anzugehen?",
  "Beschreiben Sie, wie sich Ihre Sicht auf diese Erfahrung im Laufe der Jahre verändert hat.",
  "Was halten Sie davon, dass manche prägenden Erfahrungen erst durch einen Rückschlag entstehen?",
  "Erzählen Sie von einer Erfahrung, die für Sie einen echten Wendepunkt dargestellt hat.",
  "Wie beeinflusst es Ihrer Meinung nach eine Person, wenn sie eine schwierige Erfahrung ganz allein durchsteht?",
  "Was ist Ihnen wichtiger, aus einer Erfahrung schnell weiterzuziehen oder sie in Ruhe zu verarbeiten?",
  "Erzählen Sie, wie andere Menschen auf Sie reagiert haben, nachdem Sie diese Erfahrung gemacht hatten.",
  "Was halten Sie davon, negative Erfahrungen im Nachhinein bewusst positiv umzudeuten?",
  "Beschreiben Sie eine Erfahrung, die Sie zunächst überfordert, aber letztlich reifer gemacht hat.",
  "Was würden Sie jemandem raten, der Angst hat, aus seiner Komfortzone herauszutreten?",
  "Wie hat diese Erfahrung Ihr Verständnis dafür geprägt, was im Leben wirklich wichtig ist?",
  "Erzählen Sie von einem Satz oder Rat, der Ihnen während dieser Erfahrung besonders geholfen hat.",
  "Was ist für Sie der größte Unterschied zwischen einer schwierigen und einer schmerzhaften Erfahrung?",
  "Wenn Sie diese Erfahrung noch einmal durchleben müssten, was würden Sie sich selbst im Voraus sagen?",
  "Was halten Sie davon, dass manche Menschen aus denselben Umständen ganz unterschiedliche Lehren ziehen?",
  "Beschreiben Sie, wie sich diese Erfahrung auf Ihre späteren Entscheidungen ausgewirkt hat.",
  "Was möchten Sie sich für die Zukunft vornehmen, wenn Sie wieder vor eine ähnliche Herausforderung gestellt werden?",
  "Erzählen Sie, wie diese Erfahrung Ihr Verhältnis zu Rückschlägen im Allgemeinen verändert hat.",
  "Was halten Sie von der Idee, dass die schwierigsten Erfahrungen oft die sind, die uns am meisten formen?",
]);

const ALL_TEIL1_QUESTIONS: Teil1Question[] = [
  ...REISE, ...BUCH, ...FILM, ...SPORTEREIGNIS, ...MUSIKVERANSTALTUNG, ...WICHTIGE_PERSON, ...WICHTIGE_ERFAHRUNG,
];

export function getTeil1QuestionPool(topic: string): Teil1Question[] {
  return ALL_TEIL1_QUESTIONS.filter((q) => q.topic === topic);
}

export function allTeil1Questions(): Teil1Question[] {
  return ALL_TEIL1_QUESTIONS;
}

export const TEIL1_TOPICS = ["Reise", "Buch", "Film", "Sportereignis", "Musikveranstaltung", "Wichtige Person im Leben", "Wichtige Erfahrung"];
