/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStatistikRouteImport } from './routes/_authenticated.statistik'
import { Route as AuthenticatedSecurityRouteImport } from './routes/_authenticated.security'
import { Route as AuthenticatedSchriftlichRouteImport } from './routes/_authenticated.schriftlich'
import { Route as AuthenticatedReferralsRouteImport } from './routes/_authenticated.referrals'
import { Route as AuthenticatedPruefungRouteImport } from './routes/_authenticated.pruefung'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated.onboarding'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated.notifications'
import { Route as AuthenticatedMuendlichRouteImport } from './routes/_authenticated.muendlich'
import { Route as AuthenticatedLearnRouteImport } from './routes/_authenticated.learn'
import { Route as AuthenticatedHelpRouteImport } from './routes/_authenticated.help'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated.billing'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedSchriftlichIndexRouteImport } from './routes/_authenticated.schriftlich.index'
import { Route as AuthenticatedMuendlichIndexRouteImport } from './routes/_authenticated.muendlich.index'
import { Route as AuthenticatedLearnIndexRouteImport } from './routes/_authenticated.learn.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api.public.stripe-webhook'
import { Route as AuthenticatedSchriftlichVorbereitungRouteImport } from './routes/_authenticated.schriftlich.vorbereitung'
import { Route as AuthenticatedSchriftlichPruefungRouteImport } from './routes/_authenticated.schriftlich.pruefung'
import { Route as AuthenticatedMuendlichVorbereitungRouteImport } from './routes/_authenticated.muendlich.vorbereitung'
import { Route as AuthenticatedMuendlichPruefungRouteImport } from './routes/_authenticated.muendlich.pruefung'
import { Route as AuthenticatedLearnLevelRouteImport } from './routes/_authenticated.learn.$level'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated.admin.users'
import { Route as AuthenticatedAdminSubscriptionsRouteImport } from './routes/_authenticated.admin.subscriptions'
import { Route as AuthenticatedAdminPlansRouteImport } from './routes/_authenticated.admin.plans'
import { Route as AuthenticatedAdminMessagesRouteImport } from './routes/_authenticated.admin.messages'
import { Route as AuthenticatedAdminExercisesRouteImport } from './routes/_authenticated.admin.exercises'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated.admin.analytics'
import { Route as AuthenticatedAdminExercisesNewRouteImport } from './routes/_authenticated.admin.exercises.new'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStatistikRoute = AuthenticatedStatistikRouteImport.update({
  id: '/statistik',
  path: '/statistik',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSecurityRoute = AuthenticatedSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSchriftlichRoute =
  AuthenticatedSchriftlichRouteImport.update({
    id: '/schriftlich',
    path: '/schriftlich',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReferralsRoute = AuthenticatedReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPruefungRoute = AuthenticatedPruefungRouteImport.update({
  id: '/pruefung',
  path: '/pruefung',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMuendlichRoute = AuthenticatedMuendlichRouteImport.update({
  id: '/muendlich',
  path: '/muendlich',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLearnRoute = AuthenticatedLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHelpRoute = AuthenticatedHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSchriftlichIndexRoute =
  AuthenticatedSchriftlichIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSchriftlichRoute,
  } as any)
const AuthenticatedMuendlichIndexRoute =
  AuthenticatedMuendlichIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMuendlichRoute,
  } as any)
const AuthenticatedLearnIndexRoute = AuthenticatedLearnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedLearnRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSchriftlichVorbereitungRoute =
  AuthenticatedSchriftlichVorbereitungRouteImport.update({
    id: '/vorbereitung',
    path: '/vorbereitung',
    getParentRoute: () => AuthenticatedSchriftlichRoute,
  } as any)
const AuthenticatedSchriftlichPruefungRoute =
  AuthenticatedSchriftlichPruefungRouteImport.update({
    id: '/pruefung',
    path: '/pruefung',
    getParentRoute: () => AuthenticatedSchriftlichRoute,
  } as any)
const AuthenticatedMuendlichVorbereitungRoute =
  AuthenticatedMuendlichVorbereitungRouteImport.update({
    id: '/vorbereitung',
    path: '/vorbereitung',
    getParentRoute: () => AuthenticatedMuendlichRoute,
  } as any)
const AuthenticatedMuendlichPruefungRoute =
  AuthenticatedMuendlichPruefungRouteImport.update({
    id: '/pruefung',
    path: '/pruefung',
    getParentRoute: () => AuthenticatedMuendlichRoute,
  } as any)
const AuthenticatedLearnLevelRoute = AuthenticatedLearnLevelRouteImport.update({
  id: '/$level',
  path: '/$level',
  getParentRoute: () => AuthenticatedLearnRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSubscriptionsRoute =
  AuthenticatedAdminSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPlansRoute = AuthenticatedAdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminMessagesRoute =
  AuthenticatedAdminMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminExercisesRoute =
  AuthenticatedAdminExercisesRouteImport.update({
    id: '/exercises',
    path: '/exercises',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminExercisesNewRoute =
  AuthenticatedAdminExercisesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminExercisesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/help': typeof AuthenticatedHelpRoute
  '/learn': typeof AuthenticatedLearnRouteWithChildren
  '/muendlich': typeof AuthenticatedMuendlichRouteWithChildren
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/pruefung': typeof AuthenticatedPruefungRoute
  '/referrals': typeof AuthenticatedReferralsRoute
  '/schriftlich': typeof AuthenticatedSchriftlichRouteWithChildren
  '/security': typeof AuthenticatedSecurityRoute
  '/statistik': typeof AuthenticatedStatistikRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/exercises': typeof AuthenticatedAdminExercisesRouteWithChildren
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/learn/$level': typeof AuthenticatedLearnLevelRoute
  '/muendlich/pruefung': typeof AuthenticatedMuendlichPruefungRoute
  '/muendlich/vorbereitung': typeof AuthenticatedMuendlichVorbereitungRoute
  '/schriftlich/pruefung': typeof AuthenticatedSchriftlichPruefungRoute
  '/schriftlich/vorbereitung': typeof AuthenticatedSchriftlichVorbereitungRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/learn/': typeof AuthenticatedLearnIndexRoute
  '/muendlich/': typeof AuthenticatedMuendlichIndexRoute
  '/schriftlich/': typeof AuthenticatedSchriftlichIndexRoute
  '/admin/exercises/new': typeof AuthenticatedAdminExercisesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/help': typeof AuthenticatedHelpRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/pruefung': typeof AuthenticatedPruefungRoute
  '/referrals': typeof AuthenticatedReferralsRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/statistik': typeof AuthenticatedStatistikRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/exercises': typeof AuthenticatedAdminExercisesRouteWithChildren
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/learn/$level': typeof AuthenticatedLearnLevelRoute
  '/muendlich/pruefung': typeof AuthenticatedMuendlichPruefungRoute
  '/muendlich/vorbereitung': typeof AuthenticatedMuendlichVorbereitungRoute
  '/schriftlich/pruefung': typeof AuthenticatedSchriftlichPruefungRoute
  '/schriftlich/vorbereitung': typeof AuthenticatedSchriftlichVorbereitungRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/learn': typeof AuthenticatedLearnIndexRoute
  '/muendlich': typeof AuthenticatedMuendlichIndexRoute
  '/schriftlich': typeof AuthenticatedSchriftlichIndexRoute
  '/admin/exercises/new': typeof AuthenticatedAdminExercisesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/cookies': typeof CookiesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/help': typeof AuthenticatedHelpRoute
  '/_authenticated/learn': typeof AuthenticatedLearnRouteWithChildren
  '/_authenticated/muendlich': typeof AuthenticatedMuendlichRouteWithChildren
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/pruefung': typeof AuthenticatedPruefungRoute
  '/_authenticated/referrals': typeof AuthenticatedReferralsRoute
  '/_authenticated/schriftlich': typeof AuthenticatedSchriftlichRouteWithChildren
  '/_authenticated/security': typeof AuthenticatedSecurityRoute
  '/_authenticated/statistik': typeof AuthenticatedStatistikRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/exercises': typeof AuthenticatedAdminExercisesRouteWithChildren
  '/_authenticated/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/_authenticated/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/_authenticated/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/learn/$level': typeof AuthenticatedLearnLevelRoute
  '/_authenticated/muendlich/pruefung': typeof AuthenticatedMuendlichPruefungRoute
  '/_authenticated/muendlich/vorbereitung': typeof AuthenticatedMuendlichVorbereitungRoute
  '/_authenticated/schriftlich/pruefung': typeof AuthenticatedSchriftlichPruefungRoute
  '/_authenticated/schriftlich/vorbereitung': typeof AuthenticatedSchriftlichVorbereitungRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/learn/': typeof AuthenticatedLearnIndexRoute
  '/_authenticated/muendlich/': typeof AuthenticatedMuendlichIndexRoute
  '/_authenticated/schriftlich/': typeof AuthenticatedSchriftlichIndexRoute
  '/_authenticated/admin/exercises/new': typeof AuthenticatedAdminExercisesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cookies'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/refund'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/unauthorized'
    | '/admin'
    | '/billing'
    | '/dashboard'
    | '/help'
    | '/learn'
    | '/muendlich'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/pruefung'
    | '/referrals'
    | '/schriftlich'
    | '/security'
    | '/statistik'
    | '/admin/analytics'
    | '/admin/exercises'
    | '/admin/messages'
    | '/admin/plans'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/learn/$level'
    | '/muendlich/pruefung'
    | '/muendlich/vorbereitung'
    | '/schriftlich/pruefung'
    | '/schriftlich/vorbereitung'
    | '/api/public/stripe-webhook'
    | '/admin/'
    | '/learn/'
    | '/muendlich/'
    | '/schriftlich/'
    | '/admin/exercises/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cookies'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/refund'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/unauthorized'
    | '/billing'
    | '/dashboard'
    | '/help'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/pruefung'
    | '/referrals'
    | '/security'
    | '/statistik'
    | '/admin/analytics'
    | '/admin/exercises'
    | '/admin/messages'
    | '/admin/plans'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/learn/$level'
    | '/muendlich/pruefung'
    | '/muendlich/vorbereitung'
    | '/schriftlich/pruefung'
    | '/schriftlich/vorbereitung'
    | '/api/public/stripe-webhook'
    | '/admin'
    | '/learn'
    | '/muendlich'
    | '/schriftlich'
    | '/admin/exercises/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/cookies'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/refund'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/unauthorized'
    | '/_authenticated/admin'
    | '/_authenticated/billing'
    | '/_authenticated/dashboard'
    | '/_authenticated/help'
    | '/_authenticated/learn'
    | '/_authenticated/muendlich'
    | '/_authenticated/notifications'
    | '/_authenticated/onboarding'
    | '/_authenticated/profile'
    | '/_authenticated/pruefung'
    | '/_authenticated/referrals'
    | '/_authenticated/schriftlich'
    | '/_authenticated/security'
    | '/_authenticated/statistik'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/exercises'
    | '/_authenticated/admin/messages'
    | '/_authenticated/admin/plans'
    | '/_authenticated/admin/subscriptions'
    | '/_authenticated/admin/users'
    | '/_authenticated/learn/$level'
    | '/_authenticated/muendlich/pruefung'
    | '/_authenticated/muendlich/vorbereitung'
    | '/_authenticated/schriftlich/pruefung'
    | '/_authenticated/schriftlich/vorbereitung'
    | '/api/public/stripe-webhook'
    | '/_authenticated/admin/'
    | '/_authenticated/learn/'
    | '/_authenticated/muendlich/'
    | '/_authenticated/schriftlich/'
    | '/_authenticated/admin/exercises/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CookiesRoute: typeof CookiesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundRoute: typeof RefundRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/statistik': {
      id: '/_authenticated/statistik'
      path: '/statistik'
      fullPath: '/statistik'
      preLoaderRoute: typeof AuthenticatedStatistikRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/security': {
      id: '/_authenticated/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AuthenticatedSecurityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/schriftlich': {
      id: '/_authenticated/schriftlich'
      path: '/schriftlich'
      fullPath: '/schriftlich'
      preLoaderRoute: typeof AuthenticatedSchriftlichRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/referrals': {
      id: '/_authenticated/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof AuthenticatedReferralsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pruefung': {
      id: '/_authenticated/pruefung'
      path: '/pruefung'
      fullPath: '/pruefung'
      preLoaderRoute: typeof AuthenticatedPruefungRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/muendlich': {
      id: '/_authenticated/muendlich'
      path: '/muendlich'
      fullPath: '/muendlich'
      preLoaderRoute: typeof AuthenticatedMuendlichRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/learn': {
      id: '/_authenticated/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof AuthenticatedLearnRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/help': {
      id: '/_authenticated/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthenticatedHelpRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/schriftlich/': {
      id: '/_authenticated/schriftlich/'
      path: '/'
      fullPath: '/schriftlich/'
      preLoaderRoute: typeof AuthenticatedSchriftlichIndexRouteImport
      parentRoute: typeof AuthenticatedSchriftlichRoute
    }
    '/_authenticated/muendlich/': {
      id: '/_authenticated/muendlich/'
      path: '/'
      fullPath: '/muendlich/'
      preLoaderRoute: typeof AuthenticatedMuendlichIndexRouteImport
      parentRoute: typeof AuthenticatedMuendlichRoute
    }
    '/_authenticated/learn/': {
      id: '/_authenticated/learn/'
      path: '/'
      fullPath: '/learn/'
      preLoaderRoute: typeof AuthenticatedLearnIndexRouteImport
      parentRoute: typeof AuthenticatedLearnRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/schriftlich/vorbereitung': {
      id: '/_authenticated/schriftlich/vorbereitung'
      path: '/vorbereitung'
      fullPath: '/schriftlich/vorbereitung'
      preLoaderRoute: typeof AuthenticatedSchriftlichVorbereitungRouteImport
      parentRoute: typeof AuthenticatedSchriftlichRoute
    }
    '/_authenticated/schriftlich/pruefung': {
      id: '/_authenticated/schriftlich/pruefung'
      path: '/pruefung'
      fullPath: '/schriftlich/pruefung'
      preLoaderRoute: typeof AuthenticatedSchriftlichPruefungRouteImport
      parentRoute: typeof AuthenticatedSchriftlichRoute
    }
    '/_authenticated/muendlich/vorbereitung': {
      id: '/_authenticated/muendlich/vorbereitung'
      path: '/vorbereitung'
      fullPath: '/muendlich/vorbereitung'
      preLoaderRoute: typeof AuthenticatedMuendlichVorbereitungRouteImport
      parentRoute: typeof AuthenticatedMuendlichRoute
    }
    '/_authenticated/muendlich/pruefung': {
      id: '/_authenticated/muendlich/pruefung'
      path: '/pruefung'
      fullPath: '/muendlich/pruefung'
      preLoaderRoute: typeof AuthenticatedMuendlichPruefungRouteImport
      parentRoute: typeof AuthenticatedMuendlichRoute
    }
    '/_authenticated/learn/$level': {
      id: '/_authenticated/learn/$level'
      path: '/$level'
      fullPath: '/learn/$level'
      preLoaderRoute: typeof AuthenticatedLearnLevelRouteImport
      parentRoute: typeof AuthenticatedLearnRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/subscriptions': {
      id: '/_authenticated/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AuthenticatedAdminSubscriptionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/plans': {
      id: '/_authenticated/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AuthenticatedAdminPlansRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/messages': {
      id: '/_authenticated/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AuthenticatedAdminMessagesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/exercises': {
      id: '/_authenticated/admin/exercises'
      path: '/exercises'
      fullPath: '/admin/exercises'
      preLoaderRoute: typeof AuthenticatedAdminExercisesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/exercises/new': {
      id: '/_authenticated/admin/exercises/new'
      path: '/new'
      fullPath: '/admin/exercises/new'
      preLoaderRoute: typeof AuthenticatedAdminExercisesNewRouteImport
      parentRoute: typeof AuthenticatedAdminExercisesRoute
    }
  }
}

interface AuthenticatedAdminExercisesRouteChildren {
  AuthenticatedAdminExercisesNewRoute: typeof AuthenticatedAdminExercisesNewRoute
}

const AuthenticatedAdminExercisesRouteChildren: AuthenticatedAdminExercisesRouteChildren =
  {
    AuthenticatedAdminExercisesNewRoute: AuthenticatedAdminExercisesNewRoute,
  }

const AuthenticatedAdminExercisesRouteWithChildren =
  AuthenticatedAdminExercisesRoute._addFileChildren(
    AuthenticatedAdminExercisesRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminExercisesRoute: typeof AuthenticatedAdminExercisesRouteWithChildren
  AuthenticatedAdminMessagesRoute: typeof AuthenticatedAdminMessagesRoute
  AuthenticatedAdminPlansRoute: typeof AuthenticatedAdminPlansRoute
  AuthenticatedAdminSubscriptionsRoute: typeof AuthenticatedAdminSubscriptionsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminExercisesRoute:
    AuthenticatedAdminExercisesRouteWithChildren,
  AuthenticatedAdminMessagesRoute: AuthenticatedAdminMessagesRoute,
  AuthenticatedAdminPlansRoute: AuthenticatedAdminPlansRoute,
  AuthenticatedAdminSubscriptionsRoute: AuthenticatedAdminSubscriptionsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedLearnRouteChildren {
  AuthenticatedLearnLevelRoute: typeof AuthenticatedLearnLevelRoute
  AuthenticatedLearnIndexRoute: typeof AuthenticatedLearnIndexRoute
}

const AuthenticatedLearnRouteChildren: AuthenticatedLearnRouteChildren = {
  AuthenticatedLearnLevelRoute: AuthenticatedLearnLevelRoute,
  AuthenticatedLearnIndexRoute: AuthenticatedLearnIndexRoute,
}

const AuthenticatedLearnRouteWithChildren =
  AuthenticatedLearnRoute._addFileChildren(AuthenticatedLearnRouteChildren)

interface AuthenticatedMuendlichRouteChildren {
  AuthenticatedMuendlichPruefungRoute: typeof AuthenticatedMuendlichPruefungRoute
  AuthenticatedMuendlichVorbereitungRoute: typeof AuthenticatedMuendlichVorbereitungRoute
  AuthenticatedMuendlichIndexRoute: typeof AuthenticatedMuendlichIndexRoute
}

const AuthenticatedMuendlichRouteChildren: AuthenticatedMuendlichRouteChildren =
  {
    AuthenticatedMuendlichPruefungRoute: AuthenticatedMuendlichPruefungRoute,
    AuthenticatedMuendlichVorbereitungRoute:
      AuthenticatedMuendlichVorbereitungRoute,
    AuthenticatedMuendlichIndexRoute: AuthenticatedMuendlichIndexRoute,
  }

const AuthenticatedMuendlichRouteWithChildren =
  AuthenticatedMuendlichRoute._addFileChildren(
    AuthenticatedMuendlichRouteChildren,
  )

interface AuthenticatedSchriftlichRouteChildren {
  AuthenticatedSchriftlichPruefungRoute: typeof AuthenticatedSchriftlichPruefungRoute
  AuthenticatedSchriftlichVorbereitungRoute: typeof AuthenticatedSchriftlichVorbereitungRoute
  AuthenticatedSchriftlichIndexRoute: typeof AuthenticatedSchriftlichIndexRoute
}

const AuthenticatedSchriftlichRouteChildren: AuthenticatedSchriftlichRouteChildren =
  {
    AuthenticatedSchriftlichPruefungRoute:
      AuthenticatedSchriftlichPruefungRoute,
    AuthenticatedSchriftlichVorbereitungRoute:
      AuthenticatedSchriftlichVorbereitungRoute,
    AuthenticatedSchriftlichIndexRoute: AuthenticatedSchriftlichIndexRoute,
  }

const AuthenticatedSchriftlichRouteWithChildren =
  AuthenticatedSchriftlichRoute._addFileChildren(
    AuthenticatedSchriftlichRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHelpRoute: typeof AuthenticatedHelpRoute
  AuthenticatedLearnRoute: typeof AuthenticatedLearnRouteWithChildren
  AuthenticatedMuendlichRoute: typeof AuthenticatedMuendlichRouteWithChildren
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedPruefungRoute: typeof AuthenticatedPruefungRoute
  AuthenticatedReferralsRoute: typeof AuthenticatedReferralsRoute
  AuthenticatedSchriftlichRoute: typeof AuthenticatedSchriftlichRouteWithChildren
  AuthenticatedSecurityRoute: typeof AuthenticatedSecurityRoute
  AuthenticatedStatistikRoute: typeof AuthenticatedStatistikRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHelpRoute: AuthenticatedHelpRoute,
  AuthenticatedLearnRoute: AuthenticatedLearnRouteWithChildren,
  AuthenticatedMuendlichRoute: AuthenticatedMuendlichRouteWithChildren,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedPruefungRoute: AuthenticatedPruefungRoute,
  AuthenticatedReferralsRoute: AuthenticatedReferralsRoute,
  AuthenticatedSchriftlichRoute: AuthenticatedSchriftlichRouteWithChildren,
  AuthenticatedSecurityRoute: AuthenticatedSecurityRoute,
  AuthenticatedStatistikRoute: AuthenticatedStatistikRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CookiesRoute: CookiesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RefundRoute: RefundRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
