-- Learning-assistance system (translation / evidence / explanation / saved
-- vocabulary) — foundation layer. Purely additive: nullable JSONB column on
-- each exercise table, a new per-user saved_expressions table, one new
-- pre-submission-safe translation RPC, and every existing scoring/reveal RPC
-- extended to also return the matching per-item learning_aids slice
-- alongside its existing correct/your_answer/correct_answer fields. No
-- existing column, table, RPC signature (only additive optional params), or
-- scoring logic is changed — original exam content and correctness checks
-- are untouched.
--
-- learning_aids shape (all optional, admin-authored, never AI-generated by
-- default):
--   {
--     "translation": { "text": "...", "questions": { "<itemKey>": "..." } },
--     "items": {
--       "<itemKey>": {
--         "evidence_text": "...", "evidence_translation": "...",
--         "keyword": "...",
--         "explanation_correct": "...", "explanation_wrong": "...",
--         "grammar_structure": "...", "grammar_example": "...", "grammar_translation": "..."
--       }
--     }
--   }
-- "translation" is safe to expose before an attempt is submitted (it never
-- reveals which option is correct). "items" is answer-adjacent and is only
-- ever returned by the scoring/reveal RPCs below, i.e. after the student has
-- submitted or explicitly requested the solution — the same boundary that
-- already protects correct_answer today.

ALTER TABLE lesen_exercises  ADD COLUMN IF NOT EXISTS learning_aids JSONB;
ALTER TABLE hoeren_exercises ADD COLUMN IF NOT EXISTS learning_aids JSONB;
ALTER TABLE sb_exercises     ADD COLUMN IF NOT EXISTS learning_aids JSONB;

-- ── Saved expressions (per-user vocabulary/notes) ──────────────────────────
CREATE TABLE IF NOT EXISTS saved_expressions (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  skill       TEXT NOT NULL CHECK (skill IN ('lesen', 'hoeren', 'sprachbausteine')),
  exercise_id UUID,
  item_key    TEXT,
  category    TEXT NOT NULL CHECK (category IN ('wort', 'verb', 'feste_verbindung', 'redemittel', 'grammatikstruktur', 'wichtiger_ausdruck')),
  german      TEXT NOT NULL,
  grammar     TEXT,
  translation TEXT,
  explanation TEXT,
  example     TEXT,
  is_learned  BOOLEAN NOT NULL DEFAULT FALSE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_saved_expressions_user ON saved_expressions(user_id, created_at DESC);

ALTER TABLE saved_expressions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS saved_expressions_select_own ON saved_expressions;
CREATE POLICY saved_expressions_select_own ON saved_expressions
  FOR SELECT USING (user_id = auth.uid());

DROP POLICY IF EXISTS saved_expressions_insert_own ON saved_expressions;
CREATE POLICY saved_expressions_insert_own ON saved_expressions
  FOR INSERT WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS saved_expressions_update_own ON saved_expressions;
CREATE POLICY saved_expressions_update_own ON saved_expressions
  FOR UPDATE USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS saved_expressions_delete_own ON saved_expressions;
CREATE POLICY saved_expressions_delete_own ON saved_expressions
  FOR DELETE USING (user_id = auth.uid());

-- ── Pre-submission-safe translation RPC ────────────────────────────────────
-- Returns ONLY learning_aids->'translation' (never ->'items', which is
-- answer-adjacent) — safe to call any time the student can already see the
-- exercise text, gated by the identical has_plan_access/free-sample check
-- every content table already enforces.
CREATE OR REPLACE FUNCTION public.get_exercise_translation(p_skill TEXT, p_exercise_id UUID)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_uid UUID := auth.uid();
  v_translation JSONB;
BEGIN
  IF p_skill = 'lesen' THEN
    IF NOT (public.has_plan_access(v_uid, 'schriftlich') OR public.is_d17_staff(v_uid)
            OR EXISTS (SELECT 1 FROM lesen_exercises WHERE id = p_exercise_id AND is_free_sample = true)) THEN
      RAISE EXCEPTION 'Forbidden: active schriftlich subscription required';
    END IF;
    SELECT learning_aids -> 'translation' INTO v_translation FROM lesen_exercises WHERE id = p_exercise_id;
  ELSIF p_skill = 'hoeren' THEN
    IF NOT (public.has_plan_access(v_uid, 'schriftlich') OR public.is_d17_staff(v_uid)
            OR EXISTS (SELECT 1 FROM hoeren_exercises WHERE id = p_exercise_id AND is_free_sample = true)) THEN
      RAISE EXCEPTION 'Forbidden: active schriftlich subscription required';
    END IF;
    SELECT learning_aids -> 'translation' INTO v_translation FROM hoeren_exercises WHERE id = p_exercise_id;
  ELSIF p_skill = 'sprachbausteine' THEN
    IF NOT (public.has_plan_access(v_uid, 'schriftlich') OR public.is_d17_staff(v_uid)
            OR EXISTS (SELECT 1 FROM sb_exercises WHERE id = p_exercise_id AND is_free_sample = true)) THEN
      RAISE EXCEPTION 'Forbidden: active schriftlich subscription required';
    END IF;
    SELECT learning_aids -> 'translation' INTO v_translation FROM sb_exercises WHERE id = p_exercise_id;
  ELSE
    RAISE EXCEPTION 'Invalid skill: %', p_skill;
  END IF;

  RETURN COALESCE(v_translation, 'null'::JSONB);
END;
$function$;

-- ── Extend scoring/reveal RPCs to also return per-item learning_aids ───────
-- Each function is unchanged except for one extra SELECT of the parent
-- exercise's learning_aids before the loop, and one extra key merged into
-- the existing per-item jsonb_build_object. Grading logic, score math, and
-- the attempt INSERT (where present) are byte-for-byte identical to before.

CREATE OR REPLACE FUNCTION public.score_and_save_lesen_t1(p_exercise_id uuid, p_answers jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_uid    UUID := auth.uid();
  v_results JSONB := '[]'::JSONB;
  v_score  INT := 0;
  v_total  INT := 0;
  v_t      RECORD;
  v_chosen TEXT;
  v_ok     BOOLEAN;
  v_attempt UUID;
  v_aids   JSONB;
BEGIN
  IF NOT (public.has_plan_access(v_uid, 'schriftlich') OR public.is_d17_staff(v_uid)
          OR EXISTS (SELECT 1 FROM lesen_exercises WHERE id = p_exercise_id AND is_free_sample = true)) THEN
    RAISE EXCEPTION 'Forbidden: active schriftlich subscription required';
  END IF;

  SELECT learning_aids -> 'items' INTO v_aids FROM lesen_exercises WHERE id = p_exercise_id;

  FOR v_t IN SELECT position, correct_headline FROM lesen_t1_texts WHERE exercise_id = p_exercise_id ORDER BY position LOOP
    v_total := v_total + 1;
    v_chosen := p_answers ->> v_t.position::TEXT;
    v_ok := (UPPER(COALESCE(v_chosen,'')) = UPPER(v_t.correct_headline));
    IF v_ok THEN v_score := v_score + 1; END IF;
    v_results := v_results || jsonb_build_object(
      'position', v_t.position, 'correct', v_ok,
      'your_answer', COALESCE(v_chosen,''),
      'correct_answer', CASE WHEN v_ok THEN v_chosen ELSE v_t.correct_headline END,
      'learning_aids', COALESCE(v_aids -> v_t.position::TEXT, 'null'::JSONB)
    );
  END LOOP;

  INSERT INTO lesen_attempts (user_id, exercise_id, teil, score, total, answers, results)
  VALUES (v_uid, p_exercise_id, 1, v_score, v_total, p_answers, v_results)
  RETURNING id INTO v_attempt;

  RETURN jsonb_build_object('score', v_score, 'total', v_total, 'results', v_results, 'attempt_id', v_attempt);
END;
$function$;

CREATE OR REPLACE FUNCTION public.score_lesen_t1(p_exercise_id uuid, p_answers jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_results    JSONB := '[]'::JSONB;
  v_score      INT   := 0;
  v_total      INT   := 0;
  v_text       RECORD;
  v_chosen     TEXT;
  v_is_correct BOOLEAN;
  v_aids       JSONB;
BEGIN
  IF NOT (public.has_plan_access(auth.uid(), 'schriftlich') OR public.is_d17_staff(auth.uid())) THEN
    RAISE EXCEPTION 'Forbidden: active schriftlich subscription required';
  END IF;

  SELECT learning_aids -> 'items' INTO v_aids FROM lesen_exercises WHERE id = p_exercise_id;

  FOR v_text IN
    SELECT position, correct_headline FROM lesen_t1_texts WHERE exercise_id = p_exercise_id ORDER BY position
  LOOP
    v_total    := v_total + 1;
    v_chosen   := p_answers ->> v_text.position::TEXT;
    v_is_correct := (UPPER(v_chosen) = UPPER(v_text.correct_headline));
    IF v_is_correct THEN v_score := v_score + 1; END IF;
    v_results := v_results || jsonb_build_object(
      'position', v_text.position, 'correct', v_is_correct,
      'your_answer', COALESCE(v_chosen, ''),
      'correct_answer', CASE WHEN v_is_correct THEN v_chosen ELSE v_text.correct_headline END,
      'learning_aids', COALESCE(v_aids -> v_text.position::TEXT, 'null'::JSONB)
    );
  END LOOP;

  RETURN jsonb_build_object('score', v_score, 'total', v_total, 'results', v_results);
END;
$function$;

CREATE OR REPLACE FUNCTION public.score_and_save_lesen_t2(p_exercise_id uuid, p_answers jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_results    JSONB   := '[]'::JSONB;
  v_score      INT     := 0;
  v_total      INT     := 0;
  v_question   RECORD;
  v_chosen     TEXT;
  v_is_correct BOOLEAN;
  v_uid        UUID    := auth.uid();
  v_attempt_id UUID;
  v_aids       JSONB;
BEGIN
  IF NOT (public.has_plan_access(v_uid, 'schriftlich') OR public.is_d17_staff(v_uid)
          OR EXISTS (SELECT 1 FROM lesen_exercises WHERE id = p_exercise_id AND is_free_sample = true)) THEN
    RAISE EXCEPTION 'Forbidden: active schriftlich subscription required';
  END IF;

  SELECT learning_aids -> 'items' INTO v_aids FROM lesen_exercises WHERE id = p_exercise_id;

  FOR v_question IN
    SELECT number, correct FROM lesen_t2_questions WHERE exercise_id = p_exercise_id ORDER BY number
  LOOP
    v_total      := v_total + 1;
    v_chosen     := p_answers ->> v_question.number::TEXT;
    v_is_correct := (v_chosen = v_question.correct);
    IF v_is_correct THEN v_score := v_score + 1; END IF;
    v_results := v_results || jsonb_build_object(
      'number', v_question.number, 'correct', v_is_correct,
      'your_answer', COALESCE(v_chosen, ''),
      'correct_answer', CASE WHEN v_is_correct THEN v_chosen ELSE v_question.correct END,
      'learning_aids', COALESCE(v_aids -> v_question.number::TEXT, 'null'::JSONB)
    );
  END LOOP;

  IF v_total = 0 THEN
    RAISE EXCEPTION 'Exercise % has no questions or does not exist', p_exercise_id;
  END IF;

  INSERT INTO lesen_attempts (user_id, exercise_id, teil, score, total, answers, results)
  VALUES (v_uid, p_exercise_id, 2, v_score, v_total, COALESCE(p_answers, '{}'::JSONB), v_results)
  RETURNING id INTO v_attempt_id;

  RETURN jsonb_build_object('score', v_score, 'total', v_total, 'results', v_results, 'attempt_id', v_attempt_id);
END;
$function$;

CREATE OR REPLACE FUNCTION public.score_lesen_t2(p_exercise_id uuid, p_answers jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_results  JSONB := '[]'::JSONB;
  v_score    INT   := 0;
  v_total    INT   := 0;
  v_question RECORD;
  v_chosen   TEXT;
  v_is_correct BOOLEAN;
  v_aids     JSONB;
BEGIN
  IF NOT (public.has_plan_access(auth.uid(), 'schriftlich') OR public.is_d17_staff(auth.uid())
          OR EXISTS (SELECT 1 FROM lesen_exercises WHERE id = p_exercise_id AND is_free_sample = true)) THEN
    RAISE EXCEPTION 'Forbidden: active schriftlich subscription required';
  END IF;

  SELECT learning_aids -> 'items' INTO v_aids FROM lesen_exercises WHERE id = p_exercise_id;

  FOR v_question IN
    SELECT number, correct FROM lesen_t2_questions WHERE exercise_id = p_exercise_id ORDER BY number
  LOOP
    v_total    := v_total + 1;
    v_chosen   := p_answers ->> v_question.number::TEXT;
    v_is_correct := (v_chosen = v_question.correct);
    IF v_is_correct THEN v_score := v_score + 1; END IF;
    v_results := v_results || jsonb_build_object(
      'number', v_question.number, 'correct', v_is_correct,
      'your_answer', COALESCE(v_chosen, ''),
      'correct_answer', CASE WHEN v_is_correct THEN v_chosen ELSE v_question.correct END,
      'learning_aids', COALESCE(v_aids -> v_question.number::TEXT, 'null'::JSONB)
    );
  END LOOP;

  RETURN jsonb_build_object('score', v_score, 'total', v_total, 'results', v_results);
END;
$function$;

CREATE OR REPLACE FUNCTION public.score_lesen_t3(p_exercise_id uuid, p_answers jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_results    JSONB := '[]'::JSONB;
  v_score      INT   := 0;
  v_total      INT   := 0;
  v_situation  RECORD;
  v_chosen     TEXT;
  v_is_correct BOOLEAN;
  v_aids       JSONB;
BEGIN
  IF NOT (public.has_plan_access(auth.uid(), 'schriftlich') OR public.is_d17_staff(auth.uid())
          OR EXISTS (SELECT 1 FROM lesen_exercises WHERE id = p_exercise_id AND is_free_sample = true)) THEN
    RAISE EXCEPTION 'Forbidden: active schriftlich subscription required';
  END IF;

  SELECT learning_aids -> 'items' INTO v_aids FROM lesen_exercises WHERE id = p_exercise_id;

  FOR v_situation IN
    SELECT number, correct_letter, no_match FROM lesen_t3_situations WHERE exercise_id = p_exercise_id ORDER BY number
  LOOP
    v_total    := v_total + 1;
    v_chosen   := p_answers ->> v_situation.number::TEXT;
    IF v_situation.no_match THEN
      v_is_correct := (v_chosen = '0' OR v_chosen IS NULL OR v_chosen = '');
    ELSE
      v_is_correct := (LOWER(v_chosen) = LOWER(v_situation.correct_letter));
    END IF;
    IF v_is_correct THEN v_score := v_score + 1; END IF;
    v_results := v_results || jsonb_build_object(
      'number', v_situation.number, 'correct', v_is_correct,
      'your_answer', COALESCE(v_chosen, ''),
      'correct_answer', CASE WHEN v_situation.no_match THEN '0' WHEN v_is_correct THEN v_chosen ELSE v_situation.correct_letter END,
      'learning_aids', COALESCE(v_aids -> v_situation.number::TEXT, 'null'::JSONB)
    );
  END LOOP;

  RETURN jsonb_build_object('score', v_score, 'total', v_total, 'results', v_results);
END;
$function$;

CREATE OR REPLACE FUNCTION public.score_and_save_hoeren(p_exercise_id uuid, p_answers jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_uid        UUID := auth.uid();
  v_results    JSONB := '[]'::JSONB;
  v_score      INT   := 0;
  v_total      INT   := 0;
  v_teil       SMALLINT;
  v_s          RECORD;
  v_chosen     BOOLEAN;
  v_is_correct BOOLEAN;
  v_attempt    UUID;
  v_aids       JSONB;
BEGIN
  IF NOT (public.has_plan_access(v_uid, 'schriftlich') OR public.is_d17_staff(v_uid)
          OR EXISTS (SELECT 1 FROM hoeren_exercises WHERE id = p_exercise_id AND is_free_sample = true)) THEN
    RAISE EXCEPTION 'Forbidden: active schriftlich subscription required';
  END IF;

  SELECT teil, learning_aids -> 'items' INTO v_teil, v_aids FROM hoeren_exercises WHERE id = p_exercise_id;

  FOR v_s IN
    SELECT statement_number, correct_answer FROM hoeren_statements WHERE exercise_id = p_exercise_id ORDER BY statement_number
  LOOP
    v_total  := v_total + 1;
    v_chosen := (p_answers ->> v_s.statement_number::TEXT)::BOOLEAN;
    v_is_correct := (v_chosen IS NOT NULL AND v_chosen = v_s.correct_answer);
    IF v_is_correct THEN v_score := v_score + 1; END IF;
    v_results := v_results || jsonb_build_object(
      'statement_number', v_s.statement_number, 'correct', v_is_correct,
      'your_answer', to_jsonb(v_chosen), 'correct_answer', to_jsonb(v_s.correct_answer),
      'learning_aids', COALESCE(v_aids -> v_s.statement_number::TEXT, 'null'::JSONB)
    );
  END LOOP;

  INSERT INTO hoeren_attempts (user_id, exercise_id, teil, score, total, answers, results)
  VALUES (v_uid, p_exercise_id, COALESCE(v_teil, 1), v_score, v_total, p_answers, v_results)
  RETURNING id INTO v_attempt;

  RETURN jsonb_build_object('score', v_score, 'total', v_total, 'results', v_results, 'attempt_id', v_attempt);
END;
$function$;

CREATE OR REPLACE FUNCTION public.reveal_hoeren(p_exercise_id uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_results JSONB := '[]'::JSONB;
  v_s       RECORD;
  v_aids    JSONB;
BEGIN
  IF NOT (public.has_plan_access(auth.uid(), 'schriftlich') OR public.is_d17_staff(auth.uid())
          OR EXISTS (SELECT 1 FROM hoeren_exercises WHERE id = p_exercise_id AND is_free_sample = true)) THEN
    RAISE EXCEPTION 'Forbidden: active schriftlich subscription required';
  END IF;

  SELECT learning_aids -> 'items' INTO v_aids FROM hoeren_exercises WHERE id = p_exercise_id;

  FOR v_s IN
    SELECT statement_number, correct_answer FROM hoeren_statements WHERE exercise_id = p_exercise_id ORDER BY statement_number
  LOOP
    v_results := v_results || jsonb_build_object(
      'statement_number', v_s.statement_number, 'correct_answer', to_jsonb(v_s.correct_answer),
      'learning_aids', COALESCE(v_aids -> v_s.statement_number::TEXT, 'null'::JSONB)
    );
  END LOOP;

  RETURN jsonb_build_object('results', v_results);
END;
$function$;

CREATE OR REPLACE FUNCTION public.score_sb_t1(p_exercise_id uuid, p_answers jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_results    JSONB := '[]'::JSONB;
  v_score      INT   := 0;
  v_total      INT   := 0;
  v_gap        RECORD;
  v_chosen     TEXT;
  v_is_correct BOOLEAN;
  v_aids       JSONB;
BEGIN
  IF NOT (public.has_plan_access(auth.uid(), 'schriftlich') OR public.is_d17_staff(auth.uid())
          OR EXISTS (SELECT 1 FROM sb_exercises WHERE id = p_exercise_id AND is_free_sample = true)) THEN
    RAISE EXCEPTION 'Forbidden: active schriftlich subscription required';
  END IF;

  SELECT learning_aids -> 'items' INTO v_aids FROM sb_exercises WHERE id = p_exercise_id;

  FOR v_gap IN
    SELECT gap_number, correct FROM sb_t1_gaps WHERE exercise_id = p_exercise_id ORDER BY gap_number
  LOOP
    v_total      := v_total + 1;
    v_chosen     := p_answers ->> v_gap.gap_number::TEXT;
    v_is_correct := (LOWER(v_chosen) = LOWER(v_gap.correct));
    IF v_is_correct THEN v_score := v_score + 1; END IF;
    v_results := v_results || jsonb_build_object(
      'gap_number', v_gap.gap_number, 'correct', v_is_correct,
      'your_answer', COALESCE(v_chosen, ''),
      'correct_answer', CASE WHEN v_is_correct THEN v_chosen ELSE v_gap.correct END,
      'learning_aids', COALESCE(v_aids -> v_gap.gap_number::TEXT, 'null'::JSONB)
    );
  END LOOP;

  RETURN jsonb_build_object('score', v_score, 'total', v_total, 'results', v_results);
END;
$function$;

CREATE OR REPLACE FUNCTION public.score_sb_t2(p_exercise_id uuid, p_answers jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_results    JSONB := '[]'::JSONB;
  v_score      INT   := 0;
  v_total      INT   := 0;
  v_gap        RECORD;
  v_chosen     TEXT;
  v_is_correct BOOLEAN;
  v_aids       JSONB;
BEGIN
  IF NOT (public.has_plan_access(auth.uid(), 'schriftlich') OR public.is_d17_staff(auth.uid())
          OR EXISTS (SELECT 1 FROM sb_exercises WHERE id = p_exercise_id AND is_free_sample = true)) THEN
    RAISE EXCEPTION 'Forbidden: active schriftlich subscription required';
  END IF;

  SELECT learning_aids -> 'items' INTO v_aids FROM sb_exercises WHERE id = p_exercise_id;

  FOR v_gap IN
    SELECT gap_number, correct_word FROM sb_t2_gaps WHERE exercise_id = p_exercise_id ORDER BY gap_number
  LOOP
    v_total      := v_total + 1;
    v_chosen     := p_answers ->> v_gap.gap_number::TEXT;
    v_is_correct := (LOWER(TRIM(v_chosen)) = LOWER(TRIM(v_gap.correct_word)));
    IF v_is_correct THEN v_score := v_score + 1; END IF;
    v_results := v_results || jsonb_build_object(
      'gap_number', v_gap.gap_number, 'correct', v_is_correct,
      'your_answer', COALESCE(v_chosen, ''),
      'correct_answer', CASE WHEN v_is_correct THEN v_chosen ELSE v_gap.correct_word END,
      'learning_aids', COALESCE(v_aids -> v_gap.gap_number::TEXT, 'null'::JSONB)
    );
  END LOOP;

  RETURN jsonb_build_object('score', v_score, 'total', v_total, 'results', v_results);
END;
$function$;

-- ── Admin authoring: optional learning_aids on exercise creation ──────────
-- Appended as a final DEFAULT-NULL parameter on every admin_create_* RPC, so
-- existing call sites (which don't pass it yet) keep working unchanged.

CREATE OR REPLACE FUNCTION public.admin_create_lesen_t1_exercise(p_created_by uuid, p_title text, p_level text, p_import_notes text, p_headlines jsonb, p_texts jsonb, p_learning_aids jsonb DEFAULT NULL)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_base TEXT; v_title TEXT; v_n INT := 0;
  v_h JSONB; v_t JSONB; v_letter TEXT;
  v_distractor_count INT; v_correct_count INT;
  v_ex_id UUID; v_letters TEXT[]; v_sort_order INT;
BEGIN
  IF p_level NOT IN ('TELC_B1', 'TELC_B2') THEN RAISE EXCEPTION 'Invalid level: %', p_level; END IF;

  IF COALESCE(jsonb_array_length(p_headlines), 0) <> 10 THEN
    RAISE EXCEPTION 'Expected 10 headlines, got %', COALESCE(jsonb_array_length(p_headlines), 0);
  END IF;
  v_letters := '{}'; v_distractor_count := 0;
  FOR v_h IN SELECT * FROM jsonb_array_elements(p_headlines) LOOP
    v_letter := UPPER(COALESCE(v_h->>'letter', ''));
    IF v_letter !~ '^[A-J]$' THEN RAISE EXCEPTION 'Invalid headline letter: %', v_letter; END IF;
    IF v_letter = ANY(v_letters) THEN RAISE EXCEPTION 'Duplicate headline letter: %', v_letter; END IF;
    IF COALESCE(btrim(v_h->>'text'), '') = '' THEN RAISE EXCEPTION 'Headline % has empty text', v_letter; END IF;
    v_letters := array_append(v_letters, v_letter);
    IF COALESCE((v_h->>'is_distractor')::BOOLEAN, FALSE) THEN v_distractor_count := v_distractor_count + 1; END IF;
  END LOOP;
  IF v_distractor_count <> 5 THEN RAISE EXCEPTION 'Expected 5 distractor headlines, got %', v_distractor_count; END IF;

  IF COALESCE(jsonb_array_length(p_texts), 0) <> 5 THEN
    RAISE EXCEPTION 'Expected 5 texts, got %', COALESCE(jsonb_array_length(p_texts), 0);
  END IF;
  FOR v_t IN SELECT * FROM jsonb_array_elements(p_texts) LOOP
    IF (v_t->>'position')::INT NOT BETWEEN 1 AND 5 THEN RAISE EXCEPTION 'Invalid text position'; END IF;
    IF COALESCE(btrim(v_t->>'content'), '') = '' THEN RAISE EXCEPTION 'Text % has empty content', v_t->>'position'; END IF;
    v_letter := UPPER(COALESCE(v_t->>'correct_headline', ''));
    IF v_letter !~ '^[A-J]$' THEN RAISE EXCEPTION 'Text % has invalid correct_headline', v_t->>'position'; END IF;
    IF NOT EXISTS (
      SELECT 1 FROM jsonb_array_elements(p_headlines) h
      WHERE UPPER(h->>'letter') = v_letter AND NOT COALESCE((h->>'is_distractor')::BOOLEAN, FALSE)
    ) THEN RAISE EXCEPTION 'Text % correct_headline % is not a valid (non-distractor) headline', v_t->>'position', v_letter; END IF;
  END LOOP;
  SELECT COUNT(DISTINCT UPPER(t->>'correct_headline')) INTO v_correct_count FROM jsonb_array_elements(p_texts) t;
  IF v_correct_count <> 5 THEN RAISE EXCEPTION 'Texts must map to 5 distinct headlines, got %', v_correct_count; END IF;

  v_base := NULLIF(btrim(COALESCE(p_title, '')), '');
  IF v_base IS NULL THEN
    v_title := '';
  ELSE
    v_title := v_base;
    WHILE EXISTS (SELECT 1 FROM lesen_exercises WHERE teil = 1 AND level = p_level AND title = v_title) LOOP
      v_n := v_n + 1;
      v_title := v_base || ' ' || v_n;
    END LOOP;
  END IF;

  SELECT COALESCE(MAX(sort_order), 0) + 1 INTO v_sort_order FROM lesen_exercises WHERE teil = 1 AND level = p_level;

  INSERT INTO lesen_exercises (title, teil, level, source_pdf, import_notes, created_by, sort_order, learning_aids)
  VALUES (v_title, 1, p_level, NULL, p_import_notes, p_created_by, v_sort_order, p_learning_aids)
  RETURNING id INTO v_ex_id;

  INSERT INTO lesen_t1_headlines (exercise_id, letter, text, is_distractor)
  SELECT v_ex_id, UPPER(h->>'letter'), h->>'text', COALESCE((h->>'is_distractor')::BOOLEAN, FALSE)
  FROM jsonb_array_elements(p_headlines) h;

  INSERT INTO lesen_t1_texts (exercise_id, position, title, content, correct_headline)
  SELECT v_ex_id, (t->>'position')::SMALLINT, NULLIF(btrim(COALESCE(t->>'title','')),''), t->>'content', UPPER(t->>'correct_headline')
  FROM jsonb_array_elements(p_texts) t;

  RETURN jsonb_build_object('exercise_id', v_ex_id, 'title', v_title);
END;
$function$;

CREATE OR REPLACE FUNCTION public.admin_create_lesen_t2_exercise(p_created_by uuid, p_title text, p_level text, p_import_notes text, p_passage text, p_questions jsonb, p_learning_aids jsonb DEFAULT NULL)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_base TEXT; v_title TEXT; v_n INT := 0; v_count INT; v_q JSONB; v_ex_id UUID; v_sort_order INT;
BEGIN
  IF p_level NOT IN ('TELC_B1', 'TELC_B2') THEN RAISE EXCEPTION 'Invalid level: %', p_level; END IF;
  IF p_passage IS NULL OR length(btrim(p_passage)) = 0 THEN RAISE EXCEPTION 'Passage is empty'; END IF;

  v_count := COALESCE(jsonb_array_length(p_questions), 0);
  IF v_count = 0 THEN RAISE EXCEPTION 'No questions provided'; END IF;
  FOR v_q IN SELECT * FROM jsonb_array_elements(p_questions) LOOP
    IF COALESCE(btrim(v_q->>'question'), '') = '' THEN RAISE EXCEPTION 'A question has empty text'; END IF;
    IF COALESCE(btrim(v_q->>'option_a'), '') = '' THEN RAISE EXCEPTION 'A question has an empty option a'; END IF;
    IF COALESCE(btrim(v_q->>'option_b'), '') = '' THEN RAISE EXCEPTION 'A question has an empty option b'; END IF;
    IF COALESCE(btrim(v_q->>'option_c'), '') = '' THEN RAISE EXCEPTION 'A question has an empty option c'; END IF;
    IF LOWER(COALESCE(v_q->>'correct', '')) NOT IN ('a','b','c') THEN RAISE EXCEPTION 'A question has an invalid answer key'; END IF;
  END LOOP;

  v_base := NULLIF(btrim(COALESCE(p_title, '')), '');
  IF v_base IS NULL THEN
    v_title := '';
  ELSE
    v_title := v_base;
    WHILE EXISTS (SELECT 1 FROM lesen_exercises WHERE teil = 2 AND level = p_level AND title = v_title) LOOP
      v_n := v_n + 1;
      v_title := v_base || ' ' || v_n;
    END LOOP;
  END IF;

  SELECT COALESCE(MAX(sort_order), 0) + 1 INTO v_sort_order FROM lesen_exercises WHERE teil = 2 AND level = p_level;

  INSERT INTO lesen_exercises (title, teil, level, source_pdf, import_notes, created_by, sort_order, learning_aids)
  VALUES (v_title, 2, p_level, NULL, p_import_notes, p_created_by, v_sort_order, p_learning_aids)
  RETURNING id INTO v_ex_id;

  INSERT INTO lesen_t2_passages (exercise_id, title, instructions, passage)
  VALUES (v_ex_id, v_title, '', p_passage);

  INSERT INTO lesen_t2_questions (exercise_id, number, question, option_a, option_b, option_c, correct)
  SELECT v_ex_id, (q->>'number')::SMALLINT, q->>'question', q->>'option_a', q->>'option_b', q->>'option_c', LOWER(q->>'correct')
  FROM jsonb_array_elements(p_questions) q;

  RETURN jsonb_build_object('exercise_id', v_ex_id, 'title', v_title);
END;
$function$;

CREATE OR REPLACE FUNCTION public.admin_create_lesen_t3_exercise(p_created_by uuid, p_title text, p_level text, p_import_notes text, p_texts jsonb, p_situations jsonb, p_learning_aids jsonb DEFAULT NULL)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_base TEXT; v_title TEXT; v_n INT := 0; v_ex_id UUID; v_sort_order INT;
  v_t JSONB; v_s JSONB; v_letter TEXT; v_letters TEXT[];
BEGIN
  IF p_level NOT IN ('TELC_B1', 'TELC_B2') THEN RAISE EXCEPTION 'Invalid level: %', p_level; END IF;
  IF COALESCE(jsonb_array_length(p_texts), 0) < 1 THEN RAISE EXCEPTION 'At least one ad/text is required'; END IF;
  IF COALESCE(jsonb_array_length(p_situations), 0) < 1 THEN RAISE EXCEPTION 'At least one situation is required'; END IF;

  v_letters := '{}';
  FOR v_t IN SELECT * FROM jsonb_array_elements(p_texts) LOOP
    v_letter := UPPER(COALESCE(v_t->>'letter', ''));
    IF v_letter !~ '^[A-Z]$' THEN RAISE EXCEPTION 'Invalid ad letter: %', v_letter; END IF;
    IF v_letter = ANY(v_letters) THEN RAISE EXCEPTION 'Duplicate ad letter: %', v_letter; END IF;
    IF COALESCE(btrim(v_t->>'content'), '') = '' THEN RAISE EXCEPTION 'Ad % has empty content', v_letter; END IF;
    v_letters := array_append(v_letters, v_letter);
  END LOOP;

  FOR v_s IN SELECT * FROM jsonb_array_elements(p_situations) LOOP
    IF COALESCE(btrim(v_s->>'description'), '') = '' THEN RAISE EXCEPTION 'A situation has empty description'; END IF;
    IF COALESCE((v_s->>'no_match')::BOOLEAN, FALSE) THEN
      CONTINUE;
    END IF;
    v_letter := UPPER(COALESCE(v_s->>'correct_letter', ''));
    IF v_letter = '' OR NOT (v_letter = ANY(v_letters)) THEN
      RAISE EXCEPTION 'Situation % has correct_letter % that does not match any ad letter', v_s->>'number', v_letter;
    END IF;
  END LOOP;

  v_base := NULLIF(btrim(COALESCE(p_title, '')), '');
  IF v_base IS NULL THEN
    v_title := '';
  ELSE
    v_title := v_base;
    WHILE EXISTS (SELECT 1 FROM lesen_exercises WHERE teil = 3 AND level = p_level AND title = v_title) LOOP
      v_n := v_n + 1;
      v_title := v_base || ' ' || v_n;
    END LOOP;
  END IF;

  SELECT COALESCE(MAX(sort_order), 0) + 1 INTO v_sort_order FROM lesen_exercises WHERE teil = 3 AND level = p_level;

  INSERT INTO lesen_exercises (title, teil, level, source_pdf, import_notes, created_by, sort_order, learning_aids)
  VALUES (v_title, 3, p_level, NULL, p_import_notes, p_created_by, v_sort_order, p_learning_aids)
  RETURNING id INTO v_ex_id;

  INSERT INTO lesen_t3_texts (exercise_id, letter, title, content)
  SELECT v_ex_id, UPPER(t->>'letter'), NULLIF(btrim(COALESCE(t->>'title','')),''), t->>'content'
  FROM jsonb_array_elements(p_texts) t;

  INSERT INTO lesen_t3_situations (exercise_id, number, description, correct_letter, no_match)
  SELECT v_ex_id, (s->>'number')::SMALLINT, s->>'description',
         CASE WHEN COALESCE((s->>'no_match')::BOOLEAN, FALSE) THEN NULL ELSE UPPER(s->>'correct_letter') END,
         COALESCE((s->>'no_match')::BOOLEAN, FALSE)
  FROM jsonb_array_elements(p_situations) s;

  RETURN jsonb_build_object('exercise_id', v_ex_id, 'title', v_title);
END;
$function$;

CREATE OR REPLACE FUNCTION public.admin_create_hoeren_exercise(p_created_by uuid, p_title text, p_teil smallint, p_level text, p_import_notes text, p_instructions text, p_image_path text, p_audio_path text, p_statements jsonb, p_learning_aids jsonb DEFAULT NULL)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_base TEXT; v_title TEXT; v_n INT := 0; v_ex_id UUID; v_position INT;
  v_s JSONB; v_numbers INT[];
BEGIN
  IF p_teil NOT IN (1, 2, 3) THEN RAISE EXCEPTION 'Invalid teil: %', p_teil; END IF;
  IF p_level NOT IN ('TELC_B1', 'TELC_B2') THEN RAISE EXCEPTION 'Invalid level: %', p_level; END IF;
  IF COALESCE(jsonb_array_length(p_statements), 0) <> 5 THEN
    RAISE EXCEPTION 'Expected 5 statements, got %', COALESCE(jsonb_array_length(p_statements), 0);
  END IF;

  v_numbers := '{}';
  FOR v_s IN SELECT * FROM jsonb_array_elements(p_statements) LOOP
    IF COALESCE(btrim(v_s->>'statement_text'), '') = '' THEN RAISE EXCEPTION 'A statement has empty text'; END IF;
    IF v_s->>'correct_answer' IS NULL THEN RAISE EXCEPTION 'A statement is missing correct_answer'; END IF;
    IF (v_s->>'statement_number')::INT = ANY(v_numbers) THEN RAISE EXCEPTION 'Duplicate statement_number: %', v_s->>'statement_number'; END IF;
    v_numbers := array_append(v_numbers, (v_s->>'statement_number')::INT);
  END LOOP;

  v_base := NULLIF(btrim(COALESCE(p_title, '')), '');
  IF v_base IS NULL THEN RAISE EXCEPTION 'Title is required'; END IF;
  v_title := v_base;
  WHILE EXISTS (SELECT 1 FROM hoeren_exercises WHERE teil = p_teil AND level = p_level AND title = v_title) LOOP
    v_n := v_n + 1;
    v_title := v_base || ' ' || v_n;
  END LOOP;

  SELECT COALESCE(MAX(position), 0) + 1 INTO v_position FROM hoeren_exercises WHERE teil = p_teil AND level = p_level;

  INSERT INTO hoeren_exercises (title, teil, level, image_path, instructions, source_pdf, import_notes, position, audio_path, created_by, learning_aids)
  VALUES (v_title, p_teil, p_level, NULLIF(p_image_path, ''), NULLIF(p_instructions, ''), NULL, p_import_notes, v_position, NULLIF(p_audio_path, ''), p_created_by, p_learning_aids)
  RETURNING id INTO v_ex_id;

  INSERT INTO hoeren_statements (exercise_id, statement_number, statement_text, correct_answer)
  SELECT v_ex_id, (s->>'statement_number')::SMALLINT, s->>'statement_text', (s->>'correct_answer')::BOOLEAN
  FROM jsonb_array_elements(p_statements) s;

  RETURN jsonb_build_object('exercise_id', v_ex_id, 'title', v_title);
END;
$function$;

CREATE OR REPLACE FUNCTION public.admin_create_sb_t1_exercise(p_created_by uuid, p_title text, p_level text, p_import_notes text, p_passage text, p_instructions text, p_gaps jsonb, p_learning_aids jsonb DEFAULT NULL)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_base TEXT; v_title TEXT; v_n INT := 0; v_ex_id UUID; v_position INT;
  v_g JSONB; v_numbers INT[];
BEGIN
  IF p_level NOT IN ('TELC_B1', 'TELC_B2') THEN RAISE EXCEPTION 'Invalid level: %', p_level; END IF;
  IF p_passage IS NULL OR length(btrim(p_passage)) = 0 THEN RAISE EXCEPTION 'Passage is empty'; END IF;
  IF COALESCE(jsonb_array_length(p_gaps), 0) < 1 THEN RAISE EXCEPTION 'At least one gap is required'; END IF;

  v_numbers := '{}';
  FOR v_g IN SELECT * FROM jsonb_array_elements(p_gaps) LOOP
    IF COALESCE(btrim(v_g->>'option_a'), '') = '' THEN RAISE EXCEPTION 'A gap has an empty option a'; END IF;
    IF COALESCE(btrim(v_g->>'option_b'), '') = '' THEN RAISE EXCEPTION 'A gap has an empty option b'; END IF;
    IF COALESCE(btrim(v_g->>'option_c'), '') = '' THEN RAISE EXCEPTION 'A gap has an empty option c'; END IF;
    IF LOWER(COALESCE(v_g->>'correct', '')) NOT IN ('a','b','c') THEN RAISE EXCEPTION 'A gap has an invalid answer key'; END IF;
    IF (v_g->>'gap_number')::INT = ANY(v_numbers) THEN RAISE EXCEPTION 'Duplicate gap_number: %', v_g->>'gap_number'; END IF;
    v_numbers := array_append(v_numbers, (v_g->>'gap_number')::INT);
  END LOOP;

  v_base := NULLIF(btrim(COALESCE(p_title, '')), '');
  IF v_base IS NULL THEN RAISE EXCEPTION 'Title is required'; END IF;
  v_title := v_base;
  WHILE EXISTS (SELECT 1 FROM sb_exercises WHERE teil = 1 AND level = p_level AND title = v_title) LOOP
    v_n := v_n + 1;
    v_title := v_base || ' ' || v_n;
  END LOOP;

  SELECT COALESCE(MAX(position), 0) + 1 INTO v_position FROM sb_exercises WHERE teil = 1 AND level = p_level;

  INSERT INTO sb_exercises (title, teil, level, source_pdf, import_notes, created_by, position, learning_aids)
  VALUES (v_title, 1, p_level, NULL, p_import_notes, p_created_by, v_position, p_learning_aids)
  RETURNING id INTO v_ex_id;

  INSERT INTO sb_t1_passages (exercise_id, title, instructions, passage)
  VALUES (v_ex_id, v_title, NULLIF(p_instructions, ''), p_passage);

  INSERT INTO sb_t1_gaps (exercise_id, gap_number, option_a, option_b, option_c, correct)
  SELECT v_ex_id, (g->>'gap_number')::SMALLINT, g->>'option_a', g->>'option_b', g->>'option_c', LOWER(g->>'correct')
  FROM jsonb_array_elements(p_gaps) g;

  RETURN jsonb_build_object('exercise_id', v_ex_id, 'title', v_title);
END;
$function$;

CREATE OR REPLACE FUNCTION public.admin_create_sb_t2_exercise(p_created_by uuid, p_title text, p_level text, p_import_notes text, p_passage text, p_instructions text, p_words jsonb, p_gaps jsonb, p_learning_aids jsonb DEFAULT NULL)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_base TEXT; v_title TEXT; v_n INT := 0; v_ex_id UUID; v_position INT;
  v_w JSONB; v_g JSONB; v_words TEXT[]; v_wnumbers INT[]; v_gnumbers INT[];
BEGIN
  IF p_level NOT IN ('TELC_B1', 'TELC_B2') THEN RAISE EXCEPTION 'Invalid level: %', p_level; END IF;
  IF p_passage IS NULL OR length(btrim(p_passage)) = 0 THEN RAISE EXCEPTION 'Passage is empty'; END IF;
  IF COALESCE(jsonb_array_length(p_words), 0) < 1 THEN RAISE EXCEPTION 'At least one word is required'; END IF;
  IF COALESCE(jsonb_array_length(p_gaps), 0) < 1 THEN RAISE EXCEPTION 'At least one gap is required'; END IF;

  v_words := '{}'; v_wnumbers := '{}';
  FOR v_w IN SELECT * FROM jsonb_array_elements(p_words) LOOP
    IF COALESCE(btrim(v_w->>'word'), '') = '' THEN RAISE EXCEPTION 'A word entry is empty'; END IF;
    IF (v_w->>'word_number')::INT = ANY(v_wnumbers) THEN RAISE EXCEPTION 'Duplicate word_number: %', v_w->>'word_number'; END IF;
    v_wnumbers := array_append(v_wnumbers, (v_w->>'word_number')::INT);
    v_words := array_append(v_words, btrim(v_w->>'word'));
  END LOOP;

  v_gnumbers := '{}';
  FOR v_g IN SELECT * FROM jsonb_array_elements(p_gaps) LOOP
    IF COALESCE(btrim(v_g->>'correct_word'), '') = '' THEN RAISE EXCEPTION 'A gap has an empty correct_word'; END IF;
    IF NOT (btrim(v_g->>'correct_word') = ANY(v_words)) THEN
      RAISE EXCEPTION 'Gap % correct_word "%" does not match any word in the word bank', v_g->>'gap_number', v_g->>'correct_word';
    END IF;
    IF (v_g->>'gap_number')::INT = ANY(v_gnumbers) THEN RAISE EXCEPTION 'Duplicate gap_number: %', v_g->>'gap_number'; END IF;
    v_gnumbers := array_append(v_gnumbers, (v_g->>'gap_number')::INT);
  END LOOP;

  v_base := NULLIF(btrim(COALESCE(p_title, '')), '');
  IF v_base IS NULL THEN RAISE EXCEPTION 'Title is required'; END IF;
  v_title := v_base;
  WHILE EXISTS (SELECT 1 FROM sb_exercises WHERE teil = 2 AND level = p_level AND title = v_title) LOOP
    v_n := v_n + 1;
    v_title := v_base || ' ' || v_n;
  END LOOP;

  SELECT COALESCE(MAX(position), 0) + 1 INTO v_position FROM sb_exercises WHERE teil = 2 AND level = p_level;

  INSERT INTO sb_exercises (title, teil, level, source_pdf, import_notes, created_by, position, learning_aids)
  VALUES (v_title, 2, p_level, NULL, p_import_notes, p_created_by, v_position, p_learning_aids)
  RETURNING id INTO v_ex_id;

  INSERT INTO sb_t2_passages (exercise_id, title, instructions, passage)
  VALUES (v_ex_id, v_title, NULLIF(p_instructions, ''), p_passage);

  INSERT INTO sb_t2_words (exercise_id, word_number, word)
  SELECT v_ex_id, (w->>'word_number')::SMALLINT, btrim(w->>'word')
  FROM jsonb_array_elements(p_words) w;

  INSERT INTO sb_t2_gaps (exercise_id, gap_number, correct_word)
  SELECT v_ex_id, (g->>'gap_number')::SMALLINT, btrim(g->>'correct_word')
  FROM jsonb_array_elements(p_gaps) g;

  RETURN jsonb_build_object('exercise_id', v_ex_id, 'title', v_title);
END;
$function$;

GRANT EXECUTE ON FUNCTION public.get_exercise_translation(TEXT, UUID) TO authenticated, anon;
