// SB Teil 1 restyle — batch 07: [30] Sprachen lernen mit sechzig, [31] Jutta, [32] Julia, [33] Lina (gap 26 FLAGGED, omitted), [34] Liebe Sandra Original (gap 27 FLAGGED, omitted)
export default {
  // ───────────── [30] Sprachen lernen mit sechzig ─────────────
  30: {
    21: { ok: "den", type: "pronoun", keyword: "Relativpronomen: Genus + Kasus", bed: "اللي (الرسالة اللي تلقّيتها)",
      text: `الفراغ يبدا جملة فرعية تعرّف بـ "Brief" (مذكّر)، وفي الجملة هذي "ich" هو الفاعل، يعني "Brief" هو المفعول به (Akkusativ): "den".\n✓ "den" = Akkusativ مذكّر (den Brief erhalten).\n✗ "das" = للمحايد (das Buch)، و"Brief" مذكّر.\n✗ "der" = مذكّر بصح Nominativ (الفاعل)، وهنا الفاعل "ich" و"Brief" هو المفعول به.`,
      rule: "Relativpronomen: das Genus kommt vom Bezugswort, der Kasus vom Relativsatz", ex: "Der Brief, **den** ich bekommen habe, war nett.", exTr: "الرسالة اللي جاتني كانت لطيفة." },
    22: { ok: "hast", type: "tense", keyword: "haben + Partizip II (verbringen)", bed: "قضّيتي (عطلة لطيفة)",
      text: `"verbracht" هو Partizip II من "verbringen"، و"du" هو الفاعل: Perfekt بـ "haben": "du hast … verbracht".\n✓ "hast" = Perfekt مع "haben" (verbringen ياخذ مفعول به، موش حركة).\n✗ "bist" = Perfekt بـ "sein" (للحركة والتحوّل: "du bist gefahren")، و"verbringen" ما ياخذش "sein".\n✗ "warst" = Präteritum من "sein"، وما ينجّمش يجي مع Partizip II "verbracht" كأنّها جملة كاملة.`,
      rule: "Perfekt mit haben: transitive Verben (verbringen, machen, sehen …)", ex: "Du **hast** den Sommer in Italien verbracht.", exTr: "قضّيت الصيف في إيطاليا." },
    23: { ok: "mich", type: "pronoun", keyword: "jdn. fragen + Akk.", bed: "سألتني (أنا)",
      text: `"fragen" ياخذ Akkusativ للشخص: "du hast mich gefragt".\n✓ "mich" = Akkusativ لـ "ich".\n✗ "mir" = Dativ (مع "helfen، gefallen")، و"fragen" ما ياخذش Dativ.\n✗ "sich" = ضمير انعكاسي للغائب (er / sie / es)، والفاعل هنا "du" وما فماش فعل انعكاسي.`,
      rule: "jdn. fragen + Akkusativ (Ich frage dich, er fragt mich)", ex: "Er hat **mich** nach dem Weg gefragt.", exTr: "سألني على الطريق." },
    24: { ok: "doch", type: "conjunction", keyword: "doch = aber (Gegensatz)", bed: "بصح (لكن)",
      text: `الجملة الأولى تعترف (ما عدناش صغار)، والثانية تعارضها (بصح للتعلّم مازلنا صغار): رابط تعارض يجي في الأول و"sind" بعدو مباشرة.\n✓ "doch" = بصح / لكن (Position 0، والفعل بعدو في المرتبة الثانية).\n✗ "obwohl" = رغم إنّو (Nebensatz)، والفعل يمشي للآخر، وهنا "sind" في المرتبة الثانية.\n✗ "sondern" = بل (يصحّح كلام منفي مباشرة: "nicht A, sondern B")، وهنا ما فماش تصحيح لنفس العنصر.`,
      rule: "doch (Hauptsatz) = aber  |  obwohl + Nebensatz  |  sondern nach Verneinung", ex: "Ich bin müde, **doch** ich gehe noch laufen.", exTr: "تعبان، بصح باش نمشي نجري." },
    25: { ok: "noch", type: "adjective_adverb", keyword: "noch jung genug", bed: "لسّا صغار بما فيه الكفاية",
      text: `الفكرة: "نجّمو نتعلّمو لغة وإحنا لسّا صغار بما فيه الكفاية": "noch jung genug".\n✓ "noch" = لسّا (الحالة تتواصل).\n✗ "schon" = توّا / خلاص (حاجة صارت بكري)، و"schon jung genug" تتقال لواحد صغير برشا، موش لواحد عمرو ستّين.\n✗ "erst" = غير توّا (بداية متأخرة: "erst um acht")، وما تتركّبش مع "jung genug".`,
      rule: "noch + Adjektiv = immer noch  |  schon = früher als erwartet  |  erst = nicht früher", ex: "Du bist **noch** jung genug dafür.", exTr: "إنت لسّا صغير كفاية لهذا." },
    26: { ok: "bedient", type: "verb", keyword: "einen Computer bedienen", bed: "يشغّل (الكمبيوتر)",
      text: `"كيفاش الواحد يشغّل كمبيوتر": الفعل المعتاد مع الأجهزة هو "bedienen".\n✓ "bedient" = يشغّل / يستعمل (Gerät, Maschine, Computer).\n✗ "bearbeitet" = يعالج / يخدم على (Text, Antrag, Foto)، موش تشغيل الجهاز.\n✗ "bewirkt" = يتسبّب في (eine Änderung bewirken)، وما يتركّبش مع جهاز.`,
      rule: "ein Gerät bedienen  |  einen Text / Antrag bearbeiten  |  eine Wirkung bewirken", ex: "Sie lernt, wie man das Gerät **bedient**.", exTr: "تتعلّم كيفاش تشغّل الجهاز." },
    27: { ok: "zu lernen", type: "grammar_structure", keyword: "Angst haben, … zu + Infinitiv", bed: "باش تتعلّم (حاجة جديدة)",
      text: `"Angst haben" يتبعها Infinitiv مع "zu": "Angst haben, etwas Neues zu lernen".\n✓ "zu lernen" = Infinitiv مع "zu" (بعد Angst / Lust / Zeit haben).\n✗ "lernen" = Infinitiv بدون "zu"، وهذا يتركّب غير مع الأفعال المساعدة (können, wollen, müssen).\n✗ "lernen müssen" = فيها فعل مساعد زيادة ("لازم تتعلّم")، وتغيّر المعنى وما تتركّبش بعد "Angst haben".`,
      rule: "Angst / Lust / Zeit haben, … zu + Infinitiv  |  Modalverb + Infinitiv ohne zu", ex: "Ich habe keine Lust, heute **zu arbeiten**.", exTr: "ما عنديش نفس نخدم اليوم." },
    28: { ok: "einsetzen", type: "verb", keyword: "Kenntnisse einsetzen", bed: "توظّف (معرفتك)",
      text: `"تستعمل معارفك الجديدة بشكل عملي": الفعل المناسب "einsetzen" (يوظّف).\n✓ "einsetzen" = يستعمل / يوظّف (Kenntnisse, Wissen, Fähigkeiten).\n✗ "fortsetzen" = يكمّل (eine Reise fortsetzen)، موش استعمال.\n✗ "übersetzen" = يترجم (einen Text übersetzen)، المعنى مختلف تمامًا.`,
      rule: "Kenntnisse / Wissen einsetzen = praktisch anwenden", ex: "Er will sein Wissen im Beruf **einsetzen**.", exTr: "يحب يوظّف معرفتو في الخدمة." },
    29: { ok: "Wenn", type: "fixed_expression", keyword: "Wenn du mich fragst, …", bed: "إذا تسألني (رأيي)",
      text: `تعبير ثابت: "Wenn du mich fragst" = حسب رأيي، وبعدو الفعل في الآخر.\n✓ "Wenn" = إذا (جملة شرط، "fragst" في الآخر).\n✗ "Ob" = إذا بمعنى "whether" (في الأسئلة غير المباشرة: "Ich weiß nicht, ob …")، وما تفتحش جملة شرط.\n✗ "Wann" = إمتى (سؤال عن الوقت)، موش شرط.`,
      rule: "Wenn du mich fragst, … (feste Wendung = meiner Meinung nach)", ex: "**Wenn** du mich fragst, bleib zu Hause.", exTr: "إذا تسألني، اقعد في الدار." },
    30: { ok: "nämlich", type: "adjective_adverb", keyword: "nämlich (Begründung)", bed: "خاطر (لازمني نمشي)",
      text: `"لازم نوقف… خاطر لازم نمشي للدورة توّا": الكاتبة تعطي سبب، والظرف المناسب "nämlich".\n✓ "nämlich" = خاطر / يعني (يفسّر السبب، ويجي في وسط الجملة).\n✗ "also" = إذن (يستنتج نتيجة)، وهنا ما فماش نتيجة، فما سبب.\n✗ "kaum" = بالكاد (تقريبًا ما)، وتقلب المعنى للنفي.`,
      rule: "nämlich im Mittelfeld = erklärt den vorigen Satz (Grund)", ex: "Ich muss gehen, mein Zug fährt **nämlich** gleich.", exTr: "لازم نمشي، خاطر القطار باش يمشي توّا." },
  },

  // ───────────── [31] Jutta ─────────────
  31: {
    21: { ok: "dafür", type: "pronoun_adverb", keyword: "einen Grund dafür haben", bed: "عندي سبب لهذا",
      text: `"Grund" يتبعو "für": "Grund für etwas"، والـ Pronominaladverb "dafür" (= für + das) يرجع على اللي ذكرتو قبل (ما كتبتش).\n✓ "dafür" = لهذا (Grund + für).\n✗ "darauf" = على هذا (حرف "auf")، و"Grund auf" ما يتقالش.\n✗ "dazu" = لهذا / زيادة على ذلك (غرض أو إضافة)، وما يتركّبش مع "Grund".`,
      rule: "Grund für + Akk. → ein Grund dafür", ex: "Es gibt einen guten Grund **dafür**.", exTr: "فما سبب وجيه لهذا." },
    22: { ok: "wegen", type: "preposition", keyword: "wegen + Genitiv (Grund)", bed: "بسبب (مرضي)",
      text: `الجملة اللي قبل تقول "عندي سبب وجيه"، والفراغ يعطي هذا السبب: "wegen meiner Krankheit".\n✓ "wegen" = بسبب (+ Genitiv).\n✗ "während" = أثناء (+ Genitiv): نحويًّا ممكنة، بصح تعبّر على وقت موش سبب، والسياق يحتاج سبب (triftiger Grund).\n✗ "statt" = عوض (Ersatz)، و"statt meiner Krankheit" ما تعطي معنى.`,
      rule: "wegen + Genitiv (Grund)  |  während + Genitiv (Zeit)  |  statt + Genitiv (Ersatz)", ex: "**Wegen** des Regens bleiben wir zu Hause.", exTr: "بسبب المطر نقعدو في الدار." },
    23: { ok: "verschoben", type: "tense", keyword: "verschieben – verschob – verschoben", bed: "أجّلتها (الفحص)",
      text: `بعد "habe" نحتاج Partizip II، و"verschieben" فعل قوي: Partizip II = "verschoben".\n✓ "verschoben" = Partizip II (ich habe … verschoben).\n✗ "verschieben" = Infinitiv، وبعد "habe" نحتاج Partizip II.\n✗ "verschiebten" = شكل مصطنع (تصريف ضعيف)، و"verschieben" يتصرّف: verschob / hat verschoben.`,
      rule: "verschieben ist stark: verschob, hat verschoben", ex: "Wir haben den Termin **verschoben**.", exTr: "أجّلنا الموعد." },
    24: { ok: "nicht mehr", type: "adjective_adverb", keyword: "nicht mehr ≠ noch nicht", bed: "ما عادش (نجّم نرقد)",
      text: `كنت ننجّم نرقد والحالة هذي وقفت بسبب الأوجاع: "ما عادش": "nicht mehr".\n✓ "nicht mehr" = ما عادش (حاجة كانت وتوقّفت).\n✗ "noch nicht" = مازال ما صارش (حاجة منتظرة)، وهنا النوم كان ممكن قبل.\n✗ "sogar nicht" = تركيب غير مستعمل ("sogar" تجي مع الإيجاب)، والنفي المقوّي هو "nicht einmal".`,
      rule: "nicht mehr = Zustand endet  |  noch nicht = Erwartung, noch nicht eingetreten", ex: "Er wohnt **nicht mehr** hier.", exTr: "ما عادش يسكن هنا." },
    25: { ok: "eingewiesen", type: "verb", keyword: "ins Krankenhaus einweisen", bed: "حوّلني (للسبيطار)",
      text: `الطبيب بعث المريض للسبيطار: الفعل الطبي "einweisen" (ins Krankenhaus).\n✓ "eingewiesen" = Partizip II من "einweisen" = حوّل / أدخل.\n✗ "geschicken" = شكل غلط، Partizip من "schicken" هو "geschickt".\n✗ "nachgewiesen" = أثبت (einen Beweis nachweisen)، موش حوّل للسبيطار.`,
      rule: "jdn. in + Akk. einweisen (ein-weisen, Partizip eingewiesen)", ex: "Der Arzt hat ihn ins Krankenhaus **eingewiesen**.", exTr: "الطبيب حوّلو للسبيطار." },
    26: { ok: "Übergewicht", type: "noun", keyword: "Kilo Übergewicht haben", bed: "زيادة وزن",
      text: `"ein paar Kilo ___ habe": الكلمة المعتادة مع الكيلوات الزايدة "Übergewicht".\n✓ "Übergewicht" = زيادة وزن.\n✗ "Gleichgewicht" = توازن (das Gleichgewicht halten)، معنى مختلف.\n✗ "Gleichgültigkeit" = لامبالاة (صفة شخصية)، وما علاقتها بالكيلوات.`,
      rule: "(ein paar) Kilo Übergewicht haben = zu schwer sein", ex: "Er hat zehn Kilo **Übergewicht**.", exTr: "عندو عشرة كيلو زيادة." },
    27: { ok: "zur", type: "preposition", keyword: "zur Behandlung gehen", bed: "للعلاج",
      text: `"نمشي للعلاج": الاتجاه نحو نشاط أو مكان بـ "zu" + Dativ، و"Behandlung" مؤنّث: "zur" (= zu der).\n✓ "zur" = zu + der (zur Behandlung gehen).\n✗ "auf" = على (auf die Bank, auf die Toilette gehen)، و"auf Behandlung gehen" ما يتقالش.\n✗ "für" = لأجل (Zweck)، وما يعطيش اتجاه الحركة بعد "gehen".`,
      rule: "zu + Dativ: zur Behandlung / zum Arzt / zur Therapie gehen", ex: "Ich gehe zweimal pro Woche **zur** Physiotherapie.", exTr: "نمشي مرتين في الجمعة للعلاج الطبيعي." },
    28: { ok: "hinter", type: "fixed_expression", keyword: "etwas hinter sich haben", bed: "وراي (خلصت)",
      text: `"بعض العلاجات وراي": تعبير ثابت للحاجة اللي تمّت: "hinter mir".\n✓ "hinter" = وراي (تمّت وخلصت).\n✗ "vor" = قدّامي ("vor mir" = لسّا باش تصير)، والمعنى معكوس.\n✗ "über" = فوقي (مكان)، وما يعطيش معنى "خلصت".`,
      rule: "etwas hinter sich haben = abgeschlossen  |  etwas vor sich haben = steht noch bevor", ex: "Die Prüfung ist **hinter** mir.", exTr: "الامتحان خلص (وراي)." },
    29: { ok: "unter anderem", type: "fixed_expression", keyword: "unter anderem (u. a.)", bed: "من ضمن حاجات أخرى",
      text: `الطبيب نصح بالحركة "من ضمن نصائح أخرى"، و"auch" تدلّ إنّها نصيحة زايدة: "unter anderem".\n✓ "unter anderem" = من ضمن حاجات أخرى.\n✗ "vor allem" = خاصةً (تبرز الأهم)، وهنا النصيحة وحدة من برشا نصايح موش الأهم.\n✗ "auf alle Fälle" = على كل حال / أكيد (تأكيد)، وما تعطيش معنى "من ضمن".`,
      rule: "unter anderem = neben anderen Dingen  |  vor allem = besonders  |  auf alle Fälle = unbedingt", ex: "Er hat **unter anderem** Spanisch gelernt.", exTr: "تعلّم، من ضمن حاجات أخرى، الإسبانية." },
    30: { ok: "gar nicht", type: "adjective_adverb", keyword: "gar nicht", bed: "ما يضرّني بالمرّة",
      text: `"باش نخسّر شوية وزن، وهذا ما يضرّني بالمرّة": تقوية النفي بـ "gar nicht".\n✓ "gar nicht" = أبدًا ما (ما يضرّنيش بالمرّة).\n✗ "eigentlich" = في الحقيقة (تخفيف)، و"was mir eigentlich schaden würde" تعني العكس (يضرّني).\n✗ "überhaupt" = بالمرّة لكن تحتاج نفي معاها ("überhaupt nicht")، وحدها ما تعطيش "ما يضرّش".`,
      rule: "gar nicht = überhaupt nicht (verstärkte Verneinung)", ex: "Das stört mich **gar nicht**.", exTr: "هذا ما يزعجنيش بالمرّة." },
  },

  // ───────────── [32] Julia ─────────────
  32: {
    21: { ok: "voneinander", type: "adjective_adverb", keyword: "voneinander hören", bed: "سمعنا من بعضنا (أخبار)",
      text: `"von jdm. hören" = توصلك أخبار منو: بين اثنين "voneinander" (= von + einander).\n✓ "voneinander" = من بعضنا (voneinander hören).\n✗ "miteinander" = مع بعضنا (نشاط مشترك: "miteinander sprechen")، موش وصول أخبار.\n✗ "zueinander" = تجاه بعضنا ("nett zueinander")، وما تتركّبش مع "hören" بهذا المعنى.`,
      rule: "von jdm. hören → voneinander hören (Nachricht bekommen)", ex: "Wir haben seit Jahren nichts **voneinander** gehört.", exTr: "ما سمعناش من بعضنا من سنين." },
    22: { ok: "durch", type: "preposition", keyword: "Rundreise durch + Akk.", bed: "جولة عبر (أوروبا)",
      text: `جولة تدور على بلدان كثيرة: "Rundreise durch Europa".\n✓ "durch" = عبر / في كامل (+ Akkusativ).\n✗ "über" = فوق / حول (يتقال "über Brüssel" كمحطّة عبور)، و"Rundreise über Europa" ما يتقالش.\n✗ "von" = من، وما نقولوش "Rundreise von Europa".`,
      rule: "eine Rundreise durch + Akk. (Land / Region)", ex: "Wir machen eine Rundreise **durch** Italien.", exTr: "نعملو جولة في إيطاليا." },
    23: { ok: "wie", type: "fixed_expression", keyword: "wie du weißt", bed: "كيما تعرف",
      text: `تعبير ثابت يذكّر بمعلومة معروفة: "wie du weißt".\n✓ "wie" = كيما (so wie du weißt).\n✗ "Als" = وقتما (ماضي) أو في المقارنة، وما تجيش قبل "du weißt".\n✗ "weil" = خاطر، وتطلب جملة رئيسية بعدها تفسّر، موش تقديم معلومة معروفة ("wie du weißt").`,
      rule: "wie + du weißt / siehst / sagst = so wie (Einschub)", ex: "**Wie** du sicher weißt, fängt der Kurs morgen an.", exTr: "كيما تعرف أكيد، الدورة تبدا غدوة." },
    24: { ok: "war", type: "tense", keyword: "war + begeistert (Zustand)", bed: "كان (موش متحمّس)",
      text: `"Chef war nicht begeistert": حالة في الماضي بـ "sein" في Präteritum.\n✓ "war" = Präteritum من "sein" (حالة).\n✗ "wurde" = "become" أو Passiv، و"wurde begeistert" تعني تحمّس شوية بشوية، وهنا نحكيو على حالة أوّلية.\n✗ "würde" = Konjunktiv II، وما يتماشاش مع حدث ماضي واقعي.`,
      rule: "sein + begeistert von = Zustand  |  werden = Veränderung oder Passiv", ex: "Er **war** von dem Film nicht begeistert.", exTr: "ما كانش متحمّس للفيلم." },
    25: { ok: "es", type: "pronoun", keyword: "es ist ruhiger (unpersönliches es)", bed: "الجوّ (يكون أهدى)",
      text: `نحكيو على الجوّ العام في الشركة وما فما حتى فاعل معيّن: "es" الشكلي.\n✓ "es" = ضمير غير شخصي (es ist ruhig = الجوّ هادئ).\n✗ "er" = مذكّر معيّن (شخص أو حاجة)، وما فماش مذكّر معروف في الجملة.\n✗ "man" = الواحد / الناس (فاعل عام)، والمقصود جوّ الشركة موش الناس.`,
      rule: "es als Subjekt bei Zustand / Atmosphäre / Wetter (es ist ruhig, es regnet)", ex: "Im Winter ist **es** hier ruhiger.", exTr: "في الشتاء الجوّ هنا أهدى." },
    26: { ok: "erste", type: "grammar_structure", keyword: "meine erste Station (Endung -e)", bed: "أول (محطّتي)",
      text: `"Station" مؤنّث، وبعد "meine" في Nominativ الصفة تاخذ -e: "meine erste Station".\n✓ "erste" = نهاية -e (Possessiv + Femininum Nominativ).\n✗ "ersten" = -en (Dativ، جمع، أو Akkusativ مذكّر)، و"Station" هنا Nominativ مؤنّث.\n✗ "erster" = -er للمذكّر في Nominativ، و"Station" مؤنّث.`,
      rule: "Possessiv + Fem. Nom. → Adjektiv + -e (meine erste Station)", ex: "Das war meine **erste** Reise.", exTr: "هذي كانت أول رحلة ليّ." },
    27: { ok: "daran", type: "pronoun_adverb", keyword: "denken an → daran", bed: "نفكّر في هذا",
      text: `"denken" يتركّب مع "an" + Akk.، والـ Pronominaladverb "daran" (= an + das) يعلن على "dass-Satz": "daran denken, dass …".\n✓ "daran" = في هذا (an + das).\n✗ "darüber" = حول هذا (حرف "über")، ممكنة في "Was denkst du darüber?" (رأي)، بصح مع فكرة "نفكّر في إنّو" الحرف هو "an".\n✗ "davon" = منها (von + das)، وما تتركّبش مع "denken" بهذا المعنى.`,
      rule: "denken an + Akk. → daran + dass-Satz", ex: "Ich möchte nicht **daran** denken, dass der Urlaub bald endet.", exTr: "ما نحبّش نفكّر إنّو العطلة باش تخلص." },
    28: { ok: "muss", type: "verb", keyword: "zurück müssen (Modalverb ohne Vollverb)", bed: "لازم نرجع",
      text: `الفكرة التزام: "dass ich … an den Schreibtisch zurück muss" (الرجوع للخدمة واجب).\n✓ "muss" = لازم (Modalverb + Richtung، بدون فعل حركة).\n✗ "kann" = ينجّم (إمكانية)، والمعنى هنا إلزام موش قدرة.\n✗ "mag" = يحب، وما يتركّبش مع "zurück" بهذا الشكل، ويتناقض مع "الخدمة ما توحشنيش".`,
      rule: "Modalverb + Richtungsangabe ohne Vollverb (zurück muss, nach Hause will)", ex: "Ich **muss** morgen wieder ins Büro zurück.", exTr: "لازم نرجع غدوة للمكتب." },
    29: { ok: "mir", type: "pronoun", keyword: "jdm. kommt ein Gedanke", bed: "خطرت ببالي",
      text: `التعبير "kam mir der Gedanke" = خطرت ببالي: الشخص في Dativ، و"der Gedanke" هو الفاعل.\n✓ "mir" = Dativ (kam mir der Gedanke).\n✗ "ich" = Nominativ، والفاعل هنا "der Gedanke".\n✗ "mich" = Akkusativ، و"kommen" في هذا التعبير يتركّب مع Dativ.`,
      rule: "jdm. kommt ein Gedanke / eine Idee (Dativ der Person)", ex: "Plötzlich kam **mir** eine Idee.", exTr: "فجأة جاتني فكرة." },
    30: { ok: "könnte", type: "tense", keyword: "könnte (Konjunktiv II: Möglichkeit)", bed: "نجّم (نبدا)",
      text: `فكرة خيالية على المستقبل ("ربما نجّم نبدا حاجة جديدة"): Konjunktiv II من "können".\n✓ "könnte" = نجّم (إمكانية / خيال).\n✗ "bräuchte" = نحتاج (Konjunktiv II من brauchen)، و"anfangen bräuchte" ما يتركّبش بدون "zu".\n✗ "dürfte" = مسموح لي (إذن)، والسياق خيال شخصي موش تصريح.`,
      rule: "Konjunktiv II von können: könnte = Möglichkeit / Gedanke", ex: "Ich **könnte** auch mal etwas anderes probieren.", exTr: "نجّم نجرّب شي آخر." },
  },

  // ───────────── [33] Lina (gap 26 FLAGGED: key "verschiedenen" vs. "durch ___ Stellenbörsen" → needs "verschiedene") ─────────────
  33: {
    21: { ok: "nach", type: "preposition", keyword: "Suche nach + Dativ", bed: "البحث على (شقّة أكبر)",
      text: `"Suche" تتركّب دايمًا مع "nach": "bei deiner Suche nach einer Wohnung".\n✓ "nach" = على (Suche nach).\n✗ "an" = على / في (an + Dativ مكان)، وما تتركّبش مع "Suche".\n✗ "von" = من، و"Suche von einer Wohnung" ما يتقالش.`,
      rule: "Suche nach + Dativ (suchen nach)", ex: "Die Suche **nach** einem Job war schwer.", exTr: "البحث على خدمة كان صعيب." },
    22: { ok: "daran", type: "pronoun_adverb", keyword: "daran denken, wie …", bed: "نتفكّر (في هذا)",
      text: `"denken" يتبعو "an": "an etwas denken"، والـ Pronominaladverb "daran" يعلن على "wie-Satz".\n✓ "daran" = في هذا (an + das).\n✗ "danach" = بعد ذلك (زمن: "Danach gingen wir")، موش "نتفكّر".\n✗ "darüber" = حول هذا (حرف "über")، وياخذ "nachdenken / sprechen"، موش "denken an".`,
      rule: "an etwas denken → daran (+ wie- / dass-Satz)", ex: "Denkst du noch **daran**, wie wir uns kennenlernten?", exTr: "مازلت تتفكّر كيفاش تعرفنا؟" },
    23: { ok: "war", type: "tense", keyword: "war (Präteritum, schon damals)", bed: "كان (حلمي)",
      text: `"schon damals" = ماضي واقعي، يعني Präteritum من "sein".\n✓ "war" = Präteritum (حقيقة صارت).\n✗ "wäre" = Konjunktiv II (افتراض)، وهنا نحكيو على حقيقة.\n✗ "würde" = werden-Form للافتراض، وما تتركّبش مع "mein Traum" بدون Infinitiv.`,
      rule: "Zeitangabe damals → Präteritum (war)  |  Konjunktiv II nur bei Irrealem", ex: "Reisen **war** schon immer mein Traum.", exTr: "السفر كان دايمًا حلمي." },
    24: { ok: "Zwar", type: "conjunction", keyword: "zwar … aber", bed: "صحيح (عندي شهادة)",
      text: `الجملة تعترف ("عندي شهادة ممتازة") وبعدها "aber" تجيب التعارض: "Zwar … aber".\n✓ "Zwar" = صحيح (الجزء الأول من زوج zwar … aber).\n✗ "Andererseits" = من ناحية أخرى، وتحتاج "Einerseits" قبلها وهنا ما فماش.\n✗ "weder" = لا (weder … noch)، نفي، والجملة هنا إيجابية.`,
      rule: "zwar … aber = Zugeständnis + Gegensatz  |  einerseits … andererseits  |  weder … noch", ex: "**Zwar** war es teuer, aber es hat sich gelohnt.", exTr: "صحيح كان غالي، بصح استاهل." },
    25: { ok: "musste", type: "verb", keyword: "musste + Infinitiv", bed: "لازمني",
      text: `"trotzdem unzählige Bewerbungen schreiben" = الإلزام رغم الشهادة الممتازة: "musste".\n✓ "musste" = لازمني (Präteritum من müssen، إلزام).\n✗ "wollte" = حبّيت، ممكنة نحويًّا بصح تتعارض مع "trotzdem": ما أحدش يحب يكتب برشا طلبات.\n✗ "mochte" = كنت نحب (mögen ياخذ مفعول به)، وما يتركّبش مباشرة مع Infinitiv.`,
      rule: "müssen im Präteritum: musste (Zwang)  ≠  wollte (Wunsch)", ex: "Ich **musste** viele Formulare ausfüllen.", exTr: "لازمني نعمر برشا استمارات." },
    27: { ok: "wurde", type: "grammar_structure", keyword: "wurde + Partizip II (Passiv)", bed: "كانت تتلوّج (عليها)",
      text: `الجملة ما فيهاش فاعل يبحث ("eine Junior-Referentin" هي المبحوث عليها): Vorgangspassiv في الماضي "wurde … gesucht".\n✓ "wurde" = Passiv Präteritum (wurde + Partizip II).\n✗ "hatte" = Plusquamperfekt نشط ("hatte gesucht")، ويحتاج فاعل يبحث.\n✗ "war" = Zustandspassiv (حالة)، ممكنة بصح الإعلان هنا عملية جارية فنستعملو "wurde".`,
      rule: "Vorgangspassiv Präteritum: wurde + Partizip II", ex: "Im Büro **wurde** eine neue Assistentin gesucht.", exTr: "في المكتب كانوا يلوّجو على مساعدة جديدة." },
    28: { ok: "keine", type: "grammar_structure", keyword: "keine + Akk. Plural", bed: "ما كنتش نتوقّع (فرص كبيرة)",
      text: `"Chancen" جمع ومفعول به (Akkusativ) في "sich Chancen ausrechnen": "keine großen Chancen".\n✓ "keine" = Akkusativ جمع.\n✗ "keinen" = Dativ جمع أو Akkusativ مذكّر، و"Chancen" مفعول به جمع ما يحتاجش -n.\n✗ "keiner" = Genitiv / Dativ مؤنّث، موش مفعول به جمع.`,
      rule: "Akkusativ Plural: keine (kein-Wörter wie im Nominativ Plural)", ex: "Ich habe **keine** Fragen mehr.", exTr: "ما عادش عندي أسئلة." },
    29: { ok: "zu", type: "preposition", keyword: "Einladung zu + Dativ", bed: "دعوة لـ (مقابلة)",
      text: `"Einladung" تتركّب مع "zu": "eine Einladung zu einem Vorstellungsgespräch".\n✓ "zu" = دعوة لـ (Einladung zu + Dativ).\n✗ "in" = في (مكان / زمن)، و"Einladung in einem Gespräch" ما تتقالش.\n✗ "mit" = مع، وما تعطيش معنى الدعوة.`,
      rule: "Einladung zu + Dativ (einladen zu)", ex: "Er bekam eine Einladung **zu** einer Party.", exTr: "جاتو دعوة لحفلة." },
    30: { ok: "was", type: "pronoun", keyword: "das Einzige, was …", bed: "اللي (الحاجة الوحيدة اللي تزعجني)",
      text: `بعد "das Einzige" نستعملو "was" كـ Relativpronomen: "das Einzige, was mich stört".\n✓ "was" = اللي (بعد das Einzige / alles / etwas / nichts).\n✗ "welches" = ممكنة نحويًّا بصح أسلوب قديم ونادر، والمعتاد "was" بعد das Einzige.\n✗ "wo" = وين (مكان: "der Ort, wo …")، موش فاعل الجملة.`,
      rule: "Relativsatz nach das Einzige / alles / etwas / nichts / das Beste → was", ex: "Das ist alles, **was** ich weiß.", exTr: "هذا كلّ شي نعرفو." },
  },

  // ───────────── [34] Liebe Sandra (Original) (gap 27 FLAGGED: key "lebenden" vs. "wild ___ Tiere" → needs "lebende") ─────────────
  34: {
    21: { ok: "dich", type: "pronoun", keyword: "jdn. überraschen + Akk.", bed: "يفاجئك (إنت)",
      text: `"überraschen" ياخذ Akkusativ للشخص، والمخاطبة هي Sandra ("du"): "überrascht es dich".\n✓ "dich" = Akkusativ لـ "du".\n✗ "dir" = Dativ (مع "gefallen، helfen")، و"überraschen" ما ياخذش Dativ.\n✗ "sich" = ضمير انعكاسي للغائب، وSandra هي "du".`,
      rule: "überraschen + Akkusativ (jdn. überraschen)", ex: "Die Nachricht hat **mich** überrascht.", exTr: "الخبر فاجأني." },
    22: { ok: "könnte", type: "tense", keyword: "könnte (Möglichkeit, Konjunktiv II)", bed: "ينجّم يكون",
      text: `"ما كنتش نتوقّع إنّ عطلة بدون حفلات ينجّم تناسبني": إمكانية، Konjunktiv II من "können".\n✓ "könnte" = ينجّم يكون (إمكانية).\n✗ "möchte" = يحب (رغبة)، و"Urlaub" ما عندوش رغبة.\n✗ "müsste" = لازم (واجب)، والمعنى هنا إمكانية موش واجب.`,
      rule: "dass-Satz nach 'hätte nicht gedacht' → Konjunktiv II (könnte)", ex: "Ich hätte nie gedacht, dass es so schwer sein **könnte**.", exTr: "ما كنتش نتصوّر إنّو ينجّم يكون صعيب هكا." },
    23: { ok: "von", type: "verb_prep", keyword: "sich erholen von + Dativ", bed: "نرتاح من (الضغط)",
      text: `"sich erholen" يتبعو "von" + Dativ: "sich von der Hektik erholen".\n✓ "von" = من (sich erholen von).\n✗ "mit" = مع، و"sich mit der Hektik erholen" تعطي معنى مختلف.\n✗ "vor" = قدّام / من (للخوف: "sich fürchten vor")، وما تتركّبش مع "erholen".`,
      rule: "sich erholen von + Dativ (von der Arbeit, von einer Krankheit)", ex: "Ich erhole mich **von** der Arbeit.", exTr: "نرتاح من الخدمة." },
    24: { ok: "als", type: "verb_prep", keyword: "etwas als + Adjektiv empfinden", bed: "نحسّو (مريح)",
      text: `"empfinden" يتبعو "als" قبل الصفة: "was ich als sehr angenehm empfinde".\n✓ "als" = كـ (etwas als angenehm empfinden).\n✗ "für" = لـ (halten für: "ich halte es für angenehm")، و"empfinden" ما ياخذش "für".\n✗ "wie" = كيما (مقارنة)، و"wie angenehm empfinden" ما يتقالش.`,
      rule: "etwas als + Adjektiv empfinden  |  etwas für + Adjektiv halten", ex: "Ich empfinde die Ruhe **als** wohltuend.", exTr: "نحسّ الهدوء مريح." },
    25: { ok: "aus", type: "verb_prep", keyword: "bestehen aus + Dativ", bed: "يتكوّن من",
      text: `"Helgoland" مكوّنة من جزيرتين (أجزاء مادّية): "bestehen aus".\n✓ "aus" = من (bestehen aus + Dativ).\n✗ "in" = في (bestehen in = يتمثّل في: "Die Aufgabe besteht in …")، وهنا نحكيو على مكوّنات مادّية.\n✗ "zu" = غير مع نسبة مئوية ("zu 90 Prozent aus Wasser")، موش مع عدد أجزاء.`,
      rule: "bestehen aus + Dat. (Bestandteile)  |  bestehen in (Wesen)  |  bestehen zu + Prozent", ex: "Das Team besteht **aus** fünf Personen.", exTr: "الفريق يتكوّن من خمسة أشخاص." },
    26: { ok: "ist", type: "grammar_structure", keyword: "sein + zu + Infinitiv", bed: "يتوصّل لها (بالعبّارة)",
      text: `"die per Fähre zu erreichen ist" = اللي ينجّم الواحد يوصلها بالعبّارة: sein + zu + Infinitiv (بمعنى مبني للمجهول + إمكانية).\n✓ "ist" = sein + zu + Infinitiv (= kann erreicht werden).\n✗ "hat" = haben + zu + Infinitiv (= لازم، فاعل نشط: "Er hat zu arbeiten")، والجزيرة ما تعمل حتى فعل.\n✗ "wird" = ما تتركّبش مع "zu + Infinitiv" هكا (تحتاج "wird zu erreichen sein" في المستقبل).`,
      rule: "sein + zu + Infinitiv = kann / muss + Passiv  |  haben + zu + Infinitiv = muss (aktiv)", ex: "Das Ziel **ist** leicht zu erreichen.", exTr: "الهدف سهل الوصول إليه." },
    28: { ok: "wenige", type: "grammar_structure", keyword: "nur wenige + Plural", bed: "غير ساعات قلايل",
      text: `"Stunden" جمع بدون أداة، والصفة تاخذ -e في Akkusativ جمع: "nur wenige Stunden".\n✓ "wenige" = -e (Akkusativ جمع بدون أداة).\n✗ "wenigen" = -en تجي بعد أداة معرّفة أو في Dativ، وهنا ما فما لا أداة لا Dativ.\n✗ "weniger" = أقلّ (مقارنة، وتحتاج "als")، وهنا المقصود ساعات قلايل.`,
      rule: "Akkusativ Plural ohne Artikel: wenige / viele / einige (Endung -e)", ex: "Er hat nur **wenige** Freunde.", exTr: "عندو غير أصحاب قلال." },
    29: { ok: "Sobald", type: "conjunction", keyword: "sobald + Nebensatz", bed: "ساعة ما (يمشيو)",
      text: `"ساعة ما يمشيو السيّاح، يرجع الهدوء": رابط زمني يفتح جملة فرعية، وفعلها "sind abgefahren" في الآخر.\n✓ "Sobald" = ساعة ما (زمن، + فعل في الآخر).\n✗ "Sofern" = بشرط إنّو (شرط)، والمعنى هنا زمني موش شرط.\n✗ "Somit" = وبالتالي (نتيجة)، ظرف ياخذ الفعل في المرتبة الثانية، والجملة هنا فعلها في الآخر.`,
      rule: "sobald = in dem Moment, in dem (zeitlich)  |  sofern = Bedingung  |  somit = Folge", ex: "**Sobald** ich Zeit habe, rufe ich dich an.", exTr: "ساعة ما يكون عندي وقت نعيّطلك." },
    30: { ok: "würdest", type: "tense", keyword: "würdest gern + Infinitiv", bed: "تحب (تبدّل السكنى)",
      text: `"gern umziehen" = رغبة، وفي الكلام غير المباشر نستعملو Konjunktiv II: "würdest … umziehen".\n✓ "würdest" = würde + Infinitiv (رغبة: gern umziehen würdest).\n✗ "könntest" = تنجّم: ممكنة نحويًّا، بصح مع "gern" المقصود رغبة موش قدرة.\n✗ "dürftest" = مسموحلك (إذن)، وما تتماشاش مع "gern".`,
      rule: "Wunsch: würde + gern + Infinitiv (du-Form: würdest)", ex: "Du hast gesagt, dass du gern reisen **würdest**.", exTr: "قلت إنّك تحب تسافر." },
  },
};
