// SB Teil 1 restyle — batch 05: [20] Justus (معدل), [21] Ferdinand… (Original), [22] Ferdinand… (معدل), [23] Maria und Timur, [24] Ramon
export default {
  // ───────────── [20] Justus oder Juhannas (معدل) ───────────── (23, 25, 26, 27, 28, 29 reused automatically)
  20: {
    21: { reuse: "19#21" },
    22: { ok: "ersten", type: "fixed_expression", keyword: "zum ersten Mal", bed: "لأول مرة",
      text: `التعبير الثابت لـ "لأول مرة": "zum ersten Mal" (zu + dem + Ordnungszahl + Mal).\n✓ "ersten" = zum ersten Mal (Dativ بعد "zum").\n✗ "daher" = لهذا السبب (ظرف)، وما تتركّبش بين "zum" و"Mal".\n✗ "sicher" = أكيد (صفة / ظرف)، وما تكوّنش تعبير ترتيب زمني.`,
      rule: "zum + Ordinalzahl + Mal (zum ersten / zweiten Mal)", ex: "Ich fliege **zum ersten** Mal.", exTr: "نسافر بالطيارة لأول مرة." },
    24: { reuse: "19#24" },
    30: { reuse: "19#30" },
  },

  // ───────────── [21] Ferdinand, Phillip, Christopher ( Original ) ─────────────
  21: {
    21: { ok: "um", type: "conjunction", keyword: "um … zu + Infinitiv", bed: "باش نجّم ندفع الكراء",
      text: `نحكيو على غاية: نخدم "باش" ندفع الكراء. والجملة فيها "bezahlen zu können": تركيب "um … zu + Infinitiv".\n✓ "um" = um … zu (غاية).\n✗ "anstatt" = بدل ما ("anstatt zu lernen")، معناها بدل الهدف، موش غاية.\n✗ "ohne" = من غير ما ("ohne zu fragen")، معناها غياب، موش غاية.`,
      rule: "um … zu + Infinitiv = Zweck  |  anstatt … zu / ohne … zu = Gegensatz", ex: "Ich arbeite, **um** Geld **zu** verdienen.", exTr: "نخدم باش نكسب فلوس." },
    22: { ok: "wie", type: "conjunction", keyword: "Ich weiß nicht, wie …", bed: "ما نعرفش كيفاش (نصبر)",
      text: `"Ich weiß nicht, … ich das durchhalten würde" = ما نعرفش كيفاش نصبر: سؤال غير مباشر على الكيفية.\n✓ "wie" = كيفاش (indirekte Frage).\n✗ "dass" = إنّو (تقرير حقيقة)، موش سؤال: "ich weiß nicht, dass …" معناها ما نعرفش إنّ…\n✗ "während" = بينما (توازي زمني)، وما تعبّرش عن سؤال كيفاش.`,
      rule: "Ich weiß nicht, wie + Nebensatz (indirekte Frage)", ex: "Ich weiß nicht, **wie** ich das schaffen soll.", exTr: "ما نعرفش كيفاش نخلّص هذا." },
    23: { ok: "aber", type: "conjunction", keyword: "zwar …, aber (andererseits)", bed: "صحيح تعب، بصح من ناحية أخرى",
      text: `الجملة تبدا بـ "zwar" (صحيح) وتحتاج "aber" (بصح) باش تكمّل التعارض: متعب… بصح من ناحية أخرى فيها حركة.\n✓ "aber" = بصح (تكمّل "zwar").\n✗ "denn" = خاطر (سبب)، وما يكمّلش "zwar".\n✗ "und" = و (إضافة محايدة)، وما تعبّرش عن التعارض اللي بدا بـ "zwar".`,
      rule: "zwar … aber = Zugeständnis + Gegensatz", ex: "Es ist **zwar** laut, **aber** ich mag es.", exTr: "صحيح فيه ضجيج، بصح يعجبني." },
    24: { ok: "unbedingt", type: "adjective_adverb", keyword: "unbedingt wollen", bed: "كنت نحب بأي ثمن (لازمًا)",
      text: `"wollte ich … Kellnerin werden" فيها رغبة قوية: الظرف اللي يجي مع "wollen" بهالمعنى هو "unbedingt" (بأي ثمن).\n✓ "unbedingt" = بالضرورة / بأي ثمن (مع wollen / müssen).\n✗ "bestimmt" = أكيد (توقّع: "Er kommt bestimmt")، موش شدة الرغبة.\n✗ "völlig" = تمامًا (للصفات والحالات: "völlig müde")، وما تتركّبش مع "wollen" هكا.`,
      rule: "unbedingt + wollen / müssen = auf jeden Fall", ex: "Ich will **unbedingt** Pilot werden.", exTr: "نحب بأي ثمن نولّي طيّار." },
    25: { ok: "mich", type: "pronoun", keyword: "Wenn ich mich nicht täusche", bed: "إذا ما غلطتش",
      text: `التعبير الثابت "Wenn ich mich nicht täusche" = إذا ما غلطتش. والفعل "sich täuschen" انعكاسي: الضمير لازم يطابق الفاعل (ich ← mich).\n✓ "mich" = Reflexivpronomen لـ "ich".\n✗ "dich" = لـ "du"، والفاعل هنا "ich".\n✗ "sich" = لغائب (er / sie / sie)، موش لـ "ich".`,
      rule: "sich täuschen: ich … mich (Reflexivpronomen = Subjekt)", ex: "Wenn ich **mich** nicht irre, ist er Arzt.", exTr: "إذا ما غلطتش، هو طبيب." },
    26: { ok: "als", type: "conjunction", keyword: "als (Vergangenheit)", bed: "وقتما كنّا (في المدرسة)",
      text: `نحكيو على فترة في الماضي (وقتما كنّا في المدرسة): ماضي ← "als".\n✓ "als" = وقتما (ماضي، فترة أو حدث وحيد).\n✗ "wenn" = وقتما في الحاضر / المستقبل أو التكرار، وما تنفعش لفترة في الماضي.\n✗ "wie" = كيما / كيفاش (مقارنة)، موش رابط زمني بهذا المعنى.`,
      rule: "als = einmalig / Phase in der Vergangenheit  |  wenn = Gegenwart / Zukunft / Wiederholung", ex: "**Als** wir klein waren, spielten wir hier.", exTr: "وقتما كنّا صغار، كنّا نلعبو هنا." },
    27: { ok: "kommenden", type: "adjective_adverb", keyword: "die kommenden Wochenenden", bed: "نهايات الأسبوع الجايّة",
      text: `نسألو على خطط المستقبل: الصفة المناسبة هي "kommenden" (الجايّة).\n✓ "kommenden" = الجايّة (جمع بعد "für die").\n✗ "vergangenen" = الفايتة (ماضي)، وهذا عكس "Pläne".\n✗ "baldigen" = قريب جدًا (في أقرب وقت)، يتركّب مع "Antwort / Besserung / Wiedersehen"، موش مع "Wochenenden".`,
      rule: "kommend- = bevorstehend  |  vergangen- = schon vorbei  |  baldig = in Kürze", ex: "In den **kommenden** Tagen regnet es.", exTr: "في الأيام الجايّة تشتي." },
    28: { ok: "dazu", type: "pronoun_adverb", keyword: "Lust dazu haben", bed: "عندك رغبة في هذا؟",
      text: `"Lust haben" يتركّب مع "zu" (رغبة في فعل)، والـ Pronominaladverb "dazu" يرجع للاقتراح اللي قبل (نتلاقاو ونحكيو).\n✓ "dazu" = zu + das (Lust dazu).\n✗ "danach" = من بعد ذلك (ترتيب زمني)، موش رغبة في الاقتراح.\n✗ "darüber" = حول ذلك (über + das)، وما يتركّبش مع "Lust".`,
      rule: "Lust haben zu / auf etwas → dazu", ex: "Hast du **Lust dazu**?", exTr: "عندك رغبة؟" },
    29: { ok: "sondern", type: "conjunction", keyword: "nicht nur …, sondern auch", bed: "موش بس… بل زادة",
      text: `البنية الثابتة "nicht nur …, sondern auch …" (موش بس… بل زادة).\n✓ "sondern" = تكمّل "nicht nur".\n✗ "aber" = بصح (تعارض)، وما تتركّبش مع "nicht nur … auch".\n✗ "oder" = ولا (اختيار)، والجملة تجمع الاثنين موش تختار.`,
      rule: "nicht nur … sondern auch = Addition", ex: "Er ist **nicht nur** nett, **sondern auch** klug.", exTr: "موش بس لطيف، بل ذكي زادة." },
    30: { ok: "für", type: "preposition", keyword: "was für dich", bed: "هل هذا يناسبك؟",
      text: `"Wäre das was … dich?" = هل هذا مناسب ليك؟: التعبير المعتاد "was für dich" (حاجة تناسبك).\n✓ "für" = لأجل / مناسب لـ (Akkusativ: dich).\n✗ "gegen" = ضد، يقلب المعنى (حاجة ضدّك).\n✗ "ohne" = بدون، وما تعطيش معنى الملاءمة.`,
      rule: "für + Akk. (Adressat / Eignung): Wäre das was für dich?", ex: "Ist das was **für** dich?", exTr: "هل هذا يناسبك؟" },
  },

  // ───────────── [22] Ferdinand, Phillip, Christopher (معدل) ───────────── (24, 25, 28 reused automatically)
  22: {
    21: { ok: "um", type: "conjunction", keyword: "um … zu können", bed: "باش نجّم ندفع",
      text: `الجملة فيها "zu bezahlen können" (Infinitiv مع zu)، يعني الرابط لازم يكون "um … zu" (غاية بنفس الفاعل).\n✓ "um" = um … zu (غاية، والفاعل واحد: أنا نخدم وأنا ندفع).\n✗ "damit" = باش (غاية)، لكن "damit" تفتح جملة بفعل مصرّف في الآخر ("damit ich … bezahlen kann")، وهنا فيه Infinitiv مع "zu".\n✗ "für" = لأجل + اسم، وما تربطش بـ Infinitiv ("für … zu bezahlen" غلط).`,
      rule: "um … zu + Infinitiv (gleiches Subjekt)  |  damit + Nebensatz (Subjekte dürfen verschieden sein)", ex: "Ich arbeite, **um** zu sparen.", exTr: "نخدم باش نوفّر." },
    22: { ok: "wie", type: "conjunction", keyword: "Ich weiß nicht, wie …", bed: "ما نعرفش كيفاش (نصبر)",
      text: `"Ich weiß nicht, … ich das durchhalten würde" = ما نعرفش كيفاش نصبر: سؤال غير مباشر على الكيفية.\n✓ "wie" = كيفاش (indirekte Frage).\n✗ "wann" = إمتى (زمن)، والجملة ما تسألش على الوقت.\n✗ "wo" = وين (مكان)، والصبر ما فيه مكان.`,
      rule: "Ich weiß nicht, wie + Nebensatz (indirekte Frage)", ex: "Ich weiß nicht, **wie** das funktioniert.", exTr: "ما نعرفش كيفاش هذا يخدم." },
    23: { ok: "doch", type: "conjunction", keyword: "zwar …, doch", bed: "صحيح تعب، لكن (مع ذلك)",
      text: `نفس بنية "zwar … aber": "doch" تكمّل التعارض بنفس المعنى (لكن / ومع ذلك).\n✓ "doch" = لكن / ومع ذلك (بديل لـ "aber" بعد "zwar").\n✗ "denn" = خاطر (سبب)، وما يكمّلش "zwar".\n✗ "damit" = باش (غاية)، وما تعبّرش عن التعارض.`,
      rule: "zwar … doch / aber = Gegensatz", ex: "Es ist **zwar** anstrengend, **doch** es macht Spaß.", exTr: "صحيح متعب، بصح يعجبني." },
    26: { ok: "als", type: "conjunction", keyword: "als (Vergangenheit)", bed: "وقتما كنّا (في المدرسة)",
      text: `فترة في الماضي: "وقتما كنّا في المدرسة" ← رابط زمني للماضي: "als".\n✓ "als" = وقتما (ماضي).\n✗ "da" = بما إنّو (سبب)، وما نقولوش "بما إنّا كنّا في المدرسة" كسبب لكونهم زوج.\n✗ "wenn" = وقتما في الحاضر / المستقبل أو التكرار، موش فترة ماضية.`,
      rule: "als = Vergangenheit (einmalig / Phase)  |  wenn = Gegenwart / Zukunft / Wiederholung", ex: "**Als** ich jung war, wohnte ich in Tunis.", exTr: "وقتما كنت صغير، كنت نسكن في تونس." },
    27: { ok: "kommenden", type: "adjective_adverb", keyword: "die kommenden Wochenenden", bed: "نهايات الأسبوع الجايّة",
      text: `الخطط تخص نهايات الأسبوع القادمة: "kommenden" (الجايّة).\n✓ "kommenden" = الجايّة.\n✗ "letzten" = الأخيرة / الفايتة، وهذا عكس "Pläne".\n✗ "jetzigen" = الحالية (اللي نعيشو فيها توّا)، موش اللي جاية.`,
      rule: "kommend- = bevorstehend  |  letzt- = vorherig  |  jetzig = gegenwärtig", ex: "Was machst du am **kommenden** Wochenende?", exTr: "شنوّة باش تعمل نهاية الأسبوع الجاي؟" },
    29: { ok: "als", type: "conjunction", keyword: "sowohl … als auch", bed: "كل من الكعك وكذلك أطباق صغيرة",
      text: `الجملة تبدا بـ "sowohl" (كل من)، ويكملها "als auch" (وكذلك).\n✓ "als" = sowohl … als auch.\n✗ "ebenso" = كذلك (ظرف)، وما تكمّلش "sowohl" بنفسها: لازم "als auch".\n✗ "oder" = ولا، ومعناها اختيار موش جمع بين الاثنين.`,
      rule: "sowohl … als auch (= nicht nur … sondern auch)", ex: "Ich mag **sowohl** Tee **als** auch Kaffee.", exTr: "نحب الشاي وزادة القهوة." },
    30: { ok: "einfach", type: "adjective_adverb", keyword: "doch einfach", bed: "ابعثلي ببساطة",
      text: `نشجّعو شخص: "ابعثلي ببساطة، بلا تكلّف": "doch einfach".\n✓ "einfach" = ببساطة / براحتك.\n✗ "einzig" = وحيد ("der einzige Grund")، موش طريقة التواصل.\n✗ "einen" = أداة / عدد (مذكر Akkusativ)، وما تجيش هكا بعد "mir doch".`,
      rule: "(doch) einfach = ohne Aufwand / ruhig", ex: "Ruf mich **einfach** an.", exTr: "كلّمني ببساطة." },
  },

  // ───────────── [23] Maria und Timur ─────────────
  23: {
    21: { ok: "waren", type: "tense", keyword: "Nachdem + Plusquamperfekt", bed: "من بعد ما رجعنا",
      text: `"nachdem": الحدث الأول (رجعنا) صار قبل التاني (لقينا الرسالة)، يعني نحتاج Plusquamperfekt: waren + Partizip II (و"zurückkommen" فعل حركة يتصرّف مع "sein").\n✓ "waren" = Plusquamperfekt بـ sein (waren zurückgekommen).\n✗ "sind" = Perfekt: يتسمع في الحكي اليومي، لكن القاعدة الرسمية (والامتحان) تطلب ماضي أسبق بعد "nachdem".\n✗ "seien" = Konjunktiv I (للقول غير المباشر)، وما نحتاجوش هنا.`,
      rule: "Nachdem + Plusquamperfekt (waren / hatten + Partizip II)", ex: "Nachdem wir angekommen **waren**, riefen wir an.", exTr: "من بعد ما وصلنا، كلّمنا." },
    22: { ok: "Da", type: "adjective_adverb", keyword: "Da gibt es …", bed: "هنا ما فماش برشا تفكير",
      text: `الجملة تبدا بالفراغ ويجي بعدو الفعل "gibt" مباشرة: نحتاج ظرف: "Da" (في هذه الحالة / هنا).\n✓ "Da" = ظرف (في هذا الأمر ما فماش برشا تفكير).\n✗ "Das" = ضمير إشارة (هذا)، وما يركّبش مع "es gibt" في هالجملة.\n✗ "Dass" = رابط (إنّو) يفتح جملة فرعية فعلها في الآخر، والجملة هنا رئيسية.`,
      rule: "da (Adverb) = in diesem Fall / dabei", ex: "**Da** gibt es kein Problem.", exTr: "هنا ما فماش مشكلة." },
    23: { ok: "für", type: "verb_prep", keyword: "für euch freuen", bed: "فرحانين لأجلكم",
      text: `الفرح هنا لأجل أشخاص ("euch") لأن حالهم مليح (الزواج): "sich freuen für + شخص".\n✓ "für" = فرحانين لأجلكم.\n✗ "auf" = نتشوّقو لحاجة جايّة ("sich auf die Hochzeit freuen")، وهنا الفرح لشخص موش لحدث.\n✗ "an" = للاستمتاع بحاجة قدّامك، موش لأجل شخص.`,
      rule: "sich freuen FÜR + Person  |  AUF (جاي)  |  ÜBER (صار)", ex: "Wir freuen uns **für** dich!", exTr: "فرحانين لأجلك!" },
    24: { ok: "sowohl...als auch", type: "grammar_structure", keyword: "sowohl … als auch", bed: "في تركيا وكذلك في النمسا",
      text: `الفكرة: الاحتفال في تركيا وكذلك في النمسا (الاثنين): رابط ثنائي للإضافة.\n✓ "sowohl...als auch" = كل من… وكذلك…\n✗ "weder...noch" = لا… ولا…، يعني ما يحتفلوش في الاثنين، وهذا عكس "فكرة رائعة".\n✗ "je...desto" = كل ما… كل ما (تناسب)، موش جمع بين مكانين.`,
      rule: "sowohl … als auch = beides (Addition)", ex: "Wir feiern **sowohl** in Tunis **als auch** in Berlin.", exTr: "نحتفلو في تونس وزادة في برلين." },
    25: { ok: "Verwandten", type: "grammar_structure", keyword: "alle … Verwandten", bed: "كل الأصدقاء والأقارب",
      text: `"Verwandte" اسم مشتق من صفة. بعد "alle" (جمع) تاخذ نهاية ضعيفة "-en": "alle Freunde und Verwandten" ("alle" تغطّي الاثنين).\n✓ "Verwandten" = جمع بعد "alle" (نهاية ‑en).\n✗ "Verwandte" = نهاية قوية بدون "alle" ("Freunde und Verwandte")، وهنا "alle" قبلها.\n✗ "Verwandter" = مفرد مذكر أو Genitiv جمع، موش جمع بعد "alle".`,
      rule: "substantiviertes Adjektiv nach 'alle' (Plural): -en (alle Verwandten)", ex: "Alle Bekannten und **Verwandten** kommen.", exTr: "كل المعارف والأقارب يجيو." },
    26: { ok: "unserer", type: "grammar_structure", keyword: "einige + Genitiv", bed: "بعض أصدقائنا القدامى",
      text: `"einige … alten Freunde" = بعض من أصدقائنا القدامى (جزء من مجموعة): بعد "einige" بهالمعنى يجي Genitiv جمع: "unserer".\n✓ "unserer" = Genitiv جمع (partitiv).\n✗ "unsere" = Nominativ / Akkusativ، وما تتركّبش مع "alten Freunde" بعد "einige" هنا.\n✗ "unseren" = Dativ جمع، وما فماش حرف جر يتطلّب Dativ.`,
      rule: "einige / viele / manche + Genitiv Plural (partitiv): einige unserer Freunde", ex: "Wir treffen einige **unserer** Freunde.", exTr: "نتلاقاو مع بعض أصدقائنا." },
    27: { ok: "als", type: "conjunction", keyword: "als Jugendliche", bed: "وقتما كنّا شباب",
      text: `"als Jugendliche" = وقتما كنّا شباب (مرحلة عمرية): "als + اسم" بدون أداة.\n✓ "als" = بصفتنا / وقتما كنّا (مرحلة).\n✗ "wie" = كيما (مقارنة: "wie Jugendliche")، يعني بطريقة الشباب، موش فعلًا شباب.\n✗ "für" = لأجل / مقابل، وما تعطيش معنى "في سن الشباب".`,
      rule: "als + Nomen = in der Rolle / Zeit als …", ex: "**Als** Kind war ich oft krank.", exTr: "وقتما كنت طفل، كنت مريض برشا." },
    28: { ok: "ob", type: "conjunction", keyword: "überlegen, ob …", bed: "نفكّرو هل (لازم) نحجزو",
      text: `"überlegen" + سؤال بنعم / لا (هل نحجزو ولا لا؟): الرابط "ob".\n✓ "ob" = هل (indirekte Entscheidungsfrage).\n✗ "dass" = إنّو (تقرير)، ما نقولوش "wir überlegen, dass …" بمعنى نفكّرو هل.\n✗ "falls" = في حالة (شرط)، والجملة ما تعلّقش على شرط.`,
      rule: "überlegen, ob + Nebensatz (Entscheidungsfrage)", ex: "Ich überlege, **ob** ich kommen soll.", exTr: "نفكّر هل لازم نجي." },
    29: { ok: "tun", type: "fixed_expression", keyword: "alle Hände voll zu tun haben", bed: "عندكم برشا خدمة",
      text: `تعبير ثابت: "alle Hände voll zu tun haben" = مشغولين برشا (الإيدين كلّها مليانة خدمة).\n✓ "tun" = zu tun haben.\n✗ "machen" = يعمل، لكن التعبير الثابت بـ "tun".\n✗ "bereiten" = يحضّر / يتسبّب ("Freude bereiten")، وما يدخلش في هالتعبير.`,
      rule: "alle Hände voll zu tun haben = sehr beschäftigt sein", ex: "Ich habe **alle Hände voll zu tun**.", exTr: "عندي برشا خدمة ما نجّمش نتنفّس." },
    30: { ok: "hätten", type: "tense", keyword: "hätten wir die Gelegenheit", bed: "ويكون عندنا الفرصة",
      text: `نقترحو خطّة: "وتكون عندنا الفرصة" = "hätten" (Konjunktiv II للاقتراح).\n✓ "hätten" = hätten wir die Gelegenheit (احتمال / اقتراح).\n✗ "könnten" = نقدرو، لكن "Gelegenheit" تتركّب مع "haben" ("die Gelegenheit haben").\n✗ "sollten" = كان يلزمنا، يعطي إلزام موش فرصة.`,
      rule: "Konjunktiv II (hätten) = Vorschlag / Möglichkeit", ex: "Dann **hätten** wir mehr Zeit.", exTr: "وقتها يكون عندنا وقت أكثر." },
  },

  // ───────────── [24] Ramon ─────────────
  24: {
    21: { ok: "obwohl", type: "conjunction", keyword: "obwohl + Nebensatz", bed: "رغم إنّي ما كنتش نثق في روحي",
      text: `فيه تناقض: تزلّجت وهي ما كانتش تثق في روحها: رابط تنازل مع فعل في الآخر ("hatte").\n✓ "obwohl" = رغم أنّ (+ جملة).\n✗ "trotz" = رغم (حرف جر)، ياخذ اسم Genitiv، موش جملة بفعل.\n✗ "während" = بينما / أثناء (توازي زمني)، وما تعبّرش عن التناقض.`,
      rule: "obwohl + Nebensatz  |  trotz + Genitiv (Nomen)", ex: "**Obwohl** ich Angst hatte, habe ich es gemacht.", exTr: "رغم إنّي كنت خايف، عملتها." },
    22: { ok: "hatte", type: "tense", keyword: "hatte … gebucht", bed: "كانت حجزت (قبل ما نوصل)",
      text: `"bevor ich ankam" (ماضي) والحجز تمّ قبل ذلك: حدث أسبق في الماضي ← Plusquamperfekt: "hatte … gebucht".\n✓ "hatte" = hatte … gebucht (أسبق).\n✗ "hat" = Perfekt (حاضر)، وما يبيّنش إنّو الحجز أسبق من الوصول.\n✗ "hätte" = Konjunktiv II (خيال / شرط)، والحجز حقيقة.`,
      rule: "bevor + Präteritum → Hauptsatz: Plusquamperfekt (hatte + Partizip II)", ex: "Bevor ich kam, **hatte** er alles vorbereitet.", exTr: "قبل ما نجي، كان حضّر كلشي." },
    23: { ok: "wollte", type: "verb", keyword: "wollte (Absicht)", bed: "كنت حاب نبدّل رأيي",
      text: `الجملة: كنت حاب نغيّر رأيي، بصح ليزا ما حبّتش تسمع: إرادة في الماضي ما تحققتش.\n✓ "wollte" = كنت حاب (نية).\n✗ "sollte" = كان مفروض (توقّع من الغير)، وما تعبّرش عن رغبتها هي.\n✗ "konnte" = كنت نجّم (قدرة)، موش نية، وما يعطيش معنى "كنت حاب نبدّل رأيي، بصح…".`,
      rule: "wollen im Präteritum = Absicht in der Vergangenheit (aber …)", ex: "Ich **wollte** gehen, aber es regnete.", exTr: "كنت حاب نمشي، بصح كانت تشتي." },
    24: { ok: "davon", type: "pronoun_adverb", keyword: "nichts davon hören wollen", bed: "ما حبّتش تسمع حتى شي على هذا",
      text: `التعبير الثابت: "nichts davon hören wollen" = ما تحبّش تسمع حتى كلمة على الموضوع (von + das).\n✓ "davon" = von + das (nichts davon hören).\n✗ "dafür" = لأجل ذلك، وما نقولوش "nichts dafür hören" بهالمعنى.\n✗ "damit" = بذلك / باش، وما يتركّبش مع "hören" هكا.`,
      rule: "von etwas hören / nichts davon hören wollen", ex: "Er wollte **nichts davon** wissen.", exTr: "ما حبّش يعرف حتى شي على هذا." },
    25: { ok: "Einerseits...andererseits", type: "grammar_structure", keyword: "einerseits … andererseits", bed: "من جهة متوتّرة، ومن جهة فرحانة",
      text: `الجملة تقدّم شعورين مختلفين في نفس الوقت (متوترة وفرحانة): نحتاج رابط ثنائي يقارن جهتين: "Einerseits … andererseits".\n✓ "Einerseits...andererseits" = من جهة… ومن جهة أخرى…\n✗ "weder ...noch" = لا… ولا… (نفي الاثنين)، وهنا الشعورين موجودين.\n✗ "zwar … aber" = صحيح… لكن (تنازل)، وما فماش تعارض يقلّل من الأول، الشعورين متساويين.`,
      rule: "einerseits … andererseits = zwei Seiten einer Sache", ex: "**Einerseits** ist es teuer, **andererseits** ist es bequem.", exTr: "من جهة غالي، ومن جهة مريح." },
    26: { ok: "dabei", type: "pronoun_adverb", keyword: "helfen dabei, zu …", bed: "ساعدتني في (اختيار المعدّات)",
      text: `"helfen" يتركّب مع "bei" (ساعد في)، والـ Pronominaladverb "dabei" (= bei + das) يعلن على الفعل اللي بعدو (zu + Infinitiv).\n✓ "dabei" = bei + das ("helfen bei").\n✗ "davon" = von + das، وما نقولوش "helfen von".\n✗ "dazu" = zu + das (لأجل ذلك)، و"helfen dazu" ما هيش تركيب صحيح لمساعدة في فعل.`,
      rule: "jdm. bei etwas helfen → dabei helfen, zu + Infinitiv", ex: "Er hat mir **dabei** geholfen, den Koffer zu tragen.", exTr: "ساعدني في حمل الشنطة." },
    27: { ok: "auszusuchen", type: "grammar_structure", keyword: "auszusuchen (zu im Verb)", bed: "تختار (معدّاتي)",
      text: `بعد "geholfen" نحتاج zu-Infinitiv. والفعل "aussuchen" منفصل: "zu" تتدخّل بين البادئة والفعل = "auszusuchen" (كلمة وحدة).\n✓ "auszusuchen" = aus + zu + suchen.\n✗ "aussuchen" = Infinitiv بلا "zu"، وما يجوزش بعد "geholfen, …" في هذا التركيب.\n✗ "ausgesucht" = Partizip II، موش zu-Infinitiv.`,
      rule: "trennbares Verb + zu: aus + zu + suchen = auszusuchen", ex: "Er half mir, ein Geschenk **auszusuchen**.", exTr: "ساعدني نختار هدية." },
    28: { ok: "grundlegende", type: "grammar_structure", keyword: "einige grundlegende Dinge", bed: "بعض الحاجات الأساسية",
      text: `بعد "einige" (جمع بدون أداة) الصفة تاخذ نهاية قوية: Akkusativ جمع = "-e".\n✓ "grundlegende" = einige grundlegende Dinge (Akkusativ جمع).\n✗ "grundlegenden" = نهاية Dativ جمع أو بعد أداة معرّفة ("die grundlegenden Dinge")، وهنا مفعول به Akkusativ.\n✗ "grundlegender" = Genitiv مؤنث مفرد / Nominativ مذكر، وما تطابقش "Dinge" (جمع).`,
      rule: "nach einige / viele / andere (Plural, ohne Artikel): Adjektiv -e (Nom. / Akk.)", ex: "Sie erklärte mir **einige wichtige** Regeln.", exTr: "شرحتلي بعض القواعد المهمة." },
    29: { ok: "im", type: "fixed_expression", keyword: "im Gegensatz zu", bed: "على عكسي (بخلافي)",
      text: `التعبير الثابت "im Gegensatz zu + Dativ" = بخلاف / على عكس.\n✓ "im" = in + dem، im Gegensatz zu.\n✗ "am" = an + dem (على / عند)، وما نقولوش "am Gegensatz zu".\n✗ "zum" = zu + dem (إلى)، وما يدخلش في هالتعبير الثابت.`,
      rule: "im Gegensatz zu + Dativ = anders als", ex: "**Im** Gegensatz zu mir mag er Sport.", exTr: "بخلافي، هو يحب الرياضة." },
    30: { ok: "wie", type: "conjunction", keyword: "Ich weiß nicht, wie …", bed: "ما نعرفش كيفاش نخلّص",
      text: `هي تعبانة من الألم وتسأل: "كيفاش نخلّص هذا؟": سؤال غير مباشر على الكيفية.\n✓ "wie" = كيفاش (indirekte Frage).\n✗ "ob" = هل (نعم / لا): "ob ich das schaffen soll" معناها هل لازم، موش كيفاش.\n✗ "dass" = إنّو (تقرير)، وما تسألش.`,
      rule: "Ich weiß nicht, wie + Nebensatz (indirekte Frage)", ex: "Ich weiß nicht, **wie** ich dir danken soll.", exTr: "ما نعرفش كيفاش نشكرك." },
  },
};
