// SB Teil 1 restyle — batch 01: [1] Liebe Agnieszka, [2] Frau Goronsksa, [4] Maria  (Leon [3] is the pilot, already done)
export default {
  // ───────────── [1] Liebe Agnieszka ─────────────
  1: {
    21: { ok: "her", type: "fixed_expression", keyword: "es ist … her, dass", bed: "مرّ نصف سنة (منذ آخر مرة)",
      text: `التعبير الثابت لمدّة مضت: "es ist + مدّة + her, dass …" (مرّ كذا من وقت…).\n✓ "her" = مضى (ago): مرّ نصف سنة منذ آخر رسالة.\n✗ "hin" = اتجاه بعيد عن المتكلم ("hin und her")، وما يعطيش معنى الزمن الماضي هنا.\n✗ "vorbei" = انتهى ("Der Sommer ist vorbei")؛ نقولو بيها شي خلص، موش مدّة مرّت منذ حدث.`,
      rule: "Es ist + Zeitangabe + her, dass … (= vor … Zeit)", ex: "Es ist schon drei Jahre **her**, dass wir uns gesehen haben.", exTr: "مرّو 3 سنين من آخر مرة شفنا فيها بعضنا." },
    22: { ok: "erkrankt", type: "adjective_adverb", keyword: "erkrankt sein", bed: "مريضة (مرضت)",
      text: `الجملة اللي بعد تشرح: هي في المستشفى، يعني مرضت فجأة (مرض حاد): "erkrankt sein".\n✓ "erkrankt" = مرضت، حالة مرض طارئة.\n✗ "kränklich" = ضعيف الصحة بطبعو ودايمًا يمرض، موش مرض فجأة يدخّل المستشفى.\n✗ "gekränkt" = اتأذّت مشاعرو (من "Kränkung")، ما لها علاقة بالصحة.`,
      rule: "erkrankt (akut krank)  |  kränklich (ständig schwach)  |  gekränkt (beleidigt)", ex: "Mein Kollege ist **erkrankt** und liegt im Bett.", exTr: "زميلي مرض وراقد في الفراش." },
    23: { ok: "wenn", type: "conjunction", keyword: "wenn (Zukunft)", bed: "وقتما / ساعة اللي (في المستقبل)",
      text: `نحكيو على المستقبل: ما تجي إلا ساعة اللي الامتحان يكون خلاص فات. والفعل في الآخر ("vorbei ist")، يعني Nebensatz.\n✓ "wenn" = وقتما، لحدث في المستقبل (وتستعمل زادة للتكرار).\n✗ "als" = لحدث صار مرة وحدة في الماضي ("Als ich klein war …")، والجملة هنا مستقبل.\n✗ "da" = خاطر (سبب)، والجملة تحدّد وقت العودة موش سبب.`,
      rule: "wenn = Zukunft / Wiederholung  |  als = einmalig in der Vergangenheit", ex: "Ich rufe dich an, **wenn** ich zu Hause bin.", exTr: "نكلّمك وقتما نوصل للدار." },
    24: { ok: "zwar... aber", type: "grammar_structure", keyword: "zwar … aber", bed: "هي لطيفة صحيح، بصح…",
      text: `الجملة فيها تناقض: الأستاذة البديلة لطيفة، بصح ما عندها خبرة. نحتاج رابط ثنائي معناه "صحيح… لكن".\n✓ "zwar... aber" = اعتراف بحاجة إيجابية، وبعدها "بصح" تعارضها.\n✗ "nicht nur... sondern" = موش بس… بل زادة (إضافة إيجابية على إيجابية)، والجملة التانية هنا سلبية.\n✗ "teils... teils" = جزء كذا وجزء كذا (توزيع)، موش تعارض.`,
      rule: "zwar … aber = Zugeständnis + Gegensatz", ex: "Das Hotel ist **zwar** teuer, **aber** sehr schön.", exTr: "النزل غالي صحيح، بصح زين برشا." },
    25: { ok: "würde", type: "tense", keyword: "würde + Infinitiv", bed: "نحب نحط (أمنية / تخيّل)",
      text: `الجملة تحكي على أمنية: "hoffentlich alles geschafft" وبعدها "dann würde ich …" (وقتها نحب نحط الكتب ونرتاح). هذي صيغة الأمنية والتخيّل.\n✓ "würde" = Konjunktiv II: نتخيّل كيفاش نحب نقضي أيامي من بعد الامتحان.\n✗ "werde" = Futur I، قرار أكيد وخطة؛ ممكن نحويًا، بصح ما تعطيش نبرة الأمنية اللي بعد "hoffentlich".\n✗ "wollte" = ماضي ("كنت نحب")، والجملة على المستقبل.`,
      rule: "würde + Infinitiv = Wunsch / Vorstellung", ex: "Wenn ich Zeit hätte, **würde** ich viel reisen.", exTr: "لو عندي وقت، نسافر برشا." },
    26: { ok: "Darauf", type: "pronoun_adverb", keyword: "darauf (freuen auf)", bed: "بيها (الراحة) فرحان برشا",
      text: `الفعل "sich freuen" يتركّب مع "auf" (نفرح بحاجة جايّة)، والـ Pronominaladverb هو "darauf" (= auf + das) يحيل على الراحة اللي ذكرناها.\n✓ "Darauf" = auf + das، تركيبة "sich freuen auf".\n✗ "Danach" = من بعد ذلك (ترتيب زمني)، وما تتركّبش مع "freuen" كسبب للفرحة.\n✗ "Dafür" = لأجل ذلك / مقابل ذلك، وما فماش "sich freuen für" مع حاجة.`,
      rule: "sich freuen auf + Akk. → darauf", ex: "Ich habe bald Urlaub — **darauf** freue ich mich sehr.", exTr: "قريب عندي عطلة — بيها فرحان برشا." },
    27: { ok: "davon", type: "verb_prep", keyword: "halten von", bed: "شنوّة رأيك في هذا؟",
      text: `السؤال عن الرأي: "halten von" (نقولو "Was hältst du von …?"). والـ Pronominaladverb هو "davon".\n✓ "davon" = von + das ← "halten von".\n✗ "darüber" = über + das (حول)، يتركّب مع "sprechen über / nachdenken über"، موش مع "halten".\n✗ "dazu" = zu + das (بخصوص ذلك)، يجي مع "sich äußern zu" مثلًا، موش "halten".`,
      rule: "etwas halten von + Dat. → Was hältst du davon?", ex: "Was hältst du **davon**, wenn wir morgen wandern gehen?", exTr: "شنوّة رأيك نمشيو غدوة نتمشّاو في الجبل؟" },
    28: { ok: "dir", type: "pronoun", keyword: "jdm. auf der Nase herumtanzen", bed: "يتلاعبو بيك (ما يسمعوش كلامك)",
      text: `تعبير ثابت (idiom): "jemandem auf der Nase herumtanzen" = الواحد ما يحترمك ويعمل اللي يحب. والشخص المعني (إنتِ) يجي في الـ Dativ.\n✓ "dir" = Dativ.\n✗ "dich" = Akkusativ، والتعبير ما ياخذش Akkusativ.\n✗ "sich" = انعكاسي (reflexiv)، والصغار ما يرقصوش على أنفسهم، يرقصو على أنفك إنتِ.`,
      rule: "jemandem auf der Nase herumtanzen (+ Dativ)", ex: "Die Schüler tanzen **dem** Lehrer auf der Nase herum.", exTr: "التلاميذ ما يحترموش المعلم ويتلاعبو بيه." },
    29: { ok: "zu beschäftigen", type: "grammar_structure", keyword: "zu + Infinitiv", bed: "تشغلهم (تلهّيهم) طول النهار",
      text: `الجملة على نمط "Es ist nicht leicht, … zu + Infinitiv"، والصغار (طفل وطفلة) هم المفعول: إنتِ اللي تشغلهم.\n✓ "zu beschäftigen" = zu + Infinitiv (تشغل / تلهّي)، والمفعول موجود قبلو.\n✗ "beschäftigt zu sein" = تكون إنتِ مشغولة (حالة)، والجملة تتكلم على تشغيل الأطفال موش على انشغالك.\n✗ "beschäftigen lassen" = تخلّي شخص آخر يشغلهم، وما فيهاش "zu"، والمعنى يتبدّل.`,
      rule: "Es ist (nicht) leicht, + Objekt + zu + Infinitiv", ex: "Es ist nicht leicht, drei Kinder gleichzeitig **zu beschäftigen**.", exTr: "موش سهل تشغل 3 صغار في نفس الوقت." },
    30: { ok: "wie", type: "conjunction", keyword: "einen Weg finden, wie …", bed: "طريقة كيفاش تتعامل مع الصغار",
      text: `"einen Weg finden" يتبعو سؤال على الكيفية: الطريقة كيفاش نعمل حاجة.\n✓ "wie" = كيفاش، تفتح الجملة الفرعية (الفعل "zurechtkommst" في الآخر).\n✗ "weshalb" = علاش (سبب)، والجملة ما تسألش على السبب.\n✗ "wo" = وين (مكان)، والـ Weg هنا طريقة مجازية موش مكان.`,
      rule: "Weg / Möglichkeit / Idee, wie + Nebensatz", ex: "Ich suche einen Weg, **wie** ich schneller Deutsch lerne.", exTr: "نلوّج على طريقة كيفاش نتعلّم الألمانية أسرع." },
  },

  // ───────────── [2] Frau Goronsksa ─────────────
  2: {
    21: { ok: "davon", type: "pronoun_adverb", keyword: "acht davon", bed: "منهم (من العشرة) ثمانية",
      text: `نحكيو على عشرة مدارس، وثمانية منهم في ألمانيا، يعني جزء من الكل: "davon" (= von + denen).\n✓ "davon" = منها / منهم (جزء من مجموعة).\n✗ "dabei" = بالإضافة لذلك / في هذا السياق، وما يعطيش معنى "منها".\n✗ "daraus" = من داخلها / منها كمادة أو أصل ("daraus entsteht …")، موش عدد من الكل.`,
      rule: "Zahl + davon = (ein Teil) von diesen", ex: "Wir haben zehn Kurse, drei **davon** sind kostenlos.", exTr: "عندنا 10 دورات، 3 منهم مجانية." },
    22: { ok: "denen", type: "pronoun", keyword: "an denen", bed: "اللي فيها (في المدارس هذي)",
      text: `"Schulen" جمع، و"an" يتبعو هنا Dativ (مكان: في المدارس). وبعد حرف الجر يجي ضمير الوصل (Relativpronomen).\n✓ "denen" = Relativpronomen جمع في الـ Dativ.\n✗ "die" = جمع في الـ Nominativ/Akkusativ، وبعد "an" بمعنى المكان نحتاج Dativ.\n✗ "den" = مفرد مذكر Akkusativ، وما يطابقش "Schulen" (جمع).`,
      rule: "Präposition + Relativpronomen: Plural Dativ = denen", ex: "Das sind die Schulen, an **denen** wir lernen.", exTr: "هذي المدارس اللي نقراو فيها." },
    23: { ok: "an", type: "preposition", keyword: "an fünf Tagen", bed: "في 5 أيام (في الجمعة)",
      text: `الأيام تتركّب مع "an" ("an einem Tag"، "an fünf Tagen").\n✓ "an" = Zeitangabe مع الأيام.\n✗ "in" = للأشهر والفصول والسنين ("im Mai"، "im Sommer")، موش للأيام مع عدد.\n✗ "durch" = عبر / بواسطة (وسيلة أو مرور)، ما تستعملش لتحديد أيام.`,
      rule: "an + Tag(en)", ex: "Ich arbeite **an** vier Tagen pro Woche.", exTr: "نخدم في 4 أيام في الجمعة." },
    24: { ok: "Mittwochs", type: "adjective_adverb", keyword: "Mittwochs", bed: "كل يوم أربعاء",
      text: `نحكيو على حاجة تتكرّر كل أسبوع: ما فماش دروس العشية. وللتعبير على التكرار نزيدو "s" لاسم اليوم.\n✓ "Mittwochs" = كل يوم أربعاء (Adverb).\n✗ "Jeder Mittwoch" = فاعل (Subjekt): كأنو اليوم نفسو "ما هوش درس"، وهذا ما يعطيش معنى "في الأربعاء ما فماش دروس" بصيغة طبيعية.\n✗ "Zum Mittwoch" = بحلول / لأجل الأربعاء (موعد)، موش تكرار أسبوعي.`,
      rule: "Wochentag + s = regelmäßig (montags, mittwochs …)", ex: "**Montags** habe ich frei.", exTr: "الاثنين (كل اثنين) عندي راحة." },
    25: { ok: "jedes Kurses", type: "grammar_structure", keyword: "Beginn + Genitiv", bed: "في بداية كل دورة",
      text: `"Beginn" يتبعو دايمًا Genitiv: "Beginn des Kurses" ← "Beginn jedes Kurses" (مذكر مفرد: ‑es).\n✓ "jedes Kurses" = Genitiv مذكر (jedes + Kurses).\n✗ "jedem Kurs" = Dativ، وما يتركّبش بعد "Beginn".\n✗ "jeden Kurs" = Akkusativ، نفس المشكل: "Beginn" ياخذ Genitiv.`,
      rule: "(zu) Beginn / Ende / Mitte + Genitiv", ex: "Zu Beginn **des Semesters** gibt es einen Test.", exTr: "في بداية السداسي فما اختبار." },
    26: { ok: "dessen", type: "pronoun", keyword: "mit dessen Hilfe", bed: "اللي بمساعدتو",
      text: `الجملة الفرعية تحكي على "Einstufungstest" (مذكر) وتقول "بمساعدتو": ضمير ملكية بصيغة Genitiv.\n✓ "dessen" = Genitiv للمذكر / المحايد (der Test).\n✗ "deren" = Genitiv للمؤنث أو الجمع، والـ Test مذكر.\n✗ "der" = Dativ / Genitiv مؤنث، وما يعطيش "اللي مساعدتو" بصيغة مذكر.`,
      rule: "Relativpronomen im Genitiv: dessen (m/n), deren (f/Pl.)", ex: "Das ist der Test, mit **dessen** Hilfe wir dein Niveau finden.", exTr: "هذا هو الاختبار اللي بمساعدتو نلقاو مستواك." },
    27: { ok: "wenn", type: "conjunction", keyword: "wenn = falls", bed: "إذا (في صورة النجاح)",
      text: `الشهادة تتعطى بشرط النجاح: يعني شرط (Bedingung).\n✓ "wenn" = إذا (شرط).\n✗ "obwohl" = رغم أنّ (تناقض)؛ معناها "رغم نجاحكم تاخذو شهادة"، وهذا غير منطقي.\n✗ "wobei" = وفي هذا السياق / حيث (إضافة معلومة)، وما تفتحش شرط.`,
      rule: "wenn + Nebensatz = Bedingung", ex: "**Wenn** du bestehst, bekommst du das Zertifikat.", exTr: "إذا نجحت، تاخو الشهادة." },
    28: { ok: "Ihnen", type: "pronoun", keyword: "anbieten + Dativ", bed: "تتعرض عليكم",
      text: `الرسالة رسمية (Sie)، و"anbieten" ياخذ شخص في الـ Dativ ("jemandem etwas anbieten")، وفي المبني للمجهول يبقى الشخص Dativ.\n✓ "Ihnen" = Dativ رسمي.\n✗ "Sie" = Nominativ / Akkusativ، والفعل يحتاج Dativ للشخص.\n✗ "Euch" = ضمير غير رسمي (ihr)، والرسالة رسمية بصيغة "Sie".`,
      rule: "jemandem etwas anbieten → es wird Ihnen angeboten", ex: "Die Reise wird **Ihnen** kostenlos angeboten.", exTr: "السفرة تتعرض عليكم بلاش." },
    29: { ok: "ist", type: "grammar_structure", keyword: "ist eingeschlossen", bed: "مشمولة (داخلة في الثمن)",
      text: `نحكيو على حالة ثابتة: الـ Halbpension "داخلة" في الثمن. هذا Zustandspassiv: sein + Partizip II.\n✓ "ist" = ist … eingeschlossen (حالة: مشمولة).\n✗ "hat" = يحتاج فاعل يعمل ومفعول ("hat … eingeschlossen")، موش حالة مشمولة.\n✗ "wird" = Vorgangspassiv (عملية جارية)، والمقصود النتيجة الثابتة.`,
      rule: "sein + Partizip II = Zustandspassiv (Ergebnis / Zustand)", ex: "Das Frühstück **ist** im Preis **enthalten**.", exTr: "الفطور مشمول في الثمن." },
    30: { ok: "eine Diät halten müssen", type: "grammar_structure", keyword: "Nebensatz: Modalverb am Ende", bed: "(إذا) لازم تتبعوا ريجيم",
      text: `الجملة تابعة لـ "wenn" (Nebensatz)، يعني الأفعال تروح للآخر: أول Infinitiv (halten) وبعدو Modalverb (müssen).\n✓ "eine Diät halten müssen" = المفعول، ثم Infinitiv، ثم Modalverb في الآخر.\n✗ "müssen eine Diät halten" = ترتيب Hauptsatz (Modalverb في الأول)، وفي Nebensatz الفعل المتصرّف يروح للآخر.\n✗ "müssen halten eine Diät" = المفعول جا بعد الأفعال، وهذا ترتيب مستحيل في الألمانية.`,
      rule: "Nebensatz: Objekt + Infinitiv + Modalverb (am Satzende)", ex: "… wenn Sie eine Diät **halten müssen**.", exTr: "…إذا لازم تتبعوا ريجيم." },
  },

  // ───────────── [4] Maria ─────────────
  4: {
    21: { ok: "noch", type: "adjective_adverb", keyword: "noch rasch", bed: "قبل ما نوفى، نبعثلك بسرعة",
      text: `"bevor wieder der Arbeitsalltag beginnt" معناها الوقت يضيق: نعمل حاجة زادة قبل ما نبدأو الخدمة. التعبير الطبيعي "noch rasch / noch schnell".\n✓ "noch" = (قبل ما…) حاجة أخيرة بسرعة.\n✗ "momentan" = توّا / في الوقت الحالي، ما يعطيش معنى "قبل ما…".\n✗ "weiterhin" = تواصل / لسّا (استمرار)، وما فماش حاجة تستمر هنا.`,
      rule: "noch (schnell / rasch) = zusätzlich, bevor es zu spät ist", ex: "Ich schreibe dir **noch** schnell eine Nachricht.", exTr: "نكتبلك رسالة صغيرة بسرعة قبل ما نمشي." },
    22: { ok: "wegen", type: "preposition", keyword: "wegen + Nomen", bed: "بسبب النزلة",
      text: `بعد الفراغ جاي اسم ("deiner Grippe") موش جملة بفعل، يعني نحتاج حرف جر.\n✓ "wegen" = بسبب (حرف جر + اسم).\n✗ "weil" = خاطر، رابط يحتاج جملة كاملة بفعل ("weil du Grippe hattest").\n✗ "deswegen" = لهذا السبب (ظرف)، ما ينجّمش يجي قبل اسم ويربطو.`,
      rule: "wegen + Nomen  |  weil + Nebensatz  |  deswegen = darum", ex: "**Wegen** des Regens bleiben wir zu Hause.", exTr: "بسبب الشتا نقعدو في الدار." },
    23: { ok: "bis", type: "fixed_expression", keyword: "bis auf", bed: "ماعدا ميركو (كلهم جاو بالقطار)",
      text: `التعبير الثابت لـ "ماعدا": "bis auf + شخص أو شي" (والكلمة اللي بعدو "auf").\n✓ "bis" = bis auf Mirko = ماعدا ميركو.\n✗ "abgesehen" = تحتاج "von" ("abgesehen von Mirko")، موش "auf".\n✗ "außer" = معناها ماعدا، لكن تتركّب بدون "auf" ("außer Mirko")؛ مع "auf" ما تصحش.`,
      rule: "bis auf + Akk. = außer", ex: "**Bis** auf einen Fehler war alles richtig.", exTr: "ماعدا غلطة وحدة، كلشي كان صحيح." },
    24: { ok: "hatten", type: "tense", keyword: "Nachdem + Plusquamperfekt", bed: "من بعد ما حطّينا الشنط",
      text: `"nachdem" معناها من بعد ما، والحدث اللي فيها صار قبل الحدث الأساسي، يعني نحتاج ماضي أبعد: Plusquamperfekt.\n✓ "hatten" = hatten … abgestellt (حطّينا الشنط قبل ما نمشيو نتمشّاو).\n✗ "haben" = Perfekt، نفس زمن الجملة الأساسية، وما يبيّنش إنو الحدث الأول صار قبل.\n✗ "hätten" = Konjunktiv II (شرط / خيال)، والجملة تحكي واقع صار.`,
      rule: "Nachdem + Plusquamperfekt (hatten + Partizip II) → Hauptsatz: Perfekt / Präteritum", ex: "Nachdem wir gegessen **hatten**, gingen wir spazieren.", exTr: "من بعد ما كليناهم، مشينا نتمشّاو." },
    25: { ok: "als", type: "verb_prep", keyword: "sich erweisen als", bed: "طلعت (بانت) مرشدة ممتازة",
      text: `الفعل "sich erweisen" (يبان / يطلع) يتركّب مع "als" + الصفة أو الاسم.\n✓ "als" = sich als … erweisen.\n✗ "für" = لأجل، وما تتركّبش مع "erweisen" بهذا المعنى.\n✗ "zur" = zu + der (حركة نحو)، وما نقولوش "sich zur Fremdenführerin erwiesen" بهذا المعنى.`,
      rule: "sich als + Nominativ erweisen", ex: "Er hat sich **als** guter Lehrer erwiesen.", exTr: "طلع معلم مليح." },
    26: { ok: "auf", type: "fixed_expression", keyword: "auf dem Programm stehen", bed: "كانت في البرنامج",
      text: `تعبير ثابت: "auf dem Programm stehen" = موجودة في البرنامج.\n✓ "auf" = auf dem Programm.\n✗ "in" = داخل، وما هوش التعبير الثابت المعتاد ("im Programm enthalten" يجي مع فعل آخر).\n✗ "zu" = إلى / نحو، وما يتركّبش مع "stehen" في هذا التعبير.`,
      rule: "auf dem Programm stehen = im Plan vorgesehen sein", ex: "Morgen steht ein Ausflug **auf** dem Programm.", exTr: "غدوة فما نزهة في البرنامج." },
    27: { ok: "ganz", type: "adjective_adverb", keyword: "ganz schön + Adj.", bed: "تعبانة برشا (مش شوية)",
      text: `"ganz schön anstrengend" تعبير محكي: "ganz schön" = برشا / موش قليل (ziemlich).\n✓ "ganz" = ganz schön + صفة.\n✗ "absolut" = تماماً / مطلقاً، تتركّب مع صفات مطلقة ("absolut super")، وما تتركّبش بـ "schön" هنا.\n✗ "vollkommen" = كاملاً، نفس المشكل، وما تعطيش المعنى المحكي "برشا".`,
      rule: "ganz schön + Adjektiv = ziemlich (viel)", ex: "Der Weg war **ganz** schön weit.", exTr: "الطريق كان بعيد برشا." },
    28: { ok: "obwohl", type: "conjunction", keyword: "obwohl + Nebensatz", bed: "رغم أنّ (الكل تعبان)",
      text: `الجملة فيها تناقض: كانو تعبانين، وبصح قعدو برشا يتكلمو. والفعل "waren" في الآخر، يعني نحتاج رابط يفتح Nebensatz.\n✓ "obwohl" = رغم أنّ (+ فعل في الآخر).\n✗ "trotzdem" = رغم ذلك (ظرف)، ما يفتحش Nebensatz، وياخذ الفعل في المرتبة الثانية ("trotzdem waren alle …").\n✗ "ungeachtet" = بغض النظر عن (حرف جر + Genitiv)، موش رابط جملة.`,
      rule: "obwohl + Nebensatz (Verb am Ende)  |  trotzdem + Hauptsatz (Verb an Position 2)", ex: "**Obwohl** ich müde war, bin ich gegangen.", exTr: "رغم إني كنت تعبان، مشيت." },
    29: { ok: "sollten", type: "verb", keyword: "sollten (Vorschlag)", bed: "اتفقنا إنو لازم نعملو",
      text: `"wir waren uns einig, dass …" = اتفقنا إنو … ونحكيو على قرار / اقتراح مشترك: يلزمنا نعملو نزهة قريب.\n✓ "sollten" = كان يلزمنا (اقتراح، اتفاق).\n✗ "durften" = كان مسموح لنا، الحديث على إذن، موش اتفاق على اقتراح.\n✗ "konnten" = كنا نجّمو (قدرة)، والجملة على قرار جماعي موش قدرة.`,
      rule: "sich einig sein, dass + wir … sollten = Empfehlung / Vorsatz", ex: "Wir waren uns einig, dass wir mehr lernen **sollten**.", exTr: "اتفقنا إنو لازم نقراو أكثر." },
    30: { ok: "inzwischen", type: "adjective_adverb", keyword: "inzwischen = mittlerweile", bed: "توّا (راك تحسّنت)",
      text: `"schon wieder besser" معناها بعد الوقت اللي فات (من وقت المرض لتوّا)، والظرف المناسب "inzwischen" (في هالأثناء / توّا).\n✓ "inzwischen" = ظرف زمان: بعد الوقت اللي مرّ.\n✗ "während" = أثناء (حرف جر أو رابط)، يحتاج حدث بعدو ("während du krank bist").\n✗ "zwischen" = بين (حرف جر)، يحتاج حاجتين أو فترتين.`,
      rule: "inzwischen = in der Zwischenzeit / mittlerweile", ex: "Ich hoffe, du bist **inzwischen** wieder gesund.", exTr: "نتمنى تكون توّا شفيت." },
  },
};
