// SB Teil 1 restyle — batch 12: [55] Kolleginnen und Kollegen, [56] Mitarbeiterinnen und Mitarbeiter, [57] HausbewohnerInnen, [58] Eltern (gap 21 FLAGGED, omitted)
export default {
  // ───────────── [55] Kolleginnen und Kollegen ( Neu ) ─────────────
  55: {
    21: { ok: "dazu", type: "pronoun_adverb", keyword: "einladen zu → dazu", bed: "لهذا (نعزمكم باش)",
      text: `"einladen" يتبعو "zu"، والـ Pronominaladverb "dazu" (= zu + das) يعلن على الجملة اللي بعدو ("etwas … zu tun").\n✓ "dazu" = لهذا (zu + das).\n✗ "dafür" = لأجل هذا (für + das)، و"einladen für" تجي مع مدّة زمنية موش مع فعل.\n✗ "daran" = في هذا (an + das)، و"einladen daran" ما تتقالش.`,
      rule: "jdn. zu etwas einladen → dazu einladen, etwas zu tun", ex: "Ich lade dich **dazu** ein, mitzukommen.", exTr: "نعزمك باش تجي معانا." },
    22: { ok: "Wenn", type: "conjunction", keyword: "wenn (Präsens, allgemein)", bed: "كي (تجمعو)",
      text: `الجملة تصف حاجة عامّة دايمًا صحيحة (حاضر): "Wenn Ihr den Arbeitsweg mit Bewegung verbindet …".\n✓ "Wenn" = كي / كلّما (حاضر وعام).\n✗ "Als" = وقتما (حدث ماضي مرة وحدة)، والجملة حاضر.\n✗ "Ob" = هل (سؤال غير مباشر)، وما فماش سؤال.`,
      rule: "wenn = Präsens / Wiederholung  |  als = einmalig in der Vergangenheit  |  ob = indirekte Frage", ex: "**Wenn** man viel liest, lernt man viel.", exTr: "كي الواحد يقرا برشا يتعلّم برشا." },
    23: { ok: "beim", type: "preposition", keyword: "helfen bei + Dativ (beim Sparen)", bed: "في (التوفير)",
      text: `"helfen" + "bei" + اسم مشتق من فعل: "beim Sparen" (bei + dem).\n✓ "beim" = bei + dem (helfen bei).\n✗ "an das" = ما تتركّبش مع "helfen".\n✗ "zur" = zu + der (مؤنّث)، و"Sparen" محايد (فعل كاسم).`,
      rule: "helfen bei + Dativ (beim + nominalisiertes Verb: beim Sparen, beim Lernen)", ex: "Das Navi hilft **beim** Finden des Weges.", exTr: "الـ GPS يعاون في إيجاد الطريق." },
    24: { ok: "etwas", type: "pronoun", keyword: "etwas gewinnen", bed: "حاجة (نربحو)",
      text: `"die Möglichkeit, ___ zu gewinnen": حاجة غير محدّدة نربحوها: "etwas".\n✓ "etwas" = حاجة (Pronomen محايد).\n✗ "einige" = شوية (تتبعها اسم جمع)، وهنا ما فماش اسم.\n✗ "keine" = لا شيء، وتتناقض مع الإغراء بالجوائز.`,
      rule: "etwas = unbestimmte Sache (Neutrum) + zu + Infinitiv", ex: "Hier kann man **etwas** gewinnen.", exTr: "هنا الواحد ينجّم يربح حاجة." },
    25: { ok: "spätestens", type: "adjective_adverb", keyword: "bis spätestens + Datum", bed: "على أبعد تقدير",
      text: `موعد نهائي: "bis spätestens 5. November" (آخر أجل).\n✓ "spätestens" = على أبعد تقدير.\n✗ "alsbald" = قريبًا / فورًا (أسلوب رسمي)، وما تتركّبش مع تاريخ.\n✗ "beizeiten" = بكري (في الوقت المناسب)، وما تحدّدش موعد نهائي.`,
      rule: "bis spätestens + Datum = letzter Termin", ex: "Ruf mich bis **spätestens** Montag an.", exTr: "عيّطلي على أقصى تقدير لين الإثنين." },
    26: { ok: "zwischen", type: "preposition", keyword: "zwischen … und …", bed: "بين (الخدمة والدار)",
      text: `"Arbeit und Wohnung" طرفين، والمسافة بينهم: "zwischen … und …".\n✓ "zwischen" = بين (+ اسمين بـ "und").\n✗ "entlang" = على طول (يتبعها اسم واحد: "entlang der Straße")، موش طرفين.\n✗ "von" = من: "von … nach …" ممكنة، بصح مع "und" التعبير الصحيح "zwischen".`,
      rule: "zwischen + A und B  |  von A nach B", ex: "Die Strecke **zwischen** Haus und Büro ist kurz.", exTr: "المسافة بين الدار والمكتب قصيرة." },
    27: { ok: "sich", type: "pronoun", keyword: "sich melden (wer → sich)", bed: "يتّصل (بروحو)",
      text: `الفاعل "Wer" (غائب مفرد) والفعل "melden" انعكاسي: "kann sich melden".\n✓ "sich" = انعكاسي للغائب.\n✗ "euch" = لـ "ihr" (إنتوما)، والفاعل هنا "Wer".\n✗ "ihn" = Akkusativ (Personalpronomen)، موش ضمير انعكاسي.`,
      rule: "Reflexivpronomen: wer / er / sie / es → sich", ex: "Wer Fragen hat, kann **sich** melden.", exTr: "اللي عندو أسئلة ينجّم يتّصل." },
    28: { ok: "überprüfen", type: "verb", keyword: "überprüfen lassen", bed: "يتفحّص (الدرّاجة)",
      text: `خدمة تقنية مجانية للدرّاجة: "überprüfen lassen" (يفحصوها).\n✓ "überprüfen" = يفحص / يراجع.\n✗ "übergeben" = يسلّم (etwas übergeben)، موش فحص.\n✗ "übernehmen" = يتسلّم / يتحمّل، وما تعبّرش على فحص الدرّاجة.`,
      rule: "etwas überprüfen lassen = kontrollieren lassen  |  übergeben = aushändigen  |  übernehmen = annehmen", ex: "Ich lasse mein Auto **überprüfen**.", exTr: "نخلّي كرهبتي تتفحّص." },
    29: { ok: "am", type: "fixed_expression", keyword: "am Herzen liegen", bed: "تهمّنا (على القلب)",
      text: `تعبير ثابت: "jdm. am Herzen liegen" (تهمّو برشا).\n✓ "am" = an + dem (am Herzen liegen).\n✗ "beim" = bei + dem، و"beim Herzen liegen" ما تتقالش.\n✗ "zum" = zu + dem، و"zum Herzen liegen" ما تتقالش.`,
      rule: "jdm. am Herzen liegen = wichtig sein", ex: "Die Umwelt liegt mir **am** Herzen.", exTr: "البيئة تهمّني برشا." },
    30: { ok: "auf", type: "verb_prep", keyword: "hoffen auf + Akk.", bed: "نتمنّاو (مشاركة)",
      text: `"hoffen" يتبعو "auf" + Akkusativ: "hoffen auf eine rege Teilnahme".\n✓ "auf" = على (hoffen auf).\n✗ "an" = ما تتركّبش مع "hoffen" (الحرف "an" مع "glauben an").\n✗ "mit" = مع، وما تعبّرش على الأمل في حاجة.`,
      rule: "hoffen auf + Akk.  |  glauben an + Akk.", ex: "Ich hoffe **auf** gutes Wetter.", exTr: "نتمنّى طقس مليح." },
  },

  // ───────────── [56] Mitarbeiterinnen und Mitarbeiter ( Neu ) ─────────────
  56: {
    21: { ok: "die", type: "pronoun", keyword: "Relativpronomen Akk. Plural: die", bed: "اللي (الأهداف)",
      text: `مرجع الجملة "Jahresziele" (جمع)، وفي الجملة الفرعية هي مفعول به (sich etwas vornehmen): Akkusativ جمع = "die".\n✓ "die" = Akkusativ جمع (die Ziele, die wir uns vorgenommen haben).\n✗ "der" = Genitiv / Dativ جمع أو مؤنّث، موش Akkusativ جمع.\n✗ "diese" = اسم إشارة (هذه)، موش Relativpronomen يفتح جملة فرعية.`,
      rule: "Relativpronomen: Plural Nominativ / Akkusativ = die", ex: "Die Ziele, **die** wir uns gesetzt haben, sind klar.", exTr: "الأهداف اللي حطّيناها واضحة." },
    22: { ok: "dass", type: "conjunction", keyword: "überzeugt sein, dass …", bed: "إنّو (باش نكمّلو)",
      text: `"davon überzeugt, ___ wir … meistern werden": محتوى القناعة ← "dass".\n✓ "dass" = إنّو (محتوى، والفعل في الآخر).\n✗ "das" = Artikel / Pronomen بحرف s واحد، موش رابط يفتح جملة فرعية.\n✗ "ob" = هل (سؤال)، و"überzeugt sein" يطلب خبر موش سؤال.`,
      rule: "überzeugt sein, dass + Nebensatz", ex: "Ich bin überzeugt, **dass** es klappt.", exTr: "متأكّد إنّو باش يخدم." },
    23: { ok: "Magazins", type: "grammar_structure", keyword: "Genitiv: des Magazins", bed: "متاع (المجلة)",
      text: `"unseres" + Genitiv: "Magazin" محايد، وGenitiv يزيد -s: "unseres Magazins".\n✓ "Magazins" = Genitiv محايد (-s).\n✗ "Magazin" = بدون نهاية Genitiv.\n✗ "Magazines" = شكل قديم ونادر، والمعتاد -s.`,
      rule: "Genitiv maskulin / neutrum: -s (des Magazins)", ex: "Die Seiten des **Magazins** sind bunt.", exTr: "صفحات المجلة ملوّنة." },
    24: { ok: "denen", type: "pronoun", keyword: "denen (Relativpronomen Dativ Pl.)", bed: "اللي (نوجّه ليهم)",
      text: `"jdm. Lob aussprechen": الشخص في Dativ، والمرجع "KommunikationsexpertInnen" (جمع): "denen".\n✓ "denen" = Dativ جمع (Relativpronomen).\n✗ "den" = Artikel Dativ جمع، موش Relativpronomen.\n✗ "dem" = Dativ مفرد، والمرجع جمع.`,
      rule: "Relativpronomen Dativ Plural: denen (jdm. Lob aussprechen)", ex: "Die Kollegen, **denen** ich danke, haben viel geholfen.", exTr: "الزملاء اللي نشكرهم عاونوا برشا." },
    25: { ok: "zu", type: "grammar_structure", keyword: "zu + Infinitiv", bed: "باش (نقوّيو)",
      text: `"Hier gilt weiterhin, die Kooperationen ___ stärken …": Infinitivsatz بـ "zu" + Infinitiv.\n✓ "zu" = zu + Infinitiv (zu stärken).\n✗ "zum" = zu + dem (قبل اسم)، وبعدها "stärken" فعل موش اسم.\n✗ "zur" = zu + der (قبل اسم مؤنّث)، موش قبل فعل.`,
      rule: "zu + Infinitiv (Infinitivsatz nach 'es gilt')", ex: "Es gilt, die Qualität **zu** sichern.", exTr: "لازم نحافظو على الجودة." },
    26: { ok: "im", type: "preposition", keyword: "im Sommer", bed: "في (الصيف)",
      text: `"Ausgabe im Sommer" = عدد الصيف: الفصول بـ "im" (in + dem).\n✓ "im" = في (in + dem).\n✗ "in" = بدون أداة "in Sommer" ما تتقالش.\n✗ "aus" = من، و"die Ausgabe aus Sommer" ما تتقالش بدون أداة.`,
      rule: "im + Jahreszeit (in + dem)", ex: "Die Ausgabe **im** Winter erscheint früher.", exTr: "عدد الشتاء يصدر بكري." },
    27: { ok: "Dieses", type: "grammar_structure", keyword: "dieses Mal (Neutrum)", bed: "هالمرّة",
      text: `"das Mal" محايد، وهنا مفعول به زمني (Akkusativ): "Dieses Mal".\n✓ "Dieses" = Akkusativ محايد.\n✗ "Diese" = مؤنّث أو جمع، و"Mal" محايد.\n✗ "Diesen" = مذكّر Akkusativ أو Dativ جمع، و"Mal" محايد.`,
      rule: "das Mal (Neutrum): dieses / letztes / nächstes Mal", ex: "**Dieses** Mal gewinne ich.", exTr: "هالمرّة باش نربح." },
    28: { ok: "bei", type: "verb_prep", keyword: "sich bei jdm. bedanken", bed: "عند (المصمّمين)",
      text: `الشخص اللي نشكرو بـ "bei"، والشي اللي نشكرو عليه بـ "für": "sich bei den GraphikerInnen bedanken".\n✓ "bei" = عند (sich bei + Person bedanken).\n✗ "von" = من، وما تتركّبش مع "bedanken".\n✗ "für" = على (الشي الممنون عليه: "für die Lösung")، موش الشخص.`,
      rule: "sich bei + Person bedanken für + Sache", ex: "Ich bedanke mich **bei** dir für deine Hilfe.", exTr: "نشكرك على مساعدتك." },
    29: { ok: "welches", type: "pronoun", keyword: "welches (Relativpronomen neutr. Nom.)", bed: "اللي (الحفلة)",
      text: `مرجع الجملة "Sommerfest" (محايد) وهو فاعل: Relativpronomen Nominativ محايد "welches".\n✓ "welches" = Nominativ محايد (بديل رسمي لـ "das").\n✗ "welcher" = مذكّر أو Dativ مؤنّث، و"Sommerfest" محايد.\n✗ "welchem" = Dativ مذكّر / محايد، والجملة تحتاج Nominativ فاعل.`,
      rule: "Relativpronomen neutrum Nominativ: das / welches", ex: "Das Fest, **welches** morgen stattfindet, ist kostenlos.", exTr: "الحفلة اللي تصير غدوة مجّانية." },
    30: { ok: "gemeinsamen", type: "grammar_structure", keyword: "unseren gemeinsamen Erfolg (-en)", bed: "المشترك",
      text: `"Erfolg" مذكّر ومفعول به: بعد "unseren" الصفة تاخذ -en: "unseren gemeinsamen Erfolg".\n✓ "gemeinsamen" = -en (Akkusativ مذكّر بعد Possessiv).\n✗ "gemeinsames" = -es للمحايد، و"Erfolg" مذكّر.\n✗ "gemein" = بدون نهاية، ومعناها "لئيم / قبيح"، موش "مشترك".`,
      rule: "Possessiv + Akkusativ maskulin → Adjektiv + -en", ex: "Wir feiern unseren **gemeinsamen** Sieg.", exTr: "نحتفلو بانتصارنا المشترك." },
  },

  // ───────────── [57] HausbewohnerInnen ─────────────
  57: {
    21: { ok: "Dafür", type: "pronoun_adverb", keyword: "dafür = für diesen Zweck", bed: "لهذا (الغرض)",
      text: `"باش يتجهّز الدار للشتاء… لهذا الغرض لازمنا تحضيرات": "Dafür" (= für + das)، والفعل "sind" بعدو في المرتبة الثانية.\n✓ "Dafür" = لهذا الغرض (für + das).\n✗ "Damit" = باش (رابط غرض + فعل في الآخر)، وهنا "sind" في الثانية.\n✗ "So" = هكا (طريقة)، وما تعطيش الغرض.`,
      rule: "dafür = für diesen Zweck (Adverb, Verb Position 2)  |  damit + Nebensatz = Zweck", ex: "Wir bauen um, **dafür** brauchen wir Geld.", exTr: "نبدّلو الدار، ولهذا نحتاجو فلوس." },
    22: { ok: "werden", type: "tense", keyword: "werden + Partizip II (Passiv)", bed: "تتعمل",
      text: `الأشغال ما يعملوهاش المتكلّم، فهي مبنية للمجهول: "werden … durchgeführt" (Vorgangspassiv).\n✓ "werden" = Passiv Präsens (جمع).\n✗ "sind" = Zustandspassiv (حالة: "sind durchgeführt" = تمّت خلاص)، والأشغال لسّا جاية.\n✗ "können" = فعل مساعد، ويحتاج "durchgeführt werden" في الآخر.`,
      rule: "Vorgangspassiv Präsens: werden + Partizip II", ex: "Die Kontrollen **werden** jährlich durchgeführt.", exTr: "الفحوصات تتعمل كلّ عام." },
    23: { ok: "bis", type: "preposition", keyword: "bis zu + Dativ (Frist)", bed: "لين (هذا التاريخ)",
      text: `"bis zu diesem Datum" = قبل أو في حدّ هذا التاريخ (آخر أجل).\n✓ "bis" = لين (bis zu + Dativ).\n✗ "bei" = عند (+ Dativ)، و"bei zu diesem Datum" ما تتقالش.\n✗ "vor" = قبل، و"vor zu diesem Datum" ما تتقالش.`,
      rule: "bis zu + Dat. = Frist / Endpunkt", ex: "Bitte räumt alles **bis** zum Freitag weg.", exTr: "بالله نظّفو كلّ شي لين الجمعة." },
    24: { ok: "behoben", type: "tense", keyword: "Partizip II + werden müssen (Passiv)", bed: "تتصلّح",
      text: `"die Schäden, die … ___ werden müssen": Passiv مع فعل مساعد ← Partizip II + "werden".\n✓ "behoben" = Partizip II من "beheben" (يصلّح).\n✗ "beheben" = Infinitiv، وقبل "werden" نحتاج Partizip II.\n✗ "behebt" = Präsens (3. Person)، موش Partizip II.`,
      rule: "Passiv mit Modalverb: Partizip II + werden + Modalverb", ex: "Der Fehler muss **behoben** werden.", exTr: "الغلطة لازم تتصلّح." },
    25: { ok: "um", type: "conjunction", keyword: "um … zu + Infinitiv (Zweck)", bed: "باش (نركّبو)",
      text: `الغرض من مجيء العمّال: "um … neue Fensterscheiben einzusetzen".\n✓ "um" = باش (um … zu + Infinitiv).\n✗ "dass" = إنّو (محتوى)، وما تتماشاش مع "zu-Infinitiv".\n✗ "für" = لـ (+ اسم)، وهنا بعدها فعل.`,
      rule: "um … zu + Infinitiv = Zweck (gleiches Subjekt)", ex: "Er kommt, **um** uns zu helfen.", exTr: "يجي باش يعاوننا." },
    26: { ok: "ermöglichen", type: "verb", keyword: "Zugang ermöglichen", bed: "تسهّلو (الدخول)",
      text: `"den Zugang … zu ___" = تتيحو الدخول للعمّال: "ermöglichen".\n✓ "ermöglichen" = يتيح / يسهّل.\n✗ "verhindern" = يمنع (عكس المطلوب).\n✗ "vergessen" = ينسى، وما يتماشاش مع الطلب.`,
      rule: "ermöglichen = möglich machen  |  verhindern = unmöglich machen", ex: "Wir bitten Sie, den Zugang zu **ermöglichen**.", exTr: "نرجوكم تسهّلو الدخول." },
    27: { ok: "letzter", type: "grammar_structure", keyword: "in letzter Zeit", bed: "في الفترة الأخيرة",
      text: `"in letzter Zeit" = مؤخرًا: "in" + Dativ مؤنّث بدون أداة ← -er.\n✓ "letzter" = Dativ مؤنّث (Adjektiv ohne Artikel).\n✗ "einiger" = "in einiger Zeit" معناها بعد مدّة (مستقبل)، وهنا نحكيو على فترة فاتت.\n✗ "letzte" = Nominativ / Akkusativ مؤنّث، و"in" هنا تتبعها Dativ.`,
      rule: "in letzter Zeit (Dativ fem., Adjektiv ohne Artikel: -er)", ex: "In **letzter** Zeit habe ich viel gearbeitet.", exTr: "في الفترة الأخيرة خدمت برشا." },
    28: { ok: "dass", type: "conjunction", keyword: "darauf achten, dass …", bed: "إنّو (ما يتضايقوش)",
      text: `"darauf achten, ___ …" = محتوى الانتباه: "dass".\n✓ "dass" = إنّو (محتوى، والفعل في الآخر).\n✗ "weswegen" = وهذا علاش (نتيجة / سؤال)، موش محتوى.\n✗ "weil" = خاطر (سبب)، و"darauf achten, weil" ما تتقالش هنا.`,
      rule: "darauf achten, dass + Nebensatz", ex: "Achten Sie darauf, **dass** die Tür zu ist.", exTr: "انتبهو إنّو الباب مسكّر." },
    29: { ok: "Bällen", type: "grammar_structure", keyword: "mit + Dativ Plural (Bällen)", bed: "بالكرات",
      text: `"mit" + Dativ جمع: "Ball" يتحوّل لـ "Bällen" (جمع + -n في Dativ).\n✓ "Bällen" = Dativ جمع.\n✗ "Bälle" = Nominativ / Akkusativ جمع، و"mit" تحتاج Dativ.\n✗ "Ballen" = كلمة أخرى (حزمة / بالّة: Heuballen)، موش كرات.`,
      rule: "mit + Dativ; Dativ Plural endet auf -n (Bällen)", ex: "Die Kinder spielen mit **Bällen**.", exTr: "الصغار يلعبو بالكرات." },
    30: { ok: "freundlichen", type: "grammar_structure", keyword: "mit freundlichen Grüßen", bed: "(تحيّات) لطيفة",
      text: `"mit" + Dativ جمع، والصفة بدون أداة تاخذ -en: "mit freundlichen Grüßen".\n✓ "freundlichen" = Dativ جمع (-en).\n✗ "freundliche" = Nominativ / Akkusativ جمع، و"mit" تحتاج Dativ.\n✗ "freundlichem" = Dativ مفرد (مذكّر / محايد)، و"Grüßen" جمع.`,
      rule: "mit + Dativ Plural: Adjektiv -en (mit freundlichen Grüßen)", ex: "Wir wünschen Ihnen **freundlichen** Empfang.", exTr: "نتمنّولكم استقبال لطيف." },
  },

  // ───────────── [58] Eltern und Erziehungsberechtigte (gap 21 FLAGGED: key "Anlässlich" — "___ mehr Internetsicherheit" wants a purpose word, likely "Zwecks") ─────────────
  58: {
    22: { ok: "denen", type: "pronoun", keyword: "denen (Relativpronomen Dativ Pl.: sich widmen)", bed: "اللي (نهتمّو بيهم)",
      text: `"sich einer Sache widmen" يتركّب مع Dativ، والمرجع "Bereiche" (جمع): "denen wir uns widmen".\n✓ "denen" = Dativ جمع (Relativpronomen).\n✗ "deren" = Genitiv جمع (ملكية)، وما فماش اسم ملكية بعدها.\n✗ "dessen" = Genitiv مذكّر / محايد، والمرجع جمع.`,
      rule: "sich + Dativ widmen → Relativpronomen im Dativ (denen)", ex: "Das sind Aufgaben, **denen** ich mich gern widme.", exTr: "هذي مهام نهتمّ بيها بكل نفس." },
    23: { ok: "darum", type: "pronoun_adverb", keyword: "es geht um → darum, … zu + Inf.", bed: "المسألة هي (باش)",
      text: `"es geht um etwas" ← "es geht darum, … zu beleuchten": "darum" (= um + das) يعلن على الـ Infinitivsatz.\n✓ "darum" = um + das (es geht darum).\n✗ "davon" = von + das، و"es geht davon" ما تتقالش.\n✗ "darüber" = über + das، و"es geht darüber" ما تتقالش (الحرف مع "gehen" هو "um").`,
      rule: "es geht um + Akk. → es geht darum, … zu + Infinitiv", ex: "Es geht **darum**, Fehler zu vermeiden.", exTr: "المهم هو نتفاداو الغلطات." },
    24: { ok: "Um", type: "conjunction", keyword: "um … zu + Infinitiv", bed: "باش (نتعرّفو)",
      text: `"Um solche zu erkennen, muss man …": غرض بنفس الفاعل ("man")، Infinitivsatz.\n✓ "Um" = باش (um … zu + Infinitiv).\n✗ "damit" = باش (+ جملة فرعية بفعل مصرّف، وفاعل مختلف)، وهنا "zu erkennen" Infinitiv.\n✗ "dass" = إنّو (محتوى)، موش غرض.`,
      rule: "um … zu + Infinitiv (gleiches Subjekt)  |  damit + Nebensatz (anderes Subjekt)", ex: "**Um** Fehler zu finden, muss man genau lesen.", exTr: "باش تلقى الغلطات لازم تقرا بدقّة." },
    25: { ok: "herzen", type: "fixed_expression", keyword: "am Herzen liegen (Dativ: Herzen)", bed: "على القلب (يهمّنا)",
      text: `"am Herzen liegen": "Herz" في Dativ يتحوّل لـ "Herzen" (استثناء).\n✓ "Herzen" = Dativ (am Herzen = an dem Herzen).\n✗ "Herz" = الصيغة الأساسية (Nominativ)، موش Dativ.\n✗ "Herze" = شكل غلط (ما فماش "Herze" في الألمانية الحديثة).`,
      rule: "das Herz: Dativ = dem Herzen (Ausnahme der n-Deklination)", ex: "Das liegt mir sehr am **Herzen**.", exTr: "هذا يهمّني برشا." },
    26: { ok: "anhand", type: "preposition", keyword: "anhand + Genitiv", bed: "بالاعتماد على",
      text: `"anschaulicher Beispiele" في Genitiv جمع: حرف الجر المناسب "anhand" (+ Genitiv).\n✓ "anhand" = بالاعتماد على (anhand + Genitiv).\n✗ "durch" = عبر (+ Akkusativ)، و"durch anschaulicher Beispiele" ما تتماشاش.\n✗ "mit" = مع (+ Dativ: "mit anschaulichen Beispielen")، موش Genitiv.`,
      rule: "anhand + Genitiv (= mithilfe von)", ex: "**Anhand** einiger Beispiele lernen wir die Regel.", exTr: "بالاعتماد على أمثلة نتعلّمو القاعدة." },
    27: { ok: "geschaffen", type: "tense", keyword: "geschaffen werden (Passiv)", bed: "تتخلق",
      text: `"eine alternative Realität … werden kann" = تتخلق: Partizip II من "schaffen" بمعنى "خلق": "geschaffen".\n✓ "geschaffen" = Partizip II من schaffen (erschaffen: schuf – geschaffen).\n✗ "schaffen" = Infinitiv، وقبل "werden" نحتاج Partizip II.\n✗ "geschafft" = Partizip II من "schaffen" بمعنى "نجّح / قدر" (schaffte – geschafft)، موش "خلق".`,
      rule: "schaffen (erschaffen) – schuf – geschaffen  |  schaffen (bewältigen) – schaffte – geschafft", ex: "Hier kann Neues **geschaffen** werden.", exTr: "هنا ينجّم يتخلق حاجة جديدة." },
    28: { ok: "größter", type: "adjective_adverb", keyword: "von größter Bedeutung", bed: "من أكبر أهمّية",
      text: `"von größter Bedeutung" = من أقصى أهمّية: Superlativ + نهاية Dativ مؤنّث بدون أداة (-er).\n✓ "größter" = Superlativ (Dativ fem. ohne Artikel).\n✗ "größe" = شكل ما موجودش كصفة بهذا الاستعمال.\n✗ "größen" = شكل جمع / غلط، و"Bedeutung" مفرد مؤنّث.`,
      rule: "Superlativ: Adjektiv + -st + Endung (von größter Bedeutung)", ex: "Das ist von **größter** Wichtigkeit.", exTr: "هذا من أكبر الأهمّية." },
    29: { ok: "lässt", type: "verb", keyword: "sich lassen + Infinitiv (Passiversatz)", bed: "ينجّم (الواحد)",
      text: `"wie sich Derartiges vermeiden lässt" = كيفاش ينجّم الواحد يتفادى: "sich lassen" + Infinitiv، والفاعل "Derartiges" مفرد.\n✓ "lässt" = 3. Person Singular (يطابق "Derartiges").\n✗ "lassen" = Infinitiv / جمع، والفاعل هنا مفرد.\n✗ "lasst" = Imperativ جمع (ihr)، موش فعل جملة فرعية.`,
      rule: "etwas lässt sich + Infinitiv = kann + Passiv; das Verb richtet sich nach dem Subjekt", ex: "Das Problem **lässt** sich leicht lösen.", exTr: "المشكل ينحلّ بسهولة." },
    30: { ok: "während", type: "preposition", keyword: "während + Genitiv", bed: "أثناء (الدرس)",
      text: `"des Unterrichts" في Genitiv: حرف الجر الزمني "während" (+ Genitiv).\n✓ "während" = أثناء (+ Genitiv).\n✗ "nämlich" = يعني / خاطر (ظرف تفسير)، موش حرف جر.\n✗ "trotzdem" = رغم ذلك (ظرف)، وما تتبعهاش Genitiv.`,
      rule: "während + Genitiv (Zeit)  |  trotz + Genitiv (Gegensatz)", ex: "**Während** des Unterrichts ist Essen verboten.", exTr: "أثناء الدرس الماكلة ممنوعة." },
  },
};
