// SB Teil 1 restyle — batch 08: [35] Liebe Sandra (معدل) (gap 27 FLAGGED, omitted), [36] Igor, [37] Ida, [38] Corinna (Original), [39] Corinna (معدل)
export default {
  // ───────────── [35] Liebe Sandra (معدل) ─────────────
  35: {
    21: { ok: "es", type: "pronoun", keyword: "es überrascht dich, dass …", bed: "(الشي) يفاجئك",
      text: `"überraschen" يحتاج فاعل، واللي يفسّرو هو الـ dass-Satz اللي جاي: نبداو بـ "es" كضمير مسبق.\n✓ "es" = فاعل شكلي يعلن على "dass-Satz" (es überrascht dich, dass …).\n✗ "was" = شنوّة / اللي (سؤال أو Relativpronomen)، موش فاعل شكلي.\n✗ "das" = هذا (إشارة)، ممكنة في الكلام اليومي بصح مع "dass-Satz" الصياغة المعتادة "es".`,
      rule: "es als Platzhalter (Korrelat) für einen folgenden dass-Satz", ex: "**Es** freut mich, dass du gekommen bist.", exTr: "يفرّحني إنّك جيت." },
    22: { ok: "dass", type: "conjunction", keyword: "überrascht dich, dass …", bed: "إنّي (نعمل عطلة)",
      text: `الجملة الفرعية تعطي محتوى المفاجأة ("إنّي نعمل عطلة في جزيرة"): "dass".\n✓ "dass" = إنّو (محتوى، والفعل في الآخر).\n✗ "ob" = إذا بمعنى whether (في سؤال غير مباشر)، وما فماش سؤال هنا.\n✗ "weil" = خاطر (سبب)، والجملة تعطي محتوى المفاجأة موش سببها.`,
      rule: "dass-Satz nach Gefühlsverben / Mitteilungen (überraschen, freuen, sagen)", ex: "Es überrascht mich, **dass** er schon da ist.", exTr: "يفاجئني إنّو وصل." },
    23: { ok: "viel", type: "adjective_adverb", keyword: "viel + unzählbar (viel Stress)", bed: "برشا (ضغط)",
      text: `"Stress" مفرد وغير معدود، فالكمية تتقال بـ "viel" بدون نهاية.\n✓ "viel" = برشا (+ اسم غير معدود: viel Stress).\n✗ "viele" = للجمع المعدود (viele Aufgaben)، و"Stress" مفرد.\n✗ "großen" = صفة تصف الشدّة: "großen Stress" صحيحة نحويًّا، بصح الفراغ هنا يعطي كمية، والتعبير الأنسب "viel Stress".`,
      rule: "viel + unzählbares Nomen (viel Stress, viel Zeit)  |  viele + Plural", ex: "Ich habe zurzeit **viel** Arbeit.", exTr: "عندي توّا برشا خدمة." },
    24: { ok: "was", type: "pronoun", keyword: "was (Bezug auf ganzen Satz)", bed: "اللي (وهذا اللي نحسّو مريح)",
      text: `الجملة الفرعية تعلّق على الوصف كلّو ("mild und nicht zu heiß") موش على اسم واحد: "was".\n✓ "was" = اللي (يرجع على الجملة كاملة).\n✗ "das" = Relativpronomen يرجع لاسم محايد بالضبط (das Klima, das …)، وهنا التعليق على الوصف كلّو.\n✗ "es" = ضمير شخصي (it)، موش Relativpronomen يفتح جملة فرعية.`,
      rule: "was = Relativpronomen mit Bezug auf einen ganzen Satz oder eine Aussage", ex: "Er hat gewonnen, **was** mich sehr freut.", exTr: "ربح، وهذا يفرّحني برشا." },
    25: { ok: "aus", type: "verb_prep", keyword: "bestehen aus + Dativ", bed: "يتركّب من",
      text: `الجزيرة مبنيّة من جزيرتين (مكوّنات): "besteht aus zwei Inseln".\n✓ "aus" = من (bestehen aus + Dativ).\n✗ "in" = في (bestehen in = يتمثّل في فكرة: "Die Lösung besteht in …")، وهنا أجزاء ملموسة.\n✗ "zu" = تجي غير مع نسبة ("zu 80 % aus Wasser")، موش مع عدد أجزاء.`,
      rule: "bestehen aus + Dat. (Teile)  |  bestehen in + Dat. (Inhalt)  |  zu + Prozent", ex: "Das Paket besteht **aus** drei Teilen.", exTr: "الطرد يتكوّن من ثلاثة أجزاء." },
    26: { ok: "erreichen", type: "grammar_structure", keyword: "zu + Infinitiv (zu erreichen)", bed: "نوصلو ليها",
      text: `"die … zu ___ ist" = sein + zu + Infinitiv: بعد "zu" نحط الـ Infinitiv.\n✓ "erreichen" = Infinitiv (zu erreichen ist = ينجّم الواحد يوصل ليها).\n✗ "erreicht" = Partizip II، وما يتركّبش مع "zu" في هذا الموضع.\n✗ "erreichte" = Präteritum (فعل مصرّف)، وبعد "zu" لازم Infinitiv.`,
      rule: "sein + zu + Infinitiv (nie Partizip II): ist zu erreichen", ex: "Der Ort ist nur per Bus zu **erreichen**.", exTr: "المكان يتوصّل ليه غير بالبيّاص." },
    28: { ok: "wenige", type: "grammar_structure", keyword: "nur wenige + Plural", bed: "غير ساعات قلايل",
      text: `"Stunden" جمع بدون أداة: الكمية "wenige" بنهاية -e في الـ Akkusativ.\n✓ "wenige" = قلايل (-e: Akkusativ جمع بدون أداة).\n✗ "wenigen" = -en تجي بعد أداة معرّفة أو مع Dativ، وهنا لا أداة ولا Dativ.\n✗ "weniger" = أقلّ (مقارنة وتحتاج "als")، والمقصود "ساعات قلايل".`,
      rule: "Akk. Plural ohne Artikel: wenige / einige / viele + -e", ex: "Sie hat nur **wenige** Stunden geschlafen.", exTr: "رقدت غير ساعات قلايل." },
    30: { ok: "Was", type: "fixed_expression", keyword: "Was gibt es Neues?", bed: "شنوّة (الجديد)",
      text: `سؤال على الأخبار: "Was gibt es bei dir Neues?" (شنوّة الجديد عندك).\n✓ "Was" = شنوّة (سؤال على شي).\n✗ "Wie" = كيفاش (طريقة أو حالة)، و"Wie gibt es Neues?" ما تعطيش معنى.\n✗ "warum" = علاش (سبب)، موش سؤال على محتوى الأخبار.`,
      rule: "Was gibt es Neues? = Frage nach einer Sache (Fragewort 'was')", ex: "**Was** gibt es heute zum Essen?", exTr: "شنوّة فما اليوم للماكلة؟" },
  },

  // ───────────── [36] Igor ─────────────
  36: {
    21: { ok: "über", type: "verb_prep", keyword: "sich freuen über + Akk.", bed: "فرحت بيها (الرسالة)",
      text: `"sich freuen" + "über" + Akkusativ: الرسالة وصلت وفرحت بيها: "über die".\n✓ "über" = على / بـ (sich freuen über etwas Gegenwärtiges).\n✗ "mit" = مع (sich mit jdm. freuen = تفرح مع شخص)، موش على شي.\n✗ "wegen" = بسبب (+ Genitiv)، وما تتبعش "die" كـ Relativpronomen، و"sich freuen" ما ياخذش "wegen".`,
      rule: "sich freuen über + Akk. (Gegenwart / Vergangenheit)  |  sich freuen auf + Akk. (Zukunft)", ex: "Die Blumen, **über** die sie sich freut, sind von mir.", exTr: "الورود اللي تفرح بيهم من عندي." },
    22: { ok: "außerdem", type: "adjective_adverb", keyword: "außerdem (zusätzliches Argument)", bed: "وزيد (حجّة أخرى)",
      text: `"umweltfreundlicher und ___ noch billiger": تضيف حجّة ثانية ← "außerdem".\n✓ "außerdem" = وزيد / زيادة على ذلك (إضافة).\n✗ "sonst" = وإلا (بديل: "Beeil dich, sonst …")، موش إضافة.\n✗ "weiterhin" = مازال / من بعد (استمرار في الزمن)، وما تضيفش حجّة جديدة.`,
      rule: "außerdem = zusätzlich  |  sonst = andernfalls  |  weiterhin = auch künftig", ex: "Das Hotel ist billig, **außerdem** liegt es zentral.", exTr: "النزل ما هوش غالي، وزيد في وسط البلاد." },
    23: { ok: "fahren", type: "fixed_expression", keyword: "Zug fahren", bed: "نسافروا بالتران",
      text: `بدون أداة قدّام "Zug" التعبير الثابت هو "Zug fahren" (نسافروا بالتران).\n✓ "fahren" = Zug fahren (بدون Artikel).\n✗ "nehmen" = ياخذ: يحتاج أداة ("den Zug nehmen")، و"Zug nehmen" بدونها ما تتقالش.\n✗ "kommen" = يجي، وما تتركّبش مع "Zug" كوسيلة نقل.`,
      rule: "Zug / Bus / Auto fahren (ohne Artikel)  |  den Zug nehmen (mit Artikel)", ex: "Wir **fahren** lieber Zug als Auto.", exTr: "نحبّو نسافرو بالتران أكثر من الكرهبة." },
    24: { ok: "Da", type: "conjunction", keyword: "da + Nebensatz (Grund)", bed: "بما إنّو (عمرنا أقل من 26)",
      text: `الجملة تعطي سبب معروف والفعل "sind" في الآخر، والنتيجة (السعر) في الجملة الرئيسية: رابط سبب "Da".\n✓ "Da" = بما إنّو (سبب، + فعل في الآخر).\n✗ "darum" = لهذا السبب (ظرف نتيجة، ياخذ الفعل في المرتبة الثانية)، وهنا "sind" في الآخر.\n✗ "deshalb" = ظرف نتيجة زادا، والجملة هنا تعطي السبب (العمر) والنتيجة جاية بعدها، فنحتاج رابط سبب.`,
      rule: "da / weil + Nebensatz (Verb am Ende)  |  darum / deshalb + Hauptsatz (Verb Position 2)", ex: "**Da** es regnet, bleiben wir zu Hause.", exTr: "بما إنّو تشتي، نقعدو في الدار." },
    25: { ok: "davon", type: "pronoun_adverb", keyword: "abhängen von → davon", bed: "يتعلّق بهذا (بمدّة السفر)",
      text: `"abhängen" يتبعو "von"، والـ Pronominaladverb "davon" (= von + das) يعلن على الجملة اللي بعدو ("wie lange …").\n✓ "davon" = من هذا (von + das).\n✗ "deshalb" = لهذا السبب (ظرف نتيجة)، موش Pronominaladverb متاع "abhängen".\n✗ "damit" = بهذا (mit + das)، و"abhängen mit" ما يتقالش.`,
      rule: "abhängen von + Dat. → davon (+ wie- / ob-Satz)", ex: "Es hängt **davon** ab, ob es regnet.", exTr: "يتعلّق بهل تشتي." },
    26: { ok: "gesprochen", type: "verb", keyword: "mit jdm. sprechen", bed: "حكيت (مع خالتي)",
      text: `"ich habe mit meiner Tante ___": بدون مفعول به، الفعل المناسب "sprechen" (مع شخص).\n✓ "gesprochen" = Partizip II من "sprechen" (mit jdm. sprechen).\n✗ "besprochen" = ناقش (etwas besprechen)، ويحتاج مفعول به ("die Reise besprochen")، وهنا ما فماش.\n✗ "versprochen" = وعد (versprechen)، المعنى مختلف تمامًا.`,
      rule: "mit jdm. sprechen  |  etwas besprechen (+ Akk.)  |  etwas versprechen", ex: "Ich habe gestern mit ihm **gesprochen**.", exTr: "حكيت معاه البارح." },
    27: { ok: "dass", type: "conjunction", keyword: "vorschlagen, dass …", bed: "إنّو (نقعدو عندها)",
      text: `"vorgeschlagen, ___ wir …" = محتوى الاقتراح: "dass".\n✓ "dass" = إنّو (محتوى الاقتراح، والفعل في الآخر).\n✗ "als" = وقتما (ماضي) أو في المقارنة، موش محتوى اقتراح.\n✗ "wenn" = إذا (شرط)، تفتح شرط موش محتوى الاقتراح.`,
      rule: "vorschlagen / sagen / hoffen, dass + Nebensatz (Inhalt)", ex: "Er schlug vor, **dass** wir früher anfangen.", exTr: "اقترح إنّو نبداو بكري." },
    28: { ok: "sich", type: "pronoun", keyword: "sich freuen (3. Person)", bed: "يفرحو (إنتوما)",
      text: `الفاعل "die beiden" (الإخوة) غائب جمع، والفعل "freuen" انعكاسي: "würden sich freuen".\n✓ "sich" = ضمير انعكاسي للغائب (er / sie / sie).\n✗ "euch" = لـ "ihr" (إنتوما المخاطبين)، والفاعل هنا الاثنين الآخرين.\n✗ "uns" = لـ "wir"، وهم ما هموش "إحنا".`,
      rule: "Reflexivpronomen richtet sich nach dem Subjekt: er / sie / es / sie → sich", ex: "Die Kinder würden **sich** freuen.", exTr: "الصغار باش يفرحو." },
    29: { ok: "der", type: "preposition", keyword: "wegen + Genitiv Plural: der", bed: "بسبب (مهارات اللغة)",
      text: `"wegen" + Genitiv، و"Sprachkenntnisse" جمع: أداة Genitiv جمع = "der".\n✓ "der" = Genitiv جمع (wegen der Sprachkenntnisse).\n✗ "das" = محايد (Nominativ / Akkusativ)، و"Sprachkenntnisse" جمع.\n✗ "die" = Nominativ / Akkusativ جمع، و"wegen" تحتاج Genitiv.`,
      rule: "wegen + Genitiv (Plural: der)", ex: "**Wegen** der Ferien bleibt das Büro zu.", exTr: "بسبب العطلة المكتب مسكّر." },
    30: { ok: "jedenfalls", type: "adjective_adverb", keyword: "jedenfalls", bed: "على كل حال",
      text: `الكاتب يعبّر على فرحتو "على كل حال": "jedenfalls".\n✓ "jedenfalls" = على كل حال (مهما صار).\n✗ "bestenfalls" = في أحسن الأحوال (تحفّظ)، وما تتماشاش مع "نفرح برشا".\n✗ "keinesfalls" = أبدًا (نفي)، وتناقض "ich freue mich sehr".`,
      rule: "jedenfalls = auf jeden Fall  |  bestenfalls = im günstigsten Fall  |  keinesfalls = auf keinen Fall", ex: "Ich komme **jedenfalls** mit.", exTr: "على كل حال باش نجي معاكم." },
  },

  // ───────────── [37] Ida ─────────────
  37: {
    21: { ok: "auf", type: "verb_prep", keyword: "sich freuen auf + Akk.", bed: "نفرح بـ (الخدمة الجديدة)",
      text: `الحديث على حاجة جاية (الخدمة الجديدة قبل ما تبدا): "sich freuen auf".\n✓ "auf" = على (sich freuen auf + Akk. = فرح بحاجة قادمة).\n✗ "an" = "sich an etwas freuen" ممكنة (تستمتع بحاجة قدّامك: "an den Blumen")، بصح هنا الحاجة قادمة.\n✗ "wegen" = بسبب، و"sich wegen … freuen" ما يتقالش.`,
      rule: "sich freuen auf + Akk. (Zukunft)  |  sich freuen über + Akk. (Gegenwart / Vergangenheit)", ex: "Ich freue mich **auf** den Urlaub.", exTr: "فرحان بالعطلة القادمة." },
    22: { ok: "hätte", type: "tense", keyword: "hätte … fahren können (Irrealis)", bed: "كان نجّم (نسافر)",
      text: `"كان نجّم نسافر بالتران عوض نلوّج على دار" = شي كان ممكن وما صارش: Konjunktiv II ماضي "hätte … fahren können".\n✓ "hätte" = Konjunktiv II (حاجة كانت ممكنة وما صارتش).\n✗ "habe" = Perfekt واقعي (نقدر وفعلاً عملتها)، والسياق يلوم اختيار ما صارش.\n✗ "würde" = Konjunktiv II للحاضر / المستقبل (würde fahren können)، والجملة تحكي على قرار فات.`,
      rule: "Irreale Vergangenheit: hätte + Infinitiv + Modalverb-Infinitiv (hätte fahren können)", ex: "Ich **hätte** auch früher anfangen können.", exTr: "كان نجّم نبدا بكري زادا." },
    23: { ok: "mich", type: "pronoun", keyword: "sich wohlfühlen (ich → mich)", bed: "حسّيت راحة",
      text: `"sich wohlfühlen" فعل انعكاسي والفاعل "ich": "habe mich wohlgefühlt".\n✓ "mich" = انعكاسي لـ "ich".\n✗ "dich" = انعكاسي لـ "du"، والفاعل "ich".\n✗ "uns" = انعكاسي لـ "wir"، والفاعل "ich".`,
      rule: "Reflexivpronomen = Subjekt: ich → mich, du → dich, wir → uns", ex: "Ich habe **mich** dort sofort wohlgefühlt.", exTr: "حسّيت راحة هنالك على طول." },
    24: { ok: "ausgepackt hatte", type: "tense", keyword: "nachdem + Plusquamperfekt", bed: "بعد ما فرّغتهم",
      text: `الحدث الأول (فرّغت الكراتين) صار قبل "konnte" (ماضي): "nachdem" + Plusquamperfekt، والـ "hatte" في الآخر.\n✓ "ausgepackt hatte" = Plusquamperfekt (سابق لـ "konnte").\n✗ "ausgepackt habe" = Perfekt (حاضر)، وما يتماشاش مع "konnte" (ماضي).\n✗ "auspackte" = Präteritum: يتستعمل أحيانًا في الكلام، بصح "nachdem" تطلب زمن سابق (Plusquamperfekt).`,
      rule: "nachdem: Nebensatz vorzeitig (Plusquamperfekt), Hauptsatz Präteritum", ex: "**Nachdem** er gegessen hatte, ging er schlafen.", exTr: "بعد ما أكل، مشى يرقد." },
    25: { ok: "daran", type: "pronoun_adverb", keyword: "liegen an → daran, dass", bed: "السبب في هذا (إنّي لقيت صاحبة)",
      text: `"Das liegt …, dass" = السبب في إنّو: "liegen" يتبعو "an"، فـ "daran" (= an + das).\n✓ "daran" = في هذا (liegen an + Dativ).\n✗ "darauf" = على هذا (ankommen auf: "Es kommt darauf an")، موش "liegen".\n✗ "darin" = في هذا (bestehen in: "Das Problem besteht darin")، موش "liegen".`,
      rule: "liegen an + Dat. → daran, dass  |  ankommen auf → darauf  |  bestehen in → darin", ex: "Das liegt **daran**, dass es regnet.", exTr: "هذا خاطر تشتي." },
    26: { ok: "miteinander", type: "adjective_adverb", keyword: "miteinander ins Gespräch kommen", bed: "مع بعضنا",
      text: `الاثنين بدات المحادثة بيناتهم: "mit + einander" = "miteinander" (حوار مشترك).\n✓ "miteinander" = مع بعضنا (مشاركة).\n✗ "einander" = بعضنا (بدون حرف جر)، وهنا نحتاج "mit" (ins Gespräch kommen mit).\n✗ "gegeneinander" = ضدّ بعضنا (صراع)، عكس حوار ودّي.`,
      rule: "mit + einander = miteinander (gemeinsam)  |  gegeneinander = gegen den anderen", ex: "Die Nachbarn sprechen oft **miteinander**.", exTr: "الجيران يحكيو برشا مع بعضهم." },
    27: { ok: "als", type: "conjunction", keyword: "anders als", bed: "من (قبل 3 شهور)",
      text: `مقارنة بين حياتي توّا وقبل ثلاثة شهور: "ganz anders … als".\n✓ "als" = من / على (بعد "anders" في المقارنة).\n✗ "denn" = خاطر (سبب)، وفي المقارنة تجي غير في عبارات ثابتة قديمة ("mehr denn je").\n✗ "wenn" = إذا (شرط)، موش مقارنة.`,
      rule: "anders / mehr / weniger + als (Vergleich)  |  so … wie (Gleichheit)", ex: "Es ist ganz anders, **als** ich dachte.", exTr: "مختلف تمامًا على اللي كنت نتصوّر." },
    28: { ok: "obwohl", type: "conjunction", keyword: "obwohl + Nebensatz", bed: "رغم إنّو (لازمني نخدم أكثر)",
      text: `"راضي بالخدمة… رغم إنّو لازمني نخدم ساعات زيادة": تنازل، والفعل "muss" في الآخر.\n✓ "obwohl" = رغم إنّو (+ فعل في الآخر).\n✗ "trotzdem" = رغم ذلك (ظرف، الفعل في المرتبة الثانية: "trotzdem muss ich")، وهنا "muss" في الآخر.\n✗ "während" = أثناء / بينما (زمن أو تقابل)، موش تنازل.`,
      rule: "obwohl + Nebensatz (Verb am Ende)  |  trotzdem + Hauptsatz (Verb Position 2)", ex: "Ich gehe raus, **obwohl** es regnet.", exTr: "نخرج رغم إنّو تشتي." },
    29: { ok: "bei", type: "preposition", keyword: "bei uns (im Kreis von)", bed: "عندنا (في القسم)",
      text: `نوصف جوّ العمل داخل مجموعتنا: "bei uns in der Abteilung" (عندنا).\n✓ "bei" = عندنا / وسط (bei + Dativ).\n✗ "mit" = مع (نشاط مشترك)، وما تصفش جوّ عام.\n✗ "zu" = إلى (اتجاه أو غرض)، موش مكان / مجموعة.`,
      rule: "bei + Dativ = im Umfeld / im Haus von (bei uns, bei der Arbeit)", ex: "**Bei** uns in der Firma gibt es ein Team-Essen.", exTr: "عندنا في الشركة فما غدا جماعي." },
    30: { ok: "eigentlich", type: "adjective_adverb", keyword: "eigentlich in Fragen", bed: "في الحقيقة (كيفاش حالك)",
      text: `نسأل عن الحال بطريقة ناعمة: "wie es dir eigentlich geht".\n✓ "eigentlich" = في الحقيقة (تلطيف السؤال).\n✗ "hoffentlich" = إن شاء الله (أمنية)، وما تتماشاش داخل سؤال.\n✗ "sicherlich" = أكيد (توقّع)، موش سؤال.`,
      rule: "eigentlich in Fragen = übrigens / nebenbei (Abtönung)", ex: "Wie geht es dir **eigentlich**?", exTr: "وكيفاش حالك في الحقيقة؟" },
  },

  // ───────────── [38] Corinna (Original) ─────────────
  38: {
    21: { ok: "dass", type: "conjunction", keyword: "Es tut mir leid, dass …", bed: "إنّي (ما كتبتلكش)",
      text: `"Es tut mir Leid" + محتوى الأسف: "dass ich … nicht geschrieben habe".\n✓ "dass" = إنّو (محتوى الأسف، والفعل في الآخر).\n✗ "ob" = إذا بمعنى whether (سؤال)، وما فماش سؤال.\n✗ "weil" = خاطر: ممكنة نحويًّا، بصح "leid tun" يطلب محتوى (dass-Satz) موش سبب.`,
      rule: "Es tut mir leid, dass + Nebensatz (Inhalt des Bedauerns)", ex: "Es tut mir leid, **dass** ich zu spät komme.", exTr: "آسف إنّي جيت متأخّر." },
    22: { ok: "beschäftigen", type: "verb_prep", keyword: "sich beschäftigen mit + Dat.", bed: "نشغّل روحي (بحاجة أخرى)",
      text: `"mich mit etwas … zu ___": فعل انعكاسي يتبعو "mit": "sich beschäftigen mit".\n✓ "beschäftigen" = يشتغل / يشغّل روحو (sich beschäftigen mit).\n✗ "bedienen" = يخدم زبون أو يشغّل جهاز، وما فيهاش "sich … mit".\n✗ "beeilen" = يستعجل (sich beeilen)، وما يتركّبش مع "mit etwas".`,
      rule: "sich beschäftigen mit + Dat.  |  sich beeilen (ohne Präposition)", ex: "Ich möchte mich mehr mit Sprachen **beschäftigen**.", exTr: "نحب نشتغل أكثر على اللغات." },
    23: { ok: "doch", type: "adjective_adverb", keyword: "doch (Abtönungspartikel)", bed: "(كيما تعرف) برشا",
      text: `"Gärtner? Die gibt es doch wie Sand am Meer": "doch" يذكّر بحاجة معروفة عند الكل.\n✓ "doch" = أكيد / كيما تعرف (Abtönungspartikel، بدون تشديد).\n✗ "bloß" = غير / فقط (تحديد)، وتتعارض مع "wie Sand am Meer" (برشا).\n✗ "nur" = فقط، تحدّ من العدد، والتعبير يعني الكثرة.`,
      rule: "doch (unbetont) = Verweis auf Bekanntes  |  nur / bloß = Einschränkung", ex: "Das weißt du **doch**.", exTr: "إنت تعرف هذا (أكيد)." },
    24: { ok: "insbesondere", type: "adjective_adverb", keyword: "insbesondere (besonders)", bed: "خاصةً (للفلاحين)",
      text: `يبيعو أشجار الفواكه للجميع، و"خاصةً" لفلاحي المنطقة: "insbesondere, an die Obstbauern".\n✓ "insbesondere" = خاصةً (يبرز الجزء الأهم).\n✗ "außerdem" = وزيد (يضيف حاجة جديدة)، وهنا نخصّصو جزء من نفس الزبائن.\n✗ "jedoch" = لكن (تعارض)، وما فماش تعارض.`,
      rule: "insbesondere = besonders / vor allem (hebt einen Teil hervor)", ex: "Er liebt Sport, **insbesondere** Fußball.", exTr: "يحب الرياضة، خاصةً الكورة." },
    25: { ok: "überwiegend", type: "adjective_adverb", keyword: "überwiegend = hauptsächlich", bed: "في الغالب (برّا)",
      text: `يخدم جسديًّا، "في الغالب" في الهواء الطلق: "überwiegend".\n✓ "überwiegend" = في الغالب / أغلبه.\n✗ "übermächtig" = قوي برشا (صفة: ein übermächtiger Gegner)، موش ظرف.\n✗ "übermäßig" = بإفراط (zu viel)، وتعبّر على مبالغة موش على الأغلبية.`,
      rule: "überwiegend = meistens / hauptsächlich  |  übermäßig = zu viel  |  übermächtig = zu stark", ex: "Das Wetter war **überwiegend** sonnig.", exTr: "الطقس كان في الغالب مشمس." },
    26: { ok: "muss", type: "verb", keyword: "muss (Zwang durch Umstände)", bed: "لازمني",
      text: `"leider … fast eine dreiviertel Stunde mit dem Zug fahren": إلزام مزعج بسبب المسافة.\n✓ "muss" = لازمني (إلزام من الظروف).\n✗ "darf" = مسموحلي (إذن)، و"leider" تعبّر على حاجة مزعجة موش امتياز.\n✗ "soll" = مطلوب منّي (أمر من شخص آخر)، وهنا الإلزام من المسافة.`,
      rule: "müssen = Notwendigkeit  |  dürfen = Erlaubnis  |  sollen = fremder Auftrag", ex: "Leider **muss** ich heute länger arbeiten.", exTr: "للأسف لازمني نخدم اليوم أكثر." },
    27: { ok: "wenig", type: "adjective_adverb", keyword: "wenig + Lust (ohne Endung)", bed: "قليل (نفس)",
      text: `"Lust" اسم غير معدود، والكمية بـ "wenig" بدون نهاية.\n✓ "wenig" = قليل (+ اسم غير معدود: wenig Lust).\n✗ "gering" = صغير / ضعيف، وهي صفة تحتاج نهاية ("geringe Lust")، وبدون نهاية ما تتركّبش.\n✗ "knapp" = ضيّق / بالكاد (knappes Geld)، وبدون نهاية ما تتركّبش.`,
      rule: "wenig + unzählbares Nomen (wenig Zeit, wenig Lust)  |  Adjektive brauchen eine Endung", ex: "Ich habe **wenig** Zeit.", exTr: "عندي وقت قليل." },
    28: { ok: "kommt", type: "verb", keyword: "kommt wieder", bed: "تجي (ترجع)",
      text: `"أكيد النفس باش ترجع": الفعل المعتاد مع "Lust" / "Appetit" هو "kommen".\n✓ "kommt" = تجي (ترجع).\n✗ "läuft" = تجري / تمشي (Maschine läuft)، و"Lust läuft wieder" ما تتقالش.\n✗ "steht" = واقفة، وما تعطيش معنى الرجوع.`,
      rule: "Lust / Hunger / Mut kommt (wieder)", ex: "Der Appetit **kommt** beim Essen.", exTr: "الشهيّة تجي مع الأكل." },
    29: { ok: "lässt", type: "fixed_expression", keyword: "sich Zeit lassen", bed: "تاخذ وقتك",
      text: `تعبير ثابت: "sich (Dativ) Zeit lassen" = ياخذ وقتو، و"dir" هو الضمير الانعكاسي.\n✓ "lässt" = lassen (du lässt dir Zeit).\n✗ "brauchst" = تحتاج: "brauchst du noch Zeit?" صحيحة بدون "dir"، ومع "dir" ما تتركّبش.\n✗ "hast" = عندك، و"hast du dir Zeit" ما تتقالش.`,
      rule: "sich (Dat.) Zeit lassen = nicht eilen", ex: "Er **lässt** sich beim Essen viel Zeit.", exTr: "ياخذ وقتو برشا في الماكلة." },
    30: { ok: "möglich", type: "fixed_expression", keyword: "so früh wie möglich", bed: "قدر الإمكان",
      text: `"so früh wie möglich" = أبكر ما يمكن (نصيحة).\n✓ "möglich" = ممكن (so … wie möglich).\n✗ "kürzlich" = مؤخرًا (ماضي)، وما تتماشاش مع نصيحة للمستقبل.\n✗ "üblich" = معتاد، و"so früh wie üblich" = كيما العادة، موش أقصى ما يمكن.`,
      rule: "so + Adjektiv + wie möglich = im höchsten Maß", ex: "Antworte bitte so schnell wie **möglich**.", exTr: "جاوب بالله أسرع ما يمكن." },
  },

  // ───────────── [39] Corinna (معدل) — 21–23, 27–30 come from [38] via the store ─────────────
  39: {
    24: { ok: "insbesondere", type: "adjective_adverb", keyword: "insbesondere (besonders)", bed: "خاصةً (للفلاحين)",
      text: `الفراغ يجي قبل الفاصلة ويعلن على جزء مخصوص من الزبائن: "insbesondere, an die Obstbauern".\n✓ "insbesondere" = خاصةً (يخصّص الأهم من اللي ذكرناهم).\n✗ "außerdem" = وزيد (حاجة جديدة)، وهنا ما نضيفوش زبائن آخرين، نخصّصو في نفس الزبائن.\n✗ "jedoch" = لكن (تعارض)، وما فماش تعارض بين الجملتين.`,
      rule: "insbesondere = besonders (hebt einen Teil des Genannten hervor)", ex: "Wir liefern in viele Länder, **insbesondere** nach Italien.", exTr: "نبعثو لبلدان برشا، خاصةً لإيطاليا." },
    25: { reuse: "38#25" },
    26: { ok: "fast", type: "adjective_adverb", keyword: "fast + Zahl", bed: "تقريبًا (¾ ساعة)",
      text: `"fast eine dreiviertel Stunde" = تقريبًا ¾ ساعة: ظرف تقريب مع مدّة.\n✓ "fast" = تقريبًا (+ رقم أو كمية).\n✗ "nahe" = قريب (مكان أو علاقة: "nahe am Bahnhof")، موش تقريب كمية.\n✗ "ziemlich" = برشا (درجة مع صفة)، وما تتركّبش مع رقم ("ziemlich eine Stunde" ما تتقالش).`,
      rule: "fast + Zahl / Mengenangabe = beinahe  |  ziemlich + Adjektiv", ex: "Ich warte schon **fast** eine Stunde.", exTr: "نستنّى من تقريبًا ساعة." },
  },
};
