// SB Teil 1 restyle — batch 09: [40] Paola, [41] David (Original), [42] David (معدل), [43] Lara, [44] Lina und Florian
export default {
  // ───────────── [40] Paola ─────────────
  40: {
    21: { ok: "sie", type: "pronoun", keyword: "kennenlernen + Akk. → sie", bed: "نتعرّف عليها (لورا)",
      text: `الفراغ يرجع على "Laura" (بنت صغيرة، غائبة)، و"kennenlernen" ياخذ مفعول به (Akkusativ): "sie".\n✓ "sie" = Akkusativ لـ "Laura" (she / her).\n✗ "ihr" = Dativ (لها) أو "إنتوما"، و"kennenlernen" ما ياخذش Dativ.\n✗ "Sie" = ضمير المخاطب الرسمي (بحرف كبير)، وهنا نحكيو على لورا موش على الشخص المخاطَب.`,
      rule: "jdn. kennenlernen + Akkusativ (sie = Akk. von sie)", ex: "Ich möchte **sie** bald kennenlernen.", exTr: "نحب نتعرّف عليها قريب." },
    22: { ok: "Deshalb", type: "adjective_adverb", keyword: "deshalb (Folge)", bed: "لهذا السبب",
      text: `الجملة اللي قبل تعطي السبب (الأيام الأولى مع الرضيع صعيبة) وهذي النتيجة (نستنّاو): ظرف نتيجة.\n✓ "Deshalb" = لهذا السبب (نتيجة، والفعل بعدو في المرتبة الثانية).\n✗ "obwohl" = رغم إنّو (تنازل، والفعل يمشي للآخر)، وما فماش تنازل هنا.\n✗ "trotzdem" = رغم ذلك (تعارض)، والمنطق هنا سبب ← نتيجة موش تعارض.`,
      rule: "deshalb (Hauptsatz, Position 2) = Folge  |  trotzdem = Gegensatz  |  obwohl + Nebensatz", ex: "Er ist krank, **deshalb** kommt er nicht.", exTr: "مريض، لهذا ما جاش." },
    23: { ok: "wann", type: "conjunction", keyword: "wann = indirekte Frage", bed: "إمتى",
      text: `"قولولنا إمتى يناسبكم لقاء": سؤال غير مباشر عن الوقت، والفعل "wäre" في الآخر.\n✓ "wann" = إمتى (Fragewort، + فعل في الآخر).\n✗ "bis" = لين / حتى (حدّ زمني: "bis Freitag")، وما تفتحش سؤال "إمتى".\n✗ "dann" = وقتها (ظرف)، وما تفتحش جملة فرعية، والفعل بعدها في المرتبة الثانية.`,
      rule: "indirekte Frage: Fragewort + Nebensatz (Verb am Ende)", ex: "Sag mir, **wann** du Zeit hast.", exTr: "قولي إمتى عندك وقت." },
    24: { ok: "auf", type: "fixed_expression", keyword: "auf jeden Fall", bed: "أكيد (في كل الأحوال)",
      text: `تعبير ثابت بالـ Akkusativ: "auf jeden Fall" (أكيد).\n✓ "auf" = auf jeden Fall.\n✗ "im" = in + dem (أداة مدمجة)، و"im jeden Fall" ما تتقالش.\n✗ "in" = التعبير "in jedem Fall" (Dativ) صحيح بنفس المعنى، بصح هنا "jeden" في Akkusativ، و"in jeden Fall" ما تتقالش.`,
      rule: "auf jeden Fall (Akk.) = in jedem Fall (Dat.)", ex: "Ich komme **auf** jeden Fall.", exTr: "أكيد باش نجي." },
    25: { ok: "Seit", type: "preposition", keyword: "seit + Dativ (Zeitraum)", bed: "من (هالعام)",
      text: `الوضع بدا هالعام وتواصل لين توّا: "seit diesem Jahr".\n✓ "Seit" = من (seit + Dativ، بداية في الماضي ومازال).\n✗ "vom" = von + dem (مدمجة)، و"vom diesem Jahr" فيها أداة مرتين.\n✗ "Zum" = zu + dem (مدمجة)، نفس المشكل، وما تعطيش معنى "من".`,
      rule: "seit + Dat. (Beginn in der Vergangenheit bis jetzt)  |  vom / zum enthalten schon den Artikel", ex: "**Seit** diesem Monat arbeite ich hier.", exTr: "من هالشهر نخدم هنا." },
    26: { ok: "ob", type: "conjunction", keyword: "überlegen, ob …", bed: "هل (نرجع نخدم)",
      text: `"نفكّر هل نرجع نخدم": سؤال غير مباشر بجواب نعم / لا.\n✓ "ob" = هل (whether، + فعل في الآخر).\n✗ "obwohl" = رغم إنّو (تنازل)، موش سؤال.\n✗ "ohnehin" = على أي حال (ظرف)، موش رابط جمل.`,
      rule: "ob = indirekte Ja/Nein-Frage (überlegen, fragen, wissen)", ex: "Ich überlege, **ob** ich umziehen soll.", exTr: "نفكّر هل نبدّل السكنى." },
    27: { ok: "vorstellen", type: "verb", keyword: "sich (Dat.) etwas vorstellen", bed: "نتصوّر",
      text: `"ما نجّمش نتصوّر كيفاش…": الفعل "sich vorstellen" (تصوّر).\n✓ "vorstellen" = يتصوّر (mir vorstellen).\n✗ "verstellen" = يغيّر مكان / يحجب (den Weg verstellen)، موش تصوّر.\n✗ "zustellen" = يوصّل (Post zustellen) أو يسدّ، موش تصوّر.`,
      rule: "sich (Dat.) etwas vorstellen = in Gedanken sehen  |  verstellen / zustellen: andere Bedeutung", ex: "Ich kann mir das nicht **vorstellen**.", exTr: "ما نجّمش نتصوّر هذا." },
    28: { ok: "davon", type: "pronoun_adverb", keyword: "halten von → davon", bed: "من هذا (رأيك)",
      text: `سؤال على الرأي: "Was hältst du davon?" (halten + von).\n✓ "davon" = من هذا (von + das، سؤال الرأي).\n✗ "dafür" = لهذا: "halten für" معناها تعتبر ("etwas für gut halten")، موش سؤال الرأي.\n✗ "damit" = بهذا (mit + das)، و"halten mit" ما يتركّبش.`,
      rule: "Was hältst du davon? = Frage nach der Meinung  |  halten für = betrachten als", ex: "Was hältst du **davon**, wenn wir früher fahren?", exTr: "شنوّة رأيك إذا نمشيو بكري؟" },
    29: { ok: "als", type: "preposition", keyword: "Ausbildung als + Beruf", bed: "كـ (ممرّضة)",
      text: `المهنة تتذكر بـ "als": "Ausbildung als Krankenschwester".\n✓ "als" = كـ (Ausbildung als + Beruf).\n✗ "wie" = كيما (مقارنة)، وما تعطيش المهنة.\n✗ "zu" = التعبير الصحيح "Ausbildung zur Krankenschwester" (zu + der)، و"zu Krankenschwester" بدون أداة ما تتقالش.`,
      rule: "Ausbildung als + Beruf  |  Ausbildung zur / zum + Beruf", ex: "Seine Ausbildung **als** Koch hat ihm geholfen.", exTr: "تكوينو كطبّاخ ساعدو." },
    30: { ok: "sei", type: "fixed_expression", keyword: "Wie dem auch sei", bed: "كيما كان الحال",
      text: `تعبير ثابت بصيغة Konjunktiv I: "Wie dem auch sei" = على كل حال.\n✓ "sei" = Konjunktiv I من "sein" (feste Wendung).\n✗ "hätte" = Konjunktiv II من "haben"، والتعبير الثابت ما يقبلهاش.\n✗ "wäre" = Konjunktiv II من "sein"، و"Wie dem auch wäre" ما تتقالش.`,
      rule: "Wie dem auch sei = auf jeden Fall (Konjunktiv I, feste Wendung)", ex: "Wie dem auch **sei**, wir müssen weitermachen.", exTr: "كيما كان الحال، لازمنا نكمّلو." },
  },

  // ───────────── [41] David (Original) ─────────────
  41: {
    21: { ok: "noch", type: "adjective_adverb", keyword: "noch + Komparativ", bed: "أكثر (أحلى)",
      text: `"schöner" صيغة مقارنة، وللتقوية قبلها نستعملو "noch": "noch schöner" (أحلى كذلك).\n✓ "noch" = أكثر (noch + Komparativ).\n✗ "ganz" = تمامًا (يجي مع الصفة العادية: "ganz schön")، موش مع صيغة المقارنة.\n✗ "zwar" = صحيح (zwar … aber)، رابط تنازل، وما يعطيش درجة.`,
      rule: "noch + Komparativ = Steigerung  |  ganz + Positiv  |  zwar … aber", ex: "Heute ist es **noch** kälter als gestern.", exTr: "اليوم أبرد من البارح." },
    22: { ok: "obwohl", type: "conjunction", keyword: "obwohl + Nebensatz", bed: "رغم إنّو (عندك شغل في ميونيخ)",
      text: `"تحب تزورنا رغم إنّو خدمتك في ميونيخ وإحنا في كولن": تنازل، والأفعال "hast … wohnen" في الآخر.\n✓ "obwohl" = رغم إنّو (+ فعل في الآخر).\n✗ "jedoch" = لكن (تعارض)، ظرف ياخذ الفعل في المرتبة الثانية، وهنا الفعل في الآخر.\n✗ "trotzdem" = رغم ذلك (تنازل)، بصح هو ظرف وموش رابط جملة فرعية.`,
      rule: "obwohl + Nebensatz (Verb am Ende)  |  trotzdem / jedoch + Hauptsatz (Verb Position 2)", ex: "Er kommt, **obwohl** er krank ist.", exTr: "يجي رغم إنّو مريض." },
    23: { ok: "anschauen", type: "verb", keyword: "sich (Dat.) etwas anschauen", bed: "تتفرّج على",
      text: `"Du kannst Dir den Kölner Dom ___": تزور وتتفرّج على المعلم: "anschauen" (Infinitiv بعد "kannst").\n✓ "anschauen" = تتفرّج (sich etwas anschauen).\n✗ "überschauen" = يحيط بنظره / يقيّم الوضع ("die Lage überschauen")، موش زيارة معلم.\n✗ "vorschauen" = فعل ما موجودش في الاستعمال العادي (الصحيح "vorausschauen" = يتوقّع).`,
      rule: "sich (Dat.) etwas anschauen = besichtigen / ansehen", ex: "Du kannst dir den Film **anschauen**.", exTr: "تنجّم تتفرّج على الفيلم." },
    24: { ok: "sollten", type: "tense", keyword: "sollten (Konjunktiv II: Plan)", bed: "لازم (يكون عندنا وقت)",
      text: `"وطبعًا لازم يكون عندنا وقت للحكي": Konjunktiv II من "sollen" (نيّة أو توصية).\n✓ "sollten" = لازم / ينبغي (Konjunktiv II).\n✗ "konnten" = كنّا ننجّمو (Präteritum)، والسياق مستقبل.\n✗ "wollten" = كنّا نحبّو (Präteritum)، والمقصود خطّة للمستقبل موش ماضي.`,
      rule: "sollten = Konjunktiv II (Empfehlung / Plan)  |  konnten / wollten = Präteritum (Vergangenheit)", ex: "Wir **sollten** früh anfangen.", exTr: "لازمنا نبداو بكري." },
    25: { ok: "ankommen wirst", type: "grammar_structure", keyword: "Nebensatz: Infinitiv + wirst", bed: "باش توصل",
      text: `"an welchem Tag … Du … ___" سؤال غير مباشر (Nebensatz): الفعل المصرّف "wirst" يمشي للآخر بعد الـ Infinitiv "ankommen".\n✓ "ankommen wirst" = Infinitiv + werden في الآخر (Futur I).\n✗ "anzukommen wirst" = "zu" ما تتركّبش مع "werden".\n✗ "wirst ankommen" = ترتيب الجملة الرئيسية، والـ Nebensatz يحط المصرّف في الآخر.`,
      rule: "Nebensatz + Futur I: Infinitiv … werden (am Ende)", ex: "Ich weiß nicht, wann er **ankommen wird**.", exTr: "ما نعرفش إمتى باش يوصل." },
    26: { ok: "falls", type: "conjunction", keyword: "falls + Nebensatz", bed: "في صورة (تأخّرنا)",
      text: `"في صورة تأخّرنا": رابط شرط يفتح Nebensatz مباشرة.\n✓ "falls" = في صورة / إذا (+ فعل في الآخر).\n✗ "für den Fall" = تحتاج "dass" بعدها ("für den Fall, dass …")، وهنا ما فماش.\n✗ "im Fall" = تحتاج "dass" أو Genitiv ("im Fall, dass" / "im Falle eines …")، وبدونها ما تتركّبش.`,
      rule: "falls = für den Fall, dass  |  für den Fall / im Fall + dass", ex: "**Falls** es regnet, bleiben wir drinnen.", exTr: "في صورة تشتي، نقعدو لداخل." },
    27: { ok: "seitdem", type: "adjective_adverb", keyword: "seitdem (ab diesem Zeitpunkt)", bed: "من وقتها",
      text: `الابن خرج من الدار من سنين، و"من وقتها" الغرفة تتستعمل لما يزورنا ولغيرو: "seitdem".\n✓ "seitdem" = من وقتها (بداية في الماضي ومازال).\n✗ "neulich" = من مدة قصيرة (مرة في الماضي القريب)، وما تعبّرش على استمرار.\n✗ "vormals" = قبل (سابقًا)، تحكي على ماضي انتهى، والفعل "benutzen" حاضر.`,
      rule: "seitdem = von da an bis jetzt  |  neulich = vor kurzer Zeit  |  vormals = früher", ex: "Er ist umgezogen, **seitdem** sehen wir ihn selten.", exTr: "بدّل السكنى، من وقتها قليل ما نشوفوه." },
    28: { ok: "auffrischen", type: "verb", keyword: "Erinnerungen auffrischen", bed: "ننعشو (الذكريات)",
      text: `"ننعشو الذكريات القديمة": الفعل المناسب "auffrischen".\n✓ "auffrischen" = ينعش / يجدّد (Erinnerungen, Wissen).\n✗ "aufholen" = يلحق / يعوّض (einen Rückstand aufholen)، ما يتركّبش مع ذكريات.\n✗ "aufsparen" = يوفّر ويحتفظ (Geld aufsparen)، معنى مختلف.`,
      rule: "etwas auffrischen = erneuern  |  Rückstand aufholen  |  Geld aufsparen", ex: "Ich will mein Deutsch **auffrischen**.", exTr: "نحب ننعش ألمانيتي." },
    29: { ok: "als", type: "conjunction", keyword: "als (einmalige Vergangenheit)", bed: "وقتما (كنّا عندك)",
      text: `زيارتهم لعنده حدث وقع مرة في الماضي: "als wir bei Dir zu Besuch waren".\n✓ "als" = وقتما (حدث ماضي مرة وحدة).\n✗ "wann" = إمتى (سؤال)، موش رابط زمني.\n✗ "wo" = وين (مكان)، والجملة تحدّد زمن.`,
      rule: "als = einmaliges Ereignis in der Vergangenheit  |  wann = Fragewort  |  wo = Ort", ex: "Wir haben viele Fotos gemacht, **als** wir in Rom waren.", exTr: "صوّرنا برشا صور وقتما كنّا في روما." },
    30: { ok: "lass", type: "fixed_expression", keyword: "lass dich überraschen", bed: "خلّي روحك تتفاجأ",
      text: `تعبير ثابت: "aber lass Dich überraschen" = اصبر وشوف (Imperativ من "lassen").\n✓ "lass" = Imperativ من "lassen" (lass dich überraschen).\n✗ "geh" = امشي، وما يتركّبش مع "dich überraschen".\n✗ "komm" = تعالى، وما يعطيش معنى "خلّي روحك".`,
      rule: "sich überraschen lassen → Imperativ: lass dich überraschen", ex: "Frag nicht, **lass** dich einfach überraschen.", exTr: "ما تسألش، خلّي روحك تتفاجأ." },
  },

  // ───────────── [42] David (معدل) — 21–28 from [41] via the store ─────────────
  42: {
    29: { reuse: "41#29" },
    30: { ok: "kaum", type: "fixed_expression", keyword: "kaum zu glauben", bed: "صعيب نصدّق",
      text: `تعبير ثابت: "Kaum zu glauben, dass …" = صعيب نصدّق إنّو.\n✓ "kaum" = بالكاد (kaum zu + Infinitiv).\n✗ "fast" = تقريبًا، و"fast zu glauben" ما تتقالش.\n✗ "wohl" = ربّما (توقّع)، وما تركّبش "wohl zu glauben" بهذا المعنى.`,
      rule: "kaum + zu + Infinitiv = fast unmöglich (kaum zu glauben, kaum zu sehen)", ex: "**Kaum** zu glauben, wie schnell die Zeit vergeht.", exTr: "صعيب نصدّق كيفاش الوقت يمشي بالسرعة." },
  },

  // ───────────── [43] Lara ─────────────
  43: {
    21: { ok: "deinen", type: "grammar_structure", keyword: "antworten auf + Akk.", bed: "على رسالتك",
      text: `"antworten" يتبعو "auf" + Akkusativ، و"Brief" مذكّر: "auf deinen Brief".\n✓ "deinen" = Akkusativ مذكّر (-en).\n✗ "dein" = Nominativ / Akkusativ محايد (dein Buch)، و"Brief" مذكّر في Akkusativ.\n✗ "deine" = مؤنّث أو جمع (deine Karte)، و"Brief" مذكّر.`,
      rule: "antworten auf + Akk.  |  Possessivartikel maskulin Akk. = -en (deinen)", ex: "Ich antworte auf **deinen** Anruf.", exTr: "نجاوب على مكالمتك." },
    22: { ok: "weil", type: "conjunction", keyword: "weil + Nebensatz", bed: "خاطر",
      text: `"توّا نكتب خاطر عندك أخبار": سبب في جملة فرعية، والفعل "hast" في الآخر.\n✓ "weil" = خاطر (+ فعل في الآخر).\n✗ "denn" = خاطر، لكن تدخل جملة رئيسية (الفعل في المرتبة الثانية: "denn du hast")، وهنا "hast" في الآخر.\n✗ "obwohl" = رغم إنّو (تنازل)، والمنطق هنا سبب موش تنازل.`,
      rule: "weil + Nebensatz (Verb am Ende)  |  denn + Hauptsatz  |  obwohl = Gegensatz", ex: "Ich bleibe, **weil** ich müde bin.", exTr: "نقعد خاطر تعبان." },
    23: { ok: "noch", type: "adjective_adverb", keyword: "noch gut wissen", bed: "نتفكّر (مليح)",
      text: `"Ich weiß noch gut" = نتفكّر مليح: "noch" مع "wissen" بمعنى التذكّر.\n✓ "noch" = (noch gut wissen = نتفكّر).\n✗ "schon" = تعبّر على "قبل الوقت" وما تعطيش معنى التذكّر.\n✗ "weiterhin" = مازال في المستقبل (استمرار)، وما تتركّبش مع "wissen … gut".`,
      rule: "noch (gut / genau) wissen = sich erinnern", ex: "Ich weiß **noch** genau, wie es war.", exTr: "نتفكّر بالضبط كيفاش كان." },
    24: { ok: "Für", type: "preposition", keyword: "für + Akk. (Anlass)", bed: "لأجل (بداية جديدة)",
      text: `"deinen Neubeginn" في Akkusativ، والتمنّي لمناسبة بـ "für": "Für deinen Neubeginn wünschen …".\n✓ "Für" = لأجل (für + Akk.).\n✗ "Vor" = قدّام / قبل، و"Vor deinen Neubeginn" ما تعطيش معنى.\n✗ "Zu" = تتبعها Dativ فقط ("zu deinem Neubeginn")، وهنا "deinen" Akkusativ ما تتماشاش.`,
      rule: "wünschen für + Akk. (Anlass)  |  zu + Dativ (zum Geburtstag)", ex: "**Für** die Prüfung wünsche ich dir viel Glück.", exTr: "للامتحان نتمنّالك برشا حظ." },
    25: { ok: "neuen", type: "grammar_structure", keyword: "seiner neuen Stelle (-en)", bed: "الجديدة (الخدمة)",
      text: `"auf seiner ___ Stelle": Dativ مؤنّث بعد "seiner" ← الصفة تاخذ -en.\n✓ "neuen" = -en (Dativ مؤنّث بعد Possessiv).\n✗ "neue" = Nominativ / Akkusativ مؤنّث، وهنا Dativ.\n✗ "neuer" = نهاية Nominativ مذكّر أو بدون أداة، وبعد "seiner" ما تجيش.`,
      rule: "Possessiv + Dativ Fem. → Adjektiv + -en (seiner neuen Stelle)", ex: "Er arbeitet gern in seiner **neuen** Firma.", exTr: "يخدم بكل نفس في شركتو الجديدة." },
    26: { ok: "ja", type: "adjective_adverb", keyword: "ja (Abtönungspartikel)", bed: "كيما تعرف",
      text: `"Du weißt ja, was das heißt": "ja" تذكّر بحاجة معروفة عند الاثنين.\n✓ "ja" = كيما تعرف (Abtönungspartikel، بدون تشديد).\n✗ "bloß" = غير / فقط (تحديد)، موش تذكير.\n✗ "mal" = مرة (تلطيف الأوامر: "Schau mal")، وما تتركّبش مع "weißt … was das heißt".`,
      rule: "ja (unbetont) = Hinweis auf Bekanntes", ex: "Du kennst ihn **ja**.", exTr: "إنت تعرفو، كيما تعرف." },
    27: { ok: "Darauf", type: "pronoun_adverb", keyword: "stolz sein auf → darauf", bed: "بهذا (نفتخرو)",
      text: `"stolz sein" يتبعو "auf"، و"Darauf" (= auf + das) يرجع لنتايج Sandra الجيّدة.\n✓ "Darauf" = بهذا (auf + das).\n✗ "Damit" = بهذا (mit + das)، و"stolz mit" ما يتقالش.\n✗ "Darüber" = على هذا (über + das)، و"stolz über" ما يتقالش (الصحيح "stolz auf").`,
      rule: "stolz sein auf + Akk. → darauf", ex: "**Darauf** bin ich wirklich stolz.", exTr: "بهذا فعلاً نفتخر." },
    28: { ok: "wäre", type: "tense", keyword: "wäre schön, wenn …", bed: "يكون (حلو)",
      text: `أمنية مؤدّبة بـ "wenn … würden": Konjunktiv II من "sein": "Es wäre schön".\n✓ "wäre" = Konjunktiv II (أمنية افتراضية).\n✗ "ist" = Indikativ (حقيقة)، والجملة هنا افتراضية.\n✗ "würde" = تحتاج Infinitiv بعدها ("würde schön sein")، و"es würde schön" بدونو ما تتقالش.`,
      rule: "Es wäre schön / toll / gut, wenn … (Konjunktiv II)", ex: "Es **wäre** schön, wenn du kommen könntest.", exTr: "يكون زين كان تنجّم تجي." },
    29: { ok: "trotz", type: "preposition", keyword: "trotz + Genitiv", bed: "رغم (التحضيرات)",
      text: `"رغم تحضيرات الانتقال تلقاو وقت": تنازل بـ Genitiv: "trotz der Umzugsvorbereitungen".\n✓ "trotz" = رغم (+ Genitiv).\n✗ "aufgrund" = بسبب (+ Genitiv)، والمعنى معكوس: التحضيرات تاخذ وقت موش تعطيه.\n✗ "wegen" = بسبب (+ Genitiv)، نفس المشكل.`,
      rule: "trotz + Genitiv (Gegensatz)  |  wegen / aufgrund + Genitiv (Grund)", ex: "**Trotz** des Regens gehen wir spazieren.", exTr: "رغم المطر نمشيو نتمشّاو." },
    30: { ok: "können", type: "tense", keyword: "damit + Modalverb (Präsens)", bed: "نجّمو (نتفقو)",
      text: `"damit wir etwas abmachen ___": الفعل المساعد يمشي للآخر بعد "abmachen"، في الحاضر.\n✓ "können" = Präsens (damit wir … abmachen können).\n✗ "könnten" = Konjunktiv II: ممكنة (أكثر تحفّظ)، بصح الطلب هنا مباشر في الحاضر.\n✗ "konnten" = Präteritum (ماضي)، والسياق قبل السفر (مستقبل).`,
      rule: "damit + Nebensatz mit Modalverb am Ende (Präsens: können)", ex: "Ruf an, damit wir uns treffen **können**.", exTr: "عيّط باش نتلاقاو." },
  },

  // ───────────── [44] Lina und Florian ─────────────
  44: {
    21: { ok: "sollt", type: "verb", keyword: "sollt doch endlich (Aufforderung)", bed: "لازمكم (ديما)",
      text: `"ihr … doch endlich unser Heim kennenlernen": دعوة بإلحاح: "sollt" (لازمكم).\n✓ "sollt" = لازمكم (دعوة قوية).\n✗ "dürft" = مسموحلكم (إذن)، موش دعوة بإلحاح.\n✗ "könnt" = تنجّمو (قدرة): ممكنة، بصح "doch endlich" تحمل إلحاح أقوى (ihr sollt).`,
      rule: "doch endlich + sollen = dringende Aufforderung  |  dürfen = Erlaubnis", ex: "Ihr **sollt** doch endlich mal Pause machen.", exTr: "لازمكم أخيرًا ترتاحو." },
    22: { ok: "für", type: "preposition", keyword: "einladen für + Akk.", bed: "نعزموكم لـ (نهاية الأسبوع)",
      text: `الدعوة لفترة زمنية: "einladen für das Wochenende".\n✓ "für" = لـ (einladen für + مدّة).\n✗ "an" = على / في (مع التواريخ: "am Wochenende")، و"einladen an das Wochenende" ما تتقالش.\n✗ "in" = في (مكان)، و"einladen in das Wochenende" ما تعطيش معنى.`,
      rule: "jdn. für + Zeitraum einladen  |  jdn. zu + Dat. einladen (zu einer Party)", ex: "Wir laden dich **für** das Wochenende ein.", exTr: "نعزموك لنهاية الأسبوع." },
    23: { ok: "bei", type: "preposition", keyword: "bei jdm. wohnen", bed: "عندنا (تسكنو)",
      text: `"تسكنو عندنا": "bei" مع الشخص اللي تسكن في دارو.\n✓ "bei" = عند (wohnen bei + Dativ).\n✗ "unter" = تحت / بين ("unter uns" = بيناتنا)، وما تتركّبش مع "wohnen" بهذا المعنى.\n✗ "zu" = إلى (اتجاه)، موش مكان الإقامة.`,
      rule: "bei + Dativ = im Haus von jdm. (wohnen bei)", ex: "Ich wohne **bei** meinen Eltern.", exTr: "نسكن عند والديّا." },
    24: { ok: "einiges", type: "pronoun", keyword: "einiges (Pronomen, Neutrum)", bed: "برشا حاجات",
      text: `"hat ___ zu bieten": نعمّمو "برشا حاجات" بدون اسم: "einiges" (Neutrum).\n✓ "einiges" = برشا حاجات (Akkusativ محايد، بدون اسم).\n✗ "einige" = تتبعها اسم جمع ("einige Sehenswürdigkeiten")، وبدون اسم تتحمّل "أشخاص معدودين".\n✗ "einigen" = Dativ جمع، و"hat … zu bieten" ياخذ Akkusativ.`,
      rule: "einiges = ziemlich viel (Neutrum, ohne Nomen)  |  einige + Plural-Nomen", ex: "Das Museum hat **einiges** zu bieten.", exTr: "المتحف عندو برشا حاجات يعرضها." },
    25: { ok: "den", type: "preposition", keyword: "auf + Akk. (Bewegung)", bed: "على (البرج)",
      text: `"steigen" حركة (Wohin؟) ← Wechselpräposition مع Akkusativ: "auf den Turm" (Turm مذكّر).\n✓ "den" = Akkusativ مذكّر (حركة نحو).\n✗ "dem" = Dativ (مكان بدون حركة: "auf dem Turm stehen")، وهنا "steigen" حركة.\n✗ "der" = مؤنّث أو Genitiv، و"Turm" مذكّر.`,
      rule: "Wechselpräposition: Wohin? → Akk. (auf den Turm steigen)  |  Wo? → Dat. (auf dem Turm stehen)", ex: "Wir steigen auf **den** Berg.", exTr: "نطلعو للجبل." },
    26: { ok: "sind", type: "grammar_structure", keyword: "sind … zu besichtigen (sein + zu)", bed: "تتزار (الاثنين)",
      text: `الفاعل اثنين ("Schlossbibliothek" و"Tapetenzimmer") ← جمع، والتركيب sein + zu + Infinitiv: "sind … zu besichtigen".\n✓ "sind" = جمع (sein + zu + Infinitiv = ينجّم الواحد يزور).\n✗ "ist" = مفرد، والفاعل اثنين.\n✗ "waren" = ماضي، والجملة تحكي على برنامج الزيارة (حاضر / مستقبل).`,
      rule: "sein + zu + Infinitiv = kann + Passiv; das Verb richtet sich nach dem Subjekt (Plural: sind)", ex: "Im Museum **sind** auch Videos zu sehen.", exTr: "في المتحف فما كذلك فيديوهات تتشاف." },
    27: { ok: "wo", type: "conjunction", keyword: "wo (Relativadverb: Ort)", bed: "وين",
      text: `"die Runde durch den Wehrgraben, ___ man …": الجملة تعرّف بمكان ← "wo".\n✓ "wo" = وين (يرجع على مكان).\n✗ "wann" = إمتى (زمن)، والمرجع مكان.\n✗ "wie" = كيفاش (طريقة)، وما يرجعش لمكان.`,
      rule: "wo = Relativadverb für Orte (der Ort / die Stadt, wo …)", ex: "Das ist die Stadt, **wo** ich geboren bin.", exTr: "هذي المدينة اللي وين ولدت." },
    28: { ok: "Dabei", type: "pronoun_adverb", keyword: "dabei = währenddessen", bed: "وخلال هذا",
      text: `"وخلال هذي الجولة نعرفو كلّ شي على صناعة الحديد": "Dabei" (= bei + das) يرجع على الجولة.\n✓ "Dabei" = خلال هذا / في نفس الوقت.\n✗ "Daneben" = بالجنب (مكان) أو زيادة على ذلك، وهنا الكلام على نفس الجولة.\n✗ "Darin" = داخل هذا (in + das)، والمقصود النشاط موش داخل مبنى.`,
      rule: "dabei = bei dieser Tätigkeit / währenddessen", ex: "Wir wandern, **dabei** hören wir Musik.", exTr: "نتمشّاو، وخلال هذا نسمعو موسيقى." },
    29: { ok: "diesem", type: "grammar_structure", keyword: "an diesem Wochenende (Dativ)", bed: "هذا (نهاية الأسبوع)",
      text: `"an" مع الوقت تاخذ Dativ، و"Wochenende" محايد: "an diesem Wochenende".\n✓ "diesem" = Dativ محايد.\n✗ "dies" = بدون نهاية، وما يتركّبش مع اسم.\n✗ "dieses" = Nominativ / Akkusativ محايد، و"an" في الزمن تحتاج Dativ.`,
      rule: "an + Dativ (Zeit): an diesem Wochenende, am Montag", ex: "Wir treffen uns an **diesem** Samstag.", exTr: "نتلاقاو هالسبت." },
    30: { ok: "sich", type: "fixed_expression", keyword: "sich sehen lassen können", bed: "تستاهل الفرجة",
      text: `تعبير ثابت: "etwas kann sich sehen lassen" = تستاهل الفخر / الفرجة.\n✓ "sich" = ضمير انعكاسي (sich sehen lassen können).\n✗ "man" = الواحد (فاعل)، وما يتركّبش كمفعول انعكاسي هنا.\n✗ "sie" = Akkusativ (هي / هم)، والتعبير الثابت انعكاسي.`,
      rule: "etwas kann sich sehen lassen = ist vorzeigbar (reflexiv)", ex: "Dein Ergebnis kann **sich** sehen lassen.", exTr: "نتيجتك تستاهل الفخر." },
  },
};
