// SB Teil 1 restyle — batch 14: pre-authors the NON-suspect gaps of [5] Herr Martini (Original) and [6] (معدل). Gap 21 of both is left out on purpose
// (the two gap-21 option sets are swapped in the DB — see sb_t1_key_fixes.sql). Both exercises stay PENDING until the owner approves that fix.
export default {
  5: {
    22: { ok: "kommenden", type: "adjective_adverb", keyword: "im kommenden Monat", bed: "القادم (أكتوبر)",
      text: `"im ___ Oktober" = في أكتوبر القادم: Partizip I + -en (Dativ مذكّر بعد "im").\n✓ "kommenden" = القادم (Partizip I من kommen).\n✗ "ankommenden" = اللي يوصل (ankommen: "die ankommenden Gäste")، موش شهر قادم.\n✗ "gekommenen" = Partizip II (اللي جا)، معناه ماضي، والشهر قادم.`,
      rule: "im + Partizip I + -en: im kommenden / folgenden Monat", ex: "Wir sehen uns im **kommenden** Sommer.", exTr: "نتلاقاو الصيف الجاي." },
    23: { ok: "nach", type: "preposition", keyword: "nach Kriterien auswählen", bed: "حسب (معايير)",
      text: `"sorgfältig ___ strengen Kriterien ausgewählt": الاختيار يتمّ على أساس معايير: "nach".\n✓ "nach" = حسب (nach + Dativ).\n✗ "aus" = من (مجموعة: "aus einer Liste auswählen")، موش معيار.\n✗ "mit" = مع، و"mit Kriterien auswählen" ما تعطيش معنى "حسب".`,
      rule: "nach + Dat. = gemäß (nach Kriterien / Regeln / Plan)", ex: "Die Bewerber werden **nach** klaren Regeln ausgewählt.", exTr: "المترشّحين يتختارو حسب قواعد واضحة." },
    24: { ok: "bieten", type: "verb", keyword: "anbieten (bieten … an)", bed: "يعرضو",
      text: `الأسر المضيفة هي اللي تعرض الإقامة: "bieten … an" (الفعل المنفصل "anbieten").\n✓ "bieten" = يعرض (bieten … Halbpension an).\n✗ "fordern" = يطلب (fordern … an = anfordern = يطلب)، المعنى معكوس.\n✗ "nehmen" = ياخذ (nehmen … an = annehmen = يقبل)، موش يعرض.`,
      rule: "trennbar: anbieten → sie bieten … an  |  anfordern = verlangen  |  annehmen = akzeptieren", ex: "Das Hotel **bietet** Frühstück **an**.", exTr: "النزل يعرض فطور." },
    25: { ok: "so dass", type: "conjunction", keyword: "so dass + Nebensatz (Folge)", bed: "بحيث",
      text: `النتيجة من القرب: العائلات قريبة، "بحيث" الطريق ما يتعدّاش 10 دقايق: "so dass".\n✓ "so dass" = بحيث (نتيجة، + فعل في الآخر).\n✗ "weil" = خاطر (سبب)، والجملة تعطي نتيجة القرب موش سببو.\n✗ "wenn" = إذا (شرط)، وما فماش شرط.`,
      rule: "so dass = Folge  |  weil = Grund  |  wenn = Bedingung", ex: "Er wohnt nah, **so dass** er zu Fuß gehen kann.", exTr: "يسكن قريب، بحيث ينجّم يمشي على رجليه." },
    26: { ok: "Gemeinsam mit", type: "fixed_expression", keyword: "gemeinsam mit + Dativ", bed: "مع (التلاميذ)",
      text: `"مع التلاميذ" اللي نعملو معاهم البرنامج: "Gemeinsam mit" + Dativ.\n✓ "Gemeinsam mit" = مع (+ Dativ).\n✗ "Verbunden von" = تركيب غلط (الصحيح "verbunden mit").\n✗ "Zusammen neben" = تركيب غير موجود (الصحيح "zusammen mit").`,
      rule: "gemeinsam / zusammen + mit + Dativ  |  verbunden mit", ex: "**Gemeinsam mit** Freunden fahre ich in Urlaub.", exTr: "مع الأصحاب نمشي في عطلة." },
    27: { ok: "der Besuch", type: "noun", keyword: "der Besuch + Genitiv", bed: "زيارة",
      text: `"Dazu gehört z. B. der Besuch der Gemäldegalerie, des Museums …": الفاعل "der Besuch" + Genitiv.\n✓ "der Besuch" = الزيارة (+ Genitiv، مذكّر مفرد مع "gehört").\n✗ "die Ansicht" = رأي / منظر، و"Ansicht der Galerie" ما تعني زيارتها.\n✗ "das Betrachten" = التأمّل (فعل كاسم)، وما تعبّرش على زيارة معرض كبرنامج.`,
      rule: "der Besuch + Genitiv (der Besuch des Museums)", ex: "Dazu gehört auch **der Besuch** des Museums.", exTr: "ومنها كذلك زيارة المتحف." },
    28: { ok: "ist geplant", type: "tense", keyword: "ist geplant (Zustandspassiv)", bed: "مبرمجة",
      text: `الزيارة هي المبرمجة (موش اللي تبرمج): "ein Besuch … ist geplant" (Zustandspassiv).\n✓ "ist geplant" = sein + Partizip II (خطّة مبرمجة).\n✗ "hat geplant" = Perfekt نشط، والفاعل "ein Besuch" ما يخطّطش.\n✗ "wird geplant haben" = Futur II نشط، والفاعل نفس المشكل.`,
      rule: "sein + Partizip II = Zustandspassiv (Ergebnis / Plan)", ex: "Für morgen **ist** ein Ausflug **geplant**.", exTr: "لغدوة مبرمجة رحلة." },
    29: { ok: "besprochen", type: "verb", keyword: "besprechen (Passiv)", bed: "تتناقش",
      text: `"die Aspekte … der Kultur ___ werden sollen" = تتناقش: "besprochen werden".\n✓ "besprochen" = Partizip II من "besprechen" (ناقش، + Akkusativ).\n✗ "gesprochen" = Partizip II من "sprechen"، ويحتاج "über" ("über Kultur gesprochen")، موش مفعول مباشر.\n✗ "versprochen" = وعد (versprechen)، معنى مختلف.`,
      rule: "etwas besprechen (+ Akk.)  |  über etwas sprechen  |  etwas versprechen", ex: "Das Thema soll morgen **besprochen** werden.", exTr: "الموضوع لازم يتناقش غدوة." },
    30: { ok: "haben", type: "tense", keyword: "Futur I im Nebensatz: Infinitiv + werden", bed: "(باش) يكون عندكم",
      text: `"dass Sie … einen Aufenthalt … haben werden": Futur I في الجملة الفرعية: Infinitiv + "werden" في الآخر.\n✓ "haben" = Infinitiv (haben werden).\n✗ "hatten" = Präteritum (فعل مصرّف)، وقبل "werden" لازم Infinitiv.\n✗ "hätten" = Konjunktiv II مصرّف، ونفس المشكل.`,
      rule: "Futur I im Nebensatz: Infinitiv … werden (am Ende)", ex: "Ich hoffe, dass wir viel Spaß **haben** werden.", exTr: "نتمنّى إنّو باش يكون عندنا برشا متعة." },
  },
  6: {
    22: { ok: "kommenden", type: "adjective_adverb", keyword: "im kommenden Monat", bed: "القادم (أكتوبر)",
      text: `"im ___ Oktober" = في أكتوبر القادم: Partizip I + -en.\n✓ "kommenden" = القادم (Partizip I من kommen).\n✗ "ankommenden" = اللي يوصل (ankommen)، موش شهر قادم.\n✗ "gekommenden" = شكل غلط (Partizip II مع نهاية Partizip I)، ما موجودش.`,
      rule: "im + Partizip I + -en: im kommenden / folgenden Monat", ex: "Das passiert im **kommenden** Frühling.", exTr: "هذا يصير الربيع الجاي." },
    27: { ok: "der Besuch", type: "noun", keyword: "der Besuch + Genitiv", bed: "زيارة",
      text: `"Dazu gehört z. B. der Besuch der Gemäldegalerie …": الفاعل "der Besuch" + Genitiv.\n✓ "der Besuch" = الزيارة (+ Genitiv).\n✗ "die" = أداة بدون اسم، و"die der Gemäldegalerie" ما تتركّبش.\n✗ "das Betrachten" = التأمّل (فعل كاسم)، وما تعبّرش على زيارة معرض كبرنامج.`,
      rule: "der Besuch + Genitiv (der Besuch des Museums)", ex: "Wichtig ist **der Besuch** der Altstadt.", exTr: "المهم هو زيارة المدينة القديمة." },
  },
};
