// SB Teil 1 restyle — batch 11: [50] Theatertournee, [51] Markus, [52] Laura, [53] Rahim, [54] Brauckmann Versand
export default {
  // ───────────── [50] Theatertournee durch Spanien ─────────────
  50: {
    21: { ok: "durch", type: "preposition", keyword: "Tour durch + Akk.", bed: "جولة عبر (ألمانيا وإسبانيا)",
      text: `جولة فنّية تدور على بلدين: "Tour durch Deutschland und Spanien".\n✓ "durch" = عبر / في كامل (+ Akkusativ).\n✗ "aus" = من (مصدر)، و"Tour aus Deutschland" معناها جولة جاية من ألمانيا.\n✗ "von" = من، و"Tour von Deutschland" ما تتقالش لجولة داخل البلدين.`,
      rule: "eine Tour / Reise durch + Akk. (Länder, Regionen)", ex: "Wir machen eine Tour **durch** Süditalien.", exTr: "نعملو جولة في جنوب إيطاليا." },
    22: { ok: "einer", type: "grammar_structure", keyword: "mit + Dativ Fem.: einer", bed: "مع (مجموعة) متنوّعة",
      text: `"mit" تتبعها Dativ، و"Gruppe" مؤنّث: "mit so einer bunt gemischten Gruppe".\n✓ "einer" = Dativ مؤنّث.\n✗ "eine" = Nominativ / Akkusativ مؤنّث، و"mit" تحتاج Dativ.\n✗ "einen" = Akkusativ مذكّر، و"Gruppe" مؤنّث.`,
      rule: "mit + Dativ: Femininum → einer (mit so einer Gruppe)", ex: "Ich reise mit **einer** kleinen Gruppe.", exTr: "نسافر مع مجموعة صغيرة." },
    23: { ok: "dir", type: "pronoun", keyword: "sich (Dat.) denken können", bed: "تنجّم تتصوّر",
      text: `تعبير ثابت: "Du kannst dir denken, dass …" = تنجّم تتصوّر.\n✓ "dir" = Dativ (sich etwas denken).\n✗ "dich" = Akkusativ، و"denken" في هذا التعبير يتركّب مع Dativ.\n✗ "sich" = انعكاسي للغائب، والفاعل هنا "du".`,
      rule: "sich (Dat.) etwas denken können = sich vorstellen", ex: "Das kannst du **dir** denken.", exTr: "تنجّم تتصوّر هذا." },
    24: { ok: "aufgeregt", type: "adjective_adverb", keyword: "aufgeregt sein ≠ aufregend", bed: "متحمّسة / متوتّرة",
      text: `الجملة تصف شعور الشخص ("ich bin … "): الصفة "aufgeregt".\n✓ "aufgeregt" = متحمّسة / متوتّرة (شعور الشخص).\n✗ "aufregend" = مثير (يوصف بيه الشي: "Das Spiel ist aufregend")، موش شعور الواحد.\n✗ "aufzuregen" = zu + Infinitiv، وما يتركّبش بعد "sehr … bin".`,
      rule: "aufgeregt = Gefühl der Person  |  aufregend = Eigenschaft der Sache", ex: "Ich bin vor der Prüfung immer **aufgeregt**.", exTr: "قبل الامتحان ديما نكون متوتّر." },
    25: { ok: "obwohl", type: "conjunction", keyword: "obwohl + Nebensatz", bed: "رغم إنّي (نحكي إسباني بطلاقة)",
      text: `متوتّرة رغم إنّها تحكي إسباني بطلاقة: تنازل، والفعل "spreche" في الآخر.\n✓ "obwohl" = رغم إنّو (+ فعل في الآخر).\n✗ "weil" = خاطر (سبب)، والمنطق هنا عكس التوقّع (تنازل).\n✗ "zwar" = صحيح (zwar … aber)، وهو ظرف موش رابط يفتح جملة فرعية.`,
      rule: "obwohl + Nebensatz (Verb am Ende) = Gegensatz zur Erwartung", ex: "Ich bin müde, **obwohl** ich lange geschlafen habe.", exTr: "تعبان رغم إنّي رقدت برشا." },
    26: { ok: "Im", type: "preposition", keyword: "im Herbst (in + dem)", bed: "في (الخريف)",
      text: `الفصول تتقال بـ "im": "Im Herbst" (in + dem).\n✓ "Im" = في (in + dem، مع الفصول والشهور).\n✗ "In" = بدون أداة "In Herbst" ما تتقالش (تحتاج الأداة المدمجة).\n✗ "Während" = أثناء (+ Genitiv: "Während des Herbstes")، و"Während Herbst" ما تتقالش.`,
      rule: "Jahreszeiten / Monate: im + Jahreszeit (im Herbst, im Mai)", ex: "**Im** Sommer fahren wir ans Meer.", exTr: "في الصيف نمشيو للبحر." },
    27: { ok: "würde", type: "tense", keyword: "würde gern + Infinitiv", bed: "نحب (نشوفكم)",
      text: `"wie gerne ___ ich euch alle wiedersehen": رغبة، Konjunktiv II بـ "würde" + Infinitiv.\n✓ "würde" = würde + Infinitiv (رغبة).\n✗ "hätte" = Konjunktiv II من "haben"، ويحتاج Partizip II ("hätte gesehen")، موش Infinitiv.\n✗ "wurde" = Präteritum من "werden" (ماضي)، وما يتماشاش مع رغبة.`,
      rule: "Wunsch: würde (gern) + Infinitiv", ex: "Wie gern **würde** ich dich besuchen!", exTr: "قدّاش نحب نزورك!" },
    28: { ok: "können", type: "tense", keyword: "hätte … lernen können", bed: "ننجّم (نتعلّم)",
      text: `"Ohne eure Hilfe hätte ich … lernen ___": Konjunktiv II ماضي مع فعل مساعد (نتيجة ما صارتش بدونكم): "hätte … lernen können".\n✓ "können" = Infinitiv (hätte + Infinitiv + können).\n✗ "müssen" = لازم، والمعنى "ما كنتش ننجّم" (إمكانية).\n✗ "sollen" = المفروض، موش إمكانية.`,
      rule: "Konjunktiv II Vergangenheit mit Modalverb: hätte + Infinitiv + Modalverb-Infinitiv", ex: "Ohne dich hätte ich es nicht schaffen **können**.", exTr: "بدونك ما كنتش نجّمت نعملها." },
    29: { ok: "davon", type: "pronoun_adverb", keyword: "ein bisschen davon (Teilmenge)", bed: "شوية منها",
      text: `"Ein bisschen ___" = جزء صغير من حاجة معروفة (أجواء الشقّة المشتركة): "davon" (= von + das).\n✓ "davon" = منها (جزء).\n✗ "damit" = بهذا (mit + das)، و"ein bisschen damit" ما تعبّرش على جزء.\n✗ "dazu" = لهذا / زيادة على ذلك، وما تعطيش معنى "جزء منها".`,
      rule: "davon = von + das (Teilmenge: ein bisschen davon, viel davon)", ex: "Ich habe nur ein bisschen **davon** verstanden.", exTr: "فهمت غير شوية منها." },
    30: { ok: "wiedergefunden", type: "tense", keyword: "wiedergefunden (Perfekt)", bed: "لقيتو من جديد",
      text: `"habe ich … ___": Perfekt، يحتاج Partizip II.\n✓ "wiedergefunden" = Partizip II (habe … wiedergefunden).\n✗ "wiederfinden" = Infinitiv، وبعد "habe" نحتاج Partizip II.\n✗ "wiederzufinden" = zu + Infinitiv، وما يتركّبش مع "habe" في الـ Perfekt.`,
      rule: "Perfekt mit haben: haben + Partizip II (wiedergefunden)", ex: "Ich habe meinen Schlüssel **wiedergefunden**.", exTr: "لقيت مفتاحي من جديد." },
  },

  // ───────────── [51] Markus ─────────────
  51: {
    21: { ok: "wohl", type: "adjective_adverb", keyword: "wohl (Vermutung)", bed: "غالبًا",
      text: `"ist ja ___ ganz normal, denke ich": تخمين مخفّف.\n✓ "wohl" = غالبًا (Vermutung / Abschwächung).\n✗ "doch" = تقوّي ("ist ja doch normal") ممكنة، بصح بعدها "denke ich" تعبّر على تخمين فـ "wohl" أنسب.\n✗ "sogar" = حتى (زيادة غير متوقّعة)، موش مناسبة لقول "هذا عادي".`,
      rule: "wohl = Vermutung / Abschwächung  |  doch = Verstärkung  |  sogar = überraschende Steigerung", ex: "Das ist **wohl** normal.", exTr: "هذا غالبًا عادي." },
    22: { ok: "hinter", type: "fixed_expression", keyword: "etwas hinter sich haben", bed: "خلصت (وراي)",
      text: `"habe ich die Prüfung ___ mir": الامتحان فات وخلص: "hinter mir".\n✓ "hinter" = وراي (تمّ وفات).\n✗ "hinten" = ظرف مكان ("hinten im Auto")، وما يتركّب مع "mir".\n✗ "hinunter" = لتحت (اتجاه)، وما يتركّب مع "mir" ولا مع معنى "خلصت".`,
      rule: "etwas hinter sich haben = abgeschlossen", ex: "Den Stress habe ich **hinter** mir.", exTr: "الضغط خلص." },
    23: { ok: "bestanden", type: "verb", keyword: "eine Prüfung bestehen", bed: "نجّحت (في الامتحان)",
      text: `"habe ich … ___": Perfekt من "bestehen" (امتحان).\n✓ "bestanden" = Partizip II من "bestehen" (نجح).\n✗ "gepasst" = Partizip II من "passen" (يناسب)، موش نجاح.\n✗ "bestehen" = Infinitiv، وبعد "habe" نحتاج Partizip II.`,
      rule: "eine Prüfung bestehen – bestand – bestanden", ex: "Sie hat den Test **bestanden**.", exTr: "نجّحت في الاختبار." },
    24: { ok: "ja", type: "adjective_adverb", keyword: "ja (Begründung / Bekanntes)", bed: "خاطر (كيما تعرف)",
      text: `"Ich hatte mich ja auch gut vorbereitet": "ja" تعطي تعليل معروف.\n✓ "ja" = كيما تعرف / خاطر (Abtönungspartikel).\n✗ "also" = إذن (نتيجة)، والجملة هنا تعليل.\n✗ "wohl" = غالبًا (تخمين)، والكاتبة تعرف بالضبط إنّها حضّرت.`,
      rule: "ja (unbetont) = erinnert an Bekanntes / begründet", ex: "Ich bin müde, ich war **ja** den ganzen Tag unterwegs.", exTr: "تعبان، خاطر كنت طول النهار برّة." },
    25: { ok: "mich", type: "pronoun", keyword: "sich fangen", bed: "لمّيت روحي",
      text: `"sich fangen" فعل انعكاسي بـ Akkusativ، والفاعل "ich": "bis ich mich wieder gefangen hatte".\n✓ "mich" = Akkusativ لـ "ich".\n✗ "mir" = Dativ، و"sich fangen" يتطلّب Akkusativ.\n✗ "meins" = ملكي (Possessivpronomen)، موش ضمير انعكاسي.`,
      rule: "reflexives Verb (Akk.): sich fangen → ich fange mich", ex: "Ich habe **mich** schnell wieder gefangen.", exTr: "لمّيت روحي بسرعة." },
    26: { ok: "sobald", type: "conjunction", keyword: "sobald + Präsens", bed: "ساعة ما",
      text: `"ساعة ما ناخذ الشهادة نقدّم مطلب": حدث مستقبلي يجي مباشرة بعد حدث آخر.\n✓ "Sobald" = ساعة ما (+ فعل في الآخر).\n✗ "seit" = من (حدث بدا في الماضي ومازال)، والحدث هنا مستقبلي.\n✗ "nachdem" = بعد ما: يحتاج Perfekt ("nachdem ich … bekommen habe")، وهنا "bekomme" حاضر.`,
      rule: "sobald + Präsens (Zukunft)  |  nachdem + Perfekt  |  seit = ab Beginn bis jetzt", ex: "**Sobald** ich fertig bin, rufe ich an.", exTr: "ساعة ما نخلّص نعيّط." },
    27: { ok: "bei", type: "verb_prep", keyword: "sich bewerben bei + Firma", bed: "عند (شركة كبيرة)",
      text: `التقديم لشركة بـ "bei": "sich bewerben bei einer Firma".\n✓ "bei" = عند (sich bewerben bei + Firma).\n✗ "um" = على (sich bewerben um eine Stelle)، تتبعها المنصب موش الشركة.\n✗ "an" = في (sich bewerben an einer Uni / Schule)، للجامعات والمدارس.`,
      rule: "sich bewerben bei + Firma  |  um + Stelle  |  an + Uni / Schule", ex: "Ich bewerbe mich **bei** einer Bank.", exTr: "نقدّم مطلب لبنك." },
    28: { ok: "was", type: "pronoun", keyword: "was mich erwartet", bed: "شنوّة (ينتظرني)",
      text: `"Mal sehen, ___ mich … erwartet": اللي ينتظر مجهول (شي موش شخص).\n✓ "was" = شنوّة (Fragewort للأشياء، فاعل).\n✗ "wer" = شكون (لشخص).\n✗ "wen" = شكون (Akkusativ لشخص)، و"mich" هو المفعول به والفاعل شي مجهول.`,
      rule: "was = Fragewort für Sachen (Subjekt)  |  wer / wen = Personen", ex: "Mal sehen, **was** uns dort erwartet.", exTr: "نشوفو شنوّة ينتظرنا هناك." },
    29: { ok: "der", type: "grammar_structure", keyword: "von + Dativ Fem.: der", bed: "عن (الدراسة)",
      text: `"Abstand von ___ ganzen Lernerei": "von" + Dativ، و"Lernerei" مؤنّث.\n✓ "der" = Dativ مؤنّث.\n✗ "dem" = Dativ مذكّر / محايد، و"Lernerei" مؤنّث.\n✗ "das" = Nominativ / Akkusativ محايد، و"von" تحتاج Dativ.`,
      rule: "von + Dativ: fem. → der  |  mask. / neutr. → dem", ex: "Ich brauche Abstand von **der** Arbeit.", exTr: "نحتاج مسافة عن الخدمة." },
    30: { ok: "zwar", type: "fixed_expression", keyword: "und zwar (Präzisierung)", bed: "وبالضبط",
      text: `"Eine große Party, und zwar am 14. Juni": "und zwar" تحدّد التفاصيل.\n✓ "zwar" = و"und zwar" = وبالضبط.\n✗ "dann" = وقتها: "und dann am 14. Juni" ممكنة كتسلسل، بصح "und zwar" هي اللي توضّح نفس الحفلة.\n✗ "auch" = زادا، وتضيف حاجة جديدة موش توضّح نفس الحفلة.`,
      rule: "und zwar = und genauer gesagt (Präzisierung)", ex: "Ich komme morgen, und **zwar** um acht.", exTr: "باش نجي غدوة، وبالضبط على الثامنة." },
  },

  // ───────────── [52] Laura ─────────────
  52: {
    21: { ok: "denen", type: "pronoun", keyword: "von denen (Relativpronomen Dativ Pl.)", bed: "اللي (على أشياء)",
      text: `"viele Dinge, von ___ man … hört": مرجعو جمع (Dinge)، و"von" تتبعها Dativ: "von denen".\n✓ "denen" = Dativ جمع (الـ Dinge).\n✗ "dem" = Dativ مذكّر / محايد، والمرجع جمع.\n✗ "deren" = Genitiv (ملكية)، وما تفتحش جملة بعد حرف الجر "von".`,
      rule: "Relativpronomen Dativ Plural: denen (Präposition steht davor)", ex: "Das sind Probleme, von **denen** niemand spricht.", exTr: "هذي مشاكل ما يحكي عليها حتى واحد." },
    22: { ok: "es", type: "pronoun", keyword: "es + Adjektiv + zu-Infinitiv", bed: "كان (صعيب)",
      text: `"war es mühevoll, … zu sitzen": "es" يعلن على جملة "zu + Infinitiv" اللي بعدو.\n✓ "es" = فاعل شكلي (Platzhalter).\n✗ "man" = الواحد، و"war man mühevoll" ما تتقالش (الصفة تصف الحالة موش الشخص).\n✗ "-" (بدون ضمير) = ممكنة في الأسلوب الأدبي، بصح المعتاد بعد "In den ersten Wochen" هو "es".`,
      rule: "es als Platzhalter für einen folgenden zu-Infinitiv-Satz (es war mühevoll, … zu sitzen)", ex: "Am Anfang war **es** schwer, Deutsch zu sprechen.", exTr: "في البداية كان صعيب نحكي ألماني." },
    23: { ok: "daran", type: "pronoun_adverb", keyword: "sich gewöhnen an → daran", bed: "على هذا (تعوّدت)",
      text: `"sich gewöhnen" يتبعو "an"، والـ Pronominaladverb "daran" (= an + das) يرجع على الأشياء الجديدة.\n✓ "daran" = على هذا (an + das).\n✗ "darauf" = على هذا (auf + das)، وتجي مع "sich verlassen auf / warten auf".\n✗ "dazu" = لهذا (zu + das)، وما تتركّبش مع "gewöhnen".`,
      rule: "sich gewöhnen an + Akk. → daran", ex: "Ich habe mich **daran** gewöhnt, früh aufzustehen.", exTr: "تعوّدت نقوم بكري." },
    24: { ok: "einen", type: "grammar_structure", keyword: "einen Pullover (Akk. maskulin)", bed: "(بلّوفر) واحد",
      text: `"Pullover" مذكّر ومفعول به (Akkusativ): "einen Pullover dabeihaben".\n✓ "einen" = Akkusativ مذكّر.\n✗ "ein" = Nominativ / Akkusativ محايد، و"Pullover" مذكّر.\n✗ "einer" = مؤنّث أو Dativ، موش مذكّر Akkusativ.`,
      rule: "Akkusativ maskulin: ein → einen (haben / dabeihaben / brauchen)", ex: "Ich brauche **einen** Schirm.", exTr: "نحتاج مظلّة." },
    25: { ok: "müsse", type: "tense", keyword: "müsse (Konjunktiv I, indirekte Rede)", bed: "لازم (حسب كلامو)",
      text: `"Mein Chef sagt … man müsse": كلام منقول (indirekte Rede) ← Konjunktiv I.\n✓ "müsse" = Konjunktiv I من "müssen".\n✗ "musste" = Präteritum (ماضي)، وهنا الفعل مرتبط بقول ديما.\n✗ "brauche" = Konjunktiv I من "brauchen"، ويحتاج "zu" وتركيب مختلف ("brauche man … zu trinken").`,
      rule: "indirekte Rede: Konjunktiv I (er sagt, man müsse)", ex: "Er sagt, man **müsse** früh aufstehen.", exTr: "يقول لازم الواحد يقوم بكري." },
    26: { ok: "der Nähe von", type: "preposition", keyword: "aus der Nähe von + Stadt", bed: "من قرب (ويلهلمسهافن)",
      text: `أسماء المدن بدون أداة تحتاج "von" بعد "Nähe": "aus der Nähe von Wilhelmshaven".\n✓ "der Nähe von" = من قرب (aus + Dativ مؤنّث + von + Stadt).\n✗ "der Nähe" = ناقصة "von" قبل اسم المدينة.\n✗ "die Nähe" = Akkusativ مؤنّث، و"aus" تتبعها Dativ.`,
      rule: "in / aus der Nähe von + Ort (Städtenamen brauchen 'von')", ex: "Er kommt aus **der Nähe von** Berlin.", exTr: "يجي من قرب برلين." },
    27: { ok: "den großen", type: "grammar_structure", keyword: "mit + Dativ Plural: den großen …", bed: "(السفن) الكبيرة",
      text: `"mit" + Dativ جمع (Containerschiffen): الأداة "den" والصفة -en.\n✓ "den großen" = Dativ جمع.\n✗ "großem" = Dativ مفرد (مذكّر / محايد) بدون أداة، و"Containerschiffen" جمع.\n✗ "dem großen" = Dativ مفرد، و"Containerschiffen" جمع.`,
      rule: "Dativ Plural: den + Adjektiv-en + Nomen-n", ex: "Ich spiele mit **den kleinen** Kindern.", exTr: "نلعب مع الأطفال الصغار." },
    28: { ok: "die Schiffe", type: "grammar_structure", keyword: "um + Akk. (die Schiffe)", bed: "حول (السفن)",
      text: `"um" تتبعها Akkusativ: "um die Schiffe herumkreisen" (جمع).\n✓ "die Schiffe" = Akkusativ جمع (بدون -n).\n✗ "den Schiffen" = Dativ جمع، و"um" تحتاج Akkusativ.\n✗ "die Schiffen" = أداة Akkusativ مع نهاية Dativ (-n)، شكل مخلوط وغلط.`,
      rule: "um + Akk.; Plural Akkusativ: die + Nomen (ohne -n)", ex: "Die Vögel kreisen um **die Türme**.", exTr: "الطيور تدور حول الأبراج." },
    29: { ok: "einem", type: "pronoun", keyword: "in einem der + Genitiv Pl.", bed: "في واحد (من المقاهي)",
      text: `"in einem der Cafés" = في واحد من المقاهي: "in" + Dativ، و"Café" محايد.\n✓ "einem" = Dativ محايد (واحد من مجموعة).\n✗ "eins" = واحد (Pronomen بدون حرف جر)، وبعد "in" نحتاج الشكل المصرّف.\n✗ "ein" = Nominativ / Akkusativ، و"in ein der Cafés" ما تتقالش.`,
      rule: "einer / einem / eines + der + Plural (Genitiv) = eines von mehreren", ex: "Wir sitzen in **einem** der Cafés am Hafen.", exTr: "نقعدو في واحد من المقاهي اللي في الميناء." },
    30: { ok: "wiedersehen müssen", type: "grammar_structure", keyword: "Nebensatz: Infinitiv + Modalverb am Ende", bed: "لازمنا نتلاقاو",
      text: `"daran, dass wir uns bald ___": dass-Satz، الفعل المصرّف يمشي للآخر بعد الـ Infinitiv.\n✓ "wiedersehen müssen" = Infinitiv + Modalverb في الآخر.\n✗ "wiederzusehen brauchen" = "brauchen" تحتاج نفي أو "nur" (brauchen … zu)، وهنا ما فماش.\n✗ "müssen wiedersehen" = ترتيب الجملة الرئيسية، والـ dass-Satz يحط الفعل المصرّف في الآخر.`,
      rule: "Nebensatz: Infinitiv … Modalverb (konjugiert, am Ende)", ex: "Ich weiß, dass wir früh aufstehen **müssen**.", exTr: "نعرف إنّو لازمنا نقومو بكري." },
  },

  // ───────────── [53] Rahim ─────────────
  53: {
    21: { ok: "über", type: "verb_prep", keyword: "sich freuen über + Akk.", bed: "نفرحو بـ (اهتمامك)",
      text: `"Wir freuen uns ___ dein Interesse": فرح بحاجة وصلت، "über" + Akkusativ.\n✓ "über" = على / بـ (sich freuen über).\n✗ "für" = لأجل: "sich für jdn. freuen" تتقال مع شخص ("Ich freue mich für dich")، موش مع "Interesse".\n✗ "wegen" = بسبب (+ Genitiv: "wegen deines Interesses")، وهنا "dein" Akkusativ.`,
      rule: "sich freuen über + Akk. (Sache)  |  sich freuen für + Akk. (Person)", ex: "Wir freuen uns **über** deinen Besuch.", exTr: "نفرحو بزيارتك." },
    22: { ok: "sich", type: "pronoun", keyword: "sich befinden (Subjekt: Wohnung)", bed: "موجودة",
      text: `الفاعل "die Wohnung" (غائب مؤنّث) والفعل انعكاسي: "befindet sich".\n✓ "sich" = انعكاسي للغائب.\n✗ "man" = الواحد، والفاعل "die Wohnung" موش "man".\n✗ "uns" = انعكاسي لـ "wir"، والفاعل "die Wohnung".`,
      rule: "sich befinden (Reflexivpronomen richtet sich nach dem Subjekt)", ex: "Der Bahnhof befindet **sich** in der Nähe.", exTr: "المحطّة موجودة قريب." },
    23: { ok: "von dem", type: "pronoun", keyword: "von dem (Relativpronomen mask. Dativ)", bed: "اللي من فوقو",
      text: `"Balkon" مذكّر: الجملة الفرعية تقول "من فوقو تشوف منظر": "von dem man … Aussicht hat".\n✓ "von dem" = Dativ مذكّر (+ von).\n✗ "auf der" = مؤنّث، و"Balkon" مذكّر.\n✗ "für den" = Akkusativ مذكّر + "für" (لأجل)، وما تعطيش معنى "من فوقو تشوف".`,
      rule: "Relativpronomen Dativ maskulin: dem (+ Präposition: von dem)", ex: "Der Turm, **von dem** man die Stadt sieht, ist alt.", exTr: "البرج اللي من فوقو تشوف المدينة قديم." },
    24: { ok: "werden", type: "grammar_structure", keyword: "kann … gestaltet werden (Passiv mit Modalverb)", bed: "تتجهّز (الغرفة)",
      text: `"kann … gestaltet ___": Passiv مع فعل مساعد: Partizip II + "werden" (Infinitiv).\n✓ "werden" = Infinitiv (kann … gestaltet werden).\n✗ "wurden" = Präteritum جمع، والجملة فيها "kann" (حاضر).\n✗ "würden" = Konjunktiv II جمع، موش Infinitiv بعد "kann".`,
      rule: "Modalverb + Partizip II + werden (Passiv-Infinitiv)", ex: "Das Zimmer kann nach Wunsch eingerichtet **werden**.", exTr: "الغرفة تنجّم تتجهّز على ذوقك." },
    25: { ok: "mit", type: "verb_prep", keyword: "sich beschäftigen mit (beruflich)", bed: "نشتغل على",
      text: `"ich beschäftige mich beruflich ___ der Entwicklung": الفعل يتبعو "mit".\n✓ "mit" = على (sich beschäftigen mit + Dativ).\n✗ "an" = على (arbeiten an + Dativ)، لكن مع "sich beschäftigen" الحرف "mit".\n✗ "in" = في (مكان)، وما تتركّبش مع "beschäftigen".`,
      rule: "sich beschäftigen mit + Dat. (arbeiten an + Dat.)", ex: "Er beschäftigt sich **mit** Fotografie.", exTr: "يشتغل على التصوير." },
    26: { ok: "während", type: "conjunction", keyword: "während (Gegensatz)", bed: "بينما",
      text: `مقارنة بين زوز أشخاص: واحد برّة كلّ الوقت و"أنا" في الدار: "während" (بينما).\n✓ "während" = بينما (تقابل، + فعل في الآخر).\n✗ "anstatt" = عوض (+ dass / zu)، و"anstatt ich … lasse" ما تتركّبش بدون "dass".\n✗ "sondern" = بل (يصحّح نفي)، وما فماش نفي قبلها.`,
      rule: "während + Nebensatz = Gegensatz / Gleichzeitigkeit", ex: "Er liebt Sport, **während** ich lieber lese.", exTr: "يحب الرياضة بينما أنا نفضّل نقرا." },
    27: { ok: "zwar", type: "conjunction", keyword: "zwar … aber (Zugeständnis)", bed: "صحيح",
      text: `"Abends trinken wir zwar gerne ein Gläschen Wein, aber große Partys feiern wir nie": اعتراف وبعدو "aber".\n✓ "zwar" = صحيح (الجزء الأول من zwar … aber).\n✗ "entweder" = إمّا (entweder … oder)، وما فماش "oder".\n✗ "sowohl" = تحتاج "als auch"، وما فماش.`,
      rule: "zwar … aber  |  entweder … oder  |  sowohl … als auch", ex: "Ich mag Kaffee **zwar**, aber nicht abends.", exTr: "صحيح نحب القهوة، بصح موش في العشية." },
    28: { ok: "dessen", type: "pronoun", keyword: "dessen Lebensstil (Genitiv)", bed: "اللي (نمط حياتو)",
      text: `"Mitbewohner, ___ Lebensstil …" = اللي نمط حياتو: Genitiv مذكّر (ملكية).\n✓ "dessen" = Genitiv مذكّر (dessen Lebensstil).\n✗ "denen" = Dativ جمع، موش ملكية، والمرجع مفرد.\n✗ "seinen" = Possessivartikel، والجملة الفرعية تحتاج Relativpronomen.`,
      rule: "Genitiv-Relativpronomen: dessen (m / n), deren (f / Pl.) — danach kein Artikel", ex: "Ich suche einen Mitbewohner, **dessen** Hobbys zu meinen passen.", exTr: "نلوّج على شريك سكن هواياتو تتماشى مع هواياتي." },
    29: { ok: "damit", type: "conjunction", keyword: "damit + Nebensatz (Zweck)", bed: "باش (نتعارفو)",
      text: `"Schön, dass du vorbeikommst, ___ wir uns kennenlernen können": الغرض من الزيارة.\n✓ "damit" = باش (غرض، + فعل في الآخر).\n✗ "deswegen" = لهذا السبب (ظرف نتيجة، الفعل في الثانية)، وهنا "können" في الآخر.\n✗ "indem" = بواسطة (وسيلة)، موش غرض.`,
      rule: "damit = Zweck (Nebensatz)  |  indem = Mittel  |  deswegen = Folge (Hauptsatz)", ex: "Ich rufe an, **damit** wir uns verabreden können.", exTr: "نعيّط باش نتفقو على موعد." },
    30: { ok: "gewusst hätte", type: "tense", keyword: "Wenn ich … gewusst hätte", bed: "كان عرفت",
      text: `"hätte ich mir Zeit frei gehalten" = كان نخلّي الوقت (ما صارش): شرط غير واقعي في الماضي ← Plusquamperfekt Konjunktiv II.\n✓ "gewusst hätte" = Konjunktiv II الماضي (irreal).\n✗ "gewusst habe" = Perfekt Indikativ (حقيقة)، موش افتراض.\n✗ "wüsste" = Konjunktiv II حاضر، والسياق ماضي ("hätte … gehalten").`,
      rule: "irrealer Bedingungssatz Vergangenheit: wenn + Plusquamperfekt (hätte / wäre), dann hätte / wäre + Partizip II", ex: "Wenn ich das **gewusst hätte**, wäre ich gekommen.", exTr: "كان نعرف هذا، كنت جيت." },
  },

  // ───────────── [54] Brauckmann Versand ─────────────
  54: {
    21: { ok: "Monaten", type: "grammar_structure", keyword: "vor + Dativ Plural (-n)", bed: "قبل شهرين",
      text: `"vor" الزمنية تتبعها Dativ، و"Monate" جمع Dativ يزيد -n: "vor zwei Monaten".\n✓ "Monaten" = Dativ جمع.\n✗ "Monate" = Nominativ / Akkusativ جمع، و"vor" تحتاج Dativ.\n✗ "Monats" = Genitiv مفرد، موش جمع.`,
      rule: "vor + Dativ (zeitlich): vor zwei Monaten (Dativ Plural endet auf -n)", ex: "Vor zwei **Wochen** war ich dort.", exTr: "قبل أسبوعين كنت هنا." },
    22: { ok: "Ihnen", type: "pronoun", keyword: "Ihnen (Dativ, formell)", bed: "ليكم (حضرتكم)",
      text: `رسالة رسمية للشركة: "mitteilen" + Dativ للشخص، والصيغة الرسمية بحرف كبير: "Ihnen".\n✓ "Ihnen" = Dativ رسمي (للمخاطَب).\n✗ "ihnen" = بحرف صغير تعني "لهم" (غائبين)، والرسالة موجّهة للشركة (Sie).\n✗ "Sie" = Akkusativ، و"mitteilen" ياخذ Dativ للشخص.`,
      rule: "jdm. etwas mitteilen (Dativ); formelle Anrede: Ihnen wird großgeschrieben", ex: "Ich muss **Ihnen** leider absagen.", exTr: "للأسف لازمني نعتذر منكم." },
    23: { ok: "musste", type: "verb", keyword: "musste (Präteritum, man)", bed: "كان لازم",
      text: `الأفعال حواليه ماضية ("wurden", "funktionierte")، فنستعملو Präteritum: "musste".\n✓ "musste" = Präteritum من "müssen" (مع "man").\n✗ "muss" = حاضر، والسياق ماضي.\n✗ "müssen" = جمع / Infinitiv، و"Man" مفرد.`,
      rule: "man + 3. Person Singular: muss / musste (Zeitform des Textes)", ex: "Man **musste** lange warten.", exTr: "كان لازم الواحد يستنّى برشا." },
    24: { ok: "noch", type: "adjective_adverb", keyword: "noch + Zeitraum (Rest)", bed: "مازال (باقي)",
      text: `الضمان مازال باقي منو أربعة أشهر: "noch vier Monate".\n✓ "noch" = مازال (الباقي).\n✗ "endlich" = أخيرًا (نهاية انتظار)، موش كمية باقية.\n✗ "schon" = توّا / خلاص (مدّة فاتت أو مفاجأة)، والمقصود الباقي.`,
      rule: "noch + Menge = Rest, der übrig ist  |  schon = früher / mehr als erwartet", ex: "Wir haben **noch** zwei Tage Zeit.", exTr: "مازال عندنا يومين وقت." },
    25: { ok: "deshalb", type: "adjective_adverb", keyword: "deshalb (Folge, im Mittelfeld)", bed: "لهذا السبب",
      text: `نتيجة: الجهاز خربان ← نرجّعو: "Ich schicke Ihnen deshalb das Gerät zurück".\n✓ "deshalb" = لهذا السبب (ظرف نتيجة داخل الجملة).\n✗ "denn" = خاطر (رابط يجي في أول الجملة الجديدة)، وما يجيش بعد الفاعل.\n✗ "weshalb" = وهذا علاش (رابط يفتح Nebensatz والفعل يمشي للآخر)، وهنا الجملة عادية.`,
      rule: "deshalb = Folge (Adverb im Hauptsatz)  |  denn = Konjunktion Position 0  |  weshalb + Nebensatz", ex: "Es regnet, ich nehme **deshalb** einen Schirm mit.", exTr: "تشتي، علهذا نحمل مظلّة." },
    26: { ok: "oder", type: "conjunction", keyword: "entweder … oder", bed: "أو",
      text: `"entweder zu reparieren ___ umzutauschen": اختيار بين شيئين: "entweder … oder".\n✓ "oder" = أو (الجزء الثاني من entweder … oder).\n✗ "sondern" = بل (يصحّح نفي)، وما فماش نفي قبلها.\n✗ "sonst" = وإلا (andernfalls: "Beeil dich, sonst …")، وما تعطيش اختيار بين شيئين.`,
      rule: "entweder … oder = Alternative  |  weder … noch  |  sowohl … als auch", ex: "Wir fahren entweder heute **oder** morgen.", exTr: "نمشيو إمّا اليوم وإمّا غدوة." },
    27: { ok: "um", type: "verb_prep", keyword: "bitten um + Akk.", bed: "نرجوكم (على)",
      text: `"bitten" يتبعو "um" + Akkusativ: "um Erstattung bitten".\n✓ "um" = على (bitten um).\n✗ "für" = لأجل (danken für)، وما تتركّبش مع "bitten".\n✗ "wegen" = بسبب (+ Genitiv)، وما تعبّرش على الشي المطلوب.`,
      rule: "bitten um + Akk.  |  danken für + Akk.", ex: "Ich bitte Sie **um** Verständnis.", exTr: "نرجوكم تتفهّمو." },
    28: { ok: "meine", type: "grammar_structure", keyword: "in + Akk. (Richtung): meine Heimat", bed: "(لـ) وطني",
      text: `"zurückkehren" حركة (Wohin؟) ← "in" + Akkusativ، و"Heimat" مؤنّث: "in meine Heimat".\n✓ "meine" = Akkusativ مؤنّث (حركة نحو).\n✗ "meinem" = Dativ مذكّر / محايد.\n✗ "meiner" = Dativ مؤنّث (مكان بدون حركة: "in meiner Heimat")، وهنا فما رجوع.`,
      rule: "Wechselpräposition: Wohin? → Akk. (in meine Heimat)  |  Wo? → Dat. (in meiner Heimat)", ex: "Ich fahre in **meine** Heimatstadt.", exTr: "نمشي لمدينتي الأم." },
    29: { ok: "mitnehmen", type: "grammar_structure", keyword: "möchte + Infinitiv (mitnehmen)", bed: "نحمل معايا",
      text: `"möchte … gern ___": بعد الفعل المساعد "möchte" الفعل الأساسي في Infinitiv.\n✓ "mitnehmen" = Infinitiv (möchte … mitnehmen).\n✗ "mitgenommen" = Partizip II، وبعد "möchte" نحتاج Infinitiv.\n✗ "mitnehme" = شكل مصرّف غلط، والفعل المصرّف موجود وهو "möchte".`,
      rule: "Modalverb + Infinitiv (ohne zu)", ex: "Ich möchte das Buch gern **mitnehmen**.", exTr: "نحب نحمل الكتاب معايا." },
    30: { ok: "mich", type: "pronoun", keyword: "jdn. benachrichtigen + Akk.", bed: "يعلموني (أنا)",
      text: `"benachrichtigen" فعل متعدّي ياخذ مفعول به (Akkusativ): "mich benachrichtigen".\n✓ "mich" = Akkusativ لـ "ich".\n✗ "mir" = Dativ، و"benachrichtigen" ياخذ Akkusativ.\n✗ "-" (بدون ضمير) = الفعل يحتاج مفعول به، وما ينجّمش يجي بدونو.`,
      rule: "jdn. benachrichtigen / informieren + Akkusativ", ex: "Bitte benachrichtigen Sie **mich** rechtzeitig.", exTr: "بالله أعلمني في الوقت." },
  },
};
