// SB Teil 1 restyle — batch 03: [10] Andrea (Original), [11] Andrea (معدل), [12] Andrea (معدل 2), [13] Autorinnen und Autoren, [14] Familie Geissler oder Dippold
export default {
  // ───────────── [10] Andrea ( Original ) ─────────────
  10: {
    21: { ok: "erst", type: "adjective_adverb", keyword: "erst jetzt", bed: "نرد إلا توّا (متأخر)",
      text: `الاعتذار على التأخير: "نرد توّا فقط" (ما كنتش نجّم قبل). نحتاج "erst jetzt" = إلا توّا (متأخر).\n✓ "erst" = إلا توّا (مش قبل).\n✗ "zuerst" = في الأول (ترتيب)، موش تأخير: "zuerst antworte ich" معناها نرد قبل أي حاجة.\n✗ "gleich" = حالًا / في الحين، وهذا عكس فكرة الاعتذار على التأخير.`,
      rule: "erst = (zu) spät / nicht früher als  |  zuerst = als Erstes  |  gleich = sofort", ex: "Ich habe die Nachricht **erst** jetzt gesehen.", exTr: "ما شفتش الرسالة إلا توّا." },
    22: { ok: "bestens", type: "adjective_adverb", keyword: "bestens", bed: "كلشي يخدم ممتاز",
      text: `نحكيو على جهاز يخدم دوغري توّا: "بشكل ممتاز" = "bestens" (ظرف مثبّت: ممتاز).\n✓ "bestens" = ممتاز / أحسن ما يكون (لوصف حالة موجودة).\n✗ "am besten" = الأفضل (مقارنة بين خيارات: "Es geht am besten so")، موش وصف حالة.\n✗ "bestenfalls" = في أحسن الأحوال / على الأكثر (حد أقصى)، وما تعبّرش على شي يخدم فعلًا.`,
      rule: "bestens = sehr gut  |  am besten = optimal (Superlativ)  |  bestenfalls = höchstens", ex: "Alles läuft **bestens**!", exTr: "كلشي ماشي ممتاز!" },
    23: { ok: "zu", type: "preposition", keyword: "zu uns kommen", bed: "تجي عندنا",
      text: `"kommen" فعل حركة، والوجهة (عندنا) تتحدّد بـ "zu": "zu uns kommen" = تجي لعندنا.\n✓ "zu" = اتجاه نحو شخص أو بيت.\n✗ "bei" = في مكان ثابت بدون حركة ("bei uns wohnen")، موش مع فعل حركة.\n✗ "mit" = مع (مرافقة)، و"mit uns kommen" معناها تجي معانا، موش تجي عندنا.`,
      rule: "zu + Dativ (Ziel / Richtung)  |  bei + Dativ (Ort, ohne Bewegung)", ex: "Komm doch mal **zu** uns!", exTr: "تعالى عندنا مرة!" },
    24: { ok: "aber", type: "conjunction", keyword: "aber (Gegensatz)", bed: "بصح (لكن)",
      text: `"سألت شوية… بصح إنتِ متأخرة": نتيجة معاكسة للأمل، يعني تعارض.\n✓ "aber" = لكن، تعارض بين البحث والنتيجة السلبية (متأخرة).\n✗ "denn" = خاطر (سبب)، والجملة التانية ما تفسّرش علاش سألت.\n✗ "oder" = ولا (اختيار)، وما فماش بدائل في الجملة.`,
      rule: "aber = Gegensatz (Hauptsatz: Verb an Position 2)", ex: "Ich habe gefragt, **aber** niemand weiß etwas.", exTr: "سألت، بصح حتى واحد ما يعرف شي." },
    25: { ok: "besondere", type: "adjective_adverb", keyword: "keine besondere …", bed: "ما يلزمش خبرة خاصة",
      text: `نقولو إنو الوظيفة سهلة: ما يلزمش خبرة "خاصة" (العادية تكفي). تعبير مألوف: "keine besondere + اسم".\n✓ "besondere" = خاصة / استثنائية.\n✗ "geringe" = قليلة: "keine geringe Erfahrung" = خبرة موش قليلة (يعني لازم برشا)، يقلب المعنى.\n✗ "gute" = جيدة: "keine gute Erfahrung" = ما عندوش خبرة مليحة (تقييم سلبي)، موش عدم اشتراط.`,
      rule: "kein + besonder- = nichts Spezielles verlangt", ex: "Dafür braucht man **keine besondere** Ausbildung.", exTr: "ما يلزمش تكوين خاص." },
    26: { ok: "weitere", type: "adjective_adverb", keyword: "eine weitere Fremdsprache", bed: "لغة أجنبية أخرى (زادة)",
      text: `الإنجليزية شرط، و"لغة أخرى" تكون أحسن: يعني لغة زايدة على الأولى = "weitere".\n✓ "weitere" = زايدة / أخرى.\n✗ "künftige" = اللي جايّة في المستقبل (زمن)، موش لغة إضافية.\n✗ "nächste" = الجاية في الترتيب ("der nächste Bus")، موش "لغة زيادة".`,
      rule: "weiter- = zusätzlich / noch ein-", ex: "Ich möchte noch **eine weitere** Sprache lernen.", exTr: "نحب نتعلّم لغة زادة." },
    27: { ok: "bewerben", type: "verb", keyword: "sich bewerben", bed: "تتقدّم للوظيفة",
      text: `"du musst dich …" فيها "dich" (انعكاسي): "sich bewerben" = تتقدّم لوظيفة.\n✓ "bewerben" = sich bewerben (إنتِ اللي تتقدّمي).\n✗ "anwerben" = الشركة هي اللي تجنّد موظفين (تستقطب)، موش إنتِ.\n✗ "umwerben" = يتودّد لشخص باش يكسبو، وما فماش علاقة بالوظيفة.`,
      rule: "sich bewerben (um / bei)  |  anwerben = rekrutieren  |  umwerben = jdn. gewinnen wollen", ex: "Ich will mich bei dieser Firma **bewerben**.", exTr: "نحب نتقدّم لهالشركة." },
    28: { ok: "Leider", type: "adjective_adverb", keyword: "Leider + Verb", bed: "للأسف (ما نعرفش)",
      text: `الجملة تبدا بالفراغ ويجي الفعل "kenne" مباشرة، يعني نحتاج ظرف يعبّر على الأسف: "Leider".\n✓ "Leider" = للأسف (ظرف، والفعل بعدو مباشرة في المرتبة الثانية).\n✗ "Schade" = مؤسف، تتركّب مع "dass" أو "ist es" ("Schade, dass …")، موش مع فعل بعدها مباشرة.\n✗ "Bedauerlich" = صفة (محزن)، تحتاج "ist" ("Bedauerlich ist, dass …")، موش ظرف.`,
      rule: "Leider + Verb (Position 2)  |  Schade, dass … (Nebensatz)", ex: "**Leider** habe ich keine Zeit.", exTr: "للأسف ما عندي وقت." },
    29: { ok: "übrigens", type: "adjective_adverb", keyword: "übrigens", bed: "على فكرة (معلومة جانبية)",
      text: `هنا تبدا فقرة جديدة: تحكي على حاجة تخصّها كمعلومة جانبية، موش نتيجة لجملة قبلها: "على فكرة".\n✓ "übrigens" = على فكرة (تضيف معلومة جديدة).\n✗ "deshalb" = لهذا السبب، تحتاج سبب قبلها، والجملة القبلية ("… sofort für dich eingesetzt") ما تبرّر خدمتها في المخيّم.\n✗ "trotzdem" = رغم ذلك، تحتاج تعارض مع الجملة القبلية، وما فماش.`,
      rule: "übrigens = nebenbei bemerkt (neue Information)", ex: "Ich fahre **übrigens** nächste Woche nach Berlin.", exTr: "على فكرة، نسافر لبرلين الجمعة الجاية." },
    30: { ok: "entschieden", type: "verb", keyword: "sich entscheiden, zu …", bed: "قرّرت (حسمت) إنّي نبقى هنا",
      text: `في الجملة "mich" (انعكاسي) قبل الفراغ: الفعل الانعكاسي هو "sich entscheiden".\n✓ "entschieden" = habe mich … entschieden, zu + Infinitiv.\n✗ "beschlossen" = beschließen فعل غير انعكاسي ("Ich habe beschlossen …")، وما ياخذش "mich".\n✗ "ausgemacht" = اتفقنا على (موعد / شرط)، موش قرار شخصي بـ "mich".`,
      rule: "sich entscheiden + zu-Infinitiv  |  etwas beschließen (ohne sich)", ex: "Ich habe **mich entschieden**, hier zu bleiben.", exTr: "قرّرت نبقى هنا." },
  },

  // ───────────── [11] Andrea (معدل) ───────────── (21,22,23,25,26,27,29,30 reused automatically)
  11: {
    24: { ok: "ziemlich", type: "adjective_adverb", keyword: "ziemlich spät", bed: "متأخرة برشا",
      text: `"spät dran sein" = متأخر. نحتاج ظرف درجة قبل الصفة: "ziemlich spät" = متأخرة برشا.\n✓ "ziemlich" = برشا / إلى حد كبير (ظرف درجة مع صفة).\n✗ "fast" = تقريبًا (ما وصلتش)، يعني "تقريبًا متأخرة"، وما تعبّرش على الوضع الحالي.\n✗ "ungefähr" = تقريبًا (للأرقام والمقادير: "ungefähr fünf")، موش مع صفة مثل "spät".`,
      rule: "ziemlich + Adjektiv = recht / in hohem Maß  |  fast = beinahe", ex: "Es ist schon **ziemlich** spät.", exTr: "الوقت فات برشا." },
    28: { ok: "sonst", type: "adjective_adverb", keyword: "sonst + Konjunktiv II", bed: "وإلا (لو كنت نعرفهم)",
      text: `الجملة الثانية "hätte ich … eingesetzt" Konjunktiv II: كنت نعمل لو كانت الحالة مختلفة. نحتاج رابط معناه "وإلا": "sonst".\n✓ "sonst" = وإلا / لو لا (نتيجة خيالية للحالة المعاكسة).\n✗ "außerdem" = زيادة على ذلك (إضافة)، موش نتيجة معاكسة.\n✗ "damals" = وقتها (ماضي بعيد)، وما فماش إشارة لوقت قديم.`,
      rule: "sonst = andernfalls (Irrealis: …, sonst hätte ich …)", ex: "Ich war krank, **sonst** wäre ich gekommen.", exTr: "كنت مريض، وإلا كنت جيت." },
  },

  // ───────────── [12] Andrea (معدل 2) ───────────── (all gaps except 30 reused automatically)
  12: {
    30: { ok: "ins", type: "fixed_expression", keyword: "ins Ausland", bed: "للخارج",
      text: `"Ausland" (محايد) مع فعل نية الحركة: التعبير الثابت "ins Ausland" = للخارج (in + das).\n✓ "ins" = in + das (اتجاه نحو).\n✗ "ans" = an + das (نحو شاطئ أو حافة: "ans Meer")، وما نقولوش "ans Ausland".\n✗ "beim" = bei + dem (عند / أثناء)، وما يتركّبش هنا.`,
      rule: "ins Ausland (Richtung)  |  im Ausland (Ort)", ex: "Nächstes Jahr gehe ich **ins** Ausland.", exTr: "العام الجاي نمشي للخارج." },
  },

  // ───────────── [13] Autorinnen und Autoren ─────────────
  13: {
    21: { ok: "wie", type: "conjunction", keyword: "wie ihr wisst", bed: "كيما تعرفو كلكم",
      text: `"… ihr alle wisst" = كيما تعرفو كلكم: جملة تذكير بحاجة معروفة، تبدا بـ "wie" (كيما).\n✓ "wie" = كيما (Vergleichssatz مع wissen / sagen).\n✗ "was" = شنوّة / اللي، وما تعطيش معنى "كيما تعرفو" ("was ihr wisst" = اللي تعرفوه).\n✗ "wann" = إمتى (زمن)، موش طريقة أو مصدر معلومة.`,
      rule: "Wie + Subjekt + wissen / sagen = so wie bekannt (كيما)", ex: "**Wie** du weißt, bin ich im Urlaub.", exTr: "كيما تعرف، أنا في عطلة." },
    22: { ok: "vorliegen", type: "verb", keyword: "vorliegen", bed: "تكون موجودة (وصلت)",
      text: `"wenn alle Texte und Bilder …" = لما كل النصوص والصور تكون وصلت. الفعل في الآخر (Nebensatz): "vorliegen".\n✓ "vorliegen" = موجودة / وصلت وجاهزة عند الشخص.\n✗ "unterliegen" = يخضع لـ / يخسر ("dem Gesetz unterliegen")، وما يعطيش معنى "وصلت".\n✗ "liegen lassen" = تتنسّى / تتحط وما تتلمسش، ومعناها عكس "نستنّاو توصل".`,
      rule: "vorliegen = zur Verfügung stehen  |  unterliegen + Dat. = ausgesetzt sein", ex: "Alle Unterlagen müssen **vorliegen**.", exTr: "لازم كل الوثائق تكون موجودة." },
    23: { ok: "im", type: "fixed_expression", keyword: "im Interesse + Genitiv", bed: "في مصلحة الكتّاب",
      text: `التعبير الثابت "im Interesse + Genitiv" = في مصلحة (ويجي بعدو Genitiv: "der Autorinnen und Autoren").\n✓ "im" = in + dem، "im Interesse der …".\n✗ "von" = من / تاع، وما يتركّبش مع "Interesse" في هالتعبير الثابت.\n✗ "ohne" = بدون، ومعناها عكس "في مصلحة".`,
      rule: "im Interesse + Genitiv = zum Vorteil von", ex: "Das ist auch **im** Interesse der Kunden.", exTr: "هذا زادة في مصلحة الحرفاء." },
    24: { ok: "ab", type: "verb", keyword: "abliefern (trennbar)", bed: "سلّموا مقالاتكم في الوقت",
      text: `الفعل "liefern … ab" (abliefern) = يسلّم: فعل منفصل، والبادئة "ab" تروح لآخر الجملة (Imperativ).\n✓ "ab" = Liefert … ab.\n✗ "ein" = "einliefern" (يدخّل شخص للمستشفى أو السجن)، موش تسليم مقالات.\n✗ "zu" = "zuliefern" (يمدّ مصنع بقطع)، وما يتركّبش هنا بمعنى التسليم.`,
      rule: "abliefern: Liefert … ab (trennbares Verb: Präfix am Satzende)", ex: "Bitte liefert die Arbeit rechtzeitig **ab**.", exTr: "سلّموا الخدمة في وقتها." },
    25: { ok: "bei", type: "fixed_expression", keyword: "liegt bei + Dativ", bed: "الحقوق عندكم",
      text: `"das Copyright liegt bei euch" = الحقوق ملك لكم (الملكية والمسؤولية): التعبير "liegen bei + Dativ".\n✓ "bei" = عند (ملكية / مسؤولية).\n✗ "mit" = مع، وما نقولوش "liegt mit euch".\n✗ "für" = لأجل، ويعطي معنى مخالف ("das Copyright liegt für euch" غير مفهوم).`,
      rule: "bei + Dativ liegen = in der Verantwortung / im Besitz von", ex: "Die Entscheidung liegt **bei** dir.", exTr: "القرار عندك." },
    26: { ok: "stark", type: "adjective_adverb", keyword: "stark zurückgehen", bed: "نزلت بقوة (برشا)",
      text: `"zurückgehen" (تنزل) والدرجة نعبّرو عليها بـ "stark" = بقوة.\n✓ "stark" = برشا / بشكل واضح.\n✗ "fest" = ثابت / متين، موش درجة نزول ("fest zurückgehen" غير مألوف).\n✗ "unerschütterlich" = ثابت لا يتزعزع (للمواقف والإيمان)، وما يتركّبش مع الأرقام.`,
      rule: "stark zurückgehen / sinken = deutlich abnehmen", ex: "Die Zahlen sind **stark** zurückgegangen.", exTr: "الأرقام نزلت برشا." },
    27: { ok: "darum", type: "pronoun_adverb", keyword: "bitten um → darum", bed: "نطلب منكم (بهذا الخصوص)",
      text: `الفعل "bitten" يتركّب مع "um" (نطلب حاجة)، والـ Pronominaladverb "darum" (= um das) يعلن على الطلب اللي بعدو "nur Themen zu wählen …".\n✓ "darum" = um das ← "bitten um".\n✗ "deswegen" = لهذا السبب (نتيجة)، وما يتركّبش مع "bitten" كمطلوب.\n✗ "dafür" = لأجل ذلك / مقابل ذلك، و"bitten für" ما هوش التركيب الصحيح للطلب.`,
      rule: "bitten um + Akk. → darum bitten, zu + Infinitiv", ex: "Ich bitte euch **darum**, pünktlich zu sein.", exTr: "نطلب منكم تجيو في الوقت." },
    28: { ok: "ansprechen", type: "verb", keyword: "jdn. ansprechen", bed: "تشدّهم (تهمّهم)",
      text: `"die Themen … sie auch wirklich …": مواضيع تهمّ الأعضاء وتشدّهم: الفعل "ansprechen" (تثير اهتمامهم). والفعل في الآخر (Nebensatz).\n✓ "ansprechen" = تشدّ / تهمّ القرّاء.\n✗ "besprechen" = تناقش (مع الآخرين)، موش تثير الاهتمام.\n✗ "aussprechen" = ينطق / يعبّر ("einen Wunsch aussprechen")، وما يعطيش هالمعنى.`,
      rule: "ansprechen = jdn. interessieren / gefallen", ex: "Das Thema **spricht** die Leser nicht **an**.", exTr: "الموضوع ما يشدّش القرّاء." },
    29: { ok: "dass", type: "conjunction", keyword: "Das heißt nicht, dass …", bed: "هذا ما يعنيش إنّو",
      text: `التعبير "Das heißt nicht, …" يتبعو جملة مفسِّرة بـ "dass" (إنّو).\n✓ "dass" = إنّو (نفس معنى "that").\n✗ "ob" = إذا / هل (سؤال غير مباشر)، وما نسألوش هنا.\n✗ "damit" = باش (هدف)، موش شرح للمعنى.`,
      rule: "Das heißt / bedeutet nicht, dass + Nebensatz", ex: "Das heißt nicht, **dass** wir aufgeben.", exTr: "هذا ما يعنيش إنّا نستسلمو." },
    30: { ok: "als", type: "verb_prep", keyword: "sich verstehen als", bed: "نعتبرو روحنا جريدة مستقلة",
      text: `"sich verstehen als" = يعتبر نفسو / يقدّم نفسو كـ: "als" + اسم (Nominativ).\n✓ "als" = sich als … verstehen.\n✗ "als ob" = كأنّ، تحتاج جملة بفعل ("als ob wir unabhängig wären")، والجملة هنا فيها اسم موش فعل.\n✗ "sowie" = وكذلك (رابط عطف)، وما يعطيش معنى "كـ".`,
      rule: "sich verstehen als + Nominativ = sich sehen als", ex: "Wir verstehen uns **als** neutrale Plattform.", exTr: "نعتبرو روحنا منصة محايدة." },
  },

  // ───────────── [14] Familie Geissler oder Dippold ─────────────
  14: {
    21: { ok: "auf", type: "fixed_expression", keyword: "Antwort auf + Akk.", bed: "الرد على طلبي",
      text: `الاسم "Antwort" يتركّب مع "auf" + Akkusativ (الرد على).\n✓ "auf" = Antwort auf + Akk.\n✗ "von" = من (مصدر)، "Antwort von Ihnen" ممكنة، لكن هنا نحدّدو الموضوع اللي نردّو عليه.\n✗ "wegen" = بسبب + Genitiv ("wegen meiner Bewerbung")، والنص فيه "meine" (Akkusativ).`,
      rule: "Antwort auf + Akk. (Frage / Brief / Bewerbung)", ex: "Danke für deine Antwort **auf** meine Frage.", exTr: "شكرًا على جوابك على سؤالي." },
    22: { ok: "ab", type: "verb", keyword: "abschließen (trennbar)", bed: "نكمّل (نخلّص) دراستي",
      text: `"schließe … meine Schulausbildung …" = نكمّل دراستي: الفعل "abschließen" (منفصل: البادئة "ab" في آخر الجملة).\n✓ "ab" = schließe … ab (نُنهي).\n✗ "zu" = "zuschließen" (يقفل بالمفتاح)، موش يكمّل الدراسة.\n✗ "aus" = "ausschließen" (يستثني / يطرد)، معنى مخالف.`,
      rule: "abschließen: schließe … ab (trennbares Verb)", ex: "Ich schließe im Sommer mein Studium **ab**.", exTr: "نخلّص دراستي في الصيف." },
    23: { ok: "ein bisschen", type: "adjective_adverb", keyword: "ein bisschen verbessern", bed: "نحسّن ألمانيتي شوية",
      text: `هي تحب تحسّن ألمانيتها "شوية زيادة": الكمية الإيجابية "ein bisschen" (شوية).\n✓ "ein bisschen" = شوية / قليلًا (مقدار إيجابي).\n✗ "kaum" = بالكاد (نفي ضمني)، يعني تقريبًا ما تحسّنش، يقلب هدفها.\n✗ "fast" = تقريبًا (ما وصلتش)، وما تعطيش معنى "شوية".`,
      rule: "ein bisschen = ein wenig (Menge)", ex: "Ich möchte mein Deutsch **ein bisschen** verbessern.", exTr: "نحب نحسّن ألمانيتي شوية." },
    24: { ok: "machen", type: "verb", keyword: "einen Kurs machen", bed: "نعمل (نحضر) دورة لغة",
      text: `"einen Sprachkurs … machen" = تحضّر دورة (كطالبة): الفعل المعتاد مع Kurs هو "machen" (أو besuchen).\n✓ "machen" = einen Kurs machen (تشارك في دورة).\n✗ "unterrichten" = تدرّس (كمعلّمة)، وهي طالبة موش معلمة.\n✗ "lernen" = تتعلّم، ما يتركّبش مع "einen Kurs" مباشرة ("eine Sprache lernen"، لكن "einen Kurs machen").`,
      rule: "einen Kurs machen / besuchen  |  einen Kurs geben / unterrichten (als Lehrer)", ex: "Ich **mache** einen Sprachkurs in Berlin.", exTr: "نعمل دورة لغة في برلين." },
    25: { ok: "an", type: "preposition", keyword: "eine Frage an jdn.", bed: "عندي سؤال ليكم",
      text: `السؤال موجّه لشخص: "eine Frage an jemanden" (ليكم إنتم). موضوع السؤال يجي بـ "zu / über".\n✓ "an" = Adressat (الشخص اللي نسألو).\n✗ "über" = موضوع السؤال ("eine Frage über das Wetter")، موش الشخص.\n✗ "für" = لأجل، وما نقولوش "eine Frage für Sie" بمعنى نسألكم.`,
      rule: "eine Frage an + Akk. (Adressat)  |  eine Frage zu / über (Thema)", ex: "Ich habe eine Frage **an** dich.", exTr: "عندي سؤال ليك." },
    26: { ok: "irgendjemandem", type: "pronoun", keyword: "bei irgendjemandem", bed: "عند أي حد",
      text: `"bei … ausleihen" = نستلف عند شخص. بعد "bei" نحتاج شخص في الـ Dativ: "irgendjemandem" (أي حد).\n✓ "irgendjemandem" = Dativ لشخص غير معيّن.\n✗ "irgendwo" = في مكان ما (ظرف)، ما ينجّمش يجي بعد "bei" كشخص.\n✗ "irgendetwas" = أي شي (شيء)، موش شخص نستلف منو.`,
      rule: "bei + Dativ (Person): bei irgendjemandem / bei jemandem", ex: "Kann ich Ski bei **irgendjemandem** ausleihen?", exTr: "نجّم نستلف السكي عند أي واحد؟" },
    27: { ok: "dass", type: "conjunction", keyword: "Danke, dass …", bed: "شكرًا إنكم جاي تاخذوني",
      text: `نشكرو على حاجة: "Danke, dass …" = شكرًا إنّك… (والفعل "kommen" في الآخر).\n✓ "dass" = إنّو (Nebensatz بعد Danke).\n✗ "falls" = في حالة (شرط)، والجملة شكر على فعل أكيد.\n✗ "dafür" = على ذلك (Pronominaladverb)، وما يفتحش جملة بفعل في الآخر بهالشكل.`,
      rule: "Danke, dass + Nebensatz", ex: "Danke, **dass** du mich abholst.", exTr: "شكرًا إنّك جاي تاخذني." },
    28: { ok: "schon", type: "adjective_adverb", keyword: "schon gebucht", bed: "حجزتو ديجا",
      text: `"Ich habe meinen Flug … gebucht": حجز تمّ فعلًا: "schon" = ديجا.\n✓ "schon" = ديجا (عملية انتهت).\n✗ "noch" = لسّا (مع النفي: "noch nicht gebucht")، وهنا مثبت.\n✗ "bevor" = قبل ما (رابط جمل)، موش ظرف في وسط الجملة.`,
      rule: "schon = bereits (Handlung abgeschlossen)", ex: "Ich habe die Tickets **schon** gekauft.", exTr: "اشتريت التذاكر ديجا." },
    29: { ok: "vor", type: "verb", keyword: "vorschlagen (trennbar)", bed: "نقترح",
      text: `"Ich schlage … , dass …" = نقترح إنّو: الفعل "vorschlagen" منفصل (schlage … vor).\n✓ "vor" = schlage … vor (نقترح).\n✗ "zu" = "zuschlagen" (يضرب / يحجز بسرعة)، وما يعطيش معنى الاقتراح.\n✗ "nach" = "nachschlagen" (يراجع في قاموس)، موش نقترح.`,
      rule: "vorschlagen: Ich schlage vor, dass … (trennbares Verb)", ex: "Ich schlage **vor**, dass wir uns morgen treffen.", exTr: "نقترح نتلاقاو غدوة." },
    30: { ok: "mehr", type: "adjective_adverb", keyword: "ein bisschen mehr", bed: "يشوفو شوية أكثر مني",
      text: `هي تبعث صور باش الصغار "يشوفو شوية أكثر مني" قبل ما توصل: الكمية الزائدة "mehr".\n✓ "mehr" = أكثر (ein bisschen mehr).\n✗ "viel" = برشا، و"ein bisschen viel" غير مألوف بهذا المعنى (تناقض: شوية + برشا).\n✗ "weniger" = أقل، عكس الغاية (يعرفوها أكثر قبل ما توصل).`,
      rule: "ein bisschen mehr / weniger = (nur) etwas Zusätzliches", ex: "Ich möchte ein bisschen **mehr** Zeit.", exTr: "نحب شوية وقت أكثر." },
  },
};
