// SB Teil 1 restyle — batch 06: [25] Judith oder Lina, [26] Julian, [27] Meike, [28] Liebe Anna, [29] Herr Wenzel
export default {
  // ───────────── [25] Judith oder Lina ─────────────
  25: {
    21: { ok: "Hoffentlich", type: "adjective_adverb", keyword: "Hoffentlich + Verb", bed: "إن شاء الله (نتمنّى) تقرا",
      text: `الجملة تبدا بالفراغ ويجي الفعل "rufst" مباشرة: نحتاج ظرف يعبّر على أمنية: "Hoffentlich" (إن شاء الله).\n✓ "Hoffentlich" = نتمنّى (Satzadverb، والفعل بعدو في المرتبة الثانية).\n✗ "Zuversichtlich" = متفائل (صفة تصف شخص)، موش ظرف أمنية في أول الجملة.\n✗ "Möglichst" = قدر الإمكان (مع صفة أو فعل: "möglichst bald")، وما تعبّرش على أمنية.`,
      rule: "hoffentlich = ich hoffe, dass … (Satzadverb: Verb an Position 2)", ex: "**Hoffentlich** geht es dir gut.", exTr: "إن شاء الله إنك بخير." },
    22: { ok: "nämlich", type: "adjective_adverb", keyword: "nämlich (Erklärung)", bed: "يعني / خاطر (نحبّو نهديو)",
      text: `الجملة تفسّر سبب الرسالة: "نحبّو بالضبط نهديو…": الظرف التفسيري "nämlich".\n✓ "nämlich" = يعني / خاطر (تفسير).\n✗ "vermutlich" = على الأرجح (توقّع)، وهي تعرف قرارهم: موش تخمين.\n✗ "bestimmt" = أكيد (تأكيد توقّع)، وما تفسّرش السبب.`,
      rule: "nämlich = erklärend (Begründung / Präzisierung)", ex: "Ich komme nicht, ich bin **nämlich** krank.", exTr: "ما نجيش، خاطر مريض." },
    23: { ok: "schon", type: "adjective_adverb", keyword: "schon übermorgen", bed: "توّا بعد غدوة (قريب)",
      text: `الحفلة بعد غدوة: وقت قريب (أقرب مما نتصوّرو): "schon übermorgen".\n✓ "schon" = حتى / توّا (يبيّن إنّ الموعد قريب).\n✗ "fast" = تقريبًا، و"fast übermorgen" معناها قريب من بعد غدوة (غير دقيق).\n✗ "beinahe" = تقريبًا (مثل fast)، نفس المشكل: الموعد دقيق موش تقريب.`,
      rule: "schon + Zeitangabe = früher / näher als erwartet", ex: "Der Test ist **schon** morgen.", exTr: "الاختبار غدوة (قريب برشا)." },
    24: { ok: "damit", type: "pronoun_adverb", keyword: "damit einverstanden, dass …", bed: "موافق على هذا (إنّو نهديو)",
      text: `"einverstanden sein" يتركّب مع "mit": "mit etwas einverstanden sein"، والـ Pronominaladverb "damit" (= mit + das) يعلن على الجملة اللي بعدو ("dass …").\n✓ "damit" = mit + das.\n✗ "dafür" = لأجل ذلك، و"einverstanden dafür" ما هيش تركيب صحيح.\n✗ "dadurch" = بسبب ذلك / عبر ذلك (وسيلة أو سبب)، موش موافقة.`,
      rule: "mit etwas einverstanden sein → damit einverstanden sein, dass …", ex: "Bist du **damit** einverstanden, dass wir früher gehen?", exTr: "موافق إنّو نمشيو بكري؟" },
    25: { ok: "Als", type: "conjunction", keyword: "als (Vergangenheit)", bed: "وقتما جمعنا آخر مرة",
      text: `نتفكّرو حدث واحد صار في الماضي (آخر جمعة فلوس): ماضي مرة وحدة ← "als".\n✓ "Als" = وقتما (ماضي، مرة وحدة).\n✗ "Wenn" = وقتما في الحاضر / المستقبل أو للتكرار، موش حدث ماضي وحيد.\n✗ "Wann" = إمتى (سؤال)، موش رابط زمني.`,
      rule: "als = einmaliges Ereignis in der Vergangenheit  |  wenn = Wiederholung / Zukunft  |  wann = Fragewort", ex: "**Als** ich dort war, regnete es.", exTr: "وقتما كنت هناك، كانت تشتي." },
    26: { ok: "miteinander", type: "adjective_adverb", keyword: "miteinander", bed: "مع بعضنا (جماعة)",
      text: `ميكايل وهي يمشيو يشريو "مع بعضهم": "miteinander" (= mit + einander، معناها مع بعض).\n✓ "miteinander" = مع بعضنا (نشاط مشترك).\n✗ "zueinander" = تجاه بعضنا (علاقة: "nett zueinander")، موش نشاط مشترك.\n✗ "voneinander" = من بعضنا / عن بعضنا ("voneinander lernen")، موش نمشيو مع بعض.`,
      rule: "miteinander = gemeinsam (mit + einander)", ex: "Wir gehen **miteinander** ins Kino.", exTr: "نمشيو مع بعضنا للسينما." },
    27: { ok: "kurz", type: "adjective_adverb", keyword: "kurz vor + Dativ", bed: "قبيل الحفلة بقليل",
      text: `"بقليل قبل الحفلة": "kurz vor der Feier" (kurz + حرف جر زمني).\n✓ "kurz" = بقليل (kurz vor).\n✗ "vor Kurzem" = من مدة قصيرة (ماضي: "Ich war vor Kurzem dort")، موش مستقبل.\n✗ "kürzlich" = مؤخرًا (ماضي)، والإمضاء يصير بعد غدوة (مستقبل).`,
      rule: "kurz vor + Dativ = unmittelbar davor (zeitlich)", ex: "Wir kommen **kurz** vor acht.", exTr: "نجيو قبل الثامنة بقليل." },
    28: { ok: "weshalb", type: "conjunction", keyword: "weshalb + Nebensatz", bed: "وهذا علاش كان عندي برشا خدمة",
      text: `النتيجة جاية بعد السبب (الكلّ في عطلة ← عندي برشا خدمة)، والفعل "hatte" في الآخر: نحتاج رابط ينقل النتيجة في Nebensatz: "weshalb".\n✓ "weshalb" = وهذا علاش (+ فعل في الآخر).\n✗ "deshalb" = لهذا السبب (ظرف)، ياخذ الفعل في المرتبة الثانية ("deshalb hatte ich …")، موش في الآخر.\n✗ "insofern" = بهذا المعنى / من هالناحية (تقييد)، وما تنقلش نتيجة.`,
      rule: "weshalb + Nebensatz (Verb am Ende)  |  deshalb + Hauptsatz (Verb an Position 2)", ex: "Er war krank, **weshalb** er nicht kam.", exTr: "كان مريض، وهذا علاش ما جاش." },
    29: { ok: "vollkommen", type: "adjective_adverb", keyword: "vollkommen neue …", bed: "تطوّرات جديدة كليًّا",
      text: `"vollkommen neue Entwicklungen" = تطوّرات جديدة كليًّا: ظرف يقوّي الصفة "neue".\n✓ "vollkommen" = كليًّا (درجة مع صفة).\n✗ "sämtlich" = كل / جميع (صفة: "sämtliche Mitarbeiter")، وما تقوّيش صفة أخرى.\n✗ "erschöpfend" = شامل / مستنزف ("eine erschöpfende Antwort")، موش درجة "جديد".`,
      rule: "vollkommen + Adjektiv = völlig / ganz", ex: "Das ist **vollkommen** neu für mich.", exTr: "هذا جديد كليًّا عليّ." },
    30: { ok: "angenehmen", type: "adjective_adverb", keyword: "einen angenehmen Tag wünschen", bed: "نهار لطيف (مريح)",
      text: `التمنّي الثابت: "einen angenehmen / schönen Tag wünschen" (نهار لطيف).\n✓ "angenehmen" = لطيف / مريح (الصفة المعتادة مع Tag).\n✗ "passenden" = مناسب (يتماشى مع شي)، وما نقولوش "einen passenden Tag wünschen".\n✗ "bequemen" = مريح (للجلوس أو الملابس)، وما يتركّبش مع "Tag".`,
      rule: "einen angenehmen / schönen Tag wünschen (feste Wendung)", ex: "Ich wünsche dir **einen angenehmen** Abend.", exTr: "نتمنّالك سهرة لطيفة." },
  },

  // ───────────── [26] Julian ─────────────
  26: {
    21: { ok: "konntest", type: "verb", keyword: "konntest (Präteritum, du)", bed: "كنت تنجّم ترتاح",
      text: `الجملة تتبع "du hattest" (ماضي، ضمير "du"): "und konntest dich gut erholen" بنفس الزمن ونفس الضمير.\n✓ "konntest" = Präteritum من können مع "du".\n✗ "können" = Infinitiv / صيغة "wir، sie"، وما يطابقش "du".\n✗ "dürfen" = مسموح لهم / Infinitiv، ما يطابقش الفاعل "du" ولا الزمن.`,
      rule: "Ich hoffe, du hattest … und konntest … (gleiche Zeitform, du-Form)", ex: "Ich hoffe, du hattest Spaß und **konntest** dich erholen.", exTr: "نتمنّى كان عندك متعة وارتحت." },
    22: { ok: "würde", type: "tense", keyword: "würde gern + Infinitiv", bed: "نحب نمشي (أمنية)",
      text: `"gerne mal wieder ans Meer fahren" = أمنية (موش تخطيط أكيد): Konjunktiv II مع "würde".\n✓ "würde" = würde … fahren (أمنية).\n✗ "werden" = Infinitiv / جمع، وما يتماشاش مع "ich".\n✗ "wäre" = Konjunktiv II من sein، وما نقولوش "ich wäre … fahren" (تحتاج Partizip: "wäre gefahren").`,
      rule: "würde (gern) + Infinitiv = Wunsch / höfliche Möglichkeit", ex: "Ich **würde** gern mal nach Italien fahren.", exTr: "نحب نمشي لإيطاليا مرة." },
    23: { ok: "für", type: "preposition", keyword: "Zeit für + Akk.", bed: "ما عنديش وقت للعطلة",
      text: `"Zeit" تتركّب مع "für" + اسم (وقت لـ).\n✓ "für" = Zeit für Urlaub.\n✗ "als" = كـ / من (مقارنة)، وما تتركّبش مع "Zeit" هنا.\n✗ "von" = من (مصدر)، وما نقولوش "Zeit von Urlaub" بمعنى وقت للعطلة.`,
      rule: "Zeit für + Akk. (Zweck)", ex: "Ich habe keine Zeit **für** Hobbys.", exTr: "ما عنديش وقت للهوايات." },
    24: { ok: "vielen", type: "grammar_structure", keyword: "so vielen Jahren", bed: "بعد هالسنين الكثيرة",
      text: `"Jahren" جمع Dativ (بعد "nach")، والكلمة اللي تحدّد الكمية لازم تطابقو: "so vielen" (نهاية Dativ جمع).\n✓ "vielen" = viele في Dativ جمع (so vielen Jahren).\n✗ "viel" = كمية بدون نهاية، تجي مع الأسماء غير المعدودة ("viel Zeit")، موش مع "Jahren".\n✗ "mehr" = أكثر (مقارنة)، وما تتركّبش مع "so" هكا.`,
      rule: "so + viele + Plural (Dativ nach 'nach'): so vielen Jahren", ex: "Nach **so vielen** Jahren sehen wir uns wieder.", exTr: "بعد هالسنين الكثيرة نتلاقاو من جديد." },
    25: { ok: "gefallen", type: "verb", keyword: "gefallen + Dativ (Plural)", bed: "يعجبوني (البيوت)",
      text: `الفاعل "die schönen Fachwerkhäuser" جمع، و"mir" (Dativ) هو اللي يحسّ: "gefallen" (جمع) مع Dativ.\n✓ "gefallen" = جمع (يطابق Fachwerkhäuser).\n✗ "gefällt" = مفرد، وما يطابقش الفاعل الجمع.\n✗ "mögen" = ياخذ Akkusativ ("Ich mag die Häuser")، وما يتركّبش مع "mir" كـ Dativ.`,
      rule: "jdm. gefallen: Verb richtet sich nach dem Subjekt (Plural → gefallen)  |  mögen + Akk.", ex: "Mir **gefallen** die alten Häuser.", exTr: "تعجبني البيوت القديمة." },
    26: { ok: "denn", type: "conjunction", keyword: "denn + Hauptsatz", bed: "خاطر (هناك فما برشا دكاكين)",
      text: `بعد الفاصلة جاي سبب ("dort gibt es viele …") والفعل "gibt" في المرتبة الثانية، يعني Hauptsatz: رابط السبب "denn".\n✓ "denn" = خاطر (يجي قبل جملة رئيسية عادية).\n✗ "als" = وقتما (ماضي) أو كـ (مقارنة)، وما تعطيش سبب.\n✗ "wenn" = إذا / وقتما، وتخلّي الفعل في الآخر، والجملة هنا فعلها في الثانية.`,
      rule: "denn + Hauptsatz (Verb Position 2)  ≠  weil + Nebensatz", ex: "Ich bleibe, **denn** es regnet.", exTr: "نقعد، خاطر تشتي." },
    27: { ok: "wenn", type: "conjunction", keyword: "wenn du willst", bed: "إذا تحب",
      text: `عرض مشروط: "إذا تحب… نوريك المدينة": "Wenn du willst".\n✓ "wenn" = إذا (شرط، والفعل "willst" في آخر الجملة الفرعية).\n✗ "da" = بما إنّو (سبب معروف)، موش شرط.\n✗ "außerdem" = زيادة على ذلك (ظرف)، وما يفتحش جملة فرعية شرطية.`,
      rule: "wenn + Nebensatz = Bedingung (Wenn du willst, …)", ex: "**Wenn** du willst, komme ich mit.", exTr: "إذا تحب، نجي معاك." },
    28: { ok: "dann", type: "adjective_adverb", keyword: "dann + Verb", bed: "وقتها (من بعد) يكون خلص الضغط",
      text: `الجملة تبدا بالفراغ ويجي بعدو الفعل "ist" مباشرة، يعني Hauptsatz بظرف زمني: "dann" (وقتها / وقت زيارتك).\n✓ "dann" = وقتها (ظرف، الفعل في المرتبة الثانية).\n✗ "wenn" = إذا (رابط)، تخلّي الفعل في الآخر، وما تجيش هكا في بداية جملة رئيسية.\n✗ "denn" = خاطر (رابط عطف)، ما يجيش في أول الجملة قبل الفعل بهالمعنى.`,
      rule: "dann = zu diesem Zeitpunkt (Adverb, Verb folgt direkt)", ex: "**Dann** habe ich Zeit.", exTr: "وقتها يكون عندي وقت." },
    29: { ok: "ausgeräumter", type: "adjective_adverb", keyword: "nicht ausgeräumt", bed: "صناديق ما تفرّغتش (ما تخرّجش اللي فيها)",
      text: `نحكيو على صناديق ما خرّجناش اللي فيها بعد (انتقال): الفعل الصحيح لإخراج محتوى الصناديق في الدار "ausräumen" (ويجي هنا كصفة Genitiv جمع "nicht ausgeräumter Kisten").\n✓ "ausgeräumter" = اللي ما خرّجناش حوايجها (Genitiv جمع).\n✗ "entladener" = من "entladen" (يفرّغ حمولة سيارة أو شاحنة)، موش حوايج الصناديق في الدار.\n✗ "entleerter" = من "entleeren" (يفرّغ سائل أو وعاء)، وما يتستعملش لحوايج انتقال.`,
      rule: "ausräumen = Inhalt herausnehmen (Kisten, Schrank)  |  entladen = Fahrzeug leeren  |  entleeren = Behälter leeren", ex: "Die Kisten sind noch nicht **ausgeräumt**.", exTr: "الصناديق مازالت ما تفرّغتش." },
    30: { ok: "weil", type: "conjunction", keyword: "weil + Nebensatz", bed: "خاطر (هي واسعة ووسط المدينة)",
      text: `"Glück gehabt" والسبب "sie geräumig und zentral gelegen ist": سبب (Grund) مع فعل في الآخر.\n✓ "weil" = خاطر (سبب).\n✗ "so dass" = بحيث (نتيجة)، موش سبب: "…، so dass sie geräumig ist" يقلب العلاقة.\n✗ "zu" = إلى / مفرط، وما يربط جملة فرعية بفعل مصرّف.`,
      rule: "weil + Nebensatz (Verb am Ende) = Grund  |  so dass = Folge", ex: "Ich bin glücklich, **weil** ich Urlaub habe.", exTr: "فرحان خاطر عندي عطلة." },
  },

  // ───────────── [27] Meike ─────────────
  27: {
    21: { ok: "neuen", type: "grammar_structure", keyword: "mit deiner neuen Arbeit", bed: "مع خدمتك الجديدة",
      text: `"mit" + Dativ؛ "Arbeit" مؤنث و"deiner" (Dativ مؤنث) قبلها، فالصفة تاخذ النهاية الضعيفة "-en".\n✓ "neuen" = deiner neuen Arbeit (Dativ مؤنث).\n✗ "neue" = نهاية Nominativ / Akkusativ مؤنث، وبعد "mit deiner" نحتاج Dativ.\n✗ "neuer" = نهاية قوية (بدون أداة) أو Nominativ مذكر، وهنا فيه "deiner" قبلها.`,
      rule: "Adjektiv nach Possessivartikel im Dativ Singular (f): -en", ex: "Ich bin zufrieden mit **meiner neuen** Wohnung.", exTr: "راضي على شقتي الجديدة." },
    22: { ok: "Seit", type: "conjunction", keyword: "seit + Nebensatz", bed: "من وقت ما عندي رئيس جديد",
      text: `التغيّر بدا من لحظة معيّنة ومازال: "من وقت ما عندي رئيس جديد": "seit" (حدث ماضي + نتيجة مستمرة).\n✓ "Seit" = من وقت ما (بداية في الماضي، استمرار للآن).\n✗ "Sobald" = أول ما (لحظة مستقبل / تكرار)، موش بداية استمرت.\n✗ "Solange" = طول ما (مدة)، تعني خلال وجود الرئيس، وما تبيّنش بداية التغيير.`,
      rule: "seit(dem) + Nebensatz = von diesem Zeitpunkt an bis jetzt", ex: "**Seit** ich hier wohne, bin ich glücklich.", exTr: "من وقت ما نسكن هنا، فرحان." },
    23: { ok: "darüber", type: "pronoun_adverb", keyword: "nachdenken über → darüber", bed: "فكّرت في هذا (هل…)",
      text: `"nachdenken" يتركّب مع "über" (نفكّر في)، والـ Pronominaladverb "darüber" (= über + das) يعلن على الجملة اللي بعدو ("ob …").\n✓ "darüber" = über + das.\n✗ "daran" = an + das ("denken an" بدون nach)، وما نقولوش "daran nachdenken".\n✗ "darauf" = auf + das ("sich freuen auf")، وما يتركّبش مع "nachdenken".`,
      rule: "nachdenken über + Akk. → darüber nachdenken, ob / wie …", ex: "Ich denke **darüber** nach, ob ich umziehe.", exTr: "نفكّر في هذا، هل نبدّل السكن." },
    24: { ok: "mich", type: "pronoun", keyword: "sich einschreiben", bed: "سجّلت روحي (في الجامعة)",
      text: `الفعل "sich einschreiben" انعكاسي، والفاعل "ich" ← "mich" (Akkusativ).\n✓ "mich" = Reflexivpronomen Akkusativ.\n✗ "mir" = Dativ، والفعل ياخذ Akkusativ هنا.\n✗ "es" = ضمير غير انعكاسي، وما يرجّعش الفعل على "ich".`,
      rule: "sich einschreiben: ich habe mich … eingeschrieben (Akkusativ)", ex: "Ich habe **mich** für den Kurs eingeschrieben.", exTr: "سجّلت روحي في الدورة." },
    25: { ok: "Obwohl", type: "conjunction", keyword: "obwohl + Nebensatz", bed: "رغم إنّو كانت عندي شكوك",
      text: `تناقض: كان عندها شكوك، ومع ذلك فرحانة بالقرار: رابط تنازل.\n✓ "Obwohl" = رغم أنّ (+ فعل في الآخر: "hatte").\n✗ "Damit" = باش (غاية)، موش تناقض.\n✗ "Wenn" = إذا / وقتما، وما تعبّرش عن التنازل.`,
      rule: "obwohl + Nebensatz (Verb am Ende)", ex: "**Obwohl** ich zweifelte, habe ich es gewagt.", exTr: "رغم إنّي شكّيت، جرّبت." },
    26: { ok: "könnte", type: "verb", keyword: "schaffen könnte", bed: "هل نجّم نخلّص (الدراسة)",
      text: `الشك في القدرة: "ob ich … schaffen könnte" = هل ننجّم نخلّص (Konjunktiv II للاحتمال).\n✓ "könnte" = نجّم (قدرة).\n✗ "dürfte" = يمكن (توقّع) / مسموح، وما يعبّرش عن القدرة على النجاح.\n✗ "müsste" = كان لازم (إلزام)، موش شك في القدرة.`,
      rule: "ob + Konjunktiv II (könnte) = zweifelnde Möglichkeit", ex: "Ich war unsicher, ob ich das schaffen **könnte**.", exTr: "ما كنتش متأكد هل نجّم نخلّصها." },
    27: { ok: "wie", type: "grammar_structure", keyword: "nicht so … wie früher", bed: "موش كيما قبل",
      text: `"nicht mehr so leichtfallen … früher": مقارنة تساوي منفية: "nicht so … wie".\n✓ "wie" = nicht so … wie früher.\n✗ "als" = تجي مع صيغة التفضيل ("leichter als früher")، وهنا فيه "so" قبلها.\n✗ "nach" = بعد (زمن / ترتيب)، وما يربط مقارنة مساواة.`,
      rule: "so … wie (Gleichheit, auch verneint: nicht so … wie)  |  Komparativ + als", ex: "Es fällt mir **nicht so** leicht **wie** früher.", exTr: "موش سهل عليّ كيما قبل." },
    28: { ok: "nehmen", type: "verb", keyword: "in Anspruch nehmen", bed: "تاخذ (برشا وقت)",
      text: `التعبير الثابت "Zeit in Anspruch nehmen" = تاخذ وقت. والفاعل "die Vorbereitungen" جمع، والجملة حاضر: "nehmen".\n✓ "nehmen" = جمع، مضارع (die Vorbereitungen nehmen).\n✗ "nimmt" = مفرد، وما يطابقش "die Vorbereitungen".\n✗ "nahmen" = ماضي، والجملة بالحاضر (حقيقة مستمرة).`,
      rule: "in Anspruch nehmen = benötigen; Verb passt zum Subjekt (Plural: nehmen)", ex: "Die Arbeit **nimmt** viel Zeit **in Anspruch**.", exTr: "الخدمة تاخذ برشا وقت." },
    29: { ok: "mich", type: "pronoun", keyword: "für mich", bed: "بالنسبة ليّ",
      text: `"für" يتبعو دايمًا Akkusativ: "für mich".\n✓ "mich" = Akkusativ لـ "ich".\n✗ "mir" = Dativ، وما يجيش بعد "für".\n✗ "mein" = ضمير ملكية (متاعي) يحتاج اسم بعدو، وهنا ما فماش اسم.`,
      rule: "für + Akkusativ: für mich / für dich", ex: "Für **mich** ist das wichtig.", exTr: "بالنسبة ليّ هذا مهم." },
    30: { ok: "denen", type: "pronoun", keyword: "in denen (Relativpronomen)", bed: "اللي فيها (في مجموعات الدردشة)",
      text: `نرجعو لـ "Chatgruppen" (جمع): "اللي فيها" ← حرف الجر "in" + ضمير وصل جمع Dativ: "denen".\n✓ "denen" = Relativpronomen جمع Dativ.\n✗ "der" = مؤنث مفرد Dativ، موش جمع.\n✗ "die" = جمع Nominativ / Akkusativ، وبعد "in" بمعنى المكان نحتاج Dativ.`,
      rule: "Präposition + Relativpronomen: Plural Dativ = denen", ex: "Das sind Gruppen, in **denen** man Fragen stellt.", exTr: "هذي مجموعات يسألو فيها." },
  },

  // ───────────── [28] Liebe Anna ───────────── (23, 25, 27, 29 reused automatically)
  28: {
    21: { ok: "vergangen", type: "verb", keyword: "ist … vergangen, seit …", bed: "مرّ نصف سنة (من آخر مرة)",
      text: `"ist … seit" ← "ist … vergangen" (Perfekt من vergehen بـ sein): مرّ كذا من وقت…\n✓ "vergangen" = Partizip II (ist vergangen).\n✗ "vergingen" = Präteritum مصرّف (جمع)، وما يجيش بعد "ist" كـ Partizip.\n✗ "vergehend" = Partizip I (جاري / فاني)، وما يكوّنش Perfekt بعد "ist".`,
      rule: "Zeit ist vergangen, seit … (sein + Partizip II von vergehen)", ex: "Es ist ein Jahr **vergangen**, seit wir uns sahen.", exTr: "مرّت سنة من آخر مرة شفنا بعض." },
    22: { ok: "plötzlich", type: "adjective_adverb", keyword: "plötzlich erkrankt", bed: "مرضت فجأة",
      text: `"ausgerechnet jetzt … erkrankt" = مرضت في أسوأ وقت وفجأة: الظرف "plötzlich" (فجأة، بدون إنذار).\n✓ "plötzlich" = فجأة.\n✗ "gleich" = في الحين / بعد شوية (زمن قريب)، موش مفاجأة.\n✗ "sofort" = حالًا (فورًا)، تتركّب مع أفعال تنفيذ، وما تعطيش معنى مرض مفاجئ.`,
      rule: "plötzlich = unerwartet  |  gleich / sofort = in der nächsten Minute", ex: "Er ist **plötzlich** krank geworden.", exTr: "مرض فجأة." },
    24: { ok: "zwar", type: "grammar_structure", keyword: "zwar … aber", bed: "هي لطيفة صحيح، بصح…",
      text: `"ist zwar sehr nett, aber …" = صحيح لطيفة، بصح…: "zwar" تفتح التنازل و"aber" تكمّلو.\n✓ "zwar" = صحيح (تنازل، وبعدو "aber").\n✗ "sondern" = بل (بعد نفي: "nicht …, sondern …")، وما فماش نفي قبلها.\n✗ "sowohl" = كل من (تحتاج "als auch")، موش تنازل.`,
      rule: "zwar … aber = Zugeständnis + Gegensatz", ex: "Das Essen ist **zwar** gut, aber teuer.", exTr: "الماكلة مليحة صحيح، بصح غالية." },
    26: { ok: "Darauf", type: "pronoun_adverb", keyword: "darauf (freuen auf)", bed: "عليها (الراحة) فرحان برشا",
      text: `"sich freuen" يتركّب مع "auf": الـ Pronominaladverb "Darauf" (= auf + das) يرجع للراحة اللي ذكرناها.\n✓ "Darauf" = auf + das ("freuen auf").\n✗ "Damit" = بذلك / باش، وما يتركّبش مع "sich freuen" هكا.\n✗ "Davon" = منها / عن ذلك (von + das)، وما نقولوش "sich davon freuen".`,
      rule: "sich freuen auf + Akk. → darauf", ex: "**Darauf** freue ich mich schon lange.", exTr: "عليها فرحان من بكري." },
    28: { ok: "auf", type: "fixed_expression", keyword: "auf der Nase herumtanzen", bed: "يتلاعبو بيك",
      text: `تعبير ثابت (idiom): "jemandem auf der Nase herumtanzen" = ما يحترموك ويعملو اللي يحبّو. حرف الجر الثابت "auf".\n✓ "auf" = auf der Nase herumtanzen.\n✗ "an" = على / عند، وما يجوزش في التعبير.\n✗ "in" = داخل، وما فماش "in der Nase herumtanzen".`,
      rule: "jdm. auf der Nase herumtanzen (Idiom) — Präposition: auf", ex: "Die Kinder tanzen dem Babysitter **auf** der Nase herum.", exTr: "الصغار يتلاعبو بالبيبي سيتر." },
    30: { ok: "zurechtkommst", type: "grammar_structure", keyword: "Nebensatz: trennbares Verb am Ende", bed: "كيفاش تتعامل معاهم",
      text: `بعد "wie" نحتاج Nebensatz: الفعل المتصرّف يروح للآخر ويتّحد مع البادئة ("zurechtkommst" كلمة وحدة). والضمير "du" يطلب "-st" والزمن حاضر.\n✓ "zurechtkommst" = فعل مصرّف مع "du" في الحاضر، في الآخر.\n✗ "zurechtkamst" = Präteritum (ماضي)، والجملة على الحاضر ("Du hast gute Ideen").\n✗ "zurechtzukommen" = Infinitiv مع zu، وما يصحّش كفعل مصرّف في Nebensatz بعد "du".`,
      rule: "Nebensatz: trennbares Verb bleibt zusammen am Ende (zurechtkommst)", ex: "Ich weiß, wie du damit **zurechtkommst**.", exTr: "نعرف كيفاش تتعامل مع هذا." },
  },

  // ───────────── [29] Herr Wenzel ─────────────
  29: {
    21: { ok: "für", type: "fixed_expression", keyword: "Dank für + Akk.", bed: "شكرًا على استفساركم",
      text: `"Dank" يتركّب مع "für" + Akkusativ (شكرًا على).\n✓ "für" = Dank für + Akk.\n✗ "auf" = على (مع الرد: "Antwort auf")، موش مع "Dank".\n✗ "wegen" = بسبب + Genitiv، وما نقولوش "Dank wegen Ihre Anfrage".`,
      rule: "danken / Dank für + Akk.", ex: "Vielen Dank **für** Ihre Hilfe.", exTr: "شكرًا على مساعدتكم." },
    22: { ok: "jeweils", type: "adjective_adverb", keyword: "jeweils am …", bed: "في كل مرة (دايمًا) يوم الاثنين الأول",
      text: `نحدّدو الموعد في كل شهر: "jeweils am ersten Montag" = في كل مرة يوم الاثنين الأول.\n✓ "jeweils" = كل مرة / في كل حالة (ظرف).\n✗ "jeden" = كل (مذكر Akkusativ) يحتاج اسم بعدو ("jeden Monat")، وما يتركّبش قبل "am".\n✗ "jedoch" = لكن (تعارض)، وما فماش تعارض.`,
      rule: "jeweils = jedes Mal / in jedem einzelnen Fall", ex: "Der Kurs findet **jeweils** montags statt.", exTr: "الدورة تكون كل مرة يوم الاثنين." },
    23: { ok: "gewidmet", type: "fixed_expression", keyword: "etwas (Dat.) gewidmet sein", bed: "مخصّص لجانب ثقافي",
      text: `كل سهرة مخصّصة لجانب ثقافي معيّن: "einem Aspekt gewidmet" (مكرّسة له).\n✓ "gewidmet" = مخصّص / مكرّس (Dativ: einem Aspekt).\n✗ "geeignet" = مناسب (يحتاج "für": "geeignet für")، وهنا Dativ بدون حرف جر.\n✗ "gedacht" = مفكّر فيه (يتركّب مع "für / als")، وما يركّبش مع Dativ مباشرة بهالمعنى.`,
      rule: "(einer Sache) gewidmet sein = ausschließlich dafür bestimmt", ex: "Der Abend ist der Musik **gewidmet**.", exTr: "السهرة مخصّصة للموسيقى." },
    24: { ok: "vorbereitende", type: "grammar_structure", keyword: "mehrere vorbereitende Treffen", bed: "عدّة لقاءات تحضيرية",
      text: `الصفة "vorbereitend" (Partizip I: تحضيري) بعد "mehrere" (جمع بدون أداة) تاخذ نهاية قوية "-e".\n✓ "vorbereitende" = mehrere vorbereitende Treffen (Akkusativ جمع).\n✗ "vorbereitend" = بدون نهاية، وما تجيش قبل اسم جمع.\n✗ "vorbereiteten" = نهاية Dativ / بعد أداة معرّفة، وهنا Akkusativ جمع بدون أداة.`,
      rule: "nach mehrere / einige (Plural, ohne Artikel): Adjektiv / Partizip I -e", ex: "Wir haben **mehrere vorbereitende** Treffen.", exTr: "عندنا عدّة لقاءات تحضيرية." },
    25: { ok: "meisten", type: "adjective_adverb", keyword: "die meisten + Genitiv", bed: "لأغلب أعضائنا",
      text: `"für die … unserer Mitglieder" = لأغلب أعضائنا: "die meisten" (صيغة التفضيل من viel، كاسم جمع).\n✓ "meisten" = die meisten (أغلب).\n✗ "am meisten" = أكثر شي (ظرف مع فعل: "Er arbeitet am meisten")، وما يجيش قبل Genitiv كمجموعة.\n✗ "meistens" = غالبًا (تكرار)، موش كمّ من الأشخاص.`,
      rule: "die meisten + Genitiv / von = der größte Teil", ex: "Die **meisten** meiner Freunde kommen.", exTr: "أغلب أصدقائي يجيو." },
    26: { ok: "entlang", type: "preposition", keyword: "entlang + Genitiv", bed: "على طول (مسار) الشعراء",
      text: `الرحلة تمشي على طول مسار الشعراء الألمان: حرف الجر "entlang" (+ Genitiv قبل الاسم).\n✓ "entlang" = على طول.\n✗ "gegenüber" = مقابل / تجاه (+ Dativ)، وما يعطيش معنى تتبّع المسار.\n✗ "während" = أثناء (زمن)، موش مسار مكاني.`,
      rule: "entlang + Genitiv (vor dem Nomen) / + Akkusativ (nach dem Nomen)", ex: "Wir fahren **entlang** der Küste.", exTr: "نسافرو على طول الساحل." },
    27: { ok: "auf", type: "fixed_expression", keyword: "auf den Spuren + Genitiv", bed: "على خطى تشايكوفسكي",
      text: `التعبير الثابت "auf den Spuren + Genitiv" = على خطى (تتبّع أثر شخص).\n✓ "auf" = auf den Spuren.\n✗ "hinter" = وراء (مكان)، و"hinter den Spuren" ما هيش تعبير ثابت.\n✗ "neben" = جنب، وما يعطيش معنى تتبّع الأثر.`,
      rule: "auf den Spuren + Genitiv = in jemandes Fußstapfen", ex: "Wir reisen **auf** den Spuren Goethes.", exTr: "نسافرو على خطى غوته." },
    28: { ok: "deren", type: "pronoun", keyword: "mit deren Hilfe", bed: "اللي بمساعدتهم",
      text: `نرجعو لـ "Wissenschaftlern" (جمع): "اللي بمساعدتهم" ← ضمير ملكية في Genitiv جمع: "deren".\n✓ "deren" = Genitiv جمع (der Wissenschaftler = deren).\n✗ "dessen" = Genitiv مذكر / محايد مفرد، وما يطابقش الجمع.\n✗ "der" = Dativ / Genitiv مؤنث، وما يطابقش الجمع.`,
      rule: "Relativpronomen im Genitiv: dessen (m/n)  |  deren (f/Plural)", ex: "Das sind Experten, mit **deren** Hilfe wir lernen.", exTr: "هذولا خبراء، بمساعدتهم نتعلّمو." },
    29: { ok: "sofern", type: "conjunction", keyword: "sofern + Nebensatz", bed: "بشرط إنّو يكون ممكن تنظيميًا",
      text: `الاستبدال يتعمل بشرط: "إذا / بشرط إنّو يكون ممكن تنظيميًا" والفعل "ist" في الآخر.\n✓ "sofern" = بشرط (رابط شرط).\n✗ "sogar" = حتى (مفاجأة، ظرف)، وما يفتحش جملة فرعية.\n✗ "sogleich" = حالًا (ظرف زمن)، موش شرط.`,
      rule: "sofern = falls / vorausgesetzt, dass (Bedingung, Nebensatz)", ex: "Sie bekommen Ihr Geld zurück, **sofern** Sie die Quittung haben.", exTr: "ترجعولكم فلوسكم بشرط عندكم الوصل." },
    30: { ok: "erreichbar", type: "adjective_adverb", keyword: "erreichbar sein", bed: "مفتوح (تنجّمو توصلولنا)",
      text: `نحكيو على أوقات الاتصال بالمكتب: الصفة "erreichbar" (تنجّم توصلو).\n✓ "erreichbar" = متاح للتواصل / الوصول.\n✗ "erhältlich" = يتباع / نلقاو (منتج)، موش مكتب.\n✗ "wirksam" = فعّال (دواء، إجراء)، وما يعطيش معنى التواصل.`,
      rule: "erreichbar = man kann sie kontaktieren  |  erhältlich = kaufbar", ex: "Das Büro ist montags **erreichbar**.", exTr: "المكتب تنجّم تتواصل معاه الاثنين." },
  },
};
