// SB Teil 1 restyle — batch 13 (last): [59] Liebe Clara, [60] Liebe Clara (معدل), [61] Lieber Thomas, [62] Hallo Jakob
export default {
  // ───────────── [59] Liebe Clara — 21, 24, 27, 28 from [32] via the store ─────────────
  59: {
    22: { ok: "durch", type: "preposition", keyword: "Rundreise durch + Akk.", bed: "جولة عبر (أوروبا)",
      text: `جولة تمرّ بعدّة أماكن: "Rundreise durch Europa".\n✓ "durch" = عبر (حركة بين عدّة أماكن، + Akkusativ).\n✗ "über" = فوق / عبر نقطة معيّنة ("über Brüssel")، و"Rundreise über Europa" ما تتقالش.\n✗ "in" = في (مكان ثابت): "Reise in Europa" ممكنة، بصح "Rundreise" تعبّر على حركة عبر أماكن، وتتبعها "durch".`,
      rule: "Rundreise durch + Akk. (Land / Kontinent)", ex: "Sie machen eine Rundreise **durch** Spanien.", exTr: "يعملو جولة في إسبانيا." },
    23: { ok: "Wie", type: "fixed_expression", keyword: "wie du weißt", bed: "كيما تعرف",
      text: `تذكير بمعلومة معروفة: "Wie du weißt, …".\n✓ "Wie" = كيما (so wie du weißt).\n✗ "Als" = وقتما (حدث ماضي)، وما تتركّبش قبل "du weißt".\n✗ "Wenn" = إذا (شرط)، و"Wenn du weißt" معناها لو تعرف، موش تذكير بحاجة معروفة.`,
      rule: "wie + du weißt / siehst / sagst = so wie (Einschub)", ex: "**Wie** du siehst, ist es spät.", exTr: "كيما تشوف، الوقت تأخّر." },
    25: { ok: "es", type: "pronoun", keyword: "es ist ruhiger (unpersönliches es)", bed: "الجوّ (أهدى)",
      text: `نحكيو على الجوّ العام في الشركة، وما فماش فاعل معيّن: "es" الشكلي.\n✓ "es" = ضمير غير شخصي (es ist ruhiger).\n✗ "er" = مذكّر معيّن، وما فماش مذكّر في الجملة.\n✗ "man" = الواحد، والمقصود جوّ الشركة موش الأشخاص.`,
      rule: "es als Subjekt bei Atmosphäre / Zustand (es ist ruhig, es ist laut)", ex: "Am Abend ist **es** hier ruhig.", exTr: "في العشية الجوّ هنا هادئ." },
    26: { ok: "erste", type: "grammar_structure", keyword: "meine erste Station (Endung -e)", bed: "أول",
      text: `"Station" مؤنّث وNominativ، وبعد "Meine" الصفة الترتيبية تاخذ -e: "Meine erste Station".\n✓ "erste" = -e (Possessiv + Femininum Nominativ).\n✗ "ersten" = -en (Dativ / جمع / Akkusativ مذكّر)، موش Nominativ مؤنّث.\n✗ "erst" = ظرف (nur / zuerst)، موش صفة ترتيبية قبل اسم.`,
      rule: "Possessiv + Femininum Nominativ → Adjektiv + -e (meine erste Station)", ex: "Das war meine **erste** Stunde.", exTr: "هذي كانت أول حصّة ليّ." },
    29: { ok: "mir", type: "pronoun", keyword: "jdm. kommt ein Gedanke", bed: "خطرت ببالي",
      text: `"kam mir der Gedanke" = خطرت فكرة ببالي: الشخص في Dativ.\n✓ "mir" = Dativ (kam mir der Gedanke).\n✗ "bei" = حرف جر، وما يعوّضش ضمير Dativ مباشر بعد "kam".\n✗ "in" = حرف جر، و"kam in der Gedanke" ما تتقالش.`,
      rule: "jdm. kommt ein Gedanke / eine Idee (Dativ der Person, ohne Präposition)", ex: "Plötzlich kam **mir** eine Idee.", exTr: "فجأة جاتني فكرة." },
    30: { ok: "könnte", type: "tense", keyword: "könnte (Konjunktiv II: Gedanke)", bed: "نجّم (نبدا)",
      text: `فكرة خيالية على المستقبل: "ich … etwas ganz Neues anfangen könnte" (ربما نجّم).\n✓ "könnte" = Konjunktiv II من "können" (إمكانية).\n✗ "bräuchte" = نحتاج (Konjunktiv II من brauchen)، وما يتركّبش مع "anfangen" بدون "zu".\n✗ "dürfte" = مسموحلي (إذن)، والسياق خاطرة شخصية موش تصريح.`,
      rule: "Konjunktiv II von können: könnte = Möglichkeit / Gedanke", ex: "Ich **könnte** morgen früher kommen.", exTr: "نجّم نجي بكري غدوة." },
  },

  // ───────────── [60] Liebe Clara (معدل) — 28 from [32]; 29, 30 via [59] ─────────────
  60: {
    21: { ok: "dass", type: "conjunction", keyword: "es ist lange her, dass …", bed: "إنّو (آخر مرة)",
      text: `"wie lange es schon her ist, ___ wir zuletzt … gehört haben": تعبير "es ist … her, dass".\n✓ "dass" = إنّو (es ist lange her, dass …).\n✗ "als" = وقتما: ممكنة في الكلام اليومي، بصح التعبير المعتمد بعد "her ist" هو "dass".\n✗ "wenn" = إذا / كلّما (شرط أو تكرار)، والكلام على مرّة وحدة فاتت.`,
      rule: "es ist (lange) her, dass + Nebensatz", ex: "Es ist lange her, **dass** wir uns gesehen haben.", exTr: "من برشا ما شفناش بعضنا." },
    22: { ok: "konnte", type: "verb", keyword: "konnte (Möglichkeit, Präteritum)", bed: "نجّمت",
      text: `"sehr viel gearbeitet und ___ mir nur selten freinehmen": ما كانتش عندها إمكانية (بسبب الشغل).\n✓ "konnte" = Präteritum من "können" (إمكانية).\n✗ "durfte" = مسموحلي (إذن): ممكنة نحويًّا، بصح السبب هنا الشغل الكثير موش منع من حدّ.\n✗ "wusste" = عرفت، و"wusste mir freinehmen" ما تتركّبش.`,
      rule: "können = Möglichkeit  |  dürfen = Erlaubnis  |  wissen + dass / wie", ex: "Ich **konnte** nicht kommen, ich hatte keine Zeit.", exTr: "ما نجّمتش نجي، ما كانش عندي وقت." },
    23: { ok: "musste", type: "verb", keyword: "musste (Notwendigkeit)", bed: "لازمني",
      text: `"unbedingt mal eine längere Pause einlegen" = ضرورة بعد الضغط: "musste".\n✓ "musste" = لازمني (Präteritum من müssen).\n✗ "durfte" = مسموحلي، وهنا الكلام على حاجة ملحّة موش إذن.\n✗ "sollte" = المفروض (نصيحة أو أمر من آخر)، والضرورة هنا من الوضع نفسو.`,
      rule: "müssen = Notwendigkeit  |  dürfen = Erlaubnis  |  sollen = Auftrag / Empfehlung", ex: "Ich **musste** unbedingt mal ausruhen.", exTr: "لازمني بالضرورة نرتاح شوية." },
    24: { ok: "aber", type: "conjunction", keyword: "aber (Gegensatz, Position 0)", bed: "لكن",
      text: `"زعمو ما كانش متحمّس… لكن في الآخر نجّمت نقنعو": تعارض، و"aber" ما تأثّرش على ترتيب الفعل.\n✓ "aber" = لكن (Position 0، "am Ende konnte ich" عادي).\n✗ "sondern" = بل (يصحّح نفي مباشر)، وهنا ما فماش تصحيح لنفس العنصر.\n✗ "trotzdem" = رغم ذلك (ظرف)، ياخذ الفعل مباشرة بعدو، وهنا بعدو "am Ende".`,
      rule: "aber = Gegensatz (Position 0)  |  sondern nach Verneinung  |  trotzdem + Verb Position 2", ex: "Er war müde, **aber** er kam trotzdem.", exTr: "كان تعبان، لكن جا رغم هذا." },
    25: { ok: "denn", type: "conjunction", keyword: "denn + Hauptsatz", bed: "خاطر",
      text: `"ich fliege ja nicht sehr gerne": الفعل "fliege" في المرتبة الثانية، يعني Hauptsatz: رابط السبب "denn".\n✓ "denn" = خاطر (+ جملة رئيسية، الفعل في المرتبة الثانية).\n✗ "weil" = خاطر لكن الفعل يمشي للآخر ("weil ich nicht gerne fliege")، وهنا "fliege" في الثانية.\n✗ "obwohl" = رغم إنّو (تنازل)، والمنطق هنا سبب.`,
      rule: "denn + Hauptsatz (Verb Position 2)  ≠  weil + Nebensatz (Verb am Ende)", ex: "Ich bleibe zu Hause, **denn** ich bin müde.", exTr: "نقعد في الدار، خاطر تعبان." },
    26: { ok: "dann", type: "adjective_adverb", keyword: "dann (zeitliche Abfolge)", bed: "وبعدين",
      text: `ترتيب المحطّات: أمستردام، وبعدين بروكسل: "dann ging es …" (ظرف زمني، الفعل في الثانية).\n✓ "dann" = وبعدين (تسلسل).\n✗ "damit" = باش (رابط غرض + فعل في الآخر)، وهنا "ging" في الثانية.\n✗ "dort" = هناك (مكان)، موش تسلسل زمني.`,
      rule: "dann = zeitliche Abfolge (Verb Position 2)  |  damit = Zweck  |  dort = Ort", ex: "Zuerst essen wir, **dann** gehen wir spazieren.", exTr: "الأول نأكلو، وبعدين نتمشّاو." },
    27: { ok: "möchte", type: "verb", keyword: "möchte gar nicht daran denken", bed: "نحب (ما نفكّرش)",
      text: `"ich ___ gar nicht daran denken" = ما نحبّش حتى نفكّر: "möchte".\n✓ "möchte" = نحب (Konjunktiv II من mögen، المعتاد).\n✗ "darf" = مسموحلي، وما تتماشاش مع "gar nicht daran denken".\n✗ "mag" = نحب: "Ich mag nicht daran denken" ممكنة في الكلام اليومي، بصح الصيغة المعتادة هنا "möchte".`,
      rule: "möchte (nicht) + Infinitiv = höfliche Form von wollen", ex: "Ich **möchte** gar nicht daran denken.", exTr: "ما نحبّش حتى نفكّر في هذا." },
  },

  // ───────────── [61] Lieber Thomas — 21, 22, 24, 26, 29, 30 from [24] via the store ─────────────
  61: {
    23: { ok: "wollte", type: "verb", keyword: "wollte (Absicht) … aber", bed: "حبّيت",
      text: `"Ich wollte es mir schon anders überlegen, aber Lisa …": نيّة ما تحقّقتش، والـ "aber" تكمّل.\n✓ "wollte" = حبّيت (Präteritum من wollen، نيّة).\n✗ "konnte" = نجّمت: "Ich konnte es mir anders überlegen" ممكنة، بصح "aber Lisa wollte nichts hören" تعبّر على نيّة موش قدرة.\n✗ "sollte" = المفروض، موش نيّة شخصية.`,
      rule: "wollen im Präteritum = Absicht (oft + aber = nicht verwirklicht)", ex: "Ich **wollte** gehen, aber es regnete.", exTr: "حبّيت نمشي بصح كانت تشتي." },
    25: { ok: "Einerseits... ...andererseits", type: "conjunction", keyword: "einerseits … andererseits", bed: "من ناحية… ومن ناحية أخرى",
      text: `شعورين متوازيين: توتّر وفرحة: "Einerseits war ich aufgeregt, andererseits habe ich mich gefreut".\n✓ "Einerseits... ...andererseits" = من ناحية… ومن ناحية أخرى.\n✗ "Weder...noch" = لا… ولا (نفي)، والجملتين إيجابيتين.\n✗ "Zwar...aber" = صحيح… لكن (تنازل / تعارض)، والشعورين هنا متوازيين موش متعارضين.`,
      rule: "einerseits … andererseits = zwei Seiten einer Sache  |  zwar … aber  |  weder … noch", ex: "**Einerseits** ist es teuer, **andererseits** ist es bequem.", exTr: "من ناحية غالي، ومن ناحية أخرى مريح." },
    27: { ok: "auszusuchen", type: "grammar_structure", keyword: "helfen + zu-Infinitiv (auszusuchen)", bed: "باش نختار",
      text: `"hat mir geholfen, im Sportgeschäft Schuhe … ___": جملة طويلة بمفاعيل، فنستعملو "zu" داخل الفعل المنفصل: "auszusuchen".\n✓ "auszusuchen" = aus + zu + suchen.\n✗ "aussuchen" = Infinitiv بدون "zu": "helfen" تقبلها في جمل قصيرة، بصح هنا الجملة طويلة.\n✗ "ausgesucht" = Partizip II، وما تتركّبش بعد "geholfen".`,
      rule: "helfen + zu-Infinitiv (trennbar: auszusuchen, aufzuräumen)", ex: "Er hilft mir, ein Geschenk **auszusuchen**.", exTr: "يعاوني نختار هديّة." },
    28: { ok: "grundlegende", type: "grammar_structure", keyword: "einige + Adjektiv-e (Plural)", bed: "أساسية",
      text: `بعد "einige" الصفة تاخذ -e في Akkusativ جمع: "einige grundlegende Dinge".\n✓ "grundlegende" = -e (Akkusativ جمع بعد einige).\n✗ "grundlegenden" = -en تجي بعد أداة معرّفة أو في Dativ.\n✗ "grundlegender" = Nominativ مذكّر أو Genitiv جمع، موش Akkusativ جمع.`,
      rule: "einige / viele / wenige + Adjektiv + -e (Plural Nom. / Akk.)", ex: "Sie hat einige **wichtige** Tipps gegeben.", exTr: "عطات شوية نصايح مهمّة." },
  },

  // ───────────── [62] Hallo Jakob ─────────────
  62: {
    21: { ok: "mal", type: "adjective_adverb", keyword: "sich mal melden", bed: "(أخيرًا) مرّة",
      text: `"Endlich melde ich mich mal bei dir": "mal" تلطّف وتعبّر على مرّة بعد انقطاع.\n✓ "mal" = مرّة (Abtönungspartikel).\n✗ "halt" = بكل بساطة (تعبير عن شي ما يتبدّلش: "Es ist halt so")، وما تتماشاش هنا.\n✗ "ja" = كيما تعرف: ممكنة، بصح "ja" تذكّر بحاجة معروفة، موش تعبّر على كسر انقطاع.`,
      rule: "mal (unbetont) = einmal; mildert Aussagen / Aufforderungen", ex: "Ich melde mich **mal** bei dir.", exTr: "باش نعطيك خبر مرّة." },
    22: { ok: "als", type: "preposition", keyword: "Stelle als + Beruf", bed: "كـ (ممرّض)",
      text: `المهنة تتذكر بـ "als": "eine Stelle als Krankenpfleger".\n✓ "als" = كـ (Stelle als + Beruf).\n✗ "für" = لـ: "Stelle für Krankenpfleger" ممكنة (وظيفة موجّهة لممرّضين)، بصح هو يتكلّم على وظيفتو هو.\n✗ "von" = من، وما تتركّبش مع "Stelle … Krankenpfleger".`,
      rule: "Stelle / Job als + Beruf", ex: "Sie hat eine Stelle **als** Lehrerin gefunden.", exTr: "لقات خدمة كمعلّمة." },
    23: { ok: "verschiedenen", type: "grammar_structure", keyword: "aus ganz verschiedenen Ländern", bed: "مختلفة (بلدان)",
      text: `"aus" + Dativ جمع: "ganz verschiedenen Ländern" (صفة + -en).\n✓ "verschiedenen" = Dativ جمع (-en).\n✗ "viele" = "aus ganz viele Ländern" ما تتقالش (تحتاج Dativ: "vielen").\n✗ "Vielerlei" = أنواع كثيرة (بدون نهاية، "vielerlei Länder")، وما تتركّبش مع "ganz".`,
      rule: "aus + Dativ Plural: Adjektiv -en (aus verschiedenen Ländern)", ex: "Wir kommen aus ganz **verschiedenen** Städten.", exTr: "نجيو من مدن مختلفة تمامًا." },
    24: { ok: "sich", type: "pronoun", keyword: "sich auskennen", bed: "يعرفو الطريق",
      text: `"sich in Hamburg auskennen": فعل انعكاسي، والفاعل "sie" (الزملاء): "sie kennen sich aus".\n✓ "sich" = انعكاسي للغائب جمع.\n✗ "mich" = انعكاسي لـ "ich"، والفاعل "sie".\n✗ "mir" = Dativ لـ "ich"، و"sich auskennen" يستعمل Akkusativ.`,
      rule: "reflexives Verb: sie → sich (sich auskennen in + Dat.)", ex: "Er kennt **sich** in der Stadt gut aus.", exTr: "يعرف المدينة مليح." },
    25: { ok: "zwar", type: "conjunction", keyword: "zwar … aber (Zugeständnis)", bed: "صحيح",
      text: `"Die Miete ist zwar ein bisschen teuer, aber ehrlich gesagt bin ich froh": اعتراف ثم "aber".\n✓ "zwar" = صحيح (الجزء الأول من zwar … aber).\n✗ "aber" = لكن، تجي بعد الاعتراف موش قبلو.\n✗ "sehr" = برشا، وتتناقض مع "ein bisschen" (ما تجتمعش).`,
      rule: "zwar … aber = Zugeständnis + Gegensatz", ex: "Es ist **zwar** kalt, aber schön.", exTr: "صحيح بارد، بصح زين." },
    26: { ok: "was", type: "pronoun", keyword: "das Einzige, was …", bed: "اللي (الحاجة الوحيدة)",
      text: `بعد "das Einzige" الجملة الفرعية تبدا بـ "was" كـ Relativpronomen.\n✓ "was" = اللي (بعد das Einzige / alles / nichts).\n✗ "dass" = إنّو (رابط)، موش Relativpronomen يعوّض "das Einzige".\n✗ "die" = مؤنّث / جمع، و"das Einzige" محايد.`,
      rule: "Relativsatz nach das Einzige / das Beste / alles → was", ex: "Das Beste, **was** ich kenne, ist Ruhe.", exTr: "أحسن حاجة نعرفها هي الراحة." },
    27: { ok: "die", type: "pronoun", keyword: "Relativpronomen Plural Nom.: die", bed: "اللي",
      text: `"Leute, ___ Spanisch sprechen": Relativpronomen Nominativ جمع (الفاعل: Leute).\n✓ "die" = Nominativ جمع.\n✗ "sie" = ضمير شخصي (هم)، موش Relativpronomen يفتح جملة فرعية.\n✗ "welche" = بديل رسمي ونادر: ممكنة، بصح المعتاد "die".`,
      rule: "Relativpronomen Plural Nominativ: die (seltener: welche)", ex: "Ich kenne Leute, **die** Spanisch sprechen.", exTr: "نعرف ناس اللي يحكيو إسباني." },
    28: { ok: "aber", type: "conjunction", keyword: "aber auch (Steigerung)", bed: "لكن زادا",
      text: `الجملة تكمّل فكرة سابقة وتزيدها: "Aber auch in meiner Freizeit" (الألماني ما فقطش في الخدمة).\n✓ "aber" = لكن (Aber auch = وزيد).\n✗ "als" = تحتاج "sowohl" قبلها ("sowohl … als auch")، وما تبدا جملة.\n✗ "sondern" = تحتاج "nicht nur" قبلها ("nicht nur … sondern auch")، وما تبدا جملة.`,
      rule: "(nicht nur … ,) aber auch = Steigerung  |  sowohl … als auch  |  nicht nur … sondern auch", ex: "Er arbeitet viel, **aber** auch am Wochenende.", exTr: "يخدم برشا، وزيد في نهاية الأسبوع." },
    29: { ok: "fände", type: "tense", keyword: "fände es schön, wenn …", bed: "نلقاه (حلو)",
      text: `أمنية مؤدّبة مع "wenn … würden": Konjunktiv II من "finden".\n✓ "fände" = Konjunktiv II (أمنية افتراضية).\n✗ "fand" = Präteritum (ماضي)، والسياق افتراضي.\n✗ "finde" = Präsens (حقيقة)، وهنا فما "wenn … würden" افتراضية.`,
      rule: "Konjunktiv II: fände = höfliche Wunschäußerung (Ich fände es schön, wenn …)", ex: "Ich **fände** es schön, wenn du mitkommen würdest.", exTr: "نلقاه حلو لو تجي معانا." },
    30: { ok: "Wenn", type: "conjunction", keyword: "wenn (Bedingung)", bed: "إذا",
      text: `"إذا هذا ما يمشيش، نجّم نجي": شرط افتراضي.\n✓ "Wenn" = إذا (شرط، + فعل في الآخر).\n✗ "Als" = وقتما (حدث ماضي مرة وحدة)، والجملة افتراضية.\n✗ "Da" = بما إنّو (سبب معروف / حقيقة)، والشرط هنا ما هوش مؤكّد.`,
      rule: "wenn + Nebensatz = Bedingung  |  da = bekannter Grund  |  als = einmalig in der Vergangenheit", ex: "**Wenn** es regnet, bleiben wir zu Hause.", exTr: "إذا تشتي، نقعدو في الدار." },
  },
};
