// SB Teil 1 restyle — batch 04: [15] Herr Dr. Dobromil, [16] Herr Dr. Moosberger, [17] Frau Szabo (Original), [18] Frau Szabo (معدل), [19] Justus oder Juhannas (Original)
// NOTE: [17] gap 23 is intentionally NOT written — its DB key is "Für" but the sentence "___ besserer Einschätzung" (Genitiv) needs "Zwecks" → flagged for the owner.
export default {
  // ───────────── [15] Herr Dr. Dobromil ─────────────
  15: {
    21: { ok: "allergrößtem", type: "grammar_structure", keyword: "mit allergrößtem Interesse", bed: "باهتمام كبير جدًا",
      text: `"mit" يتبعو دايمًا Dativ. و"Interesse" محايد بدون أداة (Artikel)، يعني الصفة هي اللي تحمل النهاية: محايد + Dativ = "-em".\n✓ "allergrößtem" = Dativ محايد بدون أداة (mit allergrößtem Interesse).\n✗ "allergrößte" = نهاية Nominativ / Akkusativ (مؤنث أو جمع)، وبعد "mit" نحتاج Dativ.\n✗ "allergrößten" = نهاية مع أداة معرّفة أو جمع ("mit den allergrößten Schwierigkeiten")، وبدون أداة في المحايد نحتاج "-em".`,
      rule: "mit + Dativ; Adjektiv ohne Artikel: Neutrum Dativ = -em", ex: "Ich habe es mit **großem** Interesse gelesen.", exTr: "قريتو باهتمام كبير." },
    22: { ok: "in dem", type: "pronoun", keyword: "Stellenangebot, in dem …", bed: "اللي فيه (في الإعلان) تلوّجو",
      text: `الجملة الفرعية ترجع لـ "Stellenangebot" (محايد): "في الإعلان … تلوّجو". والحرف المناسب لمحتوى الإعلان هو "in" (في داخلو).\n✓ "in dem" = Relativpronomen محايد Dativ (في الإعلان).\n✗ "an dem" = على / عند (سطح أو حافة)، وما نقولوش "an dem Angebot" لمحتوى الإعلان.\n✗ "auf dem" = فوق (سطح)، ما يتركّبش مع إعلان في جريدة بمعنى "فيه".`,
      rule: "Relativpronomen: Präposition + dem (Neutrum Dativ): in dem", ex: "Ich habe das Angebot gelesen, **in dem** Sie eine Mitarbeiterin suchen.", exTr: "قريت الإعلان اللي فيه تلوّجو على موظفة." },
    23: { ok: "Ihren", type: "grammar_structure", keyword: "dem Ihren", bed: "كيما متاع حضرتكم (محلّكم)",
      text: `"wie dem …" = كيما متاع حضرتكم: ضمير الملكية يجي بعد أداة معرّفة (dem) فنحتاج نهاية ضعيفة "-en": "dem Ihren" (= dem Ihrigen).\n✓ "Ihren" = Possessivpronomen بعد "dem" (Dativ): "dem Ihren".\n✗ "Ihrem" = نهاية قوية، تجي بدون أداة ("in Ihrem Geschäft")، وما تتجمعش مع "dem" قبلها.\n✗ "Ihres" = Genitiv، وبعد "wie dem" نحتاج Dativ.`,
      rule: "Possessivpronomen mit Artikel: dem Ihren = dem Ihrigen (Endung -en)", ex: "Mein Geschäft ist nicht so groß wie **das Ihre**.", exTr: "محلّي موش كبير كيما متاعكم." },
    24: { ok: "zu können", type: "grammar_structure", keyword: "Infinitiv + zu können", bed: "إنّي نقدر نتولّى (المهمّة)",
      text: `"Es reizt mich, … übernehmen …" تحتاج Infinitiv مع "zu": "… übernehmen zu können" (الـ Modalverb "können" يجي في الآخر كـ Infinitiv).\n✓ "zu können" = zu + Modalverb Infinitiv (أنّي نقدر).\n✗ "können" = ما فيهاش "zu"، وهذا ما يجوزش بعد "Es reizt mich,".\n✗ "könnte" = Konjunktiv II مصرّف، موش Infinitiv: الجملة تحتاج صيغة غير مصرّفة.`,
      rule: "Es reizt mich, + Infinitiv + zu können (zu + Modalverb im Infinitiv)", ex: "Es freut mich, Ihnen helfen **zu können**.", exTr: "يفرحني إنّي نقدر نساعدكم." },
    25: { ok: "bei", type: "preposition", keyword: "eine Lehre bei + Dativ", bed: "تدريب مهني عند الشركة",
      text: `التدريب المهني (Lehre) يتعمل "عند" شركة أو معلّم: "bei der Firma".\n✓ "bei" = عند (الشركة اللي تدرّب).\n✗ "an" = على / عند حافة، وتتركّب مع المؤسسات التعليمية ("an der Schule")، موش مع شركة تدرّب.\n✗ "mit" = مع (مرافقة أو أداة)، وما يعطيش معنى مكان التدريب.`,
      rule: "(eine Lehre / Ausbildung) bei + Firma / Meister", ex: "Ich mache eine Ausbildung **bei** einer Bank.", exTr: "نعمل تكوين مهني عند بنك." },
    26: { ok: "ein Jahr lang", type: "fixed_expression", keyword: "ein Jahr lang", bed: "خدمت سنة كاملة",
      text: `نحكيو على فترة انتهت في الماضي (خدمت عندهم سنة وبعدها ما عادش): مدة + "lang".\n✓ "ein Jahr lang" = لمدة سنة (مدة منتهية).\n✗ "seit einem Jahr" = من سنة وللآن (مستمر)، والفعل "arbeitete" ماضي منتهي.\n✗ "durch ein Jahr" = ما هوش تركيب ألماني للمدّة؛ "durch" تجي مع الوسيلة أو المرور.`,
      rule: "Zeitraum: Akkusativ + lang (ein Jahr lang)  |  seit + Dativ (bis heute)", ex: "Ich habe **drei Monate lang** dort gearbeitet.", exTr: "خدمت 3 أشهر هناك." },
    27: { ok: "entdeckte", type: "verb", keyword: "eine Liebe entdecken", bed: "اكتشفت حبّي لـ",
      text: `الفعل المناسب مع "Liebe zu" هو إنّك تكتشف شعور موجود فيك من قبل: "entdecken".\n✓ "entdeckte" = اكتشفت (لقيت حبّي).\n✗ "erfand" = اخترعت (شي جديد ما كان موجود)، وما نخترعوش حبّ.\n✗ "merkte" = لاحظت (غلطة، فرق)، وما يتركّبش مع "Liebe" كمفعول بهالمعنى.`,
      rule: "entdecken = zum ersten Mal finden / merken  |  erfinden = neu schaffen", ex: "Dort **entdeckte** sie ihre Leidenschaft für Musik.", exTr: "هناك اكتشفت شغفها بالموسيقى." },
    28: { ok: "was", type: "pronoun", keyword: "was … angeht", bed: "بخصوص (فيما يتعلّق بـ)",
      text: `التعبير الثابت "was … angeht" = بخصوص / فيما يتعلّق بـ.\n✓ "was" = was Möbelstile … angeht.\n✗ "das" = هذا / اللي (ضمير وصل أو إشارة)، ما يدخلش في التعبير الثابت.\n✗ "welches" = اللي لاسم معيّن (رسمي)، والتعبير هنا ما فيه اسم يرجعلو.`,
      rule: "was + Subjekt + angeht = in Bezug auf / betreffend", ex: "**Was** die Kosten angeht, können wir sparen.", exTr: "بخصوص التكاليف، نجّمو نوفّرو." },
    29: { ok: "sowohl ... als auch", type: "grammar_structure", keyword: "sowohl … als auch", bed: "في الشمال وكذلك في الجنوب",
      text: `الجملة تقول إنها تعرف أنماط الأثاث في شمال أوروبا وفي جنوبها، يعني الاثنين معًا: رابط ثنائي للإضافة.\n✓ "sowohl ... als auch" = كل من… وكذلك… (الاثنين).\n✗ "weder ... noch" = لا… ولا… (نفي الاثنين)، وهذا عكس معنى "اكتسبت معرفة".\n✗ "teils ... teils" = جزء كذا وجزء كذا (توزيع)، موش إضافة شاملة للاثنين.`,
      rule: "sowohl … als auch = beides (Addition)  |  weder … noch = keins von beiden", ex: "Ich spreche **sowohl** Deutsch **als auch** Französisch.", exTr: "نحكي ألماني وزادة فرنسي." },
    30: { ok: "auf Ihre Anzeige zu antworten", type: "grammar_structure", keyword: "sich entschließen, zu + Infinitiv", bed: "قرّرت إنّي نردّ على إعلانكم",
      text: `"sich entschließen" يتبعو "zu + Infinitiv" (إنّي نعمل حاجة).\n✓ "auf Ihre Anzeige zu antworten" = zu + Infinitiv (بدون رابط زيادة).\n✗ "auf Ihre Anzeige antworten" = Infinitiv بلا "zu"، وهذا ما يجوزش بعد "sich entschließen".\n✗ "um auf Ihre Anzeige zu antworten" = "um … zu" معناها "باش" (غاية)، والجملة هنا تعبّر على قرار موش غاية.`,
      rule: "sich entschließen + zu-Infinitiv (ohne um)", ex: "Ich habe mich entschlossen, dir **zu helfen**.", exTr: "قرّرت إنّي نساعدك." },
  },

  // ───────────── [16] Herr Dr. Moosberger ───────────── (22, 26, 27, 29, 30 reused automatically)
  16: {
    21: { reuse: "15#21" },
    23: { ok: "so", type: "grammar_structure", keyword: "so … wie", bed: "في محلّ مشهور مثل محلّكم",
      text: `"… renommierten Geschäft wie dem Ihrigen" مقارنة تساوي: نحتاج "so" قبل الصفة و"wie" بعدها.\n✓ "so" = so renommiert wie (مساواة).\n✗ "als" = تجي مع صيغة التفضيل ("renommierter als")، وهنا فيه "wie" موش "als".\n✗ "wie" = موجودة بعد الصفة، وما نحطوش "wie … wie" مرتين.`,
      rule: "so + Adjektiv + wie = Vergleich der Gleichheit  |  Adj.-er + als = Komparativ", ex: "Er ist **so** groß wie sein Vater.", exTr: "هو طويل كيما باباه." },
    24: { reuse: "15#24" },
    25: { ok: "begann", type: "verb", keyword: "begann (beginnen)", bed: "بدأت تدريب مهني",
      text: `"begann ich eine Lehre" = بدأت تدريب مهني: Präteritum من "beginnen" (مصرّف مع "ich").\n✓ "begann" = Präteritum من beginnen.\n✗ "beging" = Präteritum من "begehen" (يرتكب غلطة / جريمة)، موش يبدأ.\n✗ "belief" = من "sich belaufen auf" (يبلغ مبلغ)، وبعدو "sich" و"auf"، موش بداية تدريب.`,
      rule: "beginnen – begann – begonnen  |  begehen – beging  |  sich belaufen – belief sich", ex: "Ich **begann** 2015 meine Ausbildung.", exTr: "بدأت تكويني في 2015." },
    28: { ok: "Während", type: "preposition", keyword: "während + Genitiv", bed: "خلال (أثناء) عملي ودراستي",
      text: `بعد الفراغ جاي اسم في الـ Genitiv ("meiner Berufstätigkeit und meines Studiums") يعني نحتاج حرف جر: "während" (خلال).\n✓ "Während" = حرف جر + Genitiv (أثناء فترة).\n✗ "Dabei" = في هذه الأثناء / مع ذلك (ظرف)، ما ياخذش اسم Genitiv بعدو.\n✗ "Inzwischen" = في هالأثناء (ظرف)، وما يعمل Genitiv ولا يربط فترة بمعنى "خلال".`,
      rule: "während + Genitiv (Präposition = im Verlauf von)", ex: "**Während** des Studiums habe ich gearbeitet.", exTr: "خلال الدراسة كنت نخدم." },
  },

  // ───────────── [17] Frau Szabo ( Original ) ───────────── (gap 23 PENDING — suspect key)
  17: {
    21: { ok: "an", type: "fixed_expression", keyword: "Interesse an + Dat.", bed: "اهتمامكم بدوراتنا",
      text: `الاسم "Interesse" يتركّب مع "an" + Dativ (اهتمام بـ).\n✓ "an" = Interesse an + Dativ.\n✗ "bei" = عند، وما نقولوش "Interesse bei".\n✗ "in" = داخل، وما يتركّبش مع "Interesse" بهالمعنى.`,
      rule: "Interesse an + Dativ", ex: "Ich habe Interesse **an** Geschichte.", exTr: "عندي اهتمام بالتاريخ." },
    22: { ok: "in Höhe", type: "fixed_expression", keyword: "in Höhe von", bed: "بمبلغ (بقيمة) 200 يورو",
      text: `التعبير الثابت للمبالغ: "in Höhe von" = بقيمة / بمبلغ.\n✓ "in Höhe" = in Höhe von + مبلغ.\n✗ "in Betrag" = ما هوش تعبير ثابت ("einen Betrag von …" بدون "in").\n✗ "in Summe" = "in der Summe / insgesamt" بمعنى بالمجموع، موش "بمبلغ كذا".`,
      rule: "in Höhe von + Betrag", ex: "Bitte überweisen Sie einen Betrag **in Höhe** von 50 Euro.", exTr: "من فضلكم حوّلو مبلغ بقيمة 50 يورو." },
    24: { ok: "anschließen", type: "verb", keyword: "sich anschließen", bed: "يجي بعدو (يتبعو)",
      text: `بعد "wird sich" (Futur I) نحتاج Infinitiv: "anschließen" (يجي بعد / يتبع).\n✓ "anschließen" = Infinitiv بعد "werden" (Futur).\n✗ "angeschlossen" = Partizip II، وما يتركّبش مع "wird" كـ Futur بهالشكل.\n✗ "schließen an" = ترتيب غلط: "anschließen" فعل منفصل، وفي الـ Infinitiv يتكتب كلمة وحدة بعد "wird sich".`,
      rule: "werden + Infinitiv (Futur I): wird sich … anschließen", ex: "Dem Kurs **wird** sich ein Test **anschließen**.", exTr: "بعد الدورة يجي اختبار." },
    25: { ok: "bezüglich", type: "preposition", keyword: "bezüglich + Genitiv", bed: "بخصوص اهتماماتكم",
      text: `الاستمارة تخص اهتمامات الوقت الحرّ: نحتاج حرف جر معناه "بخصوص" + Genitiv: "bezüglich".\n✓ "bezüglich" = بخصوص / متعلّق بـ.\n✗ "anlässlich" = بمناسبة (حدث: "anlässlich des Geburtstags")، موش موضوع الاستمارة.\n✗ "mittels" = بواسطة (وسيلة)، وما تعطيش معنى "بخصوص".`,
      rule: "bezüglich + Genitiv = in Bezug auf  |  anlässlich = aus Anlass  |  mittels = mit Hilfe von", ex: "**Bezüglich** Ihrer Anfrage melde ich mich.", exTr: "بخصوص طلبكم، نتّصل بيكم." },
    26: { ok: "wie", type: "grammar_structure", keyword: "so … wie möglich", bed: "مريح أقصى ما يمكن",
      text: `التعبير الثابت "so … wie möglich" = أقصى ما يمكن: مقارنة تساوي مع "so" و"wie".\n✓ "wie" = so angenehm wie möglich.\n✗ "als" = تجي مع الـ Komparativ ("angenehmer als")، وهنا فيه "so" (مساواة).\n✗ "wenn" = إذا (شرط)، ما تدخلش في مقارنة "so … wie".`,
      rule: "so + Adjektiv + wie möglich = Maximum", ex: "Ich komme **so** schnell **wie** möglich.", exTr: "نجي أسرع ما يمكن." },
    27: { ok: "einer", type: "grammar_structure", keyword: "zwischen + Dativ", bed: "بين فندق وسكن خاص…",
      text: `"wählen zwischen" ياخذ Dativ، و"Privatunterkunft" مؤنث: Dativ مؤنث = "einer".\n✓ "einer" = Dativ مؤنث.\n✗ "ein" = Nominativ / Akkusativ (مذكر أو محايد)، وبعد "zwischen" هنا نحتاج Dativ.\n✗ "einem" = Dativ مذكر / محايد، و"Privatunterkunft" مؤنث.`,
      rule: "wählen zwischen + Dativ (feminin: einer)", ex: "Sie können zwischen einem Zimmer und **einer** Wohnung wählen.", exTr: "تنجّم تختار بين غرفة وشقة." },
    28: { ok: "Sobald", type: "conjunction", keyword: "sobald + Nebensatz", bed: "أول ما توصلنا تسجيلتكم",
      text: `التسجيل يوصل مرة وحدة، وبعدها مباشرة تجي التأكيد: "أول ما" = sobald (الفعل "eingegangen ist" في الآخر).\n✓ "Sobald" = أول ما (رابط زمني).\n✗ "Sooft" = كل مرة / كلما (تكرار)، والتسجيل يوصل مرة وحدة.\n✗ "Sofort" = حالًا (ظرف)، موش رابط يفتح Nebensatz بفعل في الآخر.`,
      rule: "sobald = in dem Moment, wenn  |  sooft = jedes Mal, wenn  |  sofort = Adverb", ex: "**Sobald** ich ankomme, rufe ich an.", exTr: "أول ما نوصل، نكلّم." },
    29: { ok: "damit", type: "conjunction", keyword: "damit + Nebensatz", bed: "باش تلقاو الطريق بسهولة",
      text: `نحكيو على غاية: نبعثو الخريطة "باش" تلقاو الطريق. والفعل "finden" في الآخر، يعني نحتاج رابط غاية.\n✓ "damit" = باش (Zweck، Nebensatz).\n✗ "dafür" = لأجل ذلك (Pronominaladverb)، وما يفتحش جملة فرعية بفعل في الآخر.\n✗ "dazu" = إلى ذلك / بخصوصو، وما يعبّرش عن الغاية في جملة فرعية.`,
      rule: "damit + Nebensatz = Zweck (Verb am Ende)", ex: "Ich erkläre es dir, **damit** du es verstehst.", exTr: "نشرحلك باش تفهم." },
    30: { ok: "Bei", type: "fixed_expression", keyword: "Bei weiteren Fragen", bed: "لو عندكم أسئلة أخرى",
      text: `الصيغة المعتادة في الرسائل الرسمية: "Bei weiteren Fragen steht … zur Verfügung" = إذا عندكم أسئلة أخرى.\n✓ "Bei" = في حالة (Fragen، Problemen).\n✗ "Für" = لأجل: "Für weitere Fragen" تتسمع زادة في الواقع، لكن الصيغة المعتمدة والأشهر هنا "Bei".\n✗ "Zu" = إلى / بخصوص، ما تتركّبش مع "weitere Fragen" في هالصيغة الرسمية.`,
      rule: "Bei + Fragen / Problemen / Bedarf = im Fall von", ex: "**Bei** Fragen rufen Sie uns an.", exTr: "إذا عندكم أسئلة، كلّمونا." },
  },

  // ───────────── [18] Frau Szabo (معدل) ───────────── (22, 27, 29 reused automatically)
  18: {
    21: { ok: "anbei", type: "fixed_expression", keyword: "anbei (Anlage)", bed: "مرفق طيّه",
      text: `في الرسائل الرسمية نقولو "Anbei erhalten Sie …" = مرفق طيّه (الوثيقة معاها في نفس الظرف).\n✓ "anbei" = مرفق / طيّه (التعبير الرسمي الثابت).\n✗ "dabei" = معاه / في هذا الأثناء (ظرف عام)، وما يعطيش معنى المرفق الرسمي.\n✗ "vorbei" = فات / انتهى ("Der Regen ist vorbei")، ما لو علاقة بالمرفقات.`,
      rule: "Anbei erhalten Sie … = im Anhang / beigefügt (Geschäftsbrief)", ex: "**Anbei** erhalten Sie den Vertrag.", exTr: "مرفق طيّه العقد." },
    23: { ok: "zur", type: "fixed_expression", keyword: "zur + Nomen (Zweck)", bed: "لأجل تقييم أدقّ",
      text: `"genaueren Einschätzung" مؤنث Dativ: نحتاج حرف جر + أداة مؤنث: "zur" (= zu + der) بمعنى "لأجل / بقصد".\n✓ "zur" = zu + der + Dativ (غاية: zur Einschätzung).\n✗ "für" = لأجل، لكن بعدها Akkusativ ("für eine genauere Einschätzung")، والنص فيه "genaueren" بدون أداة (Dativ).\n✗ "zweck" = اسم ("der Zweck") بدون حرف جر ولا أداة، وما يركّبش الجملة.`,
      rule: "zu + Dativ (Zweck: zur Information / zur Einschätzung)", ex: "**Zur** Information senden wir Ihnen den Plan.", exTr: "للعلم، نبعثولكم الخطة." },
    24: { ok: "stattfinden", type: "verb", keyword: "stattfinden", bed: "يتعمل (يصير)",
      text: `الاختبار "هو" اللي يصير (فاعل)، يعني نحتاج فعل لازم (بلا مفعول): "stattfinden".\n✓ "stattfinden" = يصير / يتعمل (فاعلو الاختبار).\n✗ "durchführen" = ينفّذ (فعل متعدّي، يحتاج مفعول): "wird durchgeführt" تكون بالمبني للمجهول، موش "wird durchführen".\n✗ "veranstalten" = ينظّم حدث (متعدّي)، نفس المشكل: الاختبار ما يعملش الحدث.`,
      rule: "stattfinden (intransitiv)  |  durchführen / veranstalten (transitiv + Objekt)", ex: "Der Test **findet** am Montag **statt**.", exTr: "الاختبار يصير الإثنين." },
    25: { reuse: "17#25" },
    26: { ok: "möglichst", type: "adjective_adverb", keyword: "möglichst + Adj.", bed: "أريح ما يمكن",
      text: `نبغاو نخلّو الإقامة مريحة "أقصى ما يمكن": الظرف اللي يجي قبل الصفة هو "möglichst".\n✓ "möglichst" = قدر الإمكان (ظرف قبل صفة).\n✗ "möglich" = ممكن (صفة)، وما تجيش قبل صفة أخرى بهالمعنى.\n✗ "möglicherweise" = ربما (احتمال)، موش درجة "قدر الإمكان".`,
      rule: "möglichst + Adjektiv = so … wie möglich", ex: "Wir möchten Ihren Aufenthalt **möglichst** angenehm machen.", exTr: "نحبو نخلّو إقامتكم مريحة قدر المستطاع." },
    28: { reuse: "17#28" },
    30: { ok: "Bei", type: "fixed_expression", keyword: "Bei weiteren Fragen", bed: "لو عندكم أسئلة أخرى",
      text: `هذا ختام الرسالة الرسمية بالصيغة الثابتة: "Bei weiteren Fragen" (إذا عندكم أسئلة أخرى) ثم "steht … zur Verfügung".\n✓ "Bei" = في حالة وجود (Fragen).\n✗ "Für" = لأجل: ممكن تتسمع، لكن الصيغة الأرجح والمعتمدة هنا "Bei".\n✗ "Als" = كـ / وقتما (ماضي)، وما تتركّبش مع "weitere Fragen".`,
      rule: "Bei weiteren Fragen steht … zur Verfügung", ex: "**Bei** Problemen melden Sie sich bitte.", exTr: "إذا فما مشاكل، اتّصلو بينا." },
  },

  // ───────────── [19] Justus oder Juhannas ( Original ) ─────────────
  19: {
    21: { ok: "über", type: "verb_prep", keyword: "sich freuen über", bed: "اللي فرحت بيها (البطاقة)",
      text: `"sich freuen" + حاجة وصلتك (بطاقة جاتك) = "über + Akk.": "die Karte, über die ich mich gefreut habe".\n✓ "über" = sich freuen über (حاجة وصلت أو صارت).\n✗ "für" = لأجل شخص ("Ich freue mich für dich")، موش حاجة.\n✗ "an" = للاستمتاع بحاجة قدّامك ("sich an Blumen freuen")، موش لبطاقة وصلت.`,
      rule: "sich freuen über + Akk. (etwas Erhaltenes) → über die", ex: "Das Geschenk, **über** das ich mich gefreut habe.", exTr: "الهدية اللي فرحت بيها." },
    22: { ok: "gar", type: "adjective_adverb", keyword: "gar nicht", bed: "ما كنتش نعرف أصلًا",
      text: `"nicht" يتزاد عليه تأكيد: "gar nicht" = أبدًا / أصلًا.\n✓ "gar" = gar nicht (تأكيد النفي).\n✗ "daher" = لهذا السبب (نتيجة)، وما يتركّبش مع "nicht" بهذا المعنى.\n✗ "sicher" = أكيد، و"sicher nicht" معناها أكيد لا (رفض)، موش "ما كنتش نعرف أصلًا".`,
      rule: "gar nicht = überhaupt nicht (Verstärkung der Verneinung)", ex: "Das wusste ich **gar** nicht.", exTr: "هذا ما كنتش نعرفو أصلًا." },
    23: { ok: "besonders", type: "adjective_adverb", keyword: "nicht besonders", bed: "ما عجبنيش برشا",
      text: `"nicht besonders gefallen" = ما عجبنيش برشا (نفي مخفّف مهذّب).\n✓ "besonders" = nicht besonders (موش بشكل خاص).\n✗ "einfach" = ببساطة / سهل، و"nicht einfach gefallen" غير مألوف.\n✗ "kaum" = بالكاد، وهي نفي بحد ذاتها: "nicht kaum" ما تجيش (نفي مزدوج غير صحيح).`,
      rule: "nicht besonders = nicht sehr (abgeschwächte Verneinung)", ex: "Der Film hat mir **nicht besonders** gefallen.", exTr: "الفيلم ما عجبنيش برشا." },
    24: { ok: "schließlich", type: "adjective_adverb", keyword: "schließlich (Begründung)", bed: "آخر الأمر (عندي برشا ضغط)",
      text: `الجملة تعطي سببًا لحبّها للبحر والراحة: "آخر الأمر عندي ضغط كافي في الحياة اليومية". كلمة "schließlich" تعني "فآخر الأمر / خاطر".\n✓ "schließlich" = (تبرير) آخر الأمر / وبالنهاية.\n✗ "außerdem" = زيادة على ذلك (إضافة نقطة)، موش تبرير.\n✗ "allerdings" = لكن / غير إنّ (تقييد أو تعارض)، وما فماش تعارض.`,
      rule: "schließlich = immerhin / denn (nachgeschobener Grund)", ex: "Ich bleibe zu Hause, **schließlich** bin ich müde.", exTr: "نقعد في الدار، خاطر آخر الأمر تعبان." },
    25: { ok: "entfernt", type: "adjective_adverb", keyword: "weiter entfernt", bed: "أبعد (مسافة)",
      text: `نقارنو المسافة: "noch weiter … als deine alte" = أبعد من القديمة. الصفة المناسبة: "entfernt" (بعيد عن).\n✓ "entfernt" = weiter entfernt (بعيد، مسافة).\n✗ "steht" = واقف، وما تركّبش مع "weiter … als" كمسافة.\n✗ "abgerückt" = اتحرّك بعيدًا (Partizip لفعل حركة)، موش تعبير مألوف لمسافة المكتب.`,
      rule: "weiter entfernt (sein) als = Komparativ von weit", ex: "Die Schule ist **weiter entfernt** als der Bahnhof.", exTr: "المدرسة أبعد من المحطة." },
    26: { ok: "wechseln", type: "verb", keyword: "die Stelle wechseln", bed: "نبدّل الخدمة",
      text: `نبدّل الخدمة بخدمة أخرى: الفعل المعتاد "wechseln" (die Stelle / den Job wechseln).\n✓ "wechseln" = نبدّل بخدمة أخرى.\n✗ "ändern" = نغيّر حاجة موجودة (نغيّر الخدمة نفسها، موش نمشي لخدمة أخرى).\n✗ "verwechseln" = نخلط بين شخصين أو حاجتين، موش نبدّل.`,
      rule: "wechseln = durch ein Gleiches ersetzen  |  ändern = anders machen  |  verwechseln = verwirren", ex: "Er möchte **den Job wechseln**.", exTr: "يحب يبدّل الخدمة." },
    27: { ok: "gesagt", type: "fixed_expression", keyword: "ehrlich gesagt", bed: "بصراحة",
      text: `تعبير ثابت: "ehrlich gesagt" = بصراحة (Partizip II).\n✓ "gesagt" = ehrlich gesagt.\n✗ "sagend" = Partizip I (حالة فعل جاري)، وما يتركّبش في هذا التعبير.\n✗ "zu sagen" = zu + Infinitiv ("Es fällt mir schwer, ehrlich zu sagen …")، موش التعبير الثابت.`,
      rule: "Adverb + gesagt: ehrlich gesagt / kurz gesagt (Partizip II)", ex: "**Ehrlich gesagt** habe ich keine Lust.", exTr: "بصراحة ما عنديش رغبة." },
    28: { ok: "kommenden", type: "grammar_structure", keyword: "ab dem kommenden Monat", bed: "من الشهر الجاي",
      text: `"ab" يتبعو Dativ، وبعد "dem" (Dativ مذكر مفرد) الصفة تاخذ النهاية الضعيفة "-en".\n✓ "kommenden" = dem kommenden Monat.\n✗ "kommende" = نهاية Nominativ / Akkusativ، وبعد "ab dem" نحتاج Dativ.\n✗ "kommendem" = نهاية قوية (بدون أداة)، وهنا فيه "dem" قبلها.`,
      rule: "Adjektiv nach Artikel (Dativ Singular) = -en: dem kommenden Monat", ex: "Ab **dem kommenden** Jahr ändert sich das.", exTr: "من العام الجاي هذا يتبدّل." },
    29: { ok: "je", type: "conjunction", keyword: "je älter, desto …", bed: "كل ما كبرت أكثر",
      text: `"immer schwieriger, … älter man ist" = كل ما كبرت أكثر: بناء "je + مقارنة".\n✓ "je" = je älter (كل ما… أكثر).\n✗ "als" = من / كيما (مقارنة أو وقت ماضي)، وما تعطيش معنى التناسب.\n✗ "weil" = خاطر (سبب)، والجملة تعبّر عن علاقة تناسب موش سبب.`,
      rule: "je + Komparativ + Nebensatz (…, desto / umso + Komparativ)", ex: "**Je** älter man wird, desto schwerer lernt man.", exTr: "كل ما كبرت، كل ما صعب التعلّم." },
    30: { ok: "wäre", type: "tense", keyword: "Wie wäre es, wenn …?", bed: "شنوّة رأيك لو نتلاقاو؟ (اقتراح)",
      text: `نعرضو اقتراح بلطف: "Wie wäre es, wenn …?" (Konjunktiv II) = شنوّة رأيك لو…؟\n✓ "wäre" = Konjunktiv II (اقتراح مؤدّب).\n✗ "ist" = مضارع واقعي ("Wie ist es?" = كيفاش الحال؟)، موش اقتراح.\n✗ "war" = ماضي، وما يعطيش اقتراح لمستقبل.`,
      rule: "Wie wäre es, wenn + Konjunktiv II = Vorschlag", ex: "**Wie wäre** es, wenn wir morgen ins Kino gingen?", exTr: "شنوّة رأيك نمشيو غدوة للسينما؟" },
  },
};
