// SB Teil 1 restyle — batch 10: [45] Vanessa, [46] Jens (gap 29 FLAGGED, omitted), [47] Daniela, [48] Frau Melchior, [49] Frau Stein Neu (gap 30 FLAGGED, omitted)
export default {
  // ───────────── [45] Vanessa ─────────────
  45: {
    21: { ok: "über den", type: "verb_prep", keyword: "sich freuen über + Akk.", bed: "فرحت بيها (الرسالة)",
      text: `"sich freuen" على حاجة وصلت وفرحنا بيها يتبعو "über" + Akkusativ، و"Brief" مذكّر: "über den Brief".\n✓ "über den" = على الرسالة (über + Akk. مذكّر).\n✗ "an den" = ما تتركّبش مع "freuen" بهذا المعنى (الحرف "an" يجي في "sich an etwas erinnern").\n✗ "auf dem" = "auf" تتبعها Dativ هنا غلط، وهي أصلاً للفرح بحاجة جاية (auf + Akk.)، موش بحاجة وصلت.`,
      rule: "sich freuen über + Akk. (Gegenwart / Vergangenheit)  |  sich freuen auf + Akk. (Zukunft)", ex: "Ich habe mich **über den** Anruf gefreut.", exTr: "فرحت بالمكالمة." },
    22: { ok: "nichts mehr", type: "fixed_expression", keyword: "nichts mehr von jdm. hören", bed: "ما سمعتش حتى حاجة (من عندي)",
      text: `"warum du schon drei Wochen ___ von mir gehört hast": ما وصلتكش أخبار من مدّة: "nichts mehr von mir gehört".\n✓ "nichts mehr" = ما عادش حاجة (انقطاع الأخبار).\n✗ "noch nicht" = مازال ما صارش: ممكنة نحويًّا، بصح تتعارض مع "schon drei Wochen" (مدّة فاتت).\n✗ "keines" = ما واحد (Pronomen محايد)، و"keines von mir gehört" ما تتقالش.`,
      rule: "nichts mehr von jdm. hören = keine Nachricht mehr bekommen", ex: "Ich habe seit Wochen **nichts mehr** von ihm gehört.", exTr: "ما سمعتش منو حتى حاجة من أسابيع." },
    23: { ok: "doch", type: "adjective_adverb", keyword: "doch selbst wissen", bed: "إنت تعرف (بروحك)",
      text: `"Du weißt doch selbst, wie anstrengend…": "doch" تذكّر بحاجة المخاطَبة تعرفها.\n✓ "doch" = أكيد / إنت تعرف (Abtönungspartikel).\n✗ "eben" = هكا هو الحال (تأكيد حقيقة: "Das ist eben so")، وما تتماشاش مع تذكير "إنت تعرف".\n✗ "überhaupt" = بالمرّة (تحتاج نفي أو سؤال)، و"du weißt überhaupt selbst" ما تتقالش.`,
      rule: "doch (unbetont) = Hinweis auf Bekanntes  |  eben = bestätigt eine Tatsache  |  überhaupt braucht Verneinung / Frage", ex: "Du kennst die Antwort **doch** selbst.", exTr: "إنت تعرف الجواب بروحك." },
    24: { ok: "Wie", type: "fixed_expression", keyword: "Wie ist es …? (Frage nach Zustand)", bed: "كيفاش (الحال)",
      text: `سؤال على الحال في عائلة Au-pair: "Wie ist es …?" (كيفاش الوضع).\n✓ "Wie" = كيفاش (سؤال على الحال / التجربة).\n✗ "Wann" = إمتى (سؤال عن الوقت)، والجملة تسأل على الحال موش على الوقت.\n✗ "Was" = شنوّة (سؤال على شي)، و"Was ist es in der Familie" ما تعطيش سؤال على الحال.`,
      rule: "Wie ist es …? = Frage nach Zustand / Erfahrung  |  Was = Sache  |  Wann = Zeit", ex: "**Wie** ist es bei dir in der Arbeit?", exTr: "كيفاش الحال عندك في الخدمة؟" },
    25: { ok: "der", type: "grammar_structure", keyword: "Nomen + Genitiv: der Alpen", bed: "متاع (الألب)",
      text: `"am Fuß" (اسم) يتبعو Genitiv، و"Alpen" جمع: "am Fuß der Alpen".\n✓ "der" = Genitiv جمع (der Alpen).\n✗ "die" = Nominativ / Akkusativ جمع، واللي بعد الاسم "Fuß" لازم يكون Genitiv.\n✗ "von" = "von" لوحدها قبل "Alpen" ما تتقالش، تحتاج أداة ("von den Alpen")، والتعبير المعتاد بعد "Fuß" هو Genitiv.`,
      rule: "Nomen + Genitiv (Plural: der): am Fuß der Alpen", ex: "Das Dorf liegt am Fuße **der** Berge.", exTr: "القرية على سفح الجبال." },
    26: { ok: "getan", type: "verb", keyword: "weh tun", bed: "كانوا يوجعو",
      text: `"die Füße haben weh ___": التعبير الثابت "weh tun" (يوجّع) ← Partizip II "getan".\n✓ "getan" = Partizip II من "tun" (weh getan).\n✗ "gelaufen" = مشى / جرى (laufen)، موش ألم.\n✗ "geworden" = صار (werden)، و"weh geworden" ما تتقالش.`,
      rule: "jdm. tut etwas weh (weh tun – tat weh – weh getan)", ex: "Mir hat der Rücken **weh getan**.", exTr: "ضهري كان يوجعني." },
    27: { ok: "umfallen", type: "verb", keyword: "vor Erschöpfung umfallen", bed: "يطيحو (من التعب)",
      text: `"bis sie vor Erschöpfung ___": يمشيو لين يطيحو من التعب: "umfallen".\n✓ "umfallen" = يطيح (للأرض).\n✗ "durchfallen" = يرسب (في امتحان)، موش يطيح من التعب.\n✗ "wegfallen" = يتلغى / يسقط (Regel fällt weg)، موش طيحة جسدية.`,
      rule: "umfallen = zu Boden fallen  |  durchfallen = in der Prüfung versagen  |  wegfallen = entfallen", ex: "Sie wäre fast vor Müdigkeit **umgefallen**.", exTr: "قريب طاحت من التعب." },
    28: { ok: "dir", type: "pronoun", keyword: "Stell dir vor (Dativ)", bed: "تصوّر",
      text: `"sich (Dativ) etwas vorstellen" = يتصوّر: "Stell dir vor".\n✓ "dir" = Dativ (تصوّر لروحك).\n✗ "dich" = Akkusativ، و"Stell dich vor" معناها قدّم روحك (تعريف)، معنى مختلف.\n✗ "mal" = مرة (تلطيف)، موش ضمير، والفعل انعكاسي يحتاج ضمير.`,
      rule: "sich (Dat.) etwas vorstellen = imaginieren  |  sich (Akk.) vorstellen = sich bekannt machen", ex: "Stell **dir** vor, wir fahren nach Rom!", exTr: "تصوّر، باش نمشيو لروما!" },
    29: { ok: "jede", type: "fixed_expression", keyword: "jede Menge", bed: "برشا (حاجات)",
      text: `"jede Menge Hindernisse" = برشا عراقيل (تعبير عامّي).\n✓ "jede" = jede Menge (برشا).\n✗ "ganze" = تحتاج أداة قبلها ("eine ganze Menge")، وهنا ما فماش "eine".\n✗ "alle" = جمع، و"Menge" مفرد مؤنّث ("alle Menge" ما تتقالش).`,
      rule: "jede Menge = sehr viele (umgangssprachlich)  |  eine ganze Menge", ex: "Auf dem Markt gab es **jede** Menge Obst.", exTr: "في السوق كان فما برشا فواكه." },
    30: { ok: "damit", type: "pronoun_adverb", keyword: "aufhören mit → damit", bed: "بهذا (يوقفو)",
      text: `"aufhören" يتبعو "mit"، والـ Pronominaladverb "damit" (= mit + das) يرجع للعبة: "mit etwas aufhören".\n✓ "damit" = بهذا (mit + das).\n✗ "dabei" = bei + das (dabei bleiben / dabei sein)، و"aufhören dabei" ما تتقالش.\n✗ "davon" = von + das، و"aufhören von" ما تتقالش.`,
      rule: "aufhören mit + Dat. → damit aufhören", ex: "Hör **damit** auf!", exTr: "وقف هذا!" },
  },

  // ───────────── [46] Jens' Fußballtrainer-Sorgen (gap 29 FLAGGED: key "totalem" vs. "in einem ___ Chaos" → needs "totalen") ─────────────
  46: {
    21: { ok: "lassen", type: "verb", keyword: "jdn. warten lassen (Infinitiv nach will)", bed: "نخلّيك تستنّى",
      text: `"ich will Dich nicht … warten ___": بعد الفعل المساعد "will" الفعل الأساسي كلّو Infinitiv: "warten lassen".\n✓ "lassen" = Infinitiv (jdn. warten lassen).\n✗ "gelassen" = Partizip II، وبعد "will" نحتاج Infinitiv.\n✗ "ließ" = Präteritum (فعل مصرّف)، والفعل المصرّف موجود قبلو "will".`,
      rule: "Modalverb + Infinitiv: will … warten lassen (nicht: gelassen)", ex: "Ich will dich nicht länger warten **lassen**.", exTr: "ما نحبّش نخلّيك تستنّى أكثر." },
    22: { ok: "weil", type: "conjunction", keyword: "weil + Nebensatz", bed: "خاطر",
      text: `الجملة تعطي سبب ("خاطر نحب نعرف أكثر") والفعل "möchte" في الآخر.\n✓ "weil" = خاطر (+ فعل في الآخر).\n✗ "denn" = خاطر لكن تدخل جملة رئيسية (الفعل في المرتبة الثانية: "denn ich möchte")، وهنا "möchte" في الآخر.\n✗ "wenn" = إذا / كلّما (شرط)، والجملة هنا تعطي سبب.`,
      rule: "weil + Nebensatz (Verb am Ende)  |  denn + Hauptsatz (Verb Position 2)", ex: "Ich schreibe dir, **weil** ich Neuigkeiten habe.", exTr: "نكتبلك خاطر عندي أخبار." },
    23: { ok: "als", type: "preposition", keyword: "Job als + Beruf", bed: "كـ (مدرّب)",
      text: `المهنة / الوظيفة تتذكر بـ "als": "Job als Fußballtrainer".\n✓ "als" = كـ (Job als + Beruf).\n✗ "für" = لـ ("ein Job für Kinder")، لكن المهنة نفسها تتقال بـ "als".\n✗ "wie" = كيما (مقارنة)، وما تعطيش الوظيفة.`,
      rule: "als + Beruf / Funktion (Job als …, arbeiten als …)", ex: "Er arbeitet **als** Taxifahrer.", exTr: "يخدم كسائق تاكسي." },
    24: { ok: "dass", type: "conjunction", keyword: "nicht wissen, dass (Überraschung)", bed: "إنّك (متحمّس للكورة)",
      text: `"Ich wusste gar nicht, ___ Du so fußballbegeistert bist!": مفاجأة من حقيقة ← "dass".\n✓ "dass" = إنّو (محتوى حقيقة، والفعل في الآخر).\n✗ "ob" = هل (whether): ممكنة نحويًّا، بصح "so begeistert" تعبّر على مفاجأة من حقيقة موش سؤال.\n✗ "wann" = إمتى (زمن)، والجملة ما تسألش على وقت.`,
      rule: "nicht wissen, dass + Nebensatz (Überraschung über eine Tatsache)", ex: "Ich wusste nicht, **dass** du Gitarre spielst.", exTr: "ما كنتش نعرف إنّك تعزف على القيثارة." },
    25: { ok: "ziemlich", type: "adjective_adverb", keyword: "ziemlich viel", bed: "برشا نوعًا ما",
      text: `"ziemlich viel Stress" = برشا ضغط نوعًا ما: ظرف درجة قبل "viel".\n✓ "ziemlich" = نوعًا ما برشا (Gradpartikel).\n✗ "eigentlich" = في الحقيقة (تخفيف)، موش درجة.\n✗ "unbedingt" = لازم (ضرورة: "unbedingt brauchen")، وما تتركّبش مع "viel Stress haben".`,
      rule: "ziemlich + viel / Adjektiv = in hohem Maß", ex: "Ich habe **ziemlich** viel Arbeit.", exTr: "عندي برشا خدمة نوعًا ما." },
    26: { ok: "beim", type: "preposition", keyword: "beim (bei + dem)", bed: "وقت (التربّص المدرسي)",
      text: `"beim Schulpraktikum" = وقت التربّص: "bei + dem" مدمجة، و"Schulpraktikum" محايد.\n✓ "beim" = bei + dem (حدث زمني).\n✗ "für" = لـ (غرض أو مدّة)، وما تعطيش معنى "خلال التربّص".\n✗ "während" = أثناء، بصح تتبعها Genitiv وأداة ("während des Schulpraktikums")، و"während Schulpraktikum" ما تتقالش.`,
      rule: "bei + dem = beim (zeitlich: beim Essen, beim Praktikum)", ex: "**Beim** Essen spricht man nicht.", exTr: "وقت الماكلة ما نحكيوش." },
    27: { ok: "durchzusetzen", type: "grammar_structure", keyword: "durchzusetzen (zu im trennbaren Verb)", bed: "نفرض روحي",
      text: `"nicht geschafft, mich … ___": بعد "schaffen" نحتاج zu + Infinitiv، وفي الفعل المنفصل "zu" تدخل بين البادئة والفعل: "durchzusetzen".\n✓ "durchzusetzen" = durch + zu + setzen.\n✗ "durchsetzen" = Infinitiv بدون "zu"، وهنا "zu" مطلوبة.\n✗ "zu durchsetzen" = "zu" لازم تدخل داخل الفعل المنفصل، موش قدّامو.`,
      rule: "trennbare Verben: zu steht zwischen Präfix und Verb (aufzustehen, durchzusetzen)", ex: "Ich versuche, früh **aufzustehen**.", exTr: "نحاول نقوم بكري." },
    28: { ok: "was", type: "pronoun", keyword: "das, was …", bed: "اللي (حبّوه)",
      text: `"nur das gemacht, ___ sie wollten": بعد "das" كمرجع عامّ نستعملو "was".\n✓ "was" = اللي (das, was …).\n✗ "das" = ممكنة نحويًّا ("das, das")، بصح الأسلوب ثقيل والمعتاد بعد "das" هو "was".\n✗ "welches" = أسلوب قديم ونادر، المعتاد "was".`,
      rule: "nach das / alles / etwas / nichts → was", ex: "Er macht nur das, **was** er will.", exTr: "يعمل غير اللي يحب." },
    30: { ok: "mir", type: "pronoun", keyword: "sich (Dat.) etwas vorstellen können", bed: "نتصوّر",
      text: `"ich kann ___ gar nicht mehr vorstellen" = ما نجّمش نتصوّر: "sich (Dativ) vorstellen".\n✓ "mir" = Dativ لـ "ich" (mir etwas vorstellen).\n✗ "mich" = Akkusativ، و"mich vorstellen" معناها نقدّم روحي (تعريف).\n✗ "sich" = للغائب (er / sie / es)، والفاعل هنا "ich".`,
      rule: "sich (Dat.) etwas vorstellen = imaginieren: ich kann mir vorstellen", ex: "Das kann ich **mir** gut vorstellen.", exTr: "هذا نجّم نتصوّرو مليح." },
  },

  // ───────────── [47] Daniela ─────────────
  47: {
    21: { ok: "eigentlich", type: "adjective_adverb", keyword: "eigentlich (ursprüngliche Absicht)", bed: "في الحقيقة (كنت نحب)",
      text: `"denn ___ wollte ich dir schon vor zwei Monaten schreiben": نيّة قديمة ما تحقّقتش.\n✓ "eigentlich" = في الحقيقة (نيّة أصلية).\n✗ "außerdem" = وزيد (إضافة)، وما تعبّرش على نيّة سابقة.\n✗ "überhaupt" = بالمرّة (تحتاج نفي)، موش مع نيّة إيجابية.`,
      rule: "eigentlich = ursprünglich / in Wahrheit", ex: "**Eigentlich** wollte ich kommen, aber ich war krank.", exTr: "في الحقيقة كنت نحب نجي، بصح كنت مريض." },
    22: { ok: "man", type: "pronoun", keyword: "man (allgemeines Subjekt)", bed: "الواحد",
      text: `الجملة عامّة على أي واحد يحضّر لامتحان: الفاعل العام "man".\n✓ "man" = الواحد (فاعل عام).\n✗ "er" = مذكّر معيّن، وهنا ما فماش شخص محدّد.\n✗ "es" = ضمير شكلي، و"hat es keine Zeit" ما تتقالش.`,
      rule: "man = allgemeines Subjekt (Verb in der 3. Person Singular)", ex: "Wenn **man** müde ist, macht man Fehler.", exTr: "كي يكون الواحد تعبان، يغلط." },
    23: { ok: "dessen", type: "pronoun", keyword: "dessen (Genitiv-Relativpronomen)", bed: "اللي بمساعدتو",
      text: `"Mein Freund, mit ___ Hilfe …" = صاحبي اللي بمساعدتو: Genitiv مذكّر (ملكية) يفتح الجملة الفرعية.\n✓ "dessen" = Genitiv مذكّر (dessen Hilfe = مساعدتو).\n✗ "der" = Dativ مؤنّث أو Nominativ مذكّر، وما تعبّرش على ملكية.\n✗ "seiner" = Possessivartikel (بمساعدتو)، والجملة الفرعية تحتاج Relativpronomen.`,
      rule: "Genitiv-Relativpronomen: dessen (m / n), deren (f / Pl.) — danach kein Artikel", ex: "Mein Nachbar, **dessen** Auto kaputt ist, fährt Bus.", exTr: "جاري اللي كرهبتو خربانة يركب البيّاص." },
    24: { ok: "überstehen", type: "verb", keyword: "eine schwere Zeit überstehen", bed: "نتحمّل (الفترة)",
      text: `"diese ganze Zeit zu ___": الفعل المناسب مع فترة صعيبة: "überstehen" (يتحمّل ويعدّي).\n✓ "überstehen" = يتحمّل / يعدّي (Zeit, Krankheit).\n✗ "übersetzen" = يترجم (أو يعدّي نهر: über den Fluss setzen)، موش تحمّل فترة.\n✗ "übertragen" = ينقل / يبثّ (eine Sendung übertragen)، معنى مختلف.`,
      rule: "etwas überstehen = durchhalten  |  übersetzen = Sprache wechseln  |  übertragen = weitergeben", ex: "Wir müssen den Winter **überstehen**.", exTr: "لازمنا نعدّيو الشتاء." },
    25: { ok: "ob", type: "conjunction", keyword: "fragen, ob …", bed: "هل",
      text: `"du hast mich gefragt, ___ ich Lust hätte": سؤال بجواب نعم / لا.\n✓ "ob" = هل (whether).\n✗ "dass" = إنّو (خبر)، والجملة هنا سؤال.\n✗ "falls" = في صورة (شرط)، موش سؤال.`,
      rule: "fragen, ob + Nebensatz (indirekte Ja/Nein-Frage)", ex: "Sie fragte, **ob** ich Zeit habe.", exTr: "سألت هل عندي وقت." },
    26: { ok: "unternehmen", type: "verb", keyword: "etwas unternehmen", bed: "نعمل (حاجة)",
      text: `"etwas Tolles zu ___": نشاط نعملوه مع صاحبة: "unternehmen".\n✓ "unternehmen" = يعمل نشاط (etwas Tolles unternehmen).\n✗ "verbringen" = يقضّي (Zeit verbringen)، والمفعول به عادة الوقت، و"etwas Tolles verbringen" ما تتقالش.\n✗ "verplanen" = يخطّط مسبقًا (Zeit verplanen)، موش يعمل نشاط.`,
      rule: "etwas unternehmen = Aktivität machen  |  Zeit verbringen  |  Zeit verplanen", ex: "Am Wochenende wollen wir etwas **unternehmen**.", exTr: "في نهاية الأسبوع نحبّو نعملو حاجة." },
    27: { ok: "ganz", type: "adjective_adverb", keyword: "ganz besonders", bed: "خصوصًا",
      text: `"ganz besonders" = خصوصًا (تقوية).\n✓ "ganz" = تمامًا (ganz besonders).\n✗ "recht" = نوعًا ما (recht gut)، و"recht besonders" ما تتقالش.\n✗ "zwar" = صحيح (zwar … aber)، رابط تنازل، موش ظرف درجة.`,
      rule: "ganz besonders = in besonderem Maße (Verstärkung)", ex: "Das Essen hat mir **ganz** besonders geschmeckt.", exTr: "الماكلة عجباتني خصوصًا." },
    28: { ok: "für", type: "verb_prep", keyword: "sich interessieren für + Akk.", bed: "نهتمّ بـ",
      text: `"sich interessieren" يتبعو "für" + Akkusativ: "für die Tate Gallery".\n✓ "für" = بـ (sich interessieren für).\n✗ "auf" = على (sich freuen auf)، و"sich interessieren auf" ما تتقالش.\n✗ "in" = في (sich auskennen in)، و"interessieren in" ما تتقالش.`,
      rule: "sich interessieren für + Akk. (nicht: auf / in)", ex: "Ich interessiere mich **für** Geschichte.", exTr: "نهتمّ بالتاريخ." },
    29: { ok: "doch", type: "adjective_adverb", keyword: "doch im Imperativ (freundliche Aufforderung)", bed: "تشجيع لطيف (هيّا)",
      text: `"Mach doch einfach ein paar Vorschläge": الأمر يتلطّف بـ "doch".\n✓ "doch" = تشجيع لطيف في الأمر (Abtönungspartikel).\n✗ "bestimmt" = أكيد (تأكيد توقّع)، وما تلطّفش الأمر.\n✗ "sicher" = أكيد / بأمان، وتجي في جمل خبرية ("ganz sicher")، موش في الأمر.`,
      rule: "doch im Imperativ = freundliche Aufforderung / Ermunterung", ex: "Komm **doch** einfach vorbei!", exTr: "عدّي لعندنا ساهل!" },
    30: { ok: "uns", type: "pronoun", keyword: "sich einigen (wir → uns)", bed: "نتفقو",
      text: `"sich einigen" فعل انعكاسي، والفاعل "wir" (أنا وصاحبتي): "wir … uns einigen".\n✓ "uns" = انعكاسي لـ "wir".\n✗ "euch" = انعكاسي لـ "ihr" (إنتوما)، والفاعل "wir".\n✗ "sich" = انعكاسي للغائب، وما يتماشاش مع "wir".`,
      rule: "reflexives Verb: wir → uns (sich einigen auf)", ex: "Wir haben **uns** schnell geeinigt.", exTr: "اتفقنا بسرعة." },
  },

  // ───────────── [48] Frau Melchior – Dresden-Reise ─────────────
  48: {
    21: { ok: "in dem", type: "pronoun", keyword: "Präposition + Relativpronomen: in dem", bed: "اللي فيه (الرسالة)",
      text: `"Schreiben" (محايد) والسؤال تمّ فيه، يعني "في الرسالة": حرف جر + Relativpronomen: "in dem".\n✓ "in dem" = اللي فيه (in + dem، Dativ محايد).\n✗ "für das" = لـ (غرض)، وما تتماشاش مع "gebeten haben" (الرسالة اللي فيها طلبتي).\n✗ "von dem" = من / عن (مصدر)، وتجي مع أفعال مثل "sprechen von"، موش مع "bitten um" في الرسالة.`,
      rule: "Relativsatz: Präposition + Relativpronomen (im Schreiben → in dem)", ex: "Das Formular, **in dem** Sie alles eintragen, liegt bei.", exTr: "الاستمارة اللي فيها تكتب كلّ شي، مرفقة." },
    22: { ok: "Da", type: "conjunction", keyword: "da + Nebensatz (bekannter Grund)", bed: "بما إنّو",
      text: `سبب معروف: البرنامج مازال ما خلصش، فنعطيو معلومات أولية: "Da".\n✓ "Da" = بما إنّو (+ فعل في الآخر).\n✗ "Wann" = إمتى (سؤال)، موش رابط سبب.\n✗ "Wenn" = إذا / كلّما (شرط)، والمعلومة هنا حقيقة مؤكّدة ما فيهاش شرط.`,
      rule: "da / weil + Nebensatz (Verb am Ende)", ex: "**Da** der Zug Verspätung hat, warten wir.", exTr: "بما إنّو التران متأخّر، نستنّاو." },
    23: { ok: "Untergebracht", type: "verb", keyword: "untergebracht sein", bed: "مسكونين",
      text: `"Untergebracht sind Sie im Hotel Corona" = إقامتكم في نزل كورونا: "untergebracht sein".\n✓ "Untergebracht" = مسكّن (Zustandspassiv: untergebracht sein).\n✗ "Verbracht" = قضّى (Zeit verbringen)، موش سكن.\n✗ "Zugebracht" = قضّى (أسلوب قديم: Zeit zubringen)، موش مناسب لوصف الإقامة.`,
      rule: "untergebracht sein = eine Unterkunft haben (Zustandspassiv)", ex: "Die Gäste sind im Hotel **untergebracht**.", exTr: "الضيوف مسكّنين في النزل." },
    24: { ok: "sich", type: "pronoun", keyword: "sich befinden", bed: "(الفندق) يوجد",
      text: `"befinden" فعل انعكاسي، والفاعل "das" (الهوتيل) غائب: "das sich befindet".\n✓ "sich" = انعكاسي للغائب.\n✗ "man" = الواحد، والفاعل هنا "das" (الهوتيل) موش "man".\n✗ "Sie" = ضمير المخاطب الرسمي، موش الفاعل.`,
      rule: "sich befinden = liegen (Reflexivpronomen = Subjekt: das → sich)", ex: "Das Museum befindet **sich** im Zentrum.", exTr: "المتحف موجود في المركز." },
    25: { ok: "gezeigt", type: "tense", keyword: "gezeigt werden (Passiv)", bed: "تتورّى",
      text: `"Ihnen alle Sehenswürdigkeiten ___ werden": الأشخاص (Ihnen) تتورّالهم الأماكن: "gezeigt werden".\n✓ "gezeigt" = Partizip II من "zeigen" (Vorgangspassiv).\n✗ "geschaut" = تفرّج (فعل لازم)، وما يتركّبش مع Dativ شخص ومعنى "تتورّى".\n✗ "gesehen" = تتشاف: ممكنة نحويًّا، بصح الـ "Ihnen" (Dativ) يطلب فعل يعطي لشخص (zeigen).`,
      rule: "jdm. etwas zeigen → Passiv: etwas wird jdm. gezeigt", ex: "Den Gästen wird die Stadt **gezeigt**.", exTr: "يوريو الضيوف المدينة." },
    26: { ok: "der", type: "grammar_structure", keyword: "Nomen + Genitiv: der", bed: "متاع (الأوبرا)",
      text: `"Besuch" + Genitiv مؤنّث: "Besuch der Semper-Oper".\n✓ "der" = Genitiv مؤنّث.\n✗ "die" = Nominativ / Akkusativ مؤنّث، واللي بعد الاسم لازم Genitiv.\n✗ "von" = "Besuch von der …" ممكنة كلاميًّا، بصح "von Semper-Oper" بدون أداة ما تتقالش.`,
      rule: "Nomen + Genitiv (fem.: der): Besuch der Oper", ex: "Der Besuch **der** Altstadt dauert zwei Stunden.", exTr: "زيارة المدينة القديمة تاخذ ساعتين." },
    27: { ok: "für", type: "verb_prep", keyword: "berühmt für + Akk.", bed: "مشهور بـ",
      text: `"berühmt" يتبعو "für": "berühmt für seine exotischen Pflanzen".\n✓ "für" = بـ (berühmt für + Akk.).\n✗ "mit" = مع، وما تعطيش سبب الشهرة.\n✗ "wegen" = بسبب: تتبعها Genitiv ("wegen seiner Pflanzen")، وهنا "seine" Akkusativ ما تتماشاش.`,
      rule: "berühmt für + Akk.  |  wegen + Genitiv", ex: "Die Stadt ist **für** ihren Käse berühmt.", exTr: "المدينة مشهورة بالجبن متاعها." },
    28: { ok: "steht", type: "fixed_expression", keyword: "zur Verfügung stehen", bed: "على ذمّتكم",
      text: `"zu Ihrer freien Verfügung" يتركّب مع "stehen": "zur Verfügung stehen".\n✓ "steht" = يكون على الذمّة (feste Wendung).\n✗ "fällt" = يطيح / يصادف (auf einen Tag fallen)، و"zur Verfügung fallen" ما تتقالش.\n✗ "liegt" = موجود (مكان)، و"zur Verfügung liegen" ما تتقالش.`,
      rule: "zur Verfügung stehen = verfügbar sein (feste Wendung)", ex: "Das Auto **steht** Ihnen zur Verfügung.", exTr: "الكرهبة على ذمّتكم." },
    29: { ok: "teilnehmen", type: "verb_prep", keyword: "an etwas teilnehmen", bed: "تشاركو",
      text: `"an einer Fahrt … teilnehmen" = يشارك: "teilnehmen an + Dativ".\n✓ "teilnehmen" = يشارك (an + Dat.).\n✗ "beteiligen" = يشارك لكن انعكاسي ("sich an etwas beteiligen")، وما فماش "sich" هنا.\n✗ "fahren" = يسافر، و"an einer Fahrt fahren" فيها تكرار وما تتركّبش مع "an".`,
      rule: "an + Dat. teilnehmen  |  sich an + Dat. beteiligen (reflexiv)", ex: "Möchten Sie an dem Ausflug **teilnehmen**?", exTr: "تحبّ تشارك في الرحلة؟" },
    30: { ok: "verschaffen", type: "verb", keyword: "jdm. einen Überblick verschaffen", bed: "تعطيكم (فكرة شاملة)",
      text: `"Ihnen einen Überblick verschaffen" = تعطيكم فكرة شاملة: فعل مع Dativ شخص.\n✓ "verschaffen" = يعطي / يوفّر (jdm. etwas verschaffen).\n✗ "vermachen" = يوصّي بـ (Erbe vermachen)، معنى مختلف.\n✗ "schaffen" = ينجّح / يخلق: "einen Überblick schaffen" ممكنة، بصح مع "Ihnen" (Dativ) الفعل المعتاد "verschaffen".`,
      rule: "jdm. etwas verschaffen = besorgen / ermöglichen  |  etwas schaffen = erschaffen / bewältigen", ex: "Die Karte soll uns einen Überblick **verschaffen**.", exTr: "الخريطة لازم تعطينا فكرة شاملة." },
  },

  // ───────────── [49] Frau Stein (Neu) (gap 30 FLAGGED: key "dabei" vs. "Wir rechnen ___, dass …" → needs "damit") ─────────────
  49: {
    21: { ok: "Ihres Vortrags", type: "preposition", keyword: "anlässlich + Genitiv", bed: "بمناسبة (محاضرتك)",
      text: `"anlässlich" حرف جر يتبعو دايمًا Genitiv: "anlässlich Ihres Vortrags".\n✓ "Ihres Vortrags" = Genitiv مذكّر (-es / -s).\n✗ "Ihrem Vortrag" = Dativ، و"anlässlich" ما ياخذش Dativ.\n✗ "Ihren Vortrag" = Akkusativ، و"anlässlich" ما ياخذش Akkusativ.`,
      rule: "anlässlich + Genitiv (Anlass)", ex: "**Anlässlich** des Jubiläums gibt es ein Fest.", exTr: "بمناسبة الذكرى فما احتفال." },
    22: { ok: "ob", type: "conjunction", keyword: "anfragen, ob …", bed: "هل",
      text: `"Heute möchte ich anfragen, ___ Sie bereit wären": سؤال بجواب نعم / لا.\n✓ "ob" = هل (whether).\n✗ "wenn" = إذا (شرط)، والجملة هنا سؤال.\n✗ "dass" = إنّو (خبر)، موش سؤال.`,
      rule: "anfragen / fragen, ob + Nebensatz (Ja/Nein-Frage)", ex: "Ich möchte anfragen, **ob** das Zimmer frei ist.", exTr: "نحب نسأل هل الغرفة فارغة." },
    23: { ok: "sowohl...als auch", type: "conjunction", keyword: "sowohl … als auch", bed: "كلّ من… و…",
      text: `الجملة تجمع شيئين: "Vorträge" و"Workshops": الزوج "sowohl … als auch".\n✓ "sowohl...als auch" = كلّ من… و… (الاثنين).\n✗ "und...und" = تركيب غير موجود (الصحيح "sowohl … als auch")، "und" تجي مرة وحدة.\n✗ "zwar...aber" = صحيح… لكن (تنازل / تعارض)، موش جمع بين شيئين.`,
      rule: "sowohl … als auch = beides  |  entweder … oder  |  weder … noch", ex: "Er spricht **sowohl** Deutsch **als auch** Französisch.", exTr: "يحكي ألماني وفرنسي الزوز." },
    24: { ok: "bis", type: "preposition", keyword: "von … bis + Uhrzeit", bed: "لين",
      text: `الفترة: "von 9 Uhr bis 18 Uhr".\n✓ "bis" = لين (von … bis).\n✗ "bis zu" = حتى (+ كمية / حدّ: "bis zu 18 Personen")، وبعد "von" مع الساعة يكفي "bis".\n✗ "bis vor" = ما تتقالش هكا مع ساعة.`,
      rule: "von … bis (Zeitraum)  |  bis zu + Menge / Grenze", ex: "Das Büro ist von 8 **bis** 16 Uhr offen.", exTr: "المكتب مفتوح من 8 لين 16." },
    25: { ok: "deren", type: "pronoun", keyword: "deren (Genitiv-Relativpronomen)", bed: "اللي (مواضيعها)",
      text: `"Expertin, ___ Themen …" = اللي مواضيعها: Genitiv مؤنّث (ملكية) يفتح الجملة الفرعية.\n✓ "deren" = Genitiv مؤنّث (deren Themen = مواضيعها).\n✗ "denen" = Dativ جمع (لهم)، وما فماش جمع مذكور هنا.\n✗ "die" = Nominativ مؤنّث (اللي)، و"die Themen … ansprechen" ما تركّبش جملة صحيحة هكا.`,
      rule: "Genitiv-Relativpronomen: dessen (m / n), deren (f / Pl.)", ex: "Die Frau, **deren** Auto kaputt ist, wartet.", exTr: "المرأة اللي كرهبتها خربانة تستنّى." },
    26: { ok: "Vortragende", type: "noun", keyword: "Vortragende (Partizip I als Nomen)", bed: "محاضِرة",
      text: `"als ___ in unser Programm aufnehmen": نريد شخص يلقي محاضرة: "Vortragende".\n✓ "Vortragende" = المحاضِرة (Partizip I كاسم).\n✗ "Vorgetragene" = اللي تقدّم (Partizip II: "das Vorgetragene")، موش الشخص.\n✗ "Vortrag" = محاضرة (الموضوع)، موش الشخص اللي يلقيها.`,
      rule: "Partizip I als Nomen = handelnde Person: Vortragende / Studierende", ex: "Die **Vortragende** erklärt das Thema.", exTr: "المحاضِرة تشرح الموضوع." },
    27: { ok: "zu sprechen", type: "grammar_structure", keyword: "Möglichkeit geben, … zu + Infinitiv", bed: "باش يحكيو",
      text: `"die Möglichkeit geben, mit Ihnen … ___" يتبعها zu + Infinitiv: "zu sprechen".\n✓ "zu sprechen" = Infinitiv مع "zu" (Möglichkeit geben, … zu + Inf.).\n✗ "geredet haben" = Perfekt، وما تتركّبش بعد "Möglichkeit geben" (حدث مستقبل).\n✗ "sprechen" = Infinitiv بدون "zu"، و"Möglichkeit geben" يطلب "zu".`,
      rule: "Möglichkeit / Chance / Zeit haben (geben) + zu + Infinitiv", ex: "Wir geben ihm die Chance, **zu zeigen**, was er kann.", exTr: "نعطيوه فرصة باش يوري شنوّة يقدر." },
    28: { ok: "zur Verfügung", type: "fixed_expression", keyword: "zur Verfügung stehen", bed: "على ذمّتك",
      text: `"stehen Ihnen … zur Verfügung" = على ذمّتكم: تعبير ثابت.\n✓ "zur Verfügung" = على الذمّة (zur Verfügung stehen).\n✗ "zu Hilfe" = للمساعدة (jdm. zu Hilfe kommen / eilen)، ما تتركّبش مع "stehen" هنا.\n✗ "zum Benutzen" = للاستعمال: ممكنة كلاميًّا، بصح ما هيش التعبير الثابت.`,
      rule: "zur Verfügung stehen = verfügbar sein (feste Wendung)", ex: "Der Raum steht den Gästen **zur Verfügung**.", exTr: "القاعة على ذمّة الضيوف." },
    29: { ok: "ein paar Tage", type: "fixed_expression", keyword: "ein paar Tage vorher", bed: "بأيام قبل",
      text: `"schicken Sie uns diese ___ vorher zu" = ابعثولنا بأيام قبل: مدّة (Akk.) + vorher.\n✓ "ein paar Tage" = بأيام (مدّة قبل الحدث).\n✗ "eines Tages" = يومًا ما (غير محدّد)، موش مدّة قبل الحدث.\n✗ "für einen Tag" = لمدّة يوم، موش "قبل بكم يوم".`,
      rule: "Zeitdauer + vorher / später (Akk.): ein paar Tage vorher", ex: "Schick es mir bitte **ein paar Tage** vorher.", exTr: "ابعثهالي بالله بأيام قبل." },
  },
};
