// SB Teil 2 restyle — batch 04: [17] + [18] Schwarzarbeit, [19] + [20] Bio (note: [20]'s word list has "Entlastet" AND "ENTLASTET" — scoring is case-insensitive so both count), [21] Teamarbeit
export default {
  // ───────────── [17] Schwarzarbeit kann teuer werden ( Original ) ─────────────
  17: {
    31: { ok: "ANSTATT", type: "conjunction", keyword: "anstatt … zu + Infinitiv", bed: "عوض (ما)",
      text: `"zahlt der Kunde drauf, ___ … Geld zu sparen": بدل ما يوفّر، يخسر: "anstatt … zu".\n✓ "anstatt" = عوض (anstatt … zu + Infinitiv).\n✗ "um" = باش (um … zu = غرض): نفس الشكل، بصح المعنى هنا عكس المتوقّع (خسارة عوض التوفير) موش غرض.\n✗ "dagegen" = بالمقابل / ضدّ هذا (ظرف)، وما تبنيش Infinitivsatz.`,
      rule: "anstatt … zu = Gegenteil des Erwarteten  |  um … zu = Zweck", ex: "Er schläft, **anstatt** zu lernen.", exTr: "هو يرقد عوض ما يقرا." },
    32: { ok: "JEDE", type: "pronoun", keyword: "nicht jede + Nomen", bed: "كلّ (موش كلّ…)",
      text: `"nicht ___ Gelegenheit so günstig": "nicht jede Gelegenheit" = موش كلّ فرصة، و"Gelegenheit" مؤنّث مفرد.\n✓ "jede" = كلّ (Femininum Singular).\n✗ "alles" = كلّ شي (محايد)، و"nicht alles Gelegenheit" ما تتقالش.\n✗ "solche" = مثل هذي (جمع أو بأداة)، و"solche Gelegenheit" بدون أداة ما تتقالش.`,
      rule: "jed- + Singular: jede Gelegenheit, jeder Mann, jedes Kind", ex: "Nicht **jede** Frage ist leicht.", exTr: "موش كلّ سؤال سهل." },
    33: { ok: "GEGEN", type: "preposition", keyword: "Argument gegen + Akk.", bed: "ضدّ",
      text: `"ein finanzielles Argument ___ illegale Arbeiter": حجّة ضدّ الشغل غير القانوني.\n✓ "gegen" = ضدّ (+ Akkusativ).\n✗ "dagegen" = ضدّ هذا (Pronominaladverb)، وبعدو اسم ("illegale Arbeiter") موش جملة.\n✗ "um" = حول / باش، و"Argument um illegale Arbeiter" ما تعطيش معنى "ضدّ".`,
      rule: "Argument gegen + Akk.  |  dagegen, wenn kein Nomen folgt", ex: "Das ist ein Argument **gegen** den Plan.", exTr: "هذي حجّة ضدّ الخطّة." },
    34: { ok: "DAVON", type: "pronoun_adverb", keyword: "abgesehen davon, dass …", bed: "من هذا",
      text: `تعبير ثابت: "abgesehen davon, dass …" = بقطع النظر على إنّو.\n✓ "davon" = من هذا (von + das).\n✗ "dagegen" = ضدّ هذا، و"abgesehen dagegen" ما تتقالش.\n✗ "gegen" = ضدّ، وما تكمّلش التعبير الثابت.`,
      rule: "abgesehen von + Dat. → abgesehen davon, dass …", ex: "**Abgesehen davon** ist es teuer.", exTr: "بقطع النظر على هذا، غالي." },
    35: { ok: "WILL", type: "verb", keyword: "will … sehen (Modalverb)", bed: "يحب (يشوف)",
      text: `"Das Finanzamt ___ eine ordentliche Rechnung … sehen": فعل مساعد + Infinitiv بدون "zu".\n✓ "will" = يحب / يطلب (wollen + Infinitiv).\n✗ "wünscht" = يتمنّى: ما ياخذش Infinitiv مباشر بدون "zu" ("wünscht … sehen" ما تتقالش).\n✗ "bilden" = يشكّل (جمع)، والفاعل "Finanzamt" مفرد، ومعناها ما يتماشاش.`,
      rule: "Modalverb + Infinitiv ohne zu: will … sehen", ex: "Der Chef **will** den Bericht sehen.", exTr: "الشاف يحب يشوف التقرير." },
    36: { ok: "BILDEN", type: "verb", keyword: "die Ausnahme bilden", bed: "تشكّل (الاستثناء)",
      text: `"mängelfreie Bauten ___ eher die Ausnahme": "die Ausnahme bilden" = تكون الاستثناء، والفاعل جمع.\n✓ "bilden" = تشكّل (Plural مع "Bauten").\n✗ "bekommen" = يتحصّل على، و"bekommen die Ausnahme" ما تعطيش معنى.\n✗ "wünscht" = مفرد (3. Person)، والفاعل "Bauten" جمع.`,
      rule: "die Ausnahme / die Regel bilden = sein", ex: "Gute Noten **bilden** hier die Regel.", exTr: "النقط الباهية هنا هي القاعدة." },
    37: { ok: "AUSGEHEN", type: "verb", keyword: "leer ausgehen", bed: "يخرج بدون شيء",
      text: `تعبير ثابت: "leer ausgehen" = يخرج بدون تعويض / بدون شيء.\n✓ "ausgehen" = يخرج (leer ausgehen).\n✗ "bekommen" = يتحصّل، و"leer bekommen" ما تتقالش.\n✗ "bilden" = يشكّل، وما يتركّب مع "leer".`,
      rule: "leer ausgehen = nichts bekommen (feste Wendung)", ex: "Die anderen gingen **leer aus**.", exTr: "الباقي خرجو بدون شيء." },
    38: { ok: "SOLCHE", type: "pronoun", keyword: "solche + Plural", bed: "مثل هذي",
      text: `"für ___ Fälle eine Haftpflichtversicherung": "solche Fälle" = حالات كيما هذي (جمع Akkusativ).\n✓ "solche" = مثل هذي (جمع).\n✗ "jede" = كلّ (مفرد)، و"jede Fälle" ما تتطابقش (Fälle جمع).\n✗ "alles" = كلّ شي (محايد)، و"alles Fälle" ما تتقالش.`,
      rule: "solche + Plural (solche Fälle, solche Leute)", ex: "Für **solche** Fälle gibt es Regeln.", exTr: "لمثل هذي الحالات فما قوانين." },
    39: { ok: "BEKOMMEN", type: "verb", keyword: "mitbekommen (bekommen … mit)", bed: "يتفطّنو (يعرفو)",
      text: `"dann ___ es gleich mehrere Behörden mit": الفعل المنفصل "mitbekommen" = يتفطّن.\n✓ "bekommen" = (bekommen … mit، جمع).\n✗ "bilden" = يشكّل، وما عندو جزء "mit".\n✗ "ausgehen" = يخرج، وما يكمّلش "mit" ("geht mit aus" معنى آخر).`,
      rule: "trennbar: mitbekommen → bekommt / bekommen … mit = etwas erfahren", ex: "Die Nachbarn **bekommen** alles **mit**.", exTr: "الجيران يتفطّنو لكلّ شي." },
    40: { ok: "MEISTENS", type: "adjective_adverb", keyword: "meistens (in den meisten Fällen)", bed: "في الغالب",
      text: `"braucht der Auftraggeber ___ einen Anwalt": ظرف تكرار: في الغالب.\n✓ "meistens" = في الغالب.\n✗ "höchstens" = على أقصى تقدير: ممكنة نحويًّا، بصح تقلّل ("غير محامي واحد") وما تتماشاش مع سياق خسائر كبيرة.\n✗ "alles" = كلّ شي (ضمير)، موش ظرف.`,
      rule: "meistens = in den meisten Fällen  |  höchstens = nicht mehr als", ex: "Er kommt **meistens** zu spät.", exTr: "هو يجي في الغالب متأخّر." },
  },

  // ───────────── [18] Schwarzarbeit kann teuer werden (معدل) ─────────────
  18: {
    31: { ok: "ANSTATT", type: "conjunction", keyword: "anstatt … zu", bed: "عوض (ما)",
      text: `"schnell zahlt der Kunde drauf, ___ … Geld zu sparen": الخسارة بدل التوفير.\n✓ "anstatt" = عوض (anstatt … zu + Infinitiv).\n✗ "um" = باش: نفس الشكل (um … zu)، بصح هنا المعنى عكس الغرض.\n✗ "dagegen" = بالمقابل (ظرف)، ما تبنيش Infinitivsatz.`,
      rule: "anstatt zu + Infinitiv = statt etwas anderes zu tun", ex: "Sie kauft ein, **anstatt** zu sparen.", exTr: "هي تشري عوض ما توفّر." },
    32: { ok: "JEDE", type: "pronoun", keyword: "jede (Femininum)", bed: "كلّ",
      text: `"nicht ___ Gelegenheit so günstig, wie sie anfangs scheint": "Gelegenheit" مؤنّث مفرد.\n✓ "jede" = كلّ (مؤنّث مفرد).\n✗ "alles" = كلّ شي (محايد)، ما يتطابقش مع "Gelegenheit".\n✗ "solche" = جمع / يحتاج أداة، موش مع "Gelegenheit" مفرد.`,
      rule: "jede + Femininum Singular (jede Chance, jede Stunde)", ex: "Nicht **jede** Reise ist teuer.", exTr: "موش كلّ سفرة غالية." },
    33: { ok: "GEGEN", type: "preposition", keyword: "gegen + Akk.", bed: "ضدّ",
      text: `"ein Argument ___ illegale Arbeiter": حجّة ضدّ.\n✓ "gegen" = ضدّ (+ Akkusativ).\n✗ "dagegen" = ضدّ هذا، يجي بدون اسم بعدو، وهنا "illegale Arbeiter".\n✗ "um" = حول، وما تعطيش معنى المعارضة.`,
      rule: "gegen + Akk. = Gegenposition (ein Argument gegen etwas)", ex: "Ich habe nichts **gegen** ihn.", exTr: "ما عنديش حاجة ضدّو." },
    34: { ok: "DAVON", type: "pronoun_adverb", keyword: "abgesehen davon", bed: "من هذا",
      text: `"Abgesehen ___, dass es strafbar ist": تعبير ثابت يتبعو dass-Satz.\n✓ "davon" = من هذا (von + das).\n✗ "dagegen" = ضدّ هذا، ما يتركّبش مع "abgesehen".\n✗ "gegen" = ضدّ، وما يكمّلش التعبير الثابت.`,
      rule: "abgesehen davon, dass … = außer dass …", ex: "**Abgesehen davon**, dass es regnet, war es schön.", exTr: "بقطع النظر على المطر، كان زين." },
    35: { ok: "WILL", type: "verb", keyword: "wollen + Infinitiv", bed: "يحب",
      text: `"Das Finanzamt ___ eine ordentliche Rechnung … sehen": الفاعل مفرد.\n✓ "will" = يحب / يطلب (3. Person Singular).\n✗ "wünscht" = يتمنّى، ما ياخذش Infinitiv بدون "zu".\n✗ "wechseln" = Infinitiv / جمع (يبدّل)، موش فعل مصرّف مفرد.`,
      rule: "er / sie / es will + Infinitiv", ex: "Er **will** die Wahrheit hören.", exTr: "هو يحب يسمع الحقيقة." },
    36: { ok: "STELLEN", type: "verb", keyword: "darstellen (stellen … dar)", bed: "تمثّل",
      text: `"mängelfreie Bauten ___ eher die Ausnahme dar": الفعل المنفصل "darstellen" = يمثّل.\n✓ "stellen" = (stellen … dar، جمع).\n✗ "wechseln" = يبدّل، و"wechseln die Ausnahme dar" ما تتقالش.\n✗ "bekommen" = يتحصّل، وما عندو جزء "dar".`,
      rule: "trennbar: darstellen → stellen … dar = sein / bedeuten", ex: "Diese Zahlen **stellen** ein Problem **dar**.", exTr: "هذي الأرقام تمثّل مشكل." },
    37: { ok: "AUSGEHEN", type: "verb", keyword: "leer ausgehen", bed: "يخرج بدون شيء",
      text: `"Verbraucher leer ___": تعبير ثابت: بدون تعويض.\n✓ "ausgehen" = يخرج (leer ausgehen).\n✗ "wechseln" = يبدّل، ما يتركّبش مع "leer".\n✗ "bekommen" = يتحصّل، و"leer bekommen" ما تتقالش.`,
      rule: "leer ausgehen = nichts erhalten", ex: "Wer zu spät kommt, **geht** leer **aus**.", exTr: "اللي يجي متأخّر يخرج بدون شيء." },
    38: { ok: "SOLCHE", type: "pronoun", keyword: "solche Fälle", bed: "مثل هذي",
      text: `"für ___ Fälle": "Fälle" جمع، ونحتاج مطابقة.\n✓ "solche" = مثل هذي (جمع).\n✗ "jede" = كلّ (مفرد)، ما تتطابقش مع "Fälle".\n✗ "alles" = كلّ شي (محايد)، ما يتركّبش مع جمع.`,
      rule: "solche + Plural-Nomen", ex: "**Solche** Probleme sind selten.", exTr: "مثل هذي المشاكل نادرة." },
    39: { ok: "BEKOMMEN", type: "verb", keyword: "mitbekommen", bed: "يتفطّنو",
      text: `"dann ___ es gleich mehrere Behörden mit": "mitbekommen" = يتفطّن (منفصل).\n✓ "bekommen" = (bekommen … mit).\n✗ "wechseln" = يبدّل، ما عندو معنى "mit" هنا.\n✗ "ausgehen" = يخرج، ما يكمّلش "mit".`,
      rule: "mitbekommen = etwas erfahren (trennbar)", ex: "Ich **bekomme** nichts **mit**.", exTr: "ما نتفطّنش لحتى شي." },
    40: { ok: "MEISTENS", type: "adjective_adverb", keyword: "meistens", bed: "في الغالب",
      text: `"braucht der Auftraggeber ___ einen Anwalt": ظرف تكرار.\n✓ "meistens" = في الغالب.\n✗ "alles" = ضمير (كلّ شي)، موش ظرف تكرار.\n✗ "jede" = كلّ (مؤنّث)، و"jede einen Anwalt" ما تتقالش.`,
      rule: "meistens = oft / in der Regel", ex: "Sie fährt **meistens** mit dem Bus.", exTr: "هي تسافر في الغالب بالبيّاص." },
  },

  // ───────────── [19] Was steckt hinter "Bio"? ( Original ) ─────────────
  19: {
    31: { ok: "OB", type: "conjunction", keyword: "sich fragen, ob …", bed: "هل",
      text: `"Viele Verbraucher fragen sich, ___ Bio-Produkte … die gesünderen sind": سؤال بجواب نعم / لا.\n✓ "ob" = هل (indirekte Ja/Nein-Frage).\n✗ "dass" = إنّو (خبر)، و"sich fragen, dass" ما تتقالش.\n✗ "wenn" = إذا (شرط)، موش سؤال.`,
      rule: "sich fragen, ob … (Ja/Nein-Frage)  |  dass = Aussage", ex: "Ich frage mich, **ob** er kommt.", exTr: "نسأل روحي هل باش يجي." },
    32: { ok: "AUSSERDEM", type: "adjective_adverb", keyword: "außerdem + Verb", bed: "وزيد",
      text: `"___ sind Bio-Produkte teurer": نضيفو حجّة أخرى، والفعل "sind" بعد الظرف.\n✓ "außerdem" = وزيد (إضافة، الفعل في الثانية).\n✗ "sogar" = حتى: ممكنة نحويًّا، بصح الجملة تضيف نقطة جديدة (السعر) موش مبالغة.\n✗ "sondern" = بل (تصحيح بعد نفي)، وما فماش نفي قبلها.`,
      rule: "außerdem = zusätzlich  |  sogar = überraschende Steigerung", ex: "Das Auto ist alt, **außerdem** ist es kaputt.", exTr: "الكرهبة قديمة، وزيد خربانة." },
    33: { ok: "ENTHALTEN", type: "verb", keyword: "enthalten (Plural)", bed: "تحتوي",
      text: `"Sie ___ weniger Nitrat, mehr Nährstoffe": "Sie" هنا جمع (Bio-Lebensmittel).\n✓ "enthalten" = تحتوي (Plural).\n✗ "verwendet" = مفرد / Partizip II (يستعمل)، وما يطابقش الفاعل الجمع.\n✗ "entlastet" = مفرد / Partizip II (يخفّف)، ونفس المشكل ومعناه ما يتماشاش.`,
      rule: "enthalten = in sich haben (sie enthalten)", ex: "Die Früchte **enthalten** viele Vitamine.", exTr: "الغلال تحتوي على برشا فيتامينات." },
    34: { ok: "HINTER", type: "preposition", keyword: "hinter + Dativ", bed: "وراء",
      text: `"steht ___ ihrem Einkaufsverhalten ein ökologisches Bewusstsein": المحرّك الخفي وراء السلوك.\n✓ "hinter" = وراء (+ Dativ).\n✗ "an" = عند / على، و"steht an ihrem Einkaufsverhalten" معناها بجنب، موش وراء.\n✗ "auf" = على، و"steht auf ihrem Einkaufsverhalten" ما تعطيش معنى السبب.`,
      rule: "hinter etwas stehen = der Grund / die Motivation sein", ex: "**Hinter** dem Erfolg steht viel Arbeit.", exTr: "وراء النجاح برشا خدمة." },
    35: { ok: "ENTLASTET", type: "verb", keyword: "entlasten (Singular)", bed: "تخفّف (على)",
      text: `"Sie ___ unsere Umwelt": "Sie" = الزراعة البيئية (مفرد)، تخفّف الضغط على البيئة.\n✓ "entlastet" = تخفّف الحمل (3. Person Singular).\n✗ "enthalten" = جمع (تحتوي)، والفاعل مفرد، ومعناها ما يتماشاش.\n✗ "verwendet" = يستعمل، و"verwendet unsere Umwelt" ما تعطيش معنى.`,
      rule: "jdn. / etwas entlasten = den Druck verringern", ex: "Der Bus **entlastet** die Straßen.", exTr: "البيّاص يخفّف الضغط على الطرقات." },
    36: { ok: "AUS", type: "preposition", keyword: "kommen aus + Dativ", bed: "من",
      text: `"Bio-Lebensmittel kommen ___ ökologischer Landwirtschaft": المصدر: "kommen aus".\n✓ "aus" = من (المصدر: kommen aus).\n✗ "an" = عند / على، و"kommen an ökologischer" ما تتقالش.\n✗ "für" = لـ، وما تعبّرش على المصدر.`,
      rule: "kommen aus + Dativ (Herkunft)", ex: "Das Gemüse **kommt** aus dem Garten.", exTr: "الخضرة جاية من الجنينة." },
    37: { ok: "AUF", type: "preposition", keyword: "auf Wochenmärkten verkaufen", bed: "في (الأسواق)",
      text: `"verkauft, beispielsweise ___ Wochenmärkten": المكان: "auf dem Markt".\n✓ "auf" = في (auf + Dativ: auf Märkten).\n✗ "an" = عند: "an Märkten" ممكنة نادرًا، بصح مع الأسواق يتقال "auf".\n✗ "hinter" = وراء، موش مكان البيع.`,
      rule: "auf dem Markt / auf Märkten (Ort des Verkaufs)", ex: "Man kauft Obst **auf** dem Markt.", exTr: "الواحد يشري الغلال في السوق." },
    38: { ok: "VERWENDET", type: "verb", keyword: "verwendet werden (Passiv)", bed: "يتستعمل",
      text: `"dürfen weder Kunstdünger noch … ___ werden": Passiv مع فعل مساعد: Partizip II + werden.\n✓ "verwendet" = Partizip II من "verwenden" (يستعمل).\n✗ "enthalten" = Partizip II من "enthalten"، وهو فعل لازم ما يتحوّل لـ Passiv هكا.\n✗ "entlastet" = Partizip II من "entlasten" (يخفّف)، ومعناه ما يتماشاش.`,
      rule: "Passiv mit Modalverb: dürfen + Partizip II + werden", ex: "Hier dürfen keine Chemikalien **verwendet** werden.", exTr: "هنا ما يتستعملوش مواد كيميائية." },
    39: { ok: "WIRKLICH", type: "adjective_adverb", keyword: "wirklich (tatsächlich)", bed: "فعلًا",
      text: `"dürfen ___ nur Bio-Lebensmittel benutzt werden": ظرف تأكيد: فعلًا غير.\n✓ "wirklich" = فعلًا / حقًّا.\n✗ "sogar" = حتى، و"dürfen sogar nur" تتناقض (حتى + غير).\n✗ "wenn" = إذا (رابط جملة فرعية)، موش ظرف.`,
      rule: "wirklich = tatsächlich (Verstärkung)", ex: "Das ist **wirklich** wichtig.", exTr: "هذا فعلًا مهمّ." },
    40: { ok: "DASS", type: "conjunction", keyword: "garantieren, dass …", bed: "إنّو",
      text: `"garantieren, ___ die Produkte wirklich "bio" sind": محتوى الضمان.\n✓ "dass" = إنّو (+ فعل في الآخر).\n✗ "ob" = هل (سؤال)، و"garantieren" يطلب خبر موش سؤال.\n✗ "wenn" = إذا (شرط)، موش محتوى ضمان.`,
      rule: "garantieren / versichern, dass + Nebensatz", ex: "Wir garantieren, **dass** alles frisch ist.", exTr: "نضمنو إنّو كلّ شي طازج." },
  },

  // ───────────── [20] Was steckt hinter "Bio"? (معدل) ─────────────
  20: {
    31: { ok: "OB", type: "conjunction", keyword: "ob (indirekte Frage)", bed: "هل",
      text: `"fragen sich, ___ Bio-Produkte nun auch wirklich die gesünderen sind": سؤال غير مباشر.\n✓ "ob" = هل (+ فعل في الآخر).\n✗ "dass" = إنّو (خبر)، موش سؤال.\n✗ "wenn" = إذا (شرط)، و"sich fragen, wenn" ما تتقالش.`,
      rule: "ob = Ja/Nein-Frage im Nebensatz", ex: "Er weiß nicht, **ob** sie kommt.", exTr: "ما يعرفش هل باش تجي." },
    32: { ok: "AUßERDEM", type: "adjective_adverb", keyword: "außerdem", bed: "وزيد",
      text: `"___ sind Bio-Produkte teurer": إضافة نقطة جديدة.\n✓ "außerdem" = وزيد (ظرف، الفعل في الثانية).\n✗ "sondern" = بل (تصحيح بعد نفي)، وما فماش نفي.\n✗ "wenn" = إذا (رابط جملة فرعية + فعل في الآخر)، و"sind" هنا في الثانية.`,
      rule: "außerdem = zusätzlich (Verb Position 2)", ex: "Es ist günstig, **außerdem** liegt es zentral.", exTr: "رخيص، وزيد في وسط البلاد." },
    33: { ok: "ENTHALTEN", type: "verb", keyword: "enthalten (Plural)", bed: "تحتوي",
      text: `"Sie ___ weniger Nitrat, mehr Nährstoffe": الفاعل جمع.\n✓ "enthalten" = تحتوي (جمع).\n✗ "verwendet" = مفرد / Partizip II، وما يطابقش الجمع.\n✗ "belastet" = مفرد (يثقل)، وما يطابقش الجمع، ومعناه عكسي لمدح المنتج.`,
      rule: "enthalten = beinhalten (Plural: enthalten)", ex: "Diese Produkte **enthalten** keinen Zucker.", exTr: "هذي المنتجات ما فيهاش سكر." },
    34: { ok: "HINTER", type: "preposition", keyword: "hinter + Dativ", bed: "وراء",
      text: `"steht ___ ihrem Einkaufsverhalten ein ökologisches Bewusstsein": الدافع وراء الشرا.\n✓ "hinter" = وراء (+ Dativ).\n✗ "an" = عند / على، موش وراء.\n✗ "auf" = على، موش دافع خفي.`,
      rule: "hinter + Dativ = als Hintergrund / Motiv", ex: "**Hinter** dieser Idee steht ein Team.", exTr: "وراء هذي الفكرة فما فريق." },
    35: { ok: "ENTLASTET", type: "verb", keyword: "entlasten ≠ belasten", bed: "تخفّف",
      text: `"Sie ___ unsere Umwelt": الزراعة البيئية تخفّف الضغط على البيئة (مدح).\n✓ "entlastet" = تخفّف (الحمل).\n✗ "belastet" = تثقل: نفس الشكل، بصح المعنى عكسي (ضرر)، والجملة تمدح الزراعة البيئية.\n✗ "verwendet" = تستعمل، و"verwendet unsere Umwelt" ما تعطيش معنى.`,
      rule: "entlasten = den Druck verringern  |  belasten = beschweren / schaden", ex: "Fahrgemeinschaften **entlasten** die Straßen.", exTr: "السفر الجماعي يخفّف الضغط على الطرقات." },
    36: { ok: "AUS", type: "preposition", keyword: "kommen aus", bed: "من",
      text: `"Bio-Lebensmittel kommen ___ ökologischer Landwirtschaft": مصدر المنتج.\n✓ "aus" = من (kommen aus).\n✗ "an" = عند، وما تعبّرش على المصدر.\n✗ "auf" = على، و"kommen auf ökologischer" ما تتقالش.`,
      rule: "kommen aus + Dativ = Herkunft", ex: "Der Käse **kommt** aus der Schweiz.", exTr: "الجبن جاي من سويسرا." },
    37: { ok: "AUF", type: "preposition", keyword: "auf Wochenmärkten", bed: "في (الأسواق)",
      text: `"beispielsweise ___ Wochenmärkten oder in Bio-Supermärkten": مكان البيع.\n✓ "auf" = في (auf + Dativ، الأسواق).\n✗ "an" = عند: ممكنة نادرًا، والمعتاد "auf" مع الأسواق.\n✗ "aus" = من (مصدر)، موش مكان البيع.`,
      rule: "auf dem Markt / auf Märkten (Ort)", ex: "Wir kaufen Fisch **auf** dem Markt.", exTr: "نشريو الحوت من السوق." },
    38: { ok: "VERWENDET", type: "verb", keyword: "verwendet werden", bed: "يتستعمل",
      text: `"dürfen weder Kunstdünger noch … ___ werden": Passiv: Partizip II + werden.\n✓ "verwendet" = Partizip II من "verwenden".\n✗ "enthalten" = فعل لازم، ما يتحوّل لـ Passiv هكا.\n✗ "belastet" = Partizip II من "belasten" (يثقل)، ومعناه ما يتماشاش مع منع المواد.`,
      rule: "Passiv: Modalverb + Partizip II + werden", ex: "Das Gerät darf nicht **verwendet** werden.", exTr: "الجهاز ما يتستعملش." },
    39: { ok: "WIRKLICH", type: "adjective_adverb", keyword: "wirklich", bed: "فعلًا",
      text: `"dürfen ___ nur Bio-Lebensmittel benutzt werden": تأكيد.\n✓ "wirklich" = فعلًا.\n✗ "wenn" = إذا (رابط)، موش ظرف.\n✗ "sondern" = بل (تصحيح بعد نفي)، وما فماش نفي.`,
      rule: "wirklich = tatsächlich", ex: "Er ist **wirklich** nett.", exTr: "هو فعلًا لطيف." },
    40: { ok: "DASS", type: "conjunction", keyword: "dass-Satz nach garantieren", bed: "إنّو",
      text: `"Diese Richtlinien garantieren, ___ die Produkte wirklich "bio" sind": محتوى الضمان.\n✓ "dass" = إنّو (+ فعل في الآخر).\n✗ "ob" = هل (سؤال)، و"garantieren" يطلب خبر.\n✗ "wenn" = إذا (شرط)، موش محتوى.`,
      rule: "dass + Nebensatz (Inhalt)", ex: "Ich hoffe, **dass** du bald kommst.", exTr: "نتمنّى إنّك تجي قريب." },
  },

  // ───────────── [21] Teamarbeit als Schlüssel zum Erfolg ─────────────
  21: {
    31: { ok: "NACHWEISEN", type: "verb", keyword: "konnte … nachweisen", bed: "يثبت",
      text: `"Ein … Forscherteam konnte eindrücklich ___, dass …": بعد "konnte" Infinitiv، و"nachweisen, dass" = يثبت إنّو.\n✓ "nachweisen" = يثبت (Infinitiv بعد konnte).\n✗ "erbringen" = يقدّم: يحتاج مفعول ("den Beweis erbringen")، و"erbringen, dass" ما تتقالش.\n✗ "geben" = يعطي، و"geben, dass" ما تتقالش.`,
      rule: "nachweisen, dass … = beweisen  |  einen Beweis erbringen", ex: "Die Studie konnte den Zusammenhang **nachweisen**.", exTr: "الدراسة نجّمت تثبت العلاقة." },
    32: { ok: "ZU", type: "preposition", keyword: "fähig zu + Dativ", bed: "قادر على",
      text: `"dass auch Schimpansen ___ echter Teamarbeit fähig sind": "fähig zu" = قادر على.\n✓ "zu" = على (fähig zu + Dativ).\n✗ "nur" = غير / برك: "echter Teamarbeit fähig" ممكنة (Genitiv قديم)، بصح "nur" تتناقض مع "auch".\n✗ "wie" = كيما، و"wie echter Teamarbeit" ما تعطيش معنى.`,
      rule: "fähig zu + Dativ (zur Teamarbeit fähig sein)", ex: "Er ist **zu** vielem fähig.", exTr: "هو قادر على برشا حاجات." },
    33: { ok: "DAZU", type: "pronoun_adverb", keyword: "dazu (für diesen Zweck)", bed: "لهذا (الغرض)",
      text: `"___ bekam einer der beiden Affen zwei Werkzeuge": لأجل التجربة (للغرض هذا).\n✓ "dazu" = لهذا الغرض (zu + das، الفعل في الثانية).\n✗ "davon" = من هذا، و"Davon bekam einer" معناها "من هذا" (تقسيم)، موش الغرض.\n✗ "bekanntlich" = كما هو معروف: ممكنة نحويًّا، بصح ما تعبّرش على الغرض من التجربة.`,
      rule: "dazu = zu diesem Zweck  |  davon = von diesem / von diesen", ex: "Er ist müde, **dazu** hat er Hunger.", exTr: "هو تعبان، وزيد جيعان." },
    34: { ok: "DAVON", type: "pronoun_adverb", keyword: "eines davon", bed: "واحد منهم",
      text: `"musste er aber eines ___ an seine Artgenossen weitergeben": واحد من الاثنين.\n✓ "davon" = منهم (von + das / von diesen: eines davon).\n✗ "dazu" = زيادة على هذا ("eines dazu" = واحد زيادة)، موش واحد منهم.\n✗ "bekanntlich" = كما هو معروف (ظرف)، وما تعطيش معنى "منهم".`,
      rule: "eines / keines / viele davon = aus der genannten Gruppe", ex: "Ich habe zwei Bücher, eines **davon** ist neu.", exTr: "عندي زوز كتب، واحد منهم جديد." },
    35: { ok: "SEI", type: "tense", keyword: "sei … gewesen (Konjunktiv I)", bed: "(قالو) كان",
      text: `"in über 70 Prozent der Versuche ___ es sogar das richtige Werkzeug gewesen, berichten die Forscher": كلام منقول، و"gewesen" ياخذ "sein".\n✓ "sei" = Konjunktiv I من "sein" (sei … gewesen).\n✗ "haben" = فعل مساعد، و"gewesen" يتصرّف مع "sein" موش "haben".\n✗ "konnten" = Präteritum جمع من "können"، وما تركّبش مع "gewesen".`,
      rule: "indirekte Rede, Perfekt: sei … gewesen / habe … gehabt", ex: "Er sagt, es **sei** ein Fehler gewesen.", exTr: "يقول إنّو كانت غلطة." },
    36: { ok: "NUR", type: "adjective_adverb", keyword: "nur beim Menschen", bed: "فقط",
      text: `"ob diese Eigenschaft ___ beim Menschen vorhanden ist": سؤال: الخاصية موجودة غير عند الإنسان؟\n✓ "nur" = فقط / غير.\n✗ "wie" = كيما: "wie beim Menschen" ممكنة نحويًّا (تشبيه)، بصح السؤال يتعلّق بالحصر موش بالتشبيه.\n✗ "zu" = إلى، ما تتركّبش هنا قبل "beim Menschen".`,
      rule: "nur = ausschließlich (nur beim Menschen)", ex: "Das gibt es **nur** hier.", exTr: "هذا يوجد غير هنا." },
    37: { ok: "KONNTEN", type: "verb", keyword: "konnten (Präteritum, Plural)", bed: "نجّمو",
      text: `"damit die Trauben … fielen und die Affen sie fressen ___": الفاعل جمع، وماضي، وإمكانية.\n✓ "konnten" = Präteritum جمع من "können".\n✗ "mussten" = لازمهم: وما يتماشاش مع "damit" (الغرض: ينجّمو ياكلو).\n✗ "haben" = فعل مساعد، و"fressen haben" ما تتقالش.`,
      rule: "damit … können = Zweck / Möglichkeit (Präteritum: konnten)", ex: "Sie bauten das Tor, damit alle hineingehen **konnten**.", exTr: "بنو الباب باش الكلّ ينجّمو يدخلو." },
    38: { ok: "LIEFERT", type: "verb", keyword: "liefern (Hinweise liefern)", bed: "تقدّم",
      text: `"Diese Studie ___ erste Hinweise darauf": "Hinweise liefern" = تقدّم مؤشّرات، والفاعل مفرد.\n✓ "liefert" = تقدّم (3. Person Singular).\n✗ "förderte" = ماضي من "fördern" (يدعم)، و"förderte Hinweise" ما تعطيش معنى.\n✗ "erbringen" = Infinitiv، وبعد "Studie" نحتاج فعل مصرّف.`,
      rule: "Hinweise / Ergebnisse liefern = zeigen / bringen", ex: "Der Test **liefert** klare Ergebnisse.", exTr: "الاختبار يقدّم نتائج واضحة." },
    39: { ok: "GEBEN", type: "verb", keyword: "Acht geben auf", bed: "ينتبه (لـ)",
      text: `"auf die Handlungen ihres Partners Acht ___ können": تعبير "auf etwas Acht geben" = ينتبه لـ.\n✓ "geben" = (Acht geben، Infinitiv قبل "können").\n✗ "haben" = "Acht haben auf" موجودة لكن أقلّ استعمالًا، والتعبير الأشهر "Acht geben".\n✗ "erbringen" = يقدّم، و"Acht erbringen" ما تتقالش.`,
      rule: "auf etwas Acht geben = aufpassen  |  (seltener) Acht haben auf", ex: "Du musst auf die Kinder **Acht geben**.", exTr: "لازمك تنتبه للصغار." },
    40: { ok: "WIE", type: "conjunction", keyword: "genau wie", bed: "كيما",
      text: `"Genau ___ den Menschen sei es den Affen möglich": مقارنة تشابه: "genau wie".\n✓ "wie" = كيما (genau wie).\n✗ "nur" = فقط، و"Genau nur den Menschen" ما تتقالش.\n✗ "zu" = إلى، و"Genau zu den Menschen" ما تعطيش معنى المقارنة.`,
      rule: "genau wie = ebenso wie (Vergleich der Gleichheit)", ex: "Er läuft **genau wie** sein Vater.", exTr: "هو يجري كيما باباه." },
  },
};
