// SB Teil 2 restyle — batch 11: [52] Schlaf, [53] Menschen helfen Menschen, [54] Hase im Display, [55] Kaffee und Kuchen, [56] Obst und Gemüse
export default {
  // ───────────── [52] Lange schlafen ist gesund, oder etwa nicht? ─────────────
  52: {
    31: { ok: "ÜBERHAUPT", type: "adjective_adverb", keyword: "überhaupt (in Fragen)", bed: "أصلًا",
      text: `"Und warum müssen wir ___ schlafen?": سؤال أساسي: علاش أصلًا لازمنا نرقدو.\n✓ "überhaupt" = أصلًا (يعمّق السؤال).\n✗ "allzu" = برشا زيادة (+ صفة / ظرف)، و"allzu schlafen" ما تتقالش.\n✗ "genauso" = بنفس الشكل، موش ظرف يعمّق السؤال.`,
      rule: "warum … überhaupt? = grundsätzlich / eigentlich", ex: "Warum lernen wir das **überhaupt**?", exTr: "علاش نتعلّمو هذا أصلًا؟" },
    32: { ok: "DAVOR", type: "pronoun_adverb", keyword: "warnen vor → davor, dass", bed: "من هذا",
      text: `"Immer wieder werden wir ___ gewarnt, dass sich zu wenig Schlaf … negativ auswirkt": "warnen vor" ← "davor" + dass-Satz.\n✓ "davor" = من هذا (vor + das).\n✗ "darauf" = على هذا (auf + das)، و"warnen darauf" ما تتقالش.\n✗ "hiermit" = بهذا (mit + hier)، و"gewarnt hiermit" ما تتقالش.`,
      rule: "warnen vor + Dat. → davor warnen, dass …", ex: "Man **warnt** uns **davor**, dass es gefährlich ist.", exTr: "يحذّرونا من إنّو خطير." },
    33: { ok: "GENAUSO", type: "adjective_adverb", keyword: "genauso … wie", bed: "بنفس القدر",
      text: `"zu viel Schlaf ___ ungesund ist wie zu wenig": مقارنة تساوي: "genauso … wie".\n✓ "genauso" = بنفس القدر (genauso + Adjektiv + wie).\n✗ "allzu" = زيادة برشا، و"allzu ungesund ist wie" ما تتقالش.\n✗ "überhaupt" = أصلًا، وما تعطيش معنى تساوي.`,
      rule: "genauso + Adjektiv + wie = gleich … wie", ex: "Er ist **genauso** groß wie ich.", exTr: "هو بنفس طولي." },
    34: { ok: "UNTER", type: "verb_prep", keyword: "leiden unter + Dativ", bed: "يعاني من",
      text: `"Notorische Langschläfer leiden … häufiger ___ Depressionen": "leiden unter" = يعاني من.\n✓ "unter" = من (leiden unter + Dativ).\n✗ "mit" = مع، و"leiden mit" معناها يتعاطف مع (شخص)، موش يعاني من مرض.\n✗ "davor" = من هذا (Pronominaladverb)، وبعدو اسم ("Depressionen") موش جملة.`,
      rule: "leiden unter + Dat. (unter Stress, unter Lärm)  |  leiden an + Dat. (Krankheit)", ex: "Er **leidet** unter Schlafmangel.", exTr: "هو يعاني من نقص النوم." },
    35: { ok: "STIMMT", type: "verb", keyword: "Das stimmt (so nicht)", bed: "صحيح",
      text: `"Das ___ so aber nicht": "stimmen" = يكون صحيح، والفاعل "das" مفرد.\n✓ "stimmt" = صحيح (3. Person مفرد).\n✗ "findet" = يتلقى / يصير: "findet … statt" يحتاج "statt" في الآخر.\n✗ "nimmt" = ياخذ، و"Das nimmt so aber nicht" ما تتقالش.`,
      rule: "etwas stimmt = ist richtig / korrekt", ex: "Das **stimmt** nicht ganz.", exTr: "هذا موش صحيح تمامًا." },
    36: { ok: "SONDERN", type: "conjunction", keyword: "nicht …, sondern vielmehr …", bed: "بل",
      text: `"nicht die Uhrzeit entscheidend ist, ___ vielmehr die ersten Stunden": تصحيح بعد النفي.\n✓ "sondern" = بل (تصحيح بعد "nicht").\n✗ "hiermit" = بهذا (ظرف)، موش رابط.\n✗ "darauf" = على هذا / بعد هذا (ظرف)، موش رابط تصحيح.`,
      rule: "nicht A, sondern (vielmehr) B", ex: "Nicht der Preis zählt, **sondern** die Qualität.", exTr: "موش السعر اللي يهمّ، بل الجودة." },
    37: { ok: "FINDET", type: "verb", keyword: "stattfinden (findet … statt)", bed: "يصير",
      text: `"In dieser Zeit ___ ein Großteil des wertvollen Tiefschlafs statt": الفعل المنفصل "stattfinden" = يصير.\n✓ "findet" = (findet … statt، 3. Person مفرد).\n✗ "nimmt" = ياخذ: "nimmt … statt" ما تتقالش.\n✗ "stimmt" = صحيح، و"stimmt … statt" ما تتقالش.`,
      rule: "trennbar: stattfinden → findet … statt = geschehen", ex: "Das Konzert **findet** heute **statt**.", exTr: "الحفلة تصير اليوم." },
    38: { ok: "ROLLE", type: "fixed_expression", keyword: "keine Rolle spielen", bed: "دور",
      text: `"spielt dabei keine ___": تعبير ثابت: "eine Rolle spielen" = يلعب دور / يهمّ.\n✓ "Rolle" = دور (keine Rolle spielen).\n✗ "Bedeutung" = أهمّية: "Bedeutung haben" / "keine Bedeutung" ممكنة، بصح مع "spielt" التعبير المعتاد "Rolle".\n✗ "Ruhe" = هدوء، و"keine Ruhe spielen" ما تتقالش.`,
      rule: "eine Rolle spielen = wichtig sein  |  Bedeutung haben", ex: "Das Alter spielt keine **Rolle**.", exTr: "العمر ما يهمّش." },
    39: { ok: "ALLZU", type: "adjective_adverb", keyword: "nicht allzu viel", bed: "برشا زيادة",
      text: `"dass im Schlaf nicht ___ viel passiert": "nicht allzu viel" = موش برشا بزّاف.\n✓ "allzu" = زيادة برشا (nicht allzu viel).\n✗ "überhaupt" = أصلًا: ترتيبها "überhaupt nicht viel"، و"nicht überhaupt viel" ما تتقالش.\n✗ "genauso" = بنفس القدر، موش درجة.`,
      rule: "nicht allzu + viel / sehr = nicht übermäßig", ex: "Es war nicht **allzu** schwer.", exTr: "ما كانش صعيب برشا." },
    40: { ok: "RUHE", type: "fixed_expression", keyword: "zur Ruhe kommen", bed: "يهدى",
      text: `"wenn der Körper zur ___ kommt": تعبير ثابت: "zur Ruhe kommen" = يهدى.\n✓ "Ruhe" = هدوء (zur Ruhe kommen).\n✗ "Rolle" = دور، و"zur Rolle kommen" ما تتقالش.\n✗ "Bedeutung" = أهمّية، و"zur Bedeutung kommen" معناها توصل لأهمّية، موش يهدى.`,
      rule: "zur Ruhe kommen = sich beruhigen / entspannen", ex: "Endlich kommt er **zur** Ruhe.", exTr: "أخيرًا يهدى." },
  },

  // ───────────── [53] Menschen helfen Menschen ─────────────
  53: {
    31: { ok: "DARÜBER", type: "pronoun_adverb", keyword: "traurig sein über → darüber, wie …", bed: "على هذا",
      text: `"bin oft sehr traurig ___, wie böse … Menschen sein können": "traurig über" ← "darüber" + wie-Satz.\n✓ "darüber" = على هذا (über + das).\n✗ "dazu" = إلى هذا (zu + das)، و"traurig dazu" ما تتقالش.\n✗ "als" = كـ / من، وما تعوّضش الحرف "über".`,
      rule: "traurig / froh / wütend über + Akk. → darüber, dass / wie …", ex: "Ich bin froh **darüber**, dass du hier bist.", exTr: "أنا فرحان على إنّك هنا." },
    32: { ok: "BESONDERS", type: "adjective_adverb", keyword: "ganz besonders", bed: "خاصةً",
      text: `"freue ich mich dann ganz ___ über Ihre Artikel": "ganz besonders" = خاصةً.\n✓ "besonders" = خاصةً (ganz besonders).\n✗ "sehr" = برشا: "ganz sehr" ما تتقالش (يتقال "sehr" أو "ganz besonders").\n✗ "immer" = ديما، و"ganz immer" ما تتقالش.`,
      rule: "ganz besonders = ganz speziell (Steigerung)", ex: "Ich freue mich **ganz besonders** auf dich.", exTr: "نفرح خاصةً بيك." },
    33: { ok: "DASS", type: "conjunction", keyword: "zeigen, dass …", bed: "إنّو",
      text: `"Artikel, die zeigen, ___ es auch viele gute … Menschen gibt": محتوى المقالات.\n✓ "dass" = إنّو (+ فعل في الآخر).\n✗ "ob" = هل (سؤال)، و"zeigen, ob" تعني تبيّن هل، موش خبر.\n✗ "da" = بما إنّو (سبب)، موش محتوى.`,
      rule: "zeigen / beweisen / sagen, dass + Nebensatz", ex: "Die Studie zeigt, **dass** Sport hilft.", exTr: "الدراسة تبيّن إنّو الرياضة تفيد." },
    34: { ok: "ALS", type: "conjunction", keyword: "als (einmalig, Vergangenheit)", bed: "وقتما",
      text: `"Es war bereits 10 Uhr nachts, ___ mein Auto plötzlich stehen blieb": حدث ماضي مرة وحدة.\n✓ "als" = وقتما (حدث ماضي واحد، + فعل في الآخر).\n✗ "da" = بما إنّو / وقتها: "da" كرابط زمني قديم، والمعتاد "als".\n✗ "ob" = هل (سؤال)، موش رابط زمني.`,
      rule: "als = einmaliges Ereignis in der Vergangenheit", ex: "Es war spät, **als** er ankam.", exTr: "كان الوقت متأخّر وقتما وصل." },
    35: { ok: "DOCH", type: "conjunction", keyword: "doch (Gegensatz, Position 0)", bed: "لكن",
      text: `"Ich versuchte mehrmals, das Auto wieder zu starten, ___ alles war vergeblich": محاولات ثم فشل: تعارض.\n✓ "doch" = لكن (Position 0، الفاعل بعدو).\n✗ "denn" = خاطر: تعطي سبب، والمنطق هنا تعارض.\n✗ "dazu" = لهذا / زيادة (ظرف)، موش رابط تعارض.`,
      rule: "doch / aber = Gegensatz (Position 0)  |  denn = Grund", ex: "Er lief schnell, **doch** der Zug war weg.", exTr: "جرى بسرعة، لكن التران مشى." },
    36: { ok: "OB", type: "conjunction", keyword: "fragen, ob …", bed: "هل",
      text: `"fragte, ___ er mir helfen könne": سؤال بجواب نعم / لا.\n✓ "ob" = هل (+ فعل في الآخر).\n✗ "dass" = إنّو (خبر)، و"fragte, dass" ما تتقالش.\n✗ "da" = بما إنّو (سبب)، موش سؤال.`,
      rule: "fragen, ob … = indirekte Ja/Nein-Frage", ex: "Er fragte, **ob** ich Zeit habe.", exTr: "سأل هل عندي وقت." },
    37: { ok: "UM", type: "conjunction", keyword: "um … zu + Infinitiv", bed: "باش",
      text: `"stieg er aus, ___ sich den Motor anzusehen": غرض مع "zu + Infinitiv".\n✓ "um" = باش (um … zu).\n✗ "dazu" = لهذا (ظرف)، و"stieg aus, dazu sich … anzusehen" ما تتقالش.\n✗ "da" = بما إنّو (+ فعل مصرّف)، موش مع "zu + Infinitiv".`,
      rule: "um … zu + Infinitiv = Zweck (gleiches Subjekt)", ex: "Er geht raus, **um** frische Luft zu holen.", exTr: "يخرج باش يتنفّس هواء." },
    38: { ok: "MEINTE", type: "verb", keyword: "meinte, dass …", bed: "قال (يعتقد)",
      text: `"fand er den Schaden und ___, dass man einen Teil des Motors austauschen müsse": فعل ماضي مفرد + dass-Satz.\n✓ "meinte" = قال / اعتبر (Präteritum + dass).\n✗ "wollte" = حبّ: "wollte, dass man … austauschen müsse" معناها يطلب، موش يخبر برأيو.\n✗ "dass" = رابط، موش فعل بعد "und".`,
      rule: "meinen, dass … = die Meinung äußern", ex: "Er **meinte**, dass es teuer wird.", exTr: "قال إنّو باش يغلى." },
    39: { ok: "WOLLTE", type: "verb", keyword: "wollte nichts annehmen", bed: "ما حبّش",
      text: `"aber er ___ nichts annehmen": فعل مساعد + Infinitiv: ما حبّش ياخذ شي.\n✓ "wollte" = حبّ (Präteritum من wollen + Infinitiv "annehmen").\n✗ "meinte" = قال، و"meinte nichts annehmen" ما تتركّبش بدون "zu" أو dass.\n✗ "immer" = ديما (ظرف)، موش فعل.`,
      rule: "Modalverb + Infinitiv (ohne zu): wollte nichts annehmen", ex: "Er **wollte** kein Geld nehmen.", exTr: "ما حبّش ياخذ فلوس." },
    40: { ok: "WENIGSTENS", type: "adjective_adverb", keyword: "wenigstens (mindestens)", bed: "على الأقلّ",
      text: `"Doch möchte ich mich ___ mit diesem Brief besonders herzlich bei ihm bedanken": بما إنّو ما قبلش المكافأة: على الأقلّ بالرسالة.\n✓ "wenigstens" = على الأقلّ.\n✗ "besonders" = خاصةً، وتتكرّر مع "besonders herzlich" قدّامها.\n✗ "doch" = لكن، وما تعطيش معنى الحدّ الأدنى.`,
      rule: "wenigstens = zumindest (Minimum)", ex: "Ruf mich **wenigstens** kurz an.", exTr: "عيّطلي على الأقلّ لحظة." },
  },

  // ───────────── [54] Hase im Display ─────────────
  54: {
    31: { ok: "ZU", type: "preposition", keyword: "von Handy zu Handy", bed: "إلى",
      text: `تعبير ثابت: "von Handy zu Handy" = من تلفون لتلفون.\n✓ "zu" = إلى (von … zu).\n✗ "an" = عند / على، و"von Handy an Handy" أقلّ استعمالًا.\n✗ "aus" = من، و"von Handy aus Handy" ما تتقالش.`,
      rule: "von A zu B (von Haus zu Haus, von Tag zu Tag)", ex: "Die Nachricht ging von Mund **zu** Mund.", exTr: "الخبر مشى من فم لفم." },
    32: { ok: "AN", type: "verb_prep", keyword: "herankommen an + Akk.", bed: "يقرب من",
      text: `"kommen … nicht einmal … annähernd ___ das deutsche SMS-Fieber heran": الفعل المنفصل "herankommen an".\n✓ "an" = (herankommen an + Akkusativ).\n✗ "nach" = بعد / نحو، و"herankommen nach" ما تتقالش.\n✗ "zu" = إلى، و"herankommen zu das" ما تتقالش.`,
      rule: "trennbar: herankommen an + Akk. = sich nähern / erreichen", ex: "Niemand **kommt** an ihn **heran**.", exTr: "حتى واحد ما يلحقو." },
    33: { ok: "SCHON", type: "adjective_adverb", keyword: "schon (bereits)", bed: "توّا (ديجا)",
      text: `"ein paar Minuten später ist ___ die Antwort da": السرعة: ديجا.\n✓ "schon" = ديجا / توّا (تعبّر على السرعة).\n✗ "sehr" = برشا (درجة)، موش ظرف زمني.\n✗ "da" = هنا، وتتكرّر مع "da" في آخر الجملة.`,
      rule: "schon = bereits (früher als erwartet)", ex: "Der Bus ist **schon** da.", exTr: "البيّاص توّا جا." },
    34: { ok: "AUS", type: "fixed_expression", keyword: "aus der Mode kommen", bed: "تخرج من الموضة",
      text: `"Selbst Liebesbriefe sind ___ der Mode gekommen": تعبير ثابت: "aus der Mode kommen".\n✓ "aus" = من (aus der Mode kommen).\n✗ "zu" = إلى، و"zu der Mode gekommen" ما تتقالش.\n✗ "nach" = بعد، و"nach der Mode" ما تعطيش معنى "خرجو منها".`,
      rule: "aus der Mode kommen = unmodern werden  |  in Mode kommen", ex: "Diese Hüte sind **aus** der Mode gekommen.", exTr: "هذي القبّعات خرجت من الموضة." },
    35: { ok: "UMSO", type: "adjective_adverb", keyword: "umso + Komparativ", bed: "أكثر",
      text: `"dafür aber ___ cooler, dynamischer": "umso + Komparativ" = أكثر بالمقابل.\n✓ "umso" = أكثر (umso + Komparativ).\n✗ "höher" = أعلى (Komparativ)، و"aber höher cooler" ما تتقالش.\n✗ "sehr" = برشا (مع الصفة العادية)، و"sehr cooler" ما تتقالش (Komparativ).`,
      rule: "umso + Komparativ = um so viel mehr", ex: "Es wird **umso** besser.", exTr: "يولّي أحسن بكثير." },
    36: { ok: "DABEI", type: "pronoun_adverb", keyword: "dabei (in diesem Zusammenhang)", bed: "وفي هذا",
      text: `"Und ___ muss der verliebte SMS-Casanova … Kreativität zeigen": ربط: في هذا السياق، والفعل "muss" بعدو.\n✓ "dabei" = وفي هذا (ظرف، الفعل في الثانية).\n✗ "also" = إذن (نتيجة): "Und also muss" قديمة وثقيلة.\n✗ "da" = هنا / بما إنّو، موش ظرف ربط هكا.`,
      rule: "dabei = bei dieser Sache / dabei muss man …", ex: "**Dabei** muss er vorsichtig sein.", exTr: "وفي هذا لازمو يكون حذر." },
    37: { ok: "DENN", type: "conjunction", keyword: "denn + Hauptsatz", bed: "خاطر",
      text: `"; ___ die Nachrichten dürfen nicht sehr lang sein": سبب، والفعل "dürfen" في الثانية.\n✓ "denn" = خاطر (+ جملة رئيسية).\n✗ "da" = بما إنّو (+ فعل في الآخر)، وهنا "dürfen" في الثانية.\n✗ "also" = إذن (نتيجة)، والمنطق سبب.`,
      rule: "denn + Hauptsatz  |  da / weil + Nebensatz", ex: "Er bleibt, **denn** es regnet.", exTr: "يقعد، خاطر تشتي." },
    38: { ok: "DARAUS", type: "pronoun_adverb", keyword: "daraus machen", bed: "منها",
      text: `"Der SMS-Künstler macht ___ „ILD“": "aus etwas etwas machen" ← "daraus" (aus "Ich liebe dich").\n✓ "daraus" = منها (aus + das).\n✗ "dabei" = في هذا، و"macht dabei ILD" ما تعطيش معنى التحويل.\n✗ "aus" = من (حرف جر)، ويحتاج اسم بعدو.`,
      rule: "aus A macht man B → daraus macht man B", ex: "Aus Mehl macht man Brot — **daraus** wird Kuchen.", exTr: "من الفرينة يتعمل خبز — ومنها يتعمل كيك." },
    39: { ok: "ALSO", type: "adjective_adverb", keyword: "also (Folgerung)", bed: "إذن",
      text: `"Schlechte Zeiten ___ für wahre Liebhaber literarischer Schreibkunst": خلاصة: إذن.\n✓ "also" = إذن / وبالتالي (ظرف خلاصة).\n✗ "denn" = خاطر (رابط سبب)، وما يجي بعد "Zeiten" هكا.\n✗ "da" = هنا / بما إنّو، موش ظرف خلاصة.`,
      rule: "also = folglich (Zusammenfassung)", ex: "Es regnet, **also** bleiben wir hier.", exTr: "تشتي، إذن نقعدو هنا." },
    40: { ok: "DRASTISCH", type: "adjective_adverb", keyword: "drastisch ansteigen", bed: "بشكل حادّ",
      text: `"sollen die Preise … ___ ansteigen": ظرف شدّة: بشكل حادّ.\n✓ "drastisch" = بشكل حادّ.\n✗ "statisch" = ثابت: "statisch ansteigen" تناقض (ثابت وترتفع).\n✗ "höher" = أعلى (Komparativ)، و"höher ansteigen" فيها تكرار ("an-steigen" فيها ارتفاع).`,
      rule: "drastisch + Verb = sehr stark / plötzlich (drastisch steigen / sinken)", ex: "Die Kosten stiegen **drastisch**.", exTr: "التكاليف ارتفعت بشكل حادّ." },
  },

  // ───────────── [55] Kaffee und Kuchen – ein Stück Tradition ─────────────
  55: {
    31: { ok: "ZU", type: "preposition", keyword: "sich treffen zu Kaffee und Kuchen", bed: "على",
      text: `"trifft man sich am Sonntagnachmittag ___ Kaffee und Kuchen": "sich treffen zu" = يتلاقاو على (مناسبة).\n✓ "zu" = على / لـ (sich treffen zu + Dativ).\n✗ "von" = من، و"sich treffen von Kaffee" ما تتقالش.\n✗ "aus" = من، و"treffen aus Kaffee" ما تتقالش.`,
      rule: "sich zu etwas treffen (zu Kaffee, zum Essen, zu einer Sitzung)", ex: "Wir treffen uns **zu** einer Besprechung.", exTr: "نتلاقاو لاجتماع." },
    32: { ok: "WIE", type: "conjunction", keyword: "wie lange (indirekte Frage)", bed: "قدّاش (من مدّة)",
      text: `"___ lange es den Brauch … gibt, ist jedoch nicht bekannt": سؤال غير مباشر على المدّة: "wie lange".\n✓ "wie" = قدّاش (wie lange).\n✗ "ob" = هل (سؤال بنعم / لا)، و"Ob lange" ما تتقالش.\n✗ "desto" = كلّما (je … desto)، موش كلمة سؤال.`,
      rule: "wie lange / wie oft / wie viel = indirekte Frage (Verb am Ende)", ex: "Ich weiß nicht, **wie** lange es dauert.", exTr: "ما نعرفش قدّاش باش يدوم." },
    33: { ok: "SICHER", type: "adjective_adverb", keyword: "sicher ist nur, dass …", bed: "المؤكّد",
      text: `"___ ist nur, dass sich dieses Getränk … verbreitete": تعبير: "Sicher ist nur, dass …" = المؤكّد بس إنّو.\n✓ "sicher" = مؤكّد (Sicher ist nur, dass …).\n✗ "genau" = بالضبط: "Genau ist nur, dass" ما تتقالش بهذا المعنى.\n✗ "damals" = وقتها (ظرف)، موش صفة بعد "ist".`,
      rule: "Sicher ist (nur), dass … = Fest steht, dass …", ex: "**Sicher** ist nur, dass er kommt.", exTr: "المؤكّد بس إنّو يجي." },
    34: { ok: "DAMALS", type: "adjective_adverb", keyword: "damals (zu jener Zeit)", bed: "وقتها",
      text: `"___ entstanden zahlreiche Kaffeehäuser": ظرف زمني ماضي: وقتها.\n✓ "damals" = وقتها (في الماضي، الفعل في الثانية).\n✗ "immer" = ديما، موش زمن محدّد.\n✗ "bis" = حتى (حرف جر / رابط)، موش ظرف زمني.`,
      rule: "damals = zu jener Zeit (Vergangenheit)", ex: "**Damals** gab es noch keine Handys.", exTr: "وقتها ما كانش فما تلفونات." },
    35: { ok: "SONDERN", type: "conjunction", keyword: "nicht nur …, sondern …", bed: "بل",
      text: `"nicht nur gespeist und getrunken, ___ man konnte in Gesellschaft sein": الزوج "nicht nur … sondern (auch)".\n✓ "sondern" = بل.\n✗ "wie" = كيما، موش رابط بعد "nicht nur".\n✗ "ob" = هل، موش رابط.`,
      rule: "nicht nur A, sondern (auch) B", ex: "Er isst nicht nur, **sondern** trinkt auch.", exTr: "هو موش بس ياكل، بل يشرب زادا." },
    36: { ok: "VON", type: "preposition", keyword: "ein Werk von + Komponist", bed: "متاع",
      text: `"die berühmte Kaffeekantate ___ Johann Sebastian Bach": المؤلّف: "von + Name".\n✓ "von" = متاع / من (Werk von Bach).\n✗ "aus" = من (مصدر / مادّة)، و"Kantate aus Bach" معناها مصنوعة منو.\n✗ "zu" = إلى، و"Kantate zu Bach" ما تتقالش.`,
      rule: "ein Werk von + Autor / Komponist", ex: "Das Lied ist **von** Mozart.", exTr: "الأغنية متاع موزارت." },
    37: { ok: "KONNTEN", type: "verb", keyword: "konnten (Präteritum, Plural)", bed: "ينجّمو",
      text: `"ein Luxusgut, das sich nur Adelige und wohlhabende Bürger leisten ___": الفاعل جمع، وماضي، وإمكانية.\n✓ "konnten" = ينجّمو (Präteritum جمع من können).\n✗ "mussten" = لازمهم، وما يتماشاش مع "leisten" (القدرة الماليّة).\n✗ "sicher" = مؤكّد (ظرف)، موش فعل مساعد.`,
      rule: "sich etwas leisten können = es sich finanziell erlauben", ex: "Nur Reiche **konnten** sich das leisten.", exTr: "غير الأغنياء ينجّمو يتحمّلو هذا." },
    38: { ok: "BIS", type: "preposition", keyword: "bis heute", bed: "لين",
      text: `"und ist es ___ heute geblieben": "bis heute" = لين اليوم.\n✓ "bis" = لين (bis heute).\n✗ "immer" = ديما: "immer heute" ما تتقالش.\n✗ "von" = من، و"von heute geblieben" ما تعطيش معنى "لين".`,
      rule: "bis heute = bis zum heutigen Tag", ex: "Das gilt **bis** heute.", exTr: "هذا ساري لين اليوم." },
    39: { ok: "AUS", type: "preposition", keyword: "aus aller Welt", bed: "من (العالم كلّو)",
      text: `"Spezialitäten ___ alle Welt": تعبير ثابت: "aus aller Welt" = من العالم كلّو.\n✓ "aus" = من (aus aller Welt، Herkunft).\n✗ "von" = من: "von aller Welt" ما تتقالش في هذا التعبير.\n✗ "zu" = إلى، موش مصدر.`,
      rule: "aus aller Welt = von überall her (feste Wendung)", ex: "Gäste **aus** aller Welt kamen.", exTr: "جاو ضيوف من العالم كلّو." },
    40: { ok: "IMMER", type: "adjective_adverb", keyword: "immer häufiger", bed: "أكثر فأكثر",
      text: `"setzten seitdem Espressokocher … ___ häufiger Konkurrenz": "immer + Komparativ" = تزايد.\n✓ "immer" = ديما (immer häufiger = أكثر فأكثر).\n✗ "mehr" = أكثر، و"mehr häufiger" فيها تكرار (Komparativ مرّتين).\n✗ "desto" = كلّما (je … desto)، وما فماش "je" قبلها.`,
      rule: "immer + Komparativ = stetige Zunahme  |  je … desto", ex: "Es wird **immer** wärmer.", exTr: "يولّي أسخن أكثر فأكثر." },
  },

  // ───────────── [56] Obst und Gemüse ─────────────
  56: {
    31: { ok: "DOCH", type: "conjunction", keyword: "doch (Kontrast)", bed: "لكن",
      text: `"draußen herrscht noch Dunkelheit… ___ in der riesigen, hell erleuchteten Halle … wird schon lange gearbeitet": تناقض: برّا ظلام، لكن في القاعة خدمة.\n✓ "doch" = لكن (تعارض).\n✗ "sondern" = بل (تصحيح بعد نفي)، وما فماش نفي.\n✗ "nämlich" = لأنّو (تفسير)، موش تعارض.`,
      rule: "doch = aber (Gegensatz zum Vorigen)", ex: "Es regnete, **doch** wir gingen raus.", exTr: "كانت تشتي، لكن خرجنا." },
    32: { ok: "LEITET", type: "verb", keyword: "einen Betrieb leiten", bed: "يدير",
      text: `"Er ___ einen Berliner Großmarkt": "einen Markt leiten" = يدير سوق، والفاعل "er" مفرد.\n✓ "leitet" = يدير (3. Person مفرد).\n✗ "erwerben" = Infinitiv / جمع (يشري)، موش مفرد.\n✗ "bewundern" = Infinitiv (يعجب)، وما يتماشاش مع "Großmarkt" هكا.`,
      rule: "etwas leiten = führen / managen (er leitet)", ex: "Sie **leitet** ein großes Team.", exTr: "هي تدير فريق كبير." },
    33: { ok: "ANKOMMT", type: "verb", keyword: "ankommen (kommt … an)", bed: "توصل",
      text: `"bis sie auf dem Großmarkt ___": فعل منفصل في الجملة الفرعية يتجمّع في الآخر: "ankommt".\n✓ "ankommt" = توصل (3. Person مفرد، Nebensatz).\n✗ "abgeschlossen" = Partizip II (خلّص)، موش فعل مصرّف.\n✗ "erwerben" = Infinitiv (يشري)، موش مصرّف.`,
      rule: "Nebensatz: trennbares Verb wird zusammengeschrieben am Ende (ankommt)", ex: "Warte, bis der Zug **ankommt**.", exTr: "استنّى لين يوصل التران." },
    34: { ok: "NÄMLICH", type: "adjective_adverb", keyword: "nämlich (Erklärung)", bed: "يعني (خاطر)",
      text: `"Die meisten Früchte wurden ___ auf dem Land-, Luft- oder Seeweg … transportiert": تفسير للجملة اللي قبل (الرحلة الطويلة).\n✓ "nämlich" = يعني / خاطر (تفسير داخل الجملة).\n✗ "sicher" = أكيد: ممكنة نحويًّا، بصح الجملة تفسّر موش تأكّد.\n✗ "genau" = بالضبط، وما تعطيش معنى التفسير.`,
      rule: "nämlich im Mittelfeld = erklärt den vorherigen Satz", ex: "Er fehlt, er ist **nämlich** krank.", exTr: "غايب، هو خاطر مريض." },
    35: { ok: "DARF", type: "verb", keyword: "darf … keinesfalls", bed: "ما ينجمش",
      text: `"Auf seinem Weg ___ das empfindliche Obst keinesfalls Schaden nehmen": منع: "darf … nicht".\n✓ "darf" = ينجّم / مسموح (مع "keinesfalls" = ممنوع تمامًا؛ الفاعل مفرد).\n✗ "konnten" = ماضي جمع، والفاعل "Obst" مفرد، والجملة حاضر.\n✗ "leitet" = يدير، و"leitet … Schaden nehmen" ما تتركّبش.`,
      rule: "darf + keinesfalls / nicht = Verbot", ex: "Das Paket **darf** keinesfalls nass werden.", exTr: "الطرد ممنوع يتبلّ تمامًا." },
    36: { ok: "ALS", type: "conjunction", keyword: "schlimmer als", bed: "من",
      text: `"Nichts ist schlimmer ___ verdorbene Ware": مقارنة بعد Komparativ.\n✓ "als" = من (Komparativ + als).\n✗ "bis" = لين، موش أداة مقارنة.\n✗ "sondern" = بل (تصحيح بعد نفي)، موش مقارنة.`,
      rule: "Komparativ + als = Vergleich der Ungleichheit", ex: "Nichts ist schöner **als** Ruhe.", exTr: "ما فما أحلى من الراحة." },
    37: { ok: "GENAU", type: "adjective_adverb", keyword: "genau ansehen", bed: "بدقّة",
      text: `"schauen sich die Käufer alles ___ an": ظرف طريقة: بدقّة.\n✓ "genau" = بدقّة (sich etwas genau ansehen).\n✗ "sicher" = أكيد، و"alles sicher ansehen" ما تعطيش معنى الدقّة.\n✗ "nämlich" = يعني / خاطر (ظرف تفسير)، موش طريقة.`,
      rule: "sich etwas genau ansehen = gründlich prüfen", ex: "Er schaut sich den Vertrag **genau** an.", exTr: "هو يتفحّص العقد بدقّة." },
    38: { ok: "ERWERBEN", type: "verb", keyword: "erwerben = kaufen", bed: "يشريو",
      text: `"krumme Gurken oder verwachsene Kartoffeln ___ sie dagegen günstiger": المشترين يشريو أرخص.\n✓ "erwerben" = يشريو (Präsens جمع، مع "sie").\n✗ "bewundern" = يعجبو، و"bewundern günstiger" ما تتقالش.\n✗ "konnten" = ماضي (نجّمو)، والجملة حاضر.`,
      rule: "erwerben = kaufen / bekommen (förmlich)", ex: "Sie **erwerben** die Ware günstig.", exTr: "هم يشريو البضاعة بسعر مناسب." },
    39: { ok: "SONDERN", type: "conjunction", keyword: "nicht …, sondern …", bed: "بل",
      text: `"nicht in Geschäften zum Verkauf angeboten, ___ direkt verarbeitet": تصحيح بعد "nicht".\n✓ "sondern" = بل.\n✗ "doch" = لكن: ممكنة نحويًّا، بصح بعد "nicht" المعتاد "sondern".\n✗ "als" = كـ / من، موش رابط تصحيح.`,
      rule: "nicht A, sondern B", ex: "Nicht frisch, **sondern** getrocknet.", exTr: "موش طازج، بل مجفّف." },
    40: { ok: "ABGESCHLOSSEN", type: "tense", keyword: "abgeschlossen sein (Zustandspassiv)", bed: "منتهية",
      text: `"Wenn die Preisverhandlungen erfolgreich ___ sind": Zustandspassiv: Partizip II + sind.\n✓ "abgeschlossen" = منتهية (Partizip II من abschließen).\n✗ "ankommt" = فعل مصرّف (يوصل)، موش Partizip II.\n✗ "erwerben" = Infinitiv، وبعد "erfolgreich … sind" نحتاج Partizip II.`,
      rule: "Zustandspassiv: sein + Partizip II (abgeschlossen sein = fertig sein)", ex: "Die Arbeit ist **abgeschlossen**.", exTr: "الخدمة منتهية." },
  },
};
