// SB Teil 2 restyle — batch 03: [12] + [13] Bodyscanning, [14] + [15] Fahrrad, [16] Haustiere
export default {
  // ───────────── [12] Maßgeschneidert nach Bodyscanning ( Original ) ─────────────
  12: {
    31: { ok: "DARÜBER", type: "pronoun_adverb", keyword: "sich ärgern über → darüber, dass", bed: "على هذا",
      text: `"sich ärgern" يتبعو "über"، والـ Pronominaladverb "darüber" (= über + das) يعلن على الـ dass-Satz.\n✓ "darüber" = على هذا (über + das).\n✗ "darum" = لهذا (um + das)، و"sich ärgern darum" ما تتقالش.\n✗ "dass" = إنّو (رابط)، وما تعوّضش الحرف "über" اللي يطلبو الفعل.`,
      rule: "sich ärgern über + Akk. → darüber, dass …", ex: "Ich ärgere mich **darüber**, dass er nie anruft.", exTr: "نغضب على هذا، إنّو ما يعيّطش أبدًا." },
    32: { ok: "NUR", type: "adjective_adverb", keyword: "fast nur noch", bed: "غير (تقريبًا)",
      text: `"gibt es fast ___ noch in den falschen Größen": "fast nur noch" = تقريبًا غير.\n✓ "nur" = غير / برك (fast nur noch).\n✗ "weder" = لا (weder … noch)، تحتاج جزئين، والـ "noch" هنا جزء من "nur noch".\n✗ "sowie" = وكذلك (رابط عطف)، موش ظرف حصر.`,
      rule: "nur noch = ausschließlich (fast nur noch = beinahe ausschließlich)", ex: "Es gibt hier **nur** noch alte Autos.", exTr: "هنا ما بقاو غير كراهب قدام." },
    33: { ok: "ANS", type: "fixed_expression", keyword: "ans Licht bringen", bed: "يكشف (للنور)",
      text: `تعبير ثابت: "etwas ans Licht bringen" = يكشف شي.\n✓ "ans" = an + das (ans Licht bringen).\n✗ "ins" = in + das: "ins Licht" تتقال مع "ins Licht rücken"، موش "bringen" بمعنى يكشف.\n✗ "als" = كـ / وقتما، و"als Licht bringen" ما تتقالش.`,
      rule: "ans Licht bringen = aufdecken  |  ins Licht rücken = hervorheben", ex: "Die Polizei brachte die Wahrheit **ans** Licht.", exTr: "البوليس كشف الحقيقة." },
    34: { ok: "WEDER", type: "conjunction", keyword: "weder … noch …", bed: "لا… ولا…",
      text: `"passen ___ den Kundinnen noch den Kunden": "noch" تدلّ على الزوج "weder … noch".\n✓ "weder" = لا (weder … noch، نفي مزدوج).\n✗ "nur" = غير / برك، وتحتاج "nicht nur … sondern auch"، موش "noch".\n✗ "sowie" = وكذلك (عطف إيجابي)، وما يعطيش نفي.`,
      rule: "weder A noch B = nicht A und nicht B", ex: "Er trinkt **weder** Kaffee noch Tee.", exTr: "هو ما يشربش لا قهوة ولا تاي." },
    35: { ok: "MÜSSEN", type: "verb", keyword: "suchen müssen (Modalverb am Ende)", bed: "لازمهم",
      text: `"dass die Modeproduzenten den Grund … suchen ___": الجملة "dass" فعلها المساعد في الآخر، والفاعل جمع.\n✓ "müssen" = لازمهم (جمع، Infinitiv + Modalverb في الآخر).\n✗ "sollen" = المفروض: ممكنة نحويًّا، بصح الاستنتاج هنا ضرورة منطقية موش أمر من واحد آخر.\n✗ "dürfen" = مسموحلهم (إذن)، وما فماش معنى "مسموح يلوّجو".`,
      rule: "müssen = Notwendigkeit  |  sollen = Auftrag / Erwartung  |  dürfen = Erlaubnis", ex: "Die Firmen **müssen** neue Wege suchen.", exTr: "الشركات لازمها تلوّج على طرق جديدة." },
    36: { ok: "DA", type: "conjunction", keyword: "da + Nebensatz (Grund)", bed: "بما إنّو",
      text: `"___ der Handel natürlich daran interessiert ist, …": سبب معروف للمشروع، والفعل "ist" في الآخر.\n✓ "da" = بما إنّو (+ فعل في الآخر).\n✗ "als" = وقتما (حدث ماضي مرة وحدة)، والجملة حاضر.\n✗ "dass" = إنّو (محتوى)، والجملة هنا تعطي سبب المشروع.`,
      rule: "da + Nebensatz = bekannter Grund  |  als = einmalig in der Vergangenheit  |  dass = Inhalt", ex: "**Da** es spät ist, gehen wir nach Hause.", exTr: "بما إنّو الوقت تأخّر، نمشيو للدار." },
    37: { ok: "DAS", type: "pronoun", keyword: "Relativpronomen: das (Projekt)", bed: "اللي (المشروع)",
      text: `"ein neues Projekt geplant, ___ Aufschluss darüber geben soll": الجملة الفرعية فاعلها هو المشروع (محايد).\n✓ "das" = Relativpronomen Nominativ محايد (das Projekt, das …).\n✗ "dass" = رابط (إنّو) يحتاج فاعل جديد، وهنا "Aufschluss … soll" ما عندهاش فاعل يخصّو.\n✗ "darum" = لهذا (um + das)، موش ضمير موصول.`,
      rule: "Relativpronomen neutrum Nominativ: das  ≠  Konjunktion dass", ex: "Das Haus, **das** dort steht, ist alt.", exTr: "الدار اللي واقفة هناك قديمة." },
    38: { ok: "SOLLEN", type: "verb", keyword: "sollen = Zweck / Plan", bed: "المفروض (الغرض)",
      text: `"Diese … Bilder ___ es ermöglichen": غرض التقنية، والفاعل جمع.\n✓ "sollen" = المفروض / الغرض منها (جمع).\n✗ "müssen" = لازم: ممكنة، بصح الجملة تحكي على غرض التقنية موش ضرورة.\n✗ "dürfen" = مسموحلهم، وما تتماشاش مع غرض تقني.`,
      rule: "sollen = geplanter Zweck / Auftrag  |  müssen = Zwang", ex: "Die Daten **sollen** uns helfen.", exTr: "المعطيات الغرض منها تعاوننا." },
    39: { ok: "DÜRFEN", type: "verb", keyword: "sich freuen dürfen", bed: "ننجّمو (نفرحو)",
      text: `"Als Kundinnen und Kunden ___ wir uns … darauf freuen": صيغة مؤدّبة = عندنا الحقّ نفرحو.\n✓ "dürfen" = ننجّمو / عندنا الحقّ (جمع wir).\n✗ "müssen" = لازمنا، وما يتقالش إنّو لازم نفرحو.\n✗ "sollen" = المفروض، وما تتماشاش مع فرحة (شعور).`,
      rule: "sich freuen dürfen = höflich: man hat Grund zur Freude", ex: "Wir **dürfen** uns auf den Urlaub freuen.", exTr: "ننجّمو نفرحو بالعطلة." },
    40: { ok: "DASS", type: "conjunction", keyword: "sich freuen, dass …", bed: "إنّو",
      text: `"freuen, ___ sich … die Modefirmen … entscheiden": محتوى الفرحة، والفعل في الآخر.\n✓ "dass" = إنّو (محتوى، + فعل في الآخر).\n✗ "das" = أداة / ضمير إشارة، موش رابط.\n✗ "als" = وقتما / من، وما تفتحش محتوى بعد "freuen".`,
      rule: "sich freuen, dass + Nebensatz", ex: "Ich freue mich, **dass** du kommst.", exTr: "نفرح إنّك جاي." },
  },

  // ───────────── [13] Maßgeschneidert nach Bodyscanning (معدل) ─────────────
  13: {
    31: { ok: "DARÜBER", type: "pronoun_adverb", keyword: "sich aufregen über → darüber", bed: "على هذا",
      text: `"sich aufregen" يتبعو "über"، و"darüber" يعلن على جملة "dass".\n✓ "darüber" = على هذا (über + das).\n✗ "darum" = لهذا (um + das)، و"sich aufregen darum" ما تتقالش.\n✗ "Das" = أداة / ضمير إشارة، وما تعوّضش الحرف "über".`,
      rule: "sich aufregen über + Akk. → darüber, dass …", ex: "Sie regt sich **darüber** auf, dass es teuer ist.", exTr: "هي تتنرفز على إنّو غالي." },
    32: { ok: "NUR", type: "adjective_adverb", keyword: "fast nur noch", bed: "غير (تقريبًا)",
      text: `"gibt es fast ___ noch": تعبير "fast nur noch" = تقريبًا فقط.\n✓ "nur" = فقط / برك.\n✗ "weder" = لا، وتحتاج "noch" ثاني ("weder … noch")، وهنا "noch" جزء من "nur noch".\n✗ "sondern" = بل (تصحيح بعد نفي)، موش ظرف حصر.`,
      rule: "fast nur noch = beinahe ausschließlich", ex: "Hier gibt es **nur** noch Restaurants.", exTr: "هنا ما بقاو غير المطاعم." },
    33: { ok: "KAM", type: "verb", keyword: "zu einer Erkenntnis kommen", bed: "وصلت (لنتيجة)",
      text: `"Eine Untersuchung … ___ nun zu der folgenden Erkenntnis": "zu einer Erkenntnis kommen" = توصّل لنتيجة، والفاعل مفرد.\n✓ "kam" = Präteritum من "kommen" (3. Person مفرد).\n✗ "habe" = فعل مساعد (Perfekt) ويحتاج Partizip II ("gekommen")، وهنا ما فماش.\n✗ "sollen" = جمع / Infinitiv، والفاعل "Eine Untersuchung" مفرد.`,
      rule: "zu + Dativ kommen: zu einem Ergebnis / zu einer Erkenntnis kommen", ex: "Die Studie **kam** zu einem klaren Ergebnis.", exTr: "الدراسة وصلت لنتيجة واضحة." },
    34: { ok: "WEDER", type: "conjunction", keyword: "weder … noch …", bed: "لا… ولا…",
      text: `"passen ___ den Kundinnen noch den Kunden": الزوج "weder … noch".\n✓ "weder" = لا (نفي مزدوج مع "noch").\n✗ "nur" = فقط، وتحتاج "nicht nur … sondern auch"، موش "noch".\n✗ "sowie" = وكذلك (عطف إيجابي)، وما يعطيش نفي.`,
      rule: "weder … noch = beides nicht", ex: "Sie hat **weder** Zeit noch Lust.", exTr: "ما عندها لا وقت ولا نفس." },
    35: { ok: "HABE", type: "tense", keyword: "habe zugenommen (Konjunktiv I)", bed: "(قالو) زادت",
      text: `"Die Länge der Arme ___ zugenommen": كلام منقول عن الدراسة (Konjunktiv I)، والفاعل مفرد.\n✓ "habe" = Konjunktiv I من "haben" (habe … zugenommen).\n✗ "kam" = Präteritum من "kommen"، و"kam zugenommen" ما تتقالش.\n✗ "sollen" = جمع / Infinitiv، وما يطابقش "Länge" المفرد.`,
      rule: "indirekte Rede, Perfekt: er habe / sei + Partizip II", ex: "Er sagt, die Zahl **habe** zugenommen.", exTr: "يقول إنّ العدد زاد." },
    36: { ok: "DA", type: "conjunction", keyword: "da + Nebensatz (Grund)", bed: "بما إنّو",
      text: `"___ man natürlich daran interessiert ist, …": سبب معروف، والفعل "ist" في الآخر.\n✓ "da" = بما إنّو (+ فعل في الآخر).\n✗ "dass" = إنّو (محتوى)، موش سبب.\n✗ "als" = وقتما (ماضي مرة وحدة)، والجملة حاضر.`,
      rule: "da = weil (bekannter Grund), Verb am Ende", ex: "**Da** ich müde bin, bleibe ich zu Hause.", exTr: "بما إنّي تعبان، نقعد في الدار." },
    37: { ok: "Das", type: "pronoun", keyword: "Relativpronomen: das (Verfahren)", bed: "اللي (الطريقة)",
      text: `"ein neues Verfahren entwickelt, ___ Männer und Frauen neu vermessen soll": "soll" مفرد ← الفاعل هو "Verfahren" (محايد).\n✓ "das" = Relativpronomen Nominativ محايد.\n✗ "dass" = رابط، وبعدو "Männer und Frauen" جمع والفعل "soll" مفرد، فما يتطابقوش.\n✗ "darum" = لهذا (um + das)، موش ضمير موصول.`,
      rule: "das (Relativpronomen, Neutrum) + Verb im Singular", ex: "Das Gerät, **das** hier liegt, gehört mir.", exTr: "الجهاز اللي هنا ملكي." },
    38: { ok: "SOLLEN", type: "verb", keyword: "sollen = Zweck", bed: "المفروض (الغرض)",
      text: `"Diese … Bilder ___ es ermöglichen": غرض الصور، والفاعل جمع.\n✓ "sollen" = الغرض منها / المفروض (جمع).\n✗ "kam" = ماضي مفرد، موش جمع ولا غرض.\n✗ "habe" = فعل مساعد مفرد (Konjunktiv I)، وما يتماشاش مع "es ermöglichen" في الآخر.`,
      rule: "sollen + Infinitiv = geplanter Zweck", ex: "Die Bilder **sollen** das Ergebnis zeigen.", exTr: "الصور الغرض منها تورّي النتيجة." },
    39: { ok: "DASS", type: "conjunction", keyword: "sich freuen, dass …", bed: "إنّو",
      text: `"freuen, ___ sich … die Modefirmen … entscheiden": محتوى الفرحة.\n✓ "dass" = إنّو (+ فعل في الآخر).\n✗ "als" = وقتما / من، وما تفتحش محتوى هكا.\n✗ "Das" = أداة / ضمير إشارة، موش رابط.`,
      rule: "freuen + dass-Satz (Inhalt der Freude)", ex: "Ich freue mich darauf, **dass** der Sommer kommt.", exTr: "نستنّى بفارغ الصبر إنّو الصيف يجي." },
    40: { ok: "GLEICH", type: "adjective_adverb", keyword: "gleich groß", bed: "نفس (الحجم)",
      text: `"überall ___ groß": الصفة "gleich" = نفس، مع "groß" للمقارنة.\n✓ "gleich" = نفس (gleich groß = بنفس الحجم).\n✗ "nur" = فقط، و"überall nur groß" ما تعبّرش على تساوي.\n✗ "weder" = لا (weder … noch)، وما تتركّبش مع "groß" هكا.`,
      rule: "gleich + Adjektiv = in gleichem Maß (gleich groß, gleich alt)", ex: "Die beiden Brüder sind **gleich** alt.", exTr: "الخوين نفس العمر." },
  },

  // ───────────── [14] Das Fahrrad: ernsthafte Konkurrenz fürs Auto? ─────────────
  14: {
    31: { ok: "KAUM", type: "adjective_adverb", keyword: "in kaum einem anderen Land", bed: "تقريبًا ما (في بلاد أخرى)",
      text: `"In ___ einem anderen Land gibt es so viele Automobilfabriken wie in Deutschland": تقريبًا ما فما بلاد أخرى.\n✓ "kaum" = بالكاد / تقريبًا ما (kaum einem = تقريبًا حتى واحد).\n✗ "fast" = تقريبًا، و"in fast einem anderen Land" تعطي معنى معكوس (تقريبًا في بلاد وحدة)، المعنى المطلوب "fast keinem".\n✗ "beinahe" = تقريبًا (مثل fast)، نفس المشكل.`,
      rule: "kaum + ein- = fast kein-  |  fast + ein- = beinahe ein-", ex: "In **kaum** einem Haus gibt es keinen Fernseher.", exTr: "تقريبًا ما فما دار ما فيهاش تلفزة." },
    32: { ok: "AUF", type: "verb_prep", keyword: "umsteigen auf + Akk.", bed: "يبدّل لـ",
      text: `"umzusteigen" يتبعو "auf" + Akkusativ: "auf ein anderes Verkehrsmittel umsteigen".\n✓ "auf" = على (umsteigen auf).\n✗ "an" = عند / على، و"an ein anderes Verkehrsmittel umsteigen" ما تتقالش.\n✗ "vor" = قدّام / قبل، وما تتركّبش مع "umsteigen".`,
      rule: "umsteigen auf + Akk. (auf das Rad, auf die Bahn)", ex: "Viele **steigen** auf das Fahrrad **um**.", exTr: "برشا يبدّلو للدرّاجة." },
    33: { ok: "VORBEI", type: "verb", keyword: "an … vorbeifahren", bed: "(يعدّي) بجنب",
      text: `"an den im Stau wartenden Fahrzeugen ___ und ausgeruht … anzukommen": الفعل المنفصل "vorbeifahren": "an etwas vorbeifahren".\n✓ "vorbei" = الجزء المنفصل (an … vorbei-zufahren).\n✗ "an" = حرف جر موجود قبل "den … Fahrzeugen"، وما يكمّلش الفعل المنفصل.\n✗ "statt" = عوض (حرف جر + Genitiv / زائد "zu")، وما يكمّلش فعل حركة.`,
      rule: "an + Dativ + vorbeifahren / vorbeigehen (trennbar)", ex: "Er fährt jeden Tag **vorbei**.", exTr: "هو يعدّي كلّ يوم بجنب." },
    34: { ok: "STATT", type: "preposition", keyword: "statt … zu + Infinitiv", bed: "عوض",
      text: `"Wer Fahrrad fährt ___ zu sitzen": بديل: يسوق درّاجة عوض ما يقعد.\n✓ "statt" = عوض (statt … zu + Infinitiv).\n✗ "vor" = قبل، و"vor zu sitzen" ما تتقالش.\n✗ "an" = على، وما تجيش قبل "zu + Infinitiv" هكا.`,
      rule: "statt … zu + Infinitiv = anstelle von", ex: "Er geht zu Fuß, **statt** zu fahren.", exTr: "يمشي على رجليه عوض ما يسوق." },
    35: { ok: "INNERHALB", type: "preposition", keyword: "innerhalb + Genitiv", bed: "داخل",
      text: `"die sich sonst die meiste Zeit ___ geschlossener Räume … aufhalten": "geschlossener Räume" Genitiv جمع.\n✓ "innerhalb" = داخل (+ Genitiv).\n✗ "vor" = قدّام / قبل، و"vor geschlossener Räume" ما تتقالش.\n✗ "auf" = على، ما تتركّب مع Genitiv ("auf geschlossener Räume") ولا مع المعنى.`,
      rule: "innerhalb + Genitiv (innerhalb des Gebäudes / geschlossener Räume)", ex: "Das Rauchen ist **innerhalb** des Gebäudes verboten.", exTr: "التدخين ممنوع داخل المبنى." },
    36: { ok: "MÜSSEN", type: "verb", keyword: "aufhalten müssen", bed: "لازمهم (يقعدو)",
      text: `"Menschen, die sich … in Büros … aufhalten ___": الفعل المساعد في الآخر، والفاعل جمع (الناس).\n✓ "müssen" = لازمهم (ضرورة من الخدمة).\n✗ "dürfen" = مسموحلهم (إذن)، وما فماش معنى امتياز.\n✗ "sollen" = المفروض: ممكنة، بصح الإلزام هنا من ظروف الخدمة موش أمر خارجي.`,
      rule: "müssen = Notwendigkeit durch die Umstände", ex: "Viele **müssen** den ganzen Tag drinnen bleiben.", exTr: "برشا لازمهم يبقاو طول النهار لداخل." },
    37: { ok: "AN", type: "preposition", keyword: "Angebot an + Dativ", bed: "عرض من",
      text: `"Ein breites Angebot ___ Zubehör": "Angebot an + Dativ" = تشكيلة من.\n✓ "an" = من (Angebot an Zubehör).\n✗ "auf" = على، و"Angebot auf Zubehör" ما تتقالش.\n✗ "dafür" = لهذا (für + das)، و"Angebot dafür Zubehör" ما تتقالش.`,
      rule: "ein Angebot an + Dat. (an Waren / an Zubehör)  |  Mangel an + Dat.", ex: "Der Laden hat ein großes Angebot **an** Büchern.", exTr: "الدكّان عندو عرض كبير من الكتب." },
    38: { ok: "SOLLEN", type: "verb", keyword: "sollen = Zweck", bed: "المفروض (الغرض)",
      text: `"Schutzhelme … , die das Fahrrad … so sicher wie einen Panzer machen ___": الغرض من المعدّات.\n✓ "sollen" = الغرض منها / المفروض (جمع).\n✗ "müssen" = لازم: ممكنة، بصح الجملة تحكي على غرض المعدّات موش إلزام.\n✗ "dürfen" = مسموحلهم، وما تتماشاش مع الغرض.`,
      rule: "sollen = Zweck / Absicht (Plural: sollen)", ex: "Die Helme **sollen** die Radfahrer schützen.", exTr: "الخوذات الغرض منها تحمي اللي يسوقو الدرّاجات." },
    39: { ok: "DANN", type: "adjective_adverb", keyword: "wenn …, dann + Verb", bed: "وقتها",
      text: `"Nur wenn es regnet …, ___ sind die Autoschlangen wieder länger": "wenn … dann" والفعل "sind" بعد "dann" مباشرة.\n✓ "dann" = وقتها (نتيجة الشرط، الفعل في الثانية).\n✗ "denn" = خاطر (رابط)، وما تجيش هكا قبل الفعل مباشرة.\n✗ "dafür" = لهذا / مقابل هذا (für + das)، وما تعبّرش على نتيجة الشرط.`,
      rule: "wenn …, dann + Verb (Position 2)", ex: "Wenn es regnet, **dann** bleibe ich zu Hause.", exTr: "إذا تشتي، وقتها نقعد في الدار." },
    40: { ok: "DENN", type: "conjunction", keyword: "denn (Begründung)", bed: "خاطر",
      text: `"___ einen praktischen Wetterschutz … haben die Geschäfte noch nicht im Angebot": الجملة تعطي سبب علاش الأوتو يكثرو مع المطر.\n✓ "denn" = خاطر (رابط سبب، Position 0).\n✗ "dafür" = مقابل ذلك: ممكنة بمعنى تعويض، بصح هنا نعطيو سبب موش بديل.\n✗ "dann" = وقتها (ظرف زمني)، وما فماش ترتيب زمني بين الجمل.`,
      rule: "denn = Grund (Position 0)  |  dafür = Ersatz / Ausgleich", ex: "Er bleibt zu Hause, **denn** er ist krank.", exTr: "يقعد في الدار، خاطر مريض." },
  },

  // ───────────── [15] Sollte man nicht doch besser aufs Fahrrad umsteigen? ─────────────
  15: {
    31: { ok: "KAUM", type: "adjective_adverb", keyword: "kaum einem anderen Land", bed: "تقريبًا ما (بلاد)",
      text: `"In ___ einem anderen Land gibt es so viele Automobilfabriken": تقريبًا ما فما بلاد أخرى.\n✓ "kaum" = بالكاد (kaum einem = تقريبًا حتى واحد).\n✗ "fast" = تقريبًا، و"in fast einem anderen Land" معناها العكس (تقريبًا في بلاد وحدة).\n✗ "beinahe" = تقريبًا، نفس المعنى، ونفس المشكل.`,
      rule: "kaum ein- = fast kein-", ex: "**Kaum** einer kennt den Weg.", exTr: "تقريبًا ما فما حتى واحد يعرف الطريق." },
    32: { ok: "AUF", type: "verb_prep", keyword: "auf etwas umsteigen", bed: "يبدّل لـ",
      text: `"auf ein anderes Verkehrsmittel umzusteigen": "umsteigen" يتبعو "auf" + Akkusativ.\n✓ "auf" = على (umsteigen auf).\n✗ "an" = عند، و"an ein Verkehrsmittel umsteigen" ما تتقالش.\n✗ "vor" = قدّام، وما تتماشاش مع الفعل.`,
      rule: "auf + Akk. umsteigen (auf das Fahrrad / auf Bus und Bahn)", ex: "Ich **steige** auf den Zug **um**.", exTr: "نبدّل للتران." },
    33: { ok: "ZUMEIST", type: "adjective_adverb", keyword: "zumeist (= meistens)", bed: "في الغالب",
      text: `"auf den ___ gut ausgebauten Fahrradwegen": ظرف تكرار قبل الصفة: غالبًا مهيّأة مليح.\n✓ "zumeist" = في الغالب (= meistens).\n✗ "kaum" = بالكاد، و"kaum gut ausgebaut" تناقض (ما هيّاش مهيّأة مليح).\n✗ "fast" = تقريبًا، و"fast gut ausgebaut" ما تعطيش معنى "في الغالب".`,
      rule: "zumeist / meistens = in den meisten Fällen", ex: "Die Straßen sind **zumeist** frei.", exTr: "الطرقات في الغالب فارغة." },
    34: { ok: "STATT", type: "preposition", keyword: "statt … zu", bed: "عوض",
      text: `"Wer Fahrrad fährt ___ zu sitzen": يسوق درّاجة عوض ما يقعد.\n✓ "statt" = عوض (statt … zu + Infinitiv).\n✗ "vor" = قبل، و"vor zu sitzen" ما تتقالش.\n✗ "dafür" = لهذا / مقابل هذا (für + das)، وما تبني Infinitivsatz.`,
      rule: "statt + zu-Infinitiv = anstatt etwas anderes zu tun", ex: "Sie lacht, **statt** zu weinen.", exTr: "هي تضحك عوض ما تبكي." },
    35: { ok: "INNERHALB", type: "preposition", keyword: "innerhalb + Genitiv", bed: "داخل",
      text: `"die meiste Zeit ___ geschlossener Räume": بعد الكلمة Genitiv جمع، والمعنى "داخل".\n✓ "innerhalb" = داخل (+ Genitiv).\n✗ "an" = عند / على، وما تتركّب مع Genitiv.\n✗ "auf" = على، و"auf geschlossener Räume" ما تتقالش.`,
      rule: "innerhalb + Genitiv = im Inneren von", ex: "**Innerhalb** der Stadt gilt Tempo 50.", exTr: "داخل المدينة السرعة 50." },
    36: { ok: "MÜSSEN", type: "verb", keyword: "aufhalten müssen", bed: "لازمهم",
      text: `"die sich … in Büros, Schulen oder Fabriken aufhalten ___": Infinitiv + Modalverb في آخر الجملة الفرعية، والفاعل جمع.\n✓ "müssen" = لازمهم (الظروف تفرض عليهم).\n✗ "dürfen" = مسموحلهم، وما فماش معنى امتياز.\n✗ "sollen" = المفروض: ممكنة، بصح الإلزام هنا من ظروف الخدمة.`,
      rule: "Nebensatz: Infinitiv + Modalverb am Ende (aufhalten müssen)", ex: "Wer arbeitet, **muss** früh aufstehen.", exTr: "اللي يخدم لازمو يقوم بكري." },
    37: { ok: "AN", type: "preposition", keyword: "Angebot an …", bed: "عرض من",
      text: `"Ein breites Angebot ___ Zubehör": تشكيلة واسعة من الإكسسوارات: "an".\n✓ "an" = من (Angebot an + Dativ).\n✗ "auf" = على، وما تتقالش مع "Angebot".\n✗ "dafür" = لهذا (für + das)، موش حرف جر قبل اسم.`,
      rule: "Angebot an / Mangel an / Bedarf an + Dativ", ex: "Es gibt ein großes Angebot **an** Obst.", exTr: "فما عرض كبير من الغلال." },
    38: { ok: "SOLLEN", type: "verb", keyword: "sollen = Zweck", bed: "الغرض منها",
      text: `"die das Fahrrad … so sicher wie einen Panzer machen ___": الغرض من الخوذات والحمايات.\n✓ "sollen" = الغرض منها / المفروض (جمع).\n✗ "müssen" = لازم: ممكنة، بصح هنا غرض موش إلزام.\n✗ "dürfen" = مسموح، وما تتماشاش مع غرض الحماية.`,
      rule: "sollen = Zweck / Funktion einer Sache", ex: "Die Schilder **sollen** vor Gefahr warnen.", exTr: "اللافتات الغرض منها تحذّر من الخطر." },
    39: { ok: "DANN", type: "adjective_adverb", keyword: "dann nach wenn-Satz", bed: "وقتها",
      text: `"Nur wenn es regnet …, ___ sind die Autoschlangen wieder länger": جواب الشرط، والفعل "sind" بعد "dann".\n✓ "dann" = وقتها (جواب الشرط، + فعل في الثانية).\n✗ "denn" = خاطر، وما تتركّبش بهذا الشكل قبل الفعل.\n✗ "vor" = قبل، وما يعطيش نتيجة للشرط.`,
      rule: "wenn-Satz + dann + Verb (Position 2)", ex: "Wenn du Zeit hast, **dann** ruf mich an.", exTr: "إذا عندك وقت، وقتها عيّطلي." },
    40: { ok: "DENN", type: "conjunction", keyword: "denn = Grund", bed: "خاطر",
      text: `"___ einen praktischen Wetterschutz … haben die Geschäfte noch nicht": تفسير لكلام السطر اللي قبل.\n✓ "denn" = خاطر (سبب، Position 0).\n✗ "dafür" = بالمقابل: ممكنة، بصح الجملة هنا تعطي سبب موش تعويض.\n✗ "dann" = وقتها، ما فماش ترتيب زمني.`,
      rule: "denn = Begründung des vorherigen Satzes", ex: "Ich bleibe, **denn** es ist spät.", exTr: "نقعد، خاطر الوقت تأخّر." },
  },

  // ───────────── [16] Ist der Umgang mit Haustieren gesund für Kleinkinder? ─────────────
  16: {
    31: { ok: "ALS", type: "conjunction", keyword: "Komparativ + als", bed: "من (في المقارنة)",
      text: `"seltener krank ___ Kinder in Haushalten ohne Tiere": مقارنة بعد "seltener" (Komparativ).\n✓ "als" = من (Komparativ + als).\n✗ "wie" = كيما: تتقال في الكلام، بصح بعد الـ Komparativ المعتمد "als" (wie للتساوي).\n✗ "um" = بـ (مقدار)، موش رابط مقارنة.`,
      rule: "Komparativ + als (Ungleichheit)  |  so … wie (Gleichheit)", ex: "Er ist älter **als** ich.", exTr: "هو أكبر مني." },
    32: { ok: "VERGANGENEN", type: "grammar_structure", keyword: "in der vergangenen Woche", bed: "الماضية",
      text: `"in der ___ Woche": Dativ مؤنّث بعد "der" ← الصفة تاخذ -en.\n✓ "vergangenen" = الماضية (-en بعد أداة معرّفة، Dativ مؤنّث).\n✗ "früheren" = أقدم (صفة)، و"in der früheren Woche" ما تعني الأسبوع الفايت.\n✗ "deutlich" = واضح (بدون نهاية)، وما يجي قبل "Woche" هكا.`,
      rule: "Dativ Feminin: der + Adjektiv-en + Nomen (in der vergangenen Woche)", ex: "In der **vergangenen** Woche war ich krank.", exTr: "في الجمعة الفايتة كنت مريض." },
    33: { ok: "ZWAR", type: "conjunction", keyword: "zwar … aber", bed: "صحيح",
      text: `"Es wurden ___ keine Erklärungen … geliefert, aber die Vermutung wurde geäußert": اعتراف ثم "aber".\n✓ "zwar" = صحيح (الجزء الأول من zwar … aber).\n✗ "wie" = كيما، موش ظرف تنازل.\n✗ "um" = حرف جر (حول / بـ)، وما يجي قبل "keine" هكا.`,
      rule: "zwar … aber = Zugeständnis + Gegensatz", ex: "Es ist **zwar** teuer, aber gut.", exTr: "صحيح غالي، لكن باهي." },
    34: { ok: "DURCH", type: "preposition", keyword: "durch + Akk. (Mittel)", bed: "عبر / بفضل",
      text: `"Hunde haben nämlich ___ die täglichen Spaziergänge … viel Kontakt": الوسيلة اللي توفّر الاحتكاك.\n✓ "durch" = عبر / بفضل (durch + Akk.).\n✗ "um" = حول، و"um die Spaziergänge" ما تعطيش معنى الوسيلة.\n✗ "wie" = كيما، موش حرف جر.`,
      rule: "durch + Akk. = Mittel / Weg (durch Training, durch Spaziergänge)", ex: "Man lernt **durch** Übung.", exTr: "الواحد يتعلّم بالتمرين." },
    35: { ok: "DIESELBE", type: "pronoun", keyword: "dieselbe Wirkung", bed: "نفس (التأثير)",
      text: `"haben demnach ___ Wirkung": "Wirkung" مؤنّث Akkusativ.\n✓ "dieselbe" = نفس (Akkusativ مؤنّث: dieselbe Wirkung).\n✗ "geringeres" = أقلّ (صفة بنهاية المحايد -es)، و"Wirkung" مؤنّث.\n✗ "deutlich" = واضح (بدون نهاية)، وما يجي قبل "Wirkung" هكا.`,
      rule: "derselbe / dieselbe / dasselbe = identisch (Genus beachten)", ex: "Sie hat **dieselbe** Tasche wie ich.", exTr: "عندها نفس الشنطة كيما أنا." },
    36: { ok: "WURDEN", type: "tense", keyword: "wurden + Partizip II (Passiv)", bed: "تمّت (مراقبتهم)",
      text: `"Für die Studie ___ in Finnland 397 Babys … beobachtet": Passiv، والفاعل جمع (Babys).\n✓ "wurden" = Präteritum Passiv جمع.\n✗ "waren" = Zustandspassiv: ممكنة، بصح تحكي على حالة موش على عملية المراقبة.\n✗ "um" = حرف جر، موش فعل مساعد.`,
      rule: "Vorgangspassiv: wurden + Partizip II (Plural)", ex: "Hundert Personen **wurden** befragt.", exTr: "مائة شخص اتسألو." },
    37: { ok: "GERINGERES", type: "adjective_adverb", keyword: "ein geringeres Risiko", bed: "أقلّ (مخاطر)",
      text: `"ein um 30 % ___ Risiko": صفة مقارنة قبل "Risiko" (محايد، Akkusativ بعد "ein").\n✓ "geringeres" = أقلّ (-es، Neutrum Akkusativ).\n✗ "weniger" = أقلّ: "ein um 30 % weniger Risiko" ممكنة في الكلام، بصح المعتمد "geringeres" (صفة بنهاية).\n✗ "deutlich" = واضح (بدون نهاية)، وما تفيدش معنى "أقلّ".`,
      rule: "ein + Komparativ + -es + Nomen (Neutrum): ein geringeres Risiko", ex: "Das ist ein **geringeres** Problem.", exTr: "هذا مشكل أصغر." },
    38: { ok: "WENIGER", type: "adjective_adverb", keyword: "weniger auftreten", bed: "أقلّ",
      text: `"Ohrenentzündungen ___ auftraten": ظرف كمية = أقلّ.\n✓ "weniger" = أقلّ (ظرف، بدون نهاية).\n✗ "deutlich" = واضح / بوضوح: "deutlich auftraten" معناها ظهرت بوضوح، عكس المقصود (قلّت).\n✗ "geringeres" = صفة بنهاية المحايد، موش ظرف.`,
      rule: "weniger = in geringerem Maß (Adverb, ohne Endung)", ex: "Er schläft jetzt **weniger**.", exTr: "هو يرقد توّا أقلّ." },
    39: { ok: "DEUTLICH", type: "adjective_adverb", keyword: "deutlich besser", bed: "أحسن بوضوح",
      text: `"in Gesellschaft von Tieren ___ besser sei": ظرف درجة قبل Komparativ.\n✓ "deutlich" = بوضوح / بشكل ملحوظ (deutlich besser).\n✗ "weniger" = أقلّ، و"weniger besser" ما تتقالش.\n✗ "zwar" = صحيح (zwar … aber)، رابط تنازل، موش ظرف درجة.`,
      rule: "deutlich + Komparativ = merklich (deutlich besser / größer)", ex: "Es geht ihm **deutlich** besser.", exTr: "هو أحسن بوضوح." },
    40: { ok: "GEGENTEIL", type: "noun", keyword: "das genaue Gegenteil", bed: "العكس",
      text: `"das genaue ___ der jetzigen Ergebnisse": "das" محايد، والاسم "Gegenteil" محايد.\n✓ "Gegenteil" = العكس (das Gegenteil، محايد).\n✗ "Gegensatz" = تناقض، لكنو مذكّر (der Gegensatz)، و"das genaue Gegensatz" ما تتماشاش.\n✗ "dieselbe" = نفس (مؤنّث)، وتناقض المعنى (النتايج عكس بعضها).`,
      rule: "das Gegenteil (Neutrum)  |  der Gegensatz (Maskulinum): im Gegensatz zu", ex: "Er hat das **Gegenteil** gesagt.", exTr: "قال العكس." },
  },
};
