// SB Teil 2 restyle — batch 01: [2] Theater (معدل), [3] Braunbär, [4] Ausbildung mit über 30 (gap 38 HELD: passage prints "vor ___ stehen", should be "zur Verfügung"), [5] Skipiste, [6] Jugend diskutiert
export default {
  // ───────────── [2] Theater für Kinder und Jugendliche (معدل) ─────────────
  2: {
    31: { ok: "SONDERN", type: "conjunction", keyword: "nicht nur … sondern auch", bed: "بل (وزيد)",
      text: `"nicht nur die Kreativität, ___ auch die Körpererfahrung": جملة بجزئين، والجزء الثاني يبدا بـ "sondern auch".\n✓ "sondern" = بل (تكمّل "nicht nur").\n✗ "aber" = لكن (تعارض)، وما تعطيش معنى الزيادة "وزيد" اللي يطلبها "nicht nur".\n✗ "da" = بما إنّو (رابط سبب + فعل في الآخر)، وما فماش سبب هنا.`,
      rule: "nicht nur … sondern auch (beides zusammen)", ex: "Er lernt nicht nur Deutsch, **sondern** auch Spanisch.", exTr: "هو ما يتعلّمش ألماني برك، بل زادا إسباني." },
    32: { ok: "SEIT", type: "preposition", keyword: "seit + Dativ", bed: "منذ",
      text: `"arbeitet ___ vielen Jahren": الفعل في الحاضر ونشاط مستمر من سنين.\n✓ "seit" = منذ (+ Dativ).\n✗ "ab" = اعتبارًا من (بداية من وقت جاي)، موش مدّة مستمرة فاتت.\n✗ "auf" = على، و"auf vielen Jahren" ما تتقالش.`,
      rule: "seit + Dativ = Dauer bis jetzt (Präsens)", ex: "Wir wohnen **seit** zwei Jahren hier.", exTr: "نسكنو هنا منذ عامين." },
    33: { ok: "WEGEN", type: "preposition", keyword: "wegen + Genitiv", bed: "بسبب",
      text: `"die ___ familiärer … Probleme Hilfe benötigen": السبب اللي علاه يحتاجو مساعدة، و"Probleme" في Genitiv.\n✓ "wegen" = بسبب (+ Genitiv).\n✗ "dazu" = لهذا (Pronominaladverb)، وما يتركّبش قدّام اسم في Genitiv.\n✗ "da" = بما إنّو (رابط جملة بفعل)، وبعدو اسم موش جملة.`,
      rule: "wegen + Genitiv (Nomen)  |  da + Satz mit Verb", ex: "**Wegen** der Kälte bleiben die Kinder drinnen.", exTr: "بسبب البرد الصغار يقعدو لداخل." },
    34: { ok: "AB", type: "preposition", keyword: "ab dem kommenden Jahr", bed: "اعتبارًا من",
      text: `"___ dem kommenden Jahr": بداية من نقطة في المستقبل.\n✓ "ab" = اعتبارًا من (+ Dativ).\n✗ "seit" = منذ (ماضي)، والمشروع باش يبدا العام الجاي.\n✗ "am" = an + dem، و"am dem kommenden Jahr" فيها أداة مرتين.`,
      rule: "ab + Dativ = Beginn in der Zukunft  |  am / im enthalten schon den Artikel", ex: "**Ab** dem nächsten Monat arbeite ich Teilzeit.", exTr: "اعتبارًا من الشهر الجاي نخدم نصف وقت." },
    35: { ok: "DES", type: "grammar_structure", keyword: "Ende + Genitiv: des Projekts", bed: "متاع (المشروع)",
      text: `"Am Ende ___ Projekts": بعد "Ende" اسم في Genitiv، و"Projekt" محايد.\n✓ "des" = Genitiv محايد (des Projekts، ونهاية -s).\n✗ "am" = an + dem، و"Am Ende am Projekts" فيها حرف جر مرتين.\n✗ "ab" = اعتبارًا من، وما يتركّبش بعد "Am Ende" قدّام اسم.`,
      rule: "Nomen + Genitiv: des (m / n) + -s  |  der (f / Pl.)", ex: "Am Ende **des** Films gibt es eine Überraschung.", exTr: "في آخر الفيلم فما مفاجأة." },
    36: { ok: "WOLFGANG", type: "noun", keyword: "Schauspieler + Vorname + Nachname", bed: "الاسم الأول",
      text: `"vom Schauspieler ___ Neuhausen": الاسم الكامل = الاسم الأول + اللقب.\n✓ "Wolfgang" = اسم أول (Apposition بعد المهنة).\n✗ "des" = أداة Genitiv، وما تجيش قبل لقب بعد "Schauspieler".\n✗ "keine" = نفي (Negation)، وما تتركّبش مع اسم شخص.`,
      rule: "Berufsbezeichnung + Vorname + Familienname (ohne Artikel)", ex: "Geleitet wird der Kurs vom Lehrer **Thomas** Weber.", exTr: "الدورة يقودها المعلّم توماس فيبر." },
    37: { ok: "KEINE", type: "grammar_structure", keyword: "keine + Plural (Verneinung)", bed: "ما فما حتى",
      text: `"da bei der Stadt ___ Gelder vorhanden waren": سبب: ما فماش فلوس، و"Gelder" جمع.\n✓ "keine" = نفي لـ "Gelder" (Plural).\n✗ "noch" = مازال، وتعطي معنى إيجابي يخالف السبب ("بما إنّو مازال عندهم فلوس" ما يفسّرش علاش المشروع مستحيل).\n✗ "des" = أداة Genitiv، و"des Gelder" ما تتقالش.`,
      rule: "kein- verneint ein Nomen: Plural → keine", ex: "Es gab **keine** Plätze mehr.", exTr: "ما عادش فما بلايص." },
    38: { ok: "AUFGEHÄNGT", type: "verb", keyword: "werden + Partizip II (aufhängen)", bed: "تتعلّق",
      text: `"werden Plakate ___": Passiv: werden + Partizip II.\n✓ "aufgehängt" = Partizip II من "aufhängen" (werden … aufgehängt).\n✗ "auf" = حرف جر (على) يحتاج اسم بعدو، وما يكمّلش الـ Passiv.\n✗ "dazu" = Pronominaladverb، موش Partizip II.`,
      rule: "Vorgangspassiv: werden + Partizip II (aufgehängt)", ex: "In der Stadt werden neue Schilder **aufgehängt**.", exTr: "في المدينة تتعلّق لافتات جديدة." },
    39: { ok: "AUF", type: "fixed_expression", keyword: "auf diese Weise", bed: "بهذه الطريقة",
      text: `تعبير ثابت: "auf diese Weise" = بهذه الطريقة.\n✓ "auf" = (auf + Akk. + Weise).\n✗ "am" = an + dem (أداة مدمجة)، و"am diese Weise" فيها أداة مرتين.\n✗ "ab" = اعتبارًا من (زمن)، موش طريقة.`,
      rule: "auf diese Weise = so / dadurch (feste Wendung)", ex: "**Auf** diese Weise sparst du viel Zeit.", exTr: "بهذه الطريقة توفّر برشا وقت." },
    40: { ok: "NOCH", type: "adjective_adverb", keyword: "noch (zusätzlich / weiterhin)", bed: "لسّا (زيادة)",
      text: `"werden … ___ ehrenamtliche Helfer gesucht": الجملة تضيف طلب: لسّا يلوّجو على متطوعين.\n✓ "noch" = لسّا (مازال، + جمع بدون أداة).\n✗ "keine" = ما فما (نفي)، وتناقض الطلب (يلوّجو على متطوعين).\n✗ "des" = أداة Genitiv، و"des ehrenamtliche Helfer" ما تتقالش.`,
      rule: "noch = weiterhin / zusätzlich  |  schon = bereits", ex: "Wir suchen **noch** Mitspieler.", exTr: "نلوّجو لسّا على لاعبين." },
  },

  // ───────────── [3] Das Schicksal des Braunbären ─────────────
  3: {
    31: { ok: "WÄHREND", type: "preposition", keyword: "während + Genitiv (Zeitraum)", bed: "خلال",
      text: `"___ der vergangenen 12000 Jahre": حرف جر زمني + Genitiv (الفترة).\n✓ "während" = أثناء (+ Genitiv).\n✗ "um" = بـ / حوالي (um + Akk. مع وقت أو مقدار)، و"um der vergangenen" ما تتقالش.\n✗ "sowie" = وكذلك (رابط عطف)، موش حرف جر زمني.`,
      rule: "während + Genitiv (Zeitraum) / + Nebensatz", ex: "**Während** des Sommers bleibt das Café lange offen.", exTr: "خلال الصيف المقهى يبقى مفتوح برشا." },
    32: { ok: "DADURCH", type: "pronoun_adverb", keyword: "dadurch = infolgedessen", bed: "بسبب هذا",
      text: `"___ wurde der Lebensraum verkleinert": نتيجة للمساحات الجديدة للفلاحة، والفعل "wurde" بعدو مباشرة.\n✓ "dadurch" = بسبب هذا (ظرف، الفعل في الثانية).\n✗ "dafür" = في مقابل هذا / لأجل هذا (für + das)، وما تعطيش علاقة سبب ونتيجة هنا.\n✗ "denn" = خاطر (رابط، الفعل يجي بعد الفاعل)، و"Denn wurde" ما تتركّبش.`,
      rule: "dadurch + Verb (Position 2) = Folge  |  denn + Subjekt + Verb", ex: "Die Preise stiegen, **dadurch** kauften weniger Leute.", exTr: "الأسعار ارتفعت، وبسبب هذا شرات الناس أقلّ." },
    33: { ok: "DASS", type: "conjunction", keyword: "unumstritten, dass …", bed: "إنّو",
      text: `"unumstritten, ___ das Verschwinden … zusammenhängt": محتوى الحقيقة المعروفة.\n✓ "dass" = إنّو (محتوى، + فعل في الآخر).\n✗ "sodass" = بحيث (نتيجة)، موش محتوى.\n✗ "während" = بينما / أثناء، موش محتوى خبر.`,
      rule: "dass-Satz nach Aussage-Adjektiven (es ist klar / bekannt, dass)", ex: "Es ist bekannt, **dass** Bären Winterschlaf halten.", exTr: "معروف إنّو الدبّ يرقد في الشتاء." },
    34: { ok: "UM", type: "preposition", keyword: "steigen um + Akk. (Differenz)", bed: "بـ (مقدار)",
      text: `"angestiegen ___ zwei bis vier Grad": الفرق في الدرجة.\n✓ "um" = بـ (um + Akk. = مقدار الزيادة).\n✗ "während" = أثناء، موش مقدار.\n✗ "sowie" = وكذلك (رابط عطف)، موش مقدار.`,
      rule: "um + Zahl = Unterschied (um zwei Grad steigen / sinken)", ex: "Die Preise sind **um** zehn Prozent gestiegen.", exTr: "الأسعار ارتفعت بعشرة بالمية." },
    35: { ok: "NACHKOMMEN", type: "noun", keyword: "Nachkommen bekommen", bed: "ذرّية",
      text: `"bekamen die Braunbären weniger ___, und ihre Zahl schrumpfte": الصغار (الذرّية).\n✓ "Nachkommen" = ذرّية (الصغار، جمع).\n✗ "Vorkommen" = وجود / ظهور (occurrence)، و"weniger Vorkommen bekommen" ما تتقالش.\n✗ "Begriffe" = مفاهيم، ما علاقتها بالتكاثر.`,
      rule: "Nachkommen = Kinder / Junge (nur Plural)  |  Vorkommen = Auftreten", ex: "Die Tiere bekamen im Frühling **Nachkommen**.", exTr: "الحيوانات جابو صغار في الربيع." },
    36: { ok: "DAFÜR", type: "pronoun_adverb", keyword: "Grund dafür", bed: "السبب في هذا",
      text: `"Der Grund ___ ist, dass …": "Grund" يتبعو "für"، و"dafür" (= für + das) يرجع على السبب اللي قبل.\n✓ "dafür" = لهذا (Grund + für).\n✗ "dadurch" = بهذه الوسيلة (durch + das)، و"Grund dadurch" ما تتقالش.\n✗ "denn" = خاطر (رابط)، موش ضمير ظرفي يجي بعد "Grund".`,
      rule: "Grund für + Akk. → der Grund dafür", ex: "Der Grund **dafür** ist einfach.", exTr: "السبب في هذا بسيط." },
    37: { ok: "DENN", type: "conjunction", keyword: "denn + Hauptsatz (Grund)", bed: "خاطر",
      text: `", ___ sie bringen im Winter ihre Jungen zur Welt": الفعل "bringen" في المرتبة الثانية، يعني Hauptsatz، والجملة تعطي سبب.\n✓ "denn" = خاطر (+ جملة رئيسية).\n✗ "sodass" = بحيث (نتيجة + فعل في الآخر)، وهنا الفعل في الثانية وما فماش نتيجة.\n✗ "dass" = إنّو (محتوى + فعل في الآخر)، موش سبب.`,
      rule: "denn + Hauptsatz (Verb Position 2)  |  sodass / dass + Nebensatz", ex: "Sie schläft, **denn** sie ist müde.", exTr: "هي ترقد، خاطر تعبانة." },
    38: { ok: "EINGRIFFE", type: "noun", keyword: "Eingriff in + Akk.", bed: "تدخّلات",
      text: `"die menschlichen ___ in die Naturlandschaften": تدخّل الإنسان في الطبيعة (+ "in").\n✓ "Eingriffe" = تدخّلات (Eingriff in + Akk.).\n✗ "Begriffe" = مفاهيم، وما تتركّبش مع "in die Naturlandschaften".\n✗ "Nachkommen" = ذرّية، وما تتماشاش مع "menschlichen … in die Naturlandschaften".`,
      rule: "Eingriff in + Akk. (in die Natur, in die Privatsphäre)", ex: "Bauen ist ein **Eingriff** in die Natur.", exTr: "البناء تدخّل في الطبيعة." },
    39: { ok: "NOCH", type: "adjective_adverb", keyword: "noch überall (damals noch)", bed: "لسّا (وقتها)",
      text: `"war der Braunbär ___ überall in Europa heimisch": في الماضي لسّا (قبل ما ينقرض).\n✓ "noch" = لسّا (الوضع كان مازال قايم).\n✗ "sowie" = وكذلك (رابط)، موش ظرف زمني.\n✗ "während" = أثناء (رابط جملة / حرف جر)، وما يجيش قدّام "überall" هكا.`,
      rule: "noch = zu diesem Zeitpunkt immer noch", ex: "Damals gab es **noch** keine Handys.", exTr: "وقتها مازال ما كانش فما تلفونات." },
    40: { ok: "GING", type: "fixed_expression", keyword: "es geht bergab mit …", bed: "(الحال) ساء",
      text: `"Richtig bergab ___ es mit dem Braunbären": تعبير "es geht bergab mit jdm." = حالو يسوء، والفعل المصرّف في المرتبة الثانية.\n✓ "ging" = Präteritum من "gehen" (es ging bergab).\n✗ "kam" = Präteritum من "kommen" (es kam zu …)، و"bergab kam es" ما تتقالش.\n✗ "Vorkommen" = اسم / مصدر، موش فعل مصرّف.`,
      rule: "es geht bergab mit jdm. = es wird schlechter  |  es kommt zu + Dativ", ex: "Mit der Firma **ging** es schnell bergab.", exTr: "الشركة حالتها ساءت بسرعة." },
  },

  // ───────────── [4] Ausbildung mit über 30 (gap 38 held) ─────────────
  4: {
    31: { ok: "DENN", type: "conjunction", keyword: "denn + Hauptsatz", bed: "خاطر",
      text: `"… noch einmal die Schulbank. ___ sie hat sich … entschieden": الجملة تشرح ليش، وبعد الرابط الفاعل ثم الفعل.\n✓ "denn" = خاطر (+ جملة رئيسية: "sie hat …").\n✗ "da" = بما إنّو: يفتح جملة فرعية وفعلها في الآخر، وهنا "hat" بعد "sie" مباشرة.\n✗ "sondern" = بل: تحتاج نفي قبلها، وما فماش نفي.`,
      rule: "denn + Subjekt + Verb (Position 2)  |  da + Nebensatz", ex: "Sie lernt viel, **denn** sie will die Prüfung bestehen.", exTr: "تقرا برشا، خاطر تحب تنجّح في الامتحان." },
    32: { ok: "MÖCHTE", type: "verb", keyword: "möchte + Infinitiv", bed: "تحب",
      text: `"Ihr Ziel: Sie ___ in den Streifendienst gehen": الهدف = رغبة، والفاعل مفرد "sie".\n✓ "möchte" = تحب (رغبة، 3. Person Singular).\n✗ "sollte" = المفروض (واجب أو نصيحة)، وهنا "Ihr Ziel" يعني رغبة شخصية.\n✗ "könnten" = جمع (Konjunktiv II)، والفاعل مفرد.`,
      rule: "möchte = Wunsch / Ziel (er / sie / es möchte)", ex: "Er **möchte** Arzt werden.", exTr: "يحب يولّي طبيب." },
    33: { ok: "DA", type: "conjunction", keyword: "da + Nebensatz (Grund)", bed: "بما إنّو",
      text: `"___ es heute in vielen Branchen aber an Nachwuchs fehlt": سبب معروف، والفعل "fehlt" في الآخر.\n✓ "da" = بما إنّو (+ فعل في الآخر).\n✗ "denn" = خاطر لكن الفعل يجي في الثانية، وما تجيش في أول جملة قبل الجملة الرئيسية هكا.\n✗ "trotzdem" = رغم ذلك (ظرف، الفعل في الثانية)، والمعنى يخالف: النقص هو اللي يعطي السبب.`,
      rule: "da / weil + Nebensatz (Verb am Ende)  |  trotzdem + Hauptsatz", ex: "**Da** es regnet, nehme ich einen Schirm.", exTr: "بما إنّو تشتي، ناخذ مظلّة." },
    34: { ok: "CHANCE", type: "noun", keyword: "eine Chance geben", bed: "فرصة",
      text: `"geben sie öfter auch Älteren eine ___": "eine Chance geben" = يعطيو فرصة.\n✓ "Chance" = فرصة (مؤنّث، يتماشى مع "eine").\n✗ "Auswahl" = اختيار / تشكيلة، و"eine Auswahl geben" ما تتقالش.\n✗ "Verfügung" = أمر إداري ("eine Verfügung erlassen")، موش فرصة.`,
      rule: "jdm. eine Chance geben  |  eine Auswahl treffen  |  eine Verfügung erlassen", ex: "Der Chef gibt dem Neuen **eine Chance**.", exTr: "الشاف يعطي الجديد فرصة." },
    35: { ok: "WARUM", type: "conjunction", keyword: "erklären, warum …", bed: "علاش",
      text: `"erklärt, ___ sein Arbeitgeber gerne Ältere ausbildet": سؤال غير مباشر على السبب، والجواب جاي بعد النقطتين.\n✓ "warum" = علاش (indirekte Frage).\n✗ "da" = بما إنّو: ممكنة نحويًّا، بصح معناها "يشرح لأنّ…"، والمقصود شنوّة السبب اللي يشرحو.\n✗ "denn" = خاطر (+ فعل في الثانية)، وهنا "ausbildet" في الآخر.`,
      rule: "indirekte Frage: Fragewort + Nebensatz (Verb am Ende)", ex: "Er erklärt, **warum** er umzieht.", exTr: "يشرح علاش باش يبدّل السكنى." },
    36: { ok: "ÜBERNEHMEN", type: "verb", keyword: "Verantwortung übernehmen", bed: "يتحمّل",
      text: `"bereit, Verantwortung zu ___": "Verantwortung übernehmen" = يتحمّل المسؤولية.\n✓ "übernehmen" = يتحمّل (Infinitiv بعد "zu").\n✗ "ziehen" = يجرّ: "zur Verantwortung ziehen" = يحاسب، موش يتحمّل.\n✗ "durften" = فعل مصرّف (ماضي)، وبعد "zu" لازم Infinitiv.`,
      rule: "Verantwortung übernehmen  |  jdn. zur Verantwortung ziehen", ex: "Sie will mehr Verantwortung **übernehmen**.", exTr: "تحب تتحمّل مسؤولية أكثر." },
    37: { ok: "KÖNNTEN", type: "verb", keyword: "könnten (Möglichkeit, Plural)", bed: "ينجّمو",
      text: `"Zudem ___ sie die Jüngeren unterstützen": "sie" جمع (الأكبر سنًّا)، وإمكانية.\n✓ "könnten" = ينجّمو (Konjunktiv II جمع).\n✗ "sollte" = المفروض (مفرد)، ما يطابقش "sie" الجمع.\n✗ "durften" = كانو مسموحلهم (ماضي)، والجملة تتكلّم على إمكانية عامة.`,
      rule: "Konjunktiv II: könnten = Möglichkeit (sie / wir)", ex: "Die Älteren **könnten** den Jungen helfen.", exTr: "الكبار ينجّمو يعاونو الصغار." },
    39: { ok: "TROTZDEM", type: "adjective_adverb", keyword: "trotzdem (Konzession)", bed: "رغم هذا",
      text: `"___ haben ältere Azubis in vielen Bereichen Möglichkeiten": بعد الاعتراض (يخدمو أقصر) نكمّلو "رغم هذا"، والفعل "haben" بعد الظرف مباشرة.\n✓ "trotzdem" = رغم هذا (ظرف تنازل، الفعل في الثانية).\n✗ "dagegen" = بالمقابل / ضدّ هذا: ممكنة نحويًّا، بصح الجملة تحكي على استمرار الإمكانيات رغم الاعتراض.\n✗ "da" = بما إنّو (رابط سبب + فعل في الآخر)، وهنا "haben" في الثانية.`,
      rule: "trotzdem + Verb (Position 2) = Gegensatz zur Erwartung", ex: "Es regnet, **trotzdem** gehen wir spazieren.", exTr: "تشتي، رغم هذا نمشيو نتمشّاو." },
    40: { ok: "SONDERN", type: "conjunction", keyword: "nicht …, sondern …", bed: "بل",
      text: `"nicht nach dem Alter festgelegt, ___ es wird … ermittelt": بعد النفي نصحّحو بـ "sondern".\n✓ "sondern" = بل (تصحيح بعد نفي).\n✗ "denn" = خاطر (سبب): ممكنة نحويًّا، بصح الجملة تصحّح معيار ("موش العمر، بل الحاجة") موش تعطي سبب.\n✗ "trotzdem" = رغم هذا (تنازل)، وما فماش تناقض بين المعنيين هنا.`,
      rule: "nicht A, sondern B = Korrektur nach Verneinung  |  denn = Grund", ex: "Das ist nicht rot, **sondern** orange.", exTr: "هذا موش أحمر، بل برتقالي." },
  },

  // ───────────── [5] Die wichtigsten Regeln auf der Skipiste ─────────────
  5: {
    31: { ok: "RECHNEN", type: "verb_prep", keyword: "mit etwas rechnen (müssen)", bed: "يتوقّع",
      text: `"muss auch mit rechtlichen Folgen ___": "mit etwas rechnen müssen" = يتوقّع / يتحمّل.\n✓ "rechnen" = يحسب حسابو / يتوقّع (rechnen mit).\n✗ "angeben" = يذكر (أو يتفاخر)، و"mit Folgen angeben" معناها يتباهى بالعواقب.\n✗ "gelten" = يسري / صالح، و"mit Folgen gelten" ما تتقالش.`,
      rule: "mit + Dativ rechnen = erwarten  |  angeben = nennen / prahlen", ex: "Wir **rechnen** mit Regen.", exTr: "نتوقّعو مطر." },
    32: { ok: "GÜLTIG", type: "adjective_adverb", keyword: "gültig sein", bed: "ساري",
      text: `"Das Strafgesetzbuch ist sowohl auf der Straße als auch auf der Piste ___": "sein + Adjektiv": صالح / ساري.\n✓ "gültig" = ساري المفعول (صفة بعد "ist").\n✗ "gelten" = يسري (فعل Infinitiv)، وبعد "ist" ما يجيش Infinitiv ("gilt" كان).\n✗ "kann" = ينجّم (فعل مساعد مصرّف)، وما يكمّلش "ist … gültig".`,
      rule: "gültig sein (Adjektiv)  |  gelten (Verb): es gilt", ex: "Die Fahrkarte ist heute noch **gültig**.", exTr: "التذكرة مازالت سارية اليوم." },
    33: { ok: "VOR", type: "verb", keyword: "vorsehen (sieht … vor)", bed: "ينصّ على",
      text: `"sieht das Gesetz Freiheitsstrafen bis zu 6 Monaten ___": الفعل المنفصل "vorsehen": "sieht … vor".\n✓ "vor" = الجزء المنفصل من "vorsehen" (sieht … vor = ينصّ على).\n✗ "zwar" = صحيح (zwar … aber)، رابط تنازل، موش جزء من فعل.\n✗ "so" = هكا (ظرف طريقة)، وما يكمّلش فعل منفصل.`,
      rule: "trennbar: vorsehen → sieht … vor", ex: "Der Plan sieht drei Pausen **vor**.", exTr: "الخطّة تنصّ على ثلاث استراحات." },
    34: { ok: "SOLLTE", type: "verb", keyword: "sollte = Empfehlung", bed: "ينبغي",
      text: `"Jeder Wintersportler ___ diese Regeln kennen": توصية / واجب مخفّف.\n✓ "sollte" = لازم / ينبغي (Konjunktiv II).\n✗ "kann" = ينجّم، ما يعبّرش على واجب.\n✗ "darf" = مسموح، وما يتماشاش مع قواعد لازم الكلّ يعرفها.`,
      rule: "sollte = Empfehlung / Pflicht  |  kann = Möglichkeit  |  darf = Erlaubnis", ex: "Jeder **sollte** Erste Hilfe können.", exTr: "كلّ واحد ينبغي يعرف الإسعافات الأولية." },
    35: { ok: "SO", type: "adjective_adverb", keyword: "so … dass", bed: "بطريقة (باش)",
      text: `"muss sich stets ___ verhalten, dass er keinen anderen gefährdet": "so … dass" (نتيجة / شرط).\n✓ "so" = هكا / بطريقة (so … dass).\n✗ "zwar" = صحيح (zwar … aber)، وما فماش "aber" ولا تنازل.\n✗ "allerdings" = لكن / غير إنّو (تقييد)، موش ظرف طريقة قبل "dass".`,
      rule: "so + Verb / Adj., dass + Nebensatz (Folge / Bedingung)", ex: "Sie spricht **so** leise, dass man sie kaum hört.", exTr: "تحكي بصوت واطي برشا لدرجة ما تتسمعش تقريبًا." },
    36: { ok: "ANPASSEN", type: "verb", keyword: "etwas + Dativ anpassen", bed: "يكيّف",
      text: `"die eigene Geschwindigkeit … seinem Können … ___": "etwas + Dativ anpassen" = يكيّف.\n✓ "anpassen" = يكيّف (etwas einer Sache anpassen).\n✗ "angeben" = يذكر / يتفاخر، موش يكيّف.\n✗ "einordnen" = يصنّف أو يندمج (في الطريق)، موش يكيّف سرعتو.`,
      rule: "etwas (Akk.) einer Sache (Dat.) anpassen", ex: "Man muss die Kleidung dem Wetter **anpassen**.", exTr: "لازم الواحد يكيّف اللبسة مع الطقس." },
    37: { ok: "ALLERDINGS", type: "adjective_adverb", keyword: "allerdings (Einschränkung)", bed: "لكن (بشرط)",
      text: `"Überholen darf man rechts oder links, ___ immer in einem Abstand …": تقييد للسماح: مسموح، لكن بشرط.\n✓ "allerdings" = غير إنّو / لكن (تقييد).\n✗ "zwar" = صحيح (تنازل)، وتحتاج "aber" بعدها.\n✗ "so" = هكا (طريقة)، وما تعطيش معنى التقييد.`,
      rule: "allerdings = jedoch / aber (schränkt ein)", ex: "Das Essen ist gut, **allerdings** etwas teuer.", exTr: "الماكلة باهية، لكن غالية شوية." },
    38: { ok: "RAND", type: "noun", keyword: "den Rand benützen", bed: "الحافة",
      text: `"Aufsteigende Skifahrer dürfen nur den ___ einer Abfahrtsstrecke benützen": "den" مذكّر Akkusativ.\n✓ "Rand" = حافة (مذكّر: den Rand).\n✗ "Stelle" = مكان (مؤنّث: "die Stelle")، و"den Stelle" ما تتماشاش مع "den".\n✗ "anpassen" = فعل، وبعد "den" نحتاج اسم.`,
      rule: "der Rand (mask.) → den Rand (Akk.)  |  die Stelle (fem.)", ex: "Bleib am **Rand** der Piste.", exTr: "ابقى على حافة المسلك." },
    39: { ok: "STELLE", type: "noun", keyword: "eine solche Stelle (fem.)", bed: "مكان / نقطة",
      text: `"eine solche ___ so schnell wie möglich freimachen": "eine" مؤنّث.\n✓ "Stelle" = مكان / نقطة (مؤنّث: eine solche Stelle).\n✗ "Rand" = حافة (مذكّر)، و"eine solche Rand" ما تتقالش.\n✗ "angeben" = فعل، وبعد "eine solche" نحتاج اسم.`,
      rule: "die Stelle (fem.): eine solche Stelle  |  der Rand (mask.)", ex: "An dieser **Stelle** ist die Piste eng.", exTr: "في هذا المكان المسلك ضيّق." },
    40: { ok: "ANGEBEN", type: "verb", keyword: "Personalien angeben", bed: "يذكر (بياناتو)",
      text: `"seine Personalien ___": "Personalien angeben" = يقدّم بياناتو.\n✓ "angeben" = يقدّم / يذكر (Personalien angeben).\n✗ "anpassen" = يكيّف، موش يقدّم بيانات.\n✗ "einordnen" = يصنّف / يدخل في صفّ، موش يقدّم بيانات.`,
      rule: "Personalien / Name / Grund angeben = nennen  |  angeben = prahlen", ex: "Bitte **geben** Sie Ihren Namen **an**.", exTr: "بالله أذكر اسمك." },
  },

  // ───────────── [6] Jugend diskutiert – mach mit! ( Original ) ─────────────
  6: {
    31: { ok: "SEIT", type: "preposition", keyword: "seit + Zeitpunkt", bed: "منذ",
      text: `"gibt es bereits ___ Herbst 2002": موعد بدا في الماضي ومازال.\n✓ "seit" = منذ (+ Dativ، بداية في الماضي ومازال).\n✗ "vor" = قبل (vor + Dativ مع مدّة: "vor zwei Jahren")، ما تتماشاش مع "seit Herbst 2002" ومع "gibt es bereits".\n✗ "an" = على / في، و"an Herbst" ما تتقالش (يتقال "im Herbst").`,
      rule: "seit + Zeitpunkt / Dauer = bis jetzt", ex: "Ich lebe **seit** Mai in Berlin.", exTr: "نعيش في برلين منذ ماي." },
    32: { ok: "WIE", type: "fixed_expression", keyword: "wie immer", bed: "كالعادة",
      text: `"___ immer bereiten sich die Teilnehmer … vor": تعبير ثابت "wie immer" = كالعادة.\n✓ "wie" = كيما (wie immer = كالعادة).\n✗ "was" = شنوّة: "was immer" = أيّ شيء (+ جملة فرعية بفعل في الآخر)، وهنا الفعل في الثانية.\n✗ "als" = وقتما / من (مقارنة)، و"als immer" ما تتقالش.`,
      rule: "wie immer = wie gewohnt", ex: "Er kommt **wie** immer zu spät.", exTr: "يجي كالعادة متأخّر." },
    33: { ok: "WARUM", type: "conjunction", keyword: "sich fragen, warum …", bed: "علاش",
      text: `"Du fragst dich, ___ du teilnehmen solltest?": سؤال على السبب.\n✓ "warum" = علاش (indirekte Frage).\n✗ "weil" = خاطر (جواب)، موش كلمة سؤال.\n✗ "obwohl" = رغم إنّو (تنازل)، موش سؤال.`,
      rule: "sich fragen + Fragewort (warum / wie / ob) + Nebensatz", ex: "Ich frage mich, **warum** er nicht anruft.", exTr: "نسأل روحي علاش ما يعيّطش." },
    34: { ok: "AUSSERDEM", type: "adjective_adverb", keyword: "außerdem + Verb", bed: "وزيد",
      text: `"___ bietet dir "Jugend diskutiert" die Chance …": إضافة، والفعل "bietet" بعدو مباشرة.\n✓ "außerdem" = وزيد (إضافة، ظرف + فعل في الثانية).\n✗ "darunter" = من بينهم / تحت هذا (يحتاج مرجع)، وما يضيفش فائدة جديدة.\n✗ "obwohl" = رغم إنّو (رابط جملة فرعية + فعل في الآخر)، و"bietet" هنا في الثانية.`,
      rule: "außerdem = zusätzlich (Verb Position 2)  |  obwohl + Nebensatz", ex: "Er ist nett, **außerdem** ist er hilfsbereit.", exTr: "هو لطيف، وزيد يحب يعاون." },
    35: { ok: "AN", type: "verb_prep", keyword: "teilnehmen an + Dativ", bed: "تشارك في",
      text: `"die dann ___ Regionalwettbewerben teilnehmen": "teilnehmen an + Dativ".\n✓ "an" = في (teilnehmen an).\n✗ "bei" = عند: "bei einem Wettbewerb mitmachen" ممكنة، بصح "teilnehmen" يتبعو "an".\n✗ "vor" = قبل / قدّام، وما تتركّبش مع "teilnehmen".`,
      rule: "an + Dat. teilnehmen  |  bei + Dat. mitmachen", ex: "Ich nehme **an** dem Kurs teil.", exTr: "نشارك في الدورة." },
    36: { ok: "ALS", type: "preposition", keyword: "als Preis", bed: "كجوائز",
      text: `"___ Preise kann man professionelle Trainings gewinnen": "als Preise" = كجوائز.\n✓ "als" = كـ (als Preis / als Belohnung).\n✗ "wie" = كيما (مقارنة)، و"wie Preise" معناها "مثل الجوائز".\n✗ "bei" = عند، و"bei Preise" ما تتقالش.`,
      rule: "als + Nomen = in der Funktion von  |  wie = Vergleich", ex: "Sie bekommt ein Buch **als** Geschenk.", exTr: "تاخذ كتاب كهدية." },
    37: { ok: "BEI", type: "preposition", keyword: "bei + Dativ (Aktivität)", bed: "في (خلال)",
      text: `"___ "Jugend diskutiert" kannst du viel lernen": "bei + Dativ" مع نشاط / مسابقة.\n✓ "bei" = في / خلال (bei + Dativ = أثناء نشاط).\n✗ "an" = على، و"an Jugend diskutiert" ما تتقالش (تحتاج "teilnehmen an").\n✗ "seit" = منذ، موش بداية جملة بهذا المعنى.`,
      rule: "bei + Dativ = während / im Rahmen von", ex: "**Bei** der Arbeit lerne ich viel.", exTr: "في الخدمة نتعلّم برشا." },
    38: { ok: "WEIL", type: "conjunction", keyword: "weil + Nebensatz", bed: "خاطر",
      text: `"mehr Selbstbewusstsein, ___ du lernst, wie man das Wort ergreift": سبب.\n✓ "weil" = خاطر (+ فعل في الآخر).\n✗ "obwohl" = رغم إنّو (تنازل)، والمنطق سبب.\n✗ "nachdem" = بعد ما (ترتيب زمني)، موش سبب.`,
      rule: "weil + Nebensatz (Grund)  |  nachdem = zeitlich  |  obwohl = Gegensatz", ex: "Ich gehe früh, **weil** ich müde bin.", exTr: "نمشي بكري خاطر تعبان." },
    39: { ok: "WAS", type: "pronoun", keyword: "zeigen, was …", bed: "اللي",
      text: `"zeigen dir … , ___ du vielleicht selbst noch nicht gesehen hast": اللي ما شفتوش.\n✓ "was" = اللي / شنوّة (يعوّض شي غير محدّد).\n✗ "wer" = شكون (لشخص)، والمقصود أشياء.\n✗ "die" = اللي (Relativpronomen يحتاج اسم جمع قبلو مباشرة)، وما فماش.`,
      rule: "was = etwas Unbestimmtes (Dinge, Seiten)  |  wer = Person", ex: "Ich zeige dir, **was** ich gefunden habe.", exTr: "نوريك اللي لقيتو." },
    40: { ok: "WER", type: "pronoun", keyword: "wer … , der …", bed: "اللي / كلّ من",
      text: `"___ das alles im Unterricht gelernt hat, kann …": أي واحد (فاعل شخص).\n✓ "wer" = اللي (أي واحد) — فاعل شخص.\n✗ "was" = شنوّة (لأشياء)، و"das alles" هو المفعول به، والفاعل شخص.\n✗ "die" = Relativpronomen يحتاج اسم قبلو، ما يبدّاش جملة بهذا الشكل.`,
      rule: "Wer + Verb, … = jeder, der …", ex: "**Wer** viel übt, wird besser.", exTr: "اللي يتمرّن برشا يتحسّن." },
  },
};
