// SB Teil 2 restyle — batch 13: [48] Garten in der Stadt (source passage is garbled but the gap words are fine), plus the NON-suspect gaps of the held exercises:
// [60] (gap 39 key IM vs "statt" omitted), [63] (gaps 31 and 35 omitted: odd colon / missing separable "an"), [64] (gap 36 omitted: bank has "sozial" but the text needs "soziale")
export default {
  // ───────────── [48] Garten in der Stadt ─────────────
  48: {
    31: { ok: "SETZEN", type: "verb", keyword: "sich auf eine Liste setzen lassen", bed: "يسجّلو روحهم",
      text: `"Daher lassen sie sich auf lange Wartelisten … ___": "sich auf eine Liste setzen lassen" = يسجّل روحو في قائمة، وبعد "lassen" Infinitiv.\n✓ "setzen" = يحطّ (Infinitiv بعد "lassen": sich setzen lassen).\n✗ "gezüchtet" = Partizip II (متربّي)، وبعد "lassen" نحتاج Infinitiv.\n✗ "erzogen" = Partizip II (متربّى)، وما يتماشاش مع "Wartelisten".`,
      rule: "sich auf etwas setzen lassen = sich eintragen lassen (lassen + Infinitiv)", ex: "Er lässt sich auf die Liste **setzen**.", exTr: "هو يخلّي ينكتب في القائمة." },
    32: { ok: "GEZÜCHTET", type: "tense", keyword: "gezüchtet werden (Passiv)", bed: "تتربّى (تتزرع)",
      text: `"werden Blumen ___": Passiv: werden + Partizip II، و"Blumen züchten" = يزرعو أزهار.\n✓ "gezüchtet" = Partizip II من "züchten" (يربّي نباتات / حيوانات).\n✗ "bezüchtet" = شكل غير موجود في اللغة.\n✗ "erzogen" = Partizip II من "erziehen" (يربّي أطفال)، وما يتماشاش مع الأزهار.`,
      rule: "Pflanzen / Tiere züchten  |  Kinder erziehen", ex: "Hier **werden** Rosen **gezüchtet**.", exTr: "هنا الورد يتزرع." },
    33: { ok: "VORTEILE", type: "noun", keyword: "die Vorteile von + Dativ", bed: "المزايا",
      text: `"Die ___ von grünen Städten liegen auf der Hand": اسم جمع (die) + "von".\n✓ "Vorteile" = مزايا (جمع).\n✗ "von" = حرف جر، موش اسم بعد "Die".\n✗ "solche" = مثل هذي (ضمير)، و"Die solche von" ما تتقالش.`,
      rule: "die Vorteile von + Dativ (Plural-Nomen mit die)", ex: "Die **Vorteile** von Sport sind bekannt.", exTr: "مزايا الرياضة معروفة." },
    34: { ok: "HÖHER", type: "adjective_adverb", keyword: "je mehr …, desto höher", bed: "أعلى",
      text: `"Je mehr Pflanzen es … gibt, desto ___ ist die Lebensqualität": "je … desto" + Komparativ.\n✓ "höher" = أعلى (Komparativ).\n✗ "klein" = صغير (بدون -er)، وعكس المعنى.\n✗ "kein" = حتى (نفي)، موش Komparativ.`,
      rule: "je + Komparativ …, desto + Komparativ (je mehr, desto höher)", ex: "Je früher, desto **besser**.", exTr: "كلّما بكري، كلّما أحسن." },
    35: { ok: "VOR", type: "preposition", keyword: "Schutz vor + Dativ", bed: "من",
      text: `"natürliche Schutzwälle ___ Wind und Lärm": "Schutz vor" = حماية من.\n✓ "vor" = من (Schutz vor + Dativ).\n✗ "von" = من / متاع: "Schutzwälle von Wind" معناها مصنوعة من الريح، موش ضدّو.\n✗ "es" = ضمير غير شخصي، موش حرف جر.`,
      rule: "Schutz vor + Dativ = gegen etwas schützen", ex: "Der Hut gibt **Schutz** vor der Sonne.", exTr: "القبّعة تعطي حماية من الشمس." },
    36: { ok: "ES", type: "pronoun", keyword: "wo es grünt und blüht", bed: "(شكلي) هو",
      text: `"Wo ___ grünt und blüht": أفعال الطبيعة ("grünen, blühen") تتطلّب فاعل شكلي "es".\n✓ "es" = ضمير غير شخصي (es grünt).\n✗ "kein" = حتى (نفي)، و"Wo kein grünt" ما تتقالش.\n✗ "solche" = مثل هذي، موش فاعل شكلي.`,
      rule: "es als Subjekt bei Naturvorgängen: es grünt, es blüht, es regnet", ex: "Im Frühling **es** grünt überall.", exTr: "في الربيع كلّ شي يخضرّ." },
    37: { ok: "EINFACH", type: "adjective_adverb", keyword: "einfach (schlicht)", bed: "ببساطة",
      text: `"da fühlen wir uns ___ wohl": ظرف تقوية: ببساطة / فعلًا.\n✓ "einfach" = ببساطة / فعلًا (تقوية).\n✗ "kein" = حتى (نفي)، وتقلب المعنى.\n✗ "höher" = أعلى (Komparativ)، و"uns höher wohl" ما تتقالش.`,
      rule: "einfach + Adjektiv / Verb = schlicht, wirklich (Verstärkung)", ex: "Hier ist es **einfach** schön.", exTr: "هنا ببساطة حلو." },
    38: { ok: "MITTLERWEILE", type: "adjective_adverb", keyword: "mittlerweile (inzwischen)", bed: "في هذه الأثناء",
      text: `"___ haben viele Städte entdeckt, dass …": ظرف زمني: بعد مدّة، توّا.\n✓ "mittlerweile" = بعد مدّة / توّا (inzwischen، الفعل في الثانية).\n✗ "dadurch" = بهذه الطريقة: ممكنة نحويًّا، بصح هنا ترتيب زمني (تطوّر مع الوقت).\n✗ "einfach" = ببساطة، موش ظرف زمني.`,
      rule: "mittlerweile = inzwischen (Zeitverlauf)  |  dadurch = auf diese Weise", ex: "**Mittlerweile** sind alle hier.", exTr: "توّا الكلّ هنا." },
    39: { ok: "SOLCHE", type: "pronoun", keyword: "solche + Plural", bed: "مثل هذي",
      text: `"dass ___ Städtchen auch schnell zu sozialen Treffpunkten werden": جمع: "solche" (Nominativ جمع).\n✓ "solche" = مثل هذي (جمع).\n✗ "kein" = حتى (نفي)، و"kein Städtchen … werden" ما يطابقش (مفرد مع جمع).\n✗ "klein" = صغير (بدون نهاية)، و"klein Städtchen" ما تتقالش (تحتاج "kleine").`,
      rule: "solche + Plural-Nomen = von dieser Art", ex: "**Solche** Projekte sind selten.", exTr: "مثل هذي المشاريع نادرة." },
    40: { ok: "DADURCH", type: "pronoun_adverb", keyword: "dadurch (= auf diese Weise)", bed: "بهذه الطريقة",
      text: `"…zu sozialen Treffpunkten werden ___": نتيجة: بسبب هذا.\n✓ "dadurch" = بهذه الطريقة / بسبب هذا (durch + das).\n✗ "mittlerweile" = توّا / بعد مدّة، موش نتيجة، ومستعملة في 38.\n✗ "einfach" = ببساطة، وما تعطيش معنى النتيجة.`,
      rule: "dadurch = infolgedessen / auf diese Weise", ex: "Er lernt viel, **dadurch** wird er besser.", exTr: "يتعلّم برشا، بهذا يولّي أحسن." },
  },

  // ───────────── [60] Es gibt immer weniger Deutsche (gap 39 held) ─────────────
  60: {
    31: { ok: "NACH", type: "preposition", keyword: "nach Angaben + Genitiv", bed: "حسب",
      text: `"___ Angaben des Statistischen Bundesamtes": تعبير ثابت: "nach Angaben" = حسب أقوال.\n✓ "nach" = حسب (nach Angaben + Genitiv).\n✗ "aufgrund" = بسبب: "Aufgrund Angaben" ما تتركّبش (تحتاج "von Angaben" أو Genitiv مباشر بمعنى سبب).\n✗ "im" = في (in + dem)، و"Im Angaben" ما تتقالش.`,
      rule: "nach Angaben / Auskunft / Meinung + Genitiv = laut", ex: "**Nach** Angaben der Polizei gab es keine Verletzten.", exTr: "حسب أقوال البوليس ما كانش فما مصابين." },
    32: { ok: "DRASTISCH", type: "adjective_adverb", keyword: "drastisch sinken", bed: "بشكل حادّ",
      text: `"wird die Bevölkerungszahl … ___ sinken": ظرف شدّة: بشكل حادّ.\n✓ "drastisch" = بشكل حادّ.\n✗ "bescheiden" = متواضع (صفة)، وما تصفش الانخفاض هنا.\n✗ "unschwer" = بسهولة، وما تعطيش معنى الشدّة.`,
      rule: "drastisch + Verb = sehr stark (drastisch sinken / steigen)", ex: "Die Zahlen sind **drastisch** gefallen.", exTr: "الأرقام نزلت بشكل حادّ." },
    33: { ok: "RECHNEN", type: "verb_prep", keyword: "rechnen mit + Dativ", bed: "يتوقّعو",
      text: `"Die Statistiker ___ damit, dass …": "rechnen mit" = يتوقّعو، والفاعل جمع.\n✓ "rechnen" = يتوقّعو (3. Person جمع، rechnen mit).\n✗ "steigen" = يرتفعو، وما يتركّبش مع "damit".\n✗ "erhöhen" = يرفعو (يحتاج مفعول)، وما يتركّبش مع "damit, dass".`,
      rule: "mit etwas rechnen = erwarten (damit rechnen, dass …)", ex: "Wir **rechnen** damit, dass es regnet.", exTr: "نتوقّعو إنّو تشتي." },
    34: { ok: "AUFGRUND", type: "preposition", keyword: "aufgrund + Genitiv", bed: "بسبب",
      text: `"werden ___ dieser Entwicklung vor großen Problemen stehen": سبب + Genitiv.\n✓ "aufgrund" = بسبب (+ Genitiv: dieser Entwicklung).\n✗ "nach" = بعد / حسب، و"nach dieser Entwicklung" تعني بعدها (زمن) موش سبب.\n✗ "für" = لـ، و"für dieser Entwicklung" ما تتطابقش (Akkusativ).`,
      rule: "aufgrund + Genitiv = wegen", ex: "**Aufgrund** des Regens fällt es aus.", exTr: "بسبب المطر يتلغى." },
    35: { ok: "STEIGEN", type: "verb", keyword: "steigen (auf + Zahl)", bed: "يرتفع",
      text: `"Das durchschnittliche Lebensalter … wird bis 2050 auf 84 … ___": Infinitiv مع "wird".\n✓ "steigen" = يرتفع (Futur I، auf + Zahl).\n✗ "erhöhen" = يرفع (متعدّي)، ويحتاج مفعول، وما يتركّبش مع الفاعل "Lebensalter" هكا.\n✗ "rechnen" = يحسب، وما يعطيش معنى الارتفاع.`,
      rule: "steigen (intransitiv) = höher werden  |  erhöhen (transitiv) = höher machen", ex: "Die Preise **steigen** auf 10 Euro.", exTr: "الأسعار ترتفع لـ 10 يورو." },
    36: { ok: "UNSCHWER", type: "adjective_adverb", keyword: "sich unschwer erahnen lassen", bed: "بسهولة",
      text: `"Die Auswirkungen … lassen sich ___ erahnen": ظرف: بسهولة.\n✓ "unschwer" = بسهولة (= leicht، غير صعيب).\n✗ "bescheiden" = متواضع، و"bescheiden erahnen" ما تتقالش.\n✗ "überheblich" = متكبّر، وما يتماشاش مع "erahnen".`,
      rule: "sich unschwer erahnen lassen = leicht vorstellbar sein", ex: "Das lässt sich **unschwer** erkennen.", exTr: "هذا يتعرف بسهولة." },
    37: { ok: "AUF", type: "verb_prep", keyword: "sich einstellen auf + Akk.", bed: "يستعدّو لـ",
      text: `"werden sich Politik und Geschäftswelt ___ diesen Personenkreis einstellen": "sich einstellen auf" = يتأقلم مع.\n✓ "auf" = على (sich einstellen auf + Akkusativ).\n✗ "an" = عند، و"sich an diesen Personenkreis einstellen" ما تتقالش.\n✗ "für" = لـ، و"sich für … einstellen" معنى آخر (يوظّف).`,
      rule: "sich auf etwas einstellen = sich anpassen / vorbereiten", ex: "Wir **stellen uns** auf Regen **ein**.", exTr: "نتهيّؤو للمطر." },
    38: { ok: "FÜR", type: "verb_prep", keyword: "sich interessieren für + Akk.", bed: "يهتمّ بـ",
      text: `"Politiker mehr ___ die alten Wähler interessieren werden": "sich interessieren für".\n✓ "für" = بـ (sich interessieren für + Akkusativ).\n✗ "an" = عند: "interessiert sein an" لكن مع "sich interessieren" الحرف "für".\n✗ "auf" = على، و"sich auf … interessieren" ما تتقالش.`,
      rule: "sich für + Akk. interessieren  |  interessiert sein an + Dat.", ex: "Er **interessiert sich** für Politik.", exTr: "هو يهتمّ بالسياسة." },
    40: { ok: "BEHEBEN", type: "verb", keyword: "Probleme beheben", bed: "يحلّو",
      text: `"Diese Probleme könne man nur ___": "Probleme beheben" = يحلّ مشاكل، Infinitiv بعد "könne".\n✓ "beheben" = يحلّ / يصلّح (Infinitiv).\n✗ "erhöhen" = يرفع، و"Probleme erhöhen" معناها يزيدهم.\n✗ "rechnen" = يحسب، وما يعطيش معنى الحلّ.`,
      rule: "ein Problem beheben = lösen / beseitigen", ex: "Man kann den Fehler **beheben**.", exTr: "الواحد ينجّم يصلّح الغلطة." },
  },

  // ───────────── [63] Sprachwandel (gaps 31 and 35 held) ─────────────
  63: {
    32: { ok: "DAZU", type: "pronoun_adverb", keyword: "sagen dazu", bed: "على هذا",
      text: `"Sprachhistoriker Rüdiger Müllerlein sagt ___": "dazu" = في هذا الموضوع (ثم الاقتباس).\n✓ "dazu" = على هذا (zu + das).\n✗ "von" = من، و"sagt von" ما تتقالش.\n✗ "an" = على / عند، و"sagt an" معناها يعلن (angesagt)، موش يعلّق.`,
      rule: "dazu sagen = sich zu der Sache äußern", ex: "Was sagst du **dazu**?", exTr: "شنوّة تقول على هذا؟" },
    33: { ok: "WEIß", type: "verb", keyword: "woher weiß man …", bed: "يعرف",
      text: `"Woher ___ man denn, was richtig und was falsch ist": "wissen" + Nebensatz (was …).\n✓ "weiß" = يعرف (wissen + was-Satz).\n✗ "kennt" = يعرف (شخص / مكان)، و"kennt, was richtig ist" ما تتقالش (تحتاج wissen).\n✗ "hält" = يمسك / يعتبر، و"Woher hält man" ما تتقالش.`,
      rule: "wissen + Nebensatz  |  kennen + Person / Ort / Sache", ex: "Woher **weiß** man das?", exTr: "منين يعرف الواحد هذا؟" },
    34: { ok: "VON", type: "fixed_expression", keyword: "von Zeit zu Zeit", bed: "من وقت لوقت",
      text: `تعبير ثابت: "von Zeit zu Zeit" = من وقت لوقت.\n✓ "von" = (von Zeit zu Zeit).\n✗ "zu" = إلى، و"zu Zeit zu Zeit" ما تتقالش.\n✗ "an" = عند، و"an Zeit zu Zeit" ما تتقالش.`,
      rule: "von Zeit zu Zeit = gelegentlich", ex: "Er besucht uns **von** Zeit zu Zeit.", exTr: "يزورنا من وقت لوقت." },
    36: { ok: "FORDERN", type: "verb", keyword: "fordern ≠ fördern", bed: "يطالبو",
      text: `"So ___ Kritiker beispielsweise ein verbindliches Regelwerk": "fordern" = يطالب، والفاعل جمع.\n✓ "fordern" = يطالبو (3. Person جمع).\n✗ "fördern" = يدعم / يشجّع: كلمة قريبة في الكتابة، بصح "ein Regelwerk fördern" معناها يشجّع (موش يطالب).\n✗ "kann" = ينجّم (مفرد)، موش مطابق للفاعل الجمع، ولا يعطي معنى مطالبة.`,
      rule: "fordern = verlangen  |  fördern = unterstützen / voranbringen", ex: "Sie **fordern** mehr Rechte.", exTr: "يطالبو بحقوق أكثر." },
    37: { ok: "ZU", type: "preposition", keyword: "Verbindung zu + Dativ", bed: "علاقة بـ",
      text: `"Die Verbindung, die man ___ der eigenen Kultur hat": "Verbindung zu" = علاقة بـ.\n✓ "zu" = بـ (Verbindung zu + Dativ).\n✗ "an" = عند، و"Verbindung an der Kultur" معناها اتصال مادّي.\n✗ "von" = من، و"Verbindung von der Kultur" ما تتقالش.`,
      rule: "Verbindung / Beziehung zu + Dativ", ex: "Er hat eine enge **Verbindung** zu seiner Heimat.", exTr: "عندو علاقة وثيقة بوطنو." },
    38: { ok: "HÄLT", type: "verb_prep", keyword: "halten von + Dativ", bed: "يعتبر (رأي)",
      text: `"Rüdiger Müllerlein ___ von diesem Anliegen wenig": "wenig halten von" = ما يعتبرش كثير.\n✓ "hält" = (halten von، 3. Person مفرد).\n✗ "kennt" = يعرف، و"kennt von diesem Anliegen wenig" معناها يعرف قليل، موش رأيو.\n✗ "kann" = ينجّم، و"kann von … wenig" ما تتقالش.`,
      rule: "wenig / viel von etwas halten = eine (gute) Meinung haben", ex: "Ich **halte** nicht viel **von** dieser Idee.", exTr: "ما نعتبرش كثير هذه الفكرة." },
    39: { ok: "ZUR", type: "fixed_expression", keyword: "zur Verfügung stehen", bed: "على الذمّة",
      text: `"damit uns die notwendige deutsche Sprache ___ Verfügung stehen": تعبير ثابت: "zur Verfügung stehen" (zu + der).\n✓ "zur" = zu + der (zur Verfügung).\n✗ "zu" = إلى، و"zu Verfügung" ما تتقالش (تحتاج "zur").\n✗ "an" = عند، و"an Verfügung" ما تتقالش.`,
      rule: "zur Verfügung stehen / stellen", ex: "Das Zimmer **steht** Ihnen **zur** Verfügung.", exTr: "الغرفة على ذمّتكم." },
    40: { ok: "LÄSST", type: "verb", keyword: "sich nicht aufhalten lassen", bed: "ينجّم (يتوقّف)",
      text: `"ein natürlicher Prozess, der sich durch ein Regelwerk nicht aufhalten ___": "sich nicht aufhalten lassen" = ما ينجّمش يتوقّف.\n✓ "lässt" = (sich lassen + Infinitiv، 3. Person مفرد).\n✗ "kann" = ينجّم: "kann sich nicht aufhalten" معناها ما ينجّمش يقعد (انعكاسي)، معنى آخر.\n✗ "hält" = يمسك، وما يعطيش معنى "ما يتوقّفش".`,
      rule: "etwas lässt sich (nicht) + Infinitiv = ist (nicht) möglich", ex: "Der Fortschritt **lässt** sich nicht aufhalten.", exTr: "التقدّم ما يتوقّفش." },
  },

  // ───────────── [64] Über den Zusammenhang zwischen Hobby und Charakter (gap 36 held) ─────────────
  64: {
    31: { ok: "SCHLIEßLICH", type: "adjective_adverb", keyword: "schließlich (= immerhin / ja)", bed: "في النهاية",
      text: `"___ wollen wir unsere Freizeit mit Aktivitäten verbringen, die uns glücklich machen": تعليل: في النهاية (ما نحبّو غير هذا).\n✓ "schließlich" = في النهاية / آخر الأمر (تعليل، الفعل في الثانية).\n✗ "trotzdem" = رغم ذلك، وما يتماشاش مع التعليل.\n✗ "bislang" = لحدّ الآن (زمن)، موش تعليل.`,
      rule: "schließlich = immerhin / letztlich (Begründung)", ex: "Er hilft, **schließlich** ist er ein Freund.", exTr: "يعاون، في النهاية هو صاحب." },
    32: { ok: "ENTSPRECHEND", type: "preposition", keyword: "entsprechend + Dativ / Genitiv", bed: "حسب",
      text: `"___ jener Eigenschaften verändern sich die Präferenzen für Hobbys": حرف جر: حسب.\n✓ "entsprechend" = حسب / وفقًا (entsprechend + Genitiv / Dativ).\n✗ "zugrunde" = (zugrunde liegen) أساس، موش "حسب".\n✗ "unabhängig" = بغضّ النظر (يحتاج "von")، وهو عكس المعنى (الهوايات تتغيّر بحسب الصفات).`,
      rule: "entsprechend = je nach / gemäß  |  unabhängig von = ohne Einfluss", ex: "**Entsprechend** deinem Alter wählst du das Programm.", exTr: "حسب عمرك تختار البرنامج." },
    33: { ok: "NAHE", type: "adjective_adverb", keyword: "es liegt nahe, dass …", bed: "منطقي",
      text: `"So liegt es zum Beispiel ___, dass offene Personen Neues entdecken": تعبير ثابت: "es liegt nahe, dass" = منطقي إنّو.\n✓ "nahe" = قريب (es liegt nahe، dass).\n✗ "zugrunde" = (liegt zugrunde) تحتاج "dem" ("liegt dem zugrunde")، موش "liegt es zugrunde, dass".\n✗ "bislang" = لحدّ الآن، موش جزء من التعبير.`,
      rule: "es liegt nahe, dass … = es ist naheliegend / logisch", ex: "Es **liegt nahe**, dass er das tut.", exTr: "منطقي إنّو يعملها." },
    34: { ok: "PASSEN", type: "verb", keyword: "passen zu + Dativ", bed: "تناسب",
      text: `"Zu gewissenhaften Menschen ___ am besten Hobbys": "zu jdm. passen" = تناسب، والفاعل جمع (Hobbys).\n✓ "passen" = تناسب (3. Person جمع).\n✗ "gehören" = تنتمي: "Zu … gehören Hobbys" ممكنة نحويًّا، بصح "passen" أنسب لمعنى المناسبة.\n✗ "ausleben" = يعيش / يطلق (فعل)، موش يناسب.`,
      rule: "zu jdm. passen = geeignet sein  |  zu etwas gehören = Teil von etwas sein", ex: "Dieses Hobby **passt** zu dir.", exTr: "هذه الهواية تناسبك." },
    35: { ok: "AUSLEBEN", type: "verb", keyword: "ausleben lassen", bed: "يعيشو (يطلقو)",
      text: `"Hobbys, die ihre strukturierte Seite ___ lassen": "etwas ausleben lassen" = يخلّي يعيش جانب من شخصيتو.\n✓ "ausleben" = يعيش / يطلق (Infinitiv بعد "lassen").\n✗ "ausprobieren" = يجرّب: "seine Seite ausprobieren lassen" ممكنة، بصح "ausleben" تعبّر على التعبير الحرّ للجانب.\n✗ "ausüben" = يمارس: "eine Seite ausüben" ما تتقالش (يتقال مع Hobby / Beruf).`,
      rule: "eine Seite ausleben = frei zeigen / leben  |  ein Hobby ausüben", ex: "Er **lebt** seine kreative Seite **aus**.", exTr: "هو يعيش جانبو الإبداعي." },
    37: { ok: "EHRENAMTLICH", type: "adjective_adverb", keyword: "ehrenamtlich engagiert", bed: "تطوّعيًّا",
      text: `"Verträgliche Menschen sind gern ___ engagiert": ظرف: تطوّعيًّا.\n✓ "ehrenamtlich" = تطوّعيًّا (بدون أجر).\n✗ "sozial" = اجتماعيًّا: "sozial engagiert" ممكنة ومشهورة، بصح "sozial" مستعملة في 36، والكلمة المقصودة هنا الشغل التطوّعي.\n✗ "alleine" = وحدو (ظرف)، وتناقض "verträgliche Menschen".`,
      rule: "ehrenamtlich engagiert = freiwillig / unbezahlt aktiv  |  sozial engagiert", ex: "Sie ist **ehrenamtlich** im Verein aktiv.", exTr: "هي تخدم تطوّعيًّا في الجمعية." },
    38: { ok: "AUSÜBEN", type: "verb", keyword: "ein Hobby ausüben", bed: "يمارس",
      text: `"beruhigende Hobbys, die sich ohne Gesellschaft ___ lassen": "ein Hobby ausüben" = يمارس هواية.\n✓ "ausüben" = يمارس (Infinitiv: sich ausüben lassen).\n✗ "ausleben" = يعيش / يطلق: ممكنة، بصح مع "Hobby" التعبير المعتاد "ausüben".\n✗ "ausprobieren" = يجرّب: ممكنة، بصح الجملة عن ممارسة موش تجربة.`,
      rule: "ein Hobby / einen Beruf ausüben = betreiben", ex: "Er **übt** ein Hobby **aus**.", exTr: "هو يمارس هواية." },
    39: { ok: "BISLANG", type: "adjective_adverb", keyword: "bislang (bis jetzt)", bed: "لحدّ الآن",
      text: `"ist sie ___ kaum wissenschaftlich untersucht": ظرف زمني: لحدّ الآن.\n✓ "bislang" = لحدّ الآن (bis jetzt).\n✗ "trotzdem" = رغم ذلك: ممكنة، بصح الجملة تتكلّم على الوضع الحالي للبحث موش تنازل.\n✗ "schließlich" = في النهاية، وما تعطيش معنى "لحدّ الآن".`,
      rule: "bislang = bis jetzt  |  trotzdem = dennoch", ex: "Das ist **bislang** unbekannt.", exTr: "هذا مجهول لحدّ الآن." },
    40: { ok: "UNABHÄNGIG", type: "adjective_adverb", keyword: "unabhängig von + Dativ", bed: "بغضّ النظر",
      text: `"Jeder Mensch sollte seinen Hobbys nachgehen – ___ von seinen Charaktermerkmalen": "unabhängig von" = بغضّ النظر عن.\n✓ "unabhängig" = مستقلّ / بغضّ النظر (unabhängig von).\n✗ "entsprechend" = حسب (عكس المعنى)، و"entsprechend von" ما تتقالش.\n✗ "zugrunde" = (zugrunde liegen) أساس، و"zugrunde von" ما تتقالش.`,
      rule: "unabhängig von + Dativ = ohne Rücksicht auf", ex: "**Unabhängig** vom Alter kann jeder lernen.", exTr: "بغضّ النظر عن العمر الكلّ ينجّم يتعلّم." },
  },
};
