// "ليش هذا النوع؟" — per gap: the syntactic evidence in the sentence that shows WHAT KIND of word the gap needs (positions 1–32).
// Positions 11, 18, 20 are copies of 10, 17, 19 (identical sentences; 18 differs at gap 36) — see the builder.
export default {
  1: { 31: `قبل الفراغ "nicht nur" وبعدو "auch": الفراغ يربط جزئين من نفس الفكرة ويكمّل الزوج.`,
    32: `بعد الفراغ جاي "vielen Jahren" (مدّة) والفعل "arbeitet" ما ينجّمش يتّصل بيها بدون حرف جرّ زمني.`,
    33: `بعد الفراغ جاي "familiärer … Probleme" (Genitiv) والاسم ما يدخلش في الجملة بدون حرف جرّ يعطي السبب.`,
    34: `بعد الفراغ جاي "dem kommenden Jahr" (Dativ زمني): الاسم يحتاج حرف جرّ يحدّد البداية.`,
    35: `الجملة تبدا بـ "___ Ende des Projekts": تعبير زمني ثابت = حرف جرّ مدمج مع الأداة ("an dem").`,
    36: `"Allen Mitarbeitern ist ___ wichtig, dass …": الفاعل الحقيقي هو جملة "dass"، فنحتاج ضمير شكلي ينوب عليه.`,
    37: `"wären" في آخر الجملة: جملة فرعية، والفراغ هو الرابط اللي يفتحها ويعطي السبب.`,
    38: `"sich kümmern" يتبعو "um"، وبعد الفراغ جاي "zu + Infinitiv": نحتاج Pronominaladverb (um + das).`,
    39: `بعد الفراغ "diese Weise" (Akkusativ): تعبير ثابت = حرف جرّ + "Weise".`,
    40: `بعد الفراغ "weitere Projekte … zu können" (Infinitiv): نحتاج رابط يعبّر على الغرض.` },
  2: { 31: `قبل الفراغ "nicht nur" وبعدو "auch": رابط يكمّل الزوج.`,
    32: `بعد الفراغ "vielen Jahren" (مدّة) والفعل "arbeitet": نحتاج حرف جرّ زمني.`,
    33: `بعد الفراغ Genitiv ("familiärer … Probleme"): نحتاج حرف جرّ يعطي السبب.`,
    34: `بعد الفراغ "dem kommenden Jahr" (Dativ زمني): نحتاج حرف جرّ يحدّد البداية.`,
    35: `بعد "Am Ende" جاي "Projekts" (محايد، بدون أداة): نحتاج أداة Genitiv تربط الاسمين.`,
    36: `بين "Schauspieler" و"Neuhausen" ينقص الاسم الأول: نحتاج اسم علم.`,
    37: `"Gelder" جمع، والجملة "da … waren" تفسّر سبب مستحيل: نحتاج أداة نفي بصيغة الجمع.`,
    38: `"werden Plakate ___, mit denen …": بنية Passiv، فنحتاج Partizip II.`,
    39: `بعد الفراغ "diese Weise" (Akkusativ): تعبير ثابت = حرف جرّ + "Weise".`,
    40: `قبل "ehrenamtliche Helfer gesucht" نحتاج ظرف يضيف طلب جديد، موش اسم ولا فعل.` },
  3: { 31: `بعد الفراغ "der vergangenen 12000 Jahre" (Genitiv زمني): نحتاج حرف جرّ زمني.`,
    32: `بداية جملة والفعل "wurde" بعدو مباشرة: نحتاج ظرف يربط بالنتيجة (da + durch).`,
    33: `"unumstritten, ___ das Verschwinden … zusammenhängt": الفعل في الآخر، فنحتاج رابط يفتح جملة محتوى.`,
    34: `بعد الفعل "angestiegen" جاي رقم ("zwei bis vier Grad"): نحتاج حرف جرّ للمقدار.`,
    35: `"weniger ___": بعد "weniger" وقبل الفاصلة نحتاج اسم جمع يكون مفعول "bekamen".`,
    36: `"Der Grund ___ ist, dass": "Grund" يتبعو "für" وما فماش اسم بعد الفراغ: نحتاج Pronominaladverb.`,
    37: `"sie bringen" فعل في المرتبة الثانية: الفراغ رابط جملة رئيسية يعطي سبب.`,
    38: `"die menschlichen ___ in die Naturlandschaften": بعد صفة جمع نحتاج اسم جمع يتبعو "in".`,
    39: `قبل "überall … heimisch" نحتاج ظرف زمني يعطي معنى "لسّا".`,
    40: `"___ es mit dem Braunbären": الفاعل "es" بعد الفراغ: نحتاج فعل مصرّف في المرتبة الثانية.` },
  4: { 31: `بعد الفراغ "sie hat … entschieden" (فاعل + فعل): نحتاج رابط Position 0 يعطي سبب.`,
    32: `"Sie ___ in den Streifendienst gehen": بعد الفاعل المفرد نحتاج فعل مساعد قبل Infinitiv "gehen".`,
    33: `"fehlt" في آخر الجملة: جملة فرعية، والفراغ هو الرابط اللي يعطي السبب.`,
    34: `قبل الفراغ "eine": نحتاج اسم مؤنّث يكمّل "eine ___ geben".`,
    35: `"erklärt, ___ … ausbildet": الفعل في الآخر: نحتاج رابط سؤال غير مباشر.`,
    36: `"bereit, Verantwortung zu ___": بعد "zu" نحتاج Infinitiv.`,
    37: `"Zudem ___ sie die Jüngeren unterstützen": فاعل جمع و Infinitiv في الآخر: نحتاج فعل مساعد مصرّف.`,
    38: `"zur ___ stehen": التعبير الثابت يطلب اسم محدّد بعد "zur".`,
    39: `بعد الفراغ "haben ältere Azubis" (فعل ثم فاعل): نحتاج ظرف ربط يقلب الترتيب.`,
    40: `قبل الفراغ "nicht nach dem Alter festgelegt" (نفي): نحتاج رابط يصحّح.` },
  5: { 31: `"muss … mit rechtlichen Folgen ___": مع "mit" نحتاج فعل يتركّب بيها ("mit etwas rechnen").`,
    32: `"ist … auf der Piste ___": بعد "ist" نحتاج صفة.`,
    33: `"sieht … Freiheitsstrafen … ___" والفعل "sieht": فعل منفصل يترك جزءو في آخر الجملة.`,
    34: `"Jeder Wintersportler ___ diese Regeln kennen": فاعل مفرد + Infinitiv "kennen": نحتاج فعل مساعد.`,
    35: `"stets ___ verhalten, dass": نحتاج ظرف يعلن بنية "so … dass".`,
    36: `"Geschwindigkeit … seinem Können … ___": بعد "muss" نحتاج Infinitiv في آخر الجملة.`,
    37: `"rechts oder links, ___ immer in einem Abstand": نحتاج ظرف يقيّد الجملة اللي قبل.`,
    38: `"den ___ einer Abfahrtsstrecke": "den" مذكّر Akkusativ ثم Genitiv: نحتاج اسم مذكّر.`,
    39: `"eine solche ___": "eine" مؤنّث: نحتاج اسم مؤنّث.`,
    40: `"seine Personalien ___": بعد المفعول به وقبل نهاية الجملة نحتاج Infinitiv.` },
  6: { 31: `بعد الفراغ "Herbst 2002" (نقطة زمنية): نحتاج حرف جرّ زمني.`,
    32: `"___ immer bereiten sich …": تعبير ثابت بكلمة مقارنة قبل "immer".`,
    33: `"fragst dich, ___ du teilnehmen solltest": نحتاج رابط سؤال غير مباشر.`,
    34: `بعد الفراغ "bietet dir" (فعل مباشرة): نحتاج ظرف إضافة.`,
    35: `"teilnehmen" فعل يتبعو حرف جرّ ثابت قبل "Regionalwettbewerben".`,
    36: `"___ Preise kann man … gewinnen": نحتاج حرف يعطي الصفة ("كـ").`,
    37: `بعد الفراغ جاي "Jugend diskutiert" (اسم): نحتاج حرف جرّ يربطو بـ "lernen".`,
    38: `بعد الفراغ جملة بفاعل ("du lernst"): نحتاج رابط سبب.`,
    39: `"zeigen dir …, ___ du … gesehen hast": جملة فرعية مفعولها ناقص: نحتاج ضمير موصول لغير محدّد.`,
    40: `الفراغ يفتح جملة فاعلها شخص عام ("… gelernt hat, kann …"): نحتاج ضمير موصول للأشخاص.` },
  7: { 31: `بعد الفراغ "Herbst 2002": نحتاج حرف جرّ زمني.`,
    32: `"___ immer bereiten sich …": تعبير ثابت بكلمة مقارنة.`,
    33: `"fragst dich, ___ …": رابط سؤال غير مباشر.`,
    34: `بعد الفراغ "bietet dir" (فعل مباشرة): ظرف إضافة.`,
    35: `"teilnehmen" يتبعو حرف جرّ ثابت قبل "Regionalwettbewerben".`,
    36: `"treten ___ Bundesfinale an": محايد + حرف مكان = حرف جرّ مدمج مع الأداة.`,
    37: `بعد الفراغ جاي "Jugend diskutiert": نحتاج حرف جرّ يربطو بـ "lernen".`,
    38: `"auf sich aufmerksam ___": نحتاج فعل مصرّف مع الفاعل "man".`,
    39: `"da du ___ Argumente finden": قبل اسم جمع بدون أداة نحتاج صفة.`,
    40: `"eine ___, Jugendliche … kennenzulernen": بعد "eine" نحتاج اسم مؤنّث.` },
  8: { 31: `بعد الفراغ "Herbst 2002": حرف جرّ زمني.`,
    32: `"die an dem Wettbewerb ___ möchten": بعد "möchten" نحتاج Infinitiv.`,
    33: `"fragst dich, ___ …": رابط سؤال غير مباشر.`,
    34: `بعد الفراغ "bietet dir": ظرف إضافة.`,
    35: `"treten ___ Bundesfinale an": حرف جرّ مدمج مع الأداة.`,
    36: `بعد الفراغ "Jugend diskutiert" (اسم): حرف جرّ يربطو بـ "lernen".`,
    37: `"auf sich aufmerksam ___": فعل مصرّف مع "man".`,
    38: `"da du ___ Argumente finden": صفة قبل اسم جمع.`,
    39: `"die Argumente anderer genau ___ kannst": قبل "kannst" في الآخر نحتاج Infinitiv.`,
    40: `"auch eine ___, Jugendliche … kennenzulernen": اسم مؤنّث بعد "eine".` },
  9: { 31: `"mit einer ___ von Fotos": بعد "einer" نحتاج اسم مؤنّث يعبّر على كمّية.`,
    32: `"für Laien ___ einfach": قبل الصفة "einfach" نحتاج ظرف درجة.`,
    33: `"harmlos, ___ die Möglichkeiten … lassen sich": فاعل بعد الفراغ: رابط تعارض Position 0.`,
    34: `"In diesem Zusammenhang ___ sich die Frage": نحتاج فعل مصرّف في المرتبة الثانية.`,
    35: `"___ Fragen sind … nachgegangen": "nachgehen" + Dativ جمع: نحتاج أداة Dativ جمع.`,
    36: `"Die ___ Teilnehmer": بعد "Die" وقبل اسم جمع نحتاج صفة تفضيل.`,
    37: `"tatsächlich ___ bestimmen": قبل الفعل نحتاج ظرف طريقة.`,
    38: `"andere ___ Abweichungen": قبل اسم جمع نحتاج صفة بنهاية -e.`,
    39: `"zwischen echten und gefälschten Details ___": بعد "Können Menschen … nicht" نحتاج Infinitiv في الآخر.`,
    40: `"Die Ergebnisse dokumentierten ___.": نحتاج ظرف يعطي خلاصة.` },
  10: { 31: `"___ gilt der Hund …, … jedoch": الجملة تفتح اعتراف وتنتظر "jedoch": نحتاج رابط يبدا الزوج.`,
    32: `"durchgeführt ___": بعد Partizip II والفاعل جمع نحتاج فعل مساعد للـ Passiv.`,
    33: `"lesen … an den Augen ___": الفعل المنفصل يترك جزءو في آخر الجملة.`,
    34: `"reagieren ___ die Stimme": "reagieren" يتبعو حرف جرّ ثابت.`,
    35: `"der Blickkontakt ___ … ein Instrument": الجملة تنقل قول الباحثين: نحتاج Konjunktiv I.`,
    36: `"___ der Behälter … leer, suchten …": شرط بلا "wenn": الفعل في أول الجملة.`,
    37: `"er leitet sie ___ Hindernisse herum": "herum" في الآخر: نحتاج حرف جرّ يتركّب معاها.`,
    38: `"geht man ___ aus, dass": "ausgehen von" + dass-Satz: نحتاج Pronominaladverb.`,
    39: `"stolz ___ sein, … zu haben": "stolz sein auf" + zu-Infinitiv: Pronominaladverb.`,
    40: `"nicht nur einen anhänglichen, ___ auch …": نحتاج رابط يكمّل الزوج.` },
  12: { 31: `"sich ___ geärgert, dass": "sich ärgern über" + dass-Satz: نحتاج Pronominaladverb.`,
    32: `"fast ___ noch in den falschen Größen": نحتاج ظرف حصر يتركّب مع "noch".`,
    33: `"brachte nun ___ Licht": تعبير ثابت: حرف جرّ مدمج مع الأداة.`,
    34: `"___ den Kundinnen noch den Kunden": "noch" تدلّ على زوج نفي.`,
    35: `"suchen ___": الفعل المساعد يمشي للآخر في الجملة الفرعية بعد Infinitiv.`,
    36: `"___ der Handel … interessiert ist": الفعل في الآخر: رابط سبب.`,
    37: `"ein neues Projekt, ___ Aufschluss … geben soll": الجملة الفرعية فاعلها هو المشروع: ضمير موصول محايد.`,
    38: `"Diese … Bilder ___ es ermöglichen": فاعل جمع + Infinitiv: فعل مساعد.`,
    39: `"Als Kundinnen … ___ wir uns … freuen": بعد "wir" وقبل Infinitiv نحتاج فعل مساعد.`,
    40: `"freuen, ___ sich … entscheiden": الفعل في الآخر: رابط محتوى.` },
  13: { 31: `"sich ___ aufgeregt, dass": "sich aufregen über" + dass-Satz: Pronominaladverb.`,
    32: `"fast ___ noch": ظرف حصر.`,
    33: `"Hohenstein ___ nun zu der folgenden Erkenntnis": فاعل مفرد + "zu …": فعل مصرّف.`,
    34: `"___ den Kundinnen noch den Kunden": زوج نفي.`,
    35: `"Die Länge der Arme ___ zugenommen": الجملة منقولة: نحتاج فعل مساعد Konjunktiv I.`,
    36: `"___ man … interessiert ist": الفعل في الآخر: رابط سبب.`,
    37: `"ein neues Verfahren, ___ Männer und Frauen … vermessen soll": فاعل مفرد: ضمير موصول.`,
    38: `"Diese … Bilder ___ es ermöglichen": فعل مساعد جمع.`,
    39: `"freuen, ___ sich … entscheiden": رابط محتوى.`,
    40: `"überall ___ groß": نحتاج صفة / ظرف قبل "groß".` },
  14: { 31: `"In ___ einem anderen Land": قبل "einem" نحتاج ظرف يعطي معنى نفي.`,
    32: `"umzusteigen" يتبعو حرف جرّ ثابت قبل "ein anderes Verkehrsmittel".`,
    33: `"an den … Fahrzeugen ___": "an" قدّام تستنّى جزء ثاني: فعل منفصل.`,
    34: `"Wer Fahrrad fährt ___ zu sitzen": نحتاج حرف يفتح Infinitivgruppe بـ "zu".`,
    35: `"___ geschlossener Räume": بعد الفراغ Genitiv جمع: حرف جرّ.`,
    36: `"aufhalten ___": الفعل المساعد يمشي للآخر في الجملة الفرعية.`,
    37: `"Angebot ___ Zubehör": "Angebot" يتبعو حرف جرّ ثابت.`,
    38: `"machen ___": الفعل المساعد الجمع في الآخر.`,
    39: `"Nur wenn es regnet, ___ sind die Autoschlangen …": جواب wenn-Satz والفعل بعدو.`,
    40: `"___ einen praktischen Wetterschutz … haben die Geschäfte": رابط تعليل Position 0.` },
  15: { 31: `"In ___ einem anderen Land": ظرف يعطي معنى نفي.`,
    32: `"umzusteigen" + حرف جرّ ثابت.`,
    33: `"auf den ___ gut ausgebauten Fahrradwegen": قبل صفة نحتاج ظرف.`,
    34: `"___ zu sitzen": حرف يفتح Infinitivgruppe.`,
    35: `"___ geschlossener Räume": حرف جرّ + Genitiv.`,
    36: `"aufhalten ___": فعل مساعد في الآخر.`,
    37: `"Angebot ___ Zubehör": حرف جرّ ثابت.`,
    38: `"machen ___": فعل مساعد جمع.`,
    39: `"…, ___ sind die Autoschlangen": ظرف جواب + فعل.`,
    40: `"___ einen praktischen Wetterschutz … haben": رابط تعليل.` },
  16: { 31: `"seltener krank ___": بعد صيغة المقارنة نحتاج أداة مقارنة.`,
    32: `"in der ___ Woche": بعد "der" (Dativ مؤنّث) قبل اسم نحتاج صفة بنهاية -en.`,
    33: `"Es wurden ___ keine Erklärungen … , aber": نحتاج رابط يبدا اعتراف قبل "aber".`,
    34: `"___ die täglichen Spaziergänge": بعد الفراغ Akkusativ: حرف جرّ يعطي الوسيلة.`,
    35: `"haben demnach ___ Wirkung": "Wirkung" مؤنّث Akk.: نحتاج ضمير / أداة مؤنّث.`,
    36: `"Für die Studie ___ … beobachtet": Partizip II في الآخر والفاعل جمع: فعل مساعد.`,
    37: `"ein um 30 % ___ Risiko": بين "ein" و"Risiko" نحتاج صفة مقارنة بنهاية.`,
    38: `"Ohrenentzündungen ___ auftraten": ظرف كمّية قبل الفعل.`,
    39: `"___ besser sei": قبل الصفة المقارنة نحتاج ظرف درجة.`,
    40: `"das genaue ___ der Ergebnisse": بعد "das genaue" نحتاج اسم محايد.` },
  17: { 31: `"zahlt der Kunde drauf, ___ … Geld zu sparen": نحتاج حرف يفتح zu-Infinitiv ببديل.`,
    32: `"nicht ___ Gelegenheit": "Gelegenheit" مؤنّث مفرد: نحتاج ضمير / أداة مؤنّث.`,
    33: `"Argument ___ illegale Arbeiter": حرف جرّ + Akkusativ.`,
    34: `"Abgesehen ___, dass": "abgesehen von" + dass-Satz: Pronominaladverb.`,
    35: `"Das Finanzamt ___ … Rechnung … sehen": فاعل مفرد + Infinitiv: فعل مساعد.`,
    36: `"Bauten ___ eher die Ausnahme": فاعل جمع + مفعول: فعل مصرّف.`,
    37: `"leer ___": بعد "dürften" نحتاج Infinitiv من تعبير فعلي.`,
    38: `"für ___ Fälle": "Fälle" جمع: ضمير / أداة جمع.`,
    39: `"dann ___ es … mit": فعل منفصل (mit في الآخر).`,
    40: `"braucht der Auftraggeber ___ einen Anwalt": نحتاج ظرف تكرار.` },
  19: { 31: `"fragen sich, ___ … sind": الفعل في الآخر: رابط سؤال غير مباشر.`,
    32: `"___ sind Bio-Produkte teurer": بعد الفراغ فعل مباشرة: ظرف إضافة.`,
    33: `"Sie ___ weniger Nitrat": فاعل جمع + مفعول: فعل مصرّف.`,
    34: `"steht ___ ihrem Einkaufsverhalten": بعد الفراغ Dativ: حرف جرّ.`,
    35: `"Sie ___ unsere Umwelt": فاعل مفرد + مفعول: فعل مصرّف.`,
    36: `"kommen ___ ökologischer Landwirtschaft": "kommen" يتبعو حرف المصدر.`,
    37: `"beispielsweise ___ Wochenmärkten": حرف جرّ مكان.`,
    38: `"dürfen … ___ werden": Passiv مع modal: Partizip II.`,
    39: `"dürfen ___ nur Bio-Lebensmittel": ظرف تأكيد.`,
    40: `"garantieren, ___ die Produkte … sind": الفعل في الآخر: رابط محتوى.` },
  21: { 31: `"konnte … ___, dass": بعد "konnte" نحتاج Infinitiv.`,
    32: `"___ echter Teamarbeit fähig": "fähig" يتبعو حرف جرّ.`,
    33: `"___ bekam einer der beiden Affen": بداية جملة والفعل بعدو: ظرف.`,
    34: `"eines ___": بعد "eines" نحتاج Pronominaladverb بمعنى "منهم".`,
    35: `"___ es sogar das richtige Werkzeug gewesen": كلام منقول: Konjunktiv I مع "gewesen".`,
    36: `"ob diese Eigenschaft ___ beim Menschen vorhanden ist": ظرف حصر.`,
    37: `"sie fressen ___": الفعل المساعد في الآخر.`,
    38: `"Diese Studie ___ erste Hinweise": فاعل مفرد: فعل مصرّف.`,
    39: `"Acht ___ können": قبل "können" Infinitiv.`,
    40: `"Genau ___ den Menschen": أداة مقارنة.` },
  22: { 31: `"Drei von vier Deutschen ___ … zu": فاعل جمع + "zu" منفصلة: فعل مصرّف.`,
    32: `"___ einer Umfrage zufolge 75 Prozent": فعل قبل الفاعل (قلب).`,
    33: `"der Wunsch ___ gewissen Höflichkeitsformen": "Wunsch" يتبعو حرف جرّ.`,
    34: `"für ein höfliches ___": بعد "ein höfliches" نحتاج اسم.`,
    35: `"sucht man sie oft ___": ظرف / صفة تصف نتيجة البحث.`,
    36: `"___ die Hälfte": قبل "die Hälfte" نحتاج ظرف يعبّر على تقدير.`,
    37: `"empfinden ___": فاعل جمع: فعل مساعد.`,
    38: `"___ sich am ungefragten Duzen": "sich … an": فعل انعكاسي.`,
    39: `"den Vortritt ___": Infinitiv.`,
    40: `"was ___ gehört": "gehören" هنا انعكاسي: ضمير.` },
  23: { 31: `"Die Arme ___ nicht auf den Tisch": فاعل جمع: فعل مصرّف.`,
    32: `"Die Schuhe ___ in jedem Fall an": فعل منفصل (an في الآخر).`,
    33: `"steht so ___ vor einem Problem": فاعل الجملة: ضمير.`,
    34: `"Die Bedienung ___ "Fräulein" zu rufen": حرف جرّ قبل التسمية.`,
    35: `"…ist ___ noch möglich": ظرف تعارض داخل الجملة.`,
    36: `"mit einem kleinen ___ mit der Hand": اسم بعد صفة.`,
    37: `"Ist man mit dem Essen ___": صفة بعد "ist … mit".`,
    38: `"ist ___ gefragt": اسم مجرّد بدون أداة.`,
    39: `"macht er dies dem Kellner ___": فعل منفصل.`,
    40: `"…bezahlen, ___ durchaus üblich ist": جملة موصولة تعلّق على الجملة كاملة.` },
  24: { 31: `"Die Arme ___ nicht auf den Tisch": فاعل جمع: فعل.`,
    32: `"Die Schuhe ___ in jedem Fall an": فعل منفصل.`,
    33: `"bereitet so ___ Probleme": بعد "bereitet" نحتاج Dativ: ضمير.`,
    34: `"Die Bedienung ___ der Anrede": حرف جرّ.`,
    35: `"ist ___ zwar korrekt": ظرف تعارض.`,
    36: `"mit einem kleinen ___": اسم.`,
    37: `"Wenn man mit dem Essen ___ ist": صفة.`,
    38: `"ist ___ wichtig": اسم مجرّد.`,
    39: `"Macht er dies dem Kellner ___": فعل منفصل.`,
    40: `"getrennt bezahlen, ___ durchaus üblich ist": ضمير موصول لجملة.` },
  25: { 31: `"Online-Sprachkurse und ___ mit Smartphones": ظرف يضيف زيادة غير متوقّعة.`,
    32: `"Tandem-Partnerschaft ___ einem Muttersprachler": حرف جرّ + Dativ.`,
    33: `"nicht nur lesen, ___ gleichzeitig auch hören": رابط الزوج.`,
    34: `"nachsprechen, ___ dass ein ganzer Kurs zuhört": حرف يفتح "dass-Satz" بمعنى نفي.`,
    35: `"…wiederholen, ___ sie … zu lernen": حرف يفتح zu-Infinitiv ببديل.`,
    36: `"sind ___ gut": ظرف درجة قبل صفة.`,
    37: `"zwar Spaß, ___ Satzbau … werden": رابط يكمّل "zwar".`,
    38: `"Dafür ___ man besser … gehen": فاعل "man" + Infinitiv: فعل مساعد.`,
    39: `"Weg, ___ … zu finden": حرف يفتح zu-Infinitiv للغرض.`,
    40: `"…eingeben, ___ werden alle Treffer angezeigt": ظرف + فعل في الثانية.` },
  26: { 31: `"___ des Inhalts": بعد الفراغ Genitiv: حرف جرّ.`,
    32: `"Kategorien ___ Single-Männern": "Kategorien" يتبعو حرف جرّ.`,
    33: `"den Kreativen, ___ den Cocktail- und …": قائمة: رابط قبل آخر عنصر.`,
    34: `"___ denen er … zusammenstellen": بعد الفراغ ضمير موصول Dativ: حرف جرّ.`,
    35: `"Der Nachteil liegt ___ der Hand": تعبير ثابت: حرف جرّ + "Hand".`,
    36: `"zu ___, zwei Tüten zu öffnen": بعد "zu" نحتاج صفة.`,
    37: `"___ kaufen diese Männer": فعل بعد الفراغ: ظرف ربط.`,
    38: `"sehen das wohl ___ skeptisch": قبل صفة نحتاج ظرف درجة.`,
    39: `"___ welcher Kategorie … gehört": "gehören" يتبعو حرف جرّ.`,
    40: `"andere ___ eher keine Lust": ظرف تخمين.` },
  27: { 31: `"Einer Studie ___": بعد اسم Dativ نحتاج حرف جرّ بعدو.`,
    32: `"den Kreativen, ___ den Cocktail-": رابط آخر القائمة.`,
    33: `"Cocktail- ___ den Gourmet-Typen": رابط الزوج.`,
    34: `"aus ___ er … zusammenstellen": ضمير موصول Dativ جمع بعد "aus".`,
    35: `"für ___ Frau": بعد "für" نحتاج ضمير مؤنّث.`,
    36: `"zu ___, zwei Tüten zu öffnen": صفة بعد "zu".`,
    37: `"___ kaufen diese Männer": ظرف ربط + فعل.`,
    38: `"Aber ___ sie … erobern können?": رابط سؤال.`,
    39: `"___ welcher Kategorie … gehört": حرف جرّ.`,
    40: `"Einige haben ___ wenig Zeit": ظرف تخمين.` },
  28: { 31: `"Einer Studie ___": حرف جرّ بعد الاسم.`,
    32: `"Kategorien ___ Single-Männern": حرف جرّ.`,
    33: `"den Kreativen, ___ den Cocktail- und …": رابط آخر القائمة.`,
    34: `"aus ___ er … zusammenstellen": ضمير موصول.`,
    35: `"für ___ Frau": ضمير مؤنّث.`,
    36: `"zu ___, zwei Tüten zu öffnen": صفة.`,
    37: `"___ kaufen diese Männer": ظرف ربط.`,
    38: `"Aber ___ sie … erobern können?": رابط سؤال.`,
    39: `"___ welcher Kategorie … gehört": حرف جرّ.`,
    40: `"Einige haben ___ wenig Zeit": ظرف تخمين.` },
  29: { 31: `"___ immer mehr Männer … greifen": فاعل ثم فعل بعد الفراغ: رابط Position 0 يعطي سبب.`,
    32: `"Ein Grund ___ diese Entwicklung": "Grund" يتبعو حرف جرّ.`,
    33: `"Unterschied besteht ___ den Ansprüchen … und denen": طرفين: حرف جرّ.`,
    34: `"Nicht ___ Topf": قبل اسم مذكّر: ضمير / أداة.`,
    35: `"Voraussetzung ___, dass": "Voraussetzung für" + dass-Satz: Pronominaladverb.`,
    36: `"hängt es … ___ ab, was": "abhängen von" + جملة: Pronominaladverb.`,
    37: `"Helfen die Bücher nicht ___": فعل منفصل (weiterhelfen).`,
    38: `"Das führt ___, dass": "führen zu" + dass-Satz: Pronominaladverb.`,
    39: `"ist aber, ___ es … ist": رابط محتوى.`,
    40: `"Das Interessante ___ ist, dass": Pronominaladverb بمعنى "في هذا".` },
  30: { 31: `"greifen … selbst ___ Kochtopf": حرف جرّ مدمج مع الأداة.`,
    32: `"Ein Grund ___ diese Entwicklung": حرف جرّ.`,
    33: `"Unterschied besteht ___ den Ansprüchen … und": حرف جرّ.`,
    34: `"zwischen den Ansprüchen … und ___ eines Hobbykochs": ضمير يعوّض الاسم الجمع.`,
    35: `"Alles andere gilt ___ stillos": "gelten als": حرف.`,
    36: `"hängt es nur noch ___ ab": Pronominaladverb.`,
    37: `"zum Dönerstand ___ die Ecke": حرف جرّ + Akkusativ.`,
    38: `"Das führt ___, dass": Pronominaladverb.`,
    39: `"ist aber, ___ es … ist": رابط محتوى.`,
    40: `"___ gut ein Festmahl zubereiten können wie sie": أداة مقارنة قبل "gut … wie".` },
  31: { 31: `"aber ___ ihre Intelligenz betrifft": جملة فرعية بفعل في الآخر: تعبير ثابت.`,
    32: `"Doch ___ haben wissenschaftliche Experimente": ظرف زمني + فعل في الثانية.`,
    33: `"Experimente ___ der Universität Wien": حرف جرّ مكان.`,
    34: `"das richtige ___ verschiedenen Bildern auswählen": حرف جرّ.`,
    35: `"und ___ entweder einen Menschen … erkennen": ضمير ظرفي يرجع للصور.`,
    36: `"ausgestattet, ___ der Hund … tippen konnte": الفعل في الآخر: رابط نتيجة.`,
    37: `"Der Hund hing ___ mit … Begeisterung …, sondern": بداية الزوج.`,
    38: `"von ___ eins Futter enthielt": حرف + ضمير موصول جمع.`,
    39: `"schließen die Forscher, ___ … interpretiert werden können": رابط محتوى.`,
    40: `"brachten ___ vergleichbaren Resultate": نفي جمع Akkusativ.` },
  32: { 31: `"Verglichen ___ der Bevölkerungszahl": حرف جرّ ثابت.`,
    32: `"drei Jahre ___ dem Kind zu Hause": حرف جرّ + Dativ.`,
    33: `"…zu bleiben, ___ hat den Vorteil": فاعل الجملة الجديدة قبل "hat": ضمير.`,
    34: `"Hauptgründe ___ zu sein, warum": Pronominaladverb.`,
    35: `"nicht still am Tisch, ___ stören …": رابط يصحّح.`,
    36: `"___ diese selbst … telefonieren": الفعل في الآخر: رابط تنازل.`,
    37: `"…anstrengen, ___ die Kinder … stören": الفعل في الآخر: رابط سبب.`,
    38: `"so angeordnet, ___ mit einem Kinderwagen …": رابط نتيجة.`,
    39: `"Anspruch ___ einen Platz": "Anspruch" يتبعو حرف جرّ.`,
    40: `"spricht man gerne ___ "Problemen"": "sprechen" يتبعو حرف جرّ.` },
};
