// SB Teil 2 restyle — batch 07: [32] + [33] + [34] Deutschland – ein Paradies für Kinder?, [35] TV-Bilder, [36] Städte vor dem Infarkt
// (note for [33]/[34] gap 32: "mit dem Kind zu Hause bleiben" is equally good German and MIT is an unused distractor there; gaps 34/35 of [33] have 3 contrast words → hedged)
export default {
  // ───────────── [32] Deutschland – ein Paradies für Kinder? ( Original ) ─────────────
  32: {
    31: { ok: "MIT", type: "preposition", keyword: "verglichen mit + Dativ", bed: "مقارنة بـ",
      text: `"Verglichen ___ der Bevölkerungszahl": تعبير ثابت للمقارنة.\n✓ "mit" = بـ (verglichen mit + Dativ).\n✗ "von" = من، و"verglichen von" ما تتقالش.\n✗ "auf" = على، وما تعطيش معنى المقارنة.`,
      rule: "verglichen mit + Dativ = im Vergleich zu", ex: "**Verglichen mit** früher ist es ruhig.", exTr: "مقارنة بقبل، هادئ." },
    32: { ok: "BEI", type: "preposition", keyword: "bei dem Kind bleiben", bed: "عند (الصغير)",
      text: `"drei Jahre ___ dem Kind zu Hause zu bleiben": الأب / الأمّ يبقى عند الصغير.\n✓ "bei" = عند (bei dem Kind = برعايتو).\n✗ "mit" = مع: ممكنة ("mit dem Kind zu Hause bleiben")، بصح "mit" لازم تتحجز للفراغ 31 ("verglichen mit")، وكلّ كلمة تتستعمل مرّة وحدة.\n✗ "von" = من، و"von dem Kind zu Hause bleiben" ما تتقالش.`,
      rule: "bei + Dativ = in der Obhut / Nähe von jdm. (beim Kind bleiben)", ex: "Sie bleibt **bei** den Kindern.", exTr: "هي تبقى عند الصغار." },
    33: { ok: "DAS", type: "pronoun", keyword: "das = Demonstrativpronomen (Rückbezug)", bed: "هذا",
      text: `"…zu Hause zu bleiben, ___ hat den Vorteil, dass …": الضمير يرجع على الجملة اللي قبل، والفعل "hat" بعدو.\n✓ "das" = هذا (Demonstrativpronomen، فاعل الجملة).\n✗ "dass" = إنّو (رابط + فعل في الآخر)، وهنا "hat" في الثانية.\n✗ "dabei" = في هذا (ظرف)، موش فاعل للفعل "hat".`,
      rule: "das (Subjekt) + Verb: Das hat den Vorteil …  ≠  dass-Satz", ex: "Er arbeitet nachts. **Das** ist anstrengend.", exTr: "هو يخدم في الليل. هذا متعب." },
    34: { ok: "DAFÜR", type: "pronoun_adverb", keyword: "Grund dafür, warum …", bed: "لهذا",
      text: `"Dies scheinen die Hauptgründe ___ zu sein, warum …": "Grund für" ← "dafür" + سؤال "warum".\n✓ "dafür" = لهذا (für + das).\n✗ "davon" = من هذا (von + das)، و"Gründe davon" ما تتقالش.\n✗ "dabei" = في هذا، و"Gründe dabei" ما تتقالش.`,
      rule: "Grund für + Akk. → der Grund dafür, warum / dass …", ex: "Das ist der Grund **dafür**, warum er fehlt.", exTr: "هذا هو السبب علاش هو غايب." },
    35: { ok: "SONDERN", type: "conjunction", keyword: "nicht …, sondern …", bed: "بل",
      text: `"Sie sitzen eben nicht still am Tisch, ___ stören mit ihrem Lachen": بعد النفي نصحّحو بـ "sondern".\n✓ "sondern" = بل (تصحيح بعد نفي).\n✗ "doch" = لكن: ممكنة في الكلام، بصح بعد "nicht" المعتاد "sondern".\n✗ "jedoch" = غير إنّو / لكن، تعارض عادي موش تصحيح.`,
      rule: "nicht A, sondern B = Korrektur", ex: "Das ist nicht teuer, **sondern** billig.", exTr: "هذا موش غالي، بل رخيص." },
    36: { ok: "OBWOHL", type: "conjunction", keyword: "obwohl + Nebensatz", bed: "رغم إنّو",
      text: `"___ diese selbst häufig lautstark telefonieren, stört das niemanden": تنازل، والفعل "telefonieren" في الآخر.\n✓ "obwohl" = رغم إنّو (+ فعل في الآخر).\n✗ "weil" = خاطر (سبب)، والمنطق هنا عكس التوقّع.\n✗ "dennoch" = رغم ذلك (ظرف، الفعل في الثانية)، موش رابط يفتح جملة فرعية.`,
      rule: "obwohl + Nebensatz  |  dennoch + Hauptsatz (Verb Position 2)", ex: "**Obwohl** er müde war, arbeitete er weiter.", exTr: "رغم إنّو كان تعبان، كمّل الخدمة." },
    37: { ok: "WEIL", type: "conjunction", keyword: "weil + Nebensatz", bed: "خاطر",
      text: `"Prozesse … anstrengen, ___ die Kinder die Ruhe … stören": سبب الدعاوى، والفعل "stören" في الآخر.\n✓ "weil" = خاطر (+ فعل في الآخر).\n✗ "obwohl" = رغم إنّو (تنازل)، والمنطق سبب.\n✗ "dass" = إنّو (محتوى)، و"anstrengen, dass" ما تعطيش معنى السبب.`,
      rule: "weil + Nebensatz = Grund", ex: "Er klagt, **weil** der Lärm zu laut ist.", exTr: "يشتكي خاطر الضجيج برشا." },
    38: { ok: "DASS", type: "conjunction", keyword: "so …, dass …", bed: "بحيث",
      text: `"so angeordnet, ___ mit einem Kinderwagen kein Durchkommen ist": "so … dass" = نتيجة.\n✓ "dass" = (so … dass: بحيث).\n✗ "weil" = خاطر (سبب)، موش نتيجة "so … dass".\n✗ "obwohl" = رغم إنّو (تنازل)، موش نتيجة.`,
      rule: "so + Adj. / Part., dass + Nebensatz = Folge", ex: "Der Weg ist so eng, **dass** kein Auto durchkommt.", exTr: "الطريق ضيّق برشا لدرجة ما تعدّي كرهبة." },
    39: { ok: "AUF", type: "preposition", keyword: "Anspruch auf + Akk.", bed: "حقّ في",
      text: `"Anspruch ___ einen Platz": "Anspruch auf" = حقّ في.\n✓ "auf" = في (Anspruch auf + Akkusativ).\n✗ "von" = من، و"Anspruch von einen Platz" ما تتقالش.\n✗ "bei" = عند، و"Anspruch bei einen Platz" ما تتقالش.`,
      rule: "Anspruch auf + Akk. (auf einen Platz, auf Urlaub)", ex: "Jeder hat **Anspruch** auf Urlaub.", exTr: "كلّ واحد عندو حقّ في عطلة." },
    40: { ok: "VON", type: "verb_prep", keyword: "sprechen von + Dativ", bed: "على",
      text: `"spricht man … gerne ___ "Problemen"": "sprechen von" = يحكي على.\n✓ "von" = على (sprechen von + Dativ).\n✗ "auf" = على، و"sprechen auf Problemen" ما تتقالش.\n✗ "davon" = على هذا (Pronominaladverb)، وبعدو اسم ("Problemen") موش جملة.`,
      rule: "sprechen von / über + Dativ / Akk.  |  davon, wenn kein Nomen folgt", ex: "Wir **sprechen** von einem Problem.", exTr: "نحكيو على مشكل." },
  },

  // ───────────── [33] Deutschland – ein Paradies für Kinder? (معدل) ─────────────
  33: {
    31: { ok: "ZUR", type: "fixed_expression", keyword: "zur Verfügung stehen", bed: "على الذمّة",
      text: `"steht … ein Betreuungsplatz … ___ Verfügung": تعبير ثابت: "zur Verfügung stehen" (zu + der).\n✓ "zur" = zu + der (zur Verfügung).\n✗ "auf" = على، و"auf Verfügung" ما تتقالش.\n✗ "mit" = مع، و"mit Verfügung stehen" ما تتقالش.`,
      rule: "zur Verfügung stehen / stellen (feste Wendung)", ex: "Das Auto **steht** uns **zur** Verfügung.", exTr: "الكرهبة على ذمّتنا." },
    32: { ok: "BEI", type: "preposition", keyword: "bei dem Kind zu Hause bleiben", bed: "عند (الصغير)",
      text: `"drei Jahre ___ dem Kind zu Hause zu bleiben": الأب / الأمّ يقعد عند الصغير.\n✓ "bei" = عند (bei dem Kind).\n✗ "mit" = مع: "mit dem Kind zu Hause bleiben" ممكنة وعاديّة في الكلام، بصح الإجابة المعتمدة هنا "bei".\n✗ "auf" = على، و"auf dem Kind zu Hause bleiben" ما تتقالش.`,
      rule: "bei + Dativ = bei jdm. sein / bleiben (Obhut)", ex: "Er bleibt **bei** seiner kranken Mutter.", exTr: "هو يبقى عند أمّو المريضة." },
    33: { ok: "DAS", type: "pronoun", keyword: "das = Rückbezug auf den Satz", bed: "هذا",
      text: `"…zu bleiben, ___ hat den Vorteil, dass …": ضمير فاعل يرجع على الجملة اللي قبل.\n✓ "das" = هذا (فاعل "hat").\n✗ "dass" = إنّو (رابط)، وما يعمل فاعل للفعل "hat".\n✗ "dabei" = في هذا (ظرف)، موش فاعل.`,
      rule: "Das + Verb = Rückbezug auf einen ganzen Satz", ex: "Er hilft uns. **Das** freut mich.", exTr: "هو يعاوننا. هذا يفرّحني." },
    34: { ok: "DENNOCH", type: "adjective_adverb", keyword: "dennoch (Konzession)", bed: "رغم ذلك",
      text: `"___ wird die Elternzeit … zu einem gravierenden Problem": بعد ذكر الميزة نقولو "رغم ذلك"، والفعل "wird" بعدو مباشرة.\n✓ "dennoch" = رغم ذلك (تنازل، الفعل في الثانية).\n✗ "jedoch" = لكن: ممكنة نحويًّا، بصح "dennoch" تعبّر على التنازل (رغم الميزة).\n✗ "dass" = إنّو (رابط + فعل في الآخر)، وهنا "wird" في الثانية.`,
      rule: "dennoch = trotzdem (Verb Position 2)  |  jedoch = aber (Gegensatz)", ex: "Es war teuer, **dennoch** kaufte er es.", exTr: "كان غالي، رغم ذلك شراه." },
    35: { ok: "DOCH", type: "conjunction", keyword: "doch (Gegensatz, Position 0)", bed: "لكن",
      text: `"___ auch andere Dinge machen Familien … das Leben schwer": فاعل ثم فعل ("auch andere Dinge machen").\n✓ "doch" = لكن (رابط تعارض، Position 0).\n✗ "dennoch" = رغم ذلك (ظرف)، ياخذ الفعل مباشرة بعدو ("Dennoch machen …").\n✗ "jedoch" = غير إنّو: ممكنة نحويًّا، بصح "doch" تجي في أول الجملة بصيغة أقرب.`,
      rule: "doch + Subjekt + Verb (Position 0)  |  dennoch + Verb + Subjekt", ex: "**Doch** auch das ist nicht genug.", exTr: "لكن حتى هذا موش كافي." },
    36: { ok: "SONDERN", type: "conjunction", keyword: "nicht …, sondern …", bed: "بل",
      text: `"nicht still am Tisch, ___ stören mit ihrem Lachen": تصحيح بعد نفي.\n✓ "sondern" = بل.\n✗ "doch" = لكن: ممكنة، بصح بعد "nicht" المعتاد "sondern".\n✗ "weil" = خاطر (+ فعل في الآخر)، وهنا "stören" في الثانية.`,
      rule: "nicht A, sondern B", ex: "Nicht heute, **sondern** morgen.", exTr: "موش اليوم، بل غدوة." },
    37: { ok: "NIEMANDEN", type: "pronoun", keyword: "stören + Akk.: niemanden", bed: "حتى واحد",
      text: `"stört das ___": "stören" ياخذ Akkusativ، والنفي بـ "niemanden".\n✓ "niemanden" = حتى واحد (Akkusativ).\n✗ "dabei" = في هذا (ظرف)، موش مفعول به.\n✗ "auf" = على (حرف جر)، وما يعمل مفعول به.`,
      rule: "stören + Akkusativ: niemanden / jemanden", ex: "Das stört **niemanden**.", exTr: "هذا ما يزعج حتى واحد." },
    38: { ok: "WEIL", type: "conjunction", keyword: "weil (Grund der Klagen)", bed: "خاطر",
      text: `"Prozesse gegen Kindergärten … anstrengen, ___ die Kinder … stören": سبب.\n✓ "weil" = خاطر.\n✗ "dass" = إنّو (محتوى)، موش سبب.\n✗ "bei" = عند، حرف جر قبل جملة ما تتركّبش.`,
      rule: "weil + Nebensatz, Verb am Ende", ex: "Sie bleiben zu Hause, **weil** es regnet.", exTr: "يقعدو في الدار خاطر تشتي." },
    39: { ok: "DASS", type: "conjunction", keyword: "so …, dass", bed: "بحيث",
      text: `"so angeordnet, ___ mit einem Kinderwagen kein Durchkommen ist": نتيجة.\n✓ "dass" = (so … dass).\n✗ "das" = ضمير إشارة (حرف s واحد)، موش رابط.\n✗ "weil" = خاطر، موش نتيجة.`,
      rule: "so …, dass = Folge", ex: "Er läuft so schnell, **dass** niemand ihn einholt.", exTr: "يجري بسرعة لدرجة حتى واحد ما يلحقو." },
    40: { ok: "AUF", type: "preposition", keyword: "Anspruch auf", bed: "حقّ في",
      text: `"Anspruch ___ einen Platz": "Anspruch auf".\n✓ "auf" = في.\n✗ "bei" = عند، و"Anspruch bei" ما تتقالش.\n✗ "mit" = مع، و"Anspruch mit einen Platz" ما تتقالش.`,
      rule: "Anspruch auf + Akk.", ex: "Du hast **Anspruch** auf Hilfe.", exTr: "عندك حقّ في مساعدة." },
  },

  // ───────────── [34] Deutschland – ein Paradies für Kinder? (معدل 2) ─────────────
  34: {
    31: { ok: "ZUR", type: "fixed_expression", keyword: "zur Verfügung", bed: "على الذمّة",
      text: `"…in einer Kindertagesstätte ___ Verfügung": "zur Verfügung stehen".\n✓ "zur" = zu + der.\n✗ "auf" = على، و"auf Verfügung" ما تتقالش.\n✗ "bei" = عند، و"bei Verfügung" ما تتقالش.`,
      rule: "zur Verfügung stehen (feste Wendung)", ex: "Die Räume stehen allen **zur** Verfügung.", exTr: "القاعات على ذمّة الكلّ." },
    32: { ok: "DENNOCH", type: "adjective_adverb", keyword: "dennoch + Verb", bed: "رغم ذلك",
      text: `"___ wird die Elternzeit … zu einem gravierenden Problem": تنازل بعد ذكر الميزة.\n✓ "dennoch" = رغم ذلك (الفعل بعدو).\n✗ "dabei" = في هذا السياق: ممكنة بمعنى "ومع ذلك"، بصح "dennoch" أوضح للتنازل.\n✗ "doch" = لكن: ممكنة نحويًّا، بصح "dennoch" تعبّر على رغم الميزة.`,
      rule: "dennoch = trotzdem (Konzessiv-Adverb)", ex: "Er ist alt, **dennoch** arbeitet er.", exTr: "هو كبير، رغم ذلك يخدم." },
    33: { ok: "VEREINBAREN", type: "verb", keyword: "zu vereinbaren (Infinitiv)", bed: "يجمع (بين)",
      text: `"Kind und Karriere zu ___ ist … unmöglich": "zu + Infinitiv" كفاعل، و"vereinbaren" = يوفّق بين.\n✓ "vereinbaren" = يوفّق / يجمع (Infinitiv بعد "zu").\n✗ "werden" = يصير، و"Kind und Karriere zu werden" ما تتقالش.\n✗ "sich" = ضمير انعكاسي، موش فعل.`,
      rule: "A und B vereinbaren = in Einklang bringen", ex: "Arbeit und Familie zu **vereinbaren** ist schwer.", exTr: "الجمع بين الخدمة والعايلة صعيب." },
    34: { ok: "NIEMANDEN", type: "pronoun", keyword: "niemanden (Akk.)", bed: "حتى واحد",
      text: `"stört das ___": مفعول به بعد "stören".\n✓ "niemanden" = حتى واحد (Akkusativ).\n✗ "dabei" = في هذا، موش مفعول به.\n✗ "sich" = انعكاسي، و"stört das sich" ما تتقالش.`,
      rule: "niemanden = Akkusativ von niemand", ex: "Ich sehe **niemanden**.", exTr: "ما نشوفش حتى واحد." },
    35: { ok: "WEIL", type: "conjunction", keyword: "weil", bed: "خاطر",
      text: `"Prozesse … anstrengen, ___ die Kinder die Ruhe … stören": سبب.\n✓ "weil" = خاطر (+ فعل في الآخر).\n✗ "dass" = إنّو، موش سبب.\n✗ "dennoch" = رغم ذلك (ظرف)، موش رابط جملة فرعية.`,
      rule: "weil + Nebensatz = Grund", ex: "Wir bleiben, **weil** wir müde sind.", exTr: "نقعدو خاطر تعبانين." },
    36: { ok: "WERDEN", type: "tense", keyword: "werden + Partizip II (Passiv)", bed: "تتسكّر",
      text: `"Spielplätze ___ von Gerichts wegen geschlossen": Passiv جمع: werden + Partizip II.\n✓ "werden" = Passiv Präsens (جمع).\n✗ "sich" = ضمير انعكاسي، موش فعل مساعد.\n✗ "vereinbaren" = فعل Infinitiv (يوفّق)، موش فعل مساعد.`,
      rule: "Vorgangspassiv: werden + Partizip II", ex: "Die Läden **werden** geschlossen.", exTr: "الدكاكين تتسكّر." },
    37: { ok: "DASS", type: "conjunction", keyword: "so …, dass", bed: "بحيث",
      text: `"so angeordnet, ___ mit einem Kinderwagen kein Durchkommen ist": نتيجة.\n✓ "dass" = (so … dass).\n✗ "weil" = خاطر، موش نتيجة.\n✗ "das" = ضمير إشارة، موش رابط.`,
      rule: "so …, dass + Nebensatz", ex: "Es ist so laut, **dass** ich nichts höre.", exTr: "صاخب برشا لدرجة ما نسمع شي." },
    38: { ok: "SICH", type: "pronoun", keyword: "sich breitmachen", bed: "(ياخذو) بلاصة",
      text: `"haben ___ schon andere Reisende breitgemacht": "sich breitmachen" فعل انعكاسي (Perfekt مع "haben").\n✓ "sich" = ضمير انعكاسي للغائب جمع.\n✗ "dabei" = في هذا (ظرف)، موش ضمير انعكاسي.\n✗ "das" = ضمير إشارة، وما يطابقش الفعل الانعكاسي.`,
      rule: "sich breitmachen = viel Platz einnehmen (reflexiv)", ex: "Er hat **sich** auf dem Sofa breitgemacht.", exTr: "هو بسط روحو على الكنبة." },
    39: { ok: "AUF", type: "preposition", keyword: "Anspruch auf", bed: "حقّ في",
      text: `"Anspruch ___ einen Platz": حقّ في.\n✓ "auf" = في (Anspruch auf + Akk.).\n✗ "zur" = zu + der (مؤنّث Dativ)، و"Anspruch zur einen Platz" ما تتقالش.\n✗ "bei" = عند، و"Anspruch bei" ما تتقالش.`,
      rule: "Anspruch auf + Akk.", ex: "Sie hat **Anspruch** auf Hilfe.", exTr: "عندها حقّ في المساعدة." },
    40: { ok: "DABEI", type: "pronoun_adverb", keyword: "dabei (= damit, in diesem Zusammenhang)", bed: "بهذا",
      text: `"Man meint ___ die Kinder": الكلمة "Problemen" مذكورة قبل، و"dabei" تعني "بهذا / في هذا السياق".\n✓ "dabei" = بهذا (bei + das، في هذا السياق).\n✗ "dafür" = لهذا (für + das)، و"meint dafür die Kinder" ما تتقالش.\n✗ "davon" = منها (von + das)، و"meint davon die Kinder" ما تتقالش.`,
      rule: "meinen mit → damit / dabei: Man meint dabei die Kinder", ex: "Er sagt Fehler und meint **dabei** dich.", exTr: "يقول غلطات ويقصد بهذا إنت." },
  },

  // ───────────── [35] Wie TV-Bilder die Fantasie von Kindern prägen ─────────────
  35: {
    31: { ok: "DURCH", type: "preposition", keyword: "durch + Akk. (Mittel)", bed: "عبر / بسبب",
      text: `"Werden Kinder … ___ brutale … Medieninhalte gewaltbereiter?": السبب / الوسيلة: عبر المحتوى (Akkusativ جمع).\n✓ "durch" = عبر / بسبب (durch + Akkusativ).\n✗ "mit" = مع (+ Dativ)، و"brutale Medieninhalte" في Akkusativ.\n✗ "von" = من (+ Dativ)، وما تعطيش معنى الوسيلة.`,
      rule: "durch + Akk. = Ursache / Mittel (durch Medien, durch Training)", ex: "Man lernt **durch** Wiederholung.", exTr: "الواحد يتعلّم بالتكرار." },
    32: { ok: "VOR", type: "fixed_expression", keyword: "vor allem", bed: "خاصةً",
      text: `تعبير ثابت: "vor allem" = خاصةً.\n✓ "vor" = (vor allem).\n✗ "von" = من، و"von allem Jungen" ما تتقالش.\n✗ "aus" = من، و"aus allem" ما تعطيش "خاصةً".`,
      rule: "vor allem = besonders / hauptsächlich (feste Wendung)", ex: "**Vor** allem Kinder lieben das.", exTr: "خاصةً الصغار يحبّو هذا." },
    33: { ok: "WELCHE", type: "pronoun", keyword: "welche + Nomen (Frage)", bed: "أيّ",
      text: `"untersucht, ___ Bilder in den Köpfen … herumgeistern": سؤال على النوع: أيّ صور.\n✓ "welche" = أيّ (Fragewort + Nomen جمع).\n✗ "was" = شنوّة: تحتاج "was für" قبل الاسم.\n✗ "wie" = كيفاش: ممكنة نحويًّا، بصح الجملة تسأل على أيّ صور موش على الطريقة.`,
      rule: "welche + Plural-Nomen = Auswahlfrage  |  was für (ein) + Nomen", ex: "Er fragt, **welche** Filme sie mag.", exTr: "يسأل أيّ أفلام تحبّ." },
    34: { ok: "UNTERSCHIEDEN", type: "verb", keyword: "sich unterscheiden", bed: "اختلفت",
      text: `"Die Fantasien der Jungen und Mädchen ___ sich deutlich": مقارنة بين الجنسين.\n✓ "unterschieden" = اختلفت (sich unterscheiden، Präteritum جمع).\n✗ "veränderten" = تغيّرت: "veränderten sich" ممكنة، بصح المعنى هنا فرق بين طرفين موش تغيّر مع الوقت.\n✗ "machten" = عملو، وما يتركّبش مع "sich deutlich".`,
      rule: "sich unterscheiden = anders sein  |  sich verändern = anders werden", ex: "Beide **unterschieden** sich stark.", exTr: "الزوز اختلفو برشا." },
    35: { ok: "LIESSEN", type: "verb", keyword: "lassen + Infinitiv (enden lassen)", bed: "خلّو (تنتهي)",
      text: `"Die Schülerinnen ___ das Märchen dagegen meist gewaltfrei enden": "enden lassen" = يخلّي تنتهي.\n✓ "ließen" = خلّو (Präteritum جمع من lassen + Infinitiv).\n✗ "machten" = عملو، و"machten … enden" ما تتركّبش (يحتاجو "lassen").\n✗ "veränderten" = غيّرو، ويحتاج مفعول به موش Infinitiv "enden".`,
      rule: "lassen + Infinitiv = veranlassen: etwas enden lassen", ex: "Sie **ließen** die Katze gehen.", exTr: "خلّاو القطّوسة تمشي." },
    36: { ok: "WIE", type: "conjunction", keyword: "wie sehr", bed: "قدّاش",
      text: `"zeige jedoch, ___ sehr Bilder aus den Medien … prägen": "wie sehr" = قدّاش (درجة).\n✓ "wie" = قدّاش (wie sehr).\n✗ "was" = شنوّة، و"was sehr" ما تتقالش.\n✗ "so" = هكا، و"so sehr Bilder … prägen" ما تعمل جملة سؤال غير مباشر.`,
      rule: "wie sehr / wie viel / wie oft + Nebensatz", ex: "Man sieht, **wie** sehr er sich freut.", exTr: "نشوفو قدّاش هو فرحان." },
    37: { ok: "VON", type: "preposition", keyword: "von + Dativ (statt Genitiv)", bed: "متاع",
      text: `"die Vorstellungswelt ___ Jugendlichen": "von" بديل للـ Genitiv مع اسم جمع بدون أداة.\n✓ "von" = متاع (von + Dativ).\n✗ "jene" = تلك (إشارة)، و"Vorstellungswelt jene Jugendlichen" ما تتطابقش.\n✗ "mit" = مع، و"Vorstellungswelt mit Jugendlichen" تعطي معنى آخر.`,
      rule: "Plural ohne Artikel: von + Dativ ersetzt den Genitiv (die Welt von Kindern)", ex: "Das ist die Welt **von** Kindern.", exTr: "هذا عالم الصغار." },
    38: { ok: "MIT", type: "pronoun", keyword: "mit dem (Relativpronomen)", bed: "بيه",
      text: `"das Vokabular, ___ dem man die Welt begreift": الوسيلة: "mit dem" (Relativpronomen).\n✓ "mit" = بـ (mit dem = بيه).\n✗ "von" = من، و"von dem man die Welt begreift" معناها غير الوسيلة.\n✗ "aus" = من، و"aus dem man die Welt begreift" ما تتقالش.`,
      rule: "Präposition + Relativpronomen: mit dem / mit der / mit denen", ex: "Das ist das Werkzeug, **mit** dem man arbeitet.", exTr: "هذي الأداة اللي بيها نخدمو." },
    39: { ok: "WAS", type: "pronoun", keyword: "was … überhaupt ist", bed: "شنوّة",
      text: `"keine Vorstellung davon entwickeln, ___ Musik überhaupt ist": سؤال على الماهية.\n✓ "was" = شنوّة (was Musik ist).\n✗ "wie" = كيفاش: ممكنة، بصح السؤال عن الماهية موش عن الكيفية.\n✗ "welche" = أيّ، و"welche Musik überhaupt ist" ما تتماشاش (يحتاج اسم بعدها).`,
      rule: "was ist X? = Frage nach dem Wesen  |  wie ist X? = Frage nach der Beschaffenheit", ex: "Er weiß nicht, **was** Freiheit ist.", exTr: "ما يعرفش شنوّة الحرية." },
    40: { ok: "DANN", type: "adjective_adverb", keyword: "dann, wenn …", bed: "وقتها",
      text: `"Gefährlich werde es aber ___, wenn positive Alternativbilder fehlten": "dann, wenn" = وقتها، وقتما.\n✓ "dann" = وقتها (dann, wenn …).\n✗ "so" = هكا، و"so, wenn" ما تتقالش.\n✗ "vor" = قبل، ما تعطيش معنى وقتها.`,
      rule: "dann, wenn … = genau dann, wenn (Bedingung betont)", ex: "Es wird schwierig **dann**, wenn wir müde sind.", exTr: "يولّي صعيب وقتها وقتما نكونو تعبانين." },
  },

  // ───────────── [36] Städte vor dem Infarkt ─────────────
  36: {
    31: { ok: "DAVON", type: "pronoun_adverb", keyword: "träumen von → davon, … zu", bed: "من هذا",
      text: `"haben Menschen ___ geträumt, jederzeit mobil zu sein": "träumen von" ← "davon" + zu-Infinitiv.\n✓ "davon" = من هذا (von + das).\n✗ "dazu" = لهذا (zu + das)، و"träumen dazu" ما تتقالش.\n✗ "hiermit" = بهذا هنا (mit + hier)، وما تتركّبش مع "träumen".`,
      rule: "träumen von + Dat. → davon träumen, … zu + Infinitiv", ex: "Er träumt **davon**, Pilot zu werden.", exTr: "يحلم إنّو يولّي طيّار." },
    32: { ok: "WER", type: "pronoun", keyword: "wer … , der … (verallgemeinernd)", bed: "اللي",
      text: `"___ Auto fährt, hat in seinem Leben etwas erreicht": جملة عامة: كلّ من.\n✓ "wer" = اللي / كلّ من (Subjekt، شخص).\n✗ "wenn" = إذا: يحتاج فاعل بعدو ("wenn man Auto fährt")، وهنا الفاعل ناقص.\n✗ "so" = هكا، موش ضمير فاعل.`,
      rule: "Wer + Verb, … = jeder, der …", ex: "**Wer** fleißig lernt, besteht.", exTr: "اللي يقرا باجتهاد ينجح." },
    33: { ok: "DASS", type: "conjunction", keyword: "Daraus folgt, dass …", bed: "إنّو",
      text: `"Daraus folgt, ___ für so viele Fahrzeuge der Platz nicht mehr ausreicht": نتيجة، محتوى.\n✓ "dass" = إنّو (+ فعل في الآخر).\n✗ "denn" = خاطر (+ فعل في الثانية)، وما يفتحش محتوى بعد "folgt".\n✗ "wenn" = إذا (شرط)، موش محتوى.`,
      rule: "Daraus folgt, dass + Nebensatz", ex: "Daraus folgt, **dass** wir sparen müssen.", exTr: "من هذا يتبع إنّو لازمنا نوفّرو." },
    34: { ok: "OFT", type: "adjective_adverb", keyword: "oft nicht breit genug", bed: "برشا مرّات",
      text: `"Die Straßen sind ___ nicht breit genug": ظرف تكرار.\n✓ "oft" = برشا مرّات.\n✗ "so" = هكا، و"sind so nicht breit genug" ما تعطيش تكرار.\n✗ "kosten" = يكلّفو (فعل)، موش ظرف بعد "sind".`,
      rule: "oft = häufig (Adverb der Häufigkeit)", ex: "Der Zug ist **oft** zu spät.", exTr: "التران برشا مرّات متأخّر." },
    35: { ok: "FAHREN", type: "verb", keyword: "länger stehen, als sie fahren", bed: "يسوقو (يتحرّكو)",
      text: `"stehen die Fahrzeuge … länger, als sie ___": مقارنة بين الوقوف والحركة، والفاعل جمع.\n✓ "fahren" = يتحرّكو (3. Person جمع).\n✗ "kosten" = يكلّفو، و"länger als sie kosten" تغيّر المعنى كلّيًّا (ثمن).\n✗ "graben" = يحفرو، ما يتماشاش مع سيّارات.`,
      rule: "länger stehen, als sie fahren (Vergleich Zeit)", ex: "Der Bus steht länger, als er **fährt**.", exTr: "البيّاص يوقف أكثر ما يسوق." },
    36: { ok: "DENN", type: "conjunction", keyword: "denn + Hauptsatz", bed: "خاطر",
      text: `"Nichts geht mehr, ___ die Zahl … ist zu groß geworden": الفعل "ist" في الثانية، يعني جملة رئيسية، والجملة تعطي سبب.\n✓ "denn" = خاطر (+ جملة رئيسية).\n✗ "dass" = إنّو (+ فعل في الآخر)، موش سبب، وهنا "ist" في الثانية.\n✗ "wenn" = إذا (+ فعل في الآخر)، وهنا الجملة سبب موش شرط.`,
      rule: "denn + Hauptsatz  |  wenn / dass + Nebensatz", ex: "Ich gehe, **denn** es ist spät.", exTr: "نمشي، خاطر الوقت تأخّر." },
    37: { ok: "DAZU", type: "pronoun_adverb", keyword: "führen zu → dazu, dass", bed: "إلى هذا",
      text: `"Die Erwärmung der Luft führt ___, dass sich das Klima verändert": "führen zu" ← "dazu".\n✓ "dazu" = إلى هذا (zu + das).\n✗ "davon" = من هذا (von + das)، و"führt davon" ما تتقالش.\n✗ "hiermit" = بهذا هنا، وما تتركّبش مع "führen".`,
      rule: "führen zu + Dat. → dazu führen, dass …", ex: "Regen **führt dazu**, dass die Straße nass ist.", exTr: "المطر يوصّل لإنّو الطريق مبلولة." },
    38: { ok: "UM", type: "conjunction", keyword: "um … zu + Infinitiv", bed: "باش",
      text: `"___ dem Verkehrsinfarkt zuvorzukommen … haben einige Großstädte damit begonnen": غرض مع "zu + Infinitiv".\n✓ "um" = باش (um … zu).\n✗ "so" = هكا، موش رابط غرض.\n✗ "wenn" = إذا (شرط)، وما تعطيش غرض.`,
      rule: "um … zu + Infinitiv = Zweck", ex: "**Um** Zeit zu sparen, nehmen wir den Zug.", exTr: "باش نوفّرو وقت، ناخذو التران." },
    39: { ok: "GRABEN", type: "verb", keyword: "sich graben durch", bed: "تحفر (طريقها)",
      text: `"In den großen Metropolen ___ sich die Tunnel … durch das Erdreich": "sich graben durch" = تحفر طريقها.\n✓ "graben" = يحفرو (sich graben، جمع).\n✗ "reiben" = يحكّو (sich reiben)، و"sich durch das Erdreich reiben" ما تعطيش معنى حفر.\n✗ "klauen" = يسرقو، وما يتركّبش مع "sich … durch".`,
      rule: "sich durch etwas graben = sich einen Weg graben", ex: "Der Maulwurf **gräbt** sich durch die Erde.", exTr: "الخلد يحفر طريقو في التراب." },
    40: { ok: "KOSTEN", type: "verb", keyword: "Überzeugungsarbeit kosten", bed: "ستكلّف (جهد)",
      text: `"…noch viel Überzeugungsarbeit ___ wird": "Arbeit kosten" = ستتطلّب جهد، والفعل في الآخر مع "wird".\n✓ "kosten" = يكلّف / يتطلّب (Infinitiv + wird).\n✗ "fahren" = يسوق، و"Überzeugungsarbeit fahren" ما تتقالش.\n✗ "klauen" = يسرق، وما يتركّبش مع "Arbeit".`,
      rule: "etwas wird Zeit / Mühe / Arbeit kosten (Futur I, Nebensatz)", ex: "Das **wird** viel Geld **kosten**.", exTr: "هذا باش يكلّف برشا فلوس." },
  },
};
