// SB Teil 2 restyle — batch 12: [57] Museum, [58] Klimawandel/Alpen (gap 31 vor/zu both OK; 32/33 einzelner/vieler hedged), [59] Teleshopping (several distractors also fit → hedged), [61] Internet-Hauptstadt, [62] Vegetarisch
export default {
  // ───────────── [57] Allein das Wort „Museum" ist schon fad ─────────────
  57: {
    31: { ok: "PUNKT", type: "fixed_expression", keyword: "auf den Punkt bringen", bed: "يلخّص بدقّة",
      text: `"wie es eine Oberstufenschülerin auf den ___ bringt": تعبير ثابت: "etwas auf den Punkt bringen" = يلخّصها في كلمات واضحة.\n✓ "Punkt" = نقطة (auf den Punkt bringen).\n✗ "Gipfel" = قمّة: "auf den Gipfel bringen" معناها يوصّل لقمّة، موش يلخّص.\n✗ "bringen" = فعل (يجيب)، موش اسم بعد "den".`,
      rule: "etwas auf den Punkt bringen = kurz und treffend sagen", ex: "Sie **bringt** das Problem **auf den Punkt**.", exTr: "هي تلخّص المشكل بدقّة." },
    32: { ok: "SCHAFFEN", type: "fixed_expression", keyword: "aus der Welt schaffen", bed: "يلغي (نهائيًّا)",
      text: `"Um genau diese Vorurteile aus der Welt zu ___": تعبير ثابت: "aus der Welt schaffen" = يزيل نهائيًّا.\n✓ "schaffen" = يزيل (aus der Welt schaffen، Infinitiv بعد "zu").\n✗ "bringen" = يجيب: "aus der Welt bringen" ما تتقالش بهذا المعنى.\n✗ "entgehen" = يفلت من (+ Dativ)، وما يعطيش معنى إزالة.`,
      rule: "etwas aus der Welt schaffen = beseitigen (Probleme, Streit, Vorurteile)", ex: "Wir wollen den Streit **aus der Welt schaffen**.", exTr: "نحبّو نلغيو الخلاف نهائيًّا." },
    33: { ok: "AN", type: "verb", keyword: "anbieten (bieten … an)", bed: "يقدّمو",
      text: `"bieten spezielle Veranstaltungen für Schüler ___": الفعل المنفصل "anbieten": "bieten … an".\n✓ "an" = الجزء المنفصل (bieten … an).\n✗ "zum" = zu + dem (حرف جر + أداة)، موش جزء فعل.\n✗ "am" = an + dem، موش جزء من "anbieten" هنا.`,
      rule: "trennbar: anbieten → bieten … an", ex: "Das Museum **bietet** Führungen **an**.", exTr: "المتحف يقدّم جولات مرشدة." },
    34: { ok: "WEITERE", type: "adjective_adverb", keyword: "noch weitere + Plural", bed: "أخرى",
      text: `"noch ___ schulbezogene Veranstaltungen angeboten werden": صفة بنهاية -e قبل جمع (Nominativ).\n✓ "weitere" = أخرى (-e: Plural Nominativ بعد "noch").\n✗ "eher" = بالأحرى (ظرف)، وما تركّبش قبل "Veranstaltungen" كصفة.\n✗ "darum" = لهذا (ظرف)، موش صفة.`,
      rule: "noch + weitere + Plural-Nomen (Nom. / Akk.)", ex: "Es gibt noch **weitere** Angebote.", exTr: "فما كذلك عروض أخرى." },
    35: { ok: "DARUM", type: "pronoun_adverb", keyword: "es geht darum, … zu", bed: "المسألة هي",
      text: `"Geht es den teilnehmenden Schulklassen ___, Interessantes … zu erfahren": "es geht um" ← "darum" + zu-Infinitiv.\n✓ "darum" = (es geht darum، um + das).\n✗ "darin" = في هذا: "es besteht darin" هي الصيغة الصحيحة، و"geht es darin" ما تتقالش.\n✗ "womit" = بشنوّة (كلمة سؤال / ضمير موصول)، موش بعد "geht es".`,
      rule: "es geht um + Akk. → es geht darum, … zu + Infinitiv", ex: "Es geht **darum**, Spaß zu haben.", exTr: "المسألة هي نتمتّعو." },
    36: { ok: "ZUM", type: "fixed_expression", keyword: "Mittel zum Zweck", bed: "وسيلة لغاية",
      text: `"Mittel ___ Zweck": تعبير ثابت: "Mittel zum Zweck" = وسيلة لتحقيق هدف.\n✓ "zum" = zu + dem (Mittel zum Zweck).\n✗ "am" = an + dem، و"Mittel am Zweck" ما تتقالش.\n✗ "an" = على / عند، و"Mittel an Zweck" ما تتقالش.`,
      rule: "Mittel zum Zweck = nur ein Weg, um etwas zu erreichen", ex: "Geld ist nur **Mittel zum Zweck**.", exTr: "الفلوس وسيلة لغاية برك." },
    37: { ok: "ENTGEHEN", type: "verb", keyword: "dem Alltag entgehen", bed: "يهرب من",
      text: `"um dem Schulalltag zu ___": "entgehen + Dativ" = يهرب من / يتجنّب.\n✓ "entgehen" = يهرب من (+ Dativ: dem Schulalltag).\n✗ "schaffen" = ينجّح / يعمل، و"dem Schulalltag zu schaffen" ما تتقالش.\n✗ "liefern" = يوصّل / يعطي، وما يعطيش معنى الهروب.`,
      rule: "jdm. / einer Sache entgehen = entkommen (ausweichen)", ex: "Er wollte dem Stress **entgehen**.", exTr: "حبّ يهرب من الضغط." },
    38: { ok: "WOVON", type: "pronoun_adverb", keyword: "handeln von → wovon", bed: "عن شنوّة",
      text: `"gar nicht sagen können, ___ das zuvor Gesehene handelt": "handeln von" = يتكلّم على، وكلمة السؤال "wovon".\n✓ "wovon" = عن شنوّة (von + was).\n✗ "womit" = بشنوّة (mit + was)، و"handeln womit" ما تتقالش.\n✗ "darin" = في هذا (ظرف)، موش كلمة سؤال.`,
      rule: "handeln von + Dat. → wovon es handelt (Fragewort)", ex: "Er weiß nicht, **wovon** der Film handelt.", exTr: "ما يعرفش على شنوّة يتكلّم الفيلم." },
    39: { ok: "AM", type: "verb_prep", keyword: "liegen an + Dativ", bed: "السبب في",
      text: `"Liegt es allein ___ Unwillen der jungen Bevölkerung": "liegen an" + Dativ، و"Unwillen" مذكّر: "am" = an + dem.\n✓ "am" = an + dem (liegen an).\n✗ "zum" = zu + dem، و"liegt es zum Unwillen" ما تتقالش.\n✗ "an" = بدون أداة: "an Unwillen" ما تتقالش، تحتاج "am" (الأداة المدمجة).`,
      rule: "es liegt an + Dativ: am Unwillen, an der Zeit", ex: "Es **liegt** am Wetter.", exTr: "السبب في الطقس." },
    40: { ok: "EHER", type: "adjective_adverb", keyword: "eher … als …", bed: "بالأحرى",
      text: `"dass … eher die Vorlieben der Pädagogen als diejenigen der Schüler zählen": مقارنة: "eher … als".\n✓ "eher" = بالأحرى (eher A als B).\n✗ "weitere" = أخرى (صفة بنهاية)، موش ظرف مقارنة.\n✗ "darum" = لهذا (ظرف)، وما تعمل مقارنة مع "als".`,
      rule: "eher A als B = mehr A als B (Vergleich)", ex: "Er ist **eher** schüchtern als stolz.", exTr: "هو بالأحرى خجول موش متكبّر." },
  },

  // ───────────── [58] Klimawandel lässt in den Alpen neue Seen entstehen ─────────────
  58: {
    31: { ok: "vor", type: "preposition", keyword: "schon vor Ostern", bed: "قبل",
      text: `"Schon ___ Ostern ist vielerorts … die Wintersportsaison beendet": "قبل عيد الفصح": الموسم يخلص بكري.\n✓ "vor" = قبل (schon vor Ostern = قبل الفصح).\n✗ "zu" = في: "Schon zu Ostern" ممكنة نحويًّا (في عيد الفصح)، بصح الفكرة هنا "قبل" (الموسم خلص بكري عن العادة).\n✗ "da" = لأنّ / هناك (رابط)، موش حرف جر قبل "Ostern".`,
      rule: "vor + Dativ (zeitlich) = früher als  |  zu Ostern = am Fest selbst", ex: "Der Schnee ist schon **vor** Weihnachten gefallen.", exTr: "الثلج نزل من قبل عيد الميلاد." },
    32: { ok: "einzelner", type: "grammar_structure", keyword: "das Wetter einzelner Jahre", bed: "سنوات معيّنة (فرديّة)",
      text: `"warnen, das Wetter ___ Jahre als Hinweis auf die Erwärmung zu betrachten": الخبراء يحذّرو من اعتبار طقس سنوات معزولة دليل.\n✓ "einzelner" = سنوات معزولة (Genitiv جمع، يعطي معنى "بعض سنوات فقط").\n✗ "vieler" = برشا: "das Wetter vieler Jahre" ممكنة نحويًّا، بصح تقلب الحجّة (التحذير يخصّ سنوات قليلة).\n✗ "keiner" = حتى واحد، و"das Wetter keiner Jahre" ما تعطيش معنى.`,
      rule: "einzelner + Genitiv Plural = nur wenige / isolierte (einzelner Jahre)", ex: "Man darf nicht von **einzelnen** Tagen auf alles schließen.", exTr: "ما يجوزش نستنتجو من أيّام معزولة." },
    33: { ok: "vieler", type: "grammar_structure", keyword: "nach Ansicht vieler Forscher", bed: "برشا (باحثين)",
      text: `"nach Ansicht ___ Forscher": "nach Ansicht + Genitiv".\n✓ "vieler" = برشا (Genitiv جمع).\n✗ "einzelner" = بعض فرديين: "nach Ansicht einzelner Forscher" ممكنة نحويًّا، بصح العبارة المعتادة "nach Ansicht vieler Forscher" (رأي أغلبية).\n✗ "keiner" = حتى واحد، وتناقض الجملة.`,
      rule: "nach Ansicht + Genitiv Plural: vieler / zahlreicher / mancher Forscher", ex: "Nach Ansicht **vieler** Experten ist das riskant.", exTr: "حسب رأي برشا خبراء هذا خطر." },
    34: { ok: "sondern", type: "conjunction", keyword: "nicht …, sondern …", bed: "بل",
      text: `"nicht einfach milderes Wetter, ___ vor allem mehr Extreme": تصحيح بعد "nicht".\n✓ "sondern" = بل.\n✗ "falls" = في صورة (شرط)، موش رابط تصحيح.\n✗ "da" = بما إنّو (سبب)، موش رابط تصحيح.`,
      rule: "nicht A, sondern B = Korrektur", ex: "Nicht kalt, **sondern** eisig.", exTr: "موش بارد، بل متجمّد." },
    35: { ok: "steigen", type: "verb", keyword: "steigen (werden … steigen)", bed: "ترتفع",
      text: `"werden die Durchschnittstemperaturen … um wenige bis einige Grad ___": ارتفاع الحرارة: Infinitiv مع "werden".\n✓ "steigen" = ترتفع (Futur I، Infinitiv في الآخر).\n✗ "sinken" = تنزل، عكس المعنى (الاحترار).\n✗ "gleiten" = تنزلق، وما تتركّب مع "Temperaturen … um … Grad".`,
      rule: "steigen ≠ sinken (Temperatur steigt / sinkt um … Grad)", ex: "Die Preise werden weiter **steigen**.", exTr: "الأسعار باش تواصل ترتفع." },
    36: { ok: "da", type: "conjunction", keyword: "da + Nebensatz (Grund / Zeit)", bed: "بما إنّو",
      text: `"___ die Gletscher gerade erst schmelzen, entstehen derzeit neue Seen": سبب معروف، والفعل "schmelzen" في الآخر.\n✓ "da" = بما إنّو (+ فعل في الآخر).\n✗ "falls" = في صورة (شرط)، والذوبان واقع فعلًا موش افتراض.\n✗ "sondern" = بل (تصحيح بعد نفي)، وما فماش نفي.`,
      rule: "da + Nebensatz = bekannter Grund", ex: "**Da** es regnet, bleiben wir zu Hause.", exTr: "بما إنّو تشتي، نقعدو في الدار." },
    37: { ok: "falls", type: "conjunction", keyword: "falls (für den Fall, dass)", bed: "في صورة",
      text: `"Schutzbauten errichtet – ___ die Seen sich sturzbachartig entladen": احتياط لحالة محتملة.\n✓ "falls" = في صورة (للاحتياط، + فعل في الآخر).\n✗ "da" = بما إنّو: ممكنة (سبب)، بصح البنايات تتعمل للاحتياط من حدوث محتمل موش لسبب واقع.\n✗ "sondern" = بل (تصحيح بعد نفي)، موش شرط.`,
      rule: "falls = für den Fall, dass (mögliches Ereignis)", ex: "Nimm einen Schirm mit, **falls** es regnet.", exTr: "خذ مظلّة، في صورة تشتي." },
    38: { ok: "bedrohlichen", type: "grammar_structure", keyword: "weiteren bedrohlichen Situationen", bed: "مهدّدة",
      text: `"zu weiteren ___ Situationen": "zu" + Dativ جمع: الصفة بـ -en.\n✓ "bedrohlichen" = مهدّدة (-en، Dativ جمع).\n✗ "beschwerlich" = متعب (بدون نهاية)، وما تجي قبل اسم جمع Dativ هكا.\n✗ "befestigt" = Partizip II (مثبّت)، ومعناه ما يوصفش المواقف.`,
      rule: "weiteren + Adjektiv-en + Plural (Dativ nach zu)", ex: "Es kam zu weiteren **gefährlichen** Vorfällen.", exTr: "صارت حوادث أخرى خطيرة." },
    39: { ok: "bekommen", type: "verb", keyword: "Risse bekommen", bed: "تتشقّق",
      text: `"Hütten ___ Risse": "Risse bekommen" = تتشقّق، والفاعل جمع.\n✓ "bekommen" = تتحصّل على (Präsens جمع، Risse bekommen).\n✗ "gleiten" = تنزلق (فعل لازم)، ما ياخذش مفعول به "Risse".\n✗ "sinken" = تنزل، و"Risse sinken" ما تتقالش.`,
      rule: "Risse / Sprünge bekommen = brüchig werden", ex: "Die Wand **bekommt** Risse.", exTr: "الجدار يتشقّق." },
    40: { ok: "befestigt", type: "tense", keyword: "befestigt worden (Passiv Perfekt)", bed: "تدعّم",
      text: `"ist sogar eigens mit Beton ___ worden": Passiv Perfekt: Partizip II + worden.\n✓ "befestigt" = Partizip II من "befestigen" (يثبّت / يدعّم).\n✗ "bekommen" = Partizip من bekommen، و"mit Beton bekommen worden" ما تتقالش.\n✗ "gleiten" = Infinitiv، وبعد "ist … worden" نحتاج Partizip II.`,
      rule: "Passiv Perfekt: ist + Partizip II + worden", ex: "Der Berg ist **befestigt** worden.", exTr: "الجبل تدعّم." },
  },

  // ───────────── [59] Teleshopping – nicht immer gut und günstig ─────────────
  59: {
    31: { ok: "DEUTLICH", type: "adjective_adverb", keyword: "deutlich + Adjektiv", bed: "بوضوح",
      text: `"Qualität ___ enttäuschend, Preise ziemlich hoch": ظرف درجة قبل الصفة.\n✓ "deutlich" = بوضوح / بشكل ملحوظ (deutlich + Adjektiv).\n✗ "eher" = بالأحرى: "eher enttäuschend" ممكنة، بصح هنا الفحص يوصّل لحكم صارم (واضح).\n✗ "genauso" = بنفس القدر (+ wie)، و"genauso enttäuschend" تحتاج مقارنة.`,
      rule: "deutlich + Adjektiv = klar erkennbar  |  eher = mehr in diese Richtung", ex: "Die Qualität war **deutlich** schlechter.", exTr: "الجودة كانت أسوأ بوضوح." },
    32: { ok: "ZOG", type: "fixed_expression", keyword: "ein Fazit ziehen", bed: "استخلص",
      text: `"das Fazit, das die Stiftung Warentest … nach dem Test … ___": تعبير ثابت: "ein Fazit ziehen" = يستخلص.\n✓ "zog" = استخلص (Präteritum من ziehen، ein Fazit ziehen).\n✗ "beschloss" = قرّر (beschließen)، و"ein Fazit beschließen" ما تتقالش.\n✗ "wenden" = يدور / يتوجّه (Infinitiv)، موش فعل ماضي مصرّف.`,
      rule: "ein Fazit ziehen = eine Schlussfolgerung machen", ex: "Er **zog** am Ende ein Fazit.", exTr: "هو في الآخر استخلص نتيجة." },
    33: { ok: "BEI", type: "preposition", keyword: "bei + Dativ (Erfahrungen bei)", bed: "في",
      text: `"die Erfahrungen, die wir ___ Beschwerdefällen machen": "Erfahrungen machen bei".\n✓ "bei" = في / عند (bei Beschwerdefällen).\n✗ "nach" = بعد / حسب، و"Erfahrungen nach Beschwerdefällen" تعني بعدها، موش خلال.\n✗ "dabei" = في هذا (Pronominaladverb)، وبعدو اسم "Beschwerdefällen" موش جملة.`,
      rule: "Erfahrungen bei / mit etwas machen", ex: "Wir machen gute Erfahrungen **bei** der Arbeit.", exTr: "عندنا تجارب باهية في الخدمة." },
    34: { ok: "SONDERN", type: "conjunction", keyword: "nicht …, sondern …", bed: "بل",
      text: `"der Kaufpreis nicht erstattet, ___ es erfolgt nur eine Gutschrift": تصحيح بعد "nicht".\n✓ "sondern" = بل (تصحيح بعد نفي).\n✗ "aber" = لكن: ممكنة، بصح بعد "nicht" المعتاد "sondern".\n✗ "dabei" = في هذا (ظرف)، موش رابط تصحيح.`,
      rule: "nicht A, sondern B  |  A, aber B", ex: "Er zahlt nicht bar, **sondern** per Karte.", exTr: "هو ما يدفعش كاش، بل بالبطاقة." },
    35: { ok: "HÖHE", type: "fixed_expression", keyword: "in voller Höhe", bed: "بالكامل (المبلغ)",
      text: `"nicht einmal in voller ___": تعبير ثابت: "in voller Höhe" = بالمبلغ الكامل.\n✓ "Höhe" = قيمة / مبلغ (in voller Höhe).\n✗ "Rechnung" = فاتورة، و"in voller Rechnung" ما تتقالش.\n✗ "nach" = بعد / حسب (حرف جر)، موش اسم بعد "voller".`,
      rule: "in voller Höhe = vollständig (Betrag)", ex: "Der Betrag wurde **in voller Höhe** erstattet.", exTr: "المبلغ رجّعولو بالكامل." },
    36: { ok: "ABGESEHEN", type: "fixed_expression", keyword: "abgesehen davon", bed: "بقطع النظر عن",
      text: `"Ganz ___ davon gilt natürlich deutsches Recht": تعبير ثابت: "abgesehen davon".\n✓ "abgesehen" = (ganz abgesehen davon = بقطع النظر على هذا).\n✗ "genauso" = بنفس القدر، و"Ganz genauso davon" ما تتقالش.\n✗ "dabei" = في هذا، و"Ganz dabei davon" ما تتقالش.`,
      rule: "abgesehen davon, dass … = außer dass …", ex: "**Abgesehen davon** ist alles gut.", exTr: "بقطع النظر عن هذا، كلّ شي باهي." },
    37: { ok: "WENDEN", type: "verb", keyword: "sich wenden an + Akk.", bed: "يتوجّهو",
      text: `"wenn sich ausländische Unternehmen … an deutsche Verbraucher ___": الجملة الفرعية، الفعل في الآخر، والفاعل جمع.\n✓ "wenden" = يتوجّهو (sich wenden an، جمع).\n✗ "zog" = ماضي مفرد (جرّ)، وما يتماشاش مع "sich … an".\n✗ "beschloss" = قرّر (ماضي مفرد)، وما يتركّبش مع "sich … an".`,
      rule: "sich an jdn. wenden = sich richten an", ex: "Die Firma **wendet** sich an junge Leute.", exTr: "الشركة تتوجّه للشباب." },
    38: { ok: "SOGAR", type: "adjective_adverb", keyword: "sogar unbefristet", bed: "حتى",
      text: `"dieses Recht gilt ___ unbefristet": تصعيد: حتى من غير أجل.\n✓ "sogar" = حتى (تصعيد).\n✗ "eher" = بالأحرى، و"gilt eher unbefristet" ما تعطيش معنى التصعيد.\n✗ "aber" = لكن (رابط)، وما تتركّبش بعد "gilt" هكا.`,
      rule: "sogar = überraschende Steigerung", ex: "Er hilft **sogar** nachts.", exTr: "هو يعاون حتى في الليل." },
    39: { ok: "GENAUSO", type: "adjective_adverb", keyword: "genauso … wie", bed: "بنفس القدر",
      text: `"beim Teleshopping ___ konsequent ihre Rechte durchzusetzen wie bei anderen Verbraucherverträgen": مقارنة تساوي: "genauso … wie".\n✓ "genauso" = بنفس القدر (genauso + Adjektiv + wie).\n✗ "deutlich" = بوضوح، و"deutlich konsequent … wie" ما تتماشاش مع "wie".\n✗ "eher" = بالأحرى، موش مقارنة تساوي.`,
      rule: "genauso + Adjektiv + wie = gleich … wie", ex: "Er ist **genauso** groß wie sein Bruder.", exTr: "هو بنفس طول خوه." },
    40: { ok: "DABEI", type: "pronoun_adverb", keyword: "dabei (in diesem Fall)", bed: "في هذا",
      text: `"___ hilft die Verbraucherzentrale Sachsen mit Tipps und Informationen": في هذا الموضوع: تساعد.\n✓ "dabei" = في هذا (bei + das، الفعل بعدو في الثانية).\n✗ "aber" = لكن: ممكنة نحويًّا، بصح الجملة تحكي على المساعدة في هذا الأمر موش تعارض.\n✗ "abgesehen" = بقطع النظر (وحدو بدون "davon")، ما تفتحش جملة هكا.`,
      rule: "dabei = bei dieser Sache / in diesem Zusammenhang", ex: "**Dabei** helfen wir Ihnen gern.", exTr: "في هذا نعاونوكم بكل سرور." },
  },

  // ───────────── [61] Die Internet-Hauptstadt Deutschlands ─────────────
  61: {
    31: { ok: "AN", type: "verb_prep", keyword: "sich anschließen an + Akk.", bed: "يلتحق بـ",
      text: `"ein offenes Rechnernetz herzustellen, ___ das sich immer weitere Teilnehmer anschließen konnten": "sich anschließen an" + Relativpronomen: "an das".\n✓ "an" = (sich anschließen an + Akkusativ: an das Netz).\n✗ "auf" = على، و"auf das … anschließen" ما تتقالش.\n✗ "darüber" = حول هذا (Pronominaladverb)، موش حرف جر قبل "das" الموصول.`,
      rule: "Präposition + Relativpronomen: an das (Netz), an das sich … anschließen", ex: "Das Netz, **an das** sich viele anschlossen, wuchs.", exTr: "الشبكة اللي التحقو بيها برشا كبرت." },
    32: { ok: "GEWORDEN", type: "tense", keyword: "war … geworden (werden)", bed: "صار",
      text: `"war ein elektronischer Postverband ___": "werden" = يصير، والـ Perfekt بـ "sein": "war … geworden".\n✓ "geworden" = صار (Partizip II من werden كفعل كامل).\n✗ "gewesen" = كان (من sein)، و"war … gewesen" معناها كان، موش تحوّل.\n✗ "worden" = Partizip II للـ Passiv فقط (ist … worden)، وما يجيش كفعل كامل.`,
      rule: "werden (Vollverb): ist … geworden  |  werden (Passiv): ist … worden", ex: "Aus dem Kind ist ein Mann **geworden**.", exTr: "من الصغير صار راجل." },
    33: { ok: "WORDEN", type: "tense", keyword: "ausgebaut worden (Passiv Perfekt)", bed: "تمّ",
      text: `"Karlsruhe ist … zum Knotenpunkt … ausgebaut ___": Passiv Perfekt: Partizip II + worden.\n✓ "worden" = (ist … ausgebaut worden).\n✗ "geworden" = صار (فعل كامل)، و"ausgebaut geworden" ما تتقالش في Passiv.\n✗ "gewesen" = كان، و"ausgebaut gewesen" ما يعطيش Passiv.`,
      rule: "Passiv Perfekt: ist + Partizip II + worden", ex: "Die Stadt ist ausgebaut **worden**.", exTr: "المدينة تمّ توسيعها." },
    34: { ok: "NICHT", type: "conjunction", keyword: "nicht nur … sondern auch", bed: "موش",
      text: `"Zu den ersten Kunden zählten aber ___ nur Universitäten …, sondern auch große Firmen": الزوج "nicht nur … sondern auch".\n✓ "nicht" = موش (nicht nur).\n✗ "doch" = لكن / فعلًا، و"aber doch nur Universitäten" ما تعطيش نفي.\n✗ "eigentlich" = في الحقيقة، و"aber eigentlich nur … sondern auch" ما تكمّلش الزوج.`,
      rule: "nicht nur A, sondern auch B", ex: "Er isst **nicht nur** Fleisch, sondern auch Gemüse.", exTr: "هو ياكل موش بس لحم، بل خضرة زادا." },
    35: { ok: "SONDERN", type: "conjunction", keyword: "nicht nur …, sondern auch …", bed: "بل",
      text: `"nicht nur Universitäten und Forschungseinrichtungen, ___ auch große Firmen": الجزء الثاني.\n✓ "sondern" = بل.\n✗ "doch" = لكن، وما تكمّلش "nicht nur … auch" هكا.\n✗ "übrigens" = على فكرة (ظرف)، موش رابط.`,
      rule: "sondern leitet den zweiten Teil von nicht nur … sondern auch ein", ex: "Nicht nur Kinder, **sondern** auch Erwachsene.", exTr: "موش بس الصغار، بل الكبار زادا." },
    36: { ok: "IN", type: "verb_prep", keyword: "sich verwandeln in + Akk.", bed: "يتحوّلو إلى",
      text: `"Die Briefschreiber von früher verwandelten sich ___ die Versender elektronischer Post": "sich verwandeln in" = يتحوّل إلى.\n✓ "in" = إلى (sich verwandeln in + Akkusativ).\n✗ "zu" = إلى: "sich zu die Versender" ما تتقالش (تحتاج Dativ "zu den Versendern").\n✗ "an" = عند / على، و"verwandeln sich an" ما تتقالش.`,
      rule: "sich in + Akk. verwandeln (= werden zu)", ex: "Die Raupe **verwandelt sich** in einen Schmetterling.", exTr: "الدودة تتحوّل إلى فراشة." },
    37: { ok: "DOCH", type: "conjunction", keyword: "doch (Position 0)", bed: "لكن",
      text: `"___ es gibt auch Stimmen, die Kritik … üben": تعارض مع الحماس، والفاعل "es" بعد الرابط مباشرة.\n✓ "doch" = لكن (Position 0، ما تقلبش الترتيب).\n✗ "eigentlich" = في الحقيقة (ظرف)، يقلب الترتيب ("Eigentlich gibt es …").\n✗ "übrigens" = على فكرة (ظرف)، يقلب الترتيب كذلك ("Übrigens gibt es …").`,
      rule: "doch / aber (Position 0) + Subjekt + Verb  |  Adverb → Verb + Subjekt", ex: "**Doch** es gibt ein Problem.", exTr: "لكن فما مشكل." },
    38: { ok: "DARAN", type: "pronoun_adverb", keyword: "Kritik üben an → daran, dass", bed: "على هذا",
      text: `"Stimmen, die Kritik ___ üben, dass die elektronische Post … geführt hat": "Kritik üben an" ← "daran" + dass-Satz.\n✓ "daran" = على هذا (an + das).\n✗ "darüber" = حول هذا (über + das): "Kritik darüber" ممكنة في الكلام، بصح مع "üben" المعتاد "an".\n✗ "auf" = على، و"Kritik auf üben" ما تتقالش.`,
      rule: "Kritik üben an + Dat. → daran Kritik üben, dass …", ex: "Er **übt** Kritik **daran**, dass nichts passiert.", exTr: "هو ينتقد إنّو ما يصيرش شي." },
    39: { ok: "ZU", type: "verb_prep", keyword: "führen zu + Dativ", bed: "أدّى إلى",
      text: `"die elektronische Post ___ einem Sprachgebrauch geführt hat": "führen zu" = أدّى إلى.\n✓ "zu" = إلى (führen zu + Dativ).\n✗ "in" = في، و"in einem Sprachgebrauch geführt" معناها دخل (حركة)، موش نتيجة.\n✗ "auf" = على، و"auf einem Sprachgebrauch geführt" ما تتقالش.`,
      rule: "zu + Dativ führen = bewirken", ex: "Das **führte** zu einem Streit.", exTr: "هذا أدّى إلى خلاف." },
    40: { ok: "AUF", type: "fixed_expression", keyword: "Wert legen auf + Akk.", bed: "يهتمّ بـ",
      text: `"Man lege keinen Wert mehr ___ den Ausdruck": تعبير ثابت: "Wert legen auf".\n✓ "auf" = على (Wert legen auf + Akkusativ).\n✗ "an" = عند / على، و"Wert legen an" ما تتقالش.\n✗ "über" = حول / فوق، و"Wert legen über" ما تتقالش.`,
      rule: "Wert legen auf + Akk. = etwas wichtig finden", ex: "Sie **legt** großen **Wert** auf Pünktlichkeit.", exTr: "هي تهتمّ برشا بالدقّة في المواعيد." },
  },

  // ───────────── [62] Vegetarisch essen ─────────────
  62: {
    31: { ok: "DEUTLICH", type: "adjective_adverb", keyword: "deutlich erhöht", bed: "بشكل ملحوظ",
      text: `"einen teilweise ___ erhöhten Nährstoffbedarf": ظرف درجة قبل الصفة "erhöhten".\n✓ "deutlich" = بشكل ملحوظ (deutlich erhöht).\n✗ "schwer" = صعيب / ثقيل، و"schwer erhöhten" ما تتقالش.\n✗ "beide" = الاثنين (ضمير)، موش ظرف درجة.`,
      rule: "deutlich + Partizip / Adjektiv = merklich (deutlich erhöht)", ex: "Der Bedarf ist **deutlich** gestiegen.", exTr: "الحاجة زادت بشكل ملحوظ." },
    32: { ok: "AUF", type: "preposition", keyword: "Auswirkungen auf + Akk.", bed: "على",
      text: `"keine Auswirkungen ___ das ungeborene Kind": "Auswirkungen auf" + Akkusativ.\n✓ "auf" = على (Auswirkung auf + Akk.).\n✗ "vor" = قبل / قدّام، و"Auswirkungen vor das Kind" ما تتقالش.\n✗ "an" = عند، و"Auswirkungen an das Kind" ما تتقالش.`,
      rule: "Auswirkungen / Einfluss / Folgen auf + Akk.", ex: "Das hat Auswirkungen **auf** die Gesundheit.", exTr: "هذا عندو تأثيرات على الصحّة." },
    33: { ok: "BEIDES", type: "pronoun", keyword: "beides (zwei Dinge)", bed: "الاثنين",
      text: `"Eier oder Milchprodukte oder sogar ___": الاثنين معًا (شيئين مختلفين) = "beides" (محايد).\n✓ "beides" = الاثنين (محايد، لحاجتين مختلفتين).\n✗ "beide" = الاثنين: ممكنة لجمع من نفس النوع، بصح "Eier" و"Milchprodukte" يختلفو، فيتقال "beides".\n✗ "essende" = ياكلو (Partizip I بنهاية)، موش ضمير.`,
      rule: "beides = zwei verschiedene Dinge (Neutrum)  |  beide = zwei gleichartige Personen / Dinge", ex: "Tee oder Kaffee? — **Beides**, bitte.", exTr: "تاي ولا قهوة؟ — الاثنين، بالله." },
    34: { ok: "DECKEN", type: "verb", keyword: "den Bedarf decken", bed: "يغطّو",
      text: `"den Bedarf der meisten Nährstoffe ___": "Bedarf decken" = يغطّي الحاجة.\n✓ "decken" = يغطّو (Infinitiv بعد "können").\n✗ "einsetzen" = يستعمل / يوظّف، و"Bedarf einsetzen" ما تتقالش.\n✗ "ersetzen" = يعوّض، و"Bedarf ersetzen" ما تعطيش معنى التغطية.`,
      rule: "den Bedarf decken = ausreichend versorgen", ex: "Die Ernte **deckt** den Bedarf.", exTr: "الحصاد يغطّي الحاجة." },
    35: { ok: "VOR", type: "verb", keyword: "vorkommen (kommen … vor)", bed: "يصير",
      text: `"kommen gerade Eisenmangelanämien bei Vegetariern nicht häufiger als bei Nichtvegetariern ___": الفعل المنفصل "vorkommen" = يظهر / يصير.\n✓ "vor" = (kommen … vor).\n✗ "an" = على / عند، و"kommen … an" معناها توصل، موش يظهر.\n✗ "auf" = على، و"kommen … auf" معنى آخر.`,
      rule: "trennbar: vorkommen → kommt … vor = auftreten", ex: "Diese Krankheit **kommt** selten **vor**.", exTr: "هذا المرض نادر يصير." },
    36: { ok: "STECKT", type: "verb", keyword: "stecken in (= enthalten sein)", bed: "موجود في",
      text: `"Folat … ___ zum Beispiel in Tomaten, Spinat": "in etwas stecken" = موجود فيها.\n✓ "steckt" = موجود (3. Person مفرد، stecken in).\n✗ "decken" = يغطّي (Infinitiv / جمع)، موش مفرد ولا معنى "موجود".\n✗ "ersetzen" = يعوّض (Infinitiv)، وما يعطيش معنى "موجود في".`,
      rule: "in etwas stecken = enthalten sein (Folat steckt in Spinat)", ex: "In dem Brot **steckt** viel Vitamin.", exTr: "في الخبز فما برشا فيتامين." },
    37: { ok: "ÜBERPRÜFEN", type: "verb", keyword: "überprüfen lassen", bed: "يتفحّص",
      text: `"ihren Nährstoffstatus regelmäßig ___ zu lassen": "überprüfen lassen" = يخلّو يتفحّص.\n✓ "überprüfen" = يفحص (Infinitiv: überprüfen zu lassen).\n✗ "ersetzen" = يعوّض، و"Status ersetzen zu lassen" معنى آخر.\n✗ "einsetzen" = يوظّف، وما يعطيش معنى فحص.`,
      rule: "etwas überprüfen lassen = kontrollieren lassen", ex: "Sie lässt ihr Auto **überprüfen**.", exTr: "هي تخلّي كرهبتها تتفحّص." },
    38: { ok: "AN", type: "verb", keyword: "ankommen auf (kommt … an)", bed: "يعتمد على",
      text: `"Außerdem kommt es auf die richtige Mischung der Lebensmittel ___": "es kommt auf etwas an" = يعتمد على (فعل منفصل).\n✓ "an" = (kommt … an).\n✗ "vor" = (kommt … vor = يصير)، معنى مختلف.\n✗ "auf" = موجودة قبل في "auf die Mischung"، وما تكمّلش الفعل المنفصل.`,
      rule: "trennbar: ankommen auf + Akk. → es kommt auf … an = es hängt von … ab", ex: "Es **kommt** auf die Zeit **an**.", exTr: "يعتمد على الوقت." },
    39: { ok: "ERSETZEN", type: "verb", keyword: "A durch B ersetzen", bed: "يعوّضو",
      text: `"den eisenreichen Gemüse-Kartoffel-Fleisch-Brei durch einen vegetarischen … Brei ___": "ersetzen durch" = يعوّض بـ.\n✓ "ersetzen" = يعوّض (A durch B ersetzen).\n✗ "einsetzen" = يوظّف / يستعمل، و"durch … einsetzen" ما تعني يعوّض.\n✗ "überprüfen" = يفحص، موش يعوّض.`,
      rule: "A durch B ersetzen = B anstelle von A nehmen", ex: "Man kann Zucker durch Honig **ersetzen**.", exTr: "الواحد ينجّم يعوّض السكّر بالعسل." },
    40: { ok: "ERNÄHRTE", type: "adjective_adverb", keyword: "vegetarisch ernährte Kinder", bed: "اللي تتغذّى",
      text: `"vegetarisch ___ Kinder": Partizip II كصفة (-e، Nominativ جمع): "ernährte Kinder" = أطفال يتغذّاو.\n✓ "ernährte" = متغذّين (Partizip II + -e).\n✗ "essende" = ياكلو (Partizip I): "vegetarisch essende Kinder" ممكنة، بصح "vegetarisch ernährte" هو التعبير المعتاد في سياق التغذية.\n✗ "schwer" = ثقيل / صعيب، و"vegetarisch schwer Kinder" ما تتقالش.`,
      rule: "vegetarisch ernährt (Zustand durch Ernährung)  |  essend = gerade beim Essen", ex: "Sie hat vegan **ernährte** Kinder.", exTr: "عندها أطفال تتغذّى نباتي." },
  },
};
