// SB Teil 2 restyle — batch 08: [37] Fische, [38] Sicherer Schulweg, [39] Schönschrift, [40] + [41] Handschrift (gaps 36/37 of [37] are DOCH/ÜBRIGENS — interchangeable → hedged)
export default {
  // ───────────── [37] Fische sind schlauer, als wir denken ─────────────
  37: {
    31: { ok: "GENAU", type: "adjective_adverb", keyword: "genau das Gegenteil", bed: "بالضبط",
      text: `"Doch ___ das Gegenteil ist der Fall": تأكيد: العكس تمامًا.\n✓ "genau" = بالضبط (genau das Gegenteil).\n✗ "deutlich" = بوضوح: ممكنة نحويًّا، بصح التعبير الثابت "genau das Gegenteil".\n✗ "noch" = لسّا، و"noch das Gegenteil" ما تتقالش.`,
      rule: "genau das Gegenteil = exakt das Gegenteil (Betonung)", ex: "Er sagt **genau** das Gegenteil.", exTr: "هو يقول بالضبط العكس." },
    32: { ok: "FÄHIG", type: "adjective_adverb", keyword: "fähig zu + Dativ", bed: "قادرين على",
      text: `"Sie sind … zu erstaunlichen kognitiven Leistungen ___": "fähig zu" = قادر على.\n✓ "fähig" = قادر (zu + Dativ).\n✗ "genau" = بالضبط (ظرف)، ما يكمّلش "zu … Leistungen".\n✗ "deutlich" = واضح (صفة)، و"zu Leistungen deutlich" ما تتقالش.`,
      rule: "zu etwas fähig sein = etwas können", ex: "Sie ist **fähig** zu großer Geduld.", exTr: "هي قادرة على صبر كبير." },
    33: { ok: "ENTWICKELTEN", type: "verb", keyword: "Fähigkeiten entwickeln", bed: "طوّرو",
      text: `"Im Laufe der Zeit ___ sie hochspezialisierte Sinnesfähigkeiten": تطوّر عبر الزمن.\n✓ "entwickelten" = طوّرو (Präteritum جمع من entwickeln).\n✗ "entwarfen" = صمّمو / رسمو خطّة (entwerfen)، موش تطوّر طبيعي.\n✗ "Beobachtung" = اسم (ملاحظة)، موش فعل.`,
      rule: "Fähigkeiten entwickeln = langsam ausbilden  |  entwerfen = planen / skizzieren", ex: "Die Tiere **entwickelten** neue Sinne.", exTr: "الحيوانات طوّرو حواسّ جديدة." },
    34: { ok: "BEOBACHTUNG", type: "noun", keyword: "durch Beobachtung lernen", bed: "الملاحظة",
      text: `"Einige Arten lernen durch ___": التعلّم بمراقبة الغير.\n✓ "Beobachtung" = الملاحظة / المراقبة (durch + Akk.).\n✗ "Betrachtung" = تأمّل / نظرة: ممكنة نحويًّا، بصح التعلّم بالمراقبة اسمو "Beobachtung".\n✗ "fähig" = قادر (صفة)، موش اسم بعد "durch".`,
      rule: "durch Beobachtung lernen  |  Betrachtung = ruhiges Anschauen", ex: "Kinder lernen **durch** Beobachtung.", exTr: "الصغار يتعلّمو بالملاحظة." },
    35: { ok: "NOCH", type: "adjective_adverb", keyword: "noch nicht einmal", bed: "حتى (ما)",
      text: `"wurde Fischen ___ nicht einmal zugetraut": "noch nicht einmal" = حتى ما.\n✓ "noch" = (noch nicht einmal = حتى بالكاد ما).\n✗ "genau" = بالضبط، و"genau nicht einmal" ما تتقالش.\n✗ "doch" = لكن / فعلًا، و"doch nicht einmal" ما تعطيش معنى التصعيد.`,
      rule: "noch nicht einmal = nicht einmal (Verstärkung der Verneinung)", ex: "Er kann **noch** nicht einmal laufen.", exTr: "هو حتى ما ينجّمش يمشي." },
    36: { ok: "ÜBRIGENS", type: "adjective_adverb", keyword: "übrigens (Nebenbemerkung)", bed: "على فكرة",
      text: `"Der Forscher bewies ___ auch als Erster, dass …": إضافة جانبية.\n✓ "übrigens" = على فكرة (ملاحظة جانبية).\n✗ "doch" = فعلًا / لكن: ممكنة ("bewies doch auch")، بصح "doch" مكانها الأنسب في 37 (تفتح سؤال بتعارض).\n✗ "denn" = خاطر: "denn auch" تعبير ممكن، بصح هنا نضيفو معلومة جانبية.`,
      rule: "übrigens = nebenbei bemerkt", ex: "Er ist **übrigens** auch Arzt.", exTr: "هو على فكرة طبيب زادا." },
    37: { ok: "DOCH", type: "conjunction", keyword: "Doch warum …? (Kontrast)", bed: "لكن",
      text: `"___ warum wurden die Fähigkeiten der Fische so lange unterschätzt?": سؤال بتناقض مع الاكتشافات.\n✓ "doch" = لكن (Position 0، تفتح سؤال بتعارض).\n✗ "übrigens" = على فكرة: ممكنة، بصح السؤال يعارض ما قبلو ("لكن علاش…") موش ملاحظة جانبية.\n✗ "denn" = خاطر: "Denn warum…" ممكنة، بصح "doch" أوضح للتعارض.`,
      rule: "Doch + Frage = Einwand / Kontrast zum Vorigen", ex: "**Doch** warum glaubt das niemand?", exTr: "لكن علاش ما يصدّق حتى واحد؟" },
    38: { ok: "FÜR", type: "preposition", keyword: "halten für + Akk.", bed: "يعتبر (ذكي)",
      text: `"___ intelligent halten wir oft nur Tiere, die uns ähnlich sind": "halten für" = يعتبر.\n✓ "für" = (etwas für intelligent halten).\n✗ "als" = كـ: "als intelligent halten" ما تتقالش (يتقال "halten für" أو "ansehen als").\n✗ "genau" = بالضبط، موش حرف جر.`,
      rule: "jdn. / etwas für + Adjektiv halten  |  als + Adjektiv ansehen", ex: "Ich halte das **für** unmöglich.", exTr: "نعتبر هذا مستحيل." },
    39: { ok: "ALS", type: "conjunction", keyword: "anders … als", bed: "من (في المقارنة)",
      text: `"mit ganz anderen Lebensbedingungen zurechtkommen ___ Tiere an Land": مقارنة بعد "anderen".\n✓ "als" = من (anders … als).\n✗ "noch" = لسّا، موش أداة مقارنة.\n✗ "für" = لـ، و"anderen … für Tiere" ما تفيدش مقارنة.`,
      rule: "anders / andere + … + als (Vergleich)", ex: "Hier ist es ganz anders **als** zu Hause.", exTr: "هنا مختلف تمامًا على الدار." },
    40: { ok: "WER", type: "pronoun", keyword: "wer … wolle, solle …", bed: "اللي",
      text: `"Allan rät, ___ mehr über Fische herausfinden wolle, solle …": جملة عامة: كلّ اللي.\n✓ "wer" = اللي / كلّ من (Konjunktiv I في الكلام المنقول).\n✗ "der" = ضمير موصول يحتاج اسم قبلو، وما فماش مرجع هنا.\n✗ "für" = لـ، موش ضمير.`,
      rule: "Wer … (wolle), der solle … = jeder, der … (indirekte Rede)", ex: "Er rät, **wer** sparen wolle, solle früh planen.", exTr: "ينصح، اللي يحب يوفّر لازمو يخطّط بكري." },
  },

  // ───────────── [38] Sicherer Schulweg ─────────────
  38: {
    31: { ok: "DESHALB", type: "adjective_adverb", keyword: "deshalb + Verb (Position 2)", bed: "لهذا السبب",
      text: `"Kinder sind oft … überfordert, ___ ist es wichtig …": نتيجة، والفعل "ist" بعد الظرف مباشرة.\n✓ "deshalb" = لهذا السبب (ظرف نتيجة، الفعل في الثانية).\n✗ "doch" = لكن (تعارض)، والمنطق هنا سبب ← نتيجة.\n✗ "statt" = عوض (حرف جر)، موش ظرف نتيجة.`,
      rule: "deshalb + Verb (Position 2) = Folge  |  doch = Gegensatz", ex: "Er ist müde, **deshalb** geht er früh.", exTr: "هو تعبان، لهذا يمشي بكري." },
    32: { ok: "NICHT", type: "adjective_adverb", keyword: "nicht immer", bed: "موش ديما",
      text: `"___ immer ist der kürzeste Weg auch der ungefährlichste": "nicht immer" = موش ديما.\n✓ "nicht" = موش (nicht immer).\n✗ "schon" = توّا / خلاص، و"Schon immer" معناها ديما من قبل، عكس المقصود.\n✗ "doch" = لكن / فعلًا، و"Doch immer ist" ما تعطيش نفي.`,
      rule: "nicht immer = manchmal nicht  |  schon immer = seit jeher", ex: "**Nicht** immer ist das einfach.", exTr: "موش ديما هذا سهل." },
    33: { ok: "KONZENTRIEREN", type: "verb_prep", keyword: "sich auf etwas konzentrieren", bed: "يركّز",
      text: `"sich voll auf das Kind ___": "sich konzentrieren auf" = يركّز على.\n✓ "konzentrieren" = يركّز (sich auf + Akk. konzentrieren).\n✗ "bemühen" = يجتهد: "sich bemühen um" (حرف "um")، و"auf das Kind bemühen" ما تتقالش.\n✗ "verhalten" = يتصرّف، وما يركّبش مع "auf das Kind".`,
      rule: "sich auf + Akk. konzentrieren  |  sich um + Akk. bemühen", ex: "Er **konzentriert** sich auf die Arbeit.", exTr: "هو يركّز على الخدمة." },
    34: { ok: "SELBST", type: "adjective_adverb", keyword: "sich selbst daran halten", bed: "بروحو",
      text: `"Verkehrsregeln nicht nur erklären, sondern sich auch ___ daran halten": تأكيد: هم نفسهم.\n✓ "selbst" = بروحو / هو نفسو (تأكيد).\n✗ "schon" = توّا / خلاص، و"sich auch schon daran halten" تغيّر المعنى (من الآن).\n✗ "nicht" = موش، وتقلب المعنى.`,
      rule: "selbst = persönlich (Betonung des Subjekts)", ex: "Er muss es **selbst** tun.", exTr: "لازم يعملها بروحو." },
    35: { ok: "HILFREICH", type: "adjective_adverb", keyword: "es ist hilfreich, wenn …", bed: "مفيد",
      text: `"Manchmal ist es ___, wenn die Großen sich … erzählen lassen": تقييم: مفيد.\n✓ "hilfreich" = مفيد (es ist hilfreich, wenn …).\n✗ "kritische" = صفة بنهاية (-e)، و"ist es kritische" ما تتقالش.\n✗ "selbstbewusst" = واثق من نفسو (يصف شخص)، موش موقف.`,
      rule: "es ist hilfreich / wichtig / sinnvoll, wenn …", ex: "Es ist **hilfreich**, wenn du Fragen stellst.", exTr: "مفيد إذا تسأل أسئلة." },
    36: { ok: "FÜR", type: "fixed_expression", keyword: "Schritt für Schritt", bed: "خطوة خطوة",
      text: `تعبير ثابت: "Schritt für Schritt" = خطوة بخطوة.\n✓ "für" = (Schritt für Schritt).\n✗ "statt" = عوض، و"Schritt statt Schritt" ما تتقالش.\n✗ "bemühen" = يجتهد (فعل)، موش حرف جر.`,
      rule: "Schritt für Schritt = allmählich (feste Wendung)", ex: "Wir lernen **Schritt** für Schritt.", exTr: "نتعلّمو خطوة خطوة." },
    37: { ok: "VERHALTEN", type: "noun", keyword: "das Verhalten im Straßenverkehr", bed: "السلوك",
      text: `"die wichtigsten Regeln für das ___ im Straßenverkehr": اسم من فعل: السلوك.\n✓ "Verhalten" = السلوك (اسم، محايد).\n✗ "Konzentrieren" = التركيز: ممكنة نحويًّا، بصح الجملة عن قواعد السلوك موش التركيز.\n✗ "Bemühen" = الاجتهاد، وما تتماشاش مع "قواعد … في الطريق".`,
      rule: "das Verhalten (substantivierter Infinitiv) = Benehmen", ex: "Es gelten Regeln für das **Verhalten** im Zug.", exTr: "فما قواعد للسلوك في التران." },
    38: { ok: "KRITISCHE", type: "adjective_adverb", keyword: "kritische Situationen", bed: "حرجة",
      text: `"noch mögliche ___ Situationen besprechen": صفة بنهاية -e قبل "Situationen" (جمع Akkusativ بعد "mögliche").\n✓ "kritische" = حرجة (Plural Akkusativ).\n✗ "selbstbewusst" = واثق، بدون نهاية، وما يصفش مواقف.\n✗ "Probleme" = اسم (مشاكل)، و"mögliche Probleme Situationen" ما تتقالش.`,
      rule: "mögliche + Adjektiv + -e (Plural Akk.)", ex: "Wir üben **kritische** Situationen.", exTr: "نتدرّبو على مواقف حرجة." },
    39: { ok: "SELBSTBEWUSST", type: "adjective_adverb", keyword: "sich selbstbewusst verhalten", bed: "بثقة",
      text: `"sich ___ im Straßenverkehr zu verhalten": ظرف طريقة: بثقة.\n✓ "selbstbewusst" = بثقة (Adjektiv كظرف).\n✗ "selbst" = بروحو: "sich selbst verhalten" ما تعطيش معنى "يتصرّف بثقة".\n✗ "hilfreich" = مفيد، وما يصفش طريقة التصرّف.`,
      rule: "sich + Adverb + verhalten (selbstbewusst, richtig, ruhig)", ex: "Sie verhält sich **selbstbewusst**.", exTr: "هي تتصرّف بثقة." },
    40: { ok: "LÖSUNGEN", type: "noun", keyword: "Lösungen finden", bed: "حلول",
      text: `"selbstständig ___ zu finden": المطلوب إيجاد حلول.\n✓ "Lösungen" = حلول (Lösungen finden).\n✗ "Probleme" = مشاكل: "Probleme finden" ممكنة نحويًّا، بصح الهدف تعلّم إيجاد الحلول.\n✗ "kritische" = صفة، وما تكمّلش "zu finden" بدون اسم.`,
      rule: "Lösungen finden (≠ Probleme finden)", ex: "Wir müssen **Lösungen** finden.", exTr: "لازمنا نلقاو حلول." },
  },

  // ───────────── [39] Schönschrift ist wieder "in" ─────────────
  39: {
    31: { ok: "WEIL", type: "conjunction", keyword: "weil + Nebensatz", bed: "خاطر",
      text: `"Das Handgelenk … schmerzt schnell, ___ Schreiben mit der Hand ungewohnt ist": سبب، والفعل "ist" في الآخر.\n✓ "weil" = خاطر (+ فعل في الآخر).\n✗ "dass" = إنّو (محتوى)، موش سبب.\n✗ "damit" = باش (غرض)، موش سبب.`,
      rule: "weil + Nebensatz = Grund  |  damit = Zweck", ex: "Er schläft, **weil** er müde ist.", exTr: "يرقد خاطر تعبان." },
    32: { ok: "IMMER", type: "adjective_adverb", keyword: "immer mehr", bed: "أكثر وأكثر",
      text: `"Kinder haben damit in der Schule ___ mehr Probleme": "immer mehr" = أكثر وأكثر.\n✓ "immer" = ديما (immer + Komparativ = تزايد).\n✗ "weil" = خاطر (رابط)، موش ظرف.\n✗ "damit" = بهذا / باش، وما تعطيش معنى التزايد.`,
      rule: "immer + Komparativ = stetige Steigerung (immer mehr, immer besser)", ex: "Es werden **immer** mehr.", exTr: "يولّيو أكثر وأكثر." },
    33: { ok: "TUN", type: "fixed_expression", keyword: "mit etwas zu tun haben", bed: "علاقة بـ",
      text: `"ein neuer Trend, der mit Handschrift zu ___ hat": تعبير ثابت: "zu tun haben" = عندو علاقة.\n✓ "tun" = (mit etwas zu tun haben).\n✗ "gestalten" = يصمّم، و"zu gestalten haben" معناها "لازمو يصمّم"، موش علاقة.\n✗ "suchen" = يلوّج، و"mit Handschrift zu suchen haben" ما تتقالش.`,
      rule: "mit etwas zu tun haben = in Beziehung stehen", ex: "Das hat nichts **mit** mir **zu tun**.", exTr: "هذا ما عندو علاقة بيّا." },
    34: { ok: "FIGUREN", type: "noun", keyword: "wie Figuren als wie Wörter", bed: "أشكال",
      text: `"die einzelnen Buchstaben eher wie ___ als wie Wörter empfunden werden": مقارنة بين "Figuren" و"Wörter" (جمع).\n✓ "Figuren" = أشكال / رسوم (اسم جمع).\n✗ "gestalten" = يصمّم (فعل)، موش اسم بعد "wie".\n✗ "spielerische" = صفة بنهاية، وما تجي وحدها بعد "wie" هكا.`,
      rule: "eher wie A als wie B = mehr A-ähnlich (Vergleich)", ex: "Die Zeichen wirken eher wie **Figuren**.", exTr: "الرموز تبان أكثر كأشكال." },
    35: { ok: "WERDEN", type: "tense", keyword: "empfunden werden (Passiv)", bed: "يتحسّو",
      text: `"die einzelnen Buchstaben … empfunden ___": Passiv جمع: Partizip II + werden.\n✓ "werden" = Passiv Präsens (جمع).\n✗ "geht" = مفرد (يمشي)، وما يكمّلش Passiv.\n✗ "tun" = يعمل (Infinitiv)، موش فعل مساعد.`,
      rule: "Vorgangspassiv: Partizip II + werden (Plural)", ex: "Die Zeichen **werden** gelesen.", exTr: "الرموز تتقرا." },
    36: { ok: "DAMIT", type: "pronoun_adverb", keyword: "Erfahrungen damit", bed: "بهذا",
      text: `"Erfahrungen ___ hat auch die Wiener Designerin … gemacht": "damit" = بالـ Lettering (ما ذكرناه قبل).\n✓ "damit" = بهذا (mit + das).\n✗ "für" = لـ، و"Erfahrungen für hat" ما تتقالش.\n✗ "von" = من: "Erfahrungen von" تحتاج اسم بعدها.`,
      rule: "Erfahrungen mit etwas → Erfahrungen damit", ex: "Ich habe gute Erfahrungen **damit** gemacht.", exTr: "عندي تجارب باهية بهذا." },
    37: { ok: "SPIELERISCHE", type: "adjective_adverb", keyword: "auf spielerische Weise", bed: "لعبية",
      text: `"Auf ___ Weise vermittelt die Künstlerin das Thema": "Weise" مؤنّث، بعد "auf" (Akkusativ) الصفة بـ -e.\n✓ "spielerische" = لعبية / بطريقة مرحة (-e: Akkusativ مؤنّث).\n✗ "gestalten" = يصمّم (فعل)، موش صفة قبل "Weise".\n✗ "Figuren" = أشكال (اسم)، وما يوصفش "Weise".`,
      rule: "auf + Adjektiv-e + Weise (auf spielerische Weise)", ex: "Er erklärt es auf einfache **Weise**.", exTr: "يشرحها بطريقة بسيطة." },
    38: { ok: "DASS", type: "conjunction", keyword: "ein Anliegen, dass …", bed: "إنّو",
      text: `"Der Künstlerin ist es ein Anliegen, ___ Kinder die Freude … wiederentdecken": محتوى الاهتمام.\n✓ "dass" = إنّو (+ فعل في الآخر).\n✗ "damit" = باش: "Anliegen, damit" ممكنة (غرض)، بصح بعد "es ist ein Anliegen" المعتاد "dass".\n✗ "weil" = خاطر (سبب)، موش محتوى.`,
      rule: "es ist (mir) ein Anliegen, dass + Nebensatz", ex: "Es ist mir wichtig, **dass** du kommst.", exTr: "يهمّني إنّك تجي." },
    39: { ok: "GESTALTEN", type: "verb", keyword: "Einladungen gestalten", bed: "تصمّم",
      text: `"coole Einladungen und Logos zu ___": المهارة: تصميم.\n✓ "gestalten" = يصمّم (Infinitiv بعد "zu").\n✗ "suchen" = يلوّج: "Logos zu suchen" ممكنة، بصح الجملة عن الإبداع (تصميم) موش البحث.\n✗ "tun" = يعمل، وما يعطيش معنى تصميم.`,
      rule: "etwas gestalten = kreativ formen (Einladungen, Logos, Räume)", ex: "Sie kann Plakate **gestalten**.", exTr: "هي تنجّم تصمّم ملصقات." },
    40: { ok: "GEHT", type: "verb", keyword: "von der Hand gehen", bed: "تمشي (بسلاسة)",
      text: `"bis ihnen das flüssig von der Hand ___": تعبير "von der Hand gehen" = تتعمل بسهولة، والفاعل مفرد "das".\n✓ "geht" = (es geht jdm. von der Hand، مفرد).\n✗ "tun" = يعمل (Infinitiv)، موش فعل مصرّف.\n✗ "werden" = يصير (جمع / Infinitiv)، وما يعطيش معنى "von der Hand gehen".`,
      rule: "etwas geht jdm. leicht von der Hand = gelingt mühelos", ex: "Die Arbeit **geht** ihm leicht von der Hand.", exTr: "الخدمة تمشي عندو بسهولة." },
  },

  // ───────────── [40] Wie Handschrift wieder cool wird ( Original ) ─────────────
  40: {
    31: { ok: "WEIL", type: "conjunction", keyword: "weil (Grund)", bed: "خاطر",
      text: `"Das Handgelenk … schmerzt schnell, ___ Schreiben mit der Hand ungewohnt ist": سبب.\n✓ "weil" = خاطر (+ فعل في الآخر).\n✗ "dass" = إنّو (محتوى)، موش سبب.\n✗ "damit" = باش (غرض)، موش سبب.`,
      rule: "weil + Nebensatz", ex: "Ich bleibe, **weil** es regnet.", exTr: "نقعد خاطر تشتي." },
    32: { ok: "IMMER", type: "adjective_adverb", keyword: "immer mehr Probleme", bed: "أكثر وأكثر",
      text: `"Kinder haben damit in der Schule ___ mehr Probleme": تزايد المشاكل.\n✓ "immer" = ديما (immer mehr = أكثر وأكثر).\n✗ "nie" = أبدًا: "nie mehr Probleme" = ما عادش مشاكل، وتناقض سياق الصعوبة.\n✗ "damit" = بهذا، موش ظرف تزايد.`,
      rule: "immer mehr = stetig zunehmend  |  nie mehr = nie wieder", ex: "Wir haben **immer** mehr Arbeit.", exTr: "عندنا أكثر وأكثر خدمة." },
    33: { ok: "TUN", type: "fixed_expression", keyword: "zu tun haben", bed: "علاقة",
      text: `"ein neuer Trend, der mit Handschrift zu ___ hat": "mit etwas zu tun haben".\n✓ "tun" = (zu tun haben).\n✗ "gestalten" = يصمّم، موش علاقة.\n✗ "suchen" = يلوّج، و"zu suchen hat" معناها لازمو يلوّج.`,
      rule: "mit + Dativ zu tun haben = zusammenhängen", ex: "Das hat damit **zu tun**.", exTr: "هذا عندو علاقة بيها." },
    34: { ok: "WURDE", type: "tense", keyword: "wurde + Partizip II (Passiv Singular)", bed: "كان يتعمل",
      text: `"wie es früher unterrichtet und von einigen auch gefürchtet ___": Passiv ماضي، والفاعل "es" مفرد.\n✓ "wurde" = Präteritum Passiv مفرد (unterrichtet und gefürchtet wurde).\n✗ "geht" = يمشي، وما يكمّلش Passiv.\n✗ "tun" = يعمل، موش فعل مساعد.`,
      rule: "Vorgangspassiv Präteritum: wurde + Partizip II", ex: "Früher **wurde** das anders gemacht.", exTr: "قبل كان يتعمل بطريقة أخرى." },
    35: { ok: "VON", type: "preposition", keyword: "Verbindung von A und B", bed: "بين (الاثنين)",
      text: `"Die Verbindung ___ Schrift und Bild": "Verbindung von … und …".\n✓ "von" = من / بين (Verbindung von + Dativ).\n✗ "für" = لـ، و"Verbindung für Schrift und Bild" معناها لأجل.\n✗ "damit" = بهذا (ظرف)، وبعدو اسم موش مرجع.`,
      rule: "Verbindung von A und B (Kombination zweier Dinge)", ex: "Die **Verbindung** von Text und Musik ist schön.", exTr: "الدمج بين النصّ والموسيقى جميل." },
    36: { ok: "DAMIT", type: "pronoun_adverb", keyword: "Erfahrungen damit", bed: "بهذا",
      text: `"Erfahrungen ___ hat auch die wiener Designerin … gemacht": "damit" = بالـ Lettering.\n✓ "damit" = بهذا (mit + das).\n✗ "von" = من، و"Erfahrungen von hat" ما تتقالش.\n✗ "für" = لـ، و"Erfahrungen für" ما تتقالش.`,
      rule: "Erfahrungen mit etwas machen → damit", ex: "Sie hat Erfahrungen **damit**.", exTr: "عندها تجارب بهذا." },
    37: { ok: "SPIELERISCHE", type: "adjective_adverb", keyword: "auf spielerische Weise", bed: "لعبية",
      text: `"Auf ___ Weise vermittelt die Künstlerin": "Weise" مؤنّث بعد "auf" ← -e.\n✓ "spielerische" = لعبية (Akkusativ مؤنّث).\n✗ "gestalten" = يصمّم (فعل)، موش صفة.\n✗ "figuren" = أشكال (اسم)، موش صفة.`,
      rule: "auf + Adjektiv + Weise: auf spielerische Weise", ex: "Sie lernt **auf spielerische** Weise.", exTr: "هي تتعلّم بطريقة لعبية." },
    38: { ok: "DASS", type: "conjunction", keyword: "Anliegen, dass", bed: "إنّو",
      text: `"ist es ein Anliegen, ___ Kinder die Freude … wieder entdecken": محتوى.\n✓ "dass" = إنّو.\n✗ "damit" = باش: ممكنة نحويًّا، بصح بعد "Anliegen" المعتاد "dass".\n✗ "das" = ضمير / أداة (حرف s واحد)، موش رابط.`,
      rule: "ein Anliegen, dass + Nebensatz", ex: "Mein Wunsch ist, **dass** alle gesund bleiben.", exTr: "أمنيتي إنّو الكلّ يبقى بصحّة." },
    39: { ok: "GESTALTEN", type: "verb", keyword: "gestalten", bed: "يصمّم",
      text: `"coole Einladungen und Logos zu ___": تصميم.\n✓ "gestalten" = يصمّم.\n✗ "suchen" = يلوّج، موش يصمّم.\n✗ "tun" = يعمل، ما يعطيش معنى تصميم.`,
      rule: "gestalten = kreativ entwerfen", ex: "Er **gestaltet** die Webseite.", exTr: "هو يصمّم موقع الويب." },
    40: { ok: "GEHT", type: "verb", keyword: "von der Hand gehen", bed: "تمشي",
      text: `"bis ihnen das flüssig von der Hand ___": الفاعل "das" مفرد.\n✓ "geht" = تمشي (von der Hand gehen).\n✗ "wurde" = Präteritum Passiv، و"von der Hand wurde" ما تتقالش.\n✗ "tun" = Infinitiv، موش فعل مصرّف.`,
      rule: "von der Hand gehen = mühelos gelingen", ex: "Das **geht** ihm leicht von der Hand.", exTr: "هذا يمشي عندو بسهولة." },
  },

  // ───────────── [41] Wie Handschrift wieder cool wird (معدل) ─────────────
  41: {
    31: { ok: "WEIL", type: "conjunction", keyword: "weil", bed: "خاطر",
      text: `"Das Handgelenk … schmerzt relativ schnell, ___ Handschrift ungewohnt ist": سبب.\n✓ "weil" = خاطر.\n✗ "dass" = إنّو، موش سبب.\n✗ "damit" = باش، موش سبب.`,
      rule: "weil = Grund (Verb am Ende)", ex: "Er fehlt, **weil** er krank ist.", exTr: "هو غايب خاطر مريض." },
    32: { ok: "IMMER", type: "adjective_adverb", keyword: "immer mehr", bed: "أكثر وأكثر",
      text: `"haben mit dem Schreiben in der Schule ___ mehr Probleme": تزايد.\n✓ "immer" = (immer mehr).\n✗ "nie" = أبدًا، و"nie mehr Probleme" = ما عادش مشاكل (عكس السياق).\n✗ "damit" = بهذا، موش ظرف.`,
      rule: "immer + Komparativ = stetig mehr", ex: "Es gibt **immer** weniger Zeit.", exTr: "الوقت يقلّ أكثر وأكثر." },
    33: { ok: "TUN", type: "fixed_expression", keyword: "mit … zu tun haben", bed: "علاقة",
      text: `"ein neuer Trend, der mit Handschrift zu ___ hat": علاقة.\n✓ "tun" = (zu tun haben).\n✗ "suchen" = يلوّج، و"mit Handschrift zu suchen hat" ما تتقالش.\n✗ "gestalten" = يصمّم، موش علاقة.`,
      rule: "mit etwas zu tun haben", ex: "Was hat das **mit** uns **zu tun**?", exTr: "شنوّة علاقة هذا بينا؟" },
    34: { ok: "DAMIT", type: "pronoun_adverb", keyword: "Erfahrungen damit", bed: "بهذا",
      text: `"Erfahrungen ___ hat die Wiener Designerin … gemacht": "damit" = مع الـ Lettering.\n✓ "damit" = بهذا (mit + das).\n✗ "dass" = إنّو (رابط)، موش ضمير ظرفي.\n✗ "für" = لـ، و"Erfahrungen für hat" ما تتقالش.`,
      rule: "Erfahrungen mit etwas → damit", ex: "Wir haben gute Erfahrungen **damit**.", exTr: "عندنا تجارب باهية بهذا." },
    35: { ok: "SPIELERISCHE", type: "adjective_adverb", keyword: "spielerische Weise", bed: "لعبية",
      text: `"Auf ___ Weise vermittelt die Künstlerin": صفة مؤنّث.\n✓ "spielerische" = لعبية (-e).\n✗ "figuren" = اسم (أشكال)، موش صفة.\n✗ "gestalten" = فعل، موش صفة.`,
      rule: "auf + Adjektiv-e + Weise", ex: "Er lehrt **auf spielerische** Weise.", exTr: "هو يعلّم بطريقة لعبية." },
    36: { ok: "DASS", type: "conjunction", keyword: "wichtig, dass", bed: "إنّو",
      text: `"ist wichtig, ___ Kinder die Freude am Schreiben wiederentdecken": محتوى.\n✓ "dass" = إنّو.\n✗ "damit" = باش: ممكنة نحويًّا (غرض)، بصح بعد "wichtig" المعتاد "dass".\n✗ "das" = أداة / ضمير، موش رابط.`,
      rule: "(es ist) wichtig, dass + Nebensatz", ex: "Es ist wichtig, **dass** alle mitmachen.", exTr: "المهم إنّو الكلّ يشارك." },
    37: { ok: "SUCHEN", type: "verb", keyword: "suchen (zu beurteilen und zu suchen)", bed: "يلوّج",
      text: `"die eigene Handschrift zu beurteilen und zu ___, zu entwickeln": Infinitiv ثاني بعد "zu": يلوّج على خطّو.\n✓ "suchen" = يلوّج (zu + Infinitiv).\n✗ "gestalten" = يصمّم: ممكنة نحويًّا، بصح "suchen … entwickeln" تتسلسل مع (beurteilen → suchen → entwickeln).\n✗ "tun" = يعمل، ما يتماشاش مع "die eigene Handschrift".`,
      rule: "zu + Infinitiv-Reihe: zu beurteilen, zu suchen, zu entwickeln", ex: "Er versucht, Fehler zu finden und zu **suchen**.", exTr: "يحاول يلقى ويلوّج على الغلطات." },
    38: { ok: "GEHT", type: "verb", keyword: "von der Hand gehen", bed: "تمشي",
      text: `"bis ihnen das flüssig von der Hand ___": فاعل مفرد.\n✓ "geht" = تمشي (von der Hand gehen).\n✗ "wurde" = Passiv ماضي، موش مع "von der Hand".\n✗ "tun" = Infinitiv، موش فعل مصرّف.`,
      rule: "etwas geht jdm. von der Hand = es gelingt mühelos", ex: "Es **geht** ihr leicht von der Hand.", exTr: "هذا يمشي عندها بسهولة." },
    39: { ok: "VON", type: "preposition", keyword: "Verbindung von … und …", bed: "بين",
      text: `"Die Verbindung ___ Schrift und Bild lässt sich auch im Alltag anwenden": "Verbindung von … und …".\n✓ "von" = بين (Verbindung von A und B).\n✗ "für" = لـ، موش معنى الجمع.\n✗ "damit" = بهذا، وبعدو اسم.`,
      rule: "Verbindung von A und B", ex: "Die **Verbindung** von Tradition und Moderne.", exTr: "الدمج بين التقليد والحداثة." },
    40: { ok: "WURDE", type: "tense", keyword: "wurde + Partizip II", bed: "كان",
      text: `"wie es früher unterrichtet und von einigen auch gefürchtet ___": Passiv ماضي.\n✓ "wurde" = (unterrichtet … gefürchtet wurde).\n✗ "geht" = يمشي، موش Passiv.\n✗ "tun" = Infinitiv، موش فعل مساعد.`,
      rule: "wurde + Partizip II (Präteritum Passiv)", ex: "Es **wurde** früher so gelehrt.", exTr: "كان يتعلّم هكا قبل." },
  },
};
