// SB Teil 2 restyle — batch 10: [47] Lernen (معدل), [49] Songwettbewerb, [50] Crowdfunding, [51] Schnell und schneller. ([48] "Garten in der Stadt" is HELD: its stored passage is garbled — see notes.)
export default {
  // ───────────── [47] Lernen ist kein Privileg der Jugend (معدل) ─────────────
  47: {
    31: { ok: "NUTZEN", type: "verb", keyword: "die Chance nutzen", bed: "يستغلّو",
      text: `"Senioren sind … rege, aktiv und ___ vielfach die Chance": فعل مصرّف جمع بعد "und" (فاعل "Senioren").\n✓ "nutzen" = يستغلّو (3. Person جمع، die Chance nutzen).\n✗ "angeboten" = Partizip II (عُرض)، موش فعل مصرّف.\n✗ "erwachsen" = كبير (صفة) أو ينشأ: وما تركّبش مع "die Chance" بهذا المعنى.`,
      rule: "die Chance nutzen = eine Gelegenheit ergreifen", ex: "Viele **nutzen** die Chance zum Lernen.", exTr: "برشا يستغلّو فرصة التعلّم." },
    32: { ok: "ANGEBOTEN", type: "tense", keyword: "angeboten wird (Passiv)", bed: "يتقدّم",
      text: `"wie es an verschiedenen deutschen Universitäten ___ wird": Passiv: Partizip II + wird.\n✓ "angeboten" = Partizip II من "anbieten".\n✗ "nutzen" = Infinitiv / جمع، وقبل "wird" نحتاج Partizip II.\n✗ "erwachsen" = كبير / Partizip من "erwachsen"، وما يعطيش معنى يتقدّم.`,
      rule: "Passiv Präsens: wird + Partizip II (angeboten)", ex: "Das Studium **wird** online **angeboten**.", exTr: "الدراسة تتقدّم أونلاين." },
    33: { ok: "ALS", type: "preposition", keyword: "als Gasthörer eingeschrieben", bed: "كـ (مستمع حرّ)",
      text: `"als Gasthörer eingeschrieben": الصفة اللي سجّلو بيها: "als + Nomen".\n✓ "als" = كـ (als Gasthörer).\n✗ "für" = لـ: "für Gasthörer eingeschrieben" ممكنة (مخصّص لهم)، بصح الجملة تحكي على صفتهم هم.\n✗ "an" = عند / في، و"an Gasthörer eingeschrieben" ما تتقالش.`,
      rule: "als + Nomen = in der Rolle von (als Gast, als Student)", ex: "Er arbeitet **als** Lehrer.", exTr: "يخدم كمعلّم." },
    34: { ok: "DAGEGEN", type: "adjective_adverb", keyword: "dagegen (Kontrast)", bed: "بالمقابل",
      text: `"Angebote aus den Sozial-, Wirtschafts- … wurden ___ weniger häufig gewählt": مقابلة مع العلوم الإنسانية اللي كانت مطلوبة برشا.\n✓ "dagegen" = بالمقابل (ظرف تعارض).\n✗ "daher" = لهذا السبب (نتيجة)، موش مقابلة.\n✗ "darauf" = بعد هذا / على هذا، موش تعارض.`,
      rule: "dagegen = im Gegensatz dazu  |  daher = deshalb", ex: "Mathe war leicht, Physik **dagegen** schwer.", exTr: "الرياضيات كانت سهلة، والفيزياء بالمقابل صعيبة." },
    35: { ok: "KÖNNTEN", type: "verb", keyword: "könnten (Möglichkeit)", bed: "ممكن يكونو",
      text: `"Die Gründe dafür ___ sein, dass Frauen …": تخمين: "ممكن" (Konjunktiv II جمع).\n✓ "könnten" = ممكن (Möglichkeit، جمع).\n✗ "nutzen" = يستغلّو، و"Gründe nutzen sein" ما تتقالش.\n✗ "angeboten" = Partizip II، موش فعل مساعد.`,
      rule: "könnten + Infinitiv = mögliche Erklärung", ex: "Die Ursachen **könnten** vielfältig sein.", exTr: "الأسباب ممكن تكون متنوّعة." },
    36: { ok: "FÜR", type: "verb_prep", keyword: "sich einsetzen für + Akk.", bed: "يدافعو عن",
      text: `"Stattdessen setzen sie sich ___ die Familie und ihre Kinder ein": "sich einsetzen für" = يدافع على / يخدم لأجل.\n✓ "für" = (sich einsetzen für + Akkusativ).\n✗ "an" = على / عند، و"sich an die Familie einsetzen" ما تتقالش.\n✗ "auf" = على، و"sich auf … einsetzen" ما تتقالش بهذا المعنى.`,
      rule: "sich für + Akk. einsetzen = sich engagieren für", ex: "Sie **setzt sich** für Tiere **ein**.", exTr: "هي تدافع على الحيوانات." },
    37: { ok: "ERWACHSEN", type: "adjective_adverb", keyword: "erwachsen sein", bed: "كبار",
      text: `"Wenn die Kinder ___ und aus dem Haus sind": الأولاد كبرو.\n✓ "erwachsen" = كبار / بالغين (صفة بعد "sind").\n✗ "angeboten" = Partizip II (عُرض)، ما يتماشاش مع "Kinder … sind".\n✗ "einige" = بعض (Pronomen)، موش صفة بعد "sind" بهذا المعنى.`,
      rule: "erwachsen sein = kein Kind mehr sein", ex: "Seine Kinder sind schon **erwachsen**.", exTr: "أولادو كبرو." },
    38: { ok: "WÄHREND", type: "preposition", keyword: "während + Genitiv", bed: "أثناء",
      text: `"häufiger ___ ihres Arbeitslebens ihre Karriere verwirklichen": زمن: أثناء حياتهم المهنية (Genitiv "ihres Arbeitslebens").\n✓ "während" = أثناء (+ Genitiv).\n✗ "aufgrund" = بسبب (+ Genitiv)، المعنى هنا زمن موش سبب.\n✗ "allein" = وحدو / فقط، وما يركّبش قبل Genitiv هكا.`,
      rule: "während + Genitiv (Zeit)  |  aufgrund + Genitiv (Grund)", ex: "**Während** des Studiums arbeitete er viel.", exTr: "أثناء الدراسة خدم برشا." },
    39: { ok: "DAHER", type: "adjective_adverb", keyword: "daher + Verb", bed: "لهذا السبب",
      text: `"___ sehen sie keine Veranlassung": نتيجة، والفعل "sehen" بعد الظرف.\n✓ "daher" = لهذا السبب (ظرف نتيجة، الفعل في الثانية).\n✗ "dagegen" = بالمقابل: ممكنة، بصح الجملة هنا نتيجة لما سبق، وكلمة "dagegen" مكانها 34.\n✗ "darauf" = على هذا / بعد هذا، وما تعطيش معنى النتيجة.`,
      rule: "daher = deshalb (Folge, Verb Position 2)", ex: "Es regnet, **daher** bleiben wir drin.", exTr: "تشتي، لهذا نقعدو لداخل." },
    40: { ok: "EINIGE", type: "pronoun", keyword: "einige + Plural", bed: "بعض",
      text: `"neues Wissen zu erwerben, ___ Kompetenzen zu entwickeln": كمّية غير محدّدة + جمع (Akkusativ).\n✓ "einige" = بعض (Plural Akkusativ).\n✗ "allein" = وحدو، موش كمّية.\n✗ "auf" = على (حرف جر)، موش بعد "zu erwerben,".`,
      rule: "einige + Plural-Nomen = mehrere / ein paar", ex: "Er hat **einige** Ideen.", exTr: "عندو بعض الأفكار." },
  },

  // ───────────── [49] Songwettbewerb auf der Burg Tanneck ─────────────
  49: {
    31: { ok: "MUSSTE", type: "verb", keyword: "musste … denken", bed: "لازمني",
      text: `"habe ich gestern … gefunden und ___ gleich an euch denken": "musste denken" = ما نجّمتش ما نفكّرش (حسّ قوي).\n✓ "musste" = لازمني (Präteritum، 1. Person مفرد).\n✗ "durfte" = مسموحلي، و"durfte an euch denken" ما تعطيش الحسّ المقصود.\n✗ "hätte" = Konjunktiv II من "haben"، ويحتاج Partizip II، موش Infinitiv "denken".`,
      rule: "(gleich) an jdn. denken müssen = unwillkürlich an jdn. denken", ex: "Ich **musste** sofort an dich denken.", exTr: "لازمني على طول نفكّر فيك." },
    32: { ok: "BEIDE", type: "pronoun", keyword: "euch beide", bed: "إنتوما الزوز",
      text: `"an euch ___ denken": "euch beide" = إنتوما الاثنين (Akkusativ).\n✓ "beide" = الاثنين (Akkusativ جمع).\n✗ "die" = أداة / ضمير موصول، و"an euch die denken" ما تتقالش.\n✗ "wisst" = فعل (ihr wisst)، موش ضمير.`,
      rule: "euch beide = ihr beide (Akkusativ)", ex: "Ich lade euch **beide** ein.", exTr: "نعزمكم الزوز." },
    33: { ok: "DIE", type: "pronoun", keyword: "Relativpronomen Plural: die", bed: "اللي",
      text: `"wunderbare Abende, ___ wir im letzten Urlaub … verbracht haben": مرجعو "Abende" (جمع)، ومفعول به في الجملة الفرعية.\n✓ "die" = اللي (Relativpronomen Nominativ / Akkusativ جمع).\n✗ "als" = وقتما / كـ، و"Abende, als wir … verbracht haben" يبقى ناقص مفعول به.\n✗ "wenn" = إذا (شرط)، موش ضمير موصول.`,
      rule: "Relativpronomen Plural Nom. / Akk.: die", ex: "Das sind die Tage, **die** ich liebe.", exTr: "هذي الأيّام اللي نحبّها." },
    34: { ok: "WÄRE", type: "tense", keyword: "Wie wäre es, …? (Vorschlag)", bed: "كيفاش تشوفو",
      text: `"Wie ___ es, hättet ihr nicht mal Lust …?": اقتراح مؤدّب: "Wie wäre es …?".\n✓ "wäre" = Konjunktiv II من "sein" (Wie wäre es?).\n✗ "hätte" = Konjunktiv II من "haben"، و"Wie hätte es" ما تتقالش.\n✗ "kennt" = Präsens من "kennen"، موش اقتراح.`,
      rule: "Wie wäre es, wenn … / Wie wäre es mit …? = Vorschlag", ex: "**Wie wäre es** mit einem Kaffee?", exTr: "كيفاش تشوف في قهوة؟" },
    35: { ok: "SCHON", type: "adjective_adverb", keyword: "schon seit", bed: "من (برشا)",
      text: `"Ich kenne die Burg Tanneck ___ seit meiner Kindheit": تأكيد على طول المدّة: "schon seit".\n✓ "schon" = ديجا / من (schon seit = من زمان).\n✗ "erst" = غير توّا: "erst seit meiner Kindheit" ممكنة، بصح "schon" تعبّر على مدّة طويلة.\n✗ "überhaupt" = أصلًا / بالمرّة، وما تتركّبش مع "seit" هكا.`,
      rule: "schon seit = bereits lange  |  erst seit = noch nicht lange", ex: "Ich wohne **schon** seit Jahren hier.", exTr: "نسكن هنا من سنين." },
    36: { ok: "ÜBERHAUPT", type: "adjective_adverb", keyword: "überhaupt nichts", bed: "أصلًا (ما)",
      text: `"hat ___ nichts mit Kommerz … zu tun": تشديد النفي: "überhaupt nichts".\n✓ "überhaupt" = بالمرّة (überhaupt nichts = ما عندو حتى علاقة).\n✗ "schon" = ديجا، و"schon nichts" ما تتقالش.\n✗ "bald" = قريبًا، وما تعطيش معنى تشديد النفي.`,
      rule: "überhaupt nicht / nichts / kein = verstärkte Verneinung", ex: "Das hat **überhaupt** nichts damit zu tun.", exTr: "هذا ما عندو أصلًا علاقة بهذا." },
    37: { ok: "KENNT", type: "verb", keyword: "man kennt (aus dem Fernsehen)", bed: "يعرف",
      text: `"wie man es sonst aus dem Fernsehen ___": الفاعل "man" (3. Person مفرد).\n✓ "kennt" = يعرف (man kennt).\n✗ "wisst" = (ihr wisst، 2. Person جمع)، ما يطابقش "man".\n✗ "hätte" = Konjunktiv II، موش حقيقة (يعرف).`,
      rule: "man + 3. Person Singular: man kennt, man weiß", ex: "Wie man es aus dem Kino **kennt**.", exTr: "كيما الواحد يعرفها من السينما." },
    38: { ok: "DARUM", type: "pronoun_adverb", keyword: "es geht darum, … zu", bed: "المسألة هي",
      text: `"Es geht nur ___, Spaß zu haben und zu singen": "es geht um" ← "darum" + zu-Infinitiv.\n✓ "darum" = (es geht darum، um + das).\n✗ "bald" = قريبًا، و"es geht nur bald" ما تتقالش.\n✗ "wenn" = إذا (رابط)، موش ضمير ظرفي.`,
      rule: "es geht um + Akk. → es geht darum, … zu + Infinitiv", ex: "Es geht **darum**, gemeinsam zu lachen.", exTr: "المسألة هي نضحكو مع بعضنا." },
    39: { ok: "WENN", type: "conjunction", keyword: "auch wenn", bed: "حتى لو",
      text: `"auch ___ ihr nur den anderen Sängern zuhören wollt": "auch wenn" = حتى لو.\n✓ "wenn" = (auch wenn + فعل في الآخر).\n✗ "als" = وقتما (ماضي مرة وحدة)، و"auch als ihr … wollt" ما تتقالش.\n✗ "erst" = غير توّا، موش رابط.`,
      rule: "auch wenn = selbst falls  |  als = einmalig in der Vergangenheit", ex: "Komm, **auch wenn** du müde bist.", exTr: "جي حتى لو تعبان." },
    40: { ok: "BALD", type: "adjective_adverb", keyword: "bald von sich hören lassen", bed: "قريب",
      text: `"Lasst ___ was von euch hören!": طلب بسرعة: قريب.\n✓ "bald" = قريب (Lasst bald von euch hören).\n✗ "erst" = غير توّا، و"Lasst erst was hören" ما تعطيش معنى.\n✗ "schon" = ديجا: "Lasst schon was hören" ممكنة (تشجيع)، بصح "bald" هي المعتادة في ختام الرسالة.`,
      rule: "Lasst bald von euch hören! = Bitte meldet euch bald", ex: "Melde dich **bald**!", exTr: "عيّطلي قريب!" },
  },

  // ───────────── [50] Crowdfunding boomt, Print lebt ─────────────
  50: {
    31: { ok: "vorstellen", type: "verb", keyword: "ein Tool vorstellen", bed: "يقدّمو",
      text: `"freien Journalisten, die in Perugia ihr Start-up oder ein Technik-Tool ___": فعل جمع في الآخر: يقدّمو.\n✓ "vorstellen" = يقدّمو (Infinitiv / جمع، vorstellen).\n✗ "ergeben" = يعطي / يؤدّي إلى، و"ein Tool ergeben" ما تعطيش معنى التقديم.\n✗ "bereit" = جاهز (صفة)، موش فعل.`,
      rule: "etwas vorstellen = präsentieren", ex: "Sie **stellen** ihr Projekt **vor**.", exTr: "يقدّمو مشروعهم." },
    32: { ok: "ebenfalls", type: "adjective_adverb", keyword: "ebenfalls (auch)", bed: "كذلك",
      text: `"die Einbindung von Video … war ___ ein Schwerpunktthema": زيادة موضوع ثاني: كذلك.\n✓ "ebenfalls" = كذلك (auch).\n✗ "eigentlich" = في الحقيقة: ممكنة ("war eigentlich ein Schwerpunktthema")، بصح الجملة تضيف موضوع آخر.\n✗ "sogleich" = على طول، وما تعطيش معنى الإضافة.`,
      rule: "ebenfalls = auch / genauso", ex: "Er kommt **ebenfalls** zur Feier.", exTr: "هو يجي كذلك للحفلة." },
    33: { ok: "davor", type: "pronoun_adverb", keyword: "die Jahre davor", bed: "قبلها",
      text: `"Im Gegensatz zu den Jahren ___": "die Jahre davor" = السنوات اللي قبل.\n✓ "davor" = قبلها (ظرف زمني بعد الاسم).\n✗ "vor" = قبل (حرف جر)، ويحتاج اسم بعدو ("vor den Jahren").\n✗ "durch" = عبر، موش ظرف زمني.`,
      rule: "die Jahre davor = die vorherigen Jahre (nachgestellt)", ex: "Im Jahr **davor** war es kälter.", exTr: "في السنة اللي قبلها كان أبرد." },
    34: { ok: "vielmehr", type: "adjective_adverb", keyword: "nicht …, vielmehr …", bed: "بالأحرى",
      text: `"nicht mehr darüber diskutiert, ob …, ___ wurde das … als gegeben angenommen": بعد النفي نقولو "بالأحرى" + الفعل في الثانية.\n✓ "vielmehr" = بالأحرى (ظرف + فعل في الثانية).\n✗ "zwar" = صحيح (zwar … aber)، رابط تنازل.\n✗ "obwohl" = رغم إنّو (رابط جملة فرعية + فعل في الآخر)، وهنا "wurde" في الثانية.`,
      rule: "nicht A, vielmehr B (Verb Position 2)", ex: "Es ist nicht schlecht, **vielmehr** gut.", exTr: "موش سيّء، بالأحرى باهي." },
    35: { ok: "vor", type: "verb", keyword: "vorherrschen (herrschte … vor)", bed: "كان سائد",
      text: `"herrschte viel Optimismus ___": الفعل المنفصل "vorherrschen" = كان سائد.\n✓ "vor" = (herrschte … vor).\n✗ "davor" = قبلها (ظرف)، موش جزء من الفعل المنفصل.\n✗ "durch" = عبر، موش جزء من "vorherrschen".`,
      rule: "trennbar: vorherrschen → herrschte … vor (dominant sein)", ex: "Hier **herrscht** Ruhe **vor**.", exTr: "هنا الهدوء سائد." },
    36: { ok: "bereit", type: "adjective_adverb", keyword: "bereit sein, … zu", bed: "مستعدّين",
      text: `"Bürger sind … immer mehr ___, in journalistische Projekte zu investieren": "bereit sein zu".\n✓ "bereit" = مستعدّ (bereit sein, … zu + Infinitiv).\n✗ "erfolgreich" = ناجح، و"erfolgreich, … zu investieren" ما تعطيش معنى الاستعداد.\n✗ "eigentlich" = في الحقيقة (ظرف)، و"immer mehr eigentlich" ما تتقالش.`,
      rule: "bereit sein, … zu + Infinitiv = willens sein", ex: "Er ist **bereit**, zu helfen.", exTr: "هو مستعدّ يعاون." },
    37: { ok: "wohl", type: "adjective_adverb", keyword: "das wohl bekannteste (Vermutung)", bed: "على الأرجح",
      text: `"ist das ___ bekannteste Modell in Europa": تخمين مخفّف: على الأرجح.\n✓ "wohl" = على الأرجح (Superlativ مخفّف).\n✗ "eigentlich" = في الحقيقة: ممكنة ("das eigentlich bekannteste")، بصح "wohl" تعبّر على تخمين.\n✗ "zwar" = صحيح (zwar … aber)، رابط تنازل.`,
      rule: "wohl + Superlativ = vermutlich der / die / das …ste", ex: "Das ist **wohl** das beste Buch.", exTr: "هذا على الأرجح أحسن كتاب." },
    38: { ok: "durch", type: "preposition", keyword: "durch Crowdfunding finanzieren", bed: "عبر",
      text: `"die vor kurzem an den Start gegangen sind und ___ Crowdfunding finanziert werden": الوسيلة: عبر.\n✓ "durch" = عبر / بواسطة (durch + Akkusativ).\n✗ "damit" = بهذا / باش (رابط)، و"und damit Crowdfunding finanziert werden" ما تتماشاش.\n✗ "obwohl" = رغم إنّو (رابط جملة فرعية)، موش حرف جر.`,
      rule: "durch + Akk. = Mittel (durch Crowdfunding finanziert)", ex: "Das Projekt wird **durch** Spenden finanziert.", exTr: "المشروع يتموّل عبر التبرّعات." },
    39: { ok: "erfolgreich", type: "adjective_adverb", keyword: "sich erfolgreich behaupten", bed: "بنجاح",
      text: `"und sich ___ behaupten": ظرف: بنجاح.\n✓ "erfolgreich" = بنجاح (sich erfolgreich behaupten = يفرض روحو).\n✗ "ebenfalls" = كذلك: ممكنة ("sich ebenfalls behaupten")، بصح الجملة تحكي على نجاحهم.\n✗ "bereit" = مستعدّ، وما تركّبش مع "sich … behaupten".`,
      rule: "sich erfolgreich behaupten = sich durchsetzen", ex: "Die Firma **behauptet** sich erfolgreich.", exTr: "الشركة تفرض روحها بنجاح." },
    40: { ok: "damit", type: "pronoun_adverb", keyword: "damit verbunden sein", bed: "بهذا (مربوط)",
      text: `"weil ___ ein Qualitätsanspruch verbunden ist": "verbunden mit" ← "damit".\n✓ "damit" = بهذا (mit + das: damit verbunden).\n✗ "davor" = قبلها (vor + das)، و"davor verbunden" ما تتقالش.\n✗ "vor" = قبل (حرف جر)، ويحتاج اسم بعدو.`,
      rule: "mit etwas verbunden sein → damit verbunden sein", ex: "Es ist viel Arbeit **damit** verbunden.", exTr: "فما برشا خدمة مربوطة بهذا." },
  },

  // ───────────── [51] Schnell und schneller ─────────────
  51: {
    31: { ok: "WÄRE", type: "tense", keyword: "wäre (Konjunktiv II)", bed: "ستكون",
      text: `"Eine Geschwindigkeitsbegrenzung … ___ in Deutschland aber eine fast undenkbare Idee": افتراض: Konjunktiv II من "sein".\n✓ "wäre" = Konjunktiv II (افتراض).\n✗ "sei" = Konjunktiv I (كلام منقول)، وما فماش نقل كلام هنا.\n✗ "würde" = تحتاج Infinitiv ("würde … sein")، وما تتركّبش مباشرة قبل اسم.`,
      rule: "Konjunktiv II von sein: wäre = Annahme / Irrealis", ex: "Das **wäre** eine gute Idee.", exTr: "هذي تكون فكرة باهية." },
    32: { ok: "DAFÜR", type: "pronoun_adverb", keyword: "Grund dafür, dass …", bed: "لهذا",
      text: `"Ein Grund ___, dass das Leben hierzulande so schnell geworden ist": "Grund für" ← "dafür" + dass-Satz.\n✓ "dafür" = لهذا (für + das).\n✗ "daran" = على هذا (an + das)، و"Grund daran" ما تتقالش.\n✗ "darauf" = على هذا (auf + das)، و"Grund darauf" ما تتقالش.`,
      rule: "Grund für + Akk. → Grund dafür, dass …", ex: "Der Grund **dafür** ist einfach.", exTr: "السبب في هذا بسيط." },
    33: { ok: "MAG", type: "verb", keyword: "mag … sein (Einräumung)", bed: "ربّما",
      text: `"Ein Grund … ___ die moderne Technik sein": "mag … sein" = ربّما / ممكن (تنازل)، والفعل بعدو "sein" في الآخر.\n✓ "mag" = ربّما (3. Person مفرد + Infinitiv "sein").\n✗ "möchte" = يحبّ (رغبة)، و"möchte die Technik sein" معناها يحبّ يكون.\n✗ "würde" = conditional: "würde … sein" ممكنة بمعنى افتراض، بصح "mag" تعبّر على احتمال حقيقي.`,
      rule: "X mag Y sein = vielleicht ist es Y (Einräumung)", ex: "Das **mag** richtig sein.", exTr: "ربّما هذا صحيح." },
    34: { ok: "ZWAR", type: "conjunction", keyword: "zwar … aber", bed: "صحيح",
      text: `"E-Mails erreichen den Empfänger ___ schneller als ein Brief, aber …": اعتراف ثم "aber".\n✓ "zwar" = صحيح (الجزء الأول من zwar … aber).\n✗ "aber" = لكن، تجي في الجزء الثاني موش الأول.\n✗ "wie" = كيما (مقارنة)، و"schneller wie" ما تتقالش (يتقال "als").`,
      rule: "zwar A, aber B = Zugeständnis + Gegensatz", ex: "Es ist **zwar** klein, aber stark.", exTr: "صحيح صغير، لكن قوي." },
    35: { ok: "ABER", type: "conjunction", keyword: "zwar …, aber …", bed: "لكن",
      text: `"…schneller als ein Brief, ___ die Informationsflut … bewirkt auch, dass …": الجزء الثاني من التعارض، والفاعل بعد الرابط.\n✓ "aber" = لكن (Position 0).\n✗ "oder" = أو (اختيار)، وما فماش بديل.\n✗ "entweder" = إمّا (entweder … oder)، وما فماش "oder".`,
      rule: "zwar … aber = Zugeständnis + Gegensatz (aber: Position 0)", ex: "Er ist alt, **aber** fit.", exTr: "هو كبير، لكن لياقتو باهية." },
    36: { ok: "ALS", type: "conjunction", keyword: "mehr … als", bed: "من",
      text: `"kostet … mehr Zeit ___ man möchte": مقارنة بعد "mehr" (Komparativ).\n✓ "als" = من (mehr … als).\n✗ "wie" = كيما: تتقال في الكلام، بصح بعد "mehr" المعتمد "als".\n✗ "würde" = فعل (conditional)، موش أداة مقارنة.`,
      rule: "mehr / weniger + Nomen + als (Ungleichheit)  |  so … wie (Gleichheit)", ex: "Er verdient mehr **als** ich.", exTr: "هو يكسب أكثر مني." },
    37: { ok: "DARAN", type: "pronoun_adverb", keyword: "zweifeln an → daran, ob", bed: "في هذا",
      text: `"Viele zweifeln inzwischen ___, ob die … Schnelligkeit … noch übereinstimmen": "zweifeln an" ← "daran" + ob-Satz.\n✓ "daran" = في هذا (an + das).\n✗ "darauf" = على هذا (auf + das)، و"zweifeln darauf" ما تتقالش.\n✗ "dafür" = لهذا (für + das)، و"zweifeln dafür" ما تتقالش.`,
      rule: "zweifeln an + Dat. → daran zweifeln, ob / dass …", ex: "Ich **zweifle daran**, ob er kommt.", exTr: "نشكّ هل باش يجي." },
    38: { ok: "DARAUF", type: "pronoun_adverb", keyword: "Einfluss darauf, wie …", bed: "على هذا",
      text: `"Die Gleichförmigkeit … hat einen starken Einfluss ___, wie das Lebenstempo empfunden wird": "Einfluss auf" ← "darauf" + wie-Satz.\n✓ "darauf" = على هذا (auf + das).\n✗ "daran" = في هذا (an + das)، و"Einfluss daran" ما تتقالش.\n✗ "danach" = بعد هذا (ظرف زمني)، و"Einfluss danach" ما تتقالش.`,
      rule: "Einfluss auf + Akk. → Einfluss darauf, wie / dass …", ex: "Das hat Einfluss **darauf**, wie wir leben.", exTr: "هذا عندو تأثير على كيفاش نعيشو." },
    39: { ok: "WÜRDE", type: "tense", keyword: "würde … entstehen (Konjunktiv II)", bed: "ممكن (يتكوّن)",
      text: `"Bei immer mehr Routine … ___, so die Forscher, der Eindruck von Schnelligkeit entstehen": افتراض: "würde + Infinitiv".\n✓ "würde" = Konjunktiv II (würde … entstehen).\n✗ "wäre" = تحتاج Partizip II ("wäre entstanden")، موش Infinitiv "entstehen".\n✗ "sei" = Konjunktiv I (كلام منقول)، و"sei … entstehen" ما تتقالش بدون Partizip.`,
      rule: "würde + Infinitiv = Irrealis / Annahme", ex: "Dann **würde** das Problem entstehen.", exTr: "وقتها ممكن يتكوّن المشكل." },
    40: { ok: "DANACH", type: "adjective_adverb", keyword: "danach befragt", bed: "بعدها",
      text: `"Und siehe da: ___ befragt, wie sie die Urlaubszeit empfunden haben, antworten die meisten": بعد العطلة، استفسار.\n✓ "danach" = بعدها (ظرف زمني: danach befragt).\n✗ "darauf" = على هذا: "darauf befragt" ممكنة (سُئلوا على هذا)، بصح السياق ترتيب زمني (بعد العطلة).\n✗ "dafür" = لهذا، موش ظرف زمني.`,
      rule: "danach = zeitlich nach dem Genannten", ex: "**Danach** gingen wir nach Hause.", exTr: "بعدها مشينا للدار." },
  },
};
