// SB Teil 2 restyle — batch 05: [22] Höflichkeit, [23] + [24] Im Restaurant (gap 32 passage shows "Die Schuhe ___ in jedem Fall an" — "man" missing after the gap), [25] Online-Sprachkurse, [26] Kühltruhe
export default {
  // ───────────── [22] Verlernen die Deutschen die Höflichkeit? ─────────────
  22: {
    31: { ok: "STIMMEN", type: "verb", keyword: "zustimmen (stimmen … zu)", bed: "يوافقو",
      text: `"Drei von vier Deutschen ___ dieser Behauptung zu": الفعل المنفصل "zustimmen" + Dativ، والفاعل جمع.\n✓ "stimmen" = (stimmen … zu، جمع).\n✗ "nehmen" = (nehmen … zu = "zunehmen" = يزيد)، فعل آخر ما ياخذش Dativ بهذا المعنى.\n✗ "meinen" = يعتقد، وما عندو جزء "zu" منفصل بمعنى يوافق.`,
      rule: "trennbar: zustimmen + Dativ → stimmen … zu  |  zunehmen = wachsen", ex: "Alle **stimmen** dem Vorschlag **zu**.", exTr: "الكلّ يوافقو على الاقتراح." },
    32: { ok: "MEINEN", type: "verb", keyword: "meinen (Meinung wiedergeben)", bed: "يعتقدو (يرى)",
      text: `"Früher waren die Menschen höflicher, ___ einer Umfrage zufolge 75 Prozent der Befragten": جملة منقولة، والفعل بعدو القلب مع الفاعل "75 Prozent".\n✓ "meinen" = يعتقدو (جمع، Inversion بعد الاقتباس).\n✗ "stimmen" = يوافقو، تحتاج "zu" ("stimmen … zu")، وما يعطيش نقل رأي هنا.\n✗ "mögen" = يحبّو، ما يعبّرش على رأي في الماضي.`,
      rule: "Aussage, meinen + Subjekt = Meinungsangabe (Inversion)", ex: "Es wird besser, **meinen** die Experten.", exTr: "يتحسّن، يعتقدو الخبراء." },
    33: { ok: "NACH", type: "preposition", keyword: "Wunsch nach + Dativ", bed: "الرغبة في",
      text: `"besteht der Wunsch ___ gewissen Höflichkeitsformen": "Wunsch nach" = الرغبة في.\n✓ "nach" = في / نحو (Wunsch nach + Dativ).\n✗ "nacheinander" = واحد بعد واحد (ظرف)، موش حرف جر.\n✗ "sich" = ضمير انعكاسي، وما يركّبش "Wunsch" مع اسم بعدو.`,
      rule: "Wunsch / Sehnsucht / Verlangen nach + Dativ", ex: "Er hat den **Wunsch** nach Ruhe.", exTr: "عندو رغبة في الراحة." },
    34: { ok: "MITEINANDER", type: "noun", keyword: "ein höfliches Miteinander", bed: "التعامل مع بعضنا",
      text: `"Klare Spielregeln für ein höfliches ___": اسم (das Miteinander) = العيش المشترك.\n✓ "Miteinander" = التعايش / التعامل (اسم محايد).\n✗ "nacheinander" = واحد بعد واحد (ترتيب)، وما يعطيش معنى التعايش.\n✗ "fein" = رفيع / لطيف (صفة)، وما تجي بعد "höfliches" هكا.`,
      rule: "das Miteinander = Zusammenleben (Nomen)  |  nacheinander = der Reihe nach", ex: "Wir brauchen ein gutes **Miteinander**.", exTr: "نحتاجو تعايش باهي." },
    35: { ok: "VERGEBLICH", type: "adjective_adverb", keyword: "vergeblich suchen", bed: "بدون جدوى",
      text: `"sucht man sie oft ___": البحث ما ينجحش.\n✓ "vergeblich" = بدون جدوى (البحث ما يعطيش نتيجة).\n✗ "sinnlos" = بلا معنى: ممكنة، بصح "vergeblich suchen" هو التعبير المعتاد لنتيجة سلبية للبحث.\n✗ "gut" = مليح، وما يعطيش معنى فشل البحث.`,
      rule: "vergeblich = ohne Erfolg  |  sinnlos = ohne Sinn", ex: "Er wartete **vergeblich** auf eine Antwort.", exTr: "استنّى جواب بدون جدوى." },
    36: { ok: "GUT", type: "adjective_adverb", keyword: "gut die Hälfte", bed: "بالأقلّ نصف",
      text: `"___ die Hälfte der Deutschen gibt zu": "gut" قبل رقم = أكثر من / ما يقلّش على.\n✓ "gut" = أكثر من (gut die Hälfte = أكثر من النصف شوية).\n✗ "fein" = رفيع / ناعم، و"fein die Hälfte" ما تتقالش.\n✗ "man" = الواحد (فاعل عام)، موش ظرف كمية.`,
      rule: "gut + Mengenangabe = reichlich (gut die Hälfte, gut zehn Minuten)", ex: "Es dauerte **gut** eine Stunde.", exTr: "دامت أكثر من ساعة." },
    37: { ok: "MÖGEN", type: "verb", keyword: "empfinden mögen (Vermutung)", bed: "ربّما يحسّو",
      text: `"Während es jüngere Menschen … als normal … empfinden ___": جمع، وصيغة "ربّما" (Konzession).\n✓ "mögen" = ربّما / يحبّو (فعل مساعد جمع).\n✗ "lassen" = يخلّي، و"empfinden lassen" ما تتماشاش مع الفاعل "jüngere Menschen".\n✗ "stören" = يزعج، وما تركّبش بعد "empfinden".`,
      rule: "mögen + Infinitiv = Zugeständnis: Sie mögen recht haben (… aber)", ex: "Das **mögen** manche so sehen.", exTr: "ربّما فما ناس يشوفوها هكا." },
    38: { ok: "STÖREN", type: "verb_prep", keyword: "sich stören an + Dativ", bed: "يزعجهم",
      text: `"besonders Ältere ___ sich am ungefragten Duzen": "sich stören an" = ينزعج من.\n✓ "stören" = (sich stören an، جمع).\n✗ "meinen" = يعتقد، ما يتركّب مع "sich … an".\n✗ "stimmen" = يوافق، وما تتركّبش مع "sich am Duzen".`,
      rule: "sich an + Dativ stören = Anstoß nehmen", ex: "Viele **stören** sich am Lärm.", exTr: "برشا ينزعجو من الضجيج." },
    39: { ok: "LASSEN", type: "verb", keyword: "den Vortritt lassen", bed: "يخلّو (الأولوية)",
      text: `"ihnen den Vortritt ___": "jdm. den Vortritt lassen" = يخلّيلو الأولوية.\n✓ "lassen" = يخلّو (Infinitiv بعد "erfordert … dass Männer … ").\n✗ "nehmen" = ياخذ: "den Vortritt nehmen" = ياخذ الأولوية لروحو، عكس المقصود.\n✗ "stören" = يزعج، وما يركّبش مع "Vortritt".`,
      rule: "jdm. den Vortritt lassen = jdn. vorgehen lassen  |  sich den Vortritt nehmen", ex: "Er **lässt** der Dame den Vortritt.", exTr: "هو يخلّي للسيّدة الأولوية." },
    40: { ok: "SICH", type: "pronoun", keyword: "was sich gehört", bed: "اللي يليق",
      text: `"Wenn man weiß, was ___ gehört": "sich gehören" = يليق / مناسب.\n✓ "sich" = الضمير الانعكاسي (was sich gehört).\n✗ "man" = الواحد (فاعل)، موش ضمير انعكاسي.\n✗ "gut" = مليح، وما يركّبش مع "gehört" هكا.`,
      rule: "es gehört sich = es ist angemessen  |  was sich gehört", ex: "Man tut, was **sich** gehört.", exTr: "الواحد يعمل اللي يليق." },
  },

  // ───────────── [23] Im Restaurant ( Original ) ─────────────
  23: {
    31: { ok: "GEHÖREN", type: "verb", keyword: "gehören auf + Akk.", bed: "بلاصتهم (على)",
      text: `"Die Arme ___ nicht auf den Tisch": "Arme" جمع، و"gehören auf" = بلاصتهم على.\n✓ "gehören" = بلاصتهم (Plural).\n✗ "bleibt" = مفرد، والفاعل "Arme" جمع.\n✗ "behält" = مفرد + يحتاج مفعول، ومعناه يحتفظ.`,
      rule: "etwas gehört auf / in / an + Akk. = hat dort seinen Platz", ex: "Die Bücher **gehören** auf das Regal.", exTr: "الكتب بلاصتها على الرفّ." },
    32: { ok: "BEHÄLT", type: "verb", keyword: "anbehalten (behält … an)", bed: "يخلّي (لابسهم)",
      text: `"Die Schuhe ___ in jedem Fall an": الفعل المنفصل "anbehalten" = يخلّي لابسو.\n✓ "behält" = (behält … an، 3. Person مفرد).\n✗ "bleibt" = يبقى، وما فماش "anbleiben" بهذا المعنى.\n✗ "gehören" = جمع، وما يكمّلش "an" هنا.`,
      rule: "trennbar: anbehalten → behält … an (Kleidung nicht ausziehen)", ex: "Er **behält** den Mantel **an**.", exTr: "هو يخلّي المعطف لابسو." },
    33: { ok: "MANCHER", type: "pronoun", keyword: "so mancher", bed: "برشا ناس",
      text: `"steht so ___ vor einem Problem": "so mancher" = برشا ناس / أكثر من واحد.\n✓ "mancher" = بعض الناس (Nominativ مذكّر).\n✗ "jeder" = كلّ واحد، و"so jeder" ما تتقالش.\n✗ "klar" = واضح (صفة)، موش ضمير.`,
      rule: "so mancher = nicht wenige Leute (Nominativ)", ex: "**So mancher** weiß das nicht.", exTr: "برشا ناس ما يعرفوش هذا." },
    34: { ok: "MIT", type: "preposition", keyword: "jdn. mit … rufen", bed: "بـ (يعيّط)",
      text: `"Die Bedienung ___ "Fräulein" an den Tisch zu rufen": الطريقة اللي نعيّطو بيها.\n✓ "mit" = بـ (mit "Fräulein" rufen).\n✗ "als" = كـ: ممكنة نحويًّا، بصح مع "rufen" المعتاد "mit" (als = "نسمّيها").\n✗ "Tipp" = بقشيش / نصيحة (اسم)، موش حرف جر.`,
      rule: "jdn. mit + Anrede rufen / ansprechen", ex: "Man ruft ihn **mit** dem Vornamen.", exTr: "نعيّطولو بالاسم الأول." },
    35: { ok: "DAGEGEN", type: "adjective_adverb", keyword: "dagegen (Kontrast)", bed: "بالمقابل",
      text: `"'Herr Ober' oder 'Bedienung' ist ___ noch möglich": مقابلة مع "Fräulein" (القديم).\n✓ "dagegen" = بالمقابل (ظرف تعارض).\n✗ "klar" = واضح، و"ist klar noch möglich" ما تتقالش.\n✗ "fertig" = خلص، وما يتماشاش مع "möglich".`,
      rule: "dagegen = im Gegensatz dazu (Adverb)", ex: "Der Zug ist spät, der Bus **dagegen** pünktlich.", exTr: "التران متأخّر، والبيّاص بالمقابل في الوقت." },
    36: { ok: "WINK", type: "noun", keyword: "ein kleiner Wink", bed: "إشارة",
      text: `"mit einem kleinen ___ mit der Hand": إشارة خفيفة باليد.\n✓ "Wink" = إشارة (حركة اليد).\n✗ "Tipp" = نصيحة / معلومة، موش حركة باليد.\n✗ "Takt" = إيقاع / حسّ لباقة، وما يعطيش إشارة.`,
      rule: "ein Wink (mit der Hand)  |  ein Tipp = Hinweis  |  der Takt = Rhythmus / Feingefühl", ex: "Sie gab ihm einen **Wink**.", exTr: "عطاتو إشارة." },
    37: { ok: "FERTIG", type: "adjective_adverb", keyword: "mit etwas fertig sein", bed: "خلّص",
      text: `"Ist man mit dem Essen ___": "mit etwas fertig sein" = خلّص.\n✓ "fertig" = خلّص (mit dem Essen fertig).\n✗ "bereit" = جاهز، و"bereit mit dem Essen" ما تتقالش (تحتاج "bereit zum Essen").\n✗ "klar" = واضح، و"mit dem Essen klar" ما تعني خلّص.`,
      rule: "mit etwas fertig sein = abgeschlossen haben  |  bereit sein zu / für", ex: "Ich bin mit der Arbeit **fertig**.", exTr: "خلّصت من الخدمة." },
    38: { ok: "TAKT", type: "noun", keyword: "Takt gefragt", bed: "لباقة",
      text: `"Beim Bezahlen ist ___ gefragt": صفة سلوكية (لباقة) بدون أداة.\n✓ "Takt" = لباقة (Feingefühl، اسم بدون أداة بعد "ist … gefragt").\n✗ "Tipp" = نصيحة: اسم مذكّر ويحتاج أداة ("ein Tipp ist gefragt").\n✗ "Wink" = إشارة، ويحتاج أداة، وما تعطيش معنى اللباقة.`,
      rule: "Takt / Geduld / Feingefühl ist gefragt (abstrakte Nomen ohne Artikel)", ex: "Hier ist **Takt** gefragt.", exTr: "هنا مطلوب لباقة." },
    39: { ok: "KLAR", type: "verb", keyword: "klarmachen (macht … klar)", bed: "يفهّم (يوضّح)",
      text: `"macht er dies dem Kellner ___": الفعل المنفصل "klarmachen" = يوضّح.\n✓ "klar" = (macht … klar = يوضّح لـ).\n✗ "fertig" = ("fertigmachen" = يخلّص أو يقهر)، معنى مختلف.\n✗ "bereit" = ("bereitmachen" = يجهّز)، معنى مختلف.`,
      rule: "trennbar: jdm. etwas klarmachen = deutlich sagen", ex: "Sie **macht** ihm den Plan **klar**.", exTr: "هي توضّحلو الخطّة." },
    40: { ok: "WAS", type: "pronoun", keyword: ", was (Bezug auf den Satz)", bed: "اللي",
      text: `"getrennt bezahlen, ___ durchaus üblich ist": الجملة الفرعية تعلّق على الجملة الكاملة.\n✓ "was" = اللي (Relativpronomen يرجع لجملة كاملة).\n✗ "als" = كـ / وقتما، موش ضمير موصول.\n✗ "dagegen" = بالمقابل (ظرف)، ما يفتحش جملة فرعية بفعل في الآخر.`,
      rule: "was = Relativpronomen mit Bezug auf einen ganzen Satz", ex: "Er kam spät, **was** niemand überraschte.", exTr: "جا متأخّر، واللي ما فاجأش حتى واحد." },
  },

  // ───────────── [24] Im Restaurant (معدل) ─────────────
  24: {
    31: { ok: "GEHÖREN", type: "verb", keyword: "gehören auf den Tisch (Plural)", bed: "بلاصتهم",
      text: `"Die Arme ___ nicht auf den Tisch": فعل جمع يتماشى مع "Arme".\n✓ "gehören" = بلاصتهم (Plural).\n✗ "bleibt" = مفرد، والفاعل جمع.\n✗ "behält" = مفرد، ويحتاج مفعول.`,
      rule: "gehören + Richtung (auf / in / an + Akk.)", ex: "Die Schuhe **gehören** in den Schrank.", exTr: "الصبّاط بلاصتو في الخزانة." },
    32: { ok: "BEHÄLT", type: "verb", keyword: "behält … an", bed: "يخلّي (لابسهم)",
      text: `"Die Schuhe ___ in jedem Fall an": "anbehalten" = ما يحلّهمش.\n✓ "behält" = (behält … an).\n✗ "bleibt" = يبقى، ما يركّبش مع "an" بهذا المعنى.\n✗ "gehören" = جمع، وما يكمّلش "an".`,
      rule: "anbehalten → behält … an", ex: "Im Büro **behält** er die Jacke **an**.", exTr: "في المكتب يخلّي الجاكيت لابسو." },
    33: { ok: "MANCHEM", type: "pronoun", keyword: "so manchem (Dativ)", bed: "لبعض الناس",
      text: `"bereitet so ___ Probleme": "bereiten" ياخذ Dativ، و"so manchem" = لبعض الناس.\n✓ "manchem" = Dativ مفرد (so manchem).\n✗ "mancher" = Nominativ / Genitiv، وما يتماشاش مع "bereitet … Probleme" (يحتاج Dativ).\n✗ "jeder" = كلّ واحد (Nominativ)، و"so jeder" ما تتقالش.`,
      rule: "jdm. Probleme bereiten: so manchem (Dativ)", ex: "Das Wetter bereitet **manchem** Sorgen.", exTr: "الطقس يسبّب قلق لبعض الناس." },
    34: { ok: "MIT", type: "preposition", keyword: "mit der Anrede rufen", bed: "بـ (الخطاب)",
      text: `"Die Bedienung ___ der Anrede "Fräulein" … zu rufen": "mit der Anrede".\n✓ "mit" = بـ (mit der Anrede).\n✗ "als" = كـ: ممكنة نحويًّا، بصح مع "Anrede" المعتاد "mit".\n✗ "bleibt" = فعل مصرّف، وما يجي بعد "Bedienung" هكا.`,
      rule: "mit der Anrede … ansprechen / rufen", ex: "Man spricht ihn **mit** der Anrede Herr an.", exTr: "نخاطبوه بكلمة سيّد." },
    35: { ok: "DAGEGEN", type: "adjective_adverb", keyword: "dagegen … zwar korrekt, aber", bed: "بالمقابل",
      text: `"ist ___ zwar korrekt, aber … unüblich": مقابلة مع الأولى.\n✓ "dagegen" = بالمقابل (ظرف).\n✗ "klar" = واضح، و"klar zwar korrekt" ما تتركّبش.\n✗ "als" = كـ / وقتما، موش ظرف تعارض.`,
      rule: "dagegen = demgegenüber (Adverb des Gegensatzes)", ex: "Das ist **dagegen** zwar erlaubt, aber selten.", exTr: "هذا بالمقابل مسموح، لكن نادر." },
    36: { ok: "WINK", type: "noun", keyword: "mit einem Wink", bed: "إشارة",
      text: `"mit einem kleinen ___ mit der Hand": إشارة باليد.\n✓ "Wink" = إشارة.\n✗ "Taktgefühl" = لباقة، موش حركة.\n✗ "was" = ضمير موصول، موش اسم بعد "kleinen".`,
      rule: "ein kleiner Wink = ein kurzes Zeichen", ex: "Mit einem **Wink** rief sie ihn.", exTr: "بإشارة عيّطتلو." },
    37: { ok: "FERTIG", type: "adjective_adverb", keyword: "fertig sein mit", bed: "خلّص",
      text: `"Wenn man mit dem Essen ___ ist": "fertig sein" = خلّص.\n✓ "fertig" = خلّص.\n✗ "bereit" = جاهز، و"mit dem Essen bereit" ما تتقالش.\n✗ "klar" = واضح، موش خلّص.`,
      rule: "fertig sein mit + Dativ", ex: "Sind Sie schon **fertig** mit dem Test?", exTr: "خلّصت من الاختبار؟" },
    38: { ok: "TAKTGEFÜHL", type: "noun", keyword: "Taktgefühl ist wichtig", bed: "حسّ اللباقة",
      text: `"Beim Bezahlen ist ___ wichtig": صفة سلوكية (حسّ اللباقة) بدون أداة.\n✓ "Taktgefühl" = حسّ اللباقة (اسم).\n✗ "Wink" = إشارة، ويحتاج أداة، وما يعبّرش على اللباقة.\n✗ "was" = ضمير موصول، موش اسم بعد "ist".`,
      rule: "Taktgefühl / Höflichkeit ist wichtig (abstrakt, ohne Artikel)", ex: "In dieser Lage ist **Taktgefühl** wichtig.", exTr: "في هذا الموقف حسّ اللباقة مهمّ." },
    39: { ok: "KLAR", type: "verb", keyword: "klarmachen", bed: "يوضّح",
      text: `"Macht er dies dem Kellner ___": الفعل المنفصل "klarmachen".\n✓ "klar" = (macht … klar = يوضّح).\n✗ "bereit" = ("bereitmachen" = يجهّز)، معنى مختلف.\n✗ "fertig" = ("fertigmachen" = يخلّص أو يقهر)، معنى مختلف.`,
      rule: "klarmachen = verständlich machen (trennbar)", ex: "Ich **mache** ihm die Regeln **klar**.", exTr: "نوضّحلو القواعد." },
    40: { ok: "WAS", type: "pronoun", keyword: "was (Relativpronomen)", bed: "اللي",
      text: `"getrennt bezahlen, ___ durchaus üblich ist": تعليق على الجملة كاملة.\n✓ "was" = اللي (يرجع للجملة كاملة).\n✗ "als" = كـ / وقتما، موش ضمير موصول.\n✗ "jeder" = كلّ واحد، موش ضمير يرجع لجملة.`,
      rule: ", was = Relativpronomen für einen ganzen Satz", ex: "Es regnet, **was** schade ist.", exTr: "تشتي، واللي حسرة." },
  },

  // ───────────── [25] Online-Sprachkurse & Co. ─────────────
  25: {
    31: { ok: "SOGAR", type: "adjective_adverb", keyword: "sogar (Steigerung)", bed: "حتى",
      text: `"zahlreiche Online-Sprachkurse und ___ mit Smartphones kann man Sprachen lernen": زيادة غير متوقّعة: حتى بالتلفون.\n✓ "sogar" = حتى (تصعيد).\n✗ "schon" = ديجا: "schon mit Smartphones" ممكنة، بصح "sogar" تضيف مفاجأة، و"schon" تعطي معنى "من الآن".\n✗ "kaum" = بالكاد، تقلب المعنى (ما ننجّموش).`,
      rule: "sogar = überraschende Steigerung  |  schon = bereits", ex: "Es gibt **sogar** Kurse für Kinder.", exTr: "فما حتى دروس للصغار." },
    32: { ok: "MIT", type: "preposition", keyword: "Partnerschaft mit + Dativ", bed: "مع",
      text: `"eine Tandem-Partnerschaft ___ einem Muttersprachler": الشراكة مع شخص.\n✓ "mit" = مع (Partnerschaft mit + Dativ).\n✗ "für" = لـ (+ Akkusativ)، و"für einem" ما تتطابقش (Dativ).\n✗ "von" = من، و"Partnerschaft von einem" ما تعطيش معنى "مع".`,
      rule: "Partnerschaft / Zusammenarbeit mit + Dativ", ex: "Sie hat eine Partnerschaft **mit** einer Firma.", exTr: "عندها شراكة مع شركة." },
    33: { ok: "SONDERN", type: "conjunction", keyword: "nicht nur … sondern auch", bed: "بل",
      text: `"nicht nur lesen, ___ gleichzeitig auch hören": الزوج "nicht nur … sondern auch".\n✓ "sondern" = بل.\n✗ "aber" = لكن: تتقال أحيانًا، بصح الزوج المعتمد "sondern auch".\n✗ "sogar" = حتى، موش رابط بين جزئين.`,
      rule: "nicht nur …, sondern auch …", ex: "Er liest nicht nur, **sondern** schreibt auch.", exTr: "هو موش بس يقرا، بل يكتب زادا." },
    34: { ok: "OHNE", type: "conjunction", keyword: "ohne dass", bed: "بدون ما",
      text: `"Wörter nachsprechen, ___ dass ein ganzer Kurs zuhört": الفايدة: بدون ما حدّ يسمع.\n✓ "ohne" = بدون (ohne dass).\n✗ "so" = بحيث (so dass)، المعنى عكسي: بحيث الكلّ يسمع.\n✗ "um" = باش (um … zu)، وما تتركّبش مع "dass".`,
      rule: "ohne dass + Nebensatz = ohne dass etwas passiert", ex: "Er ging, **ohne** dass jemand es merkte.", exTr: "مشى بدون ما حدّ يتفطّن." },
    35: { ok: "ANSTATT", type: "conjunction", keyword: "lieber … anstatt … zu", bed: "عوض",
      text: `"lieber mehrmals täglich … wiederholen, ___ sie in einer Stunde alle auf einmal zu lernen": مقارنة بين طريقتين مع "lieber".\n✓ "anstatt" = عوض (anstatt … zu + Infinitiv).\n✗ "ohne" = بدون: "ohne … zu lernen" ممكنة، بصح "lieber" تطلب البديل (عوض) موش النفي.\n✗ "um" = باش (غرض)، وتعطي معنى عكسي (باش نتعلّمهم في ساعة).`,
      rule: "lieber A, anstatt B zu tun = A statt B", ex: "Ich gehe lieber zu Fuß, **anstatt** zu fahren.", exTr: "نفضّل نمشي على رجليّا عوض ما نسوق." },
    36: { ok: "BESONDERS", type: "adjective_adverb", keyword: "besonders gut", bed: "خاصة",
      text: `"sind ___ gut zum Vokabellernen geeignet": ظرف درجة قبل الصفة.\n✓ "besonders" = خاصةً (besonders + Adjektiv).\n✗ "kaum" = بالكاد، و"kaum gut geeignet" تقلب المعنى (مش مناسبة).\n✗ "so" = هكا، و"so gut … geeignet" تحتاج "dass"، وما تتماشاش مع "mehr aber meist nicht".`,
      rule: "besonders + Adjektiv = in hohem Maß", ex: "Die App ist **besonders** gut für Anfänger.", exTr: "التطبيق خاصةً باهي للمبتدئين." },
    37: { ok: "ABER", type: "conjunction", keyword: "zwar … aber", bed: "لكن",
      text: `"macht zwar Spaß, ___ Satzbau … werden allenfalls kurz angesprochen": التنازل ثم "aber".\n✓ "aber" = لكن (الجزء الثاني من zwar … aber).\n✗ "sondern" = بل (تصحيح بعد نفي)، وما فماش نفي.\n✗ "sogar" = حتى، موش رابط تعارض.`,
      rule: "zwar A, aber B = Zugeständnis + Gegensatz", ex: "Es ist **zwar** teuer, **aber** gut.", exTr: "صحيح غالي، لكن باهي." },
    38: { ok: "SOLLTE", type: "verb", keyword: "sollte = Empfehlung", bed: "ينبغي",
      text: `"Dafür ___ man besser in einen Kurs gehen": نصيحة.\n✓ "sollte" = ينبغي (Konjunktiv II، توصية).\n✗ "müsste" = لازم: ممكنة نحويًّا، بصح الجملة نصيحة موش ضرورة مطلقة.\n✗ "kaum" = بالكاد، ظرف موش فعل مساعد.`,
      rule: "sollte = Empfehlung  |  müsste = (starke) Notwendigkeit", ex: "Man **sollte** mehr Wasser trinken.", exTr: "الواحد ينبغي يشرب ماء أكثر." },
    39: { ok: "UM", type: "conjunction", keyword: "um … zu + Infinitiv", bed: "باش",
      text: `"Der schnellste Weg, ___ einen passenden Tandem-Partner zu finden": غرض مع "zu + Infinitiv".\n✓ "um" = باش (um … zu).\n✗ "für" = لـ (+ اسم)، موش "zu + Infinitiv".\n✗ "von" = من، وما يعطيش غرض.`,
      rule: "der Weg, um … zu + Infinitiv = Mittel zum Zweck", ex: "Das ist der beste Weg, **um** Deutsch zu lernen.", exTr: "هذا أحسن طريق باش تتعلّم ألماني." },
    40: { ok: "SCHON", type: "adjective_adverb", keyword: "…, schon + Verb (sofort)", bed: "وتوّا",
      text: `"Muttersprache … eingeben, ___ werden alle Treffer angezeigt": بعد الإدخال، النتيجة على طول.\n✓ "schon" = وتوّا / على طول (النتيجة توصل بسرعة).\n✗ "so" = هكا: "so werden … angezeigt" ممكنة، بصح "schon" تعبّر على السرعة.\n✗ "kaum" = بالكاد، تقلب المعنى.`,
      rule: "(Bedingung), schon + Verb = sofort / bereits", ex: "Einmal klicken, **schon** ist es fertig.", exTr: "كليك واحد، وتوّا يخلّص." },
  },

  // ───────────── [26] Liebesgrüße aus der Kühltruhe ( Original ) ─────────────
  26: {
    31: { ok: "ANHAND", type: "preposition", keyword: "anhand + Genitiv", bed: "بالاعتماد على",
      text: `"kann man ___ des Inhalts … den Charakter erkennen": "des Inhalts" Genitiv، والوسيلة = بالاعتماد على.\n✓ "anhand" = بالاعتماد على (+ Genitiv).\n✗ "wegen" = بسبب (+ Genitiv)، وتعطي سبب موش وسيلة.\n✗ "aus" = من (+ Dativ)، و"aus des Inhalts" ما تتماشاش مع Genitiv.`,
      rule: "anhand + Genitiv = mithilfe von (anhand der Daten)", ex: "**Anhand** der Fotos erkennt man ihn.", exTr: "بالاعتماد على الصور يتعرّفو عليه." },
    32: { ok: "VON", type: "preposition", keyword: "Kategorien von + Dativ", bed: "من",
      text: `"fünf Kategorien ___ Single-Männern": "Kategorien von" = أصناف من.\n✓ "von" = من (Kategorien von + Dativ).\n✗ "aus" = من (مادّة / مصدر)، و"Kategorien aus Männern" معناها مصنوعة منهم.\n✗ "in" = في، و"Kategorien in Single-Männern" ما تتقالش.`,
      rule: "Kategorien / Arten / Typen von + Dativ", ex: "Es gibt drei Arten **von** Tickets.", exTr: "فما ثلاثة أنواع من التذاكر." },
    33: { ok: "SOWIE", type: "conjunction", keyword: "A, B, C sowie D", bed: "وكذلك",
      text: `قائمة: "den spontanen Typ, den Bequemen, den Kreativen, ___ den Cocktail- und den Gourmet-Typen": العنصر الأخير يتّصل بـ "sowie".\n✓ "sowie" = وكذلك (يربط الآخر عنصر في القائمة).\n✗ "folglich" = وبالتالي (نتيجة)، موش رابط في قائمة.\n✗ "fast" = تقريبًا، ظرف موش رابط.`,
      rule: "A, B, C sowie D = und (letztes Glied einer Aufzählung)", ex: "Wir verkaufen Äpfel, Birnen **sowie** Orangen.", exTr: "نبيعو تفّاح وإجاص وكذلك برتقال." },
    34: { ok: "AUS", type: "preposition", keyword: "aus denen zusammenstellen", bed: "منها",
      text: `"Produkte …, ___ denen er eine Mahlzeit zusammenstellen kann": من المنتجات يركّب أكلة.\n✓ "aus" = من (aus + Dativ، materiell: aus denen).\n✗ "von" = من: "von denen" ممكنة لكن مع "zusammenstellen" المعتاد "aus".\n✗ "in" = في، و"in denen eine Mahlzeit zusammenstellen" ما تعطيش معنى المصدر.`,
      rule: "etwas aus + Dativ zusammenstellen / herstellen", ex: "Er baut **aus** Holz einen Tisch.", exTr: "يبني من الخشب طاولة." },
    35: { ok: "AUF", type: "fixed_expression", keyword: "auf der Hand liegen", bed: "واضح",
      text: `تعبير ثابت: "auf der Hand liegen" = واضح للعيان.\n✓ "auf" = (auf der Hand liegen).\n✗ "in" = "in der Hand liegen" = تحت تصرّف / بيد فلان، معنى مختلف.\n✗ "von" = من، وما تعطيش التعبير.`,
      rule: "auf der Hand liegen = offensichtlich sein  |  in jds. Hand liegen = von jdm. abhängen", ex: "Die Lösung **liegt** auf der Hand.", exTr: "الحلّ واضح." },
    36: { ok: "ANSTRENGEND", type: "adjective_adverb", keyword: "zu + Adjektiv", bed: "متعب",
      text: `"Ihnen ist es sogar zu ___, zwei Tüten zu öffnen": رجال كسالى، فاتح كيسين متعب.\n✓ "anstrengend" = متعب (zu + Adjektiv).\n✗ "langweilig" = ممل: ممكنة نحويًّا، بصح الجملة تتكلّم على مجهود (كسل) موش ملل.\n✗ "eher" = بالأحرى، ظرف موش صفة بعد "zu".`,
      rule: "es ist zu + Adjektiv, … zu + Infinitiv (zu anstrengend, zu schwer)", ex: "Es ist mir zu **anstrengend**, so früh aufzustehen.", exTr: "متعب برشا عليّ نقوم بكري هكا." },
    37: { ok: "FOLGLICH", type: "adjective_adverb", keyword: "folglich (Folge)", bed: "وبالتالي",
      text: `"___ kaufen diese Männer am häufigsten komplette Gerichte": نتيجة للكسل، والفعل بعد الظرف.\n✓ "folglich" = وبالتالي (ظرف نتيجة + فعل في الثانية).\n✗ "kaum" = بالكاد، تقلب المعنى.\n✗ "fast" = تقريبًا، موش ظرف نتيجة.`,
      rule: "folglich = deshalb / also (Folgerung)", ex: "Er war krank, **folglich** blieb er zu Hause.", exTr: "كان مريض، وبالتالي قعد في الدار." },
    38: { ok: "EHER", type: "adjective_adverb", keyword: "eher skeptisch", bed: "بالأحرى",
      text: `"sehen das wohl ___ skeptisch": درجة التشكيك: بالأحرى متشكّكين.\n✓ "eher" = بالأحرى / أكثر (eher + Adjektiv).\n✗ "kaum" = بالكاد، و"kaum skeptisch" معناها تقريبًا موش متشكّكين (عكس المقصود).\n✗ "fast" = تقريبًا: ممكنة، بصح "eher" تعبّر على ميل موش على اقتراب.`,
      rule: "eher + Adjektiv = mehr in diese Richtung", ex: "Er ist **eher** ruhig.", exTr: "هو بالأحرى هادئ." },
    39: { ok: "ZU", type: "verb_prep", keyword: "gehören zu + Dativ", bed: "ينتمي لـ",
      text: `"egal, ___ welcher Kategorie ein Mann gehört": "gehören zu" = ينتمي لـ.\n✓ "zu" = لـ (gehören zu + Dativ).\n✗ "in" = في: "gehören in + Akk." تتقال بحركة، وهنا "welcher" في Dativ.\n✗ "von" = من، و"gehören von" ما تتقالش.`,
      rule: "zu + Dativ gehören = Teil von etwas sein", ex: "Er **gehört** zu unserem Team.", exTr: "هو ينتمي لفريقنا." },
    40: { ok: "WOHL", type: "adjective_adverb", keyword: "wohl eher (Vermutung)", bed: "ربّما",
      text: `"andere ___ eher keine Lust": تخمين: "andere ربّما ما عندهمش نفس".\n✓ "wohl" = ربّما (تخمين مخفّف).\n✗ "kaum" = بالكاد، و"kaum eher keine" تعطي نفي مزدوج غريب.\n✗ "fast" = تقريبًا، وما تعبّرش على تخمين.`,
      rule: "wohl = vermutlich (Abschwächung)", ex: "Er kommt **wohl** später.", exTr: "هو ربّما يجي بعد." },
  },
};
