// SB Teil 2 restyle — batch 09: [42] Schlafwagen, [43] Katzen, [44] Rückkehr des Nachtzugs, [45] Joggen (gaps 34/39 BEI/UNTER interchangeable → hedged), [46] Lernen ist kein Privileg (gap 39: WEGEN equally valid → hedged)
export default {
  // ───────────── [42] Die Reise im Schlafwagen ─────────────
  42: {
    31: { ok: "EINGESTELLT", type: "tense", keyword: "wurden … eingestellt (Passiv)", bed: "تلغاو",
      text: `"viele Angebote wurden ___": Passiv: wurden + Partizip II. "einstellen" = يوقّف / يلغي.\n✓ "eingestellt" = Partizip II من "einstellen" (wurden eingestellt = تلغاو).\n✗ "ausweiten" = Infinitiv (يوسّع)، وبعد "wurden" نحتاج Partizip II، ومعناه عكس.\n✗ "neue" = صفة، ما تكمّلش Passiv.`,
      rule: "Vorgangspassiv Präteritum: wurden + Partizip II (eingestellt = beendet)", ex: "Die Linie **wurde** gestern **eingestellt**.", exTr: "الخطّ تلغى البارح." },
    32: { ok: "KUNDEN", type: "noun", keyword: "neue Kunden gewinnen", bed: "حرفاء",
      text: `"Das Angebot gewinne kontinuierlich neue ___": "Kunden gewinnen" = يكسب حرفاء.\n✓ "Kunden" = حرفاء (Akkusativ جمع بعد "neue").\n✗ "Konkurrenten" = منافسين: "neue Konkurrenten gewinnen" ما تعطيش معنى (العرض يكسب حرفاء موش منافسين).\n✗ "Konkurrenz" = منافسة (مفرد)، و"gewinne neue Konkurrenz" ما تتقالش.`,
      rule: "Kunden / Fahrgäste gewinnen = neue Nutzer anziehen", ex: "Die Firma gewinnt neue **Kunden**.", exTr: "الشركة تكسب حرفاء جدد." },
    33: { ok: "GRÜNDEN", type: "noun", keyword: "aus Gründen + Genitiv", bed: "لأسباب",
      text: `"aus ___ des Umweltschutzes": "aus Gründen des …" = لأسباب.\n✓ "Gründen" = أسباب (aus + Dativ جمع، + Genitiv).\n✗ "Mode" = موضة، و"aus Mode des Umweltschutzes" ما تتقالش.\n✗ "insgesamt" = في المجموع (ظرف)، موش اسم بعد "aus".`,
      rule: "aus Gründen + Genitiv (aus Gründen des Umweltschutzes, aus gesundheitlichen Gründen)", ex: "Er fehlt **aus** persönlichen **Gründen**.", exTr: "هو غايب لأسباب شخصية." },
    34: { ok: "MODE", type: "fixed_expression", keyword: "in Mode kommen", bed: "يولّي موضة",
      text: `"Kommt der Nachtzug also wieder in ___?": تعبير ثابت "in Mode kommen" = يولّي موضة.\n✓ "Mode" = موضة (in Mode kommen).\n✗ "Konkurrenz" = منافسة: "in Konkurrenz kommen" ممكنة، بصح السؤال عن رجوع الشعبية.\n✗ "Gründen" = أسباب (جمع)، و"in Gründen kommen" ما تتقالش.`,
      rule: "in Mode kommen = beliebt / modern werden  |  aus der Mode kommen", ex: "Alte Möbel kommen wieder **in Mode**.", exTr: "الأثاث القديم يرجع موضة." },
    35: { ok: "KONKURRENZ", type: "noun", keyword: "jdm. Konkurrenz machen", bed: "منافسة",
      text: `"dem Flugzeug als Reisemittel ___ machen": تعبير ثابت: "jdm. Konkurrenz machen".\n✓ "Konkurrenz" = منافسة (Konkurrenz machen + Dativ).\n✗ "Konkurrenten" = منافسين (جمع)، و"dem Flugzeug Konkurrenten machen" ما تتقالش.\n✗ "Kunden" = حرفاء، و"Kunden machen" ما تعطيش معنى المنافسة.`,
      rule: "jdm. Konkurrenz machen = mit jdm. wetteifern", ex: "Der Zug macht dem Flugzeug **Konkurrenz**.", exTr: "التران ينافس الطيّارة." },
    36: { ok: "GANZ", type: "adjective_adverb", keyword: "ganz schön + Adjektiv", bed: "برشا",
      text: `"ist es manchmal ___ schön ungemütlich und stickig": "ganz schön" = برشا / فعلًا (تشديد).\n✓ "ganz" = (ganz schön + Adjektiv).\n✗ "insgesamt" = في المجموع، و"insgesamt schön ungemütlich" ما تعطيش تشديد.\n✗ "voreilig" = متسرّع (صفة)، وما تركّبش قبل "schön".`,
      rule: "ganz schön + Adjektiv = ziemlich / sehr (umgangssprachlich)", ex: "Es ist **ganz schön** kalt heute.", exTr: "اليوم برد برشا." },
    37: { ok: "AUSSERDEM", type: "adjective_adverb", keyword: "außerdem + Verb", bed: "وزيد",
      text: `"___ schrecke die lange Reisezeit viele ab": إضافة حجّة، والفعل "schrecke" بعد الظرف.\n✓ "außerdem" = وزيد (ظرف، الفعل في الثانية).\n✗ "während" = بينما (رابط جملة فرعية + فعل في الآخر)، وهنا "schrecke" في الثانية.\n✗ "als" = وقتما / كـ (رابط)، وما يعطيش إضافة.`,
      rule: "außerdem + Verb (Position 2) = zusätzlich", ex: "Es ist teuer, **außerdem** ist es weit.", exTr: "غالي، وزيد بعيد." },
    38: { ok: "ALS", type: "preposition", keyword: "als + Nomen (Funktion)", bed: "كـ",
      text: `"___ umweltschonendes Transportmittel ist der Nachtzug aktueller denn je": "als" = كـ (الصفة / الوظيفة).\n✓ "als" = كـ (als + Nomen).\n✗ "durch" = عبر / بواسطة (+ Akk.)، و"durch umweltschonendes Transportmittel" ما تعطيش معنى الصفة.\n✗ "während" = بينما / أثناء، موش حرف يعطي صفة.`,
      rule: "als + Nomen = in der Rolle / Eigenschaft von", ex: "**Als** Lehrer arbeitet er sehr viel.", exTr: "كمعلّم هو يخدم برشا." },
    39: { ok: "WÄHREND", type: "conjunction", keyword: "während + Nebensatz", bed: "بينما",
      text: `"Vor den Zugfenstern ziehen … Landschaften vorbei, ___ man von dem sanften Rattern … in den Schlaf gewiegt wird": حدثين في نفس الوقت، والفعل "wird" في الآخر.\n✓ "während" = بينما (+ فعل في الآخر).\n✗ "als" = وقتما (ماضي مرة وحدة)، والجملة حاضر.\n✗ "insgesamt" = في المجموع (ظرف)، موش رابط.`,
      rule: "während + Nebensatz = gleichzeitig  |  als = einmalig in der Vergangenheit", ex: "Er liest, **während** sie kocht.", exTr: "هو يقرا بينما هي تطيّب." },
    40: { ok: "VOREILIG", type: "adjective_adverb", keyword: "etwas voreilig sein", bed: "متسرّع",
      text: `"war etwas ___": حكم: كان متسرّع.\n✓ "voreilig" = متسرّع (صفة بعد "war etwas").\n✗ "ganz" = تمامًا، و"war etwas ganz" ما تتقالش.\n✗ "neue" = صفة بنهاية، وما تكمّلش "war etwas".`,
      rule: "voreilig sein = zu schnell urteilen / handeln", ex: "Die Entscheidung war **voreilig**.", exTr: "القرار كان متسرّع." },
  },

  // ───────────── [43] Katzen kennen ihren Namen ─────────────
  43: {
    31: { ok: "LAGE", type: "fixed_expression", keyword: "in der Lage sein", bed: "قادرة",
      text: `"sie durchaus in der ___ ihren Namen … herauszuhören": تعبير ثابت: "in der Lage sein" = قادر.\n✓ "Lage" = (in der Lage sein، مؤنّث).\n✗ "Stellung" = موضع / منصب: "in der Stellung sein" معنى آخر.\n✗ "Anzeigen" = إعلانات / شكايات (جمع)، و"in der Anzeigen" ما تتطابقش.`,
      rule: "in der Lage sein, … zu + Infinitiv = fähig sein", ex: "Er ist nicht in der **Lage**, zu helfen.", exTr: "هو موش قادر يعاون." },
    32: { ok: "ANGABEN", type: "noun", keyword: "nach eigenen Angaben", bed: "حسب أقوالهم",
      text: `"Nach eigenen ___ lieferten die Forscher …": تعبير ثابت: "nach eigenen Angaben" = حسب أقوالهم.\n✓ "Angaben" = أقوال / معطيات (Dativ جمع بعد "nach").\n✗ "Anzeigen" = إعلانات / شكايات، و"nach eigenen Anzeigen" ما تتقالش.\n✗ "Verhalten" = سلوك (مفرد)، و"nach eigenen Verhalten" ما تتطابقش.`,
      rule: "nach eigenen Angaben = laut eigener Aussage", ex: "**Nach** eigenen **Angaben** war er allein.", exTr: "حسب أقوالو كان وحدو." },
    33: { ok: "VERHALTEN", type: "noun", keyword: "das Verhalten untersuchen", bed: "السلوك",
      text: `"Die Forscher hatten das ___ von 78 Katzen untersucht": "das" محايد: اسم محايد مفرد.\n✓ "Verhalten" = السلوك (das Verhalten، محايد).\n✗ "Stellung" = موضع (مؤنّث: "die Stellung")، و"das Stellung" ما تتطابقش.\n✗ "Angaben" = أقوال (جمع)، و"das Angaben" ما تتطابقش.`,
      rule: "das Verhalten (Neutrum) = wie sich jd. benimmt", ex: "Man beobachtet das **Verhalten** der Tiere.", exTr: "يراقبو سلوك الحيوانات." },
    34: { ok: "ZUNÄCHST", type: "adjective_adverb", keyword: "zunächst (zuerst)", bed: "أوّلًا",
      text: `"___ spielten sie den Tieren vier japanische Wörter … vor": أوّل خطوة في التجربة.\n✓ "zunächst" = أوّلًا (ظرف ترتيب، الفعل في الثانية).\n✗ "zudem" = وزيد (إضافة)، موش بداية التسلسل.\n✗ "weiter" = بعد / أكثر، موش "أوّلًا".`,
      rule: "zunächst = als Erstes (zeitliche Abfolge)", ex: "**Zunächst** lesen wir den Text.", exTr: "أوّلًا نقراو النصّ." },
    35: { ok: "WEITER", type: "adjective_adverb", keyword: "immer weiter", bed: "أكثر فأكثر",
      text: `"nahm die Aufmerksamkeit der Katzen immer ___ ab": تدريجي: "immer weiter" = أكثر فأكثر.\n✓ "weiter" = أكثر / تواصل (immer weiter).\n✗ "bloß" = فقط / غير، و"immer bloß ab" ما تتقالش.\n✗ "zudem" = وزيد، موش ظرف تدرّج.`,
      rule: "immer weiter = fortlaufend / stetig", ex: "Die Preise steigen **immer weiter**.", exTr: "الأسعار تزيد أكثر فأكثر." },
    36: { ok: "SONDERN", type: "conjunction", keyword: "nicht …, sondern …", bed: "بل",
      text: `"wenn nicht der Katzenbesitzer selbst … sprach, ___ eine fremde Person": تصحيح بعد النفي.\n✓ "sondern" = بل.\n✗ "sofern" = بشرط إنّو (رابط شرط + فعل في الآخر)، موش تصحيح.\n✗ "zudem" = وزيد، موش بل.`,
      rule: "nicht A, sondern B = Korrektur nach Verneinung", ex: "Nicht er kam, **sondern** sie.", exTr: "موش هو اللي جا، بل هي." },
    37: { ok: "DENEN", type: "pronoun", keyword: "denen (= die Namen) + Genitiv", bed: "تلك",
      text: `"ihren Namen von ___ ihrer Artgenossen unterscheiden": "denen" = أسماء (جمع) يعوّض اسم قبلو، و"von" + Dativ.\n✓ "denen" = تلك (Demonstrativpronomen Dativ جمع: von denen ihrer Artgenossen).\n✗ "deren" = Genitiv (ملكية)، و"von deren ihrer" ما تتقالش.\n✗ "bekannt" = معروف (صفة)، موش ضمير.`,
      rule: "von denen = von jenen (Dativ Plural, Demonstrativ)", ex: "Er kennt seine Regeln und **denen** seiner Freunde.", exTr: "هو يعرف قواعدو وقواعد صحابو." },
    38: { ok: "SOFERN", type: "conjunction", keyword: "sofern + Nebensatz (Bedingung)", bed: "بشرط إنّو",
      text: `"Katzen sind sehr intelligent und lernfähig – ___ sie bereit sind mitzumachen": شرط، والفعل "sind" في الآخر.\n✓ "sofern" = بشرط إنّو (رابط شرط).\n✗ "sondern" = بل (تصحيح بعد نفي)، وما فماش نفي.\n✗ "zudem" = وزيد (ظرف)، موش رابط شرط.`,
      rule: "sofern = wenn / unter der Bedingung, dass (Nebensatz)", ex: "Du kannst kommen, **sofern** du Zeit hast.", exTr: "تنجّم تجي، بشرط إنّو عندك وقت." },
    39: { ok: "BEKANNT", type: "adjective_adverb", keyword: "es ist bekannt, dass", bed: "معروف",
      text: `"Aus vorherigen Untersuchungen ist ___, dass Katzen es verstehen": "bekannt sein, dass" = معروف إنّو.\n✓ "bekannt" = معروف (ist bekannt, dass).\n✗ "vertraut" = مألوف: "vertraut sein mit" تحتاج "mit"، و"ist vertraut, dass" ما تتقالش.\n✗ "weiter" = أكثر / بعد، موش صفة معنى "معروف".`,
      rule: "es ist bekannt, dass …  |  vertraut sein mit + Dativ", ex: "Es ist **bekannt**, dass Wasser nass ist.", exTr: "معروف إنّو الماء مبلول." },
    40: { ok: "BLOSS", type: "adjective_adverb", keyword: "bloß (Abtönungspartikel)", bed: "يا ترى",
      text: `"warum ist es dann ___ so schwierig": "bloß" في السؤال تعبّر على استغراب (يا ترى علاش).\n✓ "bloß" = يا ترى / آخرتها (Abtönungspartikel في سؤال).\n✗ "weiter" = أكثر، و"dann weiter so schwierig" ما تتقالش.\n✗ "zudem" = وزيد، وما تتماشاش مع سؤال الاستغراب.`,
      rule: "bloß in Fragen = verstärkt Verwunderung (warum bloß …?)", ex: "Warum ist er **bloß** so müde?", exTr: "علاش هو تعبان هكا يا ترى؟" },
  },

  // ───────────── [44] Die Rückkehr des Nachtzugs ─────────────
  44: {
    31: { ok: "MODE", type: "fixed_expression", keyword: "wieder in Mode bringen", bed: "يرجّع موضة",
      text: `"Warum die Klimadebatte Schlafwagen wieder in ___ bringt": تعبير ثابت: "in Mode bringen" = يرجّع موضة.\n✓ "Mode" = موضة (in Mode bringen).\n✗ "Form" = شكل: "in Form bringen" = يرجّع لياقتو / يرتّب، معنى مختلف.\n✗ "ganz" = تمامًا (ظرف)، موش اسم بعد "in".`,
      rule: "in Mode bringen = beliebt machen  |  in Form bringen = ordnen / herrichten", ex: "Der Film brachte den Stil wieder **in Mode**.", exTr: "الفيلم رجّع الستيل موضة." },
    32: { ok: "GANZ", type: "adjective_adverb", keyword: "ganz so … wie", bed: "تمامًا هكا",
      text: `"aber ___ so schnell wie mit dem Flugzeug ist es nicht": "ganz so … wie" = بنفس السرعة تقريبًا.\n✓ "ganz" = تمامًا (ganz so + Adjektiv + wie).\n✗ "wirklich" = فعلًا: ممكنة ("wirklich so schnell")، بصح "ganz so … wie" هو التعبير المعتاد للمقارنة.\n✗ "insgesamt" = في المجموع، وما تركّبش قبل "so schnell".`,
      rule: "(nicht) ganz so + Adj. + wie = fast gleich … wie", ex: "Es ist nicht **ganz so** teuer wie gedacht.", exTr: "موش غالي بنفس الشكل اللي توقّعناه." },
    33: { ok: "AUSWEITEN", type: "verb", keyword: "ausweiten (Infinitiv nach können)", bed: "نوسّعو",
      text: `"könnten wir das Angebot rasch deutlich ___": بعد "könnten" Infinitiv.\n✓ "ausweiten" = يوسّع (Infinitiv).\n✗ "eingestellt" = Partizip II (ألغى)، وبعد "könnten" نحتاج Infinitiv، ومعناه عكس.\n✗ "gestaltet" = Partizip II (صمّم)، ونفس المشكل.`,
      rule: "Modalverb (könnten) + Infinitiv am Ende: ausweiten", ex: "Wir könnten das Programm **ausweiten**.", exTr: "نجّمو نوسّعو البرنامج." },
    34: { ok: "INSGESAMT", type: "adjective_adverb", keyword: "insgesamt (in der Summe)", bed: "في المجموع",
      text: `"___ seien in der Regel acht Mitarbeiter in einem Nachtzug unterwegs": جملة تلخّص العدد: في المجموع.\n✓ "insgesamt" = في المجموع (ظرف).\n✗ "außerdem" = وزيد: ممكنة نحويًّا، بصح الجملة تحكي على العدد الكلّي موش إضافة.\n✗ "ganz" = تمامًا، موش ظرف تلخيص.`,
      rule: "insgesamt = alles zusammen  |  außerdem = zusätzlich", ex: "**Insgesamt** kamen 200 Gäste.", exTr: "في المجموع جاو 200 ضيف." },
    35: { ok: "NEUE", type: "adjective_adverb", keyword: "eine neue Intercity-Nachtverbindung", bed: "جديدة",
      text: `"eine ___ Intercity-Nachtverbindung gestartet": صفة بعد "eine" (Akkusativ مؤنّث) ← -e.\n✓ "neue" = جديدة (-e بعد "eine").\n✗ "gestaltet" = Partizip II (صمّم)، موش صفة بهذا المعنى.\n✗ "Form" = اسم، موش صفة.`,
      rule: "eine + Adjektiv-e + Femininum (Akk.): eine neue Verbindung", ex: "Wir haben eine **neue** Linie eröffnet.", exTr: "فتحنا خطّ جديد." },
    36: { ok: "EINGESTELLT", type: "tense", keyword: "eingestellt werden (Mitarbeiter)", bed: "يتوظّفو",
      text: `"Dazu sollen auch rund tausend zusätzliche Mitarbeiter ___ werden": Passiv + "sollen": Partizip II + werden. "Mitarbeiter einstellen" = يوظّف.\n✓ "eingestellt" = يتوظّفو (Partizip II من einstellen).\n✗ "ausweiten" = يوسّع (Infinitiv)، وما يتركّبش مع "werden" هكا.\n✗ "gestaltet" = صمّم، و"Mitarbeiter gestaltet werden" ما تتقالش.`,
      rule: "Mitarbeiter einstellen = anstellen  |  einstellen = auch beenden (ein Angebot)", ex: "Neue Lehrer **werden eingestellt**.", exTr: "معلّمين جدد باش يتوظّفو." },
    37: { ok: "KONKURRENTEN", type: "noun", keyword: "Konkurrenten (Plural)", bed: "المنافسين",
      text: `"warum nicht ___ dieses Angebot … übernehmen sollten": فاعل جمع (منافسين)، والفعل "sollten" جمع.\n✓ "Konkurrenten" = منافسين (Nominativ جمع).\n✗ "Mode" = موضة (مفرد)، و"Mode sollten" ما تتطابقش.\n✗ "Form" = شكل (مفرد)، ونفس المشكل ومعناه ما يتماشاش.`,
      rule: "Subjekt im Plural + Verb im Plural (Konkurrenten … sollten)", ex: "Die **Konkurrenten** übernehmen das Angebot.", exTr: "المنافسين ياخذو العرض." },
    38: { ok: "DURCH", type: "preposition", keyword: "reduzieren durch + Akk.", bed: "عبر",
      text: `"die vielen Flugreisen … ___ ein klimafreundliches Mobilitätsangebot zu reduzieren": الوسيلة: عبر عرض صديق للمناخ.\n✓ "durch" = عبر / بواسطة (durch + Akkusativ).\n✗ "als" = كـ، و"reduzieren als ein Angebot" ما تعطيش معنى الوسيلة.\n✗ "wegen" = بسبب (+ Genitiv)، موش وسيلة.`,
      rule: "durch + Akk. = Mittel / Weg (durch ein Angebot reduzieren)", ex: "Man spart Energie **durch** Isolierung.", exTr: "نوفّرو الطاقة بالعزل." },
    39: { ok: "GESTALTET", type: "tense", keyword: "gestaltet wäre (Zustandspassiv Konjunktiv II)", bed: "مصمّم",
      text: `"wenn so dieser neue Nachtzug in den … Europafarben ___ wäre": Zustandspassiv: Partizip II + wäre.\n✓ "gestaltet" = مصمّم (Partizip II من gestalten).\n✗ "eingestellt" = Partizip II (ألغى / وظّف)، و"in den Europafarben eingestellt" ما تتقالش.\n✗ "ausweiten" = Infinitiv، وبعد "wäre" نحتاج Partizip II.`,
      rule: "Zustandspassiv: sein + Partizip II (gestaltet sein = so aussehen)", ex: "Der Raum ist modern **gestaltet**.", exTr: "القاعة مصمّمة بشكل حديث." },
    40: { ok: "WEGEN", type: "preposition", keyword: "wegen + Genitiv", bed: "بسبب",
      text: `"wurde ___ damals hoher Verluste 2016 eingestellt": سبب + Genitiv.\n✓ "wegen" = بسبب (+ Genitiv: wegen hoher Verluste).\n✗ "durch" = عبر / بواسطة (+ Akk.)، و"durch hoher Verluste" ما تتطابقش.\n✗ "als" = كـ / وقتما، موش حرف جر سبب.`,
      rule: "wegen + Genitiv = Grund", ex: "**Wegen** des Regens fiel es aus.", exTr: "بسبب المطر تلغى." },
  },

  // ───────────── [45] Joggen: Mehr als nur Laufen ─────────────
  45: {
    31: { ok: "BEQUEM", type: "adjective_adverb", keyword: "bequem werden", bed: "مريح",
      text: `"Auto, Rolltreppe, Fahrstuhl – das moderne Leben ist ___ geworden": كلّها وسائل راحة.\n✓ "bequem" = مريح (ist bequem geworden).\n✗ "schnell" = سريع: "ist schnell geworden" ممكنة نحويًّا، بصح الأمثلة (Rolltreppe، Fahrstuhl) تعبّر على راحة موش سرعة.\n✗ "erheblich" = كبير بشكل ملحوظ (ظرف)، وما تكمّلش "ist … geworden" بهذا المعنى.`,
      rule: "bequem = ohne Anstrengung  |  schnell = mit hoher Geschwindigkeit", ex: "Das Leben ist **bequem** geworden.", exTr: "الحياة ولّات مريحة." },
    32: { ok: "SIND", type: "verb", keyword: "sind (Plural)", bed: "هي",
      text: `"Herz-Kreislauf-Erkrankungen ___ … die Todesursache Nummer Eins": الفاعل جمع.\n✓ "sind" = (Plural من sein).\n✗ "ist" = مفرد، والفاعل "Erkrankungen" جمع.\n✗ "wird" = مفرد (يصير)، وما يطابقش الجمع.`,
      rule: "Subjekt im Plural → sind (nicht ist)", ex: "Diese Zahlen **sind** hoch.", exTr: "هذي الأرقام عالية." },
    33: { ok: "DABEI", type: "pronoun_adverb", keyword: "dabei (= dabei zu trainieren)", bed: "وقتها",
      text: `"Wichtig ist, ___ richtig zu trainieren": تعبير "dabei" مع "zu-Infinitiv" = في هذا.\n✓ "dabei" = في هذا / خلال هذا (bei + das).\n✗ "dass" = إنّو (+ فعل مصرّف)، ما يتركّبش مع "zu trainieren".\n✗ "wie" = كيفاش، و"Wichtig ist, wie richtig zu trainieren" ما تتقالش.`,
      rule: "wichtig ist, dabei richtig zu + Infinitiv (dabei = bei der Sache)", ex: "Wichtig ist, **dabei** ruhig zu bleiben.", exTr: "المهم هو نبقى هادئين في هذا." },
    34: { ok: "UNTER", type: "preposition", keyword: "unter Verbrennung von …", bed: "مع (حرق)",
      text: `"Ausdauertraining ___ Verbrennung von Sauerstoff": "unter + Dativ" = مع / بينما (أثناء عملية).\n✓ "unter" = مع (unter + Dativ: unter Verbrennung).\n✗ "bei" = عند: "bei Verbrennung" ممكنة، بصح "unter" هي المستعملة في اللغة العلمية لوصف الظروف.\n✗ "aller" = Genitiv جمع (كلّ)، وما تتركّبش قبل "Verbrennung".`,
      rule: "unter + Dativ = mit / bei (Umstände): unter Aufsicht, unter Verbrennung von …", ex: "Das Training läuft **unter** Aufsicht.", exTr: "التمرين يمشي تحت إشراف." },
    35: { ok: "SOLLTE", type: "verb", keyword: "sollte … kontrolliert werden", bed: "ينبغي",
      text: `"Dabei ___ der Puls kontrolliert werden": توصية + Passiv: Modalverb + Partizip II + werden.\n✓ "sollte" = ينبغي (Konjunktiv II، توصية).\n✗ "wird" = Passiv، و"wird … kontrolliert werden" ما تتقالش بنفس الشكل (تكرار werden).\n✗ "ist" = يكون، وما يطلبش "werden" في الآخر.`,
      rule: "sollte + Partizip II + werden = Empfehlung im Passiv", ex: "Der Puls **sollte** gemessen werden.", exTr: "ينبغي النبض يتقاس." },
    36: { ok: "DASS", type: "conjunction", keyword: "dass-Satz als Subjekt", bed: "إنّو",
      text: `"___ mehr Menschen den Schritt in ein aktiveres Leben wagen sollten, machen zahlreiche Studien deutlich": جملة "dass" كفاعل للفعل "machen … deutlich".\n✓ "dass" = إنّو (+ فعل في الآخر).\n✗ "wie" = كيفاش: ممكنة ("wie … wagen sollten")، بصح المعنى هنا محتوى موش طريقة.\n✗ "dabei" = في هذا (ظرف)، موش رابط جملة.`,
      rule: "Dass-Satz kann am Satzanfang stehen: Dass …, zeigt / macht … deutlich", ex: "**Dass** er recht hat, zeigen die Zahlen.", exTr: "إنّو هو على حقّ، تورّيه الأرقام." },
    37: { ok: "ALLER", type: "pronoun", keyword: "Prozent aller + Genitiv", bed: "كلّ",
      text: `"Rund 40 Prozent ___ Deutschen bringen zu viel auf die Waage": "Prozent aller Deutschen" = نسبة من كلّ الألمان (Genitiv جمع).\n✓ "aller" = كلّ (Genitiv جمع).\n✗ "einem" = Dativ مفرد، و"40 Prozent einem Deutschen" ما تتطابقش مع جمع "Deutschen".\n✗ "bei" = عند (حرف جر)، وما تعطيش كمية.`,
      rule: "x Prozent + Genitiv Plural (aller / der Deutschen)", ex: "Die Hälfte **aller** Schüler besteht.", exTr: "نصّ كلّ التلاميذ ينجحو." },
    38: { ok: "EINEM", type: "grammar_structure", keyword: "mit einem Herzinfarkt", bed: "بـ (أزمة قلبية)",
      text: `"nicht selten mit ___ Herzinfarkt": "mit" + Dativ مذكّر.\n✓ "einem" = Dativ مذكّر (mit einem Herzinfarkt).\n✗ "aller" = Genitiv جمع، و"mit aller Herzinfarkt" ما تتطابقش.\n✗ "erheblich" = ظرف / صفة بدون نهاية، وما يعطيش أداة قبل الاسم.`,
      rule: "mit + Dativ: mask. / neutr. = einem, fem. = einer", ex: "Er kommt mit **einem** Freund.", exTr: "يجي مع صاحب." },
    39: { ok: "BEI", type: "preposition", keyword: "bei Frauen (häufiger)", bed: "عند",
      text: `"immer häufiger ___ Frauen": "bei + Dativ" = عند (مجموعة).\n✓ "bei" = عند (immer häufiger bei Frauen).\n✗ "unter" = بين: "unter Frauen" ممكنة، بصح "unter" استعملناها في 34، وكلّ كلمة مرّة وحدة.\n✗ "aller" = Genitiv (كلّ)، وما تركّبش قبل "Frauen" هكا.`,
      rule: "bei + Dativ = bei einer Gruppe auftreten (bei Frauen, bei Kindern)", ex: "Das kommt **bei** Kindern oft vor.", exTr: "هذا يصير برشا عند الصغار." },
    40: { ok: "ERHEBLICH", type: "adjective_adverb", keyword: "erheblich (deutlich)", bed: "بشكل كبير",
      text: `"minimiert sich das Risiko … zu erleiden, ___": ظرف يؤكّد حجم الانخفاض.\n✓ "erheblich" = بشكل كبير (ظرف).\n✗ "schnell" = بسرعة: ممكنة نحويًّا، بصح الجملة عن حجم تقليل المخاطر موش سرعتو.\n✗ "immer" = ديما، وما يعطيش معنى حجم.`,
      rule: "erheblich = deutlich / in hohem Maß", ex: "Die Kosten sind **erheblich** gesunken.", exTr: "التكاليف نزلت بشكل كبير." },
  },

  // ───────────── [46] Lernen ist kein Privileg der Jugend ( Original ) ─────────────
  46: {
    31: { ok: "REGE", type: "adjective_adverb", keyword: "rege (= lebhaft, aktiv)", bed: "نشيطين",
      text: `"Senioren sind heute höchst ___, aktiv": صفات إيجابية: نشيط.\n✓ "rege" = نشيط / متحرّك (höchst rege).\n✗ "einzige" = وحيد (صفة بنهاية)، وما تتماشاش مع "höchst … aktiv".\n✗ "knapp" = قليل / بالكاد، وتناقض النشاط.`,
      rule: "rege = lebhaft, aktiv (höchst rege)", ex: "Er ist trotz seines Alters sehr **rege**.", exTr: "هو رغم عمرو نشيط برشا." },
    32: { ok: "AN", type: "preposition", keyword: "an Universitäten", bed: "في (الجامعات)",
      text: `"wie es ___ verschiedenen deutschen Universitäten angeboten wird": مكان: "an + Dativ" مع الجامعات.\n✓ "an" = في (an Universitäten).\n✗ "auf" = على، و"auf Universitäten" ما تتقالش.\n✗ "durch" = عبر / بواسطة، موش مكان.`,
      rule: "an der Universität / an Universitäten (Ort)", ex: "Er studiert **an** einer Universität.", exTr: "هو يدرس في جامعة." },
    33: { ok: "ALLEIN", type: "adjective_adverb", keyword: "allein in + Ort (Betonung)", bed: "وحدها (فقط)",
      text: `"___ in Trier waren … über 130 Personen … eingeschrieben": "allein" = فقط في (تأكيد العدد الكبير).\n✓ "allein" = فقط / وحدها (allein in Trier).\n✗ "einzige" = وحيد (صفة بنهاية)، و"Einzige in Trier" ما تتقالش.\n✗ "knapp" = بالكاد / حوالي، و"Knapp in Trier" ما تعطيش معنى التأكيد.`,
      rule: "allein + Ortsangabe = nur schon dort (Betonung)", ex: "**Allein** in Berlin leben vier Millionen.", exTr: "في برلين وحدها يعيشو أربع ملايين." },
    34: { ok: "DARAUF", type: "pronoun_adverb", keyword: "darauf folgen", bed: "بعدها",
      text: `"___ folgten die neueren Sprach- und Literaturwissenschaften": "darauf folgen" = جاو بعد هذا.\n✓ "darauf" = بعد هذا (auf + das، ظرف ترتيب).\n✗ "auf" = على، و"Auf folgten" ما تتقالش بدون ضمير.\n✗ "an" = عند، و"An folgten" ما تتقالش.`,
      rule: "darauf folgen = danach kommen", ex: "**Darauf** folgte eine lange Pause.", exTr: "بعدها جات استراحة طويلة." },
    35: { ok: "DÜRFTEN", type: "verb", keyword: "dürften (Vermutung)", bed: "على الأرجح",
      text: `"Die Gründe dafür ___ sein, dass Frauen …": تخمين: Konjunktiv II من "dürfen" = على الأرجح.\n✓ "dürften" = على الأرجح (جمع، تخمين).\n✗ "möchten" = يحبّو (رغبة)، و"Gründe möchten sein" ما تتقالش.\n✗ "wegen" = بسبب (حرف جر)، موش فعل مساعد.`,
      rule: "dürfte / dürften + Infinitiv = Vermutung (wahrscheinlich)", ex: "Das **dürfte** stimmen.", exTr: "على الأرجح هذا صحيح." },
    36: { ok: "AUF", type: "verb_prep", keyword: "verzichten auf + Akk.", bed: "يتخلّى عن",
      text: `"Frauen … häufig ___ eine berufliche Karriere verzichteten": "verzichten auf" = يتخلّى عن.\n✓ "auf" = عن (verzichten auf + Akkusativ).\n✗ "an" = عند / على، و"verzichten an" ما تتقالش.\n✗ "durch" = عبر، و"verzichten durch" ما تتقالش.`,
      rule: "auf etwas (Akk.) verzichten = es freiwillig aufgeben", ex: "Er **verzichtet** auf Zucker.", exTr: "هو يتخلّى عن السكّر." },
    37: { ok: "STATTDESSEN", type: "adjective_adverb", keyword: "stattdessen + Verb", bed: "عوضها",
      text: `"___ setzten sie sich für die Familie … ein": بديل: عوض المسيرة المهنية، والفعل بعد الظرف.\n✓ "stattdessen" = عوضها (ظرف، الفعل في الثانية).\n✗ "während" = بينما (رابط جملة فرعية + فعل في الآخر)، وهنا "setzten" في الثانية.\n✗ "wegen" = بسبب (حرف جر)، موش ظرف.`,
      rule: "stattdessen = an dessen Stelle (Adverb, Verb Position 2)", ex: "Er blieb zu Hause, **stattdessen** las er.", exTr: "قعد في الدار، وعوضها قرا." },
    38: { ok: "KURZ", type: "fixed_expression", keyword: "zu kurz kommen", bed: "يتهمّش",
      text: `"deren Einsatz … zu ___ gekommen war": تعبير ثابت: "zu kurz kommen" = ما ياخذش حقّو.\n✓ "kurz" = (zu kurz kommen).\n✗ "knapp" = قليل / بالكاد، و"zu knapp kommen" ما تتقالش.\n✗ "einzige" = وحيد (صفة)، موش جزء من التعبير.`,
      rule: "zu kurz kommen = nicht genug beachtet / gefördert werden", ex: "Bei der Arbeit kommt die Familie **zu kurz**.", exTr: "في الخدمة العايلة تتهمّش." },
    39: { ok: "AUFGRUND", type: "preposition", keyword: "aufgrund + Genitiv", bed: "بسبب",
      text: `"___ dessen sehen sie keine Veranlassung": سبب + Genitiv (dessen).\n✓ "aufgrund" = بسبب (+ Genitiv).\n✗ "wegen" = بسبب: "wegen dessen" ممكنة نحويًّا زادا، بصح الإجابة المعتمدة "aufgrund".\n✗ "durch" = عبر (+ Akk.)، و"durch dessen" ما تعطيش معنى السبب بنفس الشكل.`,
      rule: "aufgrund / wegen + Genitiv = Grund", ex: "**Aufgrund** des Wetters bleiben wir hier.", exTr: "بسبب الطقس نقعدو هنا." },
    40: { ok: "DURCH", type: "preposition", keyword: "gespeist durch + Akk.", bed: "بواسطة",
      text: `"Er wird gespeist ___ die Vitalität … der heutigen "Alten"": Passiv: الفاعل الوسيلة بـ "durch".\n✓ "durch" = بواسطة / بفضل (durch + Akkusativ).\n✗ "auf" = على، و"gespeist auf die Vitalität" ما تتقالش.\n✗ "an" = عند / على، و"gespeist an" ما تتقالش.`,
      rule: "Passiv: durch + Akk. = Mittel / Ursache (gespeist durch)", ex: "Der Bach wird **durch** Regen gespeist.", exTr: "الوادي يتغذّى بالمطر." },
  },
};
