// SB Teil 2 restyle — batch 06: [27] + [28] Kühltruhe (معدل), [29] + [30] Man(n) kocht selbst, [31] Der Hund als intelligentes Wesen
export default {
  // ───────────── [27] Liebesgrüße aus der Kühltruhe (معدل) ─────────────
  27: {
    31: { ok: "ZUFOLGE", type: "preposition", keyword: "Dativ + zufolge (nachgestellt)", bed: "حسب",
      text: `"Einer Studie ___ kann man … den Charakter erkennen": "zufolge" تجي بعد الاسم (Dativ).\n✓ "zufolge" = حسب (einer Studie zufolge).\n✗ "wegen" = بسبب، وتعطي سبب موش مصدر معلومة.\n✗ "in" = في، و"Einer Studie in" ما تتقالش.`,
      rule: "Nomen (Dativ) + zufolge = laut / nach Angaben von", ex: "Einem Bericht **zufolge** sinken die Preise.", exTr: "حسب تقرير الأسعار تنزل." },
    32: { ok: "SOWIE", type: "conjunction", keyword: "A, B, C sowie D", bed: "وكذلك",
      text: `قائمة أصناف: "den Kreativen, ___ den Cocktail- und den Gourmet-Typen": الرابط قبل آخر مجموعة.\n✓ "sowie" = وكذلك (يربط آخر عنصر في القائمة).\n✗ "und" = و: ممكنة، بصح "und" جاية بعدها في 33، والاثنين متتالين "und … und" يخلّو الجملة ثقيلة.\n✗ "ob" = هل (سؤال)، موش رابط عطف.`,
      rule: "A, B, C sowie D = Aufzählung (letztes Glied)", ex: "Wir haben Brot, Käse **sowie** Obst.", exTr: "عندنا خبز وجبن وكذلك غلال." },
    33: { ok: "UND", type: "conjunction", keyword: "Cocktail- und Gourmet-Typ", bed: "و",
      text: `"den Cocktail- ___ den Gourmet-Typen": تركيب مختصر ("Cocktail-Typ und Gourmet-Typ").\n✓ "und" = و (يربط الاثنين).\n✗ "sowie" = وكذلك: ممكنة نحويًّا، بصح "sowie" استعملناها في 32 لآخر عنصر، و"und" هنا تربط الزوج.\n✗ "jede" = كلّ (ضمير)، وما تربط حاجتين.`,
      rule: "Cocktail- und Gourmet-Typ (gekürzte Wortreihe mit und)", ex: "Wir kaufen Obst- **und** Gemüsesorten.", exTr: "نشريو أنواع غلال وخضرة." },
    34: { ok: "DENEN", type: "pronoun", keyword: "aus denen (Relativpronomen Dativ Pl.)", bed: "منها",
      text: `"Produkte …, aus ___ er eine Mahlzeit zusammenstellen kann": الجملة الفرعية تعرّف بالمنتجات (جمع)، و"aus" + Dativ.\n✓ "denen" = Dativ جمع (aus denen = منها).\n✗ "jede" = كلّ (Akkusativ مؤنّث مفرد)، و"aus jede" ما تتقالش.\n✗ "folglich" = وبالتالي (ظرف)، موش ضمير موصول.`,
      rule: "Präposition + Relativpronomen (Plural Dativ): aus denen, mit denen, von denen", ex: "Das sind Zutaten, aus **denen** man Brot macht.", exTr: "هذي مكوّنات منها تتعمل الخبز." },
    35: { ok: "JEDE", type: "pronoun", keyword: "für jede Frau", bed: "كلّ",
      text: `"Hauptgewinn für ___ Frau": "für" + Akkusativ مؤنّث مفرد.\n✓ "jede" = كلّ (Akkusativ Femininum).\n✗ "denen" = ضمير موصول جمع، موش قبل "Frau" مفرد.\n✗ "zu" = إلى، و"für zu Frau" ما تتقالش.`,
      rule: "jed- + Nomen: jede Frau (Fem.), jeder Mann (Mask.), jedes Kind (Neutr.)", ex: "Das ist ein Gewinn für **jede** Familie.", exTr: "هذا ربح لكلّ عائلة." },
    36: { ok: "ANSTRENGEND", type: "adjective_adverb", keyword: "zu anstrengend", bed: "متعب برشا",
      text: `"Ihnen ist es sogar zu ___, zwei Tüten zu öffnen": رجال ما يحبّوش يطيّبو: حتى فتح كيسين متعب.\n✓ "anstrengend" = متعب (zu + Adjektiv).\n✗ "langweilig" = ممل: ممكنة نحويًّا، بصح الجملة عن جهد مش ملل.\n✗ "fast" = تقريبًا، ظرف موش صفة بعد "zu".`,
      rule: "zu + Adjektiv + (zu-Infinitiv): zu anstrengend, zu schwer", ex: "Das ist mir zu **anstrengend**.", exTr: "هذا متعب برشا عليّ." },
    37: { ok: "FOLGLICH", type: "adjective_adverb", keyword: "folglich (Konsequenz)", bed: "وبالتالي",
      text: `"___ kaufen diese Männer am häufigsten komplette Gerichte": نتيجة الكسل، والفعل بعد الظرف.\n✓ "folglich" = وبالتالي (ظرف نتيجة، الفعل في الثانية).\n✗ "vermutlich" = على الأرجح: ممكنة نحويًّا، بصح الجملة تعطي نتيجة مؤكّدة موش تخمين.\n✗ "fast" = تقريبًا، موش ظرف نتيجة.`,
      rule: "folglich = also / daher  |  vermutlich = wahrscheinlich", ex: "Es regnete, **folglich** fiel das Spiel aus.", exTr: "كانت تشتي، وبالتالي المقابلة تلغات." },
    38: { ok: "OB", type: "conjunction", keyword: "ob (indirekte Frage)", bed: "هل",
      text: `"Aber ___ sie so das Herz einer Frau erobern können?": سؤال بجواب نعم / لا.\n✓ "ob" = هل (+ فعل في الآخر).\n✗ "und" = و، وما تفتحش سؤال.\n✗ "zu" = إلى، موش رابط سؤال.`,
      rule: "ob = Ja/Nein-Frage im Nebensatz", ex: "Wer weiß, **ob** es klappt?", exTr: "شكون يعرف هل باش يخدم؟" },
    39: { ok: "ZU", type: "verb_prep", keyword: "gehören zu + Dativ", bed: "ينتمي لـ",
      text: `"egal, ___ welcher Kategorie ein Mann gehört": "gehören zu" = ينتمي لـ.\n✓ "zu" = لـ (gehören zu + Dativ).\n✗ "in" = في: "gehören in" تحتاج Akkusativ (in welche Kategorie)، وهنا "welcher" Dativ.\n✗ "auf" = على، و"gehören auf" ما تتقالش بهذا المعنى.`,
      rule: "zu + Dativ gehören = Mitglied / Teil von etwas sein", ex: "Dieses Buch **gehört** zu einer Reihe.", exTr: "هذا الكتاب جزء من سلسلة." },
    40: { ok: "VERMUTLICH", type: "adjective_adverb", keyword: "vermutlich (Vermutung)", bed: "على الأرجح",
      text: `"Einige haben ___ wenig Zeit zum Kochen": تخمين عن أسباب.\n✓ "vermutlich" = على الأرجح.\n✗ "fast" = تقريبًا، و"fast wenig Zeit" ما تتقالش (تحتاج "fast keine").\n✗ "folglich" = وبالتالي (نتيجة)، موش تخمين.`,
      rule: "vermutlich = wahrscheinlich (Vermutung)", ex: "Er kommt **vermutlich** später.", exTr: "هو على الأرجح يجي بعد." },
  },

  // ───────────── [28] Liebesgrüße aus der Kühltruhe (معدل 2) ─────────────
  28: {
    31: { ok: "ZUFOLGE", type: "preposition", keyword: "einer Studie zufolge", bed: "حسب",
      text: `"Einer Studie ___ kann man … den Charakter erkennen": مصدر المعلومة.\n✓ "zufolge" = حسب (بعد الاسم في Dativ).\n✗ "anhand" = بالاعتماد على: تجي قبل الاسم + Genitiv ("anhand einer Studie")، موش بعدو.\n✗ "aus" = من، و"Einer Studie aus" ما تتقالش.`,
      rule: "zufolge: nachgestellt + Dativ (einer Studie zufolge)  |  anhand: vorangestellt + Genitiv", ex: "Seinen Worten **zufolge** ist alles gut.", exTr: "حسب كلامو كلّ شي باهي." },
    32: { ok: "VON", type: "preposition", keyword: "Kategorien von + Dativ", bed: "من",
      text: `"fünf Kategorien ___ Single-Männern": "Kategorien von" = أصناف من.\n✓ "von" = من (Kategorien von + Dativ).\n✗ "aus" = من (مادّة)، و"Kategorien aus Männern" معناها مصنوعة منهم.\n✗ "auf" = على، و"Kategorien auf Männern" ما تتقالش.`,
      rule: "Arten / Kategorien / Gruppen von + Dativ", ex: "Es gibt zwei Gruppen **von** Schülern.", exTr: "فما مجموعتين من التلاميذ." },
    33: { ok: "SOWIE", type: "conjunction", keyword: "sowie vor dem letzten Glied", bed: "وكذلك",
      text: `"den Kreativen, ___ den Cocktail- und den Gourmet-Typen": رابط للعنصر الأخير بعد قائمة.\n✓ "sowie" = وكذلك.\n✗ "folglich" = وبالتالي (نتيجة)، موش رابط عطف.\n✗ "fast" = تقريبًا، ظرف موش رابط.`,
      rule: "sowie = und (verbindet das letzte Glied einer Reihe)", ex: "Er mag Tee, Kaffee **sowie** Saft.", exTr: "يحب تاي وقهوة وكذلك عصير." },
    34: { ok: "DENEN", type: "pronoun", keyword: "aus denen", bed: "منها",
      text: `"Produkte …, aus ___ er eine Mahlzeit zusammenstellen kann": ضمير موصول جمع Dativ بعد "aus".\n✓ "denen" = Dativ جمع.\n✗ "jede" = كلّ (مفرد Akkusativ)، موش Dativ جمع.\n✗ "von" = من، وما تعوّضش الضمير الموصول بعد "aus".`,
      rule: "aus + denen (Plural Dativ Relativpronomen)", ex: "Das sind Früchte, aus **denen** wir Saft machen.", exTr: "هذي غلال منها نعملو عصير." },
    35: { ok: "JEDE", type: "pronoun", keyword: "jede Frau", bed: "كلّ",
      text: `"Hauptgewinn für ___ Frau": مؤنّث مفرد بعد "für".\n✓ "jede" = كلّ (Akkusativ Femininum).\n✗ "denen" = ضمير موصول جمع، ما يركّبش قبل "Frau" مفرد.\n✗ "zu" = إلى، موش قبل اسم بعد "für".`,
      rule: "jede + Femininum (Akk. / Nom.)", ex: "Für **jede** Aufgabe gibt es Zeit.", exTr: "لكلّ مهمّة فما وقت." },
    36: { ok: "ANSTRENGEND", type: "adjective_adverb", keyword: "zu + Adjektiv", bed: "متعب",
      text: `"Ihnen ist es sogar zu ___, zwei Tüten zu öffnen": صفة تدلّ على مجهود.\n✓ "anstrengend" = متعب.\n✗ "eher" = بالأحرى، و"zu eher" ما تتقالش.\n✗ "fast" = تقريبًا، ظرف موش صفة بعد "zu".`,
      rule: "zu + Adjektiv (zu anstrengend, zu müde)", ex: "Die Arbeit ist **anstrengend**.", exTr: "الخدمة متعبة." },
    37: { ok: "FOLGLICH", type: "adjective_adverb", keyword: "folglich", bed: "وبالتالي",
      text: `"___ kaufen diese Männer am häufigsten komplette Gerichte": نتيجة الكسل.\n✓ "folglich" = وبالتالي (الفعل بعدو في الثانية).\n✗ "vermutlich" = على الأرجح: ممكنة، بصح هنا نتيجة منطقية موش تخمين.\n✗ "eher" = بالأحرى، موش ظرف نتيجة.`,
      rule: "folglich + Verb (Position 2) = Folge", ex: "Er übte viel, **folglich** bestand er.", exTr: "تمرّن برشا، وبالتالي نجح." },
    38: { ok: "OB", type: "conjunction", keyword: "ob + Nebensatz", bed: "هل",
      text: `"Aber ___ sie so das Herz einer Frau erobern können?": سؤال غير مباشر.\n✓ "ob" = هل.\n✗ "von" = من، موش رابط.\n✗ "zu" = إلى، موش رابط سؤال.`,
      rule: "ob = Ja/Nein-Frage (indirekt)", ex: "Ich frage mich, **ob** das stimmt.", exTr: "نسأل روحي هل هذا صحيح." },
    39: { ok: "ZU", type: "verb_prep", keyword: "zu welcher Kategorie gehören", bed: "ينتمي لـ",
      text: `"egal, ___ welcher Kategorie ein Mann gehört": "gehören zu".\n✓ "zu" = لـ (gehören zu + Dativ).\n✗ "auf" = على، و"gehören auf welcher Kategorie" ما تتقالش.\n✗ "aus" = من، و"gehören aus" ما تتقالش.`,
      rule: "gehören zu + Dativ", ex: "Wir **gehören** zu einer Gruppe.", exTr: "نحنا ننتمو لمجموعة." },
    40: { ok: "VERMUTLICH", type: "adjective_adverb", keyword: "vermutlich", bed: "على الأرجح",
      text: `"Einige haben ___ wenig Zeit, andere wohl eher keine Lust": افتراض.\n✓ "vermutlich" = على الأرجح.\n✗ "fast" = تقريبًا، ما تركّبش مع "wenig".\n✗ "folglich" = وبالتالي، موش افتراض.`,
      rule: "vermutlich = wahrscheinlich", ex: "Sie ist **vermutlich** krank.", exTr: "هي على الأرجح مريضة." },
  },

  // ───────────── [29] Man(n) kocht selbst ( Original ) ─────────────
  29: {
    31: { ok: "DENN", type: "conjunction", keyword: "denn + Hauptsatz", bed: "خاطر",
      text: `"___ immer mehr Männer in Deutschland greifen jetzt selbst zum Kochtopf": الفاعل ثم الفعل ("Männer … greifen")، والجملة تفسّر الفكرة اللي قبل.\n✓ "denn" = خاطر (+ جملة رئيسية، الفاعل أوّل).\n✗ "daher" = لهذا السبب (ظرف نتيجة)، ويقلب الترتيب ("Daher greifen …").\n✗ "dass" = إنّو (+ فعل في الآخر)، وهنا "greifen" في الثانية.`,
      rule: "denn + Subjekt + Verb (Hauptsatz)  |  daher + Verb + Subjekt", ex: "Er kommt nicht, **denn** er ist krank.", exTr: "ما يجيش، خاطر مريض." },
    32: { ok: "FÜR", type: "preposition", keyword: "Grund für + Akk.", bed: "لـ (السبب في)",
      text: `"Ein Grund ___ diese Entwicklung": "Grund für" + Akkusativ.\n✓ "für" = لـ (Grund für).\n✗ "dafür" = لهذا (Pronominaladverb)، وبعدو اسم "diese Entwicklung" موش جملة.\n✗ "gegen" = ضدّ، وتعطي معنى معاكس.`,
      rule: "Grund für + Akk.  |  dafür, wenn kein Nomen folgt", ex: "Das ist ein Grund **für** Freude.", exTr: "هذا سبب للفرحة." },
    33: { ok: "ZWISCHEN", type: "preposition", keyword: "Unterschied zwischen … und …", bed: "بين",
      text: `"Unterschied besteht ___ den Ansprüchen … und denen eines Hobbykochs": مقارنة بين شيئين (… und …).\n✓ "zwischen" = بين (zwischen … und …).\n✗ "gegen" = ضدّ، ما تعطيش معنى الفرق بين طرفين.\n✗ "für" = لـ، و"Unterschied für den Ansprüchen" ما تتماشاش.`,
      rule: "Unterschied zwischen + Dativ + und + Dativ", ex: "Der Unterschied **zwischen** Tee und Kaffee ist groß.", exTr: "الفرق بين التاي والقهوة كبير." },
    34: { ok: "IRGENDEIN", type: "pronoun", keyword: "nicht irgendein + Nomen", bed: "أيّ (موش أيّ)",
      text: `"Nicht ___ Topf darf es … sein": "nicht irgendein" = موش أيّ كان.\n✓ "irgendein" = أيّ (مذكّر، Nominativ).\n✗ "dafür" = لهذا (Pronominaladverb)، موش قبل اسم.\n✗ "weiter" = أكثر / بعد (ظرف)، ما تتركّبش قبل "Topf".`,
      rule: "irgendein + Nomen = ein beliebiger (Maskulinum Nominativ)", ex: "Ich suche nicht **irgendein** Buch.", exTr: "ما نلوّجش على أيّ كتاب." },
    35: { ok: "DAFÜR", type: "pronoun_adverb", keyword: "Voraussetzung dafür, dass …", bed: "لهذا",
      text: `"Die zweite Voraussetzung ___, dass die Gerichte auch gelingen": "Voraussetzung für" + dass-Satz ← "dafür".\n✓ "dafür" = لهذا (für + das).\n✗ "dazu" = لهذا / إليه: "Voraussetzung dazu" ما تتقالش بنفس الشكل، و"für" هو الحرف المعتاد.\n✗ "daran" = على هذا (an + das)، و"Voraussetzung daran" ما تتقالش.`,
      rule: "Voraussetzung für + Akk. → dafür, dass …", ex: "Fleiß ist die Voraussetzung **dafür**, dass man gewinnt.", exTr: "الاجتهاد شرط باش الواحد يربح." },
    36: { ok: "DAVON", type: "pronoun_adverb", keyword: "abhängen von → davon", bed: "من هذا",
      text: `"Jetzt hängt es nur noch ___ ab, was …": "abhängen von" ← "davon".\n✓ "davon" = من هذا (von + das).\n✗ "daran" = "es hängt daran" ممكنة في الكلام، بصح مع "ab" المنفصلة المعتاد "davon".\n✗ "dazu" = لهذا (zu + das)، و"abhängen dazu" ما تتقالش.`,
      rule: "abhängen von + Dat. → davon abhängen, was / ob …", ex: "Es hängt **davon** ab, wie du dich fühlst.", exTr: "يعتمد على كيفاش تحسّ." },
    37: { ok: "WEITER", type: "verb", keyword: "weiterhelfen (helfen … weiter)", bed: "يفيد",
      text: `"Helfen die Bücher nicht ___": الفعل المنفصل "weiterhelfen" = يفيد.\n✓ "weiter" = الجزء المنفصل (helfen … weiter).\n✗ "dazu" = لهذا، وما يكمّلش فعل "helfen" المنفصل.\n✗ "zu" = إلى، ما تعطيش "weiterhelfen".`,
      rule: "trennbar: weiterhelfen → hilft … weiter", ex: "Der Rat **hilft** mir nicht **weiter**.", exTr: "النصيحة ما تفيدنيش." },
    38: { ok: "DAZU", type: "pronoun_adverb", keyword: "führen zu → dazu, dass …", bed: "إلى هذا",
      text: `"Das führt ___, dass man(n) … immer öfter international kocht": "führen zu" ← "dazu".\n✓ "dazu" = إلى هذا (zu + das).\n✗ "daran" = على هذا (an + das)، و"führen daran" ما تتقالش.\n✗ "davon" = من هذا (von + das)، و"führen davon" ما تتقالش.`,
      rule: "führen zu + Dat. → dazu führen, dass …", ex: "Stress **führt** oft **dazu**, dass man krank wird.", exTr: "الضغط برشا مرّات يوصّل لإنّو الواحد يمرض." },
    39: { ok: "DASS", type: "conjunction", keyword: "ist aber, dass …", bed: "إنّو",
      text: `"Das größte Problem … ist aber, ___ es viel zu aufwändig ist": محتوى المشكلة.\n✓ "dass" = إنّو (+ فعل في الآخر).\n✗ "was" = شنوّة / اللي، و"ist aber, was es …" ما تتركّبش.\n✗ "damit" = باش (غرض)، موش محتوى.`,
      rule: "Das Problem ist, dass + Nebensatz", ex: "Mein Problem ist, **dass** ich keine Zeit habe.", exTr: "مشكلتي إنّو ما عنديش وقت." },
    40: { ok: "DARAN", type: "pronoun_adverb", keyword: "das Interessante daran", bed: "فيه (في هذا)",
      text: `"Das Interessante ___ ist, dass …": "daran" = في هذا الموضوع.\n✓ "daran" = في هذا (an + das: das Interessante daran).\n✗ "damit" = بهذا: "das Interessante damit" أقلّ استعمالًا، والمعتاد "daran".\n✗ "dafür" = لهذا، موش معنى "في هذا الأمر".`,
      rule: "das Interessante / Schöne / Schwierige daran = an der Sache", ex: "Das Schwierige **daran** ist die Zeit.", exTr: "الصعب فيه هو الوقت." },
  },

  // ───────────── [30] Man(n) kocht selbst (معدل) ─────────────
  30: {
    31: { ok: "ZUM", type: "preposition", keyword: "zum Kochtopf greifen", bed: "لـ (القدر)",
      text: `"greifen jetzt selbst ___ Kochtopf": "greifen zu" + Dativ، و"Kochtopf" مذكّر: "zu dem" = "zum".\n✓ "zum" = zu + dem (greifen zu).\n✗ "um" = حول / باش، و"um Kochtopf" ما تتقالش.\n✗ "für" = لـ، و"greifen für Kochtopf" ما تتقالش.`,
      rule: "greifen zu + Dativ: zum Kochtopf, zum Buch", ex: "Er greift **zum** Telefon.", exTr: "هو ياخذ التلفون." },
    32: { ok: "FÜR", type: "preposition", keyword: "ein Grund für", bed: "لـ",
      text: `"Ein Grund ___ diese Entwicklung mag sein": "Grund für" + Akkusativ.\n✓ "für" = لـ.\n✗ "dafür" = لهذا، وبعدو اسم موش جملة.\n✗ "um" = حول / باش، و"Grund um" ما تتقالش.`,
      rule: "Grund / Ursache für + Akk.", ex: "Das ist der Grund **für** den Streit.", exTr: "هذا هو سبب الخلاف." },
    33: { ok: "ZWISCHEN", type: "preposition", keyword: "zwischen A und B", bed: "بين",
      text: `"Unterschied besteht ___ den Ansprüchen … und denen eines Hobbykochs": طرفين.\n✓ "zwischen" = بين.\n✗ "als" = من / كـ (مقارنة)، و"Unterschied als" ما تتقالش.\n✗ "für" = لـ، موش بين طرفين.`,
      rule: "zwischen + Dativ … und … (Vergleich zweier Seiten)", ex: "**Zwischen** Stadt und Land gibt es Unterschiede.", exTr: "بين المدينة والريف فما فروقات." },
    34: { ok: "DENEN", type: "pronoun", keyword: "denen = die Ansprüche (Dativ Pl.)", bed: "تلك (متاع)",
      text: `"zwischen den Ansprüchen … und ___ eines Hobbykochs": "denen" يعوّض "den Ansprüchen" (جمع Dativ).\n✓ "denen" = تلك (Dativ جمع، بعد "zwischen").\n✗ "dass" = إنّو (رابط)، موش ضمير يعوّض اسم.\n✗ "daran" = على هذا (Pronominaladverb)، موش ضمير يرجع لاسم جمع.`,
      rule: "denen (Dativ Pl.) als Pronomen: den Ansprüchen … und denen eines …", ex: "Die Regeln hier und **denen** dort sind gleich.", exTr: "القواعد هنا وتلك اللي هناك نفس الشي." },
    35: { ok: "ALS", type: "verb_prep", keyword: "gelten als + Adjektiv", bed: "يتعتبر",
      text: `"Alles andere gilt ___ stillos": "gelten als" = يتعتبر.\n✓ "als" = كـ (gelten als).\n✗ "für" = لـ: "gilt für" = يسري على، موش يتعتبر.\n✗ "daher" = لهذا السبب (ظرف)، موش حرف ربط بصفة.`,
      rule: "gelten als + Adjektiv / Nomen = betrachtet werden als  |  gelten für = betreffen", ex: "Er **gilt** als zuverlässig.", exTr: "يتعتبر موثوق." },
    36: { ok: "DAVON", type: "pronoun_adverb", keyword: "davon abhängen", bed: "من هذا",
      text: `"Jetzt hängt es nur noch ___ ab, was …": "abhängen von".\n✓ "davon" = من هذا (von + das).\n✗ "daran" = "hängt daran" ممكنة في الكلام، بصح مع "ab" المعتاد "davon".\n✗ "dazu" = لهذا، و"abhängen dazu" ما تتقالش.`,
      rule: "abhängen von → davon abhängen", ex: "Alles hängt **davon** ab.", exTr: "كلّ شي يعتمد على هذا." },
    37: { ok: "UM", type: "preposition", keyword: "um die Ecke", bed: "حول (الزاوية)",
      text: `"zum Dönerstand ___ die Ecke gegangen": تعبير "um die Ecke" = قريب، في الزاوية.\n✓ "um" = حول (um + Akk.).\n✗ "zum" = zu + dem، و"zum die Ecke" فيها أداة مرتين.\n✗ "zwischen" = بين، و"zwischen die Ecke" ما تتقالش.`,
      rule: "um die Ecke = in der Nähe, gleich nebenan", ex: "Der Bäcker ist gleich **um** die Ecke.", exTr: "الخبّاز قريب في الزاوية." },
    38: { ok: "DAZU", type: "pronoun_adverb", keyword: "dazu führen, dass …", bed: "إلى هذا",
      text: `"Das führt ___, dass man(n) … kocht": "führen zu" ← "dazu".\n✓ "dazu" = إلى هذا (zu + das).\n✗ "daran" = على هذا، و"führen daran" ما تتقالش.\n✗ "damit" = بهذا، و"führt damit, dass" ما تتقالش.`,
      rule: "führen zu → dazu führen, dass", ex: "Das **führt dazu**, dass wir früher gehen.", exTr: "هذا يوصّل لإنّو نمشيو بكري." },
    39: { ok: "DASS", type: "conjunction", keyword: "ist aber, dass", bed: "إنّو",
      text: `"Das größte Problem … ist aber, ___ es viel zu aufwändig ist": محتوى.\n✓ "dass" = إنّو.\n✗ "denn" = خاطر (+ فعل في الثانية)، وهنا "ist" في الآخر.\n✗ "damit" = باش (غرض)، موش محتوى.`,
      rule: "dass-Satz nach 'ist aber,'", ex: "Schade ist nur, **dass** er fehlt.", exTr: "الحسرة بس إنّو غايب." },
    40: { ok: "GENAUSO", type: "adjective_adverb", keyword: "genauso gut … wie", bed: "نفس (الجودة)",
      text: `"mit weniger Aufwand ___ gut ein Festmahl zubereiten können wie sie": مقارنة تساوي: "genauso … wie".\n✓ "genauso" = بنفس (genauso gut wie).\n✗ "als" = من (Komparativ)، و"genauso gut als" ما تتقالش (بعد "genauso" نستعملو "wie").\n✗ "zum" = zu + dem، ما يركّبش قبل "gut" هكا.`,
      rule: "genauso + Adjektiv + wie (Gleichheit)  |  Komparativ + als", ex: "Er kocht **genauso** gut wie seine Mutter.", exTr: "هو يطيّب نفس الجودة كيما أمّو." },
  },

  // ───────────── [31] Der Hund als intelligentes Wesen ─────────────
  31: {
    31: { ok: "WAS", type: "fixed_expression", keyword: "was … betrifft", bed: "بالنسبة لـ",
      text: `"aber ___ ihre Intelligenz betrifft, eher mit geringen Begabungen ausgestattet": تعبير "was … betrifft" = بالنسبة لـ.\n✓ "was" = (was … betrifft = بالنسبة لـ).\n✗ "das" = الـ / هذا: "das ihre Intelligenz betrifft" تعني "اللي يخصّ ذكاءها" (ضمير موصول)، بصح التعبير الثابت بـ "was".\n✗ "welche" = اللي (جمع / مؤنّث)، موش تعبير "was … betrifft".`,
      rule: "was + Akk. betrifft = hinsichtlich (feste Wendung)", ex: "**Was** das Wetter betrifft, bin ich optimistisch.", exTr: "بالنسبة للطقس، أنا متفائل." },
    32: { ok: "JETZT", type: "adjective_adverb", keyword: "doch jetzt (Gegenwart)", bed: "توّا",
      text: `"Doch ___ haben wissenschaftliche Experimente … die Hundeehre gerettet": تحوّل من القديم ("Bislang") للحاضر.\n✓ "jetzt" = توّا (ظرف زمني، الفعل بعدو في الثانية).\n✗ "übrigens" = على فكرة: ممكنة نحويًّا، بصح هنا نقابلو "Bislang" بـ"jetzt" موش ملاحظة جانبية.\n✗ "dass" = إنّو (رابط + فعل في الآخر)، و"haben" هنا في الثانية.`,
      rule: "bislang … jetzt = früher … heute (Zeitgegensatz)", ex: "Früher war es leise, **jetzt** ist es laut.", exTr: "قبل كان هادئ، توّا صاخب." },
    33: { ok: "AN", type: "preposition", keyword: "an der Universität (Experimente an)", bed: "في (الجامعة)",
      text: `"Experimente ___ der Universität Wien und am Max-Planck-Institut": "an" + Dativ (مؤسسات بحثية).\n✓ "an" = في (an der Universität).\n✗ "aus" = من: "aus der Universität" تعني خرجت منها، موش مكان التجارب.\n✗ "zu" = إلى، و"Experimente zu der Universität" ما تتقالش.`,
      rule: "an der Universität / am Institut (Ort der Forschung)", ex: "Er forscht **an** der Universität Berlin.", exTr: "هو يعمل بحث في جامعة برلين." },
    34: { ok: "AUS", type: "preposition", keyword: "aus + Dativ auswählen", bed: "من بين",
      text: `"das richtige ___ verschiedenen Bildern auswählen": "aus" = من بين مجموعة.\n✓ "aus" = من بين (auswählen aus).\n✗ "an" = على / عند، و"auswählen an Bildern" ما تتقالش.\n✗ "zu" = إلى، موش اختيار من بين.`,
      rule: "aus + Dativ auswählen = unter mehreren wählen", ex: "Sie wählt **aus** drei Kleidern eines aus.", exTr: "هي تختار من بين ثلاثة فساتين." },
    35: { ok: "DARAUF", type: "pronoun_adverb", keyword: "darauf (auf den Bildern)", bed: "عليها",
      text: `"und ___ entweder einen Menschen oder eine Landschaft erkennen": "darauf" = على الصور.\n✓ "darauf" = عليها (auf + das / auf den Bildern).\n✗ "dem" = أداة Dativ، و"und dem entweder einen" ما تتقالش.\n✗ "welche" = اللي (جمع)، وما تعطيش معنى "على الصور".`,
      rule: "darauf = auf diesen Bildern (Pronominaladverb)", ex: "Auf dem Foto sieht man mich, **darauf** auch meine Mutter.", exTr: "في الصورة تشوفني، وعليها كذلك أمّي." },
    36: { ok: "SO DASS", type: "conjunction", keyword: "so dass (Folge)", bed: "بحيث",
      text: `"Der Monitor war mit einem Touchscreen ausgestattet, ___ der Hund … tippen konnte": نتيجة التجهيز: بحيث ينجّم الكلب يضغط.\n✓ "so dass" = بحيث (نتيجة، + فعل في الآخر).\n✗ "dass" = إنّو (محتوى)، وبلا "so" ما تعطيش معنى النتيجة.\n✗ "welche" = اللي (جمع)، موش رابط نتيجة.`,
      rule: "so dass = Folge (Nebensatz, Verb am Ende)", ex: "Es war laut, **so dass** wir nichts hörten.", exTr: "كان صاخب، بحيث ما سمعنا شي." },
    37: { ok: "NICHT NUR", type: "conjunction", keyword: "nicht nur … sondern auch", bed: "موش بس",
      text: `"Der Hund hing ___ mit … Begeisterung am Bildschirm …, sondern er war auch … treffsicher": الجزء الثاني "sondern … auch" يطلب "nicht nur" قبلو.\n✓ "nicht nur" = موش بس (يكمّل مع "sondern … auch").\n✗ "keine" = ما فماش (نفي)، موش بنية "nicht nur".\n✗ "übrigens" = على فكرة، موش جزء من الزوج.`,
      rule: "nicht nur …, sondern (…) auch …", ex: "Er war **nicht nur** nett, sondern auch klug.", exTr: "هو موش بس لطيف، بل ذكي زادا." },
    38: { ok: "DENEN", type: "pronoun", keyword: "von denen (Relativpronomen Dativ Pl.)", bed: "منها",
      text: `"zwei Gefäße, von ___ eins Futter enthielt": مرجعو "Gefäße" (جمع)، و"von" + Dativ.\n✓ "denen" = Dativ جمع (von denen = منها).\n✗ "welche" = Nominativ / Akkusativ جمع، و"von welche" تحتاج "welchen".\n✗ "dem" = Dativ مفرد، والمرجع جمع.`,
      rule: "von + denen (Plural Dativ Relativpronomen): von denen eins …", ex: "Ich habe zwei Brüder, von **denen** einer in Berlin lebt.", exTr: "عندي زوز خاوة، واحد منهم يعيش في برلين." },
    39: { ok: "DASS", type: "conjunction", keyword: "schließen, dass …", bed: "إنّو",
      text: `"Daraus schließen die Forscher …, ___ bestimmte Muster … interpretiert werden können": محتوى الاستنتاج.\n✓ "dass" = إنّو (+ فعل في الآخر).\n✗ "das" = أداة / ضمير إشارة بحرف s واحد، موش رابط.\n✗ "was" = اللي / شنوّة، موش رابط لمحتوى الاستنتاج.`,
      rule: "schließen, dass + Nebensatz  |  das = Artikel / Pronomen", ex: "Ich schließe daraus, **dass** er lügt.", exTr: "نستنتج من هذا إنّو يكذب." },
    40: { ok: "KEINE", type: "pronoun", keyword: "keine + Plural (Akk.)", bed: "ما فما",
      text: `"brachten ___ vergleichbaren Resultate": تجارب الذئاب ما عطاتش نتائج مشابهة (والجملة اللي بعدها: الكلب تعلّم هذي القدرات).\n✓ "keine" = ما فما (نفي لـ "Resultate" جمع Akkusativ).\n✗ "welche" = بعض: "welche vergleichbaren Resultate" ما تتقالش هكا.\n✗ "an" = على / عند، ما تركّبش قبل "Resultate".`,
      rule: "kein- + Plural: keine vergleichbaren Resultate (Akk. Plural)", ex: "Der Test brachte **keine** neuen Ergebnisse.", exTr: "الاختبار ما جابش نتائج جديدة." },
  },
};
