// "ليش هذا النوع؟" — part B1: positions 18, 20, 33–39, 42–48 (the twin variants 40/41 etc. are resolved by the builder through identical sentences).
export default {
  18: { 31: `"schnell zahlt der Kunde drauf, ___ … Geld zu sparen": بعد الفاصلة جاي "zu + Infinitiv" (sparen) بدون فاعل جديد: نحتاج حرف يفتح مجموعة Infinitiv ببديل.`,
    32: `"nicht ___ Gelegenheit": "Gelegenheit" مؤنّث مفرد بدون أداة: نحتاج كلمة تطابقو في النوع والعدد.`,
    33: `"ein Argument ___ illegale Arbeiter": "Argument" يتبعو حرف جرّ ثابت + Akkusativ.`,
    34: `"Abgesehen ___, dass es strafbar ist": "abgesehen von" + جملة dass: نحتاج Pronominaladverb يحيل على الجملة.`,
    35: `"Das Finanzamt ___ eine ordentliche Rechnung … sehen": فاعل مفرد + Infinitiv "sehen" في الآخر: نحتاج فعل مساعد مصرّف.`,
    36: `"mängelfreie Bauten ___ eher die Ausnahme dar": "dar" جزء منفصل في الآخر: نحتاج الفعل المصرّف (darstellen) بصيغة الجمع.`,
    37: `"Verbraucher leer ___": "leer ausgehen" تعبير ثابت: نحتاج فعل Infinitiv (بعد modal قبلو).`,
    38: `"für ___ Fälle": "Fälle" جمع Akkusativ: نحتاج كلمة جمع تطابق.`,
    39: `"dann ___ es gleich mehrere Behörden mit": "mit" في الآخر: الفعل المنفصل "mitbekommen" يحتاج جزءو المصرّف.`,
    40: `"braucht der Auftraggeber ___ einen Anwalt": الجملة كاملة (فاعل + فعل + مفعول): نحتاج ظرف تكرار يضاف.` },
  20: { 31: `"Viele Verbraucher fragen sich beispielsweise, ___ Bio-Produkte nun auch wirklich die gesünderen sind": الفعل "sind" في الآخر: سؤال غير مباشر بنعم/لا، نحتاج رابط.`,
    32: `"___ sind Bio-Produkte teurer": الفعل "sind" جاي مباشرة بعد الفراغ: ظرف ربط في الخانة الأولى.`,
    33: `"Sie ___ weniger Nitrat, mehr Nährstoffe": فاعل جمع + مفعول: الجملة بلا فعل مصرّف.`,
    34: `"steht ___ ihrem Einkaufsverhalten ein ökologisches Bewusstsein": بعد الفراغ "ihrem Einkaufsverhalten" (Dativ): حرف جرّ بـ Dativ يعبّر على الموقع.`,
    35: `"Sie ___ unsere Umwelt": فاعل مفرد (الزراعة) + مفعول Akkusativ: نحتاج فعل مصرّف.`,
    36: `"Bio-Lebensmittel kommen ___ ökologischer Landwirtschaft": "kommen" + مصدر المنتج: حرف جرّ بـ Dativ.`,
    37: `"beispielsweise ___ Wochenmärkten": اسم جمع Dativ يعبّر على المكان: حرف جرّ.`,
    38: `"dürfen weder Kunstdünger noch … ___ werden": "werden" في الآخر مع modal: نحتاج Partizip II.`,
    39: `"dürfen ___ nur Bio-Lebensmittel benutzt werden": قبل "nur": ظرف تأكيد.`,
    40: `"Diese Richtlinien garantieren, ___ die Produkte … sind": الفعل "sind" في الآخر: جملة محتوى بعد "garantieren".` },
  33: { 31: `"steht … ein Betreuungsplatz … ___ Verfügung": "Verfügung" ما يجي إلا في تعبير ثابت مع "stehen": حرف جرّ مدمج.`,
    32: `"drei Jahre ___ dem Kind zu Hause zu bleiben": بعد الفراغ "dem Kind" (Dativ) = ملازمة شخص: حرف جرّ بـ Dativ.`,
    33: `"…zu bleiben, ___ hat den Vorteil, dass …": بعد الفراغ فعل "hat" ومفعول: فاعل ناقص، والفاعل هو الفكرة اللي قبل: ضمير.`,
    34: `"___ wird die Elternzeit … zu einem gravierenden Problem": الفعل "wird" جاي مباشرة بعد الفراغ: ظرف ربط (خانة أولى، فعل ثاني).`,
    35: `"___ auch andere Dinge machen Familien … das Leben schwer": الفعل "machen" في الثانية بعد "auch andere Dinge": رابط Position 0 لا يغيّر الترتيب.`,
    36: `"nicht still am Tisch, ___ stören mit ihrem Lachen": قبل الفراغ "nicht" (نفي) وبعدو فعل: رابط Position 0 يصحّح النفي.`,
    37: `"stört das ___": "stören" يطلب مفعول Akkusativ وما فماش واحد: ضمير نفي Akkusativ.`,
    38: `"Anwohner Prozesse gegen Kindergärten und Spielplätze an, ___ die Kinder die Ruhe … stören": "stören" في الآخر: جملة فرعية تعطي سبب.`,
    39: `"so angeordnet, ___ mit einem Kinderwagen kein Durchkommen ist": "so …, ___" + "ist" في الآخر: جملة فرعية نتيجة.`,
    40: `"Anspruch ___ einen Platz": "Anspruch" يتبعو حرف جرّ ثابت + Akkusativ.` },
  34: { 31: `"…in einer Kindertagesstätte ___ Verfügung": "Verfügung" ما يجي إلا في تعبير ثابت مع "stehen": حرف جرّ مدمج.`,
    33: `"Kind und Karriere zu ___ ist … unmöglich": بعد "zu" و"ist" بعدو: نحتاج Infinitiv.`,
    36: `"Spielplätze ___ von Gerichts wegen geschlossen": Partizip II "geschlossen" في الآخر + فاعل جمع: Passiv يحتاج "werden".`,
    38: `"haben ___ schon andere Reisende breitgemacht": "sich breitmachen" فعل انعكاسي: لازم ضمير انعكاسي.`,
    40: `"Man meint ___ die Kinder": ما فماش حرف جرّ + مفعول جاي: نحتاج Pronominaladverb يحيل على الموضوع.` },
  35: { 31: `"Werden Kinder … ___ brutale … Medieninhalte gewaltbereiter?": بعد الفراغ اسم جمع Akkusativ يعبّر على الوسيلة / السبب: حرف جرّ.`,
    32: `"vor allem": "allem" ما يتجمّعش إلا مع "vor" في معنى خاصةً: تعبير ثابت.`,
    33: `"untersucht, ___ Bilder in den Köpfen … herumgeistern": الفعل في الآخر + سؤال على النوع: كلمة سؤال بنهاية جمع.`,
    34: `"Die Fantasien der Jungen und Mädchen ___ sich deutlich": فاعل جمع + "sich": نحتاج فعل مصرّف.`,
    35: `"Die Schülerinnen ___ das Märchen dagegen meist gewaltfrei enden": فاعل جمع + "enden" Infinitiv في الآخر: "lassen" مصرّف.`,
    36: `"zeige jedoch, ___ sehr Bilder aus den Medien … prägen": الفعل "prägen" في الآخر + "sehr": رابط سؤال غير مباشر على الدرجة.`,
    37: `"die Vorstellungswelt ___ Jugendlichen": بين اسمين وبدون أداة: الجمع يستعمل "von" بدل Genitiv.`,
    38: `"das Vokabular, ___ dem man die Welt begreift": بعد الفراغ "dem" (Dativ مفرد) = الوسيلة: حرف جرّ يسبق الضمير الموصول.`,
    39: `"keine Vorstellung davon entwickeln, ___ Musik überhaupt ist": "ist" في الآخر + السؤال على الماهية: كلمة سؤال.`,
    40: `"Gefährlich werde es aber ___, wenn positive Alternativbilder fehlten": جاي بعدو "wenn": ظرف زمني يتكامل مع جملة "wenn".` },
  36: { 31: `"haben Menschen ___ geträumt, jederzeit mobil zu sein": "träumen von" + zu-Infinitiv: Pronominaladverb يفتح المحتوى.`,
    32: `"___ Auto fährt, hat in seinem Leben etwas erreicht": "fährt" في الآخر + "hat" بعدو: فاعل عام (كلّ من).`,
    33: `"Daraus folgt, ___ für so viele Fahrzeuge der Platz nicht mehr ausreicht": "ausreicht" في الآخر: جملة محتوى بعد "folgt".`,
    34: `"Die Straßen sind ___ nicht breit genug": بين "sind" و"nicht breit": ظرف تكرار.`,
    35: `"…länger, als sie ___": بعد "als sie" المقارنة تحتاج فعل مصرّف جمع في الآخر.`,
    36: `"Nichts geht mehr, ___ die Zahl … ist zu groß geworden": "ist" بعد الفاعل: Hauptsatz، والجملة سبب: رابط Position 0.`,
    37: `"Die Erwärmung der Luft führt ___, dass …": "führen zu" + جملة dass: Pronominaladverb.`,
    38: `"___ dem Verkehrsinfarkt zuvorzukommen … haben einige Großstädte damit begonnen": "zuvorzukommen" (zu-Infinitiv) + "haben": رابط الغرض.`,
    39: `"In den großen Metropolen ___ sich die Tunnel … durch das Erdreich": فاعل جمع + "sich": نحتاج فعل مصرّف.`,
    40: `"…noch viel Überzeugungsarbeit ___ wird": "wird" في الآخر + مفعول: نحتاج Infinitiv.` },
  37: { 31: `"Doch ___ das Gegenteil ist der Fall": قبل اسم محدّد بأداة: ظرف تقوية بدون نهاية.`,
    32: `"Sie sind … zu erstaunlichen kognitiven Leistungen ___": بعد "sind" في الآخر مع "zu": الصفة اللي تحكم "zu + Dativ".`,
    33: `"Im Laufe der Zeit ___ sie hochspezialisierte Sinnesfähigkeiten": الجملة تبدا بعنصر زمني ثم فعل ثم الفاعل "sie": فعل جمع Präteritum.`,
    34: `"Einige Arten lernen durch ___": بعد "durch" وبدون أداة: اسم (مصدر).`,
    35: `"wurde Fischen ___ nicht einmal zugetraut": "noch nicht einmal": ظرف قبل النفي.`,
    36: `"Der Forscher bewies ___ auch als Erster, dass …": جملة كاملة والفراغ زائد جانبي: ظرف إضافة.`,
    37: `"___ warum wurden die Fähigkeiten … unterschätzt?": بعد الفراغ "warum wurden" (فعل ثاني): رابط Position 0 يقابل ما سبق.`,
    38: `"___ intelligent halten wir oft nur Tiere": "halten" يتبعو "für" + صفة: حرف جرّ ثابت.`,
    39: `"mit ganz anderen Lebensbedingungen zurechtkommen ___ Tiere an Land": بعد "anderen": رابط المقارنة.`,
    40: `"Allan rät, ___ mehr über Fische herausfinden wolle, solle …": "wolle" في الآخر + فاعل مجهول: ضمير عام (من).` },
  38: { 31: `"Kinder sind oft … überfordert, ___ ist es wichtig …": "ist es" بعد الفراغ: ظرف ربط للنتيجة في الخانة الأولى.`,
    32: `"___ immer ist der kürzeste Weg auch der ungefährlichste": الفراغ مع "immer" يملا الخانة الأولى: ظرف نفي.`,
    33: `"sich voll auf das Kind ___": "sich … auf" ثابت: نحتاج الفعل Infinitiv الأخير.`,
    34: `"nicht nur erklären, sondern sich auch ___ daran halten": "nicht nur … sondern auch" + قبل "daran halten": ظرف تأكيد.`,
    35: `"Manchmal ist es ___, wenn die Großen …": بعد "ist es" نحتاج صفة تقيّم.`,
    36: `"Schritt ___ Schritt": الاسم يتكرّر حول حرف جرّ: تعبير ثابت.`,
    37: `"die wichtigsten Regeln für das ___ im Straßenverkehr": بعد "das" وقبل "im": نحتاج اسم.`,
    38: `"noch mögliche ___ Situationen besprechen": قبل اسم جمع بعد "mögliche": صفة بنهاية -e.`,
    39: `"sich ___ im Straßenverkehr zu verhalten": بين "sich" و"zu verhalten": ظرف طريقة بدون نهاية.`,
    40: `"selbstständig ___ zu finden": "finden" يطلب مفعول وما فماش أداة: اسم جمع.` },
  39: { 31: `"…schmerzt schnell, ___ Schreiben mit der Hand ungewohnt ist": "ist" في الآخر: جملة فرعية للسبب.`,
    32: `"in der Schule ___ mehr Probleme": قبل "mehr": تعبير ثابت للزيادة.`,
    33: `"einen neuen Trend, der mit Handschrift zu ___ hat": "zu … hat": Infinitiv.`,
    34: `"eher wie ___ als wie Wörter": بعد "wie" بدون أداة، ومقارنة مع "Wörter" (جمع): اسم جمع.`,
    35: `"…empfunden ___": Partizip II + فاعل جمع في الآخر: "werden" (Passiv).`,
    36: `"Erfahrungen ___ hat auch die Wiener Designerin … gemacht": "Erfahrungen machen mit" + مرجع لشيء مذكور: Pronominaladverb.`,
    37: `"Auf ___ Weise vermittelt die Künstlerin das Thema": قبل "Weise" (مؤنّث Akk): صفة بنهاية -e.`,
    38: `"…ein Anliegen, ___ Kinder die Freude … wiederentdecken": الفعل في الآخر: جملة محتوى بعد "Anliegen".`,
    39: `"coole Einladungen und Logos zu ___": بعد "zu": Infinitiv.`,
    40: `"bis ihnen das flüssig von der Hand ___": فاعل مفرد + "bis": فعل مصرّف في الآخر.` },
  42: { 31: `"viele Angebote wurden ___": "wurden" + نهاية الجملة: Partizip II.`,
    32: `"Das Angebot gewinne kontinuierlich neue ___": بعد "neue": اسم جمع.`,
    33: `"aus ___ des Umweltschutzes": بعد "aus" وقبل Genitiv: اسم جمع.`,
    34: `"Kommt der Nachtzug also wieder in ___?": "in ___ kommen": اسم بدون أداة.`,
    35: `"dem Flugzeug als Reisemittel ___ machen": الاسم يكمّل الفعل "machen".`,
    36: `"ist es manchmal ___ schön ungemütlich": قبل صفة: ظرف درجة.`,
    37: `"___ schrecke die lange Reisezeit viele ab": "schrecke" بعد الفراغ: ظرف ربط (إضافة).`,
    38: `"___ umweltschonendes Transportmittel ist der Nachtzug …": اسم بدون أداة + "ist": "als" = بصفته.`,
    39: `"…vorbei, ___ man von dem sanften Rattern … gewiegt wird": "wird" في الآخر: جملة فرعية لحدثين متزامنين.`,
    40: `"war etwas ___": بعد "war etwas": صفة.` },
  43: { 31: `"sie durchaus in der ___ ihren Namen … herauszuhören": "in der ___" + zu-Infinitiv: اسم مؤنّث في تعبير ثابت.`,
    32: `"Nach eigenen ___ lieferten die Forscher …": بعد "eigenen": اسم جمع.`,
    33: `"das ___ von 78 Katzen untersucht": بعد "das" وقبل "von": اسم محايد.`,
    34: `"___ spielten sie den Tieren vier japanische Wörter … vor": "spielten" بعد الفراغ: ظرف ترتيب.`,
    35: `"nahm die Aufmerksamkeit der Katzen immer ___ ab": "immer ___": ظرف تدرّج.`,
    36: `"wenn nicht der Katzenbesitzer selbst … sprach, ___ eine fremde Person": "nicht … ___": رابط تصحيح.`,
    37: `"ihren Namen von ___ ihrer Artgenossen unterscheiden": بعد "von" + Genitiv جمع: ضمير يعوّض "Namen".`,
    38: `"…lernfähig – ___ sie bereit sind mitzumachen": "sind … mitzumachen" في الآخر: رابط شرط.`,
    39: `"Aus vorherigen Untersuchungen ist ___, dass …": بعد "ist": صفة.`,
    40: `"warum ist es dann ___ so schwierig": بين "dann" و"so schwierig": ظرف تقوية.` },
  44: { 31: `"Schlafwagen wieder in ___ bringt": "in ___ bringen": اسم بدون أداة.`,
    32: `"aber ___ so schnell wie mit dem Flugzeug ist es nicht": "ganz so … wie": ظرف قبل "so".`,
    33: `"könnten wir das Angebot rasch deutlich ___": "könnten" + الفعل الأساسي Infinitiv في الآخر.`,
    34: `"___ seien in der Regel acht Mitarbeiter … unterwegs": "seien" بعد الفراغ: ظرف تلخيص.`,
    35: `"eine ___ Intercity-Nachtverbindung gestartet": بين "eine" واسم مؤنّث: صفة بنهاية -e.`,
    36: `"…zusätzliche Mitarbeiter ___ werden": "sollen … werden": Partizip II.`,
    37: `"warum nicht ___ dieses Angebot … übernehmen sollten": فاعل جمع + "sollten": اسم جمع.`,
    38: `"…Flugreisen … ___ ein klimafreundliches Mobilitätsangebot zu reduzieren": بعد الفراغ اسم Akkusativ يعبّر على الوسيلة: حرف جرّ.`,
    39: `"…Europafarben ___ wäre": "wäre" في الآخر: Zustandspassiv يحتاج Partizip II.`,
    40: `"wurde ___ damals hoher Verluste 2016 eingestellt": بعد الفراغ Genitiv يعبّر على السبب: حرف جرّ.` },
  45: { 31: `"das moderne Leben ist ___ geworden": "ist … geworden": صفة.`,
    32: `"Herz-Kreislauf-Erkrankungen ___ … die Todesursache Nummer Eins": فاعل جمع وخبر بدون فعل: "sein" مصرّف.`,
    33: `"Wichtig ist, ___ richtig zu trainieren": "Wichtig ist, ___ …zu trainieren": ظرف يحيل على النشاط.`,
    34: `"Ausdauertraining ___ Verbrennung von Sauerstoff": اسم بدون أداة: حرف جرّ بـ Dativ.`,
    35: `"Dabei ___ der Puls kontrolliert werden": "kontrolliert werden": modal.`,
    36: `"___ mehr Menschen den Schritt … wagen sollten, machen zahlreiche Studien deutlich": "sollten" في آخر الجزء ثم "machen": جملة dass في الخانة الأولى.`,
    37: `"Rund 40 Prozent ___ Deutschen": بعد "Prozent" Genitiv جمع.`,
    38: `"nicht selten mit ___ Herzinfarkt": "mit" + Dativ مذكّر.`,
    39: `"immer häufiger ___ Frauen": اسم جمع بدون أداة: حرف جرّ.`,
    40: `"minimiert sich das Risiko … zu erleiden, ___": ظرف في آخر الجملة يعبّر على الدرجة.` },
  46: { 31: `"Senioren sind heute höchst ___, aktiv": بعد "höchst": صفة بدون نهاية.`,
    32: `"wie es ___ verschiedenen deutschen Universitäten angeboten wird": قبل اسم جمع Dativ: مكان.`,
    33: `"___ in Trier waren … über 130 Personen": قبل حرف جرّ + اسم: ظرف حصر.`,
    34: `"___ folgten die neueren Sprach- und Literaturwissenschaften": "folgten" بعد الفراغ: "darauf folgen".`,
    35: `"Die Gründe dafür ___ sein, dass Frauen …": فاعل جمع + "sein": فعل مساعد.`,
    36: `"Frauen … häufig ___ eine berufliche Karriere verzichteten": "verzichten" يتبعو "auf" + Akkusativ.`,
    37: `"___ setzten sie sich für die Familie … ein": "setzten" بعد الفراغ: ظرف ربط.`,
    38: `"deren Einsatz … zu ___ gekommen war": "zu kurz kommen": تعبير ثابت.`,
    39: `"___ dessen sehen sie keine Veranlassung": بعد الفراغ Genitiv "dessen": حرف جرّ للسبب.`,
    40: `"Er wird gespeist ___ die Vitalität …": Passiv مع مصدر: حرف جرّ.` },
  47: { 31: `"Senioren sind … rege, aktiv und ___ vielfach die Chance": بعد "und" ولا فعل: فعل مصرّف جمع.`,
    32: `"wie es an … Universitäten ___ wird": "wird": Partizip II.`,
    33: `"als Gasthörer eingeschrieben": "als + Nomen": الصفة.`,
    34: `"Angebote … wurden ___ weniger häufig gewählt": مقابلة: ظرف.`,
    35: `"Die Gründe dafür ___ sein, dass Frauen …": Konjunktiv II جمع.`,
    36: `"Stattdessen setzen sie sich ___ die Familie … ein": "sich einsetzen für": حرف جرّ.`,
    37: `"Wenn die Kinder ___ und aus dem Haus sind": بعد "die Kinder" و"sind": صفة.`,
    38: `"häufiger ___ ihres Arbeitslebens ihre Karriere verwirklichen": Genitiv زمني: حرف جرّ.`,
    39: `"___ sehen sie keine Veranlassung": "sehen" بعد الفراغ: ظرف نتيجة.`,
    40: `"neues Wissen zu erwerben, ___ Kompetenzen zu entwickeln": اسم جمع بدون أداة: كمّية.` },
  48: { 31: `"Daher lassen sie sich auf lange Wartelisten … ___": بعد "lassen" Infinitiv.`,
    32: `"werden Blumen ___": "werden": Partizip II.`,
    33: `"Die ___ von grünen Städten liegen auf der Hand": اسم جمع (die) + "von".`,
    34: `"Je mehr Pflanzen … gibt, desto ___ ist die Lebensqualität": "je … desto" + Komparativ.`,
    35: `"natürliche Schutzwälle ___ Wind und Lärm": "Schutz vor": حرف جرّ.`,
    36: `"Wo ___ grünt und blüht": "grünt" و"blüht" بلا فاعل: فاعل شكلي.`,
    37: `"da fühlen wir uns ___ wohl": ظرف تقوية.`,
    38: `"___ haben … Städte entdeckt, dass …": "haben" بعد الفراغ: ظرف زمني.`,
    39: `"dass ___ Städtchen auch schnell … werden": اسم جمع Nominativ: ضمير.`,
    40: `"…zu sozialen Treffpunkten werden ___": ظرف في آخر الجملة للنتيجة.` },
};
