// SB Teil 2 restyle — batch 02: [7] + [8] Jugend diskutiert (معدل), [9] Manipulierte Bilder (passage typo noted: "…Flut. Von Fotos"), [10] Der klügste Freund (Original) — [11] fills from the store
export default {
  // ───────────── [7] Jugend diskutiert – mach mit! (معدل) ─────────────
  7: {
    31: { ok: "SEIT", type: "preposition", keyword: "seit + Zeitpunkt (bereits seit)", bed: "منذ",
      text: `"gibt es bereits ___ Herbst 2002": الوجود بدا في الماضي ومازال، و"bereits" تدلّ على المدّة.\n✓ "seit" = منذ (بداية في الماضي ومازال).\n✗ "im" = في (in + dem): "im Herbst 2002" ممكنة نحويًّا لموعد، بصح "gibt es bereits" تعبّر على مدّة مستمرة، موش حدث في لحظة.\n✗ "nachdem" = بعد ما (رابط يفتح جملة فرعية)، وبعدو "Herbst 2002" اسم موش جملة.`,
      rule: "seit + Zeitpunkt = ab damals bis jetzt  |  im + Jahreszeit = Zeitpunkt", ex: "Es gibt den Laden **seit** Juni.", exTr: "الدكّان موجود من جوان." },
    32: { ok: "WIE", type: "fixed_expression", keyword: "wie immer", bed: "كالعادة",
      text: `تعبير ثابت: "wie immer" = كالعادة، وبعدو الفعل "bereiten" في الثانية.\n✓ "wie" = كيما (wie immer = كالعادة).\n✗ "als" = وقتما / من (مقارنة)، و"als immer" ما تتقالش.\n✗ "obwohl" = رغم إنّو (رابط جملة فرعية + فعل في الآخر)، وهنا "bereiten" في الثانية.`,
      rule: "wie immer = wie gewohnt (feste Wendung)", ex: "**Wie** immer ist er pünktlich.", exTr: "كالعادة هو في الوقت." },
    33: { ok: "WARUM", type: "conjunction", keyword: "sich fragen, warum …", bed: "علاش",
      text: `"Du fragst dich, ___ du teilnehmen solltest?": سؤال على السبب، والجواب جاي ("Ganz einfach: … bringt dich weiter").\n✓ "warum" = علاش (indirekte Frage، + فعل في الآخر).\n✗ "wie" = كيفاش: ممكنة نحويًّا بصح تسأل على الطريقة، والجواب هنا يشرح الفايدة موش الطريقة.\n✗ "obwohl" = رغم إنّو (تنازل)، موش كلمة سؤال.`,
      rule: "indirekte Frage nach dem Grund: warum + Nebensatz  |  wie = Art und Weise", ex: "Ich weiß nicht, **warum** er lacht.", exTr: "ما نعرفش علاش يضحك." },
    34: { ok: "AUSSERDEM", type: "adjective_adverb", keyword: "außerdem + Verb", bed: "وزيد",
      text: `"___ bietet dir "Jugend diskutiert" die Chance …": نضيفو فايدة أخرى، والفعل "bietet" بعد الكلمة مباشرة.\n✓ "außerdem" = وزيد (ظرف إضافة + فعل في الثانية).\n✗ "darunter" = من بينهم (يحتاج مجموعة مذكورة قبلها)، وما يضيفش فايدة.\n✗ "nachdem" = بعد ما (رابط جملة فرعية + فعل في الآخر)، و"bietet" هنا في الثانية.`,
      rule: "außerdem + Verb (Position 2) = zusätzlich", ex: "Die Wohnung ist hell, **außerdem** ist sie günstig.", exTr: "الشقّة منوّرة، وزيد رخيصة." },
    35: { ok: "AN", type: "verb_prep", keyword: "teilnehmen an + Dativ", bed: "يشارك في",
      text: `"die dann ___ Regionalwettbewerben teilnehmen": "teilnehmen" يتبعو "an" + Dativ.\n✓ "an" = في (teilnehmen an).\n✗ "bei" = عند: "bei Wettbewerben mitmachen" ممكنة، بصح "teilnehmen" يتبعو "an".\n✗ "im" = in + dem (مفرد)، و"Regionalwettbewerben" جمع.`,
      rule: "an + Dativ teilnehmen  |  bei + Dativ mitmachen", ex: "Viele Schüler nehmen **an** dem Projekt teil.", exTr: "برشا تلاميذ يشاركو في المشروع." },
    36: { ok: "IM", type: "preposition", keyword: "im Finale antreten", bed: "في (النهائي)",
      text: `"Die Sieger treten ___ Bundesfinale an": المرحلة النهائية (Bundesfinale محايد)، و"in + dem" = "im".\n✓ "im" = في (in + dem، "im Finale antreten").\n✗ "an" = على / في، و"an Bundesfinale" ما تتقالش بدون أداة مدمجة.\n✗ "bei" = عند، و"bei Bundesfinale" ما تتقالش (كان "beim")، والتعبير المعتاد "im Finale".`,
      rule: "antreten in + Dativ: im Finale / im Wettbewerb", ex: "Sie tritt **im** Finale an.", exTr: "هي تشارك في النهائي." },
    37: { ok: "BEI", type: "preposition", keyword: "bei + Dativ (Aktivität)", bed: "في (خلال)",
      text: `"___ "Jugend diskutiert" kannst du viel lernen": "bei + Dativ" مع مسابقة / نشاط (خلال المشاركة).\n✓ "bei" = في / خلال (bei + Dativ).\n✗ "an" = على، و"an Jugend diskutiert" ما تتقالش (تحتاج "teilnehmen an").\n✗ "als" = كـ، وما تتماشاش مع هذا الاستعمال.`,
      rule: "bei + Dativ = im Rahmen von / während", ex: "**Bei** dem Kurs lerne ich viel.", exTr: "في الدورة نتعلّم برشا." },
    38: { ok: "MACHT", type: "verb", keyword: "auf sich aufmerksam machen", bed: "يلفت الانتباه",
      text: `"wie man das Wort ergreift und auf sich aufmerksam ___": "auf sich aufmerksam machen" = يلفت الانتباه، والفعل مع "man" في 3. Person.\n✓ "macht" = Präsens مع "man" (auf sich aufmerksam machen).\n✗ "eigene" = صفة (own)، وبعد "aufmerksam" نحتاج فعل.\n✗ "Chance" = اسم (فرصة)، وما يكمّلش التعبير الفعلي.`,
      rule: "auf sich / etwas aufmerksam machen = Aufmerksamkeit erregen", ex: "Sie **macht** mit einem Plakat auf sich aufmerksam.", exTr: "هي تلفت الانتباه بملصق." },
    39: { ok: "EIGENE", type: "adjective_adverb", keyword: "eigene Argumente", bed: "(حجج) خاصة بيك",
      text: `"da du ___ Argumente finden und die Argumente anderer … prüfen kannst": مقابلة بين حججك وحجج الآخرين.\n✓ "eigene" = ملكك (صفة، -e قبل جمع Akkusativ بدون أداة).\n✗ "die" = أداة معرّفة: "die Argumente finden" ممكنة، بصح الجملة تقابل "Argumente anderer" بحججك أنت، وهذا يطلب "eigene".\n✗ "wie" = كيفاش / كيما، وما تعطيش صفة قبل "Argumente".`,
      rule: "eigen- + Plural ohne Artikel: eigene (Endung -e)", ex: "Jeder hat **eigene** Ideen.", exTr: "كلّ واحد عندو أفكار خاصة بيه." },
    40: { ok: "CHANCE", type: "noun", keyword: "eine Chance, … zu + Infinitiv", bed: "فرصة",
      text: `"eine ___, Jugendliche aus ganz Deutschland kennenzulernen": اسم مؤنّث (eine) + "zu-Infinitiv".\n✓ "Chance" = فرصة (eine Chance, … zu + Infinitiv).\n✗ "eigene" = صفة، وبعد "eine" ممكن "eine eigene" لكن ما تكمّلش الجملة (تحتاج اسم قبل الفاصلة).\n✗ "macht" = فعل مصرّف، وبعد "eine" نحتاج اسم.`,
      rule: "die Chance, … zu + Infinitiv (Substantiv + Infinitivsatz)", ex: "Das ist eine **Chance**, neue Leute zu treffen.", exTr: "هذي فرصة باش نلتقي ناس جدد." },
  },

  // ───────────── [8] Jugend diskutiert – mach mit! (معدل 2) ─────────────
  8: {
    31: { ok: "SEIT", type: "preposition", keyword: "seit + Herbst 2002", bed: "منذ",
      text: `"gibt es bereits ___ Herbst 2002": مسابقة بدات في 2002 ومازالت قايمة.\n✓ "seit" = منذ (+ Dativ، من 2002 لين توّا).\n✗ "an" = على، و"an Herbst" ما تتقالش (يتقال "im Herbst").\n✗ "als" = وقتما / كـ، وما تعطيش معنى مدّة.`,
      rule: "seit = Beginn in der Vergangenheit, der bis heute anhält", ex: "Ich kenne ihn **seit** der Schule.", exTr: "نعرفو من المدرسة." },
    32: { ok: "TEILNEHMEN", type: "verb_prep", keyword: "an + Dat. teilnehmen", bed: "يشارك",
      text: `"die an dem Wettbewerb ___ möchten": بعد "möchten" الفعل في Infinitiv، و"an dem Wettbewerb teilnehmen".\n✓ "teilnehmen" = يشارك (Infinitiv بعد möchten).\n✗ "prüfen" = يفحص، موش يشارك في مسابقة.\n✗ "macht" = فعل مصرّف (3. Person)، وبعد "möchten" لازم Infinitiv.`,
      rule: "an + Dativ teilnehmen (trennbar: nimmt … teil)", ex: "Wir möchten an dem Kurs **teilnehmen**.", exTr: "نحبّو نشاركو في الدورة." },
    33: { ok: "WARUM", type: "conjunction", keyword: "Frage nach dem Grund: warum", bed: "علاش",
      text: `"Du fragst dich, ___ du teilnehmen solltest?": الجواب جاي بعدها، يعني سؤال على السبب.\n✓ "warum" = علاش (Fragewort، + فعل في الآخر).\n✗ "nachdem" = بعد ما (ترتيب زمني)، موش سؤال.\n✗ "darunter" = من بينهم / تحت هذا، موش كلمة سؤال.`,
      rule: "warum = Frage nach dem Grund (indirekt: Verb am Ende)", ex: "Er fragt, **warum** sie weint.", exTr: "يسأل علاش تبكي." },
    34: { ok: "AUSSERDEM", type: "adjective_adverb", keyword: "außerdem (zusätzlicher Vorteil)", bed: "وزيد",
      text: `"___ bietet dir …": نذكرو فايدة زايدة، والفعل "bietet" بعد الظرف.\n✓ "außerdem" = وزيد (ظرف إضافة، الفعل في الثانية).\n✗ "darunter" = من بينهم، يحتاج مجموعة مذكورة قبلها.\n✗ "als" = كـ / وقتما، و"Als bietet dir" ما تتركّبش (تحتاج جملة فرعية بفعل في الآخر).`,
      rule: "außerdem = zusätzlich  |  darunter = unter diesen / unter dieser Gruppe", ex: "Er spricht Deutsch, **außerdem** lernt er Spanisch.", exTr: "يحكي ألماني، وزيد يتعلّم إسباني." },
    35: { ok: "IM", type: "preposition", keyword: "im Bundesfinale antreten", bed: "في (النهائي)",
      text: `"Die Sieger … treten ___ Bundesfinale an": "in + dem" مدمجة = "im".\n✓ "im" = في (in + dem، Bundesfinale محايد).\n✗ "an" = على / في، و"an Bundesfinale" ما تتقالش بدون أداة.\n✗ "bei" = عند، و"bei Bundesfinale" ما تتقالش، والتعبير المعتاد "im Finale".`,
      rule: "in + dem = im (Neutrum, Dativ): im Finale, im Spiel", ex: "Die Mannschaft spielt **im** Halbfinale.", exTr: "الفريق يلعب في نصف النهائي." },
    36: { ok: "BEI", type: "preposition", keyword: "bei + Dativ", bed: "في (خلال)",
      text: `"___ "Jugend diskutiert" kannst du viel lernen": خلال المشاركة في النشاط.\n✓ "bei" = في / خلال (bei + Dativ).\n✗ "seit" = منذ، موش بداية جملة بهذا المعنى.\n✗ "als" = كـ / وقتما، وما تتركّبش مع الاسم هكا.`,
      rule: "bei + Dativ = während einer Tätigkeit / an einem Ort", ex: "**Bei** der Übung lernt man viel.", exTr: "في التمرين الواحد يتعلّم برشا." },
    37: { ok: "MACHT", type: "verb", keyword: "aufmerksam machen (auf sich)", bed: "يلفت الانتباه",
      text: `"auf sich aufmerksam ___": الفعل المصرّف مع "man": "macht".\n✓ "macht" = Präsens (man macht … aufmerksam).\n✗ "prüfen" = Infinitiv (يفحص)، وما يكمّلش التعبير ولا يطابق "man".\n✗ "teilnehmen" = Infinitiv (يشارك)، وبعد "man" نحتاج فعل مصرّف.`,
      rule: "jdn. auf etwas aufmerksam machen  |  auf sich aufmerksam machen", ex: "Der Lehrer **macht** uns auf Fehler aufmerksam.", exTr: "المعلّم يلفتلنا الانتباه للغلطات." },
    38: { ok: "EIGENE", type: "adjective_adverb", keyword: "eigene (Plural, Akk.)", bed: "خاصة بيك",
      text: `"da du ___ Argumente finden … kannst": حجج خاصة بيك مقابل حجج الآخرين.\n✓ "eigene" = صفة بنهاية -e (Plural Akkusativ بدون أداة).\n✗ "die" = أداة معرّفة: ممكنة نحويًّا، بصح المعنى يطلب "eigene" (حججك أنت).\n✗ "darunter" = من بينهم، وما تتركّبش قبل "Argumente".`,
      rule: "Plural ohne Artikel: eigene / andere / neue + Nomen", ex: "Sie hat **eigene** Pläne.", exTr: "عندها مخططات خاصة بيها." },
    39: { ok: "PRÜFEN", type: "verb", keyword: "Argumente prüfen können", bed: "تفحص",
      text: `"die Argumente anderer genau ___ kannst": الفعل المساعد "kannst" في الآخر، وقبلو Infinitiv.\n✓ "prüfen" = يفحص (Infinitiv + kannst).\n✗ "teilnehmen" = يشارك، معنى مختلف ومنفصل ("nimmt … teil").\n✗ "macht" = فعل مصرّف، وقبل "kannst" لازم Infinitiv.`,
      rule: "Nebensatz: Infinitiv + Modalverb am Ende (prüfen kannst)", ex: "Du musst die Quellen genau **prüfen** können.", exTr: "لازمك تنجّم تفحص المصادر بدقّة." },
    40: { ok: "CHANCE", type: "noun", keyword: "eine Chance", bed: "فرصة",
      text: `"auch eine ___, Jugendliche … kennenzulernen": "eine" + اسم مؤنّث.\n✓ "Chance" = فرصة (مؤنّث).\n✗ "eigene" = صفة، وما تكمّلش الجملة بدون اسم.\n✗ "darunter" = من بينهم، موش اسم.`,
      rule: "eine Chance haben / bieten + zu-Infinitiv", ex: "Der Kurs ist eine **Chance** zum Lernen.", exTr: "الدورة فرصة للتعلّم." },
  },

  // ───────────── [9] Manipulierte Bilder ─────────────
  9: {
    31: { ok: "FLUT", type: "noun", keyword: "eine Flut von …", bed: "سيل (من)",
      text: `"mit einer ___ von Fotos konfrontiert": صورة مجازية: سيل من الصور، و"einer" مؤنّث.\n✓ "Flut" = سيل / كمّ هائل (eine Flut von + Dativ Plural).\n✗ "verschieden" = مختلف (صفة)، وما تجي بدون نهاية بعد "einer" ولا تعبّر على كمية.\n✗ "meisten" = أغلب (صفة)، وما تتركّبش مع "einer" هكا.`,
      rule: "eine Flut von + Dativ Plural = eine riesige Menge", ex: "Wir erhalten täglich eine **Flut** von Nachrichten.", exTr: "نتلقّاو كلّ يوم سيل من الرسائل." },
    32: { ok: "RECHT", type: "adjective_adverb", keyword: "recht einfach", bed: "بسيط نوعًا ما",
      text: `"machen es … für Laien ___ einfach": ظرف درجة قبل الصفة "einfach".\n✓ "recht" = نوعًا ما / برشا (recht + Adjektiv).\n✗ "korrekt" = صحيح (صفة)، موش ظرف درجة، و"korrekt einfach" ما تتقالش.\n✗ "zwar" = صحيح (zwar … aber)، رابط تنازل، موش درجة.`,
      rule: "recht + Adjektiv = ziemlich  |  korrekt = fehlerfrei", ex: "Der Test war **recht** schwer.", exTr: "الاختبار كان صعيب نوعًا ما." },
    33: { ok: "ABER", type: "conjunction", keyword: "aber (Position 0)", bed: "لكن",
      text: `"Meist sind die Manipulationen harmlos, ___ die Möglichkeiten … lassen sich … missbrauchen": تعارض، والفاعل "die Möglichkeiten" يجي مباشرة بعد الرابط.\n✓ "aber" = لكن (Position 0، الترتيب العادي بعدها).\n✗ "somit" = وبالتالي (ظرف نتيجة، يقلب الترتيب: "somit lassen sich …")، وما فماش نتيجة هنا.\n✗ "zwar" = صحيح (zwar … aber)، ويقلب الترتيب بعدو، وما فماش "aber" مكمّل.`,
      rule: "aber = Gegensatz (Position 0, keine Inversion)  |  somit / zwar + Verb Position 2", ex: "Es ist einfach, **aber** nicht billig.", exTr: "سهل، لكن موش رخيص." },
    34: { ok: "STELLT", type: "verb", keyword: "sich die Frage stellen", bed: "تطرح (روحها)",
      text: `"In diesem Zusammenhang ___ sich die Frage": "sich die Frage stellen" = تُطرح المسألة، والفعل في الثانية.\n✓ "stellt" = Präsens 3. Person (es stellt sich die Frage).\n✗ "unterscheiden" = Infinitiv، وبعد "Zusammenhang" نحتاج فعل مصرّف في الثانية.\n✗ "abgrenzen" = Infinitiv (يفصل)، ونفس المشكل، ومعناها مختلف.`,
      rule: "es stellt sich die Frage, inwieweit … (reflexiv, Verb Position 2)", ex: "Hier **stellt** sich die Frage nach den Kosten.", exTr: "هنا تُطرح مسألة التكاليف." },
    35: { ok: "DIESEN", type: "grammar_structure", keyword: "diesen Fragen (Dativ Plural)", bed: "هذه (الأسئلة)",
      text: `"___ Fragen sind nun Forscher nachgegangen": "nachgehen" + Dativ، و"Fragen" جمع.\n✓ "diesen" = Dativ جمع (diesen Fragen).\n✗ "meisten" = أغلب، و"Meisten Fragen" تحتاج أداة قبلها ("Den meisten Fragen").\n✗ "verschieden" = مختلف (صفة بدون نهاية)، وما تجيش قبل اسم هكا.`,
      rule: "nachgehen + Dativ: diesen Fragen / dieser Frage", ex: "Die Polizei geht **diesen** Hinweisen nach.", exTr: "البوليس يتابع هذه المعلومات." },
    36: { ok: "MEISTEN", type: "grammar_structure", keyword: "die meisten + Nomen", bed: "أغلب",
      text: `"Die ___ Teilnehmer waren nur eher zufällig in der Lage": "die meisten" = الأغلبية.\n✓ "meisten" = أغلب (Superlativ، + -en بعد "die" في Plural).\n✗ "verschieden" = مختلف، وتحتاج نهاية -en ("verschiedenen") قبل اسم.\n✗ "reisend" = مسافر (Partizip I)، وتحتاج نهاية، ومعناها ما يتماشاش.`,
      rule: "die meisten + Plural = der größte Teil von …", ex: "Die **meisten** Gäste kamen zu Fuß.", exTr: "أغلب الضيوف جاو على رجليهم." },
    37: { ok: "KORREKT", type: "adjective_adverb", keyword: "korrekt bestimmen", bed: "بشكل صحيح",
      text: `"konnten sie tatsächlich ___ bestimmen, wo das Bild verändert worden war": ظرف طريقة: بشكل صحيح.\n✓ "korrekt" = بشكل صحيح (Adjektiv كظرف).\n✗ "recht" = نوعًا ما (ظرف درجة)، موش ظرف طريقة بعد "tatsächlich".\n✗ "zwar" = صحيح (zwar … aber)، رابط تنازل، موش ظرف طريقة.`,
      rule: "korrekt = richtig (Adverb der Art und Weise)", ex: "Er hat die Aufgabe **korrekt** gelöst.", exTr: "حلّ التمرين بشكل صحيح." },
    38: { ok: "UNLOGISCHE", type: "adjective_adverb", keyword: "andere unlogische Abweichungen", bed: "غير منطقية",
      text: `"andere ___ Abweichungen": صفة قبل جمع، بنهاية -e بعد "andere".\n✓ "unlogische" = غير منطقية (-e، Plural Nominativ بعد "andere").\n✗ "korrekt" = صحيح، بدون نهاية، وما تتماشاش مع معنى "Abweichungen".\n✗ "verschieden" = مختلف، بدون نهاية، وما تتركّبش قبل اسم.`,
      rule: "andere + Adjektiv + -e (Plural Nom. / Akk.)", ex: "Es gab andere **wichtige** Gründe.", exTr: "كانو فما أسباب أخرى مهمّة." },
    39: { ok: "UNTERSCHEIDEN", type: "verb_prep", keyword: "zwischen … und … unterscheiden", bed: "يميّز",
      text: `"Können Menschen also nicht zwischen echten und gefälschten Details … ___": "zwischen … und … unterscheiden" = يميّز بين.\n✓ "unterscheiden" = يميّز (Infinitiv بعد "Können … nicht").\n✗ "abgrenzen" = يفصل / يحدّد حدود (abgrenzen von)، وما تتركّبش مع "zwischen … und" بمعنى يميّز.\n✗ "stellt" = فعل مصرّف، وبعد "Können Menschen … nicht" نحتاج Infinitiv.`,
      rule: "zwischen A und B unterscheiden  |  A von B abgrenzen", ex: "Kinder können oft nicht zwischen Traum und Wirklichkeit **unterscheiden**.", exTr: "الصغار برشا مرّات ما يفرّقوش بين الحلم والواقع." },
    40: { ok: "SOMIT", type: "adjective_adverb", keyword: "somit (Folgerung)", bed: "وبالتالي",
      text: `"Die Ergebnisse dokumentierten ___": ظرف يعطي خلاصة: وبالتالي.\n✓ "somit" = وبالتالي (ظرف نتيجة).\n✗ "zwar" = صحيح (zwar … aber)، يحتاج "aber" بعدو.\n✗ "aber" = لكن (تعارض)، وما فماش تعارض مع الجملة اللي قبل.`,
      rule: "somit = folglich / dadurch (Folgerung)", ex: "Es regnete, **somit** fiel das Fest aus.", exTr: "كانت تشتي، وبالتالي الحفلة تلغات." },
  },

  // ───────────── [10] Der klügste Freund des Menschen ( Original ) ─────────────
  10: {
    31: { ok: "ZWAR", type: "conjunction", keyword: "zwar … jedoch", bed: "صحيح",
      text: `"___ gilt der Hund … als treuer Begleiter, besondere Leistungen … wurden ihm jedoch … seltener zugesprochen": اعتراف أول ثم تعارض مع "jedoch".\n✓ "zwar" = صحيح (الجزء الأول من zwar … jedoch / aber).\n✗ "aber" = لكن، تجي في الجزء الثاني (تعارض)، موش في بداية الاعتراف.\n✗ "sondern" = بل (تصحيح بعد نفي)، وما فماش نفي قبلها.`,
      rule: "zwar … aber / jedoch = Zugeständnis + Gegensatz", ex: "**Zwar** ist er jung, doch er weiß viel.", exTr: "صحيح هو صغير، بصح يعرف برشا." },
    32: { ok: "WURDEN", type: "tense", keyword: "wurden + Partizip II (Passiv, Plural)", bed: "تمّت (اتعملت)",
      text: `"Untersuchungen, die … durchgeführt ___": Passiv في الماضي، و"Untersuchungen" جمع.\n✓ "wurden" = Präteritum Passiv جمع (wurden … durchgeführt).\n✗ "war" = مفرد، والفاعل "Untersuchungen" جمع.\n✗ "seien" = Konjunktiv I (كلام منقول)، وهنا الجملة تعطي معلومة حقيقية بـ "beweisen".`,
      rule: "Vorgangspassiv Präteritum: wurde / wurden + Partizip II (Plural → wurden)", ex: "Die Tests **wurden** im Mai durchgeführt.", exTr: "الاختبارات اتعملت في ماي." },
    33: { ok: "AB", type: "verb", keyword: "ablesen (liest … ab)", bed: "يقرا (من)",
      text: `"Hunde lesen kommunikative Informationen besonders an den Augen ___": الفعل المنفصل "ablesen" = يقرا من.\n✓ "ab" = الجزء المنفصل من "ablesen" (lesen … ab).\n✗ "an" = على، وما يكمّلش "ablesen" (ما فماش "anlesen" بهذا المعنى).\n✗ "auf" = على، ما تكمّلش الفعل ("auflesen" = يلمّ، معنى مختلف).`,
      rule: "trennbar: ablesen → liest … ab (etwas an / von etwas ablesen)", ex: "Man kann ihm die Freude am Gesicht **ablesen**.", exTr: "الواحد ينجّم يقرا الفرحة في وجهو." },
    34: { ok: "AUF", type: "verb_prep", keyword: "reagieren auf + Akk.", bed: "يتفاعل مع",
      text: `"sie reagieren auch ___ die Stimme": "reagieren" يتبعو "auf" + Akkusativ.\n✓ "auf" = على (reagieren auf).\n✗ "über" = حول / فوق، و"reagieren über" ما تتقالش.\n✗ "darauf" = على هذا (Pronominaladverb)، وبعدو اسم ("die Stimme") موش جملة.`,
      rule: "reagieren auf + Akk.  |  darauf, wenn kein Nomen folgt", ex: "Die Katze **reagiert** auf jedes Geräusch.", exTr: "القطّوس يتفاعل مع كلّ صوت." },
    35: { ok: "SEI", type: "tense", keyword: "sei (Konjunktiv I, indirekte Rede)", bed: "(يقولو) يكون",
      text: `"Ganz besonders der Blickkontakt ___ für Hunde ein wichtiges Instrument": كلام منقول عن الباحثين، فنستعملو Konjunktiv I.\n✓ "sei" = Konjunktiv I من "sein" (3. Person مفرد).\n✗ "war" = Präteritum: ممكنة نحويًّا، بصح الجملة تنقل قول الباحثين (Konjunktiv I) والمعنى حاضر.\n✗ "seien" = Konjunktiv I جمع، و"Blickkontakt" مفرد.`,
      rule: "indirekte Rede: Konjunktiv I (er sei, sie seien)", ex: "Er sagt, der Test **sei** schwer gewesen.", exTr: "يقول إنّو الاختبار كان صعيب." },
    36: { ok: "WAR", type: "tense", keyword: "War …, suchten … (Konditionalsatz)", bed: "كان",
      text: `"___ der Behälter nach dem Öffnen leer, suchten die Hunde …": شرط بدون "wenn": الفعل في الأول.\n✓ "war" = Präteritum (Konditionalsatz بالقلب، يتماشى مع "suchten").\n✗ "wurden" = جمع Passiv، و"Behälter" مفرد، و"wurden … leer" ما تتقالش.\n✗ "sei" = Konjunktiv I: ممكنة في أسلوب رسمي، بصح هنا نحكيو على تجربة فاتت بـ "suchten" (Präteritum).`,
      rule: "Konditionalsatz ohne wenn: Verb an Position 1 (War er leer, …)", ex: "**War** es zu kalt, blieben sie zu Hause.", exTr: "كان البرد شديد، يقعدو في الدار." },
    37: { ok: "UM", type: "preposition", keyword: "um … herum", bed: "حول",
      text: `"er leitet sie ___ Hindernisse herum": الحركة حول العراقيل: "um … herum".\n✓ "um" = حول (um + Akk. + herum).\n✗ "über" = فوق، وتتقال "über Hindernisse hinweg" موش "herum".\n✗ "an" = عند / على، و"an Hindernissen vorbei" تتقال مع "vorbei" موش "herum".`,
      rule: "um + Akk. + herum = im Kreis / außen herum  |  über … hinweg  |  an … vorbei", ex: "Wir gehen **um** den See herum.", exTr: "نمشيو حول البحيرة." },
    38: { ok: "DAVON", type: "pronoun_adverb", keyword: "davon ausgehen, dass …", bed: "من (هذا) (نفترض)",
      text: `"geht man ___ aus, dass …": "ausgehen von" = ينطلق من / يفترض، والـ Pronominaladverb "davon" يعلن على الـ dass-Satz.\n✓ "davon" = من هذا (von + das).\n✗ "darauf" = على هذا (auf + das)، و"ausgehen darauf" ما تتقالش.\n✗ "darüber" = حول هذا (über + das)، و"ausgehen darüber" ما تتقالش.`,
      rule: "ausgehen von + Dat. → davon ausgehen, dass …", ex: "Wir gehen **davon** aus, dass er kommt.", exTr: "نفترضو إنّو باش يجي." },
    39: { ok: "DARAUF", type: "pronoun_adverb", keyword: "stolz sein auf → darauf", bed: "بهذا (يفتخرو)",
      text: `"stolz ___ sein, nicht nur einen anhänglichen … Begleiter zu haben": "stolz sein auf" + zu-Infinitiv ← "darauf".\n✓ "darauf" = على هذا (auf + das).\n✗ "davon" = من هذا (von + das)، و"stolz davon" ما تتقالش.\n✗ "darüber" = حول هذا (über + das)، و"stolz darüber" ما تتقالش (الحرف الصحيح "auf").`,
      rule: "stolz sein auf + Akk. → darauf, … zu + Infinitiv", ex: "Sie ist **darauf** stolz, geholfen zu haben.", exTr: "هي تفتخر إنّها عاونت." },
    40: { ok: "SONDERN", type: "conjunction", keyword: "nicht nur …, sondern auch …", bed: "بل",
      text: `"nicht nur einen anhänglichen, ___ auch einen intelligenten Begleiter": الزوج "nicht nur … sondern auch".\n✓ "sondern" = بل (يكمّل "nicht nur").\n✗ "aber" = لكن: تتقال أحيانًا في الكلام ("nicht nur …, aber auch")، بصح الزوج المعتمد "sondern auch".\n✗ "zwar" = صحيح (zwar … aber)، رابط تنازل، موش جزء من "nicht nur".`,
      rule: "nicht nur A, sondern auch B  |  zwar A, aber B", ex: "Er ist nicht nur nett, **sondern** auch klug.", exTr: "هو موش بس لطيف، بل زادا ذكي." },
  },
};
