// "ليش هذا النوع؟" — part C: leftovers of the twin variants 40/41 and positions 49–64.
// typeFix: gaps whose stored item_type does not match the word that really fills the gap (so the header category would contradict the reason).
export const typeFix = { "35#38": "preposition" };
export default {
  40: { 34: `"wie es früher unterrichtet und von einigen auch gefürchtet ___": Partizip II "gefürchtet" في الآخر + فاعل "es" مفرد وزمن ماضي: Passiv ماضي يحتاج "wurde".`,
    35: `"Die Verbindung ___ Schrift und Bild": بين اسمين بدون أداة: "Verbindung" يتبعو "von … und …".`,
    37: `"Auf ___ Weise vermittelt die Künstlerin": قبل "Weise" (مؤنّث Akk): صفة بنهاية -e.`,
    38: `"…ein Anliegen, ___ Kinder die Freude … wieder entdecken": الفعل في الآخر: جملة محتوى بعد "Anliegen".` },
  41: { 31: `"…schmerzt relativ schnell, ___ Handschrift ungewohnt ist": "ist" في الآخر: جملة فرعية للسبب.`,
    32: `"haben mit dem Schreiben in der Schule ___ mehr Probleme": قبل "mehr": تعبير ثابت للزيادة.`,
    34: `"Erfahrungen ___ hat die Wiener Designerin … gemacht": "Erfahrungen machen mit" + مرجع لشيء مذكور: Pronominaladverb.`,
    35: `"Auf ___ Weise vermittelt die Künstlerin": قبل "Weise" (مؤنّث Akk): صفة بنهاية -e.`,
    36: `"ist wichtig, ___ Kinder die Freude am Schreiben wiederentdecken": الفعل في الآخر: جملة محتوى.`,
    37: `"die eigene Handschrift zu beurteilen und zu ___": "und zu" يطلب Infinitiv ثاني.`,
    39: `"Die Verbindung ___ Schrift und Bild": بين اسمين: "Verbindung von … und …".`,
    40: `"wie es früher unterrichtet und von einigen auch gefürchtet ___": Partizip II + فاعل "es" مفرد وزمن ماضي: Passiv ماضي.` },
  49: { 31: `"habe ich gestern … gefunden und ___ gleich an euch denken": بعد "und" فعل مصرّف ماضي + "denken" Infinitiv في الآخر: modal ماضي.`,
    32: `"an euch ___ denken": بعد "euch" وقبل "denken": ضمير يحدّد العدد.`,
    33: `"wunderbare Abende, ___ wir im letzten Urlaub … verbracht haben": جملة فرعية (فعل في الآخر) تصف "Abende" (جمع Akkusativ): ضمير موصول.`,
    34: `"Wie ___ es, hättet ihr nicht mal Lust …?": "Wie ___ es" اقتراح مؤدّب: Konjunktiv II من sein.`,
    35: `"Ich kenne die Burg Tanneck ___ seit meiner Kindheit": قبل "seit": ظرف يشدّد على طول المدّة.`,
    36: `"hat ___ nichts mit Kommerz … zu tun": قبل "nichts": ظرف يشدّد النفي.`,
    37: `"wie man es sonst aus dem Fernsehen ___": فاعل "man" + الجملة الفرعية: فعل مصرّف مفرد في الآخر.`,
    38: `"Es geht nur ___, Spaß zu haben und zu singen": "es geht um" + zu-Infinitiv: Pronominaladverb.`,
    39: `"auch ___ ihr nur den anderen Sängern zuhören wollt": "wollt" في الآخر: جملة فرعية بعد "auch": رابط شرط / تنازل.`,
    40: `"Lasst ___ was von euch hören!": أمر ومفعول جاهز: نحتاج ظرف زمني (قريبًا).` },
  50: { 31: `"…die in Perugia ihr Start-up oder ein Technik-Tool ___": جملة موصولة، فاعل جمع + مفعول وما فماش فعل: فعل جمع في الآخر.`,
    32: `"die Einbindung von Video … war ___ ein Schwerpunktthema": بين "war" واسم "ein Schwerpunktthema": ظرف إضافة.`,
    33: `"Im Gegensatz zu den Jahren ___": بعد "den Jahren" في الآخر: ظرف يشير للفترة السابقة.`,
    34: `"nicht mehr darüber diskutiert, ob …, ___ wurde das … als gegeben angenommen": "wurde" بعد الفراغ + نفي قبلو: ظرف تصحيح.`,
    35: `"herrschte viel Optimismus ___": "herrschte … vor": جزء منفصل في الآخر.`,
    36: `"Bürger sind … immer mehr ___, in journalistische Projekte zu investieren": بعد "sind … immer mehr" + zu-Infinitiv: صفة ("bereit sein zu").`,
    37: `"ist das ___ bekannteste Modell in Europa": قبل صفة تفضيل: ظرف تخمين.`,
    38: `"… und ___ Crowdfunding finanziert werden": Passiv + اسم بدون أداة: حرف جرّ للوسيلة.`,
    39: `"und sich ___ behaupten": بين "sich" والفعل: ظرف طريقة.`,
    40: `"weil ___ ein Qualitätsanspruch verbunden ist": "verbunden" + "mit" مرجع لشيء مذكور: Pronominaladverb.` },
  51: { 31: `"Eine Geschwindigkeitsbegrenzung … ___ in Deutschland aber eine fast undenkbare Idee": الجملة بلا فعل وهي افتراض: Konjunktiv II من sein.`,
    32: `"Ein Grund ___, dass das Leben hierzulande so schnell geworden ist": "Grund für" + dass: Pronominaladverb.`,
    33: `"Ein Grund … ___ die moderne Technik sein": "sein" Infinitiv في الآخر + فاعل: modal "mögen" (ربّما).`,
    34: `"E-Mails erreichen den Empfänger ___ schneller als ein Brief, aber …": قبل "aber": رابط يفتح تنازل.`,
    35: `"…schneller als ein Brief, ___ die Informationsflut … bewirkt auch, dass …": بعد "zwar": رابط Position 0 للجزء المقابل.`,
    36: `"mehr Zeit ___ man möchte": بعد "mehr" (مقارنة): "als" + "möchte" في الآخر.`,
    37: `"Viele zweifeln inzwischen ___, ob …": "zweifeln an" + ob: Pronominaladverb.`,
    38: `"…einen starken Einfluss ___, wie das Lebenstempo empfunden wird": "Einfluss auf" + wie: Pronominaladverb.`,
    39: `"Bei immer mehr Routine … ___, so die Forscher, der Eindruck von Schnelligkeit entstehen": "entstehen" Infinitiv + فاعل: "würde + Infinitiv" (Konjunktiv).`,
    40: `"Und siehe da: ___ befragt, wie …": Partizip "befragt" بعد الفراغ: ظرف زمني.` },
  52: { 31: `"Und warum müssen wir ___ schlafen?": بين "wir" والفعل: ظرف يعمّم السؤال.`,
    32: `"Immer wieder werden wir ___ gewarnt, dass …": "warnen vor" + dass: Pronominaladverb.`,
    33: `"zu viel Schlaf ___ ungesund ist wie zu wenig": يتبعو "wie": ظرف مساواة.`,
    34: `"Notorische Langschläfer leiden … häufiger ___ Depressionen": "leiden unter" + اسم جمع: حرف جرّ ثابت.`,
    35: `"Das ___ so aber nicht": فاعل "das" مفرد: فعل مصرّف.`,
    36: `"nicht die Uhrzeit entscheidend ist, ___ vielmehr die ersten Stunden": بعد "nicht": رابط تصحيح.`,
    37: `"In dieser Zeit ___ ein Großteil … statt": "statt" في الآخر: الفعل المنفصل "stattfinden".`,
    38: `"spielt dabei keine ___": "spielen" + "keine": اسم مؤنّث.`,
    39: `"nicht ___ viel passiert": قبل "viel": ظرف يخفّف.`,
    40: `"zur ___ kommt": بعد "zur" وقبل "kommt": اسم.` },
  53: { 31: `"traurig ___, wie böse … Menschen sein können": "traurig über" + wie-Satz: Pronominaladverb.`,
    32: `"freue ich mich dann ganz ___ über Ihre Artikel": "ganz ___ über": ظرف تشديد.`,
    33: `"Artikel, die zeigen, ___ es auch viele gute … Menschen gibt": "gibt" في الآخر: جملة محتوى.`,
    34: `"Es war bereits 10 Uhr nachts, ___ mein Auto plötzlich stehen blieb": "blieb" في الآخر: جملة فرعية زمنية لحدث مرة وحدة.`,
    35: `"…wieder zu starten, ___ alles war vergeblich": "war" بعد "alles": رابط Position 0 للتعارض.`,
    36: `"fragte, ___ er mir helfen könne": "könne" في الآخر: سؤال نعم / لا.`,
    37: `"stieg er aus, ___ sich den Motor anzusehen": "anzusehen" zu-Infinitiv: رابط الغرض.`,
    38: `"fand er den Schaden und ___, dass …": بعد "und" فعل ماضي مفرد + dass.`,
    39: `"aber er ___ nichts annehmen": فاعل مفرد + Infinitiv: modal.`,
    40: `"Doch möchte ich mich ___ mit diesem Brief … bedanken": بين "mich" و"mit diesem Brief": ظرف يعبّر على الحدّ الأدنى.` },
  54: { 31: `"von Handy ___ Handy": الاسم يتكرّر حول حرف جرّ: تعبير ثابت.`,
    32: `"kommen … annähernd ___ das deutsche SMS-Fieber heran": "heran" في الآخر + Akkusativ: "herankommen" يتبعو "an".`,
    33: `"ein paar Minuten später ist ___ die Antwort da": ظرف يعبّر على السرعة.`,
    34: `"Selbst Liebesbriefe sind ___ der Mode gekommen": "aus der Mode kommen": حرف جرّ + Dativ.`,
    35: `"dafür aber ___ cooler, dynamischer": قبل Komparativ: ظرف "umso".`,
    36: `"Und ___ muss der verliebte SMS-Casanova … Kreativität zeigen": "muss" بعد الفراغ: ظرف في الخانة الأولى.`,
    37: `"; ___ die Nachrichten dürfen nicht sehr lang sein": "dürfen" ثاني: Hauptsatz، رابط Position 0 للسبب.`,
    38: `"Der SMS-Künstler macht ___ „ILD“": "machen aus" + اسم: Pronominaladverb.`,
    39: `"Schlechte Zeiten ___ für wahre Liebhaber …": جملة بلا فعل: ظرف استنتاج.`,
    40: `"sollen die Preise … ___ ansteigen": قبل "ansteigen": ظرف.` },
  55: { 31: `"trifft man sich am Sonntagnachmittag ___ Kaffee und Kuchen": اسمين بدون أداة: حرف جرّ للغرض.`,
    32: `"___ lange es den Brauch … gibt, ist jedoch nicht bekannt": "gibt" في الآخر + "lange": سؤال غير مباشر على المدّة.`,
    33: `"___ ist nur, dass …": "ist" ثاني + "dass" بعدو: صفة خبر.`,
    34: `"___ entstanden zahlreiche Kaffeehäuser": "entstanden" ماضي بعد الفراغ: ظرف زمني.`,
    35: `"nicht nur gespeist und getrunken, ___ man konnte in Gesellschaft sein": "nicht nur … sondern (auch)": الجزء الثاني.`,
    36: `"die berühmte Kaffeekantate ___ Johann Sebastian Bach": اسم + اسم شخص: حرف جرّ للمؤلّف.`,
    37: `"…das sich nur Adelige und wohlhabende Bürger leisten ___": جملة موصولة، فاعل جمع + "leisten" Infinitiv: modal ماضي في الآخر.`,
    38: `"und ist es ___ heute geblieben": قبل "heute": حرف جرّ زمني.`,
    39: `"Spezialitäten ___ alle Welt": بعد اسم وقبل "Welt": حرف جرّ لمصدر / أصل.`,
    40: `"…Espressokocher … ___ häufiger Konkurrenz": قبل Komparativ "häufiger": ظرف.` },
  56: { 31: `"draußen herrscht noch Dunkelheit… ___ in der riesigen, hell erleuchteten Halle … wird schon lange gearbeitet": "wird" بعد "in der … Halle": رابط Position 0 يقابل "draußen".`,
    32: `"Er ___ einen Berliner Großmarkt": فاعل "er" + مفعول: فعل مصرّف.`,
    33: `"bis sie auf dem Großmarkt ___": جملة فرعية: الفعل المنفصل "ankommen" في الآخر.`,
    34: `"Die meisten Früchte wurden ___ auf dem Land-, Luft- oder Seeweg … transportiert": بين "wurden" و"auf …": ظرف يعطي تفسير.`,
    35: `"Auf seinem Weg ___ das empfindliche Obst und Gemüse keinesfalls Schaden nehmen": "Schaden nehmen" Infinitiv في الآخر + فاعل مفرد: modal.`,
    36: `"Nichts ist schlimmer ___ verdorbene Ware": بعد "schlimmer" (Komparativ): رابط مقارنة.`,
    37: `"schauen sich die Käufer alles ___ an": بين المفعول و"an": ظرف طريقة.`,
    38: `"…verwachsene Kartoffeln ___ sie dagegen günstiger": الفاعل "sie" بعد الفراغ والمفعول قبلو: فعل مصرّف في الخانة الثانية.`,
    39: `"nicht in Geschäften zum Verkauf angeboten, ___ direkt verarbeitet": بعد "nicht": رابط تصحيح.`,
    40: `"Wenn die Preisverhandlungen erfolgreich ___ sind": "sind" في الآخر: Zustandspassiv يحتاج Partizip II.` },
  57: { 31: `"wie es eine Oberstufenschülerin auf den ___ bringt": "auf den ___ bringen": اسم مذكّر.`,
    32: `"Um genau diese Vorurteile aus der Welt zu ___": "um … zu" يطلب Infinitiv.`,
    33: `"bieten spezielle Veranstaltungen für Schüler ___": الفعل المنفصل "anbieten": الجزء "an" في الآخر.`,
    34: `"noch ___ schulbezogene Veranstaltungen angeboten werden": قبل صفة + اسم جمع Nominativ: صفة بنهاية -e.`,
    35: `"Geht es den teilnehmenden Schulklassen ___, Interessantes … zu erfahren": "es geht um" + zu-Infinitiv: Pronominaladverb.`,
    36: `"Mittel ___ Zweck": اسمين بحرف جرّ مدمج.`,
    37: `"um dem Schulalltag zu ___": "um … zu" + Dativ: Infinitiv يطلب Dativ.`,
    38: `"gar nicht sagen können, ___ das zuvor Gesehene handelt": "handelt" في الآخر: سؤال غير مباشر على موضوع: wo + حرف جرّ.`,
    39: `"Liegt es allein ___ Unwillen der jungen Bevölkerung": "liegen an" + Dativ مذكّر: حرف جرّ مدمج.`,
    40: `"…bei der Auswahl des Programms ___ die Vorlieben der Pädagogen als diejenigen der Schüler zählen": بعد الفراغ مقارنة بـ "als diejenigen": ظرف مقارنة قبل المبتدأ.` },
  58: { 31: `"Schon ___ Ostern ist vielerorts … die Wintersportsaison beendet": بعد "Schon" وقبل اسم زمني: حرف جرّ.`,
    32: `"…das Wetter ___ Jahre als Hinweis … zu betrachten": بعد "Wetter" وقبل "Jahre": Genitiv جمع: نهاية -er.`,
    33: `"nach Ansicht ___ Forscher": "nach Ansicht" + Genitiv جمع: نهاية -er.`,
    34: `"nicht einfach milderes Wetter, ___ vor allem mehr Extreme": بعد "nicht": رابط تصحيح.`,
    35: `"werden die Durchschnittstemperaturen … um wenige bis einige Grad ___": "werden" + Infinitiv في الآخر.`,
    36: `"___ die Gletscher gerade erst schmelzen, entstehen derzeit neue Seen": "schmelzen" في آخر الجزء الأول: جملة فرعية للسبب.`,
    37: `"Schutzbauten errichtet – ___ die Seen sich sturzbachartig entladen": "entladen" في الآخر: جملة فرعية لشرط احتمالي.`,
    38: `"zu weiteren ___ Situationen": بعد "zu weiteren" (Dativ جمع) وقبل اسم: نهاية -en.`,
    39: `"Hütten ___ Risse": فاعل جمع + مفعول: فعل.`,
    40: `"ist sogar eigens mit Beton ___ worden": "worden" في الآخر: Partizip II.` },
  59: { 31: `"Qualität ___ enttäuschend": قبل صفة: ظرف درجة.`,
    32: `"das Fazit, das die Stiftung Warentest … ___": جملة موصولة، فاعل "die Stiftung" مفرد: فعل Präteritum في الآخر.`,
    33: `"Erfahrungen, die wir ___ Beschwerdefällen machen": اسم جمع Dativ: حرف جرّ.`,
    34: `"der Kaufpreis nicht erstattet, ___ es erfolgt nur eine Gutschrift": بعد "nicht": رابط تصحيح.`,
    35: `"nicht einmal in voller ___": بعد "in voller": اسم مؤنّث.`,
    36: `"Ganz ___ davon gilt natürlich deutsches Recht": "Ganz ___ davon": Partizip II في تعبير ثابت.`,
    37: `"wenn sich ausländische Unternehmen … an deutsche Verbraucher ___": جملة "wenn": فعل جمع في الآخر.`,
    38: `"dieses Recht gilt ___ unbefristet": قبل صفة: ظرف تصعيد.`,
    39: `"beim Teleshopping ___ konsequent ihre Rechte durchzusetzen wie …": يتبعو "wie": ظرف مساواة.`,
    40: `"___ hilft die Verbraucherzentrale Sachsen …": "hilft" بعد الفراغ: ظرف في الخانة الأولى.` },
  60: { 31: `"___ Angaben des Statistischen Bundesamtes": قبل اسم جمع + Genitiv: حرف جرّ.`,
    32: `"wird die Bevölkerungszahl … ___ sinken": قبل "sinken": ظرف.`,
    33: `"Die Statistiker ___ damit, dass …": فاعل جمع + "damit": فعل جمع.`,
    34: `"werden ___ dieser Entwicklung vor großen Problemen stehen": بعد الفراغ Genitiv: حرف جرّ للسبب.`,
    35: `"…wird bis 2050 auf 84 … ___": "wird" + Infinitiv في الآخر.`,
    36: `"lassen sich ___ erahnen": قبل "erahnen": ظرف.`,
    37: `"werden sich Politik und Geschäftswelt ___ diesen Personenkreis einstellen": "sich einstellen auf" + Akk.: حرف جرّ.`,
    38: `"Politiker mehr ___ die alten Wähler interessieren werden": "sich interessieren für" + Akk.: حرف جرّ.`,
    39: `"…Rentenversicherungen ___ in den Konsum stecken müssen": بين مجموعتين: حرف جرّ بمعنى بدل.`,
    40: `"Diese Probleme könne man nur ___": "könne" + Infinitiv.` },
  61: { 31: `"…herzustellen, ___ das sich immer weitere Teilnehmer anschließen konnten": "sich anschließen an" + ضمير موصول Akk.: حرف جرّ قبلو.`,
    32: `"war ein elektronischer Postverband ___": "war … geworden": Perfekt مع "werden".`,
    33: `"…ausgebaut ___": Passiv Perfekt: "ist … worden".`,
    34: `"zählten aber ___ nur Universitäten …, ___ auch große Firmen": "nur" جاي بعد الفراغ و"auch" بعد الفاصلة: هذا زوج رابط ثنائي، والفراغ الأول هو الجزء المنفي اللي يفتحو ("nicht nur … sondern auch").`,
    35: `"…nur Universitäten und Forschungseinrichtungen, ___ auch große Firmen": "auch" جاي بعد الفراغ وقبلو جزء منفي ("nicht nur …"): نحتاج رابط ثاني من الزوج يصحّح ويضيف.`,
    36: `"verwandelten sich ___ die Versender": "sich verwandeln in" + Akk.: حرف جرّ.`,
    37: `"___ es gibt auch Stimmen": "gibt" بعد "es": رابط Position 0 للتعارض.`,
    38: `"Stimmen, die Kritik ___ üben, dass …": "Kritik üben an" + dass: Pronominaladverb.`,
    39: `"…die elektronische Post ___ einem Sprachgebrauch geführt hat": "führen zu" + Dativ.`,
    40: `"Man lege keinen Wert mehr ___ den Ausdruck": "Wert legen auf" + Akk.` },
  62: { 31: `"einen teilweise ___ erhöhten Nährstoffbedarf": قبل صفة (Partizip): ظرف درجة.`,
    32: `"keine Auswirkungen ___ das ungeborene Kind": "Auswirkungen auf" + Akk.`,
    33: `"Eier oder Milchprodukte oder sogar ___": آخر الجملة بعد "oder sogar": ضمير جامع.`,
    34: `"den Bedarf der meisten Nährstoffe ___": مفعول + Infinitiv: "Bedarf decken".`,
    35: `"…nicht häufiger als bei Nichtvegetariern ___": "kommen … vor" في الآخر.`,
    36: `"Folat … ___ zum Beispiel in Tomaten, Spinat": فاعل مفرد + "in": فعل.`,
    37: `"ihren Nährstoffstatus regelmäßig ___ zu lassen": قبل "zu lassen": Infinitiv.`,
    38: `"Außerdem kommt es auf die richtige Mischung der Lebensmittel ___": الفعل المنفصل "ankommen": الجزء "an" في الآخر.`,
    39: `"…Brei durch einen vegetarischen … Brei ___": الفعل يرجع للآخر مع "durch": Infinitiv.`,
    40: `"vegetarisch ___ Kinder": بين ظرف و"Kinder": Partizip II كصفة بنهاية -e.` },
  63: { 31: `"simpel und frustrierend ___!": بعد صفتين وفي الآخر: ظرف.`,
    32: `"Sprachhistoriker … sagt ___": "sagen zu" + الاقتباس: Pronominaladverb.`,
    33: `"Woher ___ man denn, was richtig und was falsch ist": "man" بعد الفراغ: فعل مصرّف.`,
    34: `"von Zeit ___ Zeit": الاسم يتكرّر حول حرف جرّ: تعبير ثابت.`,
    35: `"…immer mehr ___ dieses … Social-Media-Deutsch an": "an" في الآخر: "sich anpassen an" + Akk.`,
    36: `"So ___ Kritiker beispielsweise ein verbindliches Regelwerk": فاعل جمع بعد الفراغ: فعل في الخانة الثانية.`,
    37: `"Die Verbindung, die man ___ der eigenen Kultur hat": "Verbindung zu" + Dativ.`,
    38: `"Rüdiger Müllerlein ___ von diesem Anliegen wenig": فاعل مفرد + "von": فعل.`,
    39: `"damit uns die notwendige deutsche Sprache ___ Verfügung stehen": "Verfügung" ما يجي إلا في تعبير ثابت مع "stehen".`,
    40: `"der sich durch ein Regelwerk nicht aufhalten ___": "sich lassen" + Infinitiv: فعل مصرّف في الآخر.` },
  64: { 31: `"___ wollen wir unsere Freizeit … verbringen": "wollen" بعد الفراغ: ظرف ربط.`,
    32: `"___ jener Eigenschaften verändern sich die Präferenzen für Hobbys": بعد الفراغ Genitiv جمع: حرف جرّ (حسب).`,
    33: `"So liegt es zum Beispiel ___, dass …": "liegen nahe" تعبير ثابت: صفة خبر.`,
    34: `"Zu gewissenhaften Menschen ___ am besten Hobbys": "passen zu" + فاعل جمع: فعل جمع.`,
    35: `"Hobbys, die ihre strukturierte Seite ___ lassen": "lassen" + Infinitiv.`,
    36: `"eignen sich ___ Aktivitäten wie Konzerte oder Feste": قبل اسم جمع بدون أداة: صفة بنهاية -e.`,
    37: `"Verträgliche Menschen sind gern ___ engagiert": بين "gern" و"engagiert": ظرف طريقة بدون نهاية.`,
    38: `"…die sich ohne Gesellschaft ___ lassen": "lassen" + Infinitiv.`,
    39: `"ist sie ___ kaum wissenschaftlich untersucht": قبل "kaum": ظرف زمني.`,
    40: `"– ___ von seinen Charaktermerkmalen": "unabhängig von": صفة.` },
};
