// "ليش هذا النوع؟" — overrides (loaded last, so they win over sb2_why_a/b/c): reasons that did not name the word class explicitly
// or did not match the header category. Keyed by the store entry's own position → gap.
export default {
  3: { 40: `"Richtig bergab ___ es mit dem Braunbären": التعبير الثابت "es geht bergab mit …" يحتاج فعل "gehen" مصرّف، والفاعل "es" جاي بعد الفراغ، يعني الفعل في المرتبة الثانية.` },
  9: { 36: `"Die ___ Teilnehmer": بين "Die" واسم جمع نحتاج كلمة كمّية تعطي "الأغلبية": التركيب الثابت "die meisten + اسم جمع".` },
  12: { 34: `"___ den Kundinnen noch den Kunden": "noch" بعد الفراغ دليل على زوج نفي: نحتاج رابط ثنائي "weder … noch".` },
  13: { 34: `"___ den Kundinnen noch den Kunden": "noch" بعد الفراغ دليل على زوج نفي: نحتاج رابط ثنائي "weder … noch".` },
  14: { 39: `"Nur wenn es regnet, ___ sind die Autoschlangen …": بعد جملة "wenn" نحتاج كلمة تفتح الجملة الرئيسية، والفعل "sind" جاي مباشرة بعدها: ظرف ربط (wenn … dann).` },
  23: { 40: `"…bezahlen, ___ durchaus üblich ist": الجملة الفرعية تعلّق على الجملة كاملة (موش على اسم): نحتاج ضمير موصول "was".` },
  30: { 40: `"mit weniger Aufwand ___ gut ein Festmahl zubereiten können wie sie": "gut … wie" يدلّ على مقارنة تساوي: نحتاج ظرف يسبق الصفة ("genauso gut … wie").` },
  39: { 32: `"in der Schule ___ mehr Probleme": قبل "mehr" نحتاج ظرف يعبّر على الزيادة التدريجية ("immer mehr").`,
    33: `"einen neuen Trend, der mit Handschrift zu ___ hat": "hat" في الآخر بعد "zu": التعبير الثابت "mit etwas zu tun haben" يطلب Infinitiv "tun" بعد "zu".` },
  40: { 32: `"in der Schule ___ mehr Probleme": قبل "mehr" نحتاج ظرف يعبّر على الزيادة التدريجية ("immer mehr").`,
    33: `"einen neuen Trend, der mit Handschrift zu ___ hat": "hat" في الآخر بعد "zu": التعبير الثابت "mit etwas zu tun haben" يطلب Infinitiv "tun" بعد "zu".`,
    35: `"Die Verbindung ___ Schrift und Bild": بين اسمين: "Verbindung" يتبعو حرف جرّ ثابت ("Verbindung von … und …").` },
  41: { 32: `"haben mit dem Schreiben in der Schule ___ mehr Probleme": قبل "mehr" نحتاج ظرف يعبّر على الزيادة التدريجية ("immer mehr").`,
    33: `"einen neuen Trend, der mit Handschrift zu ___ hat": "hat" في الآخر بعد "zu": التعبير الثابت "mit etwas zu tun haben" يطلب Infinitiv "tun" بعد "zu".`,
    39: `"Die Verbindung ___ Schrift und Bild": بين اسمين: "Verbindung" يتبعو حرف جرّ ثابت ("Verbindung von … und …").` },
  42: { 38: `"___ umweltschonendes Transportmittel ist der Nachtzug …": قبل اسم بدون أداة نحتاج حرف جرّ يعطي الصفة / الوظيفة: "als" = بصفته.` },
  46: { 34: `"___ folgten die neueren Sprach- und Literaturwissenschaften": "folgten" جاي بعد الفراغ والفعل "folgen" يحتاج إحالة على اللي قبل: Pronominaladverb "darauf".`,
    36: `"Frauen … häufig ___ eine berufliche Karriere verzichteten": "verzichten" يتبعو دايمًا حرف جرّ ثابت: بعد الفراغ Akkusativ، فالحرف هو "auf".` },
  47: { 33: `"…über 130 Personen … ___ Gasthörer eingeschrieben": بعد الفراغ اسم بدون أداة يعطي الصفة اللي سجّلو بيها: حرف جرّ "als".`,
    35: `"Die Gründe dafür ___ sein, dass Frauen …": فاعل جمع + "sein" Infinitiv في الآخر: نحتاج فعل modal مصرّف بصيغة Konjunktiv II (احتمال).` },
  50: { 35: `"herrschte viel Optimismus ___": "herrschte" في المرتبة الثانية وما فماش حاجة في الآخر: الفعل المنفصل "vorherrschen" يحتاج جزءو "vor" في آخر الجملة.` },
  53: { 36: `"fragte, ___ er mir helfen könne": "könne" في الآخر: جملة فرعية لسؤال نعم / لا: نحتاج رابط "ob".` },
  54: { 32: `"kommen … annähernd ___ das deutsche SMS-Fieber heran": "heran" في الآخر: الفعل المنفصل "herankommen" يتبعو حرف جرّ ثابت قبل المفعول Akkusativ: "an".` },
  55: { 32: `"___ lange es den Brauch … gibt, ist jedoch nicht bekannt": "gibt" في الآخر: جملة فرعية لسؤال غير مباشر على المدّة، فنحتاج رابط سؤال + "lange": "wie".` },
  57: { 32: `"Um genau diese Vorurteile aus der Welt zu ___": "um … zu" يطلب Infinitiv: التعبير الثابت "aus der Welt schaffen" فنحتاج الفعل "schaffen".`,
    38: `"gar nicht sagen können, ___ das zuvor Gesehene handelt": "handelt" في الآخر: جملة فرعية لسؤال غير مباشر، و"handeln von" يطلب حرف جرّ: نحتاج Pronominaladverb "wovon".` },
  61: { 39: `"…die elektronische Post ___ einem Sprachgebrauch geführt hat": "führen" يتبعو حرف جرّ ثابت قبل Dativ: "zu".`,
    40: `"Man lege keinen Wert mehr ___ den Ausdruck": التعبير الثابت "Wert legen auf" يطلب حرف جرّ قبل Akkusativ: "auf".` },
  62: { 35: `"…nicht häufiger als bei Nichtvegetariern ___": "kommen" في المرتبة الثانية وفي الآخر نحتاج جزءو المنفصل: "vorkommen" → "vor".` },
  63: { 35: `"…immer mehr ___ dieses … Social-Media-Deutsch an": "an" في آخر الجملة: الفعل المنفصل "sich anpassen" يتبعو حرف جرّ قبل المفعول Akkusativ: "an".` },
};
