/**
 * Shared types for the learning-assistance layer (translation / evidence /
 * explanation / saved vocabulary). Populated by admins via the optional
 * learning_aids JSONB column on lesen_exercises/hoeren_exercises/sb_exercises
 * (see migration 20260810180000_learning_assistance_foundation.sql) — never
 * AI-generated by default. All fields are optional: UI must gracefully hide
 * affordances when a given field is absent.
 */
/** One option in the elimination-reasoning table of the optional strategy
 * card. `key` is the option's own identifier (MC letter "a"/"b"/"c",
 * headline letter "A".."J", or ad letter "A".."L" — whatever the exercise
 * type already uses), so no new identifier scheme is introduced. Scope is
 * proportional to the option pool: for large pools (T1 headlines, T3 ads)
 * only the genuinely plausible distractors need an entry, not all N-1 —
 * explaining why an obviously unrelated option is wrong teaches nothing and
 * clutters the UI; the mandatory Warum? card's evidence already covers the
 * single closest distractor for those cases. */
export interface OptionReasoning {
  key: string;
  label?: string | null;
  correct: boolean;
  reason: string;
}

export interface LearningAidsItem {
  evidence_text?: string | null;
  evidence_translation?: string | null;
  /** Arabic translation of the correct answer itself (the headline / MC
   * option text) — distinct from evidence_translation, which translates the
   * passage sentence that proves it. Optional; the solution view simply
   * omits the translation line when an exercise hasn't been authored yet. */
  answer_translation?: string | null;
  keyword?: string | null;
  explanation_correct?: string | null;
  explanation_wrong?: string | null;
  grammar_structure?: string | null;
  grammar_example?: string | null;
  grammar_translation?: string | null;
  /** The linguistic category of this gap — drives BOTH the "Typ:" label
   * shown to the student AND which fields/tone are appropriate, so a
   * conjunction gets a logic/timing explanation while a preposition gets a
   * case-government explanation instead of one generic template for
   * everything. Supersedes the earlier binary merke_type: "fixed_expression"
   * and "verb_prep" are the two categories genuinely worth memorizing as a
   * chunk (the "هذا تركيب ثابت..." reinforcement line under Merke only shows
   * for those two); the other eight are general patterns that generalize
   * beyond this one sentence, where that reinforcement line would be
   * actively misleading. Unset/null renders no Typ badge and no
   * reinforcement line (safe default — don't claim a classification nobody
   * made). */
  item_type?:
    | "fixed_expression" // Feste Wendung/Struktur: es ist + Adj + zu + Infinitiv, einen Weg finden wie, in Kauf nehmen
    | "verb" // erkranken, bestehen (meaning/form of the verb itself)
    | "verb_prep" // sich freuen auf + Akk, denken an + Akk, warten auf + Akk (Rektion — also memorize-as-chunk)
    | "noun" // gender/case/plural fact about a specific noun
    | "preposition" // mit + Dativ, während + Genitiv (case-governing preposition alone)
    | "conjunction" // wenn, weil, obwohl, zwar...aber, sowohl...als auch — connects clauses/ideas
    | "adjective_adverb" // adjective/adverb choice or declension ending
    | "tense" // Perfekt/Präteritum/Passiv/Konjunktiv II — the tense/mood/voice itself is the point
    | "pronoun" // personal/possessive/relative pronoun, case agreement
    | "pronoun_adverb" // da(r)+preposition: davon, daran, darauf, damit...
    | "grammar_structure" // word order, other sentence-structure patterns not covered above
    | null;
  /** Optional "Wie finde ich die Antwort?" strategy content — a reusable
   * B2 technique, not a repeat of the mandatory evidence/explanation above.
   * All three fields are independently optional; the strategy trigger only
   * renders once at least one is present. */
  /** Schlüsselwörter aus der Frage/Überschrift (German), for the learner to
   * recognize the same idea worded differently in the text. */
  keywords?: string[] | null;
  /** Synonym/paraphrase mapping: how the question/headline's wording maps to
   * the text's actual wording — teaches "compare meaning, not exact words". */
  paraphrase?: { question: string; text: string }[] | null;
  /** Elimination reasoning for the plausible options (see OptionReasoning). */
  options_reasoning?: OptionReasoning[] | null;
}

/** "Typ:" label shown on the Warum card, and whether that category's Merke
 * box gets the "memorize this as a fixed chunk" reinforcement line. */
export const ITEM_TYPE_INFO: Record<NonNullable<LearningAidsItem["item_type"]>, { label: string; reinforceMemorize: boolean }> = {
  fixed_expression: { label: "Feste Struktur", reinforceMemorize: true },
  verb: { label: "Verb", reinforceMemorize: false },
  verb_prep: { label: "Verb + Präposition", reinforceMemorize: true },
  noun: { label: "Nomen", reinforceMemorize: false },
  preposition: { label: "Präposition", reinforceMemorize: false },
  conjunction: { label: "Konnektor", reinforceMemorize: false },
  adjective_adverb: { label: "Adjektiv/Adverb", reinforceMemorize: false },
  tense: { label: "Zeitform", reinforceMemorize: false },
  pronoun: { label: "Pronomen", reinforceMemorize: false },
  pronoun_adverb: { label: "Pronominaladverb", reinforceMemorize: false },
  grammar_structure: { label: "Grammatikstruktur", reinforceMemorize: false },
};

export type Skill = "lesen" | "hoeren" | "sprachbausteine";

export type SavedExpressionCategory =
  | "wort" | "verb" | "feste_verbindung" | "redemittel" | "grammatikstruktur" | "wichtiger_ausdruck";

export const CATEGORY_LABELS: Record<SavedExpressionCategory, string> = {
  wort: "Wort",
  verb: "Verb",
  feste_verbindung: "Feste Verbindung",
  redemittel: "Redemittel",
  grammatikstruktur: "Grammatikstruktur",
  wichtiger_ausdruck: "Wichtiger Ausdruck",
};
