/**
 * Shared types for the learning-assistance layer (translation / evidence /
 * explanation / saved vocabulary). Populated by admins via the optional
 * learning_aids JSONB column on lesen_exercises/hoeren_exercises/sb_exercises
 * (see migration 20260810180000_learning_assistance_foundation.sql) — never
 * AI-generated by default. All fields are optional: UI must gracefully hide
 * affordances when a given field is absent.
 */
/** One option in the elimination-reasoning table of the optional strategy
 * card. `key` is the option's own identifier (MC letter "a"/"b"/"c",
 * headline letter "A".."J", or ad letter "A".."L" — whatever the exercise
 * type already uses), so no new identifier scheme is introduced. Scope is
 * proportional to the option pool: for large pools (T1 headlines, T3 ads)
 * only the genuinely plausible distractors need an entry, not all N-1 —
 * explaining why an obviously unrelated option is wrong teaches nothing and
 * clutters the UI; the mandatory Warum? card's evidence already covers the
 * single closest distractor for those cases. */
export interface OptionReasoning {
  key: string;
  label?: string | null;
  correct: boolean;
  reason: string;
}

export interface LearningAidsItem {
  evidence_text?: string | null;
  evidence_translation?: string | null;
  /** Arabic translation of the correct answer itself (the headline / MC
   * option text) — distinct from evidence_translation, which translates the
   * passage sentence that proves it. Optional; the solution view simply
   * omits the translation line when an exercise hasn't been authored yet. */
  answer_translation?: string | null;
  keyword?: string | null;
  explanation_correct?: string | null;
  explanation_wrong?: string | null;
  grammar_structure?: string | null;
  grammar_example?: string | null;
  grammar_translation?: string | null;
  /** Classifies the MERKE box so the UI knows whether the "memorize fixed
   * expressions" Arabic reinforcement line applies. "grammar" = a general
   * rule (conjunctions, cases, tenses, word order) that generalizes beyond
   * this one sentence — showing a "memorize this fixed phrase" nudge there
   * is actively misleading. "fixed_expression" = a specific collocation
   * (Nomen-Verb-Verbindung, idiom, fixed prep+verb pairing) that genuinely
   * IS worth memorizing as one chunk. Unset/null renders no reinforcement
   * line (safe default — don't claim a classification nobody made). */
  merke_type?: "grammar" | "fixed_expression" | null;
  /** Optional "Wie finde ich die Antwort?" strategy content — a reusable
   * B2 technique, not a repeat of the mandatory evidence/explanation above.
   * All three fields are independently optional; the strategy trigger only
   * renders once at least one is present. */
  /** Schlüsselwörter aus der Frage/Überschrift (German), for the learner to
   * recognize the same idea worded differently in the text. */
  keywords?: string[] | null;
  /** Synonym/paraphrase mapping: how the question/headline's wording maps to
   * the text's actual wording — teaches "compare meaning, not exact words". */
  paraphrase?: { question: string; text: string }[] | null;
  /** Elimination reasoning for the plausible options (see OptionReasoning). */
  options_reasoning?: OptionReasoning[] | null;
}

export type Skill = "lesen" | "hoeren" | "sprachbausteine";

export type SavedExpressionCategory =
  | "wort" | "verb" | "feste_verbindung" | "redemittel" | "grammatikstruktur" | "wichtiger_ausdruck";

export const CATEGORY_LABELS: Record<SavedExpressionCategory, string> = {
  wort: "Wort",
  verb: "Verb",
  feste_verbindung: "Feste Verbindung",
  redemittel: "Redemittel",
  grammatikstruktur: "Grammatikstruktur",
  wichtiger_ausdruck: "Wichtiger Ausdruck",
};
