/**
 * Shared types for the learning-assistance layer (translation / evidence /
 * explanation / saved vocabulary). Populated by admins via the optional
 * learning_aids JSONB column on lesen_exercises/hoeren_exercises/sb_exercises
 * (see migration 20260810180000_learning_assistance_foundation.sql) — never
 * AI-generated by default. All fields are optional: UI must gracefully hide
 * affordances when a given field is absent.
 */
export interface LearningAidsItem {
  evidence_text?: string | null;
  evidence_translation?: string | null;
  keyword?: string | null;
  explanation_correct?: string | null;
  explanation_wrong?: string | null;
  grammar_structure?: string | null;
  grammar_example?: string | null;
  grammar_translation?: string | null;
}

export type Skill = "lesen" | "hoeren" | "sprachbausteine";

export type SavedExpressionCategory =
  | "wort" | "verb" | "feste_verbindung" | "redemittel" | "grammatikstruktur" | "wichtiger_ausdruck";

export const CATEGORY_LABELS: Record<SavedExpressionCategory, string> = {
  wort: "Wort",
  verb: "Verb",
  feste_verbindung: "Feste Verbindung",
  redemittel: "Redemittel",
  grammatikstruktur: "Grammatikstruktur",
  wichtiger_ausdruck: "Wichtiger Ausdruck",
};
